BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (38033121,3,0,279052450,33,2000,1700,6,2,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (38033121, 'Dark Magician Girl', 'This card gains 300 ATK for every "Dark Magician" or "Magician of Black Chaos" in either player''s Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49702428,1,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (49702428, 'Dark Burning Attack', 'If you control a "Dark Magician Girl" monster: Destroy all face-up monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2295831,1,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (2295831, 'Ring of Peace', 'To activate this card, you must draw it for your normal draw in your Draw Phase while your opponent controls 3 or more monsters and you control no cards, reveal it, and keep it revealed until the start of Main Phase 1. At the start of your Main Phase 1 that same turn, you can: Add 1 card from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34710660,1,0,0,33,0,1800,4,32,16,0);
INSERT OR REPLACE INTO "texts" VALUES (34710660, 'Electromagnetic Turtle', 'During your opponent''s Battle Phase: You can banish this card from your Graveyard; end the Battle Phase (this is a Quick Effect). You can only use the effect of "Electromagnetic Turtle" once per Duel.', 'End Battle Phase?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32754886,1,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (32754886, 'Dark Illusion', 'All DARK Spellcaster-Type monsters you currently control with 2000 or more ATK cannot be destroyed by battle, they are unaffected by your opponent''s card effects, also their effects are negated. These changes last until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91152256,3,0,0,17,1400,1200,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (91152256, 'Celtic Guardian', 'An elf who learned to wield a sword, he baffles enemies with lightning-swift attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74677422,3,0,59,17,2400,2000,7,8192,32,0);
INSERT OR REPLACE INTO "texts" VALUES (74677422, 'Red-Eyes B. Dragon', 'A ferocious dragon with a deadly attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49791927,3,0,0,17,1300,1100,4,32768,1,0);
INSERT OR REPLACE INTO "texts" VALUES (49791927, 'Tiger Axe', 'A fast and powerful axe-wielding beast-warrior.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24311372,3,0,0,17,2600,1900,7,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (24311372, 'Zoa', 'A monster whose full potential can be achieved when outfitted with "Metalmorph".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6740720,3,0,0,17,2500,2300,7,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (6740720, 'Seiyaryu', '"A mystical dragon that burns away the unworthy with its mystic flames."', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24433920,3,0,0,17,1750,2000,6,32,32,0);
INSERT OR REPLACE INTO "texts" VALUES (24433920, 'Pendulum Machine', 'A horrible torture machine with a large pendulum blade.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87322377,3,0,0,17,2200,2500,7,32,4,0);
INSERT OR REPLACE INTO "texts" VALUES (87322377, 'Launcher Spider', 'A mechanical spider with rocket launchers capable of random fire.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32012841,3,0,0,17,0,3000,5,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (32012841, 'Millennium Shield', 'A famous shield said to belong to an ancient Egyptian Pharaoh. Legends tell of its power to block any strong attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12829151,3,0,0,17,1400,1400,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (12829151, 'Kanan the Swordmistress', 'A lady warrior armed with sword and shield, she floats lightly and stings sharply.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80304126,3,0,0,33,1600,1800,4,2,16,1114112);
INSERT OR REPLACE INTO "texts" VALUES (80304126, 'Magician''s Valkyria', 'Your opponent cannot select another Spellcaster-Type monster you control as an attack target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64335804,3,0,59,33,2800,2400,8,32,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (64335804, 'Red-Eyes Black Metal Dragon', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your Deck) by Tributing "Red-Eyes B. Dragon" equipped with "Metalmorph".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36354007,3,0,0,33,2800,1400,8,1,16,3);
INSERT OR REPLACE INTO "texts" VALUES (36354007, 'Gilford the Lightning', 'You can Tribute 3 monsters to Tribute Summon this card. If you do, destroy all monsters your opponent controls.', 'Tribute 3 monsters to Tribute Summon this card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42035044,3,0,0,33,2000,1600,4,32768,1,65536);
INSERT OR REPLACE INTO "texts" VALUES (42035044, 'Panther Warrior', 'This card cannot attack unless you Tribute 1 monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52040216,3,0,100,33,2000,2500,7,8192,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (52040216, 'Harpie''s Pet Dragon', 'This card gains 300 ATK and DEF for each "Harpie Lady" on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80316585,3,76812113,9633892,33,1800,1300,4,512,8,0);
INSERT OR REPLACE INTO "texts" VALUES (80316585, 'Cyber Harpie Lady', '(This card''s name is always treated as "Harpie Lady".)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29654737,3,0,4,33,1500,1300,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (29654737, 'Amazoness Chain Master', 'When this card is destroyed by battle and sent to the Graveyard, you can pay 1500 Life Points to look at your opponent''s hand, select 1 Monster Card in it, and add that card to your hand.', '手牌夺取', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50705071,3,0,0,33,3000,2300,8,32,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (50705071, 'Metalzoa', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your Deck) by Tributing "Zoa" equipped with "Metalmorph".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48948935,3,0,0,33,3300,2500,8,8,32,262656);
INSERT OR REPLACE INTO "texts" VALUES (48948935, 'Masked Beast Des Gardius', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by Tributing 2 monsters, including at least 1 "Grand Tiki Elder" or "Melchid the Four-Face Beast". When this card is sent from the field to the Graveyard, equip 1 "The Mask of Remnants" from your Deck to 1 monster on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5640330,3,0,0,33,1400,1800,4,2,32,67108865);
INSERT OR REPLACE INTO "texts" VALUES (5640330, 'Hannibal Necromancer', 'When this card is Normal Summoned, place 1 Spell Counter on it (max. 1). You can remove 1 Spell Counter from this card to destroy 1 face-up Trap Card.', 'Place counter', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45425051,3,0,0,33,2200,1500,6,1024,2,8192);
INSERT OR REPLACE INTO "texts" VALUES (45425051, 'Fairy King Truesdale', 'While this card is in Defense Position, all Plant-Type monsters you control gain 500 ATK and DEF.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16469012,3,0,0,33,2000,1500,5,1,16,65536);
INSERT OR REPLACE INTO "texts" VALUES (16469012, 'Teva', 'When this card is Tribute Summoned successfully, your opponent cannot declare an attack during his/her next turn.', 'Cannot declare attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63749102,3,0,0,33,1800,1900,4,32768,32,24576);
INSERT OR REPLACE INTO "texts" VALUES (63749102, 'Exarion Universe', 'During your Battle Step, if this card attacks a Defense Position monster: You can activate this effect; this card loses exactly 400 ATK, and if it does, it will inflict piercing battle damage to your opponent. These effects last until the End Phase..', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70074904,3,0,0,33,1700,1600,4,1,1,4);
INSERT OR REPLACE INTO "texts" VALUES (70074904, 'D.D. Assailant', 'After damage calculation, when this card is destroyed by battle with an opponent''s monster: Banish that monster, also banish this card.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39180960,3,0,0,2097185,1600,100,3,1024,4,8256);
INSERT OR REPLACE INTO "texts" VALUES (39180960, 'Rigorous Reaver', 'FLIP: Each player discards 1 card. A monster that destroys this card by battle loses 500 ATK and DEF.', 'Discard hand', '攻守下降500', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67959180,3,0,0,33,950,700,3,4,16,134225920);
INSERT OR REPLACE INTO "texts" VALUES (67959180, 'Goddess of Whim', 'Toss a coin and call Heads or Tails. Call it right and this card''s ATK will be doubled during this turn. Call it wrong and it will be halved during this turn.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8131171,3,0,0,33,300,250,1,524288,2,1024);
INSERT OR REPLACE INTO "texts" VALUES (8131171, 'Sinister Serpent', 'You can only use the effect of “Sinister Serpent” once per turn. During your Standby Phase, if this card is in your Graveyard: You can add this card to your hand. During your opponent’s next End Phase, banish 1 “Sinister Serpent” from your Graveyard.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69123138,3,0,0,129,2800,2300,8,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (69123138, 'Zera the Mant', 'This card can only be Ritual Summoned with the Ritual Spell Card, "Zera Ritual".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33951077,3,0,0,129,2300,2100,7,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (33951077, 'Super War-Lion', 'This monster can only be Ritual Summoned with the Ritual Spell Card, "War-Lion Ritual".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62873545,3,0,0,97,5000,5000,12,8192,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (62873545, 'Dragon Master Knight', '"Black Luster Soldier" + "Blue-Eyes Ultimate Dragon"
This monster cannot be Special Summoned except by Fusion Summon. This card gains 500 ATK for each other Dragon-Type monster you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41462083,3,0,0,65,2400,2000,7,8192,8,0);
INSERT OR REPLACE INTO "texts" VALUES (41462083, 'Thousand Dragon', '"Time Wizard" + "Baby Dragon"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3366982,3,0,0,97,1700,1500,5,8192,8,131072);
INSERT OR REPLACE INTO "texts" VALUES (3366982, 'Alligator''s Sword Dragon', '"Baby Dragon" + "Alligator''s Sword"
This card can attack your opponent directly if the only face-up monsters they control are EARTH, WATER, or FIRE.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45231177,3,0,0,65,1800,1600,5,1,4,0);
INSERT OR REPLACE INTO "texts" VALUES (45231177, 'Flame Swordsman', '"Flame Manipulator" + "Masaki the Legendary Swordsman"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83764718,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (83764718, 'Monster Reborn', 'Target 1 monster in either player''s Graveyard; Special Summon it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74137509,3,0,0,65538,0,0,0,0,0,134225920);
INSERT OR REPLACE INTO "texts" VALUES (74137509, 'Graceful Dice', 'Roll a six-sided die. All monsters you currently control gain ATK and DEF equal to the result x 100, until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32268901,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (32268901, 'Salamandra', 'Equip only to a FIRE monster. It gains 700 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13604200,3,0,0,2,0,0,0,0,0,262656);
INSERT OR REPLACE INTO "texts" VALUES (13604200, 'Sage''s Stone', 'Activate only if you control a face-up "Dark Magician Girl". Special Summon 1 "Dark Magician" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63224564,3,0,147,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (63224564, 'Cyber Shield', 'Equip only to "Harpie Lady" or "Harpie Lady Sisters". It gains 500 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29762407,3,0,0,131074,0,0,0,0,0,262152);
INSERT OR REPLACE INTO "texts" VALUES (29762407, 'Temple of the Kings', 'You can only use each effect of “Temple of the Kings” once per turn. You can activate 1 Trap Card you control during the turn it is Set. You can send both this card and 1 face-up “Mystical Beast Serket” to the Graveyard; Special Summon 1 monster from your hand or Deck, or 1 Fusion Monster from your Extra Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22610082,3,0,0,2,0,0,0,0,0,4128);
INSERT OR REPLACE INTO "texts" VALUES (22610082, 'The Mask of Remnants', 'Shuffle this card into its owner''s Deck, OR if this card was put into play by the effect of "Masked Beast Des Gardius", this card is treated as an Equip Card. Control of the equipped monster is switched.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24094653,3,0,70,2,0,0,0,0,0,268697608);
INSERT OR REPLACE INTO "texts" VALUES (24094653, 'Polymerization', 'Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters from your hand or your side of the field as Fusion Materials.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97809599,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (97809599, 'Seal of the Ancients', 'Pay 1000 Life Points. Pick up and see all face-down cards on your opponent''s side of the field, then return them to their original positions. (The effects of the face-down cards are not activated.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18144506,3,0,100,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (18144506, 'Harpie''s Feather Duster', 'Destroy all Spell and Trap Cards your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (126218,3,0,0,4,0,0,0,0,0,134225920);
INSERT OR REPLACE INTO "texts" VALUES (126218, 'Skull Dice', 'Roll a six-sided die. All monsters your opponent currently controls lose ATK and DEF equal to the result x 100, until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96008713,3,0,0,4,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (96008713, 'Magical Arm Shield', 'When your opponent declares an attack while you control a monster: Target 1 face-up monster your opponent controls, except the attacking monster; take control of that target until the end of the Battle Phase, and if you do, it is attacked instead, and you proceed to damage calculation.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37390589,3,0,0,4,0,0,0,0,0,10240);
INSERT OR REPLACE INTO "texts" VALUES (37390589, 'Kunai with Chain', 'Activate 1 or both of these effects (simultaneously).
● When an opponent''s monster declares an attack: Target the attacking monster; change that target to Defense Position.
● Target 1 face-up monster you control; equip this card to that target. It gains 500 ATK.', 'When an opponent''s monster attacks: Target the attacking monster; change that target to Defense Position', 'Target 1 face-up monster you control; equip this card to that target. It gains 500 ATK', 'Activate both effects', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17484499,3,0,0,4,0,0,0,0,0,128);
INSERT OR REPLACE INTO "texts" VALUES (17484499, 'Exchange of the Spirit', 'You can only activate 1 “Exchange of the Spirit” per Duel. If each player has 15 or more cards in their Graveyard: Pay 1000 Life Points; both players swaps cards in their Decks with cards in their Graveyards, then shuffle the Decks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68540058,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (68540058, 'Metalmorph', 'Target 1 face-up monster on the field; equip this card to that target. It gains 300 ATK and DEF. If it attacks, it gains ATK equal to half the ATK of the attack target, during damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79766336,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (79766336, 'Trap of Darkness', 'Activate only by paying 1000 Life Points while you have 3000 Life Points or less. Select a Normal Trap Card in your Graveyard. This card''s effect is the same as that Trap Card''s. Remove from play that Normal Trap Card.', '自分の墓地に存在する通常罠カード１枚を選択してください', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77754944,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (77754944, 'Widespread Ruin', 'Activate only when your opponent declares an attack. Destroy the Attack Position monster your opponent controls with the highest ATK. (If it''s a tie, you get to choose.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59744639,3,0,0,4,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (59744639, 'Windstorm of Etaqua', 'Change the battle positions of all face-up monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95132338,3,0,0,131076,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (95132338, 'Aqua Chorus', 'If there are monsters with the same name on the field, increase the ATK and DEF of all those monsters with the same name by 500 points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57793869,3,0,0,33,-2,-2,10,8,32,8195);
INSERT OR REPLACE INTO "texts" VALUES (57793869, 'The Wicked Eraser', 'This card cannot be Special Summoned. This card cannot be Normal Summoned or Set except by Tributing 3 monsters. The ATK and DEF of this card are each equal to the number of cards your opponent controls × 1000. When this card is destroyed and sent to the Graveyard, destroy all cards on the field. During your Main Phase, you can destroy this card.', '场上的卡全部破坏', 'Self-destruct', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62180201,3,0,0,33,4000,4000,10,8,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (62180201, 'The Wicked Dreadroot', 'This card cannot be Special Summoned. This card cannot be Normal Summoned or Set except by Tributing 3 monsters. Halve the ATK and DEF of all monsters on the field, except this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21208154,3,0,0,33,-2,-2,10,8,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (21208154, 'The Wicked Avatar', 'This card cannot be Special Summoned. This card cannot be Normal Summoned or Set except by Tributing 3 monsters. Your opponent cannot activate Spell or Trap Cards until the end of their 2nd turn after this card is Normal Summoned. The ATK and DEF of this card are each 100 points higher than the highest face-up monster''s ATK on the field (except "The Wicked Avatar").', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
