BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (9287078,1,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (9287078, 'Dark Renewal', 'When your opponent Normal or Special Summons a monster(s): Target 1 of those monsters and 1 Spellcaster-Type monster you control; send those 2 monsters to the Graveyard, then you can Special Summon 1 DARK Spellcaster-Type monster from your Deck or Graveyard.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75347539,3,0,0,33,3500,3850,8,256,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (75347539, 'Valkyrion the Magna Warrior', 'This card cannot be Normal Summoned or Set. This card can only be Special Summoned by Tributing "Alpha The Magnet Warrior", "Beta The Magnet Warrior", and "Gamma The Magnet Warrior" from your hand or your side of the field. You can Tribute this card to Special Summon "Alpha The Magnet Warrior", "Beta The Magnet Warrior", and "Gamma The Magnet Warrior" from your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46986414,3,0,162,17,2500,2100,7,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (46986414, 'Dark Magician', 'The ultimate wizard in terms of attack and defense.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38033121,3,0,279052450,33,2000,1700,6,2,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (38033121, 'Dark Magician Girl', 'This card gains 300 ATK for every "Dark Magician" or "Magician of Black Chaos" in either player''s Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78193831,3,0,0,33,2600,2300,7,1,1,1056768);
INSERT OR REPLACE INTO "texts" VALUES (78193831, 'Buster Blader', 'This card gains 500 ATK for each Dragon-Type monster your opponent controls or is in their Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50287060,3,0,69,33,2200,2500,6,8,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (50287060, 'Archfiend of Gilfer', 'When this card is sent to the Graveyard: You can target 1 face-up monster on the field; equip that target with this card. That monster loses 500 ATK while equipped with this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90876561,3,0,0,17,1900,1000,5,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (90876561, 'Jack''s Knight', 'A strong master swordsman. His loyalty is to justice, his duty to protect the weak.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25652259,3,0,0,17,1500,1600,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (25652259, 'Queen''s Knight', 'This knight catches her opponents off guard, dominating them with swift yet graceful attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64788463,3,0,0,33,1600,1400,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (64788463, 'King''s Knight', 'When this card is Normal Summoned while you control "Queen''s Knight": You can Special Summon 1 "Jack''s Knight" from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77207191,3,0,0,33,1400,1800,5,8,32,512);
INSERT OR REPLACE INTO "texts" VALUES (77207191, 'Berfomet', 'When this card is Normal or Flip Summoned, you can add 1 "Gazelle the King of Mythical Beasts" from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5818798,3,0,27,17,1500,1200,4,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (5818798, 'Gazelle the King of Mythical Beasts', 'This monster moves so fast that it looks like an illusion to mortal eyes.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99785935,3,0,0,17,1400,1700,4,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (99785935, 'Alpha the Magnet Warrior', 'Alpha, Beta, and Gamma meld as one to form a powerful monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39256679,3,0,0,17,1700,1600,4,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (39256679, 'Beta the Magnet Warrior', 'Alpha, Beta, and Gamma meld as one to form a powerful monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11549357,3,0,0,17,1500,1800,4,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (11549357, 'Gamma the Magnet Warrior', 'Alpha, Beta, and Gamma meld as one to form a powerful monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65240384,3,0,0,33,100,2600,4,1,1,-2113927168);
INSERT OR REPLACE INTO "texts" VALUES (65240384, 'Big Shield Gardna', 'During either player''s turn, when this face-down card (and no other cards) is targeted by a Spell Card: Change this card to face-up Defense Position, and if you do, negate the Spell Card''s activation. If this card is attacked, change it to Attack Position at the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40640057,3,0,0,33,300,200,1,8,32,8);
INSERT OR REPLACE INTO "texts" VALUES (40640057, 'Kuriboh', 'uring your opponent''s turn, at damage calculation: You can discard this card; you take no battle damage from that battle (this is a Quick Effect).', 'Reduce damage to 0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83764718,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (83764718, 'Monster Reborn', 'Target 1 monster in either player''s Graveyard; Special Summon it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72302403,3,0,0,2,0,0,0,0,0,67584);
INSERT OR REPLACE INTO "texts" VALUES (72302403, 'Swords of Revealing Light', 'Flip all monsters your opponent controls face-up. This card remains on the field for 3 of your opponent''s turns. While this card is face-up on the field, monsters your opponent controls cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99789342,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (99789342, 'Dark Magic Curtain', 'If you activate this card, you cannot Normal Summon, Flip Summon or Special Summon this turn. Pay half your Life Points to Special Summon 1 "Dark Magician" from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63391643,3,0,0,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (63391643, 'Thousand Knives', 'Activate only while you control a face-up "Dark Magician". Destroy one monster your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67227834,3,0,0,262146,0,0,0,0,0,8396800);
INSERT OR REPLACE INTO "texts" VALUES (67227834, 'Magic Formula', 'Equip only to "Dark Magician" or "Dark Magician Girl". The equipped monster gains 700 ATK. When this card is sent from the field to the Graveyard, gain 1000 Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28553439,3,0,0,65538,0,0,0,0,0,1310722);
INSERT OR REPLACE INTO "texts" VALUES (28553439, 'Magical Dimension', 'If you control a face-up Spellcaster-Type monster: Target 1 monster you control; Tribute it, then Special Summon 1 Spellcaster-Type monster from your hand, then you can destroy 1 monster on the field.', 'Destroy 1 monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87880531,3,0,0,2,0,0,0,0,0,32768);
INSERT OR REPLACE INTO "texts" VALUES (87880531, 'Diffusion Wave-Motion', 'Pay 1000 Life Points. Select 1 Level 7 or higher Spellcaster-Type monster on your side of the field. During this turn, only the selected monster can attack and it attacks all monsters on your opponent''s side of the field once each. The effects of Effect Monsters destroyed by this attack(s) are not activated.', '相手モンスター全てに１回ずつ攻撃', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24096228,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (24096228, 'Double Spell', 'Discard 1 Spell Card from your hand. Select 1 Spell Card from your opponent''s Graveyard and use it from the Graveyard as your Spell Card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97342942,3,0,0,131074,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (97342942, 'Ectoplasmer', 'Once during each player''s End Phase, the turn player Tributes 1 face-up monster on their side of the field and inflicts damage to the opponent equal to half of the original ATK of the Tributed monster.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81510157,3,0,0,2,0,0,0,0,0,8388610);
INSERT OR REPLACE INTO "texts" VALUES (81510157, 'Soul Taker', 'Destroy 1 face-up monster your opponent controls. Then, your opponent gains 1000 Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55144522,3,0,0,2,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (55144522, 'Pot of Greed', 'Draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72892473,3,0,0,2,0,0,0,0,0,328);
INSERT OR REPLACE INTO "texts" VALUES (72892473, 'Card Destruction', 'Each player discards their entire hand, then draws the same number of cards they discarded.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5556668,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (5556668, 'Exchange', 'Both players reveal their hands and add 1 card from each other''s hand to their hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93108433,3,0,0,65538,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (93108433, 'Monster Recovery', 'Unite 1 of your own monsters on your side of the field and your hand with your Deck and then shuffle it. Draw the same number of cards that were in your hand from the Deck. (You cannot activate this card if you have your opponent''s card in your hand.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24094653,3,0,70,2,0,0,0,0,0,268697608);
INSERT OR REPLACE INTO "texts" VALUES (24094653, 'Polymerization', 'Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters from your hand or your side of the field as Fusion Materials.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95286165,3,0,70,65538,0,0,0,0,0,262176);
INSERT OR REPLACE INTO "texts" VALUES (95286165, 'De-Fusion', 'Select 1 face-up Fusion Monster on the field and return it to the Extra Deck. If all the Fusion Material Monsters that were used for the Fusion Summon of that Fusion Monster are in your Graveyard, you can Special Summon them.', 'Special Summon Fusion Material Monsters?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40703222,3,0,0,65538,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (40703222, 'Multiply', 'Tribute 1 face-up "Kuriboh". Special Summon as many "Kuriboh Token" (Fiend-Type/DARK/Level 1/ATK 300/DEF 200) as possible in Defense Position. These Tokens cannot be Tributed for a Tribute Summon.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44095762,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (44095762, 'Mirror Force', 'When an opponent''s monster declares an attack: Destroy all Attack Position monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81210420,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (81210420, 'Magical Hats', 'Activate only during your opponent''s Battle Phase. Select 2 non-Monster Cards from your Deck and 1 monster you control. Shuffle those 3 cards and Set them on the field in face-down Defense Position. The 2 cards selected from your Deck are treated as monsters (ATK 0/DEF 0) and are destroyed at the end of the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62279055,3,0,0,4,0,0,0,0,0,4259840);
INSERT OR REPLACE INTO "texts" VALUES (62279055, 'Magic Cylinder', 'When an opponent''s monster declares an attack: Target the attacking monster; negate the attack, and if you do, inflict damage to your opponent equal to its ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18807108,3,0,0,131076,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (18807108, 'Spellbinding Circle', 'Select 1 monster. It cannot attack or change its Battle position. When that monster is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49587034,3,0,0,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (49587034, 'Lightforce Sword', 'Select 1 random card from your opponent''s hand and remove it from play face-down. During your opponent''s 4th Standby Phase after this card''s activation, return that card to their hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1248895,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (1248895, 'Chain Destruction', 'When a monster(s) with 2000 or less ATK is Summoned: Target 1 of them; destroy all cards with that name in its controller''s hand and Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37383714,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (37383714, 'Soul Rope', 'When a monster you control is destroyed and sent to the Graveyard (except during the Damage Step): Pay 1000 Life Points; Special Summon 1 Level 4 monster from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35686187,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (35686187, 'Tragedy', 'Activate only when a monster on your opponent''s side of the field in face-up Attack Position is changed to face-up Defense Position. Destroy all Defense Position monsters on your opponent''s side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4796100,3,0,27,97,2100,1800,6,16384,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (4796100, 'Chimera the Flying Mythical Beast', '"Gazelle the King of Mythical Beasts" + "Berfomet"
(This monster is always treated as a "Phantom Beast" monster.) When this card is destroyed, you can select and Special Summon either "Berfomet" or "Gazelle the King of Mythical Beasts" from your Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
