BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (48094997,3,0,0,17,1000,2100,4,32,4,0);
INSERT OR REPLACE INTO "texts" VALUES (48094997, 'Battle Footballer', 'A cyborg with high defense power. Originally it was invented for a football machine.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5464695,3,0,0,17,1850,0,4,128,4,0);
INSERT OR REPLACE INTO "texts" VALUES (5464695, 'Blazing Inpachi', 'A wicked wooden spirit now burning in flames. Its fire attack is powerful, but it will soon be nothing but ashes.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74093656,3,0,0,4113,1600,200,3,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (74093656, 'Tune Warrior', 'The warrior''s antenna can attune it to any energy wave. It can monitor transmissions from miles away but always suffers from bad reception.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (255998,3,0,0,33,1200,200,4,1,8,131072);
INSERT OR REPLACE INTO "texts" VALUES (255998, 'Rapid Warrior', 'During your Main Phase 1, you can activate this card''s effect. If you do, it can attack your opponent directly this turn. Other monsters cannot attack during the turn you activate this effect.', 'Direct attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36643046,3,0,23,33,0,700,2,32,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (36643046, 'Synchron Explorer', 'When this card is Normal Summoned, you can select 1 "Synchron" monster in your Graveyard and Special Summon it. Its effects are negated.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54652250,3,0,0,2097185,450,600,2,2048,1,2);
INSERT OR REPLACE INTO "texts" VALUES (54652250, 'Man-Eater Bug', 'FLIP: Select and destroy 1 monster on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21015833,3,0,0,33,1000,700,3,1,1,32768);
INSERT OR REPLACE INTO "texts" VALUES (21015833, 'Hayabusa Knight', 'This card can make a second attack during each Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77252217,3,0,0,33,2400,0,4,2048,1,256);
INSERT OR REPLACE INTO "texts" VALUES (77252217, 'Chainsaw Insect', 'At the end of the Damage Step, if this card attacked or was attacked: Your opponent draws 1 card.', '对方抽1张卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88650530,3,0,62,2097185,300,200,1,524288,16,1);
INSERT OR REPLACE INTO "texts" VALUES (88650530, 'Worm Apocalypse', 'FLIP: Target 1 Spell/Trap Card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63977008,3,0,4390935,4129,1300,500,3,1,32,-2147221504);
INSERT OR REPLACE INTO "texts" VALUES (63977008, 'Junk Synchron', 'When this card is Normal Summoned, you can select 1 Level 2 or lower monster from your Graveyard, and Special Summon it in face-up Defense Position. That monster''s effect(s) is negated.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9365703,3,0,0,33,900,400,2,1,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (9365703, 'Speed Warrior', 'During the Battle Phase of the turn you Normal Summon this card, you can double its original ATK until the end of the Battle Phase.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23571046,3,0,0,33,800,800,2,32,1,262148);
INSERT OR REPLACE INTO "texts" VALUES (23571046, 'Quillbolt Hedgehog', 'If you control a face-up Tuner monster: You can Special Summon this card from your Graveyard. If this card was Summoned this way, banish it when it leaves the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50604950,3,0,4109,33,1800,800,4,1,1,73736);
INSERT OR REPLACE INTO "texts" VALUES (50604950, 'X-Saber Galahad', 'If this card attacks an opponent''s monster, this card gains 300 ATK during the Damage Step only. If this card is attacked by an opponent''s monster, this card loses 500 ATK during the Damage Step only. When this card is selected as an attack target, you can Tribute another "Saber" monster to negate the attack.', 'Negate attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66288028,3,0,0,33,600,1200,2,1,1,16777216);
INSERT OR REPLACE INTO "texts" VALUES (66288028, 'Fortress Warrior', 'You take no battle damage from attacks involving this card. Once per turn, this card cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88559132,3,0,0,33,1200,2000,5,1,1,1318912);
INSERT OR REPLACE INTO "texts" VALUES (88559132, 'Turret Warrior', 'You can Tribute 1 Warrior-Type monster to Special Summon this card from your hand. If you do, it gains ATK equal to the Tributed monster''s original ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40225398,3,0,0,33,1600,1000,4,1,32,49152);
INSERT OR REPLACE INTO "texts" VALUES (40225398, 'Twin-Sword Marauder', 'Once per Battle Phase, if this card attacks a Defense Position monster, it can make a second attack in a row. If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent.', 'Attack again?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76614003,3,0,0,4129,1000,1300,2,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (76614003, 'Dark Tinker', 'When this card you control is sent to the Graveyard, look at the top card of your Deck. Return that card to either the top or the bottom of the Deck.', 'Confirm', 'Return to the top of the deck', 'Return to the bottom of the deck', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20932152,3,0,23,4129,700,1400,5,32,8,537133056);
INSERT OR REPLACE INTO "texts" VALUES (20932152, 'Quickdraw Synchron', 'You can send 1 monster from your hand to the Graveyard and Special Summon this card (from your hand). For a Synchro Summon, you can substitute this card for any 1 "Synchron" Tuner monster. This card cannot be used as a Synchro Material Monster, except for the Synchro Summon of a monster that lists a "Synchron" monster as a Tuner.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73048641,3,0,0,65538,0,0,0,0,0,16785408);
INSERT OR REPLACE INTO "texts" VALUES (73048641, 'Half Shut', 'Target 1 face-up monster on the field; it cannot be destroyed by battle this turn, but its ATK is halved until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42703248,3,0,0,2,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (42703248, 'Giant Trunade', 'Return all Spell and Trap Cards on the field to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72892473,3,0,0,2,0,0,0,0,0,328);
INSERT OR REPLACE INTO "texts" VALUES (72892473, 'Card Destruction', 'Each player discards their entire hand, then draws the same number of cards they discarded.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32807846,3,0,0,2,0,0,0,0,0,1049088);
INSERT OR REPLACE INTO "texts" VALUES (32807846, 'Reinforcement of the Army', 'Add 1 Level 4 or lower Warrior-Type monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95281259,3,0,0,2,0,0,0,0,0,1049600);
INSERT OR REPLACE INTO "texts" VALUES (95281259, 'The Warrior Returning Alive', 'Target 1 Warrior-Type monster in your Graveyard; add that target to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10012614,3,0,0,131074,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (10012614, 'Banner of Courage', 'During your Battle Phase only, all face-up monsters you control gain 200 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98045062,3,0,0,65538,0,0,0,0,0,6144);
INSERT OR REPLACE INTO "texts" VALUES (98045062, 'Enemy Controller', 'Activate 1 of these effects.
● Target 1 face-up monster your opponent controls; change that target''s battle position.
● Tribute 1 monster, then target 1 face-up monster your opponent controls; take control of that target until the End Phase.', 'Change the Battle Position of 1 face-up monster your opponent controls', 'Tribute 1 monster. Select 1 face-up monster your opponent controls. Take control of it until the End Phase', 'Select effect', 'Select effect', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26412047,3,0,0,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (26412047, 'Hammer Shot', 'Destroy 1 face-up Attack Position monster with the highest ATK. (If it is a tie, you get to choose.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74848038,3,0,0,2,0,0,0,0,0,1048);
INSERT OR REPLACE INTO "texts" VALUES (74848038, 'Monster Reincarnation', 'Discard 1 card, then target 1 monster in your Graveyard; add it to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98143165,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (98143165, 'Synchro Boost', 'The equipped monster gains 500 ATK, and its Level is increased by 1.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47766694,3,0,0,4,0,0,0,0,0,3);
INSERT OR REPLACE INTO "texts" VALUES (47766694, 'Wild Tornado', 'Select 1 face-up card in the Spell & Trap Card Zones and destroy it. The controller of the destroyed card can then Set 1 Spell or Trap Card from their hand. If this Set card is destroyed and sent to the Graveyard, select and destroy 1 face-up card on the field.', 'Set 1 Card?', 'Destroy 1 face-up card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4206964,3,0,8978508,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (4206964, 'Trap Hole', 'When your opponent Normal or Flip Summons 1 monster with 1000 or more ATK: Target that monster; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60082869,3,0,0,4,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (60082869, 'Dust Tornado', 'Target 1 Spell/Trap Card your opponent controls; destroy that target, then you can Set 1 Spell/Trap Card from your hand.', 'Set 1 Card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4178474,3,0,0,4,0,0,0,0,0,3);
INSERT OR REPLACE INTO "texts" VALUES (4178474, 'Raigeki Break', 'Discard 1 card, then target 1 card on the field; destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93382620,3,0,0,4,0,0,0,0,0,270336);
INSERT OR REPLACE INTO "texts" VALUES (93382620, 'Rope of Life', 'When a monster(s) is destroyed by battle and sent to your Graveyard: Discard your entire hand (min.1), then target 1 of those monsters; Special Summon it, and if you do, it gains 800 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27053506,3,0,0,4,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (27053506, 'Secret Barrel', 'Inflict damage to your opponent equal to the total number of cards on your opponent''s side of the field and in your opponent''s hand x 200.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56120475,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (56120475, 'Sakuretsu Armor', 'When an opponent''s monster declares an attack: Target the attacking monster; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36361633,3,0,0,4,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (36361633, 'Threatening Roar', 'Your opponent cannot declare an attack this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78211862,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (78211862, 'Rising Energy', 'Discard 1 card, then target 1 face-up monster on the field; that target gains 1500 ATK until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24268052,3,0,0,4,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (24268052, 'Defense Draw', 'Activate only during damage calculation during your opponent''s turn. The Battle Damage you would receive becomes 0. Draw 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74860293,3,0,4391168,8225,2600,2500,8,1,1,3);
INSERT OR REPLACE INTO "texts" VALUES (74860293, 'Junk Destroyer', '"Junk Synchron" + 1 or more non-Tuner monsters
When this card is Synchro Summoned: You can target cards on the field, up to the number of non-Tuner monsters used as Synchro Material Monsters for this card; destroy the target(s).', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80108118,3,0,4109,8225,2200,1300,7,1,1,96);
INSERT OR REPLACE INTO "texts" VALUES (80108118, 'X-Saber Urbellum', '1 Tuner + 1 or more non-Tuner monsters
When this card inflicts Battle Damage to your opponent while they have 4 or more cards in their hand, place 1 random card from their hand on top of their Deck.', 'Return to deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97204936,3,0,0,8193,2600,800,6,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (97204936, 'Gaia Knight, the Force of Earth', '1 Tuner + 1 or more non-Tuner monsters', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83810690,3,0,4109,8225,2100,400,5,1,1,1310720);
INSERT OR REPLACE INTO "texts" VALUES (83810690, 'X-Saber Wayne', '1 Tuner + 1 or more non-Tuner monsters
When this card is Synchro Summoned, you can Special Summon 1 Level 4 or lower Warrior-Type monster from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
