BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (11091375,3,0,0,17,1900,1600,4,8192,8,0);
INSERT OR REPLACE INTO "texts" VALUES (11091375, 'Luster Dragon', 'A very beautiful dragon covered with sapphire. It does not like fights, but has incredibly high attack power.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69247929,3,0,0,17,2000,100,4,32768,1,0);
INSERT OR REPLACE INTO "texts" VALUES (69247929, 'Gene-Warped Warwolf', 'This warwolf was given incalculable strength through horrific genetic manipulation. Its gentle nature was completely wiped out, and it now lives only to unleash destruction.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6631034,3,0,0,17,2600,1700,6,65536,2,0);
INSERT OR REPLACE INTO "texts" VALUES (6631034, 'Frostosaurus', 'This monster''s metabolism enables it to endure long periods of cold, harnessing the power to become a creature of solid ice! Nothing else can withstand such temperatures, especially victims of its glacial rampage.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43096270,3,0,0,17,2000,100,4,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (43096270, 'Alexandrite Dragon', 'Many of the czars'' lost jewels can be found in the scales of this priceless dragon. Its creator remains a mystery, along with how they acquired the imperial treasures. But whosoever finds this dragon has hit the jackpot... whether they know it or not.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31560081,3,0,0,2097185,300,400,1,2,16,1024);
INSERT OR REPLACE INTO "texts" VALUES (31560081, 'Magician of Faith', 'FLIP: Target 1 Spell Card in your Graveyard; add that target to your hand.', 'Spell recovery', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93013676,3,0,0,33,1550,1400,4,2,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (93013676, 'Maha Vailo', 'This card gains 500 ATK for each Equip Card equipped to this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34124316,3,0,147,2097185,900,900,3,256,32,262402);
INSERT OR REPLACE INTO "texts" VALUES (34124316, 'Cyber Jar', 'FLIP: Destroy all monsters on the field, then both players reveal the top 5 cards from their Decks, then Special Summon all revealed Level 4 or lower monsters in face-up Attack Position or face-down Defense Position, also add any remaining cards to their hand. (If either player has less than 5 cards in their Deck, reveal as many as possible.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78658564,3,0,172,33,2300,0,4,1,1,2048);
INSERT OR REPLACE INTO "texts" VALUES (78658564, 'Goblin Attack Force', 'If this card attacks, it is changed to Defense Position at the end of the Battle Phase, and its battle position cannot be changed until the End Phase of your next turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66362965,3,0,147,33,2200,1200,6,1,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (66362965, 'The Fiend Megacyber', 'If your opponent controls at least 2 more monsters than you do, you can Special Summon this card (from your hand).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31709826,3,0,0,33,1500,500,4,64,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (31709826, 'Revival Jam', 'When this card is destroyed by battle and sent to the Graveyard: You can pay 1000 Life Points; Special Summon it in face-up Defense Position during your next turn''s Standby Phase.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88240808,3,0,0,33,1800,700,4,2,32,4);
INSERT OR REPLACE INTO "texts" VALUES (88240808, 'Kycoo the Ghost Destroyer', 'When this card inflicts battle damage to your opponent: You can target up to 2 monsters in their Graveyard; banish those targets. Your opponent cannot banish cards from either player''s Graveyard.', 'Select up to 2 monsters to banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40133511,3,0,0,33,1600,900,4,16384,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (40133511, 'Bazoo the Soul-Eater', 'Once per turn: You can banish up to 3 monsters from your Graveyard; this card gains 300 ATK for each, until the end of your opponent''s turn.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45894482,3,0,0,33,1400,400,3,65536,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (45894482, 'Gilasaurus', 'You can Special Summon this card (from your hand). When you do: Your opponent can target 1 monster in their Graveyard; your opponent Special Summons that target to their side of the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88472456,3,0,0,33,2100,500,4,1,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (88472456, 'Zombyra the Dark', 'This card cannot attack your opponent directly. If this card destroys a monster by battle: This card loses 200 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8131171,3,0,0,33,300,250,1,524288,2,1024);
INSERT OR REPLACE INTO "texts" VALUES (8131171, 'Sinister Serpent', 'You can only use the effect of “Sinister Serpent” once per turn. During your Standby Phase, if this card is in your Graveyard: You can add this card to your hand. During your opponent’s next End Phase, banish 1 “Sinister Serpent” from your Graveyard.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18036057,3,0,0,33,1900,1400,5,4,16,16640);
INSERT OR REPLACE INTO "texts" VALUES (18036057, 'Airknight Parshath', 'If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. When this card inflicts battle damage to your opponent: Draw 1 card.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43586926,3,0,0,33,1500,1200,3,8192,8,270336);
INSERT OR REPLACE INTO "texts" VALUES (43586926, 'Twin-Headed Behemoth', 'During the End Phase, if this card was destroyed on the field and sent to the Graveyard this turn: Special Summon it from the Graveyard, and make its ATK and DEF 1000. You can only use the effect of "Twin-Headed Behemoth" once per Duel.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79575620,3,0,0,33,400,1500,3,2,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (79575620, 'Injection Fairy Lily', 'If this card attacks or is attacked, during damage calculation (in either player''s turn): You can pay 2000 Life Points once per battle; this card gains 3000 ATK during that damage calculation only.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47025270,3,0,0,33,1600,0,4,32,16,288);
INSERT OR REPLACE INTO "texts" VALUES (47025270, 'Helping Robo for Combat', 'When this card destroys an opponent''s monster by battle: Draw 1 card, then return 1 card from your hand to the bottom of the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90790253,3,0,0,33,1400,1800,4,1,8,2048);
INSERT OR REPLACE INTO "texts" VALUES (90790253, 'Little-Winguard', 'Once per turn, during your End Phase: You can change the battle position of this card.', '表示形式を変更', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7572887,3,0,0,33,1500,1600,4,1,16,4);
INSERT OR REPLACE INTO "texts" VALUES (7572887, 'D.D. Warrior Lady', 'After damage calculation, when this card battles an opponent''s monster: You can banish that monster, also banish this card.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16268841,3,0,0,33,1700,1200,4,4,1,8388608);
INSERT OR REPLACE INTO "texts" VALUES (16268841, 'Zolga', 'When a monster is Tribute Summoned by Tributing this card: The owner of this card gains 2000 Life Points.', 'Gain LP', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40737112,3,0,162,33,2800,2600,8,2,32,1044);
INSERT OR REPLACE INTO "texts" VALUES (40737112, 'Dark Magician of Chaos', 'During the End Phase, if this card was Normal or Special Summoned this turn: You can target 1 Spell Card in your Graveyard; add it to your hand. You can only use this effect of "Dark Magician of Chaos" once per turn. At the end of the Damage Calculations, if this card destroyed an opponent’s monster by battle: Banish that monster. If this card would leave the field, banish it instead.', 'Spell recovery', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2671330,3,0,0,33,1500,1200,4,65536,1,16);
INSERT OR REPLACE INTO "texts" VALUES (2671330, 'Hyper Hammerhead', 'At the end of the Damage Step, if an opponent''s monster that battled this card is not destroyed: Return that opponent''s monster to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22609617,3,0,0,33,1300,800,3,1,32,36864);
INSERT OR REPLACE INTO "texts" VALUES (22609617, 'Mataza the Zapper', 'This card can make a second attack during each Battle Phase. Control of this face-up card on the field cannot switch.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68007326,3,0,82,33,2800,2000,7,4,16,8388608);
INSERT OR REPLACE INTO "texts" VALUES (68007326, 'Guardian Angel Joan', 'When this card destroys a monster by battle and sends it to the Graveyard: Gain Life Points equal to the original ATK of that destroyed monster in the Graveyard.', 'LP回复', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78636495,3,0,0,2097185,1900,400,4,8,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (78636495, 'Slate Warrior', 'FLIP: This card gains 500 ATK and DEF.
If this card is destroyed by battle: The monster that destroyed it loses 500 ATK and DEF.', 'Gain 500 ATK and DEF', 'Lose 500 ATK and DEF', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70074904,3,0,0,33,1700,1600,4,1,1,4);
INSERT OR REPLACE INTO "texts" VALUES (70074904, 'D.D. Assailant', 'After damage calculation, when this card is destroyed by battle with an opponent''s monster: Banish that monster, also banish this card.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4041838,3,0,43,33,1800,1000,4,1,16,2);
INSERT OR REPLACE INTO "texts" VALUES (4041838, 'Ninja Grandmaster Sasuke', 'At the start of the Damage Step, if this card attacks a face-up Defense Position monster: Destroy that monster.', 'Destroy Defense Position monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88975532,3,0,0,33,1600,600,4,32768,32,0);
INSERT OR REPLACE INTO "texts" VALUES (88975532, 'Pitch-Black Warwolf', 'Your opponent cannot activate Trap Cards during the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15960641,3,0,0,33,1600,600,4,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (15960641, 'Mirage Dragon', 'Your opponent cannot activate Trap Cards during the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65240384,3,0,0,33,100,2600,4,1,1,-2113927168);
INSERT OR REPLACE INTO "texts" VALUES (65240384, 'Big Shield Gardna', 'During either player''s turn, when this face-down card (and no other cards) is targeted by a Spell Card: Change this card to face-up Defense Position, and if you do, negate the Spell Card''s activation. If this card is attacked, change it to Attack Position at the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42386471,3,0,98,4194337,1900,900,4,2,1,131136);
INSERT OR REPLACE INTO "texts" VALUES (42386471, 'Toon Gemini Elf', 'This card cannot attack the turn it is Summoned. If "Toon World" on the field is destroyed, destroy this card. While you control "Toon World" and your opponent controls no Toon Monsters, this card can attack your opponent directly. When this card inflicts battle damage to your opponent: Discard 1 random card from your opponent''s hand.', 'Discard hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16956455,3,0,0,33,1800,1000,4,32768,1,1);
INSERT OR REPLACE INTO "texts" VALUES (16956455, 'Chiron the Mage', 'Once per turn: You can discard 1 Spell Card, then target 1 Spell/Trap Card your opponent controls; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83104731,3,0,7,33,3000,3000,8,32,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (83104731, 'Ancient Gear Golem', 'Cannot be Special Summoned. If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. If this card attacks, your opponent cannot activate any Spell/Trap Cards until the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18325492,3,0,22,33,1000,1000,3,32,8,16777216);
INSERT OR REPLACE INTO "texts" VALUES (18325492, 'Gyroid', 'Once per turn, this card cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44729197,3,0,22,33,1800,1800,4,32,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (44729197, 'Steamroid', 'If this card attacks an opponent''s monster, this card gains 500 ATK during the Damage Step only. If this card is attacked by an opponent''s monster, this card loses 500 ATK during the Damage Step only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71218746,3,0,22,33,1600,1600,4,32,1,2);
INSERT OR REPLACE INTO "texts" VALUES (71218746, 'Drillroid', 'Before damage calculation, if this card attacks a Defense Position monster: Destroy that monster.', '破坏守备怪物', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70095154,3,0,278069507,33,2100,1600,5,32,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (70095154, 'Cyber Dragon', 'If your opponent controls a monster and you control no monsters, you can Special Summon this card (from your hand).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85306040,3,0,172,33,2200,1500,4,8,1,2048);
INSERT OR REPLACE INTO "texts" VALUES (85306040, 'Goblin Elite Attack Force', 'If this card attacks, it is changed to Defense Position at the end of the Battle Phase, and its battle position cannot be changed until the end of your next turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63749102,3,0,0,33,1800,1900,4,32768,32,24576);
INSERT OR REPLACE INTO "texts" VALUES (63749102, 'Exarion Universe', 'During your Battle Step, if this card attacks a Defense Position monster: You can activate this effect; this card loses exactly 400 ATK, and if it does, it will inflict piercing battle damage to your opponent. These effects last until the End Phase..', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55424270,3,0,110,33,1400,1400,4,2,16,67117056);
INSERT OR REPLACE INTO "texts" VALUES (55424270, 'Mythical Beast Cerberus', 'Each time a Spell Card is activated, place 1 Spell Counter on this card when that Spell Card resolves. This card gains 500 ATK for each Spell Counter on it. If damage calculation is conducted involving this card, remove all Spell Counters from it at the end of the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12538374,3,0,18,33,100,100,1,64,2,263168);
INSERT OR REPLACE INTO "texts" VALUES (12538374, 'Treeborn Frog', 'During your Standby Phase, if this card is in your Graveyard and you do not control a "Treeborn Frog": You can Special Summon this card. You must control no Spell/Trap Cards to activate and to resolve this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99861526,3,0,22,33,800,1800,4,32,2,133120);
INSERT OR REPLACE INTO "texts" VALUES (99861526, 'Submarineroid', 'This card can attack your opponent directly, but when it does so using this effect, the battle damage inflicted to your opponent is the original ATK of this card. At the end of the Damage Step, if this card attacked or was attacked: You can change this card to Defense Position.', 'Change to defense position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15894048,3,0,0,33,3000,2200,8,65536,1,0);
INSERT OR REPLACE INTO "texts" VALUES (15894048, 'Ultimate Tyranno', 'If this card is in face-up Attack Position at the beginning of your Battle Phase, it must attack first, and attack all monsters your opponent controls once each.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85520851,3,0,0,33,3300,1400,8,65536,16,4194304);
INSERT OR REPLACE INTO "texts" VALUES (85520851, 'Super Conductor Tyranno', 'Once per turn: You can Tribute 1 monster; inflict 1000 damage to your opponent. This card cannot declare an attack the turn you activate this effect.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81919143,3,0,0,33,2400,1500,7,2048,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (81919143, 'Brain Crusher', 'Once per turn, during the End Phase, if this card destroyed an opponent''s monster by battle and sent it to the Graveyard this turn while you controlled it: You can target 1 of those destroyed monsters in the Graveyard; Special Summon that target.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85087012,3,0,0,33,400,400,3,32,1,8456);
INSERT OR REPLACE INTO "texts" VALUES (85087012, 'Card Trooper', 'Once per turn: You can choose a number from 1 to 3, then send that many cards from the top of your Deck to the Graveyard; this card gains 500 ATK for each card sent to the Graveyard this way, until the end of this turn. If this card you control is destroyed and sent to your Graveyard: Draw 1 card.', 'Gain attack', 'Draw card', 'Send how many cards to Graveyard?', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48115277,3,0,0,33,1000,1500,4,256,1,786432);
INSERT OR REPLACE INTO "texts" VALUES (48115277, 'Blockman', 'You can Tribute this card; Special Summon in Defense Position, a number of "Block Tokens" (Rock-Type/EARTH/Level 4/ATK 1000/DEF 1500) equal to the number of your turns this card has been face-up on your side of the field. These Tokens cannot declare an attack.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93187568,3,0,0,33,600,200,3,1,1,393216);
INSERT OR REPLACE INTO "texts" VALUES (93187568, 'Spell Striker', 'You can Special Summon this card (from your hand) by banishing 1 Spell Card from your Graveyard. This card can attack your opponent directly. You take no battle damage from attacks involving this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18430390,3,0,0,33,1800,500,4,32768,8,16);
INSERT OR REPLACE INTO "texts" VALUES (18430390, 'Winged Rhynos', 'During either player''s turn, when a Trap Card is activated (except during the Damage Step): You can return this face-up card from the field to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4906301,3,0,0,33,600,1300,3,1,32,65536);
INSERT OR REPLACE INTO "texts" VALUES (4906301, 'Necro Gardna', 'During your opponent''s turn: You can banish this card from your Graveyard; negate the next attack this turn from a monster your opponent controls (this is a Quick Effect).', '1次攻击无效', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66337215,3,0,0,33,1800,600,4,2,16,1048);
INSERT OR REPLACE INTO "texts" VALUES (66337215, 'Herald of Creation', 'Once per turn: You can discard 1 card, then target 1 Level 7 or higher monster in your Graveyard; add that target to your hand.', '7星以上的怪兽加入手牌', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58554959,3,0,24584,33,2600,1800,7,8,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (58554959, 'Evil HERO Malicious Edge', 'If your opponent controls a monster, you can Tribute Summon this card with 1 Tribute. If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', 'Tribute Summon with 1 tribute', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61538782,3,0,22,33,1000,2000,4,32,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (61538782, 'Truckroid', 'When this card destroys an opponent''s monster by battle and sends it to the Graveyard: Equip the destroyed monster to this card. This card gains ATK equal to the combined ATK of the monsters equipped to it by this effect.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39303359,3,0,7,2081,1800,500,4,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (39303359, 'Ancient Gear Knight', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it become an Effect Monster with this effect.
● If this card attacks, your opponent cannot activate Spell/Trap Cards until the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64262809,3,0,0,33,1800,2200,5,8192,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (64262809, 'Dragon Ice', 'When your opponent Special Summons a monster (except during the Damage Step): You can discard 1 card; Special Summon this card from your hand or Graveyard. There can only be 1 "Dragon Ice" on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26376390,3,0,0,33,0,0,1,2,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (26376390, 'Copycat', 'When this card is Summoned: Target 1 face-up monster your opponent controls; this card''s ATK and DEF become equal to that monster''s original ATK and DEF.', '攻守变化', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3657444,3,0,147,33,0,0,1,32,16,1316);
INSERT OR REPLACE INTO "texts" VALUES (3657444, 'Cyber Valley', 'You can use 1 of these effects.
● When this card is targeted for an attack by an opponent''s monster: You can banish this card; draw 1 card, then end the Battle Phase.
● You can target 1 face-up monster you control and this card; banish both that target and this card, then draw 2 cards.
● You can target 1 card in your Graveyard; banish this card and 1 card from your hand, then place that target on top of the Deck.', 'Banish this card; draw 1 card, then end the Battle Phase.', 'Target 1 face-up monster you control and this card; banish both that target and this card, then draw 2 cards.', 'Target 1 card in your Graveyard; banish this card and 1 card from your hand, then place that target on top of the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40921744,3,0,0,33,2800,2300,8,4,32,2);
INSERT OR REPLACE INTO "texts" VALUES (40921744, 'Darklord Zerato', 'If you have 4 or more DARK monsters with different names in your Graveyard, you can Tribute Summon this card by Tributing 1 DARK monster. You can send 1 DARK monster from your hand to the Graveyard; destroy all monsters your opponent controls. During the End Phase, if you activated this effect this turn: Destroy this card.', 'Send 1 DARK monster to Graveyard', 'Destroy', 'Self-Destruct', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33655493,3,0,0,33,2800,2400,8,8,32,33619968);
INSERT OR REPLACE INTO "texts" VALUES (33655493, 'Belial - Marquis of Darkness', 'Your opponent cannot target any face-up monster you control, except "Belial - Marquis of Darkness", for an attack, or with Spell/Trap effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78700060,3,0,0,33,1900,1800,4,8,32,-2147483646);
INSERT OR REPLACE INTO "texts" VALUES (78700060, 'Doomcaliber Knight', 'Cannot be Special Summoned. During either player''s turn, when a monster effect is activated: Tribute this face-up card; negate the activation, and if you do, destroy that monster.', '不能特殊召唤', '怪物效果效果发动无效并破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13893596,3,0,0,33,-2,0,10,2,32,270344);
INSERT OR REPLACE INTO "texts" VALUES (13893596, 'Exodius the Ultimate Forbidden Lord', 'Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by shuffling all monsters in your Graveyard into the Deck, and cannot be Special Summoned by other ways. When this card declares an attack: Send 1 monster from your hand or Deck to the Graveyard. This card gains 1000 ATK for each Normal Monster in your Graveyard. If this face-up card would leave the field, banish it instead. If there are 5 different "Forbidden One" cards in your Graveyard that were sent there by this card''s effect, you win the Duel.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83269557,3,0,0,2081,1800,1050,4,4,32,67117058);
INSERT OR REPLACE INTO "texts" VALUES (83269557, 'Dark Valkyria', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it become an Effect Monster with this effect.
● Once, while this is face-up on the field: You can place 1 Spell Counter on it. This card gains 300 ATK for each Spell Counter on it. You can remove 1 Spell Counter from this card, then target 1 monster on the field; destroy that target.
', 'Place spell counter', 'Destroy 1 monster on the field', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49879995,3,0,0,33,2300,2200,8,8192,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (49879995, 'Phantom Dragon', 'When your opponent Special Summons a monster (except during the Damage Step): You can Special Summon this card from your hand. 2 of your Monster Card Zones cannot be used.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95360850,3,0,0,33,800,1600,3,1,1,16777216);
INSERT OR REPLACE INTO "texts" VALUES (95360850, 'Shield Warrior', 'During damage calculation, in either player''s turn: You can banish this card from your Graveyard; monsters you control cannot be destroyed by this battle.', '戦闘では破壊されない', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97021916,3,0,87,4129,1300,300,3,8,32,16777216);
INSERT OR REPLACE INTO "texts" VALUES (97021916, 'Dark Resonator', 'Once per turn, this card cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59575539,3,0,0,4129,1200,400,2,1048576,32,65536);
INSERT OR REPLACE INTO "texts" VALUES (59575539, 'Krebons', 'When this card is targeted for an attack: You can pay 800 Life Points; negate the attack.', '怪兽的攻击无效', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14778250,3,0,0,33,2000,1200,5,2,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (14778250, 'The Tricky', 'You can Special Summon this card (from your hand) by discarding 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5645210,3,0,0,33,2800,2400,8,4,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (5645210, 'Splendid Venus', 'All non-Fairy-Type monsters lose 500 ATK and DEF. The activation and effects of Spell/Trap Cards you control cannot be negated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33420078,3,0,0,4129,400,200,2,16,32,262148);
INSERT OR REPLACE INTO "texts" VALUES (33420078, 'Plaguespreader Zombie', 'You can return 1 card from your hand to the top of the Deck; Special Summon this card from your Graveyard. If you do, banish this card when it leaves the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96938777,3,0,0,33,1600,1500,4,32,1,32768);
INSERT OR REPLACE INTO "texts" VALUES (96938777, 'Machine Lord Ür', 'This card can attack all monsters your opponent controls once each. If this card attacks or is attacked, your opponent takes no battle damage.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8483333,3,0,0,33,2800,2500,8,16384,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (8483333, 'Mosaic Manticore', 'During the Standby Phase of your next turn after you Tribute Summoned this face-up card on the field: Special Summon, from the Graveyard, as many monster(s) as possible that were used for its Tribute Summon. They cannot declare an attack, and their effects are negated.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20546916,3,0,0,33,1600,2000,4,1024,1,1060864);
INSERT OR REPLACE INTO "texts" VALUES (20546916, 'Botanical Lion', 'This card gains 300 ATK for each face-up Plant-Type monster you control. Control of this face-up card cannot switch.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61802346,3,0,0,33,1800,1000,4,8192,2,0);
INSERT OR REPLACE INTO "texts" VALUES (61802346, 'Blizzard Dragon', 'Once per turn: You can target 1 monster your opponent controls; it cannot change its battle position or declare an attack until the end of your opponent''s next turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33695750,3,0,0,33,500,500,3,2048,32,83894272);
INSERT OR REPLACE INTO "texts" VALUES (33695750, 'Des Mosquito', 'When this card is Normal or Special Summoned: Place 2 counters on it. It gains 500 ATK for each of these counters. If this card would be destroyed by battle, remove 1 of these counters instead.', 'Place counter', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15341821,3,0,0,33,300,300,3,1024,1,786432);
INSERT OR REPLACE INTO "texts" VALUES (15341821, 'Dandylion', 'When this card is sent to the Graveyard: Special Summon 2 "Fluff Tokens" (Plant-Type/WIND/Level 1/ATK 0/DEF 0) in Defense Position. These Tokens cannot be Tributed for a Tribute Summon during the turn they are Special Summoned.', 'Special Summon token', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66288028,3,0,0,33,600,1200,2,1,1,16777216);
INSERT OR REPLACE INTO "texts" VALUES (66288028, 'Fortress Warrior', 'You take no battle damage from attacks involving this card. Once per turn, this card cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40225398,3,0,0,33,1600,1000,4,1,32,49152);
INSERT OR REPLACE INTO "texts" VALUES (40225398, 'Twin-Sword Marauder', 'Once per Battle Phase, if this card attacks a Defense Position monster, it can make a second attack in a row. If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent.', 'Attack again?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78651105,3,0,0,33,3000,1200,8,32768,1,8195);
INSERT OR REPLACE INTO "texts" VALUES (78651105, 'Beast King Barbaros', 'You can Normal Summon/Set this card without Tributing, but its original ATK becomes 1900. You can Tribute 3 monsters to Tribute Summon this card. If you do: Destroy all cards your opponent controls.', 'Normal Summon or Set this card without Tributing', 'Tribute 3 monsters to Tribute Summon this card', 'Destroy all cards your opponent controls', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59042331,3,0,0,33,0,2100,3,1024,1,16785408);
INSERT OR REPLACE INTO "texts" VALUES (59042331, 'Hedge Guard', 'During damage calculation, in either player''s turn: You can send this card from your hand to the Graveyard; halve the ATK of a monster you control until the End Phase, but that monster cannot be destroyed by this battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4694209,3,0,0,33,1600,500,4,8,32,83894272);
INSERT OR REPLACE INTO "texts" VALUES (4694209, 'Card Guard', 'If this card is Normal or Special Summoned: Place 1 Guard Counter on it. This card gains 300 ATK for each Guard Counter on it. Once per turn: You can target 1 other face-up card you control; remove 1 Guard Counter from this card, and if you do, place 1 Guard Counter on that target (if that card would ever be destroyed, remove 1 Guard Counter from it instead).', 'Place counter', '转移指示物', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79473793,3,0,0,33,3000,2500,8,8192,2,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (79473793, 'White Night Dragon', 'During either player''s turn, when a Spell/Trap Card that targets this card is activated: Negate the activation and destroy it. When a face-up monster you control is targeted for an attack: You can send 1 Spell/Trap card you control to the Graveyard; change the target to this card.', '无效并破坏', '改变攻击对象', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19028307,3,0,0,33,3800,1200,8,32768,1,1310720);
INSERT OR REPLACE INTO "texts" VALUES (19028307, 'Beast Machine King Barbaros Ür', 'You can Special Summon this card (from your hand) by banishing 1 Machine-Type monster and 1 Beast-Warrior-Type monster from your hand, field, and/or Graveyard. If this card attacks or is attacked, your opponent takes no battle damage.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96872283,3,0,0,2081,1900,900,4,1,4,3);
INSERT OR REPLACE INTO "texts" VALUES (96872283, 'Evocator Chevalier', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it become an Effect Monster with this effect.
● You can send 1 face-up Equip Card you control to the Graveyard, then target 1 card your opponent controls; destroy that target.
', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19665973,3,0,0,33,0,0,1,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (19665973, 'Battle Fader', 'When your opponent''s monster declares a direct attack: You can Special Summon this card from your hand, then end the Battle Phase. If this card is Special Summoned with this effect, banish it when it leaves the field.', '结束战斗阶段', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42280216,3,0,0,33,1000,2000,5,2,16,262656);
INSERT OR REPLACE INTO "texts" VALUES (42280216, 'Oracle of the Sun', 'If your opponent controls a monster and you control no monsters, you can Special Summon this card (from your hand). When this card on the field is destroyed and sent to the Graveyard: You can add 1 "Fire Ant Ascator" or "Supay" from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64926005,3,0,47,33,1800,1500,4,1,2,2306);
INSERT OR REPLACE INTO "texts" VALUES (64926005, 'Samurai of the Ice Barrier', 'When this face-up Attack Position card is changed to face-up Defense Position: Destroy this card, and if you do, draw 1 card.', '破坏并抽卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85028288,3,0,34,33,3000,2800,9,65536,4,33562624);
INSERT OR REPLACE INTO "texts" VALUES (85028288, 'Jurrac Titano', 'Cannot be Special Summoned. Cannot be targeted by Trap or monster effects. Once per turn: You can banish 1 "Jurrac" monster with 1700 or less ATK from your Graveyard; this card gains 1000 ATK until the End Phase.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55690251,3,0,0,33,3000,2800,10,4,32,1056778);
INSERT OR REPLACE INTO "texts" VALUES (55690251, 'Darklord Desire', 'Cannot be Special Summoned. You can Tribute Summon this card by Tributing 1 Fairy-Type monster. Once per turn: You can target 1 monster your opponent controls; this card loses exactly 1000 ATK, and if it does, send that target to the Graveyard.', 'Tribute Summon this card by Tributing 1 Fairy-Type monster', 'You can target 1 monster your opponent controls; this card loses 1000 ATK, and you send that target to the Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7025445,3,0,0,33,2200,0,6,256,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (7025445, 'Power Giant', 'You can Special Summon this card (from your hand) by sending 1 Level 4 or lower monster from your hand to the Graveyard. If you do, decrease this card''s Level by the Level of that monster. If this card attacks or is attacked, until the end of the Damage Step any effect damage you take becomes 0.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58324930,3,0,0,33,1800,100,4,2,1,4);
INSERT OR REPLACE INTO "texts" VALUES (58324930, 'Anarchist Monk Ranshin', 'When this card you control is sent to your Graveyard by your opponent''s card (either by battle, by card effect, or by being destroyed): Target 1 monster in your opponent''s Graveyard; banish that target.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41098335,3,0,0,33,1900,1200,4,16384,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (41098335, 'Ape Fighter', 'If this card destroys an opponent''s monster by battle: This card gains 300 ATK. If this card does not attack during your turn, the ATK gained from this effect returns to 0 during the End Phase of that turn.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15394083,3,0,24642,33,1200,800,3,16384,1,786432);
INSERT OR REPLACE INTO "texts" VALUES (15394083, 'Tanngrisnir of the Nordic Beasts', 'When this card is destroyed by battle and sent to the Graveyard: Special Summon 2 "Nordic Beast Tokens" (Beast-Type/EARTH/Level 3/ATK 0/DEF 0).', 'Special Summon token', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97940434,3,0,0,33,2500,1600,7,8,32,263168);
INSERT OR REPLACE INTO "texts" VALUES (97940434, 'Chaos Hunter', 'When your opponent Special Summons a monster (except during the Damage Step): You can discard 1 card; Special Summon this card from your hand. Your opponent cannot banish cards.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84914462,3,0,0,33,2000,1200,4,8192,32,2048);
INSERT OR REPLACE INTO "texts" VALUES (84914462, 'Axe Dragonute', 'If this card attacks, change it to Defense Position at the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40619741,3,0,48,33,1700,1000,4,4,16,2048);
INSERT OR REPLACE INTO "texts" VALUES (40619741, 'Vylon Soldier', 'When this card declares an attack: You can target monsters your opponent controls, up to the number of Equip Cards equipped to this card; change those targets'' battle positions.', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14785765,3,0,51,33,1600,1000,4,512,32,4456464);
INSERT OR REPLACE INTO "texts" VALUES (14785765, 'Blackwing - Zephyros the Elite', 'If this card is in your Graveyard: You can return 1 face-up card you control to the hand; Special Summon this card, and if you do, take 400 damage. You can only use this effect of "Blackwing - Zephyros the Elite" once per Duel.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97896503,3,0,143,33,1600,900,3,1,1,2);
INSERT OR REPLACE INTO "texts" VALUES (97896503, 'Zubaba Knight', 'At the start of the Damage Step, if this card attacks a face-up Defense Position monster: Destroy that monster.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62476815,3,0,89,33,1800,1500,4,256,1,17039360);
INSERT OR REPLACE INTO "texts" VALUES (62476815, 'Gogogo Golem', 'Once per turn, this Defense Position card cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56223084,3,0,0,33,1500,100,3,131072,2,270336);
INSERT OR REPLACE INTO "texts" VALUES (56223084, 'Needle Sunfish', 'When this card is sent to the Graveyard: Target 1 face-up monster your opponent controls; that target loses 500 ATK.', 'Lower attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2584136,3,0,0,33,1600,800,4,131072,2,-2147475456);
INSERT OR REPLACE INTO "texts" VALUES (2584136, 'Shocktopus', 'When this card is destroyed by battle with an opponent''s monster and sent to the Graveyard: You can equip this card to that opponent''s monster. That monster''s ATK becomes 0, also it cannot change its battle position.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65367484,3,0,85,33,2100,0,4,1,16,327680);
INSERT OR REPLACE INTO "texts" VALUES (65367484, 'Photon Thrasher', 'Cannot be Normal Summoned or Set. Must first be Special Summoned (from your hand) while you control no monsters. If you control another monster, this card cannot attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25206027,3,0,0,33,2200,1100,5,8192,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (25206027, 'Interplanetarypurplythorny Dragon', 'If a monster you control is destroyed by battle or by card effect and sent to the Graveyard: You can Special Summon this card from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52823314,3,0,0,33,1000,1000,3,8,32,32);
INSERT OR REPLACE INTO "texts" VALUES (52823314, 'Tour Bus From the Underworld', 'When this card is sent to the Graveyard: Target 1 monster in either player''s Graveyard, except "Tour Bus From the Underworld"; shuffle that target into the Deck.', 'Return to deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1281505,3,0,48,4129,900,900,2,32,16,16778240);
INSERT OR REPLACE INTO "texts" VALUES (1281505, 'Vylon Tetra', 'If this card is sent from the Monster Card Zone to the Graveyard: You can pay 500 Life Points, then target 1 face-up monster you control; equip this card to that target. If the equipped monster would be destroyed, you can destroy this Equip Card instead.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38679204,3,0,48,4129,1400,200,3,4,16,2);
INSERT OR REPLACE INTO "texts" VALUES (38679204, 'Vylon Stella', 'If this card is sent from the Monster Card Zone to the Graveyard: You can pay 500 Life Points, then target 1 face-up monster you control; equip this card to that target. At the end of the Damage Step, if the equipped monster battled an opponent''s monster: Destroy that opponent''s monster.', 'Become equip card', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74064212,3,0,48,4129,1500,1500,4,4096,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (74064212, 'Vylon Prism', 'If this card is sent from the Monster Card Zone to the Graveyard: You can pay 500 Life Points, then target 1 face-up monster you control; equip this card to that target. If the equipped monster attacks or is attacked: It gains 1000 ATK during the Damage Step only.', 'Become equip card', 'Become equip card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55758589,3,0,85,33,2500,2000,7,8192,16,3);
INSERT OR REPLACE INTO "texts" VALUES (55758589, 'Photon Wyvern', 'When this card is Normal or Flip Summoned: Destroy all Set cards your opponent controls.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86039057,3,0,0,33,1700,100,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (86039057, 'Tasuke Knight', 'When an opponent''s monster declares an attack, while you have no cards in your hand and this card is in your Graveyard: You can Special Summon this card from your Graveyard, then end the Battle Phase. You can only use the effect of "Tasuke Knight" once per Duel.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12423762,3,0,84,33,1500,2000,4,1,1,17039360);
INSERT OR REPLACE INTO "texts" VALUES (12423762, 'Gagaga Gardna', 'When an opponent''s monster declares a direct attack: You can Special Summon this card from your hand. When this face-up card is targeted for an attack: You can discard 1 card; this card cannot be destroyed by that battle.', 'Special Summon', '不被战破', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45812361,3,0,0,33,800,400,2,32,1,256);
INSERT OR REPLACE INTO "texts" VALUES (45812361, 'Cardcar D', 'Cannot be Special Summoned. During your Main Phase 1, if this card was Normal Summoned this turn: You can Tribute this card; draw 2 cards, then it becomes the End Phase of this turn. You cannot Special Summon during the turn you activate this effect.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66499018,3,0,0,33,1800,0,4,16384,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (66499018, 'Flame Tiger', 'During your Draw Phase, if this card is in your Graveyard and you control no monsters, instead of conducting your normal draw: You can Special Summon this card from the Graveyard. If this card is Special Summoned with this effect, banish it when it leaves the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64892035,3,0,0,33,2200,0,4,8,32,65536);
INSERT OR REPLACE INTO "texts" VALUES (64892035, 'Tardy Orc ', 'This card cannot attack the turn it is Normal Summoned.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36088082,3,0,0,33,1600,1200,4,1,1,2);
INSERT OR REPLACE INTO "texts" VALUES (36088082, 'Bull Blader', 'When an attack is declared involving this card and an opponent''s monster: You can activate this effect; during this battle involving this monster, neither player takes any battle damage, also destroy the opponent''s monster after damage calculation.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33911264,3,0,0,33,800,2400,5,32,16,270336);
INSERT OR REPLACE INTO "texts" VALUES (33911264, 'Solar Wind Jammer', 'If you control no monsters, you can Special Summon this card (from your hand), but its original ATK and DEF become halved. During each of your Standby Phases: Increase the Level of this card by 1. There can only be 1 face-up "Solar Wind Jammer" on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21954587,3,0,7667828,33,2400,1900,7,262144,2,295424);
INSERT OR REPLACE INTO "texts" VALUES (21954587, 'Mermail Abyssmegalo', 'You can discard 2 other WATER monsters to the Graveyard; Special Summon this card from your hand. When you do: You can add 1 "Abyss-" Spell/Trap Card from your Deck to your hand. You can Tribute 1 other face-up Attack Position WATER monster; this card can make a second attack during each Battle Phase this turn.', 'Special Summon', 'Recover', 'Attack twice', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19700943,3,0,130,33,1800,1900,4,32,1,33554432);
INSERT OR REPLACE INTO "texts" VALUES (19700943, 'Dododo Bot', 'Cannot be Normal Summoned (but can be Normal Set). If this card attacks, it is unaffected by other card effects until the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82593786,3,0,0,33,700,600,2,16,32,65536);
INSERT OR REPLACE INTO "texts" VALUES (82593786, 'Bacon Saver', 'During either player''s Battle Step, while an attack is occurring: You can banish this card from your Graveyard; negate the attack. You can only use the effect of "Bacon Saver" once per Duel.', 'Negate attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18988391,3,0,0,33,100,200,1,1024,1,0);
INSERT OR REPLACE INTO "texts" VALUES (18988391, 'Amarylease', 'During your Main Phase: You can banish this card from your Graveyard; you can Normal Summon 1 monster this turn for 1 less Tribute. You can only use the effect of "Amarylease" once per turn.', 'Normal Summon a monster with 1 less Tribute than required', 'Activate the effect of "Amarylease"', 'Tribute (another) monster for Normal Summon?', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10532969,3,0,0,33,2900,1300,8,131072,2,2);
INSERT OR REPLACE INTO "texts" VALUES (10532969, 'Hyper-Ancient Shark Megalodon', 'When this card inflicts battle damage to your opponent: You can target 1 monster your opponent controls; destroy that target.', 'Monster desrtuction', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61231400,3,0,0,33,2900,1800,8,128,4,4210688);
INSERT OR REPLACE INTO "texts" VALUES (61231400, 'Pyrotech Mech - Shiryu', 'You can Tribute Summon this card with 1 Tribute. If Summoned this way, during each End Phase: You take 1000 damage. If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent.', 'Normal Summon with 1 Tribute', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42969214,3,0,103,33,1600,1800,4,32,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (42969214, 'Aye-Iron', 'Once per turn: You can have this card gain 400 ATK. This card cannot attack the turn you activate this effect.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66200210,3,0,4123,33,1100,1600,3,32,8,17563648);
INSERT OR REPLACE INTO "texts" VALUES (66200210, 'Mecha Phantom Beast Hamstrat', 'When this card is flipped face-up: Special Summon 2 "Mecha Phantom Beast Tokens" (Machine-Type/WIND/Level 3/ATK 0/DEF 0). This card''s Level is increased by the total Levels of all "Mecha Phantom Beast Tokens" you control. While you control a Token, this card cannot be destroyed by battle or card effects. You can Tribute 1 Token, then target 1 "Mecha Phantom Beast" monster in your Graveyard; Special Summon that target. You can only use this effect of "Mecha Phantom Beast Hamstrat" once per turn.', 'Special Summon', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83764718,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (83764718, 'Monster Reborn', 'Target 1 monster in either player''s Graveyard; Special Summon it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55144522,3,0,0,2,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (55144522, 'Pot of Greed', 'Draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52097679,3,0,0,2,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (52097679, 'Shield  Sword', 'Switch the original ATK and DEF of all face-up monsters currently on the field, until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40619825,3,0,69,262146,0,0,0,0,0,9248);
INSERT OR REPLACE INTO "texts" VALUES (40619825, 'Axe of Despair', '(This card is always treated as an "Archfiend" card.)
The equipped monster gains 1000 ATK. When this card is sent from the field to the Graveyard: You can Tribute 1 monster; place this card on the top of your Deck.', '回到卡组的最上面', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99597615,3,0,0,262146,0,0,0,0,0,8224);
INSERT OR REPLACE INTO "texts" VALUES (99597615, 'Malevolent Nuzzler', 'The equipped monster gains 700 ATK. When this card is sent from the field to the Graveyard: You can pay 500 Life Points; return this card to the top of the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70046172,3,0,0,65538,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (70046172, 'Rush Recklessly', 'Target 1 face-up monster on the field; it gains 700 ATK until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64047146,3,0,0,262146,0,0,0,0,0,8224);
INSERT OR REPLACE INTO "texts" VALUES (64047146, 'Horn of the Unicorn', 'The equipped monster gains 700 ATK and DEF. When this card is sent from the field to the Graveyard: Return it to the top of the Deck.', 'Return to deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70828912,3,0,0,262146,0,0,0,0,0,262146);
INSERT OR REPLACE INTO "texts" VALUES (70828912, 'Premature Burial', 'Activate this card by paying 800 LP, then target 1 monster in your Graveyard; Special Summon that target in face-up Attack Position and equip it with this card. When this card is destroyed, destroy the equipped monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73915051,3,0,0,65538,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (73915051, 'Scapegoat', 'Special Summon 4 "Sheep Tokens" (Beast-Type/EARTH/Level 1/ATK 0/DEF 0) in Defense Position. These Tokens cannot be Tributed for a Tribute Summon. You cannot Summon other monsters the turn you activate this card (but you can Set).', 'Special Summon token', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79571449,3,0,0,2,0,0,0,0,0,264);
INSERT OR REPLACE INTO "texts" VALUES (79571449, 'Graceful Charity', 'Draw 3 cards, then discard 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14087893,3,0,0,65538,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (14087893, 'Book of Moon', 'Target 1 face-up monster on the field; change that target to face-down Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58577036,3,0,0,2,0,0,0,0,0,262152);
INSERT OR REPLACE INTO "texts" VALUES (58577036, 'Reasoning', 'Your opponent declares a monster Level. Excavate cards from the top of your Deck until you excavate a monster that can be Normal Summoned/Set. If that monster is the same Level as the one declared by your opponent, send all excavated cards to the Graveyard. If not, Special Summon the excavated monster, also send the remaining cards to the Graveyard.', 'Select monster Level', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71453557,3,0,0,262146,0,0,0,0,0,262146);
INSERT OR REPLACE INTO "texts" VALUES (71453557, 'Autonomous Action Unit', 'Pay 1500 Life Points, then target 1 monster in your opponent''s Graveyard; Special Summon that target on your side of the field in face-up Attack Position, and equip it with this card. When this card leaves the field, destroy the equipped monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61127349,3,0,0,262146,0,0,0,0,0,24580);
INSERT OR REPLACE INTO "texts" VALUES (61127349, 'Big Bang Shot', 'The equipped monster gains 400 ATK. If the equipped monster attacks a Defense Position monster, inflict piercing battle damage to your opponent. When this card leaves the field, banish the equipped monster.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34016756,3,0,0,2,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (34016756, 'Riryoku', 'Target 2 face-up monsters on the field; halve the ATK of 1 monster, and if you do, add that lost ATK to the other monster. These effects last until the End Phase.', 'Select monster to halve the ATK', 'Select the monster to gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32022366,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (32022366, 'Gravity Axe - Grarl', 'The equipped monster gains 500 ATK. Monsters your opponent controls cannot change their Battle Positions.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98045062,3,0,0,65538,0,0,0,0,0,6144);
INSERT OR REPLACE INTO "texts" VALUES (98045062, 'Enemy Controller', 'Activate 1 of these effects.
● Target 1 face-up monster your opponent controls; change that target''s battle position.
● Tribute 1 monster, then target 1 face-up monster your opponent controls; take control of that target until the End Phase.', 'Change the Battle Position of 1 face-up monster your opponent controls', 'Tribute 1 monster. Select 1 face-up monster your opponent controls. Take control of it until the End Phase', 'Select effect', 'Select effect', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82828051,3,0,0,2,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (82828051, 'Earthquake', 'Change all face-up monsters on the field to Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55713623,3,0,0,65538,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (55713623, 'Shrink', 'Target 1 face-up monster on the field; the original ATK of that monster is halved until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12923641,3,0,0,131074,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (12923641, 'Swords of Concealing Light', 'When this card resolves, all monsters your opponent controlled when this card was activated are changed to face-down Defense Position. Monsters your opponent controls cannot change their battle positions. Destroy this card during your 2nd Standby Phase after activation.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58775978,3,0,0,2,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (58775978, 'Nightmare''s Steelcage', 'This card remains on the field for 2 of your opponent''s turns. While this card is face-up on the field, no monsters can attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80921533,3,0,0,524290,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (80921533, 'Mausoleum of the Emperor', 'During either player''s Main Phase: The turn player can pay 1000 Life Points x the number of monsters normally needed for the Tribute Summon of a monster (max. 2000); that player Normal Summons/Sets that monster without Tributing. (This is their one Normal Summon/Set for that turn. This is not a Tribute Summon.)', 'Special Summon', '表侧表示召唤', '里侧表示放置', 'Select amount of Life Points to pay', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48712195,3,0,0,131074,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (48712195, 'Card Trader', 'Once per turn, during your Standby Phase: You can shuffle 1 card from your hand into the Deck; draw 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24874630,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (24874630, 'Fiend''s Sanctuary', 'Special Summon 1 "Metal Fiend Token" (Fiend-Type/DARK/Level 1/ATK 0/DEF 0). It cannot attack. Your opponent takes any battle damage you would have taken from battles involving it. During each of your Standby Phases, pay 1000 Life Points or destroy this Token.', 'Pay 1000LP to maintain "Metal Fiend Tokens"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60399954,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (60399954, 'Union Attack', 'Target 1 face-up monster you control; add up the total ATK of all other face-up Attack Position monsters you currently control, then during the Battle Phase of this turn only, the monster gains that much ATK, but cannot inflict battle damage to your opponent, also other face-up Attack Position monsters cannot attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6178850,3,0,0,262146,0,0,0,0,0,16785408);
INSERT OR REPLACE INTO "texts" VALUES (6178850, 'Fighting Spirit', 'The equipped monster gains 300 ATK for each monster your opponent controls. If it would be destroyed by battle, you can destroy this card instead.', 'Destroy "Fighting Spirit" instead?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67196946,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (67196946, 'Star Blast', 'Pay any number of Life Points in multiples of 500; reduce the Level of 1 monster you control or that is in your hand by 1 for each 500 Life Points you paid, until the End Phase.', 'Select amount of LP to pay', 'Select monster to reduce its Level', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25789292,3,0,0,65538,0,0,0,0,0,-2147475456);
INSERT OR REPLACE INTO "texts" VALUES (25789292, 'Forbidden Chalice', 'Target 1 face-up monster on the field; until the end of this turn, that target gains 400 ATK, but its effects are negated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91580102,3,0,60,262146,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (91580102, 'Reptilianne Rage', 'The equipped monster is treated as Reptile-Type. It gains 800 ATK. When this card is destroyed and sent to the Graveyard: Target 1 face-up monster your opponent controls; it loses 800 ATK.', 'Lower attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27863269,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (27863269, 'Rocket Pilder', 'While the equipped monster is attacking, it cannot be destroyed by battle. At the end of the Damage Step, if the equipped monster attacked: The attack target loses ATK equal to the ATK of the equipped monster, until the End Phase.', 'Lose attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73048641,3,0,0,65538,0,0,0,0,0,16785408);
INSERT OR REPLACE INTO "texts" VALUES (73048641, 'Half Shut', 'Target 1 face-up monster on the field; it cannot be destroyed by battle this turn, but its ATK is halved until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98867329,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (98867329, 'Cursed Armaments', 'The equipped monster loses 600 ATK for each monster you control. When this card is sent from the field to the Graveyard: You can target 1 face-up monster your opponent controls; equip it with this card.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98645731,3,0,0,2,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (98645731, 'Pot of Duality', 'Reveal the top 3 cards of your Deck, add 1 of them to your hand, then shuffle the rest back into your Deck. You can only activate 1 "Pot of Duality" per turn. You cannot Special Summon during the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19578592,3,0,0,262146,0,0,0,0,0,-2143281152);
INSERT OR REPLACE INTO "texts" VALUES (19578592, 'Axe of Fools', 'The equipped monster gains 1000 ATK, but its effects are negated. During each of your Standby Phases: Inflict 500 damage to the controller of the equipped monster.', '500damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27243130,3,0,0,65538,0,0,0,0,0,33562624);
INSERT OR REPLACE INTO "texts" VALUES (27243130, 'Forbidden Lance', 'Target 1 face-up monster on the field; until the end of this turn, that target loses 800 ATK, but is unaffected by the effects of other Spell/Trap Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22346472,3,0,0,2,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (22346472, 'Blustering Winds', 'Target 1 face-up monster you control; it gains 1000 ATK and DEF until your next Standby Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73178098,3,0,0,65538,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (73178098, 'Ego Boost', 'When a monster declares an attack: Target 1 face-up monster on the field; it gains 1000 ATK until the end of the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33904024,3,0,0,131074,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (33904024, 'Shard of Greed', 'Each time you draw a card(s) for your normal draw in your Draw Phase, place 1 Greed Counter on this card. You can send this card with 2 or more Greed Counters to the Graveyard; draw 2 cards.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81000306,3,0,0,2,0,0,0,0,0,16777218);
INSERT OR REPLACE INTO "texts" VALUES (81000306, 'Full-Force Strike', 'Target 1 face-up monster you control; this turn, it cannot be destroyed by battle, players take no Battle Damage from its attack, and if it attacks an opponent''s monster, destroy the opponent''s monster after damage calculation.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17418744,3,0,85,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (17418744, 'Photon Sanctuary', 'Special Summon 2 "Photon Tokens" (Thunder-Type/LIGHT/Level 4/ATK 2000/DEF 0) in Defense Position. These Tokens cannot attack or be used as Synchro Material Monsters. You cannot Summon other monsters the turn you activate this card, except for LIGHT monsters.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96864811,3,0,0,65538,0,0,0,0,0,50339840);
INSERT OR REPLACE INTO "texts" VALUES (96864811, 'Forbidden Dress', 'Target 1 face-up monster on the field; until the end of this turn, that target loses 600 ATK, but cannot be targeted or destroyed by other card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77622396,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (77622396, 'Reverse Trap', 'Until the End Phase, all effects that add or subtract ATK or DEF are reversed. (Additions now subtract, and subtractions now add, instead. Multiplications and divisions, including halving/doubling, are not affected.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12607053,3,0,0,4,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (12607053, 'Waboku', 'You take no battle damage from your opponent''s monsters this turn. Your monsters cannot be destroyed by battle this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97077563,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (97077563, 'Call of the Haunted', 'Activate this card by targeting 1 monster in your Graveyard; Special Summon that target in Attack Position. When this card leaves the field, destroy that target. When that target is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22359980,3,0,0,131076,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (22359980, 'Mirror Wall', 'Each of your opponent''s monsters that conducted an attack while this card was face-up on the field has its ATK halved as long as this card remains on the field. During each of your Standby Phases, pay 2000 LP or destroy this card.', 'Pay 2000LP for the effect of "Mirror Wall"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68540058,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (68540058, 'Metalmorph', 'Target 1 face-up monster on the field; equip this card to that target. It gains 300 ATK and DEF. If it attacks, it gains ATK equal to half the ATK of the attack target, during damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57882509,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (57882509, 'Mask of Weakness', 'Target 1 attacking monster; that target loses 700 ATK until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37576645,3,0,0,4,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (37576645, 'Reckless Greed', 'Draw 2 cards and skip your next 2 Draw Phases.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93382620,3,0,0,4,0,0,0,0,0,270336);
INSERT OR REPLACE INTO "texts" VALUES (93382620, 'Rope of Life', 'When a monster(s) is destroyed by battle and sent to your Graveyard: Discard your entire hand (min.1), then target 1 of those monsters; Special Summon it, and if you do, it gains 800 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59744639,3,0,0,4,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (59744639, 'Windstorm of Etaqua', 'Change the battle positions of all face-up monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83133491,3,0,0,4,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (83133491, 'Zero Gravity', 'Change the battle positions of all face-up monsters on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21597117,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (21597117, 'A Hero Emerges', 'When an opponent''s monster declares an attack: Your opponent chooses 1 random card from your hand, then if it is a monster that can be Special Summoned, Special Summon it. Otherwise, send it to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28649820,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (28649820, 'Embodiment of Apophis', 'During either player''s Main Phase: Special Summon this card as a Normal Monster (Reptile-Type/EARTH/Level 4/ATK 1600/DEF 1800). (This card is also still a Trap Card.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43250041,3,0,0,4,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (43250041, 'Draining Shield', 'When an opponent''s monster declares an attack: Target the attacking monster; negate that attack, and if you do, gain Life Points equal to that target''s ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66742250,3,0,0,4,0,0,0,0,0,10240);
INSERT OR REPLACE INTO "texts" VALUES (66742250, 'Curse of Anubis', 'Change all Effect Monsters on the field to Defense Position. This turn, the original DEF of those monsters becomes 0, also their battle positions cannot be changed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66526672,3,0,0,131076,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (66526672, 'Labyrinth of Nightmare', 'Once per turn, during each player''s End Phase: Change the battle positions of all face-up monsters the turn player controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36361633,3,0,0,4,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (36361633, 'Threatening Roar', 'Your opponent cannot declare an attack this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78211862,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (78211862, 'Rising Energy', 'Discard 1 card, then target 1 face-up monster on the field; that target gains 1500 ATK until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96008713,3,0,0,4,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (96008713, 'Magical Arm Shield', 'When your opponent declares an attack while you control a monster: Target 1 face-up monster your opponent controls, except the attacking monster; take control of that target until the end of the Battle Phase, and if you do, it is attacked instead, and you proceed to damage calculation.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12117532,3,0,0,131076,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (12117532, 'Shattered Axe', 'Activate this card by targeting 1 face-up monster on the field. During each of your Standby Phases: It loses 500 ATK. When that target is destroyed, destroy this card.', 'Lose attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13955608,3,0,0,131076,0,0,0,0,0,270336);
INSERT OR REPLACE INTO "texts" VALUES (13955608, 'Stronghold the Moving Fortress', 'Special Summon this card in Defense Position as an Effect Monster (Machine-Type/EARTH/Level 4/ATK 0/DEF 2000). (This card is also still a Trap Card.) While you control a "Green Gadget", "Red Gadget", and "Yellow Gadget", this card gains 3000 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30643162,3,0,0,4,0,0,0,0,0,24576);
INSERT OR REPLACE INTO "texts" VALUES (30643162, 'Strike Slash', 'When a monster you control declares an attack: Until the End Phase, that monster gains 700 ATK, also, if it attacks a Defense Position monster, inflict piercing battle damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60306104,3,0,0,4,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (60306104, 'No Entry!!', 'Change all Attack Position monsters to Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86871614,3,0,0,4,0,0,0,0,0,786432);
INSERT OR REPLACE INTO "texts" VALUES (86871614, 'Cloning', 'When your opponent Normal or Flip Summons a monster that has a Level: Target that face-up monster; Special Summon 1 "Clone Token", with the same original Type, Attribute, Level, ATK, and DEF as that target. When that target is destroyed and sent to the Graveyard, destroy this Token.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26905245,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (26905245, 'Metal Reflect Slime', 'Special Summon this card in Defense Position as an Effect Monster (Aqua-Type/WATER/Level 10/ATK 0/DEF 3000). (This card is also still a Trap Card.) This card cannot attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79852326,3,0,0,131076,0,0,0,0,0,4456448);
INSERT OR REPLACE INTO "texts" VALUES (79852326, 'Zoma the Spirit', 'Special Summon this card in Defense Position as an Effect Monster (Zombie-Type/DARK/Level 4/ATK 1800/DEF 500). (This card is also still a Trap Card.) If this card is destroyed by battle: Inflict damage to your opponent equal to the ATK of the monster that destroyed it.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34815282,3,0,0,131076,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (34815282, 'Miniaturize', 'Activate this card by targeting 1 face-up monster on the field with more than 1000 original ATK that has a Level; its Level is reduced by 1, also it loses 1000 ATK. When that monster leaves the field, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97151365,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (97151365, 'Spacegate', 'Each time a monster your opponent controls attacks or is attacked, place 1 Gate Counter on this card at the end of the Damage Step. During your Main Phase: You can send this card to the Graveyard; Special Summon 1 monster from your hand whose Level is less than or equal to the number of Gate Counters on this card.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71272951,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (71272951, 'Overworked', 'Destroy each monster whose ATK is higher than its original ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37390589,3,0,0,4,0,0,0,0,0,10240);
INSERT OR REPLACE INTO "texts" VALUES (37390589, 'Kunai with Chain', 'Activate 1 or both of these effects (simultaneously).
● When an opponent''s monster declares an attack: Target the attacking monster; change that target to Defense Position.
● Target 1 face-up monster you control; equip this card to that target. It gains 500 ATK.', 'When an opponent''s monster attacks: Target the attacking monster; change that target to Defense Position', 'Target 1 face-up monster you control; equip this card to that target. It gains 500 ATK', 'Activate both effects', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66518841,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (66518841, 'Prideful Roar', 'Activate only during damage During damage calculation, if your monster battles an opponent''s monster with a higher ATK: Pay Life Points equal to the difference in ATK; your monster gains ATK equal to that difference +300, during damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80987696,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (80987696, 'Time Machine', 'When exactly 1 monster is destroyed by battle and sent to the Graveyard: Special Summon that monster to the same side of the field it was on, in the same battle position it was in when destroyed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15552258,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (15552258, 'Half or Nothing', 'During your opponent''s Battle Phase (except during the Damage Step): Your opponent chooses 1 of these effects.
● Halve the ATK of all monsters they currently control, until the end of the Battle Phase.
● End the Battle Phase.
', 'Halve the ATK of all monsters you control until the end of the Battle Phase', 'End the Battle Phase', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97168905,3,0,0,4,0,0,0,0,0,41216);
INSERT OR REPLACE INTO "texts" VALUES (97168905, 'Miracle Locus', 'Target 1 face-up Attack Position monster you control; your opponent draws 1 card, also that monster gains 1000 ATK until the End Phase, and if it does, it can attack up to 2 monsters during each Battle Phase this turn. If it attacks or is attacked this turn, your opponent takes no battle damage from that attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73729209,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (73729209, 'Skill Successor', 'Target 1 face-up monster you control; it gains 400 ATK until the end of this turn. During your turn, except the turn this card was sent to the Graveyard: You can banish this card from the Graveyard, then target 1 face-up monster you control; that target gains 800 ATK until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53656677,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (53656677, 'Power Frame', 'When a face-up monster you control is targeted for an attack by a monster with a higher ATK: Target the attack target; negate that attack, and if you do, equip this card to that target. The equipped monster gains ATK equal to the difference between its ATK and the ATK of its attacker when this card resolves.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87106146,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (87106146, 'Damage Gate', 'When you take battle damage: Target 1 monster in your Graveyard with ATK less than or equal to the amount of damage you took; Special Summon that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21636650,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (21636650, 'Miracle''s Wake', 'Target 1 monster that was destroyed by battle and sent to your Graveyard this turn; Special Summon it from your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6799227,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (6799227, 'Half Counter', 'During damage calculation, if a monster you control is being attacked: Target that monster you control; that target gains ATK equal to half the original ATK of the attacking monster, until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42671151,3,0,0,4,0,0,0,0,0,8650752);
INSERT OR REPLACE INTO "texts" VALUES (42671151, 'The Golden Apples', 'When you take battle damage while you control no monsters: Gain Life Points equal to the battle damage you took, and if you do, Special Summon 1 "Malus Token" (Fiend-Type/DARK/Level 1/ATK ?/DEF ?). Its ATK and DEF are each equal to the amount of Life Points you gained by this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3129635,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (3129635, 'Tiki Curse', 'Special Summon this card as an Effect Monster (Rock-Type/DARK/Level 4/ATK 1800/DEF 1000). (This card is also still a Trap Card.) While this card is an Effect Monster, if another Trap Card that is a monster battles an opponent''s monster, after damage calculation: Destroy that opponent''s monster.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49514333,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (49514333, 'Tiki Soul', 'Special Summon this card as an Effect Monster (Rock-Type/LIGHT/Level 4/ATK 1000/DEF 1800). (This card is also still a Trap Card.) While this card is an Effect Monster, if another Trap Card you control that is a monster would be destroyed by your opponent''s card (either by battle or by card effect) and sent to your Graveyard, you can Set it in the Spell & Trap Card Zone instead.', 'Activate effect of "Tiki Soul"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86778566,3,0,0,4,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (86778566, 'Impenetrable Attack', 'During the Battle Phase, activate 1 of these effects.
● Target 1 monster on the field; it cannot be destroyed by battle or by card effects during this Battle Phase.
● You take no battle damage during this Battle Phase.
', 'Target 1 monster; it cannot be destroyed during this Battle Phase.', 'During this Battle Phase, you take no Battle Damage.', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60080151,3,0,0,4,0,0,0,0,0,4456452);
INSERT OR REPLACE INTO "texts" VALUES (60080151, 'Memory of an Adversary', 'When an opponent''s monster declares an attack: You take damage equal to the attacking monster''s ATK, and if you do, banish that monster. During the End Phase of your opponent''s next turn, Special Summon that monster to your side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44046281,3,0,0,131076,0,0,0,0,0,262148);
INSERT OR REPLACE INTO "texts" VALUES (44046281, 'Dimension Gate', 'When this card is activated: Target 1 monster you control; banish that target face-up. When an opponent''s monster declares a direct attack: You can send this face-up card on the field to the Graveyard. If this card is sent to the Graveyard: You can Special Summon the monster banished by this card''s effect.', 'Send to Graveyard', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6691855,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (6691855, 'Spikeshield with Chain', 'Target 1 face-up monster on the field; equip this card to that target. It gains 500 ATK. If the equipped monster attacks or is attacked while in Defense Position, it gains DEF equal to its ATK during damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78474168,3,0,0,4,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (78474168, 'Breakthrough Skill', 'Target 1 face-up Effect Monster your opponent controls; negate the effects of that opponent''s face-up monster, until the end of this turn. During your turn, except the turn this card was sent to the Graveyard: You can banish this card from your Graveyard, then target 1 face-up Effect Monster your opponent controls; negate that target''s effects until the end of this turn.', 'Negate effect', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
