BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (98494543,3,0,0,2,0,0,0,0,0,1032);
INSERT OR REPLACE INTO "texts" VALUES (98494543, 'Magical Stone Excavation', 'Discard 2 cards, then target 1 Spell Card in your Graveyard; add it to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22567609,3,0,120,33,1000,100,2,16384,1,8650752);
INSERT OR REPLACE INTO "texts" VALUES (22567609, 'Nimble Momonga', 'When this card is destroyed by battle and sent to the Graveyard, gain 1000 Life Points. You can also Special Summon any number of "Nimble Momongas" from your Deck in face-down Defense Position.', 'Recover', 'Special Summon another monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31560081,3,0,0,2097185,300,400,1,2,16,1024);
INSERT OR REPLACE INTO "texts" VALUES (31560081, 'Magician of Faith', 'FLIP: Target 1 Spell Card in your Graveyard; add that target to your hand.', 'Spell recovery', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77044671,3,0,0,33,1200,1400,4,16,1,1310720);
INSERT OR REPLACE INTO "texts" VALUES (77044671, 'Pyramid Turtle', 'When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 Zombie-Type monster with 2000 or less DEF from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97169186,3,0,0,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (97169186, 'Smashing Ground', 'Destroy the 1 face-up monster your opponent controls that has the highest DEF. (If it''s a tie, you get to choose).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40640057,3,0,0,33,300,200,1,8,32,8);
INSERT OR REPLACE INTO "texts" VALUES (40640057, 'Kuriboh', 'uring your opponent''s turn, at damage calculation: You can discard this card; you take no battle damage from that battle (this is a Quick Effect).', 'Reduce damage to 0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18318842,3,0,117,33,1800,1300,4,64,2,16);
INSERT OR REPLACE INTO "texts" VALUES (18318842, 'Abyss Soldier', 'Once per turn: You can discard 1 WATER monster to the Graveyard to target 1 card on the field; return it to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83555666,3,0,0,4,0,0,0,0,0,4194306);
INSERT OR REPLACE INTO "texts" VALUES (83555666, 'Ring of Destruction', 'You can only activate 1 “Ring of Destruction” per turn. During your opponent’s turn: Target 1 face-up monster your opponent controls whose ATK is lower than or equal to your opponent’s LP; destroy that face-up monster, and if you do, you take damage equal to that monster’s original ATK, then, inflict damage to your opponent equal to the damage you took.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33508719,3,0,0,2097185,700,600,2,256,1,264);
INSERT OR REPLACE INTO "texts" VALUES (33508719, 'Morphing Jar', 'FLIP: Both players discard all the cards in their hands, then draw 5 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97642679,3,0,0,161,2700,1500,8,8,32,134217730);
INSERT OR REPLACE INTO "texts" VALUES (97642679, 'Dark Master - Zorc', 'This card can only be Ritual Summoned with the Ritual Spell Card "Contract with the Dark Master". During your Main Phase, you can roll 1 six-sided die. On a 1 or 2, destroy all monsters on your opponent''s side of the field. On a 3, 4, or 5, destroy 1 monster on your opponent''s side of the field. On a 6, destroy all monsters on your side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28553439,3,0,0,65538,0,0,0,0,0,1310722);
INSERT OR REPLACE INTO "texts" VALUES (28553439, 'Magical Dimension', 'If you control a face-up Spellcaster-Type monster: Target 1 monster you control; Tribute it, then Special Summon 1 Spellcaster-Type monster from your hand, then you can destroy 1 monster on the field.', 'Destroy 1 monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99030164,3,0,0,17,800,500,2,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (99030164, 'Happy Lover', 'Enemies become overjoyed when struck by the Heart Ray emitted from the forehead of this tiny cherub.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70046172,3,0,0,65538,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (70046172, 'Rush Recklessly', 'Target 1 face-up monster on the field; it gains 700 ATK until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36468556,3,0,0,4,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (36468556, 'Ceasefire', 'Change all face-down Defense Position monsters on the field to face-up Defense Position (Flip Effects are not activated), also inflict 500 damage to your opponent for each Effect Monster on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31786629,3,0,0,33,1600,1500,5,4096,16,512);
INSERT OR REPLACE INTO "texts" VALUES (31786629, 'Thunder Dragon', 'You can discard this card to add up to 2 "Thunder Dragons" from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43586926,3,0,0,33,1500,1200,3,8192,8,270336);
INSERT OR REPLACE INTO "texts" VALUES (43586926, 'Twin-Headed Behemoth', 'During the End Phase, if this card was destroyed on the field and sent to the Graveyard this turn: Special Summon it from the Graveyard, and make its ATK and DEF 1000. You can only use the effect of "Twin-Headed Behemoth" once per Duel.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38699854,3,0,0,2,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (38699854, 'Book of Taiyou', 'Flip 1 face-down monster on the field into face-up Attack Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73628505,3,0,0,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (73628505, 'Terraforming', 'Add 1 Field Spell Card from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61127349,3,0,0,262146,0,0,0,0,0,24580);
INSERT OR REPLACE INTO "texts" VALUES (61127349, 'Big Bang Shot', 'The equipped monster gains 400 ATK. If the equipped monster attacks a Defense Position monster, inflict piercing battle damage to your opponent. When this card leaves the field, banish the equipped monster.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60764581,3,0,0,2,0,0,0,0,0,786432);
INSERT OR REPLACE INTO "texts" VALUES (60764581, 'Stray Lambs', 'Special Summon 2 "Lamb Tokens" (Beast-Type/EARTH/Level 1/ATK 0/DEF 0) in Defense Position. You cannot Summon other monsters the turn you activate this card (but you can Set).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
