BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (36045450,3,0,0,2,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (36045450, 'Magicians Unite', 'If you control 2 or more Attack Position Spellcaster-Type monsters: Target 1 of them; its ATK becomes 3000 until the end of this turn, but other Spellcaster-Type monsters you control cannot attack this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23205979,3,0,0,33,300,200,3,16,32,16777282);
INSERT OR REPLACE INTO "texts" VALUES (23205979, 'Spirit Reaper', 'Cannot be destroyed by battle. After resolving a card effect that targets this face-up card, destroy this card. When this card inflicts battle damage to your opponent by a direct attack: Discard 1 random card from their hand.', 'Discard hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24317029,3,0,46,2097185,1200,2000,4,2,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (24317029, 'Gravekeeper''s Spy', 'FLIP: Special Summon 1 "Gravekeeper''s" monster with 1500 or less ATK from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84290642,3,0,0,33,1500,600,4,8,32,134217739);
INSERT OR REPLACE INTO "texts" VALUES (84290642, 'Snipe Hunter', 'You can discard 1 card, then target 1 card on the field; roll a six-sided die, and destroy that target unless you roll a 1 or 6.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93554166,3,0,6,2,0,0,0,0,0,11);
INSERT OR REPLACE INTO "texts" VALUES (93554166, 'Dark World Lightning', 'Target 1 Set card on the field; destroy that target, then discard 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70074904,3,0,0,33,1700,1600,4,1,1,4);
INSERT OR REPLACE INTO "texts" VALUES (70074904, 'D.D. Assailant', 'After damage calculation, when this card is destroyed by battle with an opponent''s monster: Banish that monster, also banish this card.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78004197,3,0,6,33,2300,1400,5,8,32,262147);
INSERT OR REPLACE INTO "texts" VALUES (78004197, 'Goldd, Wu-Lord of Dark World', 'If this card is discarded to the Graveyard by a card effect: If it was discarded from your hand to your Graveyard by an opponent''s card effect, you can target up to 2 cards your opponent controls; Special Summon this card from the Graveyard, then destroy those cards (if any).', 'Special Summon', 'Destroy card(s) on your opponent''s field?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77121851,3,0,0,33,2300,1000,6,32768,4,1310728);
INSERT OR REPLACE INTO "texts" VALUES (77121851, 'Manticore of Darkness', 'During the End Phase of the turn this card was sent to the Graveyard: You can send to the Graveyard 1 Beast, Beast-Warrior, or Winged Beast-Type monster from your hand or your side of the field; Special Summon this card from your Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91345518,3,0,68,33,2400,0,6,4,16,4194304);
INSERT OR REPLACE INTO "texts" VALUES (91345518, 'The Agent of Judgment - Saturn', 'While your Life Points are higher than your opponent''s, you can Tribute this card to inflict damage to your opponent equal to the difference. If you do not control a face-up "The Sanctuary in the Sky", this effect is not applied. You cannot conduct your Battle Phase the turn you activate this effect.', '给与对方基本分差值的伤害', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74270067,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (74270067, 'Pikeru''s Circle of Enchantment', 'Damage to you from card effects becomes 0 until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77754944,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (77754944, 'Widespread Ruin', 'Activate only when your opponent declares an attack. Destroy the Attack Position monster your opponent controls with the highest ATK. (If it''s a tie, you get to choose.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20315854,3,0,0,17,1100,1200,4,8192,8,0);
INSERT OR REPLACE INTO "texts" VALUES (20315854, 'Fairy Dragon', 'This beautiful Dragon spirit harbors hidden strength.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16956455,3,0,0,33,1800,1000,4,32768,1,1);
INSERT OR REPLACE INTO "texts" VALUES (16956455, 'Chiron the Mage', 'Once per turn: You can discard 1 Spell Card, then target 1 Spell/Trap Card your opponent controls; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34627841,3,0,0,33,200,700,3,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (34627841, 'Kaibaman', 'You can Tribute this card to Special Summon 1 "Blue-Eyes White Dragon" from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22790789,3,0,21,33,2100,1000,5,32,2,83888130);
INSERT OR REPLACE INTO "texts" VALUES (22790789, 'B.E.S. Crystal Core', 'When this card is Normal Summoned, put 3 counters on it. This card cannot be destroyed by battle. If this card attacks or is attacked, remove 1 counter from this card at the end of the Damage Step. If you cannot, destroy it. Once per turn, during your Main Phase, you can change 1 face-up Attack Position monster your opponent controls to face-up Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62473983,3,0,46,33,1900,1200,5,2,32,33816576);
INSERT OR REPLACE INTO "texts" VALUES (62473983, 'Gravekeeper''s Chief', 'You can only control 1 "Gravekeeper''s Chief". Cards in your Graveyard are unaffected by "Necrovalley". When this card is Tribute Summoned, you can select 1 "Gravekeeper''s" monster from your Graveyard and Special Summon it.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61166988,3,0,0,2,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (61166988, 'Wild Nature''s Release', 'Target 1 Beast or Beast-Warrior-Type monster; it gains ATK equal to its current DEF until the End Phase. During the End Phase, destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49140998,3,0,0,2,0,0,0,0,0,1064);
INSERT OR REPLACE INTO "texts" VALUES (49140998, 'A Feather of the Phoenix', 'Discard 1 card. Select 1 card from your Graveyard and return it to the top of your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69035382,3,0,0,130,0,0,0,0,0,2359296);
INSERT OR REPLACE INTO "texts" VALUES (69035382, 'Contract with the Abyss', 'This card is used to Ritual Summon any DARK Ritual Monster. You must also Tribute monsters from the field or your hand whose total Levels equal the Level of the Ritual Monster you are Ritual Summoning.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47355498,3,0,145,524290,0,0,0,0,0,-2147475456);
INSERT OR REPLACE INTO "texts" VALUES (47355498, 'Necrovalley', 'All "Gravekeeper''s" monsters gain 500 ATK and DEF. Cards in either player''s Graveyard cannot be banished. Negate any card effect that would move a card in the Graveyard, other than itself, to a different place.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
