BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (77936940,3,0,0,33,1300,1200,4,16,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (77936940, 'Gernia', 'During your next Standby Phase, after this face-up card you control was destroyed and sent to your Graveyard by an opponent''s card effect: Special Summon it.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80604091,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (80604091, 'Ultimate Offering', 'You can pay 500 Life Points to Normal Summon or Set 1 extra monster. You can only activate this effect during your Main Phase or your opponent''s Battle Phase.', 'Special Summon', 'Activate effect?', 'Normal Summon monster', 'Set monster', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29401950,3,0,8978508,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (29401950, 'Bottomless Trap Hole', 'When your opponent Summons a monster(s) with 1500 or more ATK: Destroy that monster(s) with 1500 or more ATK, and if you do, banish it instead of sending it to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9156135,3,0,0,33,400,800,2,2,32,68420096);
INSERT OR REPLACE INTO "texts" VALUES (9156135, 'Apprentice Magician', 'When this card is Summoned, place 1 Spell Counter on a face-up card that you can place a Spell Counter on. When this card is destroyed by battle, you can Special Summon 1 Level 2 or lower Spellcaster-Type monster from your Deck in face-down Defense Position.', 'Place spell counter', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22587018,3,0,0,33,1600,1000,4,65536,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (22587018, 'Hydrogeddon', 'When this card destroys a monster your opponent controls by battle and sends it to the Graveyard: You can Special Summon 1 "Hydrogeddon" from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17375316,3,0,0,2,0,0,0,0,0,64);
INSERT OR REPLACE INTO "texts" VALUES (17375316, 'Confiscation', 'Pay 1000 Life Points. Look at your opponent''s hand, select 1 card in it, and discard that card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16556849,3,0,0,33,1700,1200,4,1,16,2);
INSERT OR REPLACE INTO "texts" VALUES (16556849, 'Freed the Brave Wanderer', 'Once per turn: You can banish 2 LIGHT monsters from your Graveyard to target 1 face-up monster on the field with higher ATK than this face-up card; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31423101,3,0,0,262146,0,0,0,0,0,9220);
INSERT OR REPLACE INTO "texts" VALUES (31423101, 'Divine Sword - Phoenix Blade', 'Equip only to a Warrior-Type monster. It gains 300 ATK. During your Main Phase, if this card is in your Graveyard you can remove from play 2 Warrior-Type monsters in your Graveyard to add this card to your hand.', '这张卡加入手牌', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27174286,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (27174286, 'Return from the Different Dimension', 'Pay half your Life Points; Special Summon as many of your banished monsters as possible. During the End Phase, banish all monsters that were Special Summoned by this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79853073,3,0,0,33,1350,1800,3,32,1,1056768);
INSERT OR REPLACE INTO "texts" VALUES (79853073, 'Kinetic Soldier', 'During damage calculation, if this card battles a Warrior-Type monster: This card gains 2000 ATK and DEF during damage calculation only.', 'Increase ATK and DEF', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50755,3,0,0,4,0,0,0,0,0,262656);
INSERT OR REPLACE INTO "texts" VALUES (50755, 'Magician''s Circle', 'When a Spellcaster-Type monster declares an attack: Each player Special Summons 1 Spellcaster-Type monster with 2000 or less ATK from their Deck in Attack Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68005187,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (68005187, 'Soul Exchange', 'Target 1 monster your opponent controls; this turn, if you Tribute a monster, you must Tribute that monster, as if you controlled it. You cannot conduct your Battle Phase the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57839750,3,0,0,33,1400,1000,4,32768,2,2359296);
INSERT OR REPLACE INTO "texts" VALUES (57839750, 'Mother Grizzly', 'When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 WATER monster with 1500 or less ATK from your Deck, in face-up Attack Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13676474,3,0,0,17,1500,800,4,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (13676474, 'Grand Tiki Elder', 'A masked monster that wields the most deadly of curses.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47606319,3,0,0,33,1900,1300,4,256,1,2359301);
INSERT OR REPLACE INTO "texts" VALUES (47606319, 'Gigantes', 'This card cannot be Normal Summoned or Set. This card can only be Special Summoned by removing from play 1 EARTH monster in your Graveyard. When this card is destroyed by battle and sent to the Graveyard, destroy all Spell and Trap Cards on the field.', '破坏场上所有魔法·陷阱卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88279736,3,0,172,131076,0,0,0,0,0,64);
INSERT OR REPLACE INTO "texts" VALUES (88279736, 'Robbin'' Goblin', 'Each time a monster you control inflicts Battle Damage to your opponent, your opponent discards 1 random card.', '对方随机丢弃1张手牌', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95492061,3,0,0,33,1400,1000,4,4,16,512);
INSERT OR REPLACE INTO "texts" VALUES (95492061, 'Manju of the Ten Thousand Hands', 'When this card is Normal Summoned or Flip Summoned, you can add 1 Ritual Monster Card or 1 Ritual Spell Card from your Deck to your hand.', 'Select 1 Ritual Monster Card or 1 Ritual Spell Card from your Deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98446407,3,0,0,33,600,600,2,2,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (98446407, 'Hand of Nephthys', 'You can Tribute this card and 1 other monster to Special Summon 1 "Sacred Phoenix of Nephthys" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48092532,3,0,0,33,1800,200,4,1,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (48092532, 'D.D. Survivor', 'During the End Phase, if this card was banished while face-up, on your side of the field, this turn: Special Summon this banished card. This effect can only activate once per turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12538374,3,0,18,33,100,100,1,64,2,263168);
INSERT OR REPLACE INTO "texts" VALUES (12538374, 'Treeborn Frog', 'During your Standby Phase, if this card is in your Graveyard and you do not control a "Treeborn Frog": You can Special Summon this card. You must control no Spell/Trap Cards to activate and to resolve this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
