BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (45945685,3,0,22,17,800,1000,3,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (45945685, 'Cycroid', 'The most lovable and friendly of all the Vehicroids. It can arm itself with training wheels!', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60246171,3,0,0,17,0,0,3,4,8,0);
INSERT OR REPLACE INTO "texts" VALUES (60246171, 'Soitsu', 'Apparently totally unreliable, he wonders if he has incredible potential.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97240270,3,0,0,17,1700,1000,3,64,2,0);
INSERT OR REPLACE INTO "texts" VALUES (97240270, 'Mad Lobster', 'A gourmet food renowned by the Dark World upper crust. It has sensational flavor.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23635815,3,0,0,17,1750,0,3,1024,1,0);
INSERT OR REPLACE INTO "texts" VALUES (23635815, 'Jerry Beans Man', 'Jerry, a bean soldier, believes he is the strongest warrior in the world, but his true abilities are still untested.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98585345,3,0,10747969,33,300,200,10,4,16,4194306);
INSERT OR REPLACE INTO "texts" VALUES (98585345, 'Winged Kuriboh LV10', 'Cannot be Normal Summoned or Set. Must be Special Summoned with "Transcendent Wings" and cannot be Special Summoned by other ways. During your opponent''s Battle Phase: You can Tribute this face-up card; destroy all Attack Position monsters your opponent controls and inflict damage to your opponent equal to the combined original ATK of those destroyed monster(s).', 'Destroy and inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71930383,3,0,22,33,1200,1200,4,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (71930383, 'Patroid', 'Once per turn, during your Main Phase, you can look at 1 face-down card your opponent controls, then return it to its original position.', '确认盖卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18325492,3,0,22,33,1000,1000,3,32,8,16777216);
INSERT OR REPLACE INTO "texts" VALUES (18325492, 'Gyroid', 'Once per turn, this card cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44729197,3,0,22,33,1800,1800,4,32,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (44729197, 'Steamroid', 'If this card attacks an opponent''s monster, this card gains 500 ATK during the Damage Step only. If this card is attacked by an opponent''s monster, this card loses 500 ATK during the Damage Step only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71218746,3,0,22,33,1600,1600,4,32,1,2);
INSERT OR REPLACE INTO "texts" VALUES (71218746, 'Drillroid', 'Before damage calculation, if this card attacks a Defense Position monster: Destroy that monster.', '破坏守备怪物', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7602840,3,0,22,33,1200,1200,6,32,16,1310720);
INSERT OR REPLACE INTO "texts" VALUES (7602840, 'UFOroid', 'When this card is destroyed by battle and sent to the Graveyard, you can Special Summon 1 Machine-Type monster with 1500 or less ATK from your Deck in face-up Attack Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43697559,3,0,22,33,1200,1800,4,32,8,1310720);
INSERT OR REPLACE INTO "texts" VALUES (43697559, 'Jetroid', 'At the time this card is selected as an attack target by an opponent''s monster, you can activate Trap Card(s) from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6480253,3,0,0,33,800,1200,3,32,1,1040);
INSERT OR REPLACE INTO "texts" VALUES (6480253, 'Wroughtweiler', 'When this card is destroyed by battle and sent to the Graveyard: Target 1 "Elemental HERO" card and 1 "Polymerization" in your Graveyard; add both those targets to your hand.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33875961,3,0,0,33,1000,1500,4,32,1,3);
INSERT OR REPLACE INTO "texts" VALUES (33875961, 'Dark Catapulter', 'During your Standby Phase, if this card is in Defense Position, put 1 counter on this card. You can remove from play a number of card(s) in your Graveyard equal to the number of counters on this card to destroy that many Spell or Trap Card(s) on the field. Then remove all counter(s) from this card.', 'Place counter', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79979666,3,0,12296,33,800,1200,4,1,2,262400);
INSERT OR REPLACE INTO "texts" VALUES (79979666, 'Elemental HERO Bubbleman', 'If this is the only card in your hand, you can Special Summon it (from your hand). When this card is Summoned: You can draw 2 cards. You must control no other cards and have no cards in your hand to activate and to resolve this effect.', 'Special Summon', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70095154,3,0,278069507,33,2100,1600,5,32,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (70095154, 'Cyber Dragon', 'If your opponent controls a monster and you control no monsters, you can Special Summon this card (from your hand).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59023523,3,0,9699475,33,2400,1000,6,2,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (59023523, 'Cybernetic Magician', 'You can discard 1 card to target 1 face-up monster on the field; that target''s ATK becomes 2000 until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96428622,3,0,9699475,33,1400,200,4,32768,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (96428622, 'Cybernetic Cyclopean', 'While you have no cards in your hand, this card gains 1000 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22512237,3,0,0,33,2800,1500,7,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (22512237, 'Mechanical Hound', 'While you have no cards in your hand, your opponent cannot activate Spell Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59907935,3,0,9633861,33,1000,2000,4,8,32,258);
INSERT OR REPLACE INTO "texts" VALUES (59907935, 'Cyber Archfiend', 'At the beginning of your Draw Phase, if you have no cards in your hand, draw 1 more card in addition to the normal draw. During your End Phase, if you have 1 or more card(s) in your hand, destroy this card.', 'Draw', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85306040,3,0,172,33,2200,1500,4,8,1,2048);
INSERT OR REPLACE INTO "texts" VALUES (85306040, 'Goblin Elite Attack Force', 'If this card attacks, it is changed to Defense Position at the end of the Battle Phase, and its battle position cannot be changed until the end of your next turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22790789,3,0,21,33,2100,1000,5,32,2,83888130);
INSERT OR REPLACE INTO "texts" VALUES (22790789, 'B.E.S. Crystal Core', 'When this card is Normal Summoned, put 3 counters on it. This card cannot be destroyed by battle. If this card attacks or is attacked, remove 1 counter from this card at the end of the Damage Step. If you cannot, destroy it. Once per turn, during your Main Phase, you can change 1 face-up Attack Position monster your opponent controls to face-up Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58185394,3,0,0,33,2500,2400,4,8,32,4194304);
INSERT OR REPLACE INTO "texts" VALUES (58185394, 'Giant Kozaky', 'If there is no face-up "Kozaky" on the field, destroy this card. If this face-up card is destroyed, inflict damage equal to the original ATK of this card to its current controller.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84173492,3,0,0,33,2300,0,4,32768,1,2048);
INSERT OR REPLACE INTO "texts" VALUES (84173492, 'Indomitable Fighter Lei Lei', 'If this card attacks, it is changed to Defense Position at the end of the Battle Phase. This card''s battle position cannot be changed until the end of your next turn, except with a card effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11678191,3,0,0,1057,0,0,1,4,16,16779264);
INSERT OR REPLACE INTO "texts" VALUES (11678191, 'Protective Soul Ailin', 'Once per turn, you can equip this card to an "Indomitable Fighter Lei Lei" you control, OR unequip it to Special Summon this card in face-up Attack Position. When equipped to a monster by this card''s effect, you can change that monster''s battle position once per turn. (A monster can only be equipped with 1 Union Monster at a time. If the equipped monster would be destroyed by battle, destroy this card instead.)', 'Equip', 'Special Summon', '表示形式を変更', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57062206,3,0,0,1057,100,200,4,4,1,17047552);
INSERT OR REPLACE INTO "texts" VALUES (57062206, 'Doitsu', 'Once per turn, you can equip this card to a "Soitsu" you control, OR unequip it to Special Summon this card in face-up Attack Position. While equipped to a monster by this card''s effect, that monster gains 2500 ATK. (A monster can only be equipped with 1 Union Monster at a time. If the equipped monster would be destroyed by battle, destroy this card instead.)', 'Equip', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84451804,3,0,18,33,1900,0,5,64,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (84451804, 'Des Frog', 'When this card is Tribute Summoned, you can Special Summon "Des Frog"(s) from your hand or Deck up to the number of "T.A.D.P.O.L.E."(s) in your Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10456559,3,0,0,33,0,0,1,64,2,512);
INSERT OR REPLACE INTO "texts" VALUES (10456559, 'T.A.D.P.O.L.E.', 'When this card you control is destroyed by battle and sent to your Graveyard, you can add any "T.A.D.P.O.L.E."(s) from your Deck to your hand.', 'Add "T.A.D.P.O.L.E." to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56840658,3,0,18,33,100,100,2,64,2,256);
INSERT OR REPLACE INTO "texts" VALUES (56840658, 'Poison Draw Frog', 'When this face-up card on the field is sent to the Graveyard (unless it was attacked while face-down and destroyed by battle), you can draw 1 card.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83235263,3,0,0,33,-2,0,4,65536,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (83235263, 'Tyranno Infinity', 'The original ATK of this card is the number of your banished Dinosaur-Type monsters x 1000.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19733961,3,0,40,33,0,0,2,4096,16,1056768);
INSERT OR REPLACE INTO "texts" VALUES (19733961, 'Batteryman C', 'If all "Batteryman C"(s) you control are in Attack Position, all Machine-Type monsters you control gain 500 ATK for each "Batteryman C" you control. If all "Batteryman C"(s) you control are in Defense Position, all Machine-Type monsters you control gain 500 DEF for each "Batteryman C" you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46128076,3,0,110,33,1200,0,2,2,32,4194304);
INSERT OR REPLACE INTO "texts" VALUES (46128076, 'Ebon Magician Curran', 'During your Standby Phase, inflict 300 damage to your opponent for each monster they control.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82112775,3,0,0,33,1700,1500,5,2,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (82112775, 'D.D.M. - Different Dimension Master', 'Once per turn, you can discard 1 Spell Card to Special Summon 1 of your removed from play monsters.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5368615,3,0,22,65,2200,1600,6,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (5368615, 'Steam Gyroid', '"Gyroid" + "Steamroid"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32752319,3,0,22,97,-2,-2,10,32,16,270336);
INSERT OR REPLACE INTO "texts" VALUES (32752319, 'UFOroid Fighter', '"UFOroid" + 1 Warrior-Type monster
A Fusion Summon of this card can only be conducted with the above Fusion Material Monsters. The original ATK and DEF of this card become equal to the combined original ATK of the 2 Fusion Material Monsters you used for the Fusion Summon of this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74157028,3,0,9634051,97,2800,2100,8,32,16,32768);
INSERT OR REPLACE INTO "texts" VALUES (74157028, 'Cyber Twin Dragon', '"Cyber Dragon" + "Cyber Dragon"
A Fusion Summon of this card can only be conducted with the above Fusion Material Monsters. This card can attack twice during each Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1546123,3,0,9634051,97,4000,2800,10,32,16,16384);
INSERT OR REPLACE INTO "texts" VALUES (1546123, 'Cyber End Dragon', '"Cyber Dragon" + "Cyber Dragon" + "Cyber Dragon"
A Fusion Summon of this card can only be conducted with the above Fusion Material Monsters. If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37630732,3,0,0,2,0,0,0,0,0,273948672);
INSERT OR REPLACE INTO "texts" VALUES (37630732, 'Power Bond', 'Send, from your hand or your side of the field to the Graveyard, Fusion Material Monsters that are listed on a Machine-Type Fusion Monster Card, then Special Summon that Fusion Monster from your Extra Deck, and it gains ATK equal to its original ATK. (This Special Summon is treated as a Fusion Summon.) During the End Phase of this turn, the player who activated this card takes damage equal to the original ATK of the monster (at the time it was Summoned).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18511384,3,0,70,2,0,0,0,0,0,268436480);
INSERT OR REPLACE INTO "texts" VALUES (18511384, 'Fusion Recovery', 'Target 1 "Polymerization", and 1 Fusion Material Monster that was used for a Fusion Summon, in your Graveyard; add them to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45906428,3,0,70,2,0,0,0,0,0,268697604);
INSERT OR REPLACE INTO "texts" VALUES (45906428, 'Miracle Fusion', 'Banish, from your side of the field or your Graveyard, the Fusion Material Monsters that are listed on an "Elemental HERO" Fusion Monster Card, then Special Summon that Fusion Monster from your Extra Deck. (This Special Summon is treated as a Fusion Summon.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71490127,3,0,0,2,0,0,0,0,0,269746180);
INSERT OR REPLACE INTO "texts" VALUES (71490127, 'Dragon''s Mirror', 'Banish, from your side of the field or your Graveyard, Fusion Material Monsters that are listed on a Dragon-Type Fusion Monster Card, and Special Summon that Fusion Monster from your Extra Deck. (This Special Summon is treated as a Fusion Summon.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18895832,3,0,0,2,0,0,0,0,0,1048580);
INSERT OR REPLACE INTO "texts" VALUES (18895832, 'System Down', 'Pay 1000 Life Points; banish all face-up Machine-Type monsters your opponent controls and in their Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44883830,3,0,0,2,0,0,0,0,0,3);
INSERT OR REPLACE INTO "texts" VALUES (44883830, 'Des Croaking', 'Activate only while you control 3 face-up "Des Frogs". Destroy all cards your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70278545,3,0,0,2,0,0,0,0,0,32);
INSERT OR REPLACE INTO "texts" VALUES (70278545, 'Pot of Generosity', 'Return 2 cards from your hand to your Deck. Then shuffle your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7672244,3,0,0,2,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (7672244, 'Shien''s Spy', 'Select 1 face-up monster on your side of the field to activate this card. Until the End Phase of this turn, shift control of the selected monster to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25573054,3,0,0,65538,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (25573054, 'Transcendent Wings', 'Send 1 "Winged Kuriboh" you control and 2 cards from your hand to the Graveyard; Special Summon 1 "Winged Kuriboh LV10" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61968753,3,0,0,65538,0,0,0,0,0,264192);
INSERT OR REPLACE INTO "texts" VALUES (61968753, 'Bubble Shuffle', 'Target 1 face-up Attack Position "Elemental HERO Bubbleman" you control and 1 face-up Attack Position monster your opponent controls; change both those targets to Defense Position, then Tribute that 1 "Elemental HERO Bubbleman", then Special Summon 1 "Elemental HERO" monster from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97362768,3,0,0,262146,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (97362768, 'Spark Blaster', 'Equip only to "Elemental HERO Sparkman". During your Main Phase: You can target 1 face-up monster; change the battle position of that target. After you use this effect 3 times, destroy this card.', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63035430,3,0,0,524290,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (63035430, 'Skyscraper', 'When an "Elemental HERO" monster attacks, if its ATK is lower than the ATK of the attack target, the attacking monster gains 1000 ATK during damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43061293,3,0,0,4,0,0,0,0,0,138412032);
INSERT OR REPLACE INTO "texts" VALUES (43061293, 'Fire Darts', 'You can only activate this card when you have no cards in your hand. Roll a six-sided die 3 times, and inflict damage to your opponent''s Life Points equal to the total result of the die rolls × 100 points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70156997,3,0,0,4,0,0,0,0,0,2359304);
INSERT OR REPLACE INTO "texts" VALUES (70156997, 'Spiritual Earth Art - Kurogane', 'Tribute 1 EARTH monster on your side of the field. Special Summon 1 Level 4 or lower EARTH monster from your Graveyard, except the Tributed monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6540606,3,0,0,4,0,0,0,0,0,2097216);
INSERT OR REPLACE INTO "texts" VALUES (6540606, 'Spiritual Water Art - Aoi', 'Tribute 1 WATER monster; look at your opponent''s hand, then send 1 card from their hand to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42945701,3,0,0,4,0,0,0,0,0,6291456);
INSERT OR REPLACE INTO "texts" VALUES (42945701, 'Spiritual Fire Art - Kurenai', 'Tribute 1 FIRE monster; inflict damage to your opponent equal to that monster''s original ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79333300,3,0,0,4,0,0,0,0,0,2097184);
INSERT OR REPLACE INTO "texts" VALUES (79333300, 'Spiritual Wind Art - Miyabi', 'Tribute 1 WIND monster to select 1 card your opponent controls. Place that card on the bottom of the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5728014,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (5728014, 'A Rival Appears!', 'Select 1 face-up monster your opponent controls. Special Summon 1 monster from your hand that has the same Level as the selected monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32723153,3,0,0,4,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (32723153, 'Magical Explosion', 'You can only activate this card when you have no cards in your hand. Inflict 200 points of damage to your opponent''s Life Points for each Spell Card in your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78211862,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (78211862, 'Rising Energy', 'Discard 1 card, then target 1 face-up monster on the field; that target gains 1500 ATK until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5606466,3,0,8978508,4,0,0,0,0,0,6);
INSERT OR REPLACE INTO "texts" VALUES (5606466, 'D.D. Trap Hole', 'When your opponent Sets exactly 1 monster (and no other cards): Target that Set monster and 1 monster you control; destroy those targets, and if you do, banish them.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31000575,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (31000575, 'Conscription', 'Excavate the top card of your opponent''s Deck, and if it is a monster that can be Normal Summoned/Set, Special Summon it to your side of the field. Otherwise, add that card to your opponent''s hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67095270,3,0,0,4,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (67095270, 'Dimension Wall', 'Activate only when an opponent''s monster declares an attack. Instead of you, your opponent takes the Battle Damage you would have taken from this battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4483989,3,0,0,131076,0,0,0,0,0,138414080);
INSERT OR REPLACE INTO "texts" VALUES (4483989, 'Prepare to Strike Back', 'Each time your opponent declares an attack on a face-up Defense Position monster, toss a coin and call it. If you call it right, change the targeted face-up Defense Position monster to Attack Position. If you call it wrong, the controller of this card takes damage equal to the difference between the ATK of the attacking monster, and DEF of the attacked monster.', 'Coin toss', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
