BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (67030233,3,0,63,8225,4000,3000,10,8192,32,-2130436062);
INSERT OR REPLACE INTO "texts" VALUES (67030233, 'Majestic Red Dragon', '"Majestic Dragon" + "Red Dragon Archfiend" + 1 non-Tuner monster
 This card cannot be destroyed by card effects. If this card attacks, destroy all Defense Position monsters on the field after damage calculation. Once per turn, you can negate the effect(s) of 1 face-up monster your opponent controls and have this card gain ATK equal to the negated monster''s ATK, until the End Phase. During the End Phase, return this card from the field to the Extra Deck, and Special Summon 1 "Red Dragon Archfiend" from your Graveyard.', 'Destroy all Defense Position monsters', 'Negate effect', '返回额外卡组', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40044918,3,0,12296,33,1800,300,4,1,8,513);
INSERT OR REPLACE INTO "texts" VALUES (40044918, 'Elemental HERO Stratos', 'When this card is Normal or Special Summoned: You can activate 1 of these effects.
● You can destroy Spell/Trap Cards on the field, up to the number of "HERO" monsters you control, except this card.
● Add 1 "HERO" monster from your Deck to your hand.', 'Select effect', 'You destroy Spell/Trap Cards on the field, up to the number of other "HERO" monsters you control.', 'Add 1 "HERO" monster from your Deck to your hand.', 'Do you want to destroy Spell/Trap Cards on the field?', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24857466,3,0,0,33,2800,2500,8,8192,32,-2143027197);
INSERT OR REPLACE INTO "texts" VALUES (24857466, 'Van''Dalgyon the Dark Dragon Lord', 'After a Counter Trap Card you control negates the activation of an opponent''s card(s) or effect(s), you can Special Summon this card from your hand. Then activate the appropriate effects, based on the type of cards negated:
● Spell: Inflict 1500 damage to your opponent.
● Trap: Select and destroy 1 card your opponent controls.
● Effect Monster: Select 1 monster in your Graveyard and Special Summon it.', 'Special Summon', 'Inflict 1500 damage to your opponent', 'Select and destroy 1 card your opponent controls', 'Select 1 monster in your Graveyard and Special Summon it', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39439590,3,0,147,33,2500,1900,7,32,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (39439590, 'Cyber Dinosaur', 'When your opponent Special Summons a monster from their hand, you can Special Summon this card from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19665973,3,0,0,33,0,0,1,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (19665973, 'Battle Fader', 'When your opponent''s monster declares a direct attack: You can Special Summon this card from your hand, then end the Battle Phase. If this card is Special Summoned with this effect, banish it when it leaves the field.', '结束战斗阶段', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9012916,3,0,0,8225,2800,1600,8,8192,32,71311360);
INSERT OR REPLACE INTO "texts" VALUES (9012916, 'Black-Winged Dragon', '1 Tuner + 1 or more non-Tuner monsters 

Whenever you would take damage from a card effect, place 1 Black Feather Counter on this card instead. This card loses 700 ATK for each Black Feather Counter on it. Once per turn, you can remove all Black Feather Counters on this card to have 1 face-up monster your opponent controls lose 700 ATK for each Black Feather Counter, and inflict damage to your opponent equal to the ATK lost by that monster because of this effect.', 'Lower attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46668237,3,0,0,33,2600,1800,7,16384,1,1310720);
INSERT OR REPLACE INTO "texts" VALUES (46668237, 'Green Baboon, Defender of the Forest', 'When a Beast-Type monster you control is destroyed and sent to the Graveyard, you can pay 1000 Life Points to Special Summon this card from your hand or the Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57793869,3,0,0,33,-2,-2,10,8,32,8195);
INSERT OR REPLACE INTO "texts" VALUES (57793869, 'The Wicked Eraser', 'This card cannot be Special Summoned. This card cannot be Normal Summoned or Set except by Tributing 3 monsters. The ATK and DEF of this card are each equal to the number of cards your opponent controls × 1000. When this card is destroyed and sent to the Graveyard, destroy all cards on the field. During your Main Phase, you can destroy this card.', '场上的卡全部破坏', 'Self-destruct', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72714392,3,0,51,4129,800,0,1,512,32,-1610350588);
INSERT OR REPLACE INTO "texts" VALUES (72714392, 'Blackwing - Vayu the Emblem of Honor', 'If this card is face-up on the field, you cannot use it for a Synchro Summon. If this card is in your Graveyard, you can remove from play this card plus 1 non-Tuner "Blackwing" monster in your Graveyard, and Special Summon 1 "Blackwing" Synchro Monster from your Extra Deck whose Level equals the total Levels of the removed monsters. The effect(s) of that Synchro Monster is negated.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79229522,3,0,259,97,0,0,8,32,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (79229522, 'Chimeratech Fortress Dragon', '"Cyber Dragon" + 1 or more Machine-Type monsters.
This monster cannot be used as a Fusion Material Monster. You can only Special Summon this card from your Extra Deck by sending the above cards from either side of the field to the Graveyard. (You do not use "Polymerization".) The original ATK of this card is equal to 1000 x the number of Fusion Material Monsters used to Special Summon it.', 'Please select a "Cyber Dragon"', 'Please select 1 or more Machine-Type monsters', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14017402,3,0,257,97,3200,2000,10,8192,8,542113796);
INSERT OR REPLACE INTO "texts" VALUES (14017402, 'Dragon Knight Draco-Equiste', '1 Dragon-Type Synchro Monster + 1 Warrior-Type Monster.
This monster can only be Special Summoned by Fusion Summon (from the Extra Deck). Once per turn, you can select 1 Dragon-Type Synchro Monster in the Graveyard. Remove it from play, treat this card''s name as that monster''s name, and give this card the same effects as that monster, until the End Phase. While this card is in face-up Attack Position, any effect damage you would take from an opponent''s card effect is inflicted to your opponent instead.', '获得龙族同调怪兽效果', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50287060,3,0,69,33,2200,2500,6,8,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (50287060, 'Archfiend of Gilfer', 'When this card is sent to the Graveyard: You can target 1 face-up monster on the field; equip that target with this card. That monster loses 500 ATK while equipped with this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62180201,3,0,0,33,4000,4000,10,8,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (62180201, 'The Wicked Dreadroot', 'This card cannot be Special Summoned. This card cannot be Normal Summoned or Set except by Tributing 3 monsters. Halve the ATK and DEF of all monsters on the field, except this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65192027,3,0,0,33,2800,1000,7,8192,32,2359303);
INSERT OR REPLACE INTO "texts" VALUES (65192027, 'Dark Armed Dragon', 'Cannot be Normal Summoned or Set. Must be Special Summoned (from your hand) by having exactly 3 DARK monsters in your Graveyard and cannot be Special Summoned by other ways. You can banish 1 DARK monster from your Graveyard to target 1 card on the field; destroy that target.', '不能通常召唤', '墓地暗属性三张时才能特殊召唤', '破坏场上一张卡', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38109772,3,0,0,33,2800,2300,7,8192,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (38109772, 'Dragonic Knight', 'When the effect of an opponent''s monster is activated that targets and destroys a card(s) you control, you can send the targeted card(s) to the Graveyard to Special Summon this card from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
