BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (41855169,3,0,0,33,200,1300,3,2,16,10);
INSERT OR REPLACE INTO "texts" VALUES (41855169, 'Jowgen the Spiritualist', 'Discard 1 random card from your hand to the Graveyard to destroy all Special Summoned monsters on the field. As long as this card remains face-up on the field, no monsters can be Special Summoned.', '特殊召唤的怪兽全部破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88240808,3,0,0,33,1800,700,4,2,32,4);
INSERT OR REPLACE INTO "texts" VALUES (88240808, 'Kycoo the Ghost Destroyer', 'When this card inflicts battle damage to your opponent: You can target up to 2 monsters in their Graveyard; banish those targets. Your opponent cannot banish cards from either player''s Graveyard.', 'Select up to 2 monsters to banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40133511,3,0,0,33,1600,900,4,16384,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (40133511, 'Bazoo the Soul-Eater', 'Once per turn: You can banish up to 3 monsters from your Graveyard; this card gains 300 ATK for each, until the end of your opponent''s turn.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31829185,3,0,0,33,2200,2800,8,8,32,266240);
INSERT OR REPLACE INTO "texts" VALUES (31829185, 'Dark Necrofear', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by banishing 3 Fiend-Type monsters from your Graveyard. During the End Phase, if this card was destroyed by an opponent''s card this turn (either by battle or by card effect) and sent to the Graveyard while it was a Monster Card in your possession: Target 1 face-up monster your opponent controls; equip this card from the Graveyard to that target. While this card is equipped to a monster by this effect, take control of that monster.', 'Take control', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77527210,3,0,0,33,2000,1800,6,4,16,2367488);
INSERT OR REPLACE INTO "texts" VALUES (77527210, 'Soul of Purity and Light', 'This card cannot be Normal Summoned or Set. This card can only be Special Summoned by removing from play 2 LIGHT monsters in your Graveyard. All monsters your opponent controls lose 300 ATK during their Battle Phase only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40916023,3,0,0,33,1600,1200,4,64,2,2361344);
INSERT OR REPLACE INTO "texts" VALUES (40916023, 'Aqua Spirit', 'This card cannot be Normal Summoned or Set. This card can only be Special Summoned by removing 1 WATER monster in your Graveyard from play. During each of your opponent''s Standby Phases, you can change the battle position of 1 of your opponent''s face-up Monster Cards. Once changed, the monster must remain in this position for the rest of the turn.', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76305638,3,0,0,33,1700,1000,4,256,1,2367488);
INSERT OR REPLACE INTO "texts" VALUES (76305638, 'The Rock Spirit', 'This card cannot be Normal Summoned or Set. This card can only be Special Summoned by removing 1 EARTH monster in your Graveyard from play. Increase the ATK of this monster by 300 points during your opponent''s Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45894482,3,0,0,33,1400,400,3,65536,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (45894482, 'Gilasaurus', 'You can Special Summon this card (from your hand). When you do: Your opponent can target 1 monster in their Graveyard; your opponent Special Summons that target to their side of the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71283180,3,0,0,2097185,1100,1000,4,512,8,16);
INSERT OR REPLACE INTO "texts" VALUES (71283180, 'Tornado Bird', 'FLIP: Return 2 Spell or Trap Cards on the field to their owners'' hands.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88472456,3,0,0,33,2100,500,4,1,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (88472456, 'Zombyra the Dark', 'This card cannot attack your opponent directly. If this card destroys a monster by battle: This card loses 200 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71466592,3,0,0,33,900,900,3,64,2,-2147483639);
INSERT OR REPLACE INTO "texts" VALUES (71466592, 'Maryokutai', 'You can only activate this card''s effect during your opponent''s turn. When your opponent activates a Spell Card, Tribute this face-up card to negate the activation of the Spell Card and destroy it.', '魔法的发动无效并破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86099788,3,0,0,97,2350,2300,7,1,1,2);
INSERT OR REPLACE INTO "texts" VALUES (86099788, 'The Last Warrior from Another Planet', '"Zombyra the Dark" + "Maryokutai"
When this card is Special Summoned, destroy all monsters on your side of the field except this card. As long as this card remains face-up on the field, neither player can Normal Summon, Flip Summon, or Special Summon any monster.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93599951,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (93599951, 'Dark Spirit of the Silent', 'Activate only when an opponent''s monster declares an attack. Negate that attack, and select another face-up monster your opponent controls. That monster attacks instead. (If it is in face-up Defense Position, change it to Attack Position.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33950246,3,0,0,131076,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (33950246, 'Royal Command', 'Flip monsters'' effects cannot be activated, also their effects are negated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70344351,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (70344351, 'Riryoku Field', 'When a Spell Card that targets exactly 1 monster on the field (and no other cards) is activated: Negate the activation, and if you do, destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6733059,3,0,0,131076,0,0,0,0,0,6);
INSERT OR REPLACE INTO "texts" VALUES (6733059, 'Skull Lair', 'Remove from play any number of Monster Cards in your Graveyard to destroy 1 face-up monster on the field whose Level is equal to the number of the cards you removed from play.', 'Activate the effect of "Skull Lair"?', 'Destroy', 'Please select the number of monsters to banish', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33737664,3,0,0,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (33737664, 'Graverobber''s Retribution', 'During each of your Standby Phases, inflict 100 points of damage to your opponent''s Life Points for each of your opponent''s monsters that have been removed from play.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5616412,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (5616412, 'Destruction Punch', 'If the ATK of an attacking monster on your opponent controls is lower than the DEF of the attacked Defense Position monster, destroy the attacking monster at the end of the Damage Step. (Damage calculation is applied normally.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32015116,3,0,0,131076,0,0,0,0,0,134217730);
INSERT OR REPLACE INTO "texts" VALUES (32015116, 'Blind Destruction', 'Once per turn, during your Standby Phase: Roll a six-sided die. If the result is 1-5, destroy all monsters on the field with the same Level as the number rolled. If it is 6, destroy all Level 6 and higher monsters on the field.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68400115,3,0,0,131076,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (68400115, 'The Emperor''s Holiday', 'Negate all Equip Card effects on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94212438,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (94212438, 'Destiny Board', 'At the end of each of your opponent''s turns, place 1 "Spirit Message" card from your hand or your Deck face-up on the field. If you control the "Spirit Message" cards "I", "N", "A", and "L" in the proper order, you win the Duel. If any "Spirit Message" cards or "Destiny Board" you control is removed from the field, all "Spirit Message" cards and "Destiny Board" you control are sent to the Graveyard.', 'カードを出す', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31893528,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (31893528, 'Spirit Message "I"', 'This card can only be placed on the field by the effect of "Destiny Board."', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67287533,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (67287533, 'Spirit Message "N"', 'This card can only be placed on the field by the effect of "Destiny Board."', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94772232,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (94772232, 'Spirit Message "A"', 'This card can only be placed on the field by the effect of "Destiny Board."', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30170981,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (30170981, 'Spirit Message "L"', 'This card can only be placed on the field by the effect of "Destiny Board."', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30606547,3,0,0,131074,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (30606547, 'The Dark Door', 'Both players can only attack with 1 monster during their respective Battle Phases.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15866454,3,0,0,2,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (15866454, 'Spiritualism', 'Return 1 Spell or Trap Card on your opponent''s side of the field to his/her hand. This card''s activation and effect cannot be negated by any other card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5494820,3,0,0,262146,0,0,0,0,0,16384);
INSERT OR REPLACE INTO "texts" VALUES (5494820, 'Cyclon Laser', 'You can only equip this card to "Gradius". Increase the ATK of "Gradius" by 300 points. When the equipped "Gradius" attacks with an ATK that is higher than the DEF of a Defense Position monster, inflict the difference as Battle Damage to your opponent''s Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95286165,3,0,70,65538,0,0,0,0,0,262176);
INSERT OR REPLACE INTO "texts" VALUES (95286165, 'De-Fusion', 'Select 1 face-up Fusion Monster on the field and return it to the Extra Deck. If all the Fusion Material Monsters that were used for the Fusion Summon of that Fusion Monster are in your Graveyard, you can Special Summon them.', 'Special Summon Fusion Material Monsters?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33550694,3,0,70,524290,0,0,0,0,0,268697604);
INSERT OR REPLACE INTO "texts" VALUES (33550694, 'Fusion Gate', 'While this card is on the field: Either player can Fusion Summon a Fusion Monster without using "Polymerization", but the Fusion Material Monsters are banished instead of being sent to the Graveyard.', '融合召唤', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69954399,3,0,0,262146,0,0,0,0,0,66578);
INSERT OR REPLACE INTO "texts" VALUES (69954399, 'Ekibyo Drakmord', 'The equipped monster cannot attack. Destroy the equipped monster at the end of its controller''s 2nd turn after this card is activated. At that time, this card is returned to the owner''s hand.', 'Destroy', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6343408,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (6343408, 'Miracle Dig', 'If 5 or more of your monsters are currently removed from play, return 3 of them to the Graveyard.', 'Return to Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95220856,3,0,0,131074,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (95220856, 'Vengeful Bog Spirit', 'Monsters cannot attack the turn they are Summoned.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39507162,3,0,0,33,1600,1000,4,1,16,-2147475456);
INSERT OR REPLACE INTO "texts" VALUES (39507162, 'Blade Knight', 'While you have 1 or less cards in your hand, this card gains 400 ATK. If you control no other monsters, negate the effects of Flip Effect Monsters destroyed by battle with this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88819587,3,0,0,17,1200,700,3,8192,8,0);
INSERT OR REPLACE INTO "texts" VALUES (88819587, 'Baby Dragon', 'Much more than just a child, this dragon is gifted with untapped power.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87564352,3,0,0,17,1500,800,4,8192,32,0);
INSERT OR REPLACE INTO "texts" VALUES (87564352, 'Blackland Fire Dragon', 'A dragon that dwells in the depths of darkness, its vulnerability lies in its poor eyesight.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18246479,3,0,0,17,1800,1300,5,32768,1,0);
INSERT OR REPLACE INTO "texts" VALUES (18246479, 'Battle Steer', 'A bull monster often found in the woods, it charges enemy monsters with a pair of deadly horns.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71625222,3,0,0,33,500,400,2,2,16,138412034);
INSERT OR REPLACE INTO "texts" VALUES (71625222, 'Time Wizard', 'Once per turn: You can toss a coin and call it. If you call it right, destroy all monsters your opponent controls. If you call it wrong, destroy all monsters you control, and if you do, you take damage equal to half the total ATK that those destroyed monsters had on the field.', 'Toss coin', 'Please select head or tails', 'Reversed', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66602787,3,0,0,17,600,1500,3,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (66602787, 'Saggi the Dark Clown', 'This clown appears from nowhere and executes very strange moves to avoid enemy attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55763552,3,0,0,2097185,200,1800,3,128,4,2049);
INSERT OR REPLACE INTO "texts" VALUES (55763552, 'Dragon Piper', 'FLIP: Destroy all face-up "Dragon Capture Jar"(s) on the field. If you destroy any, change all face-up Dragon-Type monsters on the field to Attack Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28546905,3,0,0,17,1200,2200,5,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (28546905, 'Illusionist Faceless Mage', 'Manipulates enemy attacks with the power of illusion.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26202165,3,0,0,33,1000,600,3,8,32,512);
INSERT OR REPLACE INTO "texts" VALUES (26202165, 'Sangan', 'When this card is sent from the field to the Graveyard: Add 1 monster with 1500 or less ATK from your Deck to your hand.', 'Search card group', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14141448,3,0,0,33,2600,2500,8,2048,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (14141448, 'Great Moth', 'This monster cannot be Normal Summoned or Set. This card can only be Special Summoned by Tributing "Petit Moth" on the 4th of your turns after "Petit Moth" has been equipped with "Cocoon of Evolution".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40640057,3,0,0,33,300,200,1,8,32,8);
INSERT OR REPLACE INTO "texts" VALUES (40640057, 'Kuriboh', 'uring your opponent''s turn, at damage calculation: You can discard this card; you take no battle damage from that battle (this is a Quick Effect).', 'Reduce damage to 0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41462083,3,0,0,65,2400,2000,7,8192,8,0);
INSERT OR REPLACE INTO "texts" VALUES (41462083, 'Thousand Dragon', '"Time Wizard" + "Baby Dragon"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69455834,3,0,0,17,2000,1530,5,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (69455834, 'King of Yamimakai', 'Wields the power of darkness to destroy its enemies.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95727991,3,0,0,33,1000,2000,5,64,2,4194304);
INSERT OR REPLACE INTO "texts" VALUES (95727991, 'Catapult Turtle', 'Once per turn: You can Tribute 1 monster; inflict damage to your opponent equal to half the Tributed monster''s ATK on the field.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68516705,3,0,0,17,1300,1550,4,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (68516705, 'Mystic Horseman', 'Half man and half horse, this monster is known for its extreme speed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94905343,3,0,0,65,2000,1700,6,32768,1,0);
INSERT OR REPLACE INTO "texts" VALUES (94905343, 'Rabid Horseman', '"Battle Ox" + "Mystic Horseman"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93889755,3,0,0,33,1350,1400,4,8,32,16);
INSERT OR REPLACE INTO "texts" VALUES (93889755, 'Crass Clown', 'When this card is changed from Defense Position to Attack Position, return 1 monster on your opponent''s side of the field to the owner''s hand.', '对方1只怪兽回到手牌', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13215230,3,0,0,33,1200,900,3,1,1,2);
INSERT OR REPLACE INTO "texts" VALUES (13215230, 'Dream Clown', 'When this card is changed from Attack Position to Defense Position, destroy 1 monster on your opponent''s side of the field.', '破坏对方场上1只怪兽', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51371017,3,0,0,2097185,900,700,3,1,8,4194304);
INSERT OR REPLACE INTO "texts" VALUES (51371017, 'Princess of Tsurugi', 'FLIP: Inflict 500 damage to your opponent for each Spell and Trap Card on your opponent''s side of the field.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46918794,3,0,0,2,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (46918794, 'Tremendous Fire', 'Inflict 1000 points of damage to your opponent''s Life Points and 500 points of damage to your Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94773007,3,0,0,33,2200,100,4,2048,1,134225920);
INSERT OR REPLACE INTO "texts" VALUES (94773007, 'Jirai Gumo', 'When this card declares an attack: Toss a coin and call it. If you call it wrong, lose half your Life Points.', 'Coin toss', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30778711,3,0,0,33,1600,1300,5,16,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (30778711, 'Shadow Ghoul', 'This card gains 100 ATK for each monster in your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24611934,3,0,0,17,1600,1200,4,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (24611934, 'Ryu-Kishin Powered', 'A gargoyle enhanced by the powers of darkness. Very sharp talons make it a worthy opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87322377,3,0,0,17,2200,2500,7,32,4,0);
INSERT OR REPLACE INTO "texts" VALUES (87322377, 'Launcher Spider', 'A mechanical spider with rocket launchers capable of random fire.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31786629,3,0,0,33,1600,1500,5,4096,16,512);
INSERT OR REPLACE INTO "texts" VALUES (31786629, 'Thunder Dragon', 'You can discard this card to add up to 2 "Thunder Dragons" from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84926738,3,0,0,2097185,1500,1300,4,4096,16,12582912);
INSERT OR REPLACE INTO "texts" VALUES (84926738, 'The Immortal of Thunder', 'FLIP: Increase your Life Points by 3000 points. When this card is sent from the field to the Graveyard, you lose 5000 Life Points.', 'LP回复', 'LP失去', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67629977,3,0,0,33,500,700,2,4,16,2105344);
INSERT OR REPLACE INTO "texts" VALUES (67629977, 'Hoshiningen', 'As long as this card remains face-up on the field, increase the ATK of all LIGHT monsters by 500 points and decrease the ATK of all DARK monsters by 400 points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11384280,3,0,0,33,1400,1300,4,32,32,4194304);
INSERT OR REPLACE INTO "texts" VALUES (11384280, 'Cannon Soldier', 'You can Tribute 1 monster to inflict 500 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46657337,3,0,0,33,600,300,2,256,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (46657337, 'Muka Muka', 'This card gains 300 ATK and DEF for each card in your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71107816,3,0,0,33,1800,1000,4,8,32,256);
INSERT OR REPLACE INTO "texts" VALUES (71107816, 'The Bistro Butcher', 'When this card inflicts Battle Damage to your opponent''s Life Points, your opponent draws 2 cards from their Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8201910,3,0,0,33,550,500,2,64,2,2105344);
INSERT OR REPLACE INTO "texts" VALUES (8201910, 'Star Boy', 'As long as this card remains face-up on the field, increase the ATK of all WATER monsters by 500 points and decrease the ATK of all FIRE monsters by 400 points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7489323,3,0,0,33,300,250,1,16384,1,2105344);
INSERT OR REPLACE INTO "texts" VALUES (7489323, 'Milus Radiant', 'As long as this card remains face-up on the field, increase the ATK of all EARTH monsters by 500 points and decrease the ATK of all WIND monsters by 400 points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78010363,3,0,0,33,1100,1200,4,2,32,512);
INSERT OR REPLACE INTO "texts" VALUES (78010363, 'Witch of the Black Forest', 'When this card is sent from the field to the Graveyard: Add 1 monster with 1500 or less DEF from your Deck to your hand.', 'Search card group', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68658728,3,0,0,33,600,550,2,16384,4,2105344);
INSERT OR REPLACE INTO "texts" VALUES (68658728, 'Little Chimera', 'All FIRE monsters on the field gain 500 ATK. All WATER monsters on the field lose 400 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28470714,3,0,0,33,600,700,2,2048,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (28470714, 'Bladefly', 'As long as this card remains face-up on the field, increase the ATK of all WIND monsters by 500 points and decrease the ATK of all EARTH monsters by 400 points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54752875,3,0,0,65,2800,2100,7,4096,16,0);
INSERT OR REPLACE INTO "texts" VALUES (54752875, 'Twin-Headed Thunder Dragon', '"Thunder Dragon" + "Thunder Dragon"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80741828,3,0,0,33,550,500,2,2,32,2105344);
INSERT OR REPLACE INTO "texts" VALUES (80741828, 'Witch''s Apprentice', 'As long as this card remains face-up on the field, increase the ATK of all DARK monsters by 500 points and decrease the ATK of all LIGHT monsters]by 400 points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5818798,3,0,27,17,1500,1200,4,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (5818798, 'Gazelle the King of Mythical Beasts', 'This monster moves so fast that it looks like an illusion to mortal eyes.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81480460,3,0,0,33,2600,2200,7,32,32,134217730);
INSERT OR REPLACE INTO "texts" VALUES (81480460, 'Barrel Dragon', 'Once per turn: You can target 1 monster your opponent controls; toss a coin 3 times and destroy it if at least 2 of the results are Heads.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41420027,3,0,0,1048580,0,0,0,0,0,-2147483645);
INSERT OR REPLACE INTO "texts" VALUES (41420027, 'Solemn Judgment', 'When a monster would be Summoned, OR a Spell/Trap Card is activated: Pay half your Life Points; negate the Summon or activation, and if you do, destroy that card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77414722,3,0,0,1048580,0,0,0,0,0,-2147483639);
INSERT OR REPLACE INTO "texts" VALUES (77414722, 'Magic Jammer', 'When a Spell Card is activated: Discard 1 card; negate the activation, and if you do, destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3819470,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (3819470, 'Seven Tools of the Bandit', 'When a Trap Card is activated: Pay 1000 LP; negate the activation, and if you do, destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98069388,3,0,0,1048580,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (98069388, 'Horn of Heaven', 'When a monster would be Summoned: Tribute 1 monster; negate the Summon, and if you do, destroy that monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52097679,3,0,0,2,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (52097679, 'Shield  Sword', 'Switch the original ATK and DEF of all face-up monsters currently on the field, until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25880422,3,0,0,2,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (25880422, 'Block Attack', 'Select 1 face-up Attack Position monster on your opponent''s side of the field and change it to Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51275027,3,0,0,33,0,100,1,2,16,65536);
INSERT OR REPLACE INTO "texts" VALUES (51275027, 'The Unhappy Maiden', 'When this card is sent to the Graveyard as a result of battle, the Battle Phase for that turn ends immediately.', '结束战斗阶段', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88279736,3,0,172,131076,0,0,0,0,0,64);
INSERT OR REPLACE INTO "texts" VALUES (88279736, 'Robbin'' Goblin', 'Each time a monster you control inflicts Battle Damage to your opponent, your opponent discards 1 random card.', '对方随机丢弃1张手牌', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44095762,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (44095762, 'Mirror Force', 'When an opponent''s monster declares an attack: Destroy all Attack Position monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20436034,3,0,0,262146,0,0,0,0,0,73728);
INSERT OR REPLACE INTO "texts" VALUES (20436034, 'Ring of Magnetism', 'You can only equip this card to a monster on your side of the field. Decrease the ATK and DEF of a monster equipped with this card by 500 points. In addition, all the monsters on your opponents side of the field can only attack the monster equipped with this card, if they attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56830749,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (56830749, 'Share the Pain', 'Tribute 1 monster; make your opponent Tribute 1 monster (for no effect).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19613556,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (19613556, 'Heavy Storm', 'Destroy all Spell and Trap Cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27324313,3,0,14,17,1000,500,3,4096,16,0);
INSERT OR REPLACE INTO "texts" VALUES (27324313, 'Wattkid', 'A creature that electrocutes opponents with bolts of lightning.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47852924,3,0,0,2,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (47852924, 'Soul of the Pure', 'Increases your Life Points by 800 points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45895206,3,0,0,2,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (45895206, 'Dark-Piercing Light', 'Flip all face-down monsters on your opponent''s side of the field face-up.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10262698,3,0,0,17,1100,1400,4,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (10262698, 'The Statue of Easter Island', 'A stone monument from Easter Island that launches laser blasts from its rock-hewn lips.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82085619,3,0,0,17,1300,1100,4,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (82085619, 'Shining Friendship', 'The peacemaker among monsters.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6285791,3,0,62,33,1400,700,3,16384,1,16);
INSERT OR REPLACE INTO "texts" VALUES (6285791, 'The Wicked Worm Beast', 'This face-up card on the field is returned to the owner''s hand during the End Phase of your turn.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49791927,3,0,0,17,1300,1100,4,32768,1,0);
INSERT OR REPLACE INTO "texts" VALUES (49791927, 'Tiger Axe', 'A fast and powerful axe-wielding beast-warrior.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48305365,3,0,0,17,1700,1150,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (48305365, 'Axe Raider', 'An axe-wielding monster of tremendous strength and agility.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7359741,3,0,0,17,1850,800,4,32,32,0);
INSERT OR REPLACE INTO "texts" VALUES (7359741, 'Mechanicalchaser', 'A hunter that relentlessly pursues its target by order of the Machine King.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69140098,3,0,0,17,1900,900,4,2,1,0);
INSERT OR REPLACE INTO "texts" VALUES (69140098, 'Gemini Elf', 'Elf twins that alternate their attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79571449,3,0,0,2,0,0,0,0,0,264);
INSERT OR REPLACE INTO "texts" VALUES (79571449, 'Graceful Charity', 'Draw 3 cards, then discard 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94119974,3,0,0,17,1600,1200,4,65536,1,0);
INSERT OR REPLACE INTO "texts" VALUES (94119974, 'Two-Headed King Rex', 'A powerful monster whose two heads attack as one.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53493204,3,0,0,33,1200,1000,4,4,16,268435456);
INSERT OR REPLACE INTO "texts" VALUES (53493204, 'Goddess with the Third Eye', 'You can substitute this card for any 1 Fusion Material Monster. When you do this, the other Fusion Material Monster(s) must be the correct one(s).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99510761,3,0,0,17,1400,1200,4,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (99510761, 'Lord of the Lamp', 'This spirit emerges from the mystic lamp and obeys the wishes of its summoner.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46700124,3,0,0,33,2200,2000,6,32,1,1056768);
INSERT OR REPLACE INTO "texts" VALUES (46700124, 'Machine King', 'This card gains 100 ATK for each Machine-Type monster on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69015963,3,0,147,33,700,500,2,32,32,268697600);
INSERT OR REPLACE INTO "texts" VALUES (69015963, 'Cyber-Stein', 'Pay 5000 Life Points. Special Summon 1 Fusion Monster from your Fusion Deck to the field in Attack Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28563545,3,0,0,33,2000,2100,6,8,32,2);
INSERT OR REPLACE INTO "texts" VALUES (28563545, 'Dragon Seeker', 'When this card is Normal Summoned or Flip Summoned, destroy 1 face-up Dragon-Type monster on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81843628,3,0,62,2097185,750,600,2,2048,1,136);
INSERT OR REPLACE INTO "texts" VALUES (81843628, 'Needle Worm', 'FLIP: Send the top 5 cards of your opponent''s Deck to the Graveyard.
', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61831093,3,0,0,2097185,650,900,3,1,32,1);
INSERT OR REPLACE INTO "texts" VALUES (61831093, 'Greenkappa', 'FLIP: Target 2 Set Spell/Trap Cards on the field; destroy those targets.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33508719,3,0,0,2097185,700,600,2,256,1,264);
INSERT OR REPLACE INTO "texts" VALUES (33508719, 'Morphing Jar', 'FLIP: Both players discard all the cards in their hands, then draw 5 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93920745,3,0,90,2097185,750,500,2,64,2,16);
INSERT OR REPLACE INTO "texts" VALUES (93920745, 'Penguin Soldier', 'FLIP: You can target up to 2 monsters on the field; return those targets to the hand.', 'Return to hand', 'Return Monster Cards to hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51452091,3,0,0,131076,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (51452091, 'Royal Decree', 'Negate the effects of all other Trap Cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53119267,3,0,0,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (53119267, 'Magical Thorn', 'When your opponent''s card(s) in their hand are discarded to the Graveyard, inflict 500 points of damage to their Life Points for each card that was discarded.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99518961,3,0,0,2,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (99518961, 'Restructer Revolution', 'Inflict 200 points of damage to your opponent''s Life Points for each card in your opponent''s hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26902560,3,0,70,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (26902560, 'Fusion Sage', 'Add 1 "Polymerization" card from your Deck to your hand. Then shuffle your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75372290,3,0,0,33,1550,2500,6,1,32,2048);
INSERT OR REPLACE INTO "texts" VALUES (75372290, 'Total Defense Shogun', 'This card is changed to Defense Position when it is Normal Summoned or Flip Summoned successfully. This card can attack while it is in Defense Position. If this card attacks while in Defense Position, apply the ATK of this card for damage calculation.', 'Change to defense position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16589042,3,0,189,33,2300,2100,7,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (16589042, 'Swift Gaia the Fierce Knight', 'If this is the only card in your hand, you can Normal Summon it without Tributing.', 'リリースなしで召喚', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52077741,3,0,0,33,1400,1200,4,1,1,16777216);
INSERT OR REPLACE INTO "texts" VALUES (52077741, 'Obnoxious Celtic Guard', 'This card cannot be destroyed by battle with a monster that has 1900 or more ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57482479,3,0,0,33,2100,1400,5,1,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (57482479, 'Luminous Soldier', 'If this card battles with a DARK monster, increase the ATK of this card by 500 points during the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10375182,3,0,0,33,1200,1900,4,1,4,73728);
INSERT OR REPLACE INTO "texts" VALUES (10375182, 'Command Knight', 'While at least 1 other monster exists on your side of the field, your opponent cannot select this card as an attack target. Also, while this card remains face-up on the field, increase the ATK of all your Warrior-Type monsters by 400 points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17444133,3,0,0,33,1700,1650,4,262144,16,2097152);
INSERT OR REPLACE INTO "texts" VALUES (17444133, 'Kaiser Sea Horse', 'This card can be treated as 2 Tributes for the Tribute Summon of a LIGHT monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53839837,3,0,142,33,2000,1500,5,16,32,262280);
INSERT OR REPLACE INTO "texts" VALUES (53839837, 'Vampire Lord', 'When this card inflicts battle damage to your opponent: Declare 1 card type (Monster, Spell, or Trap); your opponent sends 1 card of that type from their Deck to the Graveyard. During your next Standby Phase after this card in your possession was destroyed and sent to your Graveyard by an opponent''s card effect: Special Summon this card from the Graveyard.', 'Card to send to Graveyard', 'Monster card', 'Spell card', 'Trap card', 'Special Summon', 'Please declare the type of card', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15270885,3,0,11272290,4194337,2300,0,4,1,1,395264);
INSERT OR REPLACE INTO "texts" VALUES (15270885, 'Toon Goblin Attack Force', 'This card cannot attack during the turn that it is Normal Summoned, Flip Summoned, or Special Summoned. When "Toon World" on the field is destroyed, this card is also destroyed. If "Toon World" is on your side of the field and your opponent does not control a Toon Monster, this card can attack your opponent''s Life Points directly. If this card attacks, it is changed to Defense Position at the end of the Battle Phase, and you cannot change this Battle Position until the end of your next turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79875176,3,0,98,4194337,1400,1300,4,32,32,4325888);
INSERT OR REPLACE INTO "texts" VALUES (79875176, 'Toon Cannon Soldier', 'This card cannot attack during the turn that it is Normal Summoned, Flip Summoned, or Special Summoned. When "Toon World" on the field is destroyed, destroy this card. If "Toon World" is on your side of the field and your opponent does not control a Toon Monster, this card can attack your opponent''s Life Points directly. Tribute 1 monster on your side of the field to inflict 500 points of damage to your opponent''s Life Points.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42386471,3,0,98,4194337,1900,900,4,2,1,131136);
INSERT OR REPLACE INTO "texts" VALUES (42386471, 'Toon Gemini Elf', 'This card cannot attack the turn it is Summoned. If "Toon World" on the field is destroyed, destroy this card. While you control "Toon World" and your opponent controls no Toon Monsters, this card can attack your opponent directly. When this card inflicts battle damage to your opponent: Discard 1 random card from your opponent''s hand.', 'Discard hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16392422,3,0,98,4194337,900,1400,4,2,32,393472);
INSERT OR REPLACE INTO "texts" VALUES (16392422, 'Toon Masked Sorcerer', 'This card cannot attack during the turn that it is Normal Summoned, Flip Summoned, or Special Summoned. When "Toon World" on the field is destroyed, destroy this card. If "Toon World" is on your side of the field and your opponent does not control a Toon Monster, this card can attack your opponent''s Life Points directly. When this card inflicts Battle Damage to your opponent''s Life Points, draw 1 card from your Deck.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89997728,3,0,98,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (89997728, 'Toon Table of Contents', 'Add 1 card from your Deck to your hand that includes "Toon" in its card name, or is named "Manga Ryu-Ran".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43509019,3,0,98,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (43509019, 'Toon Defense', 'When your opponent''s monster attacks a face-up Level 4 or lower Toon Monster on your side of the field, you can make the attack a direct attack to your Life Points.', '改变攻击对象', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91512835,3,0,0,33,2200,2400,7,2048,1,794624);
INSERT OR REPLACE INTO "texts" VALUES (91512835, 'Insect Queen', 'This card cannot declare an attack unless you Tribute 1 monster. This card gains 200 ATK for each Insect-Type monster on the field. During the End Phase, if this card destroyed an opponent''s monster by battle this turn: Special Summon 1 "Insect Monster Token" (Insect-Type/EARTH/Level 1/ATK 100/DEF 100) in Attack Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53982768,3,0,0,33,2450,1600,6,8,32,-2146435072);
INSERT OR REPLACE INTO "texts" VALUES (53982768, 'Dark Ruler Ha Des', 'Cannot be Special Summoned from the Graveyard. Negate the effects of monsters destroyed by battle with Fiend-Type monsters you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80071763,3,0,109,97,2000,1200,5,8,32,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (80071763, 'Dark Balter the Terrible', '"Possessed Dark Soul" + "Frontier Wiseman"
A Fusion Summon of this monster can only be conducted with the above Fusion Material Monsters. When a Normal Spell Card is activated, negate the effect by paying 1000 Life Points. The effect of an Effect Monster that this monster destroys as a result of battle is negated.', 'Negate effect', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16475472,3,0,69,33,2100,1000,5,8,32,4);
INSERT OR REPLACE INTO "texts" VALUES (16475472, 'Lesser Fiend', '(This card is always treated as an "Archfiend" card.)
Banish any monster destroyed by battle with this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52860176,3,0,0,33,1200,800,3,8,32,4096);
INSERT OR REPLACE INTO "texts" VALUES (52860176, 'Possessed Dark Soul', 'You can Tribute this face-up card; take control of all face-up Level 3 or lower monsters your opponent currently controls.', '得到控制权', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89258225,3,0,0,33,700,700,2,8,32,1056768);
INSERT OR REPLACE INTO "texts" VALUES (89258225, 'Winged Minion', 'Tribute this face-up card. Select 1 face-up Fiend-Type monster on the field. Increase the ATK and DEF of the monster by 700 points as long as it remains face-up on the field.', 'Increase ATK and DEF', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15653824,3,0,0,33,1000,1200,3,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (15653824, 'Skull Knight 2', 'If you Tribute Summon a Fiend-Type monster by Tributing this monster, Special Summon 1 "Skull Knight #2" from your Deck. Then shuffle your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88132637,3,0,0,33,1500,1000,4,8,32,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (88132637, 'Twin-Headed Wolf', 'When there is another face-up Fiend-Type monster on your side of the field, negate the effect of Flip Effect Monsters destroyed by this card as a result of battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14531242,3,0,0,17,1800,1700,4,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (14531242, 'Opticlops', 'A one-eyed giant that serves the "Dark Ruler Ha Des", it skewers its enemies with its sharp horn, shattering them to pieces.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41925941,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (41925941, 'Bark of Dark Ruler', 'If a Fiend-Type monster you control battles, during the Damage Step: Pay LP (in multiples of 100 points), then target the opponent''s battling monster; that opponent''s monster loses that much ATK and DEF, until the end of this turn.', '攻守ダウン', '払うライフポイントを指定してください', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77910045,3,0,0,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (77910045, 'Fatal Abacus', 'Each time 1 monster is sent from the field to the Graveyard, inflict 500 points of damage per card to the respective card owner''s Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40703393,3,0,0,2,0,0,0,0,0,262148);
INSERT OR REPLACE INTO "texts" VALUES (40703393, 'The Puppet Magic of Dark Ruler', 'Select 1 Fiend-Type monster from your Graveyard. Remove from play monsters on your side of the field whose total Levels exactly equal the Level of the selected Fiend-Type monster. Then Special Summon the selected monster from your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76297408,3,0,0,131076,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (76297408, 'Soul Demolition', 'You can only activate this card''s effect when you have a Fiend-Type monster on your side of the field. Pay 500 Life Points to use this effect. Both players select 1 Monster Card from their opponent''s Graveyard. Remove the selected cards from play.', 'Banish', 'Do you want to activate the effect of "Soul Demolition"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3682106,3,0,0,2,0,0,0,0,0,3);
INSERT OR REPLACE INTO "texts" VALUES (3682106, 'Double Snare', 'Destroy 1 face-up card on the field that has an effect that negates Trap Cards'' effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49681811,3,0,0,33,2300,1700,5,1,1,-2146434560);
INSERT OR REPLACE INTO "texts" VALUES (49681811, 'Freed the Matchless General', 'Negate any Spell effects that target this card, and if you do, destroy that Spell Card. During your Draw Phase, instead of conducting your normal draw: You can add 1 Level 4 or lower Warrior-Type monster from your Deck to your hand. This card must be face-up on the field to activate and to resolve this effect.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2460565,3,0,0,33,1200,400,3,1,1,1376256);
INSERT OR REPLACE INTO "texts" VALUES (2460565, 'Marauding Captain', 'Your opponent cannot target face-up Warrior-Type monsters for attacks, except this one. When this card is Normal Summoned: You can Special Summon 1 Level 4 or lower monster from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49868263,3,0,0,97,2000,1200,6,1,1,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (49868263, 'Ryu Senshi', '"Warrior Dai Grepher" + "Spirit Ryu"
A Fusion Summon of this monster can only be conducted with the above Fusion Material Monsters. As long as this card remains face-up on the field, negate the effect of a Normal Trap Card by paying 1000 Life Points. Negate the effect of a Spell Card that targets this card and destroy it.', 'Negate effect', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75953262,3,0,0,17,1700,1600,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (75953262, 'Warrior Dai Grepher', 'The warrior who can manipulate dragons. Nobody knows his mysterious past.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1347977,3,0,0,2097185,800,1200,3,2,1,48);
INSERT OR REPLACE INTO "texts" VALUES (1347977, 'Mysterious Guard', 'FLIP: Target 1 face-up monster on the field, and if you control a face-up Warrior-Type monster, you can target 1 additional face-up monster on the field; return the first target to the top of the Deck, then return the additional target (if any) to the hand if you still control a face-up Warrior-Type monster.', 'Return another face-up monster to its owner''s hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38742075,3,0,0,33,1600,800,3,2,1,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (38742075, 'Frontier Wiseman', 'Negate any Spell effects that target a Warrior-Type monster you control, and if you do, destroy that card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74131780,3,0,0,33,1000,1000,4,1,1,10);
INSERT OR REPLACE INTO "texts" VALUES (74131780, 'Exiled Force', 'You can Tribute this card to target 1 monster on the field; destroy that target.', '破坏场上的1只怪兽', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37620434,3,0,69,2097185,800,700,3,1,1,4096);
INSERT OR REPLACE INTO "texts" VALUES (37620434, 'Shadow Tamer', '(This card is always treated as an "Archfiend" card.)
FLIP: Target 1 Fiend-Type monster your opponent controls; take control of that target until the End Phase.', '控制权转移', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63018132,3,0,0,2097185,700,800,3,1,1,4098);
INSERT OR REPLACE INTO "texts" VALUES (63018132, 'Dragon Manipulator', 'FLIP: Take control of 1 face-up Dragon-Type monster on your opponent''s side of the field until the end of the End Phase.', 'Take control', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (403847,3,0,0,131074,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (403847, 'The A. Forces', 'All Warrior-Type monsters you control gain 200 ATK for each Warrior or Spellcaster-Type monster you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32807846,3,0,0,2,0,0,0,0,0,1049088);
INSERT OR REPLACE INTO "texts" VALUES (32807846, 'Reinforcement of the Army', 'Add 1 Level 4 or lower Warrior-Type monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69296555,3,0,0,524290,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (69296555, 'Array of Revealing Light', 'Declare 1 Type of monster. Any monster of the declared Type cannot declare an attack during the turn it is Normal Summoned, Flip Summoned, or Special Summoned.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95281259,3,0,0,2,0,0,0,0,0,1049600);
INSERT OR REPLACE INTO "texts" VALUES (95281259, 'The Warrior Returning Alive', 'Target 1 Warrior-Type monster in your Graveyard; add that target to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53046408,3,0,0,65538,0,0,0,0,0,8388616);
INSERT OR REPLACE INTO "texts" VALUES (53046408, 'Emergency Provisions', 'Send any number of other Spell and Trap Cards you control to the Graveyard. Gain 1000 Life Points for each card sent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94568601,3,0,0,33,2900,2500,8,8192,4,32768);
INSERT OR REPLACE INTO "texts" VALUES (94568601, 'Tyrant Dragon', 'During your Battle Phase, if your opponent controls a monster after this card''s first attack, this card can make a second attack. Negate any Trap effects that target this card, and if you do, destroy that Trap Card. This card cannot be Special Summoned from the Graveyard, unless you Tribute 1 Dragon-Type monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31553716,3,0,0,33,1900,0,4,8192,8,18432);
INSERT OR REPLACE INTO "texts" VALUES (31553716, 'Spear Dragon', 'During battle between this attacking card and a Defense Position monster whose DEF is lower than the ATK of this card, inflict the difference as Battle Damage to your opponent. If this card attacks, it is changed to Defense Position at the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67957315,3,0,0,33,1000,1000,4,8192,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (67957315, 'Spirit Ryu', 'You can only activate this effect during your Battle Step, if this card battles during your turn. Discard 1 Dragon-Type monster from your hand to the Graveyard to increase the ATK and DEF of this card by 1000 points until the End Step.', 'Increase ATK and DEF', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66235877,3,0,69,97,2000,1200,5,8192,8,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (66235877, 'Fiend Skull Dragon', '"Cave Dragon" + "Lesser Fiend"
(This card is always treated as an "Archfiend" card.)
A Fusion Summon of this monster can only be done with the above Fusion Material Monsters. Negate the effects of Flip Effect Monsters. Negate any Trap effects that target this card on the field, and if you do, destroy that Trap Card.', 'Negate effect', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93220472,3,0,0,33,2000,100,4,8192,8,65536);
INSERT OR REPLACE INTO "texts" VALUES (93220472, 'Cave Dragon', 'Cannot be Normal Summoned while you control a monster. This card cannot declare an attack unless you control another Dragon-Type monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29618570,3,0,0,33,1300,700,3,8192,8,32768);
INSERT OR REPLACE INTO "texts" VALUES (29618570, 'Gray Wing', 'Discard 1 card from your hand during your Main Phase 1. This monster can attack twice during the Battle Phase of this turn.', '两次攻击', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55013285,3,0,0,33,700,800,2,8192,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (55013285, 'Troop Dragon', 'If this card is destroyed and sent to the Graveyard as a result of battle, select and Special Summon 1 "Troop Dragon" from your Deck to your side of the field. Then shuffle your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92408984,3,0,0,131076,0,0,0,0,0,-2146435063);
INSERT OR REPLACE INTO "texts" VALUES (92408984, 'The Dragon''s Bead', 'Discard 1 card from your hand. Negate the effect of a Trap Card that targets 1 face-up Dragon-Type monster and destroy the Trap Card.', 'Negate and destroy Trap Card', 'Activate the effect of "The Dragon''s Bead"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28596933,3,0,0,2,0,0,0,0,0,17);
INSERT OR REPLACE INTO "texts" VALUES (28596933, 'A Wingbeat of Giant Dragon', 'Return 1 face-up Level 5 or higher Dragon-Type monster you control to the owner''s hand and destroy all Spell and Trap Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55991637,3,0,0,2,0,0,0,0,0,4194306);
INSERT OR REPLACE INTO "texts" VALUES (55991637, 'Dragon''s Gunfire', 'Activate only if you control a face-up Dragon-Type monster. Activate 1 of these effects:
● Inflict 800 damage to your opponent.
● Select 1 face-up monster with 800 or less DEF, and destroy it.', 'Inflict 800 damage to your opponent.', 'Select 1 face-up monster with 800 or less DEF, and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81385346,3,0,0,2,0,0,0,0,0,5242881);
INSERT OR REPLACE INTO "texts" VALUES (81385346, 'Stamping Destruction', 'If you control a Dragon-Type monster: Target 1 Spell/Trap Card on the field; destroy that target, and if you do, inflict 500 damage to its controller.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27770341,3,0,0,65538,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (27770341, 'Super Rejuvenation', 'During the End Phase of the turn this card was activated, draw a number of cards equal to the combined number of Dragon-Type monsters you discarded or Tributed from your hand or your side of the field this turn.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54178050,3,0,0,131076,0,0,0,0,0,1064960);
INSERT OR REPLACE INTO "texts" VALUES (54178050, 'Dragon''s Rage', 'During battle between an attacking Dragon-Type monster you control and a Defense Position monster whose DEF is lower than the ATK of the attacking monster, inflict the difference as Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80163754,3,0,0,4,0,0,0,0,0,1048578);
INSERT OR REPLACE INTO "texts" VALUES (80163754, 'Burst Breath', 'Tribute 1 Dragon-Type monster; destroy all face-up monsters on the field whose DEF is less than or equal to the ATK the Tributed monster had on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17658803,3,0,0,17,2400,1400,6,8192,8,0);
INSERT OR REPLACE INTO "texts" VALUES (17658803, 'Luster Dragon 2', 'This dragon feeds on emerald. Enchanted by this monster even when attacked, few people live to tell of its beauty.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78706415,3,0,0,2097185,500,500,3,1024,1,288);
INSERT OR REPLACE INTO "texts" VALUES (78706415, 'Fiber Jar', 'FLIP: Each player shuffles all cards from their hand, field, and Graveyard into the Deck, then draws 5 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71829750,3,0,0,33,1400,2000,4,524288,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (71829750, 'Serpentine Princess', 'If this face-up card is returned from the field to your Deck, select and Special Summon 1 Level 3 or lower monster from your Deck to your side of the field. Then shuffle your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19153634,3,0,0,33,2000,1400,5,16,32,0);
INSERT OR REPLACE INTO "texts" VALUES (19153634, 'Patrician of Darkness', 'You choose the attack targets for your opponent''s attacks.', 'Do you want to change attack target?', 'Select target', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70797118,3,0,0,33,1900,800,4,4096,16,0);
INSERT OR REPLACE INTO "texts" VALUES (70797118, 'Thunder Nyan Nyan', 'If there is a non-LIGHT monster on your side of the field, destroy this face-up card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14291024,3,0,0,33,-2,-2,1,32,16,270336);
INSERT OR REPLACE INTO "texts" VALUES (14291024, 'Gradius'' Option', 'This card cannot be Normal Summoned or Set. This monster can only be Special Summoned by selecting 1 face-up "Gradius" on your side of the field. The ATK and DEF of this card becomes the same as the ATK and DEF of the selected "Gradius". If the selected "Gradius" is removed from the field, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79575620,3,0,0,33,400,1500,3,2,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (79575620, 'Injection Fairy Lily', 'If this card attacks or is attacked, during damage calculation (in either player''s turn): You can pay 2000 Life Points once per battle; this card gains 3000 ATK during that damage calculation only.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6979239,3,0,0,33,900,400,3,1024,1,4194304);
INSERT OR REPLACE INTO "texts" VALUES (6979239, 'Woodland Sprite', 'Send 1 Equip Card equipped to this card to the Graveyard. Inflict 500 points of damage to your opponent''s Life Points.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18036057,3,0,0,33,1900,1400,5,4,16,16640);
INSERT OR REPLACE INTO "texts" VALUES (18036057, 'Airknight Parshath', 'If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. When this card inflicts battle damage to your opponent: Draw 1 card.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43586926,3,0,0,33,1500,1200,3,8192,8,270336);
INSERT OR REPLACE INTO "texts" VALUES (43586926, 'Twin-Headed Behemoth', 'During the End Phase, if this card was destroyed on the field and sent to the Graveyard this turn: Special Summon it from the Graveyard, and make its ATK and DEF 1000. You can only use the effect of "Twin-Headed Behemoth" once per Duel.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40695128,3,0,0,545,1200,1700,4,256,1,16);
INSERT OR REPLACE INTO "texts" VALUES (40695128, 'Maharaghi', 'This card cannot be Special Summoned. This card returns to the owner''s hand during the End Phase of the turn that this card is Normal Summoned or flipped face-up. If this card is Normal Summoned or flipped face-up, look at 1 card on the top of your Deck during your next Draw Phase (before you draw), and return the card to the top or the bottom of your Deck.', 'Return to hand', 'Look at the top card', 'Top', 'Bottom', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77084837,3,0,0,545,700,500,3,16384,1,131088);
INSERT OR REPLACE INTO "texts" VALUES (77084837, 'Inaba White Rabbit', 'This card cannot be Special Summoned. This card returns to the owner''s hand during the End Phase of the turn that this card is Normal Summoned or flipped face-up. This monster attacks your opponent''s Life Points directly.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3078576,3,0,0,545,200,100,2,8,8,32);
INSERT OR REPLACE INTO "texts" VALUES (3078576, 'Yata-Garasu', 'This card cannot be Special Summoned. This card returns to its owner''s hand during the End Phase of the turn it is Normal Summoned or flipped face-up. When this card inflicts Battle Damage to your opponent, they skip their next Draw Phase.', 'Spirit', '跳过下次抽卡阶段', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40473581,3,0,0,545,2000,1600,4,4096,1,16);
INSERT OR REPLACE INTO "texts" VALUES (40473581, 'Susa Soldier', 'This card cannot be Special Summoned. This card returns to the owner''s hand during the End Phase of the turn that this card is Normal Summoned or flipped face-up. The Battle Damage this card inflicts to your opponent''s Life Points is halved.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76862289,3,0,0,545,2600,3100,7,8192,4,272);
INSERT OR REPLACE INTO "texts" VALUES (76862289, 'Yamata Dragon', 'This card cannot be Special Summoned. This card returns to its owner''s hand during the End Phase of the turn it is Normal Summoned or flipped face-up. When this card inflicts Battle Damage to your opponent, draw cards until you have 5 cards in your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2356994,3,0,0,545,1900,1700,5,32768,32,16);
INSERT OR REPLACE INTO "texts" VALUES (2356994, 'Great Long Nose', 'This card cannot be Special Summoned. This card returns to the owner''s hand during the End Phase of the turn that this card is Normal Summoned or flipped face-up. If this card inflicts Battle Damage to your opponent''s Life Points, your opponent skips their next Battle Phase.', 'Return to hand', 'バトルフェイズをスキップ', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39751093,3,0,0,545,0,100,3,2,16,2064);
INSERT OR REPLACE INTO "texts" VALUES (39751093, 'Otohime', 'Cannot be Special Summoned. During the End Phase of the turn this card is Normal Summoned or flipped face-up: Return it to the hand. When this card is Normal Summoned or flipped face-up: You can target 1 face-up monster your opponent controls; change that target''s battle position.', 'Return to hand', '表示形式を変更', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75745607,3,0,0,545,2800,2900,8,128,4,80);
INSERT OR REPLACE INTO "texts" VALUES (75745607, 'Hino-Kagu-Tsuchi', 'This card cannot be Special Summoned. This card returns to its owner''s hand during the End Phase of the turn it is Normal Summoned or flipped face-up. If this card inflicts Battle Damage to your opponent, they discard all cards in their hand during the next Draw Phase, before they draw.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2134346,3,0,0,545,1700,1200,4,4,16,32800);
INSERT OR REPLACE INTO "texts" VALUES (2134346, 'Asura Priest', 'Cannot be Special Summoned. During the End Phase of the turn this card is Normal Summoned or flipped face-up: Return it to the hand. This card can attack all monsters your opponent controls once each.', 'Spirit', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38538445,3,0,0,545,1200,0,4,512,4,8388624);
INSERT OR REPLACE INTO "texts" VALUES (38538445, 'Fushi No Tori', 'This card cannot be Special Summoned. This card returns to the owner''s hand during the End Phase of the turn that this card is Normal Summoned or flipped face-up. When this card inflicts Battle Damage to your opponent''s Life Points, increase your Life Points by an amount equal to the Battle Damage.', 'Return to hand', 'Gain LP', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64801562,3,0,0,262146,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (64801562, 'Heart of Clear Water', 'If the equipped monster''s ATK is 1300 or higher, this card is destroyed. The monster equipped with this card is not destroyed as a result of battle or by the effect of a card that targets the monster. (Damage calculation is applied normally.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (295517,3,22702055,0,524290,0,0,0,0,0,2105344);
INSERT OR REPLACE INTO "texts" VALUES (295517, 'A Legendary Ocean', 'This card''s name is treated as "Umi". Reduce the Level of all WATER monsters in both player''s hands and on the field by 1. All WATER monsters gain 200 ATK and DEF.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37684215,3,0,70,262146,0,0,0,0,0,16785408);
INSERT OR REPLACE INTO "texts" VALUES (37684215, 'Fusion Sword Murasame Blade', 'Equip only to a Warrior-Type monster. It gains 800 ATK. While equipped to a monster, this card cannot be destroyed by card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63789924,3,0,0,262146,0,0,0,0,0,64);
INSERT OR REPLACE INTO "texts" VALUES (63789924, 'Smoke Grenade of the Thief', 'When this Equip Spell Card is active and is destroyed by a card effect, look at your opponent''s hand. Select 1 card from their hand and discard it to the Graveyard.', '手札を捨てる', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31036355,3,0,0,2,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (31036355, 'Creature Swap', 'Each player chooses 1 monster they control and switches control of those monsters with each other. Those monsters cannot change their battle positions for the rest of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99173029,3,0,0,131074,0,0,0,0,0,24);
INSERT OR REPLACE INTO "texts" VALUES (99173029, 'Spiritual Energy Settle Machine', 'As long as this card remains face-up on the field, all Spirit monsters remain face-up on the field and do not return to their owners'' hand during the End Phase even if they are Normal Summoned or flipped face-up. Discard 1 card from your hand to the Graveyard during each of your End Phases. If you do not, destroy this card. When this card is removed from the field, all face-up Spirit monsters return to the owners'' hands.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36562627,3,0,0,131074,0,0,0,0,0,134217728);
INSERT OR REPLACE INTO "texts" VALUES (36562627, 'Second Coin Toss', 'When a coin toss is performed, you can choose to redo the coin toss. (If the toss involved multiple coin flips, redo all of them.) You can only use the effect of "Second Coin Toss" once per turn.', 'Activate the effect of "Second Coin Toss"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62966332,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (62966332, 'Convulsion of Nature', 'As long as this card remains face-up on the field, both players must turn their respective Decks upside down and proceed with the current Duel.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99351431,3,0,0,2,0,0,0,0,0,64);
INSERT OR REPLACE INTO "texts" VALUES (99351431, 'The Secret of the Bandit', 'This card can only be activated during Main Phase 1. Select 1 face-up monster on the field. Each time the selected monster inflicts Battle Damage to your opponent''s Life Points this turn, your opponent discards 1 random card.', 'Discard hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25345186,3,0,0,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (25345186, 'After The Struggle', 'This card can only be activated during Main Phase 1. All monsters on both sides of the field that have been involved in damage calculation are destroyed during the End Step of the turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61844784,3,0,0,2,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (61844784, 'Magic Reflector', 'Select 1 Spell Card that remains face-up on your side of the field and put 1 counter on it. If the selected card would be destroyed, the counter is removed instead.', 'Select 1 Spell Card that remains face-up on your side of the field', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98239899,3,0,0,4,0,0,0,0,0,8195);
INSERT OR REPLACE INTO "texts" VALUES (98239899, 'Blast with Chain', 'Target 1 face-up monster you control; equip this card to that target. It gains 500 ATK. When this card is destroyed by a card effect while equipped: Target 1 card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24623598,3,0,0,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (24623598, 'Disappear', 'Remove from play 1 card from your opponent''s Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61622107,3,0,0,4,0,0,0,0,0,8);
INSERT OR REPLACE INTO "texts" VALUES (61622107, 'Bubble Crash', 'This card can only be activated when any player has 6 or more cards on the field and/or in their hand. The player(s) then select and send cards to their respective Graveyards until the amount remaining on the field and in their hand is 5.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93016201,3,0,0,131076,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (93016201, 'Royal Oppression', 'Either player can pay 800 Life Points to negate the Special Summon of a monster(s), and/or an effect that Special Summons a monster(s), and destroy those cards.', 'Negate Special Summon', 'Activate effect of "Royal Oppression"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29401950,3,0,8978508,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (29401950, 'Bottomless Trap Hole', 'When your opponent Summons a monster(s) with 1500 or more ATK: Destroy that monster(s) with 1500 or more ATK, and if you do, banish it instead of sending it to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40633297,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (40633297, 'Bad Reaction to Simochi', 'As long as this card remains face-up on the field, any effect of increasing your opponent''s Life Points is changed to inflict the same amount of points in damage to your opponent''s Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56995655,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (56995655, 'Ominous Fortunetelling', 'During your Standby Phase, select 1 random card from your opponent''s hand. Call the type of card (Monster, Spell, or Trap). If you call it right, inflict 700 points of damage to your opponent''s Life Points. You can use this effect once per turn.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92394653,3,0,0,131076,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (92394653, 'Spirit''s Invitation', 'Each time your Spirit monster returns to your hand, select 1 monster on your opponent''s side of the field and return it to its owner''s hand. Pay 500 Life Points during each of your Standby Phases. If you do not, this card is destroyed.', 'Return to hand', 'Pay 500LP for Spirit''s Invitation effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55773067,3,0,0,4,0,0,0,0,0,72);
INSERT OR REPLACE INTO "texts" VALUES (55773067, 'Drop Off', 'When your opponent draws for their normal draw in their Draw Phase: Your opponent discards 1 card they just drew.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28566710,3,0,0,4,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (28566710, 'Last Turn', 'This card can only be activated during your opponent''s turn when your Life Points are 1000 or less. Select 1 monster on your side of the field and send all other cards on the field and in their respective owner''s hands to their respective Graveyards. After that, your opponent selects and Special Summons 1 monster from their Deck in face-up Attack Position and attacks your selected monster. (Any Battle Damage from this battle is treated as 0.) The player whose monster remains alone on the field at the End Phase of this turn wins the Duel. Any other case results in a DRAW.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83986578,3,0,0,33,1700,1000,4,16384,1,2);
INSERT OR REPLACE INTO "texts" VALUES (83986578, 'King Tiger Wanghu', 'When a monster(s) with 1400 or less ATK is Normal Summoned or Special Summoned: Destroy those monsters with 1400 or less ATK. This card must be face-up on the field to activate and to resolve this effect.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45547649,3,0,0,33,1600,1600,4,512,8,512);
INSERT OR REPLACE INTO "texts" VALUES (45547649, 'Birdface', 'When this card is sent to the Graveyard as a result of battle, you can add 1 "Harpie Lady" from your Deck to your hand. Then shuffle your Deck.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82642348,3,0,0,33,1000,1700,4,8,32,134217730);
INSERT OR REPLACE INTO "texts" VALUES (82642348, 'Kryuel', 'When this card is sent to the Graveyard as a result of battle, toss a coin and call it. If you call it right, destroy 1 monster on your opponent''s side of the field.', 'Coin toss', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42364374,3,0,0,33,2000,2000,3,2048,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (42364374, 'Arsenal Bug', 'If you control no other Insect-Type monsters, this card''s ATK and DEF become 1000.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17214465,3,0,0,33,700,2000,4,64,2,0);
INSERT OR REPLACE INTO "texts" VALUES (17214465, 'Maiden of the Aqua', 'As long as this card remains face-up on the field, the field is treated as "Umi" (however there is no increasing or decreasing of ATK/DEF due to "Umi"''s effect). If there is an active Field Spell Card on the field, this effect is not applied.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5257687,3,0,0,2097185,200,100,2,8,2,135168);
INSERT OR REPLACE INTO "texts" VALUES (5257687, 'Jowls of Dark Demise', 'FLIP: Take control of 1 monster on your opponent''s side of the field until the end of the turn that this card''s effect is activated. When the controlled monster attacks, it may attack your opponent''s Life Points directly.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70307656,3,0,0,33,0,100,3,64,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (70307656, 'Mucus Yolk', 'This card can attack your opponent''s Life Points directly. Each time this card inflicts Battle Damage to your opponent''s Life Points, increase the ATK of this card by 1000 points during your next Standby Phase. The ATK increase lasts as long as this card remains face-up on the field.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75285069,3,0,0,33,2800,2900,9,4,16,1);
INSERT OR REPLACE INTO "texts" VALUES (75285069, 'Moisture Creature', 'If you Tribute Summon this monster by Tributing 3 monsters on the field, destroy all Spell and Trap Cards on your opponent''s side of the field.', 'Tribute Summon this monster by Tributing 3 monsters on the field', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80233946,3,0,0,33,1100,1100,3,64,2,65536);
INSERT OR REPLACE INTO "texts" VALUES (80233946, 'Gora Turtle', 'As long as this card remains face-up on the field, monsters with an ATK equal to 1900 or more cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16222645,3,0,0,33,500,800,2,1,8,2);
INSERT OR REPLACE INTO "texts" VALUES (16222645, 'Sasuke Samurai', 'At the start of the Damage Step, if this card attacks a face-down Defense Position monster: Destroy that face-down monster.', '里侧守备的攻击对象怪兽破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89111398,3,0,0,545,2200,1800,6,16,1,18);
INSERT OR REPLACE INTO "texts" VALUES (89111398, 'Dark Dust Spirit', 'Cannot be Special Summoned. During the End Phase of the turn this card is Normal Summoned or flipped face-up: Return it to the hand. When this card is Normal Summoned or flipped face-up: Destroy all other face-up monsters on the field.', 'Spirit', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16509093,3,0,0,33,1600,1700,4,16,1,10240);
INSERT OR REPLACE INTO "texts" VALUES (16509093, 'Royal Keeper', 'Once per turn, you can flip this card into face-down Defense Position. When this card is flipped face-up, it gains 300 ATK and DEF until the end of the turn. (If attacked, this effect resolves after damage calculation.)', '变成里侧守备', '攻守上升', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42994702,3,0,0,33,1500,1500,4,16,1,10240);
INSERT OR REPLACE INTO "texts" VALUES (42994702, 'Wandering Mummy', 'You can flip this card into face-down Defense Position once per turn during your Main Phase. After you use this effect, rearrange the face-down Defense Position monsters on your side of the field, then return them in face-down Defense Position.', '变成里侧守备', '攻守上升', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88989706,3,0,0,33,1900,2300,6,2,32,-2147221504);
INSERT OR REPLACE INTO "texts" VALUES (88989706, 'Great Dezard', 'When this monster destroys the following number of monsters as a result of battle, the following effects are activated in order:  One: As long as this card remains face-up on the field, negate the activation and effects of all Spell and Trap Cards that target this card and destroy them.  Two: You can Special Summon 1 "Fushioh Richie" from your hand or your Deck by Tributing this card during your Main Phase.', 'Destroy', '無効', '特殊召喚', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15383415,3,0,0,33,500,1000,3,2048,32,2050);
INSERT OR REPLACE INTO "texts" VALUES (15383415, 'Swarm of Scarabs', 'Once per turn, you can flip this card into face-down Defense Position. When this card is Flip Summoned, destroy 1 monster your opponent controls.', '变成里侧守备表示', '破坏对方1只怪兽', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41872150,3,0,0,33,1000,500,3,2048,32,2049);
INSERT OR REPLACE INTO "texts" VALUES (41872150, 'Swarm of Locusts', 'Once per turn, you can flip this card into face-down Defense Position. When this card is Flip Summoned, destroy 1 Spell or Trap Card your opponent controls.', '变成里侧守备表示', '破坏对方1张魔法·陷阱卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78266168,3,0,0,33,1700,2000,5,16,1,2050);
INSERT OR REPLACE INTO "texts" VALUES (78266168, 'Giant Axe Mummy', 'You can flip this card into face-down Defense Position once per turn during your Main Phase. If the ATK of a monster on your opponent''s side of the field that attacks this card in face-down Defense Position is lower than the DEF of this monster, the attacking monster is destroyed.', 'Destroy', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40659562,3,0,5374044,33,1700,2400,5,256,1,2064);
INSERT OR REPLACE INTO "texts" VALUES (40659562, 'Guardian Sphinx', 'Once per turn: You can change this card to face-down Defense Position. When this card is Flip Summoned: Return all monsters your opponent controls to the hand.', '变成里侧守备表示', '对方场上的全部怪兽返回手牌', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77044671,3,0,0,33,1200,1400,4,16,1,1310720);
INSERT OR REPLACE INTO "texts" VALUES (77044671, 'Pyramid Turtle', 'When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 Zombie-Type monster with 2000 or less DEF from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3549275,3,0,0,2097185,200,300,3,256,16,138412032);
INSERT OR REPLACE INTO "texts" VALUES (3549275, 'Dice Jar', 'FLIP: Both players roll a six-sided die. The player with the lower result takes damage equal to their opponent''s roll x 500. However, if the winner rolled a 6, the loser takes 6000 damage. If the rolls are the same, both players roll again.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40933924,3,0,26,33,1000,1000,4,1,32,128);
INSERT OR REPLACE INTO "texts" VALUES (40933924, 'Dark Scorpion Burglars', 'When this card inflicts Battle Damage to your opponent''s Life Points, your opponent selects 1 Spell Card from their Deck and sends it to the Graveyard. Then shuffle the Deck.', 'Select 1 Spell Card to send to the Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76922029,3,0,0,33,1400,1500,4,1,32,200);
INSERT OR REPLACE INTO "texts" VALUES (76922029, 'Don Zaloog', 'When this card inflicts Battle Damage to your opponent, you can either:
● Discard 1 random card from your opponent''s hand. OR
● Send the top 2 cards of your opponent''s Deck to the Graveyard.', 'Select effect', 'Discard 1 random card from your opponent''s hand.', 'Send the top 2 cards of your opponent''s Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2204140,3,0,0,2,0,0,0,0,0,1311748);
INSERT OR REPLACE INTO "texts" VALUES (2204140, 'Book of Life', 'Target 1 Zombie-Type monster in your Graveyard and 1 monster in your opponent''s Graveyard; Special Summon the first target, also banish the second target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38699854,3,0,0,2,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (38699854, 'Book of Taiyou', 'Flip 1 face-down monster on the field into face-up Attack Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14087893,3,0,0,65538,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (14087893, 'Book of Moon', 'Target 1 face-up monster on the field; change that target to face-down Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41482598,3,0,0,131074,0,0,0,0,0,264);
INSERT OR REPLACE INTO "texts" VALUES (41482598, 'Mirage of Nightmare', 'During your opponent''s Standby Phase, draw cards until you have 4 cards in your hand. During your Standby Phase, discard to the Graveyard the same number of random cards you drew with this card''s effect.', 'Draw card', '丢弃', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77876207,3,0,0,2,0,0,0,0,0,131072);
INSERT OR REPLACE INTO "texts" VALUES (77876207, 'Secret Pass to the Treasures', 'Select 1 face-up monster with an ATK equal to 1000 points or less on your side of the field. During the turn this card is activated, the selected monster can attack your opponent''s Life Points directly.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4861205,3,0,0,131074,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (4861205, 'Call of the Mummy', 'Once per turn: You can Special Summon 1 Zombie-Type monster from your hand. You must control no monsters to activate and to resolve this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40350910,3,0,0,2,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (40350910, 'Timidity', 'Neither player can destroy Set Spell and Trap Cards on the field until your opponent''s next End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76754619,3,0,0,65538,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (76754619, 'Pyramid Energy', 'You can select and activate 1 of the following effects:
● Increase the ATK of all face-up monsters on your side of the field by 200 points until the End Phase of the turn this card is activated.
● Increase the DEF of all face-up monsters on your side of the field by 500 points until the End Phase of the turn this card is activated.', 'Increase the ATK of all face-up monsters on your side of the field by 200 points until the End Phase', 'Increase the DEF of all face-up monsters on your side of the field by 500 points until the End Phase', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3149764,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (3149764, 'Tutan Mask', 'When a Spell/Trap Card is activated that targets exactly 1 Zombie-Type monster on the field (and no other cards): Negate the activation, and if you do, destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39537362,3,0,0,131076,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (39537362, 'Ordeal of a Traveler', 'You can activate this card''s effect when your opponent declares an attack. Your opponent selects 1 random card in your hand and calls the type of the card (Monster, Spell, or Trap). If your opponent calls it wrong, the attacking monster is returned to its owner''s hand.', 'Declare card type', 'Use the effect of "Ordeal of a Traveler"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76532077,3,0,0,131076,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (76532077, 'Bottomless Shifting Sand', 'At the end of your opponent''s turn, destroy the face-up monster(s) with the highest ATK on the field. During your own Standby Phase, if you have 4 or less cards in your hand, this card is destroyed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2926176,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (2926176, 'Curse of Royal', 'Negate the activation and the effect of a Spell or Trap Card that includes the effect of destroying 1 Spell or Trap Card and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38411870,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (38411870, 'Needle Ceiling', 'When there are 4 or more monsters on the field: Destroy all face-up monsters.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65810489,3,0,0,4,0,0,0,0,0,786432);
INSERT OR REPLACE INTO "texts" VALUES (65810489, 'Statue of the Wicked', 'When this face-down card is destroyed and sent to the Graveyard, Special Summon 1 "Wicked Token" (Fiend-Type/DARK/Level 4 /ATK 1000/DEF 1000) on your side of the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1804528,3,0,0,4,0,0,0,0,0,66);
INSERT OR REPLACE INTO "texts" VALUES (1804528, 'Dark Coffin', 'When this face-down card is destroyed and sent to the Graveyard, your opponent selects and executes 1 of the following effects:
● Discard 1 random card in their hand.
● Select 1 monster on their side of the field and destroy it.', 'Select effect', 'Discard 1 random card', 'Select 1 monster on your side of the field and destroy it', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38299233,3,0,0,131076,0,0,0,0,0,134217730);
INSERT OR REPLACE INTO "texts" VALUES (38299233, 'Needle Wall', 'Once per turn, during your Standby Phase: Roll a six-sided die. Treat your opponent''s Monster Card Zones as numbers 1-5, counting from your right, and destroy the monster that is in the same Monster Card Zone as the result. If the result is 6, roll again.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64697231,3,0,0,4,0,0,0,0,0,96);
INSERT OR REPLACE INTO "texts" VALUES (64697231, 'Trap Dustshoot', 'Activate only if your opponent has 4 or more cards in their hand. Look at your opponent''s hand, select 1 Monster Card in it, and return that card to its owner''s Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37576645,3,0,0,4,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (37576645, 'Reckless Greed', 'Draw 2 cards and skip your next 2 Draw Phases.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63571750,3,0,0,4,0,0,0,0,0,1024);
INSERT OR REPLACE INTO "texts" VALUES (63571750, 'Pharaoh''s Treasure', 'After activation, put this card face-up in your Deck and shuffle it. When you draw this card, send it to the Graveyard and add 1 card in your Graveyard (except this card) to your hand.', '回收', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48579379,3,0,0,33,3500,3000,8,2048,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (48579379, 'Perfectly Ultimate Great Moth', 'This card cannot be Normal Summoned or Set. This monster can only be Special Summoned by Tributing "Petit Moth" on the 6th of your turns after "Petit Moth" has been equipped with "Cocoon of Evolution".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41426869,3,0,0,130,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (41426869, 'Black Illusion Ritual', 'This card is used to Ritual Summon "Relinquished". You must also Tribute monsters from the field or your hand whose total Levels equal 1 or more.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
