BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (21844576,3,0,12296,17,1000,1000,3,1,8,0);
INSERT OR REPLACE INTO "texts" VALUES (21844576, 'Elemental HERO Avian', 'A winged Elemental HERO who wheels through the sky and manipulates the wind. His signature move, Featherbreak, gives villainy a blow from sky-high.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58932615,3,0,12296,17,1200,800,3,1,4,0);
INSERT OR REPLACE INTO "texts" VALUES (58932615, 'Elemental HERO Burstinatrix', 'A flame manipulator who was the first Elemental HERO woman. Her Burstfire burns away villainy.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84327329,3,0,12296,17,800,2000,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (84327329, 'Elemental HERO Clayman', 'An Elemental HERO with a clay body built-to-last. He''ll preserve his Elemental HERO colleagues at any cost.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20721928,3,0,12296,17,1600,1400,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (20721928, 'Elemental HERO Sparkman', 'An Elemental HERO and a warrior of light who proficiently wields many kinds of armaments. His Static Shockwave cuts off the path of villainy.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57116033,3,0,164,33,300,200,1,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (57116033, 'Winged Kuriboh', 'If this card on the field is destroyed and sent to the Graveyard: Any further Battle Damage you take this turn becomes 0.', 'Reduce damage to 0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98585345,3,0,10747969,33,300,200,10,4,16,4194306);
INSERT OR REPLACE INTO "texts" VALUES (98585345, 'Winged Kuriboh LV10', 'Cannot be Normal Summoned or Set. Must be Special Summoned with "Transcendent Wings" and cannot be Special Summoned by other ways. During your opponent''s Battle Phase: You can Tribute this face-up card; destroy all Attack Position monsters your opponent controls and inflict damage to your opponent equal to the combined original ATK of those destroyed monster(s).', 'Destroy and inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6480253,3,0,0,33,800,1200,3,32,1,1040);
INSERT OR REPLACE INTO "texts" VALUES (6480253, 'Wroughtweiler', 'When this card is destroyed by battle and sent to the Graveyard: Target 1 "Elemental HERO" card and 1 "Polymerization" in your Graveyard; add both those targets to your hand.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33875961,3,0,0,33,1000,1500,4,32,1,3);
INSERT OR REPLACE INTO "texts" VALUES (33875961, 'Dark Catapulter', 'During your Standby Phase, if this card is in Defense Position, put 1 counter on this card. You can remove from play a number of card(s) in your Graveyard equal to the number of counters on this card to destroy that many Spell or Trap Card(s) on the field. Then remove all counter(s) from this card.', 'Place counter', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79979666,3,0,12296,33,800,1200,4,1,2,262400);
INSERT OR REPLACE INTO "texts" VALUES (79979666, 'Elemental HERO Bubbleman', 'If this is the only card in your hand, you can Special Summon it (from your hand). When this card is Summoned: You can draw 2 cards. You must control no other cards and have no cards in your hand to activate and to resolve this effect.', 'Special Summon', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35809262,3,0,12296,97,2100,1200,6,1,8,4194304);
INSERT OR REPLACE INTO "texts" VALUES (35809262, 'Elemental HERO Flame Wingman', '"Elemental HERO Avian" + "Elemental HERO Burstinatrix"
Must be Fusion Summoned and cannot be Special Summoned by other ways. When this card destroys a monster by battle and sends it to the Graveyard: Inflict damage to your opponent equal to the ATK of the destroyed monster.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61204971,3,0,12296,97,2400,1500,6,1,16,2);
INSERT OR REPLACE INTO "texts" VALUES (61204971, 'Elemental HERO Thunder Giant', '"Elemental HERO Sparkman" + "Elemental HERO Clayman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. Once per turn: You can discard 1 card to target 1 face-up monster on the field with original ATK less than the ATK of this card; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47737087,3,0,12296,97,2000,2500,6,1,1,139264);
INSERT OR REPLACE INTO "texts" VALUES (47737087, 'Elemental HERO Rampart Blaster', '"Elemental HERO Clayman" + "Elemental HERO Burstinatrix"
Must be Fusion Summoned and cannot be Special Summoned by other ways. This card can attack while in face-up Defense Position, but only if your opponent controls no monsters, and if it does, this card''s ATK is halved during damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81197327,3,0,12296,97,1800,1000,5,1,2,8388608);
INSERT OR REPLACE INTO "texts" VALUES (81197327, 'Elemental HERO Steam Healer', '"Elemental HERO Burstinatrix" + "Elemental HERO Bubbleman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. When this card destroys a monster by battle and sends it to the Graveyard: Gain Life Points equal to the ATK of that destroyed monster in the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24094653,3,0,70,2,0,0,0,0,0,268697608);
INSERT OR REPLACE INTO "texts" VALUES (24094653, 'Polymerization', 'Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters from your hand or your side of the field as Fusion Materials.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26902560,3,0,70,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (26902560, 'Fusion Sage', 'Add 1 "Polymerization" card from your Deck to your hand. Then shuffle your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95281259,3,0,0,2,0,0,0,0,0,1049600);
INSERT OR REPLACE INTO "texts" VALUES (95281259, 'The Warrior Returning Alive', 'Target 1 Warrior-Type monster in your Graveyard; add that target to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19394153,3,0,0,2,0,0,0,0,0,32768);
INSERT OR REPLACE INTO "texts" VALUES (19394153, 'Feather Shot', 'Target 1 face-up "Elemental HERO Avian" you control; during this turn, that target can attack a number of times equal to the number of monsters you control when this card resolves, but cannot attack directly, and other monsters you control cannot attack this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25573054,3,0,0,65538,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (25573054, 'Transcendent Wings', 'Send 1 "Winged Kuriboh" you control and 2 cards from your hand to the Graveyard; Special Summon 1 "Winged Kuriboh LV10" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61968753,3,0,0,65538,0,0,0,0,0,264192);
INSERT OR REPLACE INTO "texts" VALUES (61968753, 'Bubble Shuffle', 'Target 1 face-up Attack Position "Elemental HERO Bubbleman" you control and 1 face-up Attack Position monster your opponent controls; change both those targets to Defense Position, then Tribute that 1 "Elemental HERO Bubbleman", then Special Summon 1 "Elemental HERO" monster from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97362768,3,0,0,262146,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (97362768, 'Spark Blaster', 'Equip only to "Elemental HERO Sparkman". During your Main Phase: You can target 1 face-up monster; change the battle position of that target. After you use this effect 3 times, destroy this card.', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63035430,3,0,0,524290,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (63035430, 'Skyscraper', 'When an "Elemental HERO" monster attacks, if its ATK is lower than the ATK of the attack target, the attacking monster gains 1000 ATK during damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27191436,3,0,0,2,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (27191436, 'Burst Return', 'If you control a face-up "Elemental HERO Burstinatrix": Return all face-up "Elemental HERO" monsters on the field to the hand, except "Elemental HERO Burstinatrix".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53586134,3,0,0,262146,0,0,0,0,0,16785408);
INSERT OR REPLACE INTO "texts" VALUES (53586134, 'Bubble Blaster', 'You can only equip this card to "Elemental HERO Bubbleman". Increase the ATK of the equipped monster by 800 points. If the equipped monster would be destroyed as a result of battle, destroy this card instead, and make the Battle Damage to the controller of the equipped monster 0.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80075749,3,0,0,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (80075749, 'Bubble Illusion', 'You can only activate this card while there is a face-up "Elemental HERO Bubbleman" on your side of the field. During this turn, you can activate 1 Trap Card from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21597117,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (21597117, 'A Hero Emerges', 'When an opponent''s monster declares an attack: Your opponent chooses 1 random card from your hand, then if it is a monster that can be Special Summoned, Special Summon it. Otherwise, send it to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43250041,3,0,0,4,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (43250041, 'Draining Shield', 'When an opponent''s monster declares an attack: Target the attacking monster; negate that attack, and if you do, gain Life Points equal to that target''s ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14315573,3,0,0,1048580,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (14315573, 'Negate Attack', 'Activate only when a target opponent''s monster declares an attack. Negate the attack and end the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22020907,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (22020907, 'Hero Signal', 'When a monster you control is destroyed by battle and sent to the Graveyard: Special Summon 1 Level 4 or lower "Elemental HERO" monster from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71060915,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (71060915, 'Feather Wind', 'When a Spell/Trap Card is activated while you control a face-up "Elemental HERO Avian": Negate the activation and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22479888,3,0,0,4,0,0,0,0,0,4194306);
INSERT OR REPLACE INTO "texts" VALUES (22479888, 'Clay Charge', 'When an "Elemental HERO Clayman" you control is targeted for an attack (even if it is face-down, but reveal it to your opponent in that case): Destroy the attacking monster and that "Elemental HERO Clayman", and inflict 800 damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
