BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (93717133,3,0,276496469,33,3000,2500,8,8192,16,1073750020);
INSERT OR REPLACE INTO "texts" VALUES (93717133, 'Galaxy-Eyes Photon Dragon', 'You can Special Summon this card (from your hand) by Tributing 2 monsters with 2000 or more ATK. During either player''s Battle Step, when this card battles an opponent''s monster: You can target the monster this card is battling; banish both it and this card. At the end of the Battle Phase, return any monsters banished by this effect to the field, and if the other monster was an Xyz Monster, this card gains 500 ATK for each Xyz Material it had when it was banished.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29116732,3,0,0,33,1700,0,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (29116732, 'Daybreaker', 'When this card is Special Summoned: You can Special Summon 1 "Daybreaker" from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55501446,3,0,0,33,1200,800,3,524288,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (55501446, 'Lightserpent', 'If this card is sent from the hand to your Graveyard: You can Special Summon it from the Graveyard. This card cannot be used as a Synchro Material Monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28990150,3,0,85,33,1300,600,3,16384,16,0);
INSERT OR REPLACE INTO "texts" VALUES (28990150, 'Photon Cerberus', 'During the turn this card was Normal Summoned, neither player can activate Trap Cards while this card is face-up on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38973775,3,0,85,33,900,1200,3,8192,16,512);
INSERT OR REPLACE INTO "texts" VALUES (38973775, 'Photon Lizard', 'You can Tribute this card; add 1 Level 4 or lower "Photon" monster from your Deck to your hand. The effect of "Photon Lizard" can only be used once per turn.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65367484,3,0,85,33,2100,0,4,1,16,327680);
INSERT OR REPLACE INTO "texts" VALUES (65367484, 'Photon Thrasher', 'Cannot be Normal Summoned or Set. Must first be Special Summoned (from your hand) while you control no monsters. If you control another monster, this card cannot attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1362589,3,0,85,33,2000,0,4,1,16,2048);
INSERT OR REPLACE INTO "texts" VALUES (1362589, 'Photon Crusher', 'If this card attacks, it is changed to Defense Position at the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38757297,3,0,85,33,2100,1100,6,16384,16,2336);
INSERT OR REPLACE INTO "texts" VALUES (38757297, 'Photon Leo', 'When this card is Normal Summoned: You can have your opponent shuffle their entire hand into the Deck, then they draw the same number of cards as they shuffled into the Deck.', '重新筹卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64145892,3,0,85,33,1000,1000,4,2,16,0);
INSERT OR REPLACE INTO "texts" VALUES (64145892, 'Photon Circle', 'Any Battle Damage you take from battles involving this card is halved.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90640901,3,0,0,33,1500,0,4,8,16,2);
INSERT OR REPLACE INTO "texts" VALUES (90640901, 'Reverse Buster', 'This card can only attack face-down Defense Position monsters. If this card attacks, your opponent cannot activate any Spell/Trap Cards until the end of the Damage Step. At the start of the Damage Step, if this card attacked a face-down Defense Position monster: You can destroy that monster immediately with this card''s effect without flipping it face-up or applying damage calculation.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36834155,3,0,85,33,1000,1000,3,32,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (36834155, 'Photon Pirate', 'You can banish 1 "Photon" monster from your Graveyard; this card gains 1000 ATK until the End Phase. You can use the effect of "Photon Pirate" up to twice per turn.', 'Increase ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63223260,3,0,85,33,0,0,1,32,16,0);
INSERT OR REPLACE INTO "texts" VALUES (63223260, 'Photon Satellite', 'Once per turn: You can target 1 other "Photon" monster you control; the Levels of both that monster and this card become the combined current Levels of those 2 monsters.', 'Level becomes equal to combined Levels', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9718968,3,0,85,33,2100,1000,5,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (9718968, 'Photon Slasher', 'If a face-up Xyz Monster is on the field, you can Special Summon this card (from your hand) in face-up Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35112613,3,0,85,33,300,200,1,8,16,16);
INSERT OR REPLACE INTO "texts" VALUES (35112613, 'Kuriphoton', 'During either player''s turn: You can send this card from your hand to the Graveyard and pay 2000 Life Points; you take no damage this turn. If this card is in your Graveyard: You can send 1 "Photon" monster from your hand to the Graveyard, except "Kuriphoton"; add this card from your Graveyard to your hand. You can only use this effect of "Kuriphoton" once per turn.', 'Take 0 damage', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62107612,3,0,0,33,0,0,1,2,16,4194304);
INSERT OR REPLACE INTO "texts" VALUES (62107612, 'Dimension Wanderer', 'When a monster is banished by the effect of "Galaxy-Eyes Photon Dragon": You can send this card from your hand to the Graveyard; inflict 3000 damage to your opponent. You can only use the effect of "Dimension Wanderer" once per turn.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98555327,3,0,123,33,0,1800,4,2,16,512);
INSERT OR REPLACE INTO "texts" VALUES (98555327, 'Galaxy Wizard', 'Once per turn: You can increase this card''s Level by 4 until the End Phase. You can Tribute this card; add 1 "Galaxy" card from your Deck to your hand, except "Galaxy Wizard".', 'Increase level', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35950025,3,0,123,33,2800,2600,8,1,16,270336);
INSERT OR REPLACE INTO "texts" VALUES (35950025, 'Galaxy Knight', 'If you control a "Photon" or "Galaxy" monster, you can Normal Summon this card without Tributing. When you do: Target 1 "Galaxy-Eyes Photon Dragon" in your Graveyard (if possible); regardless, this card loses 1000 ATK, and if it does, Special Summon that target (if any) in face-up Defense Position. This ATK decrease lasts until the End Phase.', 'Normal Summon without tribute', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29455728,3,0,85,97,2400,1000,6,8192,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (29455728, 'Twin Photon Lizard', '2 "Photon" monsters
You can Tribute this face-up card on the field; Special Summon, from your Graveyard, both of the Fusion Material Monsters used for the Fusion Summon of this card.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11411223,3,0,72,8388641,2400,2400,4,1,16,256);
INSERT OR REPLACE INTO "texts" VALUES (11411223, 'Number 10: Illumiknight', '3 Level 4 monsters
Once per turn: You can detach 1 Xyz Material from this card; send 1 card from your hand to the Graveyard, and if you do, draw 1 card.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47805931,3,0,72,8388641,1800,1800,3,2048,16,1073750016);
INSERT OR REPLACE INTO "texts" VALUES (47805931, 'Number 20: Giga-Brilliant', '2 Level 3 monsters
Once per turn: You can detach 1 Xyz Material from this card; all face-up monsters you currently control gain 300 ATK.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55935416,3,0,72,8388641,500,600,1,16384,16,288);
INSERT OR REPLACE INTO "texts" VALUES (55935416, 'Number 56: Gold Rat', '3 Level 1 monsters
Once per turn: You can detach 1 Xyz Material from this card; draw 1 card, then shuffle 1 card from your hand into the Deck.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61344030,3,0,0,8388641,2000,1000,4,1,16,-2147475200);
INSERT OR REPLACE INTO "texts" VALUES (61344030, 'Starliege Paladynamo', '2 Level 4 LIGHT monsters
Once per turn: You can detach 2 Xyz Materials from this card to target 1 face-up monster your opponent controls; its ATK becomes 0, and if it does, its effects are negated. When this card you control is destroyed by your opponent''s card (either by battle or by card effect) and sent to your Graveyard: Draw 1 card.', 'ATK becomes 0 and negate effect', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9354555,3,0,85,2,0,0,0,0,0,2097696);
INSERT OR REPLACE INTO "texts" VALUES (9354555, 'Photon Veil', 'Shuffle 3 LIGHT monsters from your hand into the Deck, then add 1 to 3 Level 4 or lower LIGHT monsters from your Deck to the hand. If you add 2 or more monsters, they must have the same name.', 'Add more cards to hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35848254,3,0,85,65538,0,0,0,0,0,2359296);
INSERT OR REPLACE INTO "texts" VALUES (35848254, 'Photon Lead', 'Special Summon 1 Level 4 or lower LIGHT monster from your hand in face-up Attack Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80887714,3,0,123,65538,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (80887714, 'Galaxy Storm', 'Target 1 face-up Xyz Monster on the field that has no Xyz Material; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97433739,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (97433739, 'Message in a Bottle', 'Target 3 monsters with different Levels in your Graveyard; Special Summon all 3 of them. Their ATK''s become 0, also their effects are negated. If you do not Xyz Summon this turn after Summoning those 3 monsters, you lose 4000 Life Points during the End Phase. You cannot Special Summon any other monsters, except by Xyz Summon, during the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34838437,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (34838437, 'Accellight', 'If you control no monsters: Special Summon 1 Level 4 or lower "Photon" or "Galaxy" monster from your Deck. You can only activate 1 "Accellight" per turn. You cannot Normal Summon/Set during the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60222582,3,0,123,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (60222582, 'Galaxy Expedition', 'If you control a Level 5 or higher "Photon" or "Galaxy" monster: Special Summon 1 Level 5 or higher "Photon" or "Galaxy" monster from your Deck in face-up Defense Position. You can only activate 1 "Galaxy Expedition" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97617181,3,0,123,262146,0,0,0,0,0,270336);
INSERT OR REPLACE INTO "texts" VALUES (97617181, 'Galaxy Zero', 'Target 1 "Photon" or "Galaxy" monster in your Graveyard; Special Summon it in face-up Attack Position and equip it with this card. It cannot attack or activate its effects. If it would be destroyed during the Battle Phase, you can destroy this card instead. When this card leaves the field: The equipped monster''s ATK becomes 0. You can only activate 1 "Galaxy Zero" per turn.', 'Use the effect of "Galaxy Zero" to avoid destruction?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57115864,3,0,0,4,0,0,0,0,0,2105344);
INSERT OR REPLACE INTO "texts" VALUES (57115864, 'Lumenize', 'When an opponent''s monster declares an attack: Target the attacking monster; negate the attack, and 1 face-up LIGHT monster you control gains ATK equal to that target''s ATK, until your next End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
