BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (89943723,3,0,602120,17,2500,2000,7,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (89943723, 'Elemental HERO Neos', 'A new Elemental HERO has arrived from Neo-Space! When he initiates a Contact Fusion with a Neo-Spacian, his unknown powers are unleashed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59793705,3,0,12296,33,2600,1800,7,1,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (59793705, 'Elemental HERO Bladedge', 'If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86188410,3,0,12296,33,1500,1600,4,1,1,33554432);
INSERT OR REPLACE INTO "texts" VALUES (86188410, 'Elemental HERO Wildheart', 'This card is unaffected by the effects of Trap Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32679370,3,0,0,33,300,600,2,1,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (32679370, 'Hero Kid', 'When this card is Special Summoned: You can Special Summon any number of "Hero Kid"(s) from your Deck.', 'Special Summon', 'Special Summon "Hero Kid"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17955766,3,0,31,33,600,800,3,1,2,4194306);
INSERT OR REPLACE INTO "texts" VALUES (17955766, 'Neo-Spacian Aqua Dolphin', 'Once per turn: You can discard 1 card; look at your opponent''s hand and choose 1 Monster Card in it. If you control a monster with ATK greater than or equal to the ATK of the chosen card, destroy the chosen card and inflict 500 damage to your opponent. Otherwise, take 500 damage.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89621922,3,0,31,33,500,500,3,2048,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (89621922, 'Neo-Spacian Flare Scarab', 'This card gains 400 ATK for each Spell/Trap Card your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43237273,3,0,31,33,1000,500,3,16384,32,0);
INSERT OR REPLACE INTO "texts" VALUES (43237273, 'Neo-Spacian Dark Panther', 'Once per turn: You can target 1 face-up monster your opponent controls; until the End Phase, while you control this face-up card, this card''s name and effects become those of that target.', '效果复制', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42682609,3,0,30,33,400,600,2,131072,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (42682609, 'Chrysalis Dolphin', 'By Tributing this card while "Neo Space" is on the field, Special Summon 1 "Neo-Spacian Aqua Dolphin" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85087012,3,0,0,33,400,400,3,32,1,8456);
INSERT OR REPLACE INTO "texts" VALUES (85087012, 'Card Trooper', 'Once per turn: You can choose a number from 1 to 3, then send that many cards from the top of your Deck to the Graveyard; this card gains 500 ATK for each card sent to the Graveyard this way, until the end of this turn. If this card you control is destroyed and sent to your Graveyard: Draw 1 card.', 'Gain attack', 'Draw card', 'Send how many cards to Graveyard?', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10526791,3,0,12296,97,2600,2300,8,1,1,32768);
INSERT OR REPLACE INTO "texts" VALUES (10526791, 'Elemental HERO Wildedge', '"Elemental HERO Wildheart" + "Elemental HERO Bladedge"
Must be Fusion Summoned and cannot be Special Summoned by other ways. This card can attack every monster your opponent controls (one attack on each monster per Battle Phase).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55615891,3,0,12296,97,1900,2300,8,1,1,1);
INSERT OR REPLACE INTO "texts" VALUES (55615891, 'Elemental HERO Wild Wingman', '"Elemental HERO Wildheart" + "Elemental HERO Avian"
Must be Fusion Summoned and cannot be Special Summoned by other ways. You can discard 1 card to target 1 Spell/Trap Card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55171412,3,0,602120,97,2500,2000,7,1,2,96);
INSERT OR REPLACE INTO "texts" VALUES (55171412, 'Elemental HERO Aqua Neos', '"Elemental HERO Neos" + "Neo-Spacian Aqua Dolphin"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization".) Once per turn: You can discard 1 card; destroy 1 random card in your opponent''s hand. During the End Phase: Shuffle this card into the Extra Deck.', 'Destroy card in opponent''s hand', 'Back to Extra Deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81566151,3,0,602120,97,2500,2000,7,1,4,8224);
INSERT OR REPLACE INTO "texts" VALUES (81566151, 'Elemental HERO Flare Neos', '"Elemental HERO Neos" + "Neo-Spacian Flare Scarab"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization".) This card gains 400 ATK for each Spell/Trap Card on the field. During the End Phase: Shuffle this card into the Extra Deck.', 'Back to Extra Deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28677304,3,0,602120,97,2500,2000,7,1,32,-2147483616);
INSERT OR REPLACE INTO "texts" VALUES (28677304, 'Elemental HERO Dark Neos', '"Elemental HERO Neos" + "Neo-Spacian Dark Panther"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization".) If this card is not already targeting a monster with its effect: You can target 1 face-up Effect Monster on the field; while you control this face-up card, that target''s effect on the field is negated. During the End Phase: Shuffle this card into the Extra Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29612557,3,0,0,262146,0,0,0,0,0,4202497);
INSERT OR REPLACE INTO "texts" VALUES (29612557, 'Cyclone Boomerang', 'Equip only to "Elemental HERO Wildheart". It gains 500 ATK. When the equipped monster is destroyed by a card effect and sent to the Graveyard: Destroy all Spell and Trap Cards on the field, then inflict 100 damage to your opponent for each Spell/Trap Card destroyed by this effect.', 'Destroy and inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74825788,3,0,0,2,0,0,0,0,0,24576);
INSERT OR REPLACE INTO "texts" VALUES (74825788, 'H - Heated Heart', 'Target 1 face-up monster you control; until the End Phase, it gains 500 ATK, and if it attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (213326,3,0,0,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (213326, 'E - Emergency Call', 'Add 1 "Elemental HERO" monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37318031,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (37318031, 'R - Righteous Justice', 'Destroy Spell/Trap Cards equal to the number of face-up "Elemental HERO" cards you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63703130,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (63703130, 'O - Oversoul', 'Target 1 "Elemental HERO" Normal Monster in your Graveyard; Special Summon that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (191749,3,0,0,2,0,0,0,0,0,393216);
INSERT OR REPLACE INTO "texts" VALUES (191749, 'Hero Flash!!', 'Banish "H - Heated Heart", "E - Emergency Call", "R - Righteous Justice" and "O - Oversoul" from your Graveyard; Special Summon 1 "Elemental HERO" Normal Monster from your Deck. All "Elemental HERO" Normal Monsters you currently control can attack your opponent directly this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16616620,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (16616620, 'Contact', 'Send all "Chrysalis" monsters you control to the Graveyard, and Special Summon 1 monster from your hand or Deck that is written in the card text of those cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78387742,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (78387742, 'Fake Hero', 'Special Summon 1 "Elemental HERO" monster from your hand. That monster cannot attack, and returns to the hand during the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14772491,3,0,0,131074,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (14772491, 'Common Soul', 'Select 1 face-up monster on the field. Special Summon 1 "Neo-Spacian" monster from your hand to the same side of the field as the selected monster. The selected monster gains ATK equal to the ATK of the monster that was Special Summoned by this effect. When this card is removed from the field, return the Special Summoned monster to its owner''s hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42015635,3,0,9,524290,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (42015635, 'Neo Space', '"Elemental HERO Neos" and all Fusion Monsters that list "Elemental HERO Neos" as a Fusion Material Monster gain 500 ATK. Fusion Monsters that list "Elemental HERO Neos" as a Fusion Material Monster do not have to have activate their effects during the End Phase that shuffle them into the Extra Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11471117,3,0,0,262146,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (11471117, 'Light Laser', 'Equip only to a LIGHT Warrior-Type monster. Remove from play any monsters that battle with it at the end of Damage Step.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48976825,3,0,0,65538,0,0,0,0,0,1032);
INSERT OR REPLACE INTO "texts" VALUES (48976825, 'Burial from a Different Dimension', 'Select up to 3 removed from play monsters, and return them to their owners'' Graveyards.', 'Select up to 3 banished monsters', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44676200,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (44676200, 'Hero Barrier', 'Negate 1 attack from an opponent''s monster. You must control a face-up "Elemental HERO" monster to resolve this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55985014,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (55985014, 'Miracle Kids', 'Target 1 monster your opponent controls; that target loses 400 ATK for each "Hero Kid" in your Graveyard, until the End Phase.', 'Lower attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84361420,3,0,0,4,0,0,0,0,0,4194306);
INSERT OR REPLACE INTO "texts" VALUES (84361420, 'Edge Hammer', 'Tribute 1 "Elemental HERO Bladedge" to target 1 monster your opponent controls; destroy that target and inflict damage to your opponent equal to that target''s original ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
