BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (63977008,3,0,4390935,4129,1300,500,3,1,32,-2147221504);
INSERT OR REPLACE INTO "texts" VALUES (63977008, 'Junk Synchron', 'When this card is Normal Summoned, you can select 1 Level 2 or lower monster from your Graveyard, and Special Summon it in face-up Defense Position. That monster''s effect(s) is negated.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23571046,3,0,0,33,800,800,2,32,1,262148);
INSERT OR REPLACE INTO "texts" VALUES (23571046, 'Quillbolt Hedgehog', 'If you control a face-up Tuner monster: You can Special Summon this card from your Graveyard. If this card was Summoned this way, banish it when it leaves the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35537860,3,0,0,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (35537860, 'Synchro Blast Wave', 'Activate only while you control a face-up Synchro Monster. Destroy 1 monster your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56286179,3,0,23,4129,800,300,3,32,1,1065216);
INSERT OR REPLACE INTO "texts" VALUES (56286179, 'Drill Synchron', 'While you control this face-up card, during each battle between a Warrior-Type attacking monster you control and a Defense Position monster whose DEF is lower than the ATK of the attacking monster, inflict the difference as Battle Damage to your opponent. Once per turn, when you inflict battle damage to your opponent with this effect, you can draw 1 card.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9365703,3,0,0,33,900,400,2,1,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (9365703, 'Speed Warrior', 'During the Battle Phase of the turn you Normal Summon this card, you can double its original ATK until the end of the Battle Phase.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51630558,3,0,0,2,0,0,0,0,0,264);
INSERT OR REPLACE INTO "texts" VALUES (51630558, 'Advance Draw', 'Tribute 1 face-up Level 8 or higher monster you control. Draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57421866,3,0,0,33,600,0,1,2048,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (57421866, 'Level Eater', 'If this card is in the Graveyard: You can target 1 face-up Level 5 or higher monster you control; reduce it''s Level by 1, and if you do, Special Summon this card from the Graveyard. This card cannot be Tributed except for a Tribute Summon.', 'Special Summon', 'Select 1 face-up Level 5 or higher monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2295440,3,0,0,2,0,0,0,0,0,262656);
INSERT OR REPLACE INTO "texts" VALUES (2295440, 'One for One', 'Send 1 monster from your hand to the Graveyard; Special Summon 1 Level 1 monster from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98427577,3,0,0,4,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (98427577, 'Scrap-Iron Scarecrow', 'When an opponent''s monster declares an attack: Target the attacking monster; negate that target''s attack, then Set this card face-down again instead of sending it to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
