BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (46986414,3,0,162,17,2500,2100,7,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (46986414, 'Dark Magician', 'The ultimate wizard in terms of attack and defense.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70781052,3,0,69,17,2500,1200,6,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (70781052, 'Summoned Skull', 'A fiend with dark powers for confusing the enemy. Among the Fiend-Type monsters, this monster boasts considerable force.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25652259,3,0,0,17,1500,1600,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (25652259, 'Queen''s Knight', 'This knight catches her opponents off guard, dominating them with swift yet graceful attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90876561,3,0,0,17,1900,1000,5,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (90876561, 'Jack''s Knight', 'A strong master swordsman. His loyalty is to justice, his duty to protect the weak.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40640057,3,0,0,33,300,200,1,8,32,8);
INSERT OR REPLACE INTO "texts" VALUES (40640057, 'Kuriboh', 'uring your opponent''s turn, at damage calculation: You can discard this card; you take no battle damage from that battle (this is a Quick Effect).', 'Reduce damage to 0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95727991,3,0,0,33,1000,2000,5,64,2,4194304);
INSERT OR REPLACE INTO "texts" VALUES (95727991, 'Catapult Turtle', 'Once per turn: You can Tribute 1 monster; inflict damage to your opponent equal to half the Tributed monster''s ATK on the field.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78193831,3,0,0,33,2600,2300,7,1,1,1056768);
INSERT OR REPLACE INTO "texts" VALUES (78193831, 'Buster Blader', 'This card gains 500 ATK for each Dragon-Type monster your opponent controls or is in their Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38033121,3,0,279052450,33,2000,1700,6,2,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (38033121, 'Dark Magician Girl', 'This card gains 300 ATK for every "Dark Magician" or "Magician of Black Chaos" in either player''s Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65240384,3,0,0,33,100,2600,4,1,1,-2113927168);
INSERT OR REPLACE INTO "texts" VALUES (65240384, 'Big Shield Gardna', 'During either player''s turn, when this face-down card (and no other cards) is targeted by a Spell Card: Change this card to face-up Defense Position, and if you do, negate the Spell Card''s activation. If this card is attacked, change it to Attack Position at the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88619463,3,0,0,33,3200,2800,9,2,32,-2147221503);
INSERT OR REPLACE INTO "texts" VALUES (88619463, 'Sorcerer of Dark Magic', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by Tributing 2 Level 6 or higher Spellcaster-Type monsters. You can negate the activation of any Trap Cards and destroy them.', '無効', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64788463,3,0,0,33,1600,1400,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (64788463, 'King''s Knight', 'When this card is Normal Summoned while you control "Queen''s Knight": You can Special Summon 1 "Jack''s Knight" from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41172955,3,0,81,33,1400,600,4,32,1,512);
INSERT OR REPLACE INTO "texts" VALUES (41172955, 'Green Gadget', 'When this card is Normal or Special Summoned: You can add 1 "Red Gadget" from your Deck to your hand.', 'Add 1 "Red Gadget" from your Deck to your hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86445415,3,0,81,33,1300,1500,4,32,1,512);
INSERT OR REPLACE INTO "texts" VALUES (86445415, 'Red Gadget', 'When this card is Normal or Special Summoned: You can add 1 "Yellow Gadget" from your Deck to your hand.', 'Add 1 "Yellow Gadget" from your Deck to your hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13839120,3,0,81,33,1200,1200,4,32,1,512);
INSERT OR REPLACE INTO "texts" VALUES (13839120, 'Yellow Gadget', 'When this card is Normal or Special Summoned: You can add 1 "Green Gadget" from your Deck to your hand.', 'Add 1 "Green Gadget" from your Deck to your hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31305911,3,0,0,33,300,500,3,4,16,20971520);
INSERT OR REPLACE INTO "texts" VALUES (31305911, 'Marshmallon', 'After damage calculation, if this card was attacked, and was face-down at the start of the Damage Step: The attacking player takes 1000 damage. Cannot be destroyed by battle.', '1000damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98502113,3,0,110,97,2900,2400,8,2,32,-2146426871);
INSERT OR REPLACE INTO "texts" VALUES (98502113, 'Dark Paladin', '"Dark Magician" + "Buster Blader"
Must be Fusion Summoned and cannot be Special Summoned by other ways. During either player''s turn, when a Spell Card is activated: You can discard 1 card; negate the activation, and if you do, destroy it. This card must be face-up on the field to activate and to resolve this effect. This card gains 500 ATK for each Dragon-Type monster on the field or in either player''s Graveyard.', 'Negate and Destroy Spell Card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5405694,3,0,4979,129,3000,2500,8,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (5405694, 'Black Luster Soldier', 'This monster can only be Ritual Summoned with the Ritual Spell Card, "Black Luster Ritual".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72302403,3,0,0,2,0,0,0,0,0,67584);
INSERT OR REPLACE INTO "texts" VALUES (72302403, 'Swords of Revealing Light', 'Flip all monsters your opponent controls face-up. This card remains on the field for 3 of your opponent''s turns. While this card is face-up on the field, monsters your opponent controls cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83764718,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (83764718, 'Monster Reborn', 'Target 1 monster in either player''s Graveyard; Special Summon it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5556668,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (5556668, 'Exchange', 'Both players reveal their hands and add 1 card from each other''s hand to their hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55761792,3,0,0,130,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (55761792, 'Black Luster Ritual', 'This card is used to Ritual Summon "Black Luster Soldier". You must also Tribute monsters from the field or your hand whose total Levels equal 8 or more.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87880531,3,0,0,2,0,0,0,0,0,32768);
INSERT OR REPLACE INTO "texts" VALUES (87880531, 'Diffusion Wave-Motion', 'Pay 1000 Life Points. Select 1 Level 7 or higher Spellcaster-Type monster on your side of the field. During this turn, only the selected monster can attack and it attacks all monsters on your opponent''s side of the field once each. The effects of Effect Monsters destroyed by this attack(s) are not activated.', '相手モンスター全てに１回ずつ攻撃', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87910978,3,0,0,2,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (87910978, 'Brain Control', 'Pay 800 Life Points. Select 1 face-up monster your opponent controls. Take control of it until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42664989,3,0,0,2,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (42664989, 'Card of Sanctity', 'Banish all other cards you control and in your hand (min.1 from each); draw until you have 2 cards in your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18807108,3,0,0,131076,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (18807108, 'Spellbinding Circle', 'Select 1 monster. It cannot attack or change its Battle position. When that monster is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44095762,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (44095762, 'Mirror Force', 'When an opponent''s monster declares an attack: Destroy all Attack Position monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81210420,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (81210420, 'Magical Hats', 'Activate only during your opponent''s Battle Phase. Select 2 non-Monster Cards from your Deck and 1 monster you control. Shuffle those 3 cards and Set them on the field in face-down Defense Position. The 2 cards selected from your Deck are treated as monsters (ATK 0/DEF 0) and are destroyed at the end of the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49587034,3,0,0,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (49587034, 'Lightforce Sword', 'Select 1 random card from your opponent''s hand and remove it from play face-down. During your opponent''s 4th Standby Phase after this card''s activation, return that card to their hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13955608,3,0,0,131076,0,0,0,0,0,270336);
INSERT OR REPLACE INTO "texts" VALUES (13955608, 'Stronghold the Moving Fortress', 'Special Summon this card in Defense Position as an Effect Monster (Machine-Type/EARTH/Level 4/ATK 0/DEF 2000). (This card is also still a Trap Card.) While you control a "Green Gadget", "Red Gadget", and "Yellow Gadget", this card gains 3000 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
