BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (13179332,3,0,0,17,100,2100,1,128,4,0);
INSERT OR REPLACE INTO "texts" VALUES (13179332, 'Charcoal Inpachi', 'A wicked wooden spirit that has burned out. The barbecue grilled with this charcoal is so awesome that everybody thinks it''s priceless.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49563947,3,0,0,17,1200,3000,6,2,2,0);
INSERT OR REPLACE INTO "texts" VALUES (49563947, 'Neo Aqua Madoor', 'The true nature of this wizard, who rules all water. It defends itself with a vast, impenetrable wall of ice.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86652646,3,0,0,17,1350,2000,4,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (86652646, 'Skull Dog Marron', 'A lost dog that wandered off 1000 years ago. He''s still waiting for his master to come for him.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12057781,3,0,172,17,400,400,1,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (12057781, 'Goblin Calligrapher', 'A Goblin who devotes himself to mastering perfect calligraphy of the word "False". He gives his all to each stroke.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49441499,3,0,65,33,0,0,1,2048,8,33816584);
INSERT OR REPLACE INTO "texts" VALUES (49441499, 'Ultimate Insect LV1', 'While this card is on the field, it is unaffected by the effects of Spell Cards. During your Standby Phase, by sending this face-up card to the Graveyard, Special Summon 1 "Ultimate Insect LV3" from your hand or Deck. (You cannot activate this effect the turn this card is Normal Summoned, Special Summoned, or flipped face-up.)', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75830094,3,0,65,33,1600,1000,4,8192,4,266248);
INSERT OR REPLACE INTO "texts" VALUES (75830094, 'Horus the Black Flame Dragon LV4', 'Control of this card cannot switch. During the End Phase of a turn that this card destroyed a monster by battle, by sending this card to the Graveyard, Special Summon 1 "Horus the Black Flame Dragon LV6" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11224103,3,0,65,33,2300,1600,6,8192,4,33817088);
INSERT OR REPLACE INTO "texts" VALUES (11224103, 'Horus the Black Flame Dragon LV6', 'This card is unaffected by Spell effects. During the End Phase, if this card destroyed a monster by battle this turn: You can send this face-up card to the Graveyard; Special Summon 1 "Horus the Black Flame Dragon LV8" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48229808,3,0,65,33,3000,1800,8,8192,4,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (48229808, 'Horus the Black Flame Dragon LV8', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by the effect of "Horus the Black Flame Dragon LV6". You can negate the activation and effect of any Spell Cards and destroy them.', 'Negate and Destroy Spell Card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74713516,3,0,65,2097185,100,1000,1,8,32,262400);
INSERT OR REPLACE INTO "texts" VALUES (74713516, 'Dark Mimic LV1', 'FLIP: Draw 1 card. During your Standby Phase, by sending this face-up card to the Graveyard, Special Summon 1 "Dark Mimic LV3" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1102515,3,0,65,33,1000,1000,3,8,32,256);
INSERT OR REPLACE INTO "texts" VALUES (1102515, 'Dark Mimic LV3', 'If this card is sent to the Graveyard by battle, the controller of this card draws 1 card. If this card was Special Summoned by the effect of "Dark Mimic LV1", they draw 2 cards instead.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47507260,3,0,65,33,900,0,2,1,1,262154);
INSERT OR REPLACE INTO "texts" VALUES (47507260, 'Mystic Swordsman LV2', 'If this card attacks a face-down Defense Position monster, destroy the monster immediately with this card''s effect without flipping it face-up or applying damage calculation. During the End Phase of a turn that this card destroyed a monster by battle, by sending this card to the Graveyard, Special Summon 1 "Mystic Swordsman LV4" from your hand or Deck.', 'Destroy', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74591968,3,0,65,33,1900,1600,4,1,1,262146);
INSERT OR REPLACE INTO "texts" VALUES (74591968, 'Mystic Swordsman LV4', 'If you Normal Summon this card, you must place it in face-down Defense Position. If this card attacks a face-down Defense Position monster, destroy the monster immediately with this card''s effect without flipping it face-up or applying damage calculation. During the End Phase of a turn that this card destroyed a monster by battle, by sending this card to the Graveyard, Special Summon 1 "Mystic Swordsman LV6" from your hand or Deck.', 'Destroy', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (980973,3,0,65,33,1200,900,3,8192,8,262656);
INSERT OR REPLACE INTO "texts" VALUES (980973, 'Armed Dragon LV3', 'During your Standby Phase, you can send this face-up card from the field to the Graveyard to Special Summon 1 "Armed Dragon LV5" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73879377,3,0,65,33,2800,1000,7,8192,8,10);
INSERT OR REPLACE INTO "texts" VALUES (73879377, 'Armed Dragon LV7', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by the effect of "Armed Dragon LV5". Send 1 Monster Card from your hand to the Graveyard to destroy all face-up monsters on your opponent''s side of the field with an ATK equal to or less than the ATK of the sent monster.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9264485,3,0,0,33,100,100,1,32768,4,33554432);
INSERT OR REPLACE INTO "texts" VALUES (9264485, 'Horus'' Servant', 'Your opponent cannot select "Horus the Black Flame Dragon" (of any LV) as the target of the effect of a Spell, Trap, or Monster Card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36262024,3,0,0,33,800,500,1,8192,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (36262024, 'Red-Eyes B. Chick', 'You can send this face-up card you control to the Graveyard; Special Summon 1 "Red-Eyes B. Dragon" from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72657739,3,0,0,33,1600,1700,4,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (72657739, 'Malice Doll of Demise', 'If this card is sent from the field to the Graveyard by the effect of a Continuous Spell Card, Special Summon this card from the Graveyard during your Standby Phase.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4041838,3,0,43,33,1800,1000,4,1,16,2);
INSERT OR REPLACE INTO "texts" VALUES (4041838, 'Ninja Grandmaster Sasuke', 'At the start of the Damage Step, if this card attacks a face-up Defense Position monster: Destroy that monster.', 'Destroy Defense Position monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31440542,3,0,0,2097185,300,900,2,1024,1,4096);
INSERT OR REPLACE INTO "texts" VALUES (31440542, 'Rafflesia Seduction', 'FLIP: Take control of 1 face-up monster on your opponent''s side of the field until the end of this turn.', 'コントロールを得る', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67934141,3,0,0,33,500,1000,3,1,4,6299648);
INSERT OR REPLACE INTO "texts" VALUES (67934141, 'Ultimate Baseball Kid', 'This card gains 1000 ATK for each other FIRE monster on the field. By sending a FIRE monster other than this card to the Graveyard, inflict 500 damage to your opponent.', '给与对方1000伤害', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4929256,3,0,190,33,2400,1000,6,64,2,1);
INSERT OR REPLACE INTO "texts" VALUES (4929256, 'Mobius the Frost Monarch', 'When this card is Tribute Summoned: You can target up to 2 Spell/Trap Cards on the field; destroy those targets.', 'Select up to 2 Spell or Trap Cards on the field to destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30314994,3,0,0,33,1500,1200,4,8192,16,2138112);
INSERT OR REPLACE INTO "texts" VALUES (30314994, 'Element Dragon', 'This monster gets the following effect(s) while there is a monster(s) with the following Attribute(s) on the field: ● FIRE: This card gains 500 ATK. ● WIND: If this card destroyed your opponent''s monster by battle, it can attack once again in a row.', 'Attack again', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66712593,3,0,0,33,1500,1200,4,8,32,-2145386496);
INSERT OR REPLACE INTO "texts" VALUES (66712593, 'Element Soldier', 'This monster gets the following effect(s) while there is a monster(s) with the following Attribute(s) on the field: ● WATER: Control of this card cannot switch. ● EARTH: Negate the effect of an Effect Monster that this card destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93107608,3,0,0,33,1200,1300,3,2048,1,1048576);
INSERT OR REPLACE INTO "texts" VALUES (93107608, 'Howling Insect', 'When this card is destroyed by battle and sent to the Graveyard, you can Special Summon 1 Insect-Type monster with 1500 or less ATK from your Deck. Then shuffle your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39191307,3,0,0,33,1400,1100,3,8192,4,1310720);
INSERT OR REPLACE INTO "texts" VALUES (39191307, 'Masked Dragon', 'When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 Dragon-Type monster with 1500 or less ATK from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92084010,3,0,0,33,1500,1600,4,131072,2,2097152);
INSERT OR REPLACE INTO "texts" VALUES (92084010, 'Unshaven Angler', 'When Tribute Summoning a WATER monster, you can treat this 1 monster as 2 Tributes.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38479725,3,0,0,33,1600,1200,4,16384,1,2097152);
INSERT OR REPLACE INTO "texts" VALUES (38479725, 'The Trojan Horse', 'When Tribute Summoning an EARTH monster, you can treat this 1 monster as 2 Tributes.', 'Treat as 2 Tributes', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65878864,3,0,0,2097185,900,1200,5,2048,1,2);
INSERT OR REPLACE INTO "texts" VALUES (65878864, 'Nobleman-Eater Bug', 'FLIP: Destroy 2 monsters on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91862578,3,0,0,33,1200,600,5,256,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (91862578, 'Enraged Muka Muka', 'This card gains 400 ATK and DEF for each card in your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28357177,3,0,0,2097185,900,1000,5,16384,1,16);
INSERT OR REPLACE INTO "texts" VALUES (28357177, 'Hade-Hane', 'FLIP: You can return up to 3 monsters on the field to the owner''s hand.', 'Return to hand', 'Select a monster to return to hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64751286,3,0,0,33,2100,1400,6,1,32,2105344);
INSERT OR REPLACE INTO "texts" VALUES (64751286, 'Penumbral Soldier Lady', 'If this card battles a LIGHT monster, this card gains 1000 ATK during the Damage Step only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90140980,3,0,15,97,0,3000,6,16384,16,0);
INSERT OR REPLACE INTO "texts" VALUES (90140980, 'Ojama King', '"Ojama Green" + "Ojama Yellow" + "Ojama Black"
Select up to 3 of your opponent''s Monster Card Zones. The selected zones cannot be used.', 'Select Monster Card Zones?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27134689,3,0,0,65,4200,3700,9,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (27134689, 'Master of Oz', '"Big Koala" + "Des Kangaroo"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53539634,3,0,0,65,2100,1800,6,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (53539634, 'Sanwitch', '"Sangan" + "Witch of the Black Forest"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90928333,3,0,0,2,0,0,0,0,0,1024);
INSERT OR REPLACE INTO "texts" VALUES (90928333, 'Dark Factory of Mass Production', 'Target 2 Normal Monsters in your Graveyard; add those targets to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26412047,3,0,0,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (26412047, 'Hammer Shot', 'Destroy 1 face-up Attack Position monster with the highest ATK. (If it is a tie, you get to choose.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52817046,3,0,0,65538,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (52817046, 'Mind Wipe', 'Activate only if your opponent has 3 or less cards in their hand. Your opponent adds their hand to the Deck and shuffles it, then draws the same of number of cards they added to the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89801755,3,0,0,2,0,0,0,0,0,3145728);
INSERT OR REPLACE INTO "texts" VALUES (89801755, 'Abyssal Designator', 'Pay 1000 Life Points. Declare a Type and an Attribute. Your opponent must send 1 monster with both the declared Type and Attribute from their hand or Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25290459,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (25290459, 'Level Up!', 'Send 1 face-up "LV" monster on your side of the field to the Graveyard. Special Summon a monster from your hand or Deck that is written in the card text of the sent monster, ignoring any and all Summoning conditions.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52684508,3,0,0,2,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (52684508, 'Inferno Fire Blast', 'Inflict damage to your opponent equal to the original ATK of 1 face-up "Red-Eyes B. Dragon" you control. "Red-Eyes B. Dragon" cannot attack the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97342942,3,0,0,131074,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (97342942, 'Ectoplasmer', 'Once during each player''s End Phase, the turn player Tributes 1 face-up monster on their side of the field and inflicts damage to the opponent equal to half of the original ATK of the Tributed monster.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88089103,3,0,0,2,0,0,0,0,0,32);
INSERT OR REPLACE INTO "texts" VALUES (88089103, 'The Graveyard in the Fourth Dimension', 'Add 2 "LV" monsters from your Graveyard to your Deck and shuffle it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25578802,3,0,0,131074,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (25578802, 'Two-Man Cell Battle', 'During each player''s End Phase, the turn player can Special Summon 1 Level 4 Normal Monster from their hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51562916,3,0,0,2,0,0,0,0,0,2359296);
INSERT OR REPLACE INTO "texts" VALUES (51562916, 'Big Wave Small Wave', 'Destroy all face-up WATER monsters on your side of the field. Then you can Special Summon WATER monsters from your hand, up to the same number of monsters destroyed by this effect.', 'Special summon WATER monsters from hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27967615,3,0,70,262146,0,0,0,0,0,268443648);
INSERT OR REPLACE INTO "texts" VALUES (27967615, 'Fusion Weapon', 'Equip only to a Level 6 or lower Fusion Monster. The equipped monster gains 1500 ATK and DEF.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54351224,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (54351224, 'Ritual Weapon', 'Equip only to a Level 6 or lower Ritual Monster. The equipped monster gains 1500 ATK and DEF.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90740329,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (90740329, 'Taunt', 'Activate only during your opponent''s Main Phase 1, select 1 monster on your side of the field. While the selected card remains on the field, if your opponent attacks with a monster(s) this turn, they must select the selected monster as the attack target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27744077,3,0,0,4,0,0,0,0,0,131072);
INSERT OR REPLACE INTO "texts" VALUES (27744077, 'Absolute End', 'Activate only during your opponent''s turn. This turn, the attacks from your opponent''s monsters become direct attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53239672,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (53239672, 'Spirit Barrier', 'While you control a monster, you take no battle damage.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89628781,3,0,97,131076,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (89628781, 'Ninjitsu Art of Decoy', 'Target 1 face-up "Ninja" monster you control; that target cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26022485,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (26022485, 'Enervating Mist', 'Your opponent''s hand size limit becomes 5.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52417194,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (52417194, 'Heavy Slump', 'Activate only when your opponent has 8 or more cards in their hand. Your opponent adds their hand to the Deck, shuffles it, and draws 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89405199,3,0,0,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (89405199, 'Greed', 'Each time a player draws cards because of a card effect, they take 500 damage during the End Phase for each card drawn by the card effect.', 'ダメージを受ける', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15800838,3,0,0,4,0,0,0,0,0,64);
INSERT OR REPLACE INTO "texts" VALUES (15800838, 'Mind Crush', 'Declare 1 card name; if that card is in your opponent''s hand, they must discard all copies of it from their hand to the Graveyard, otherwise you discard 1 random card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80863132,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (80863132, 'Null and Void', 'Activate only when an effect of drawing card(s) is activated. Both players see the cards drawn by the effect and discard them all to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52648457,3,0,0,4,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (52648457, 'Gorgon''s Eye', 'Until the end of this turn, all effects of Defense Position monsters are negated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51394546,3,0,0,4,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (51394546, 'Cemetary Bomb', 'Inflict 100 damage to your opponent for each card in their Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88789641,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (88789641, 'Hallowed Life Barrier', 'Discard 1 card. This turn, any damage you take from your opponent''s cards and effects becomes 0.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35322812,3,0,0,17,500,2500,5,32,4,0);
INSERT OR REPLACE INTO "texts" VALUES (35322812, 'Woodborg Inpachi', 'The new form of the enigmatic Inpachi, remodeled by cutting-edge Dark World technology. Maneuverability has been sacrificed for strong armor, which is considered more important.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62327910,3,0,0,17,500,1200,4,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (62327910, 'Mighty Guard', 'A machine soldier that was developed as a guard. It is made of rust-proof metal.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8715625,3,0,0,17,500,500,2,32,32,0);
INSERT OR REPLACE INTO "texts" VALUES (8715625, 'Bokoichi the Freightening Car', 'A freight car that is exclusively for Dekoichi. It can transport anything, but most cargo arrives broken.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34100324,3,0,100,17,500,500,2,512,8,0);
INSERT OR REPLACE INTO "texts" VALUES (34100324, 'Harpie Girl', 'A Harpie chick who aspires to flit about beautifully and gorgeously, but attack sharply.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61505339,3,0,0,33,2300,3000,8,4096,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (61505339, 'The Creator', 'This card cannot be Special Summoned from the Graveyard. Once per turn, you can select 1 monster in your Graveyard, then send 1 card from your hand to the Graveyard and Special Summon that monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97093037,3,0,0,33,1600,1500,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (97093037, 'The Creator Incarnate', 'You can Tribute this card to Special Summon 1 "The Creator" from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34088136,3,0,65,33,1400,900,3,2048,8,270336);
INSERT OR REPLACE INTO "texts" VALUES (34088136, 'Ultimate Insect LV3', 'If this card was Special Summoned by the effect of "Ultimate Insect LV1", while it remains on the field all of your opponent''s monsters lose 300 ATK. During your Standby Phase, by sending this face-up card to the Graveyard, Special Summon 1 "Ultimate Insect LV5" from your hand or Deck. (You cannot activate this effect the turn this card is Normal Summoned, Special Summoned, or flipped face-up.)', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60482781,3,0,65,33,2300,1700,6,1,1,34);
INSERT OR REPLACE INTO "texts" VALUES (60482781, 'Mystic Swordsman LV6', 'If you Normal Summon this card, you must place it in face-down Defense Position. If this card attacks a face-down Defense Position monster, destroy the monster immediately with this card''s effect without flipping it face-up or applying damage calculation. You can return the monster destroyed with this effect to the top of its owner''s Deck, instead of sending it to the Graveyard.', 'Destroy', 'Return monster to top of its owner''s Deck?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1995985,3,0,65,33,1000,1000,3,1,16,262656);
INSERT OR REPLACE INTO "texts" VALUES (1995985, 'Silent Swordsman LV3', 'Negate your opponent''s Spell effects that target this card. During your Standby Phase: You can send this face-up card to the Graveyard; Special Summon 1 "Silent Swordsman LV5" from your hand or Deck. You cannot activate this effect the turn this card is Summoned or flipped face-up.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81306586,3,0,90,33,900,1800,4,64,2,2105360);
INSERT OR REPLACE INTO "texts" VALUES (81306586, 'Nightmare Penguin', 'All face-up WATER monsters you control gain 200 ATK. When this card is flipped face-up: Target 1 card your opponent controls; return that target to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23265594,3,0,0,1057,500,500,3,32,32,17833984);
INSERT OR REPLACE INTO "texts" VALUES (23265594, 'Heavy Mech Support Platform', 'Once per turn, you can either: Target 1 Machine-Type monster you control, equip this card to that target, OR: Unequip this card and Special Summon it in face-up Attack Position. While equipped by this effect, the equipped monster gains 500 ATK and DEF. (A monster can only be equipped with 1 Union monster at a time. If the equipped monster would be destroyed, destroy this card instead.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18891691,3,0,0,33,2700,1500,8,32,1,1056768);
INSERT OR REPLACE INTO "texts" VALUES (18891691, 'Perfect Machine King', 'This card gains 500 ATK for each other Machine-Type monster on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65260293,3,0,0,33,1500,1200,4,2,16,2129920);
INSERT OR REPLACE INTO "texts" VALUES (65260293, 'Element Magician', 'This monster gets the following effect(s) while there is a monster(s) with the following Attribute(s) on the field: ● WATER: Control of this card cannot switch. ● WIND: If this card destroyed your opponent''s monster by battle, it can attack once again in a row.', 'Attack again', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92755808,3,0,0,33,1500,1200,4,65536,32,-2145378304);
INSERT OR REPLACE INTO "texts" VALUES (92755808, 'Element Saurus', 'This monster gets the following effect(s) while there is a monster(s) with the following Attribute(s) on the field: ● FIRE: This card gains 500 ATK. ● EARTH: Negate the effect of an Effect Monster that this card destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28143906,3,0,0,33,2400,1400,6,512,8,1024);
INSERT OR REPLACE INTO "texts" VALUES (28143906, 'Roc from the Valley of Haze', 'When this card is sent directly from your hand to the Graveyard, add this card to the Deck and shuffle it.', 'Return to deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64538655,3,0,0,33,1200,1200,4,1,8,134217730);
INSERT OR REPLACE INTO "texts" VALUES (64538655, 'Sasuke Samurai 4', 'If this card battles a monster, toss a coin and call heads or tails before damage calculation. If you call it right, destroy the opponent''s monster with this effect.', '战斗怪兽破坏', '正面', '反面', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91932350,3,76812113,100,33,1300,1400,4,512,8,2105344);
INSERT OR REPLACE INTO "texts" VALUES (91932350, 'Harpie Lady 1', '(This card''s name is always treated as "Harpie Lady".)
All WIND monsters gain 300 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27927359,3,76812113,100,33,1300,1400,4,512,8,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (27927359, 'Harpie Lady 2', '(This card''s name is always treated as "Harpie Lady".)
Negate the effects of Flip Effect monsters this card destroys by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54415063,3,76812113,100,33,1300,1400,4,512,8,65536);
INSERT OR REPLACE INTO "texts" VALUES (54415063, 'Harpie Lady 3', '(This card''s name is always treated as "Harpie Lady").
An opponent''s monster that battles this card cannot declare an attack during your opponent''s next 2 turns.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90810762,3,0,0,33,100,200,3,128,4,139264);
INSERT OR REPLACE INTO "texts" VALUES (90810762, 'Raging Flame Sprite', 'This card can attack your opponent directly. If this card inflicts battle damage to your opponent by a direct attack: This card gains 1000 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26205777,3,0,190,33,2400,1000,6,128,4,4194368);
INSERT OR REPLACE INTO "texts" VALUES (26205777, 'Thestalos the Firestorm Monarch', 'When this card is Tribute Summoned, discard 1 random card from your opponent''s hand. If it was a Monster Card, inflict damage to your opponent equal to its Level x 100.', 'Opponent discards 1 random card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53693416,3,0,0,33,1300,1200,3,512,8,33554432);
INSERT OR REPLACE INTO "texts" VALUES (53693416, 'Eagle Eye', 'When this card is Normal Summoned successfully, no Trap Cards can be activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89698120,3,0,0,33,1300,1200,3,1,1,33554432);
INSERT OR REPLACE INTO "texts" VALUES (89698120, 'Tactical Espionage Expert', 'When this card is Normal Summoned successfully, no Trap Cards can be activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26082229,3,0,0,33,1300,1200,3,128,4,33554432);
INSERT OR REPLACE INTO "texts" VALUES (26082229, 'Invasion of Flames', 'When this card is Normal Summoned successfully, no Trap Cards can be activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52571838,3,0,0,33,1300,1200,3,131072,2,33554432);
INSERT OR REPLACE INTO "texts" VALUES (52571838, 'Creeping Doom Manta', 'When this card is Normal Summoned successfully, no Trap Cards can be activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88975532,3,0,0,33,1600,600,4,32768,32,0);
INSERT OR REPLACE INTO "texts" VALUES (88975532, 'Pitch-Black Warwolf', 'Your opponent cannot activate Trap Cards during the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15960641,3,0,0,33,1600,600,4,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (15960641, 'Mirage Dragon', 'Your opponent cannot activate Trap Cards during the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51355346,3,0,0,33,2000,0,4,128,4,1073154);
INSERT OR REPLACE INTO "texts" VALUES (51355346, 'Gaia Soul the Combustible Collective', 'You can tribute up to 2 Pyro-Type monsters. If you do this, this card gains ATK equal to the number of tributed monsters x 1000. During battle between this card and a Defense Position monster whose DEF is lower than the ATK of this card, inflict the difference as Battle Damage to your opponent. Destroy this card at the end of this turn.', 'Gain ATK', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88753985,3,0,0,33,300,200,2,128,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (88753985, 'Fox Fire', 'During the End Phase, if this card was destroyed by battle and sent to the Graveyard this turn and was face-up at the start of the Damage Step: Special Summon this card from the Graveyard. This face-up card cannot be Tributed for a Tribute Summon.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14148099,3,0,21,33,2300,1100,6,32,32,83886082);
INSERT OR REPLACE INTO "texts" VALUES (14148099, 'Big Core', 'Put 3 counters on this card when you Normal Summon it. This card cannot be destroyed as a result of battle. If this card battles a monster, remove 1 counter from this card at the end of the Damage Step. If this card battles without a counter, destroy this card at the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51632798,3,0,0,33,2800,2000,7,32,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (51632798, 'Fusilier Dragon, the Dual-Mode Beast', 'You can Normal Summon or Set this card without Tributing. If you do, its original ATK and DEF are halved.', 'Summon without tributes', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87621407,3,0,0,2097185,1400,1000,4,32,32,256);
INSERT OR REPLACE INTO "texts" VALUES (87621407, 'Dekoichi the Battlechanted Locomotive', 'FLIP: Draw 1 card, then draw 1 additional card for each face-up "Bokoichi the Freightening Car" you control.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13026402,3,0,0,33,300,400,2,32,4,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (13026402, 'A-Team: Trap Disposal Unit', 'This effect can be used during either player''s turn. When your opponent activates a Trap Card, Tribute this face-up card to negate the activation of the Trap Card and destroy it.', '発動を無効にし、それを破壊', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40410110,3,0,0,33,1800,1600,4,1024,16,2097152);
INSERT OR REPLACE INTO "texts" VALUES (40410110, 'Homunculus the Alchemic Being', 'Once per turn, you can change the Attribute of this monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86805855,3,0,0,97,2200,1500,6,1,32,4);
INSERT OR REPLACE INTO "texts" VALUES (86805855, 'Dark Blade the Dragon Knight', '"Dark Blade" + "Pitch-Dark Dragon"
Each time this card inflicts Battle Damage to your opponent, you can select up to 3 Monster Cards from your opponent''s Graveyard and remove them from play.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13803864,3,0,0,97,300,100,6,4,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (13803864, 'Mokey Mokey King', '"Mokey Mokey" + "Mokey Mokey" + "Mokey Mokey"
When this card is removed from the field, you can Special Summon as many "Mokey Mokey" as possible from your Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49398568,3,0,0,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (49398568, 'Serial Spell', 'Activate only when you activate one of your Normal Spell Cards. Discard all the cards in your hand to the Graveyard. The effect of this card becomes the same as the Normal Spell Card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75782277,3,0,100,524290,0,0,0,0,0,8193);
INSERT OR REPLACE INTO "texts" VALUES (75782277, 'Harpies'' Hunting Ground', 'All Winged Beast-Type monsters gain 200 ATK and DEF. When any "Harpie Lady" or "Harpie Lady Sisters" are Normal or Special Summoned: The player who conducted the Summon targets 1 Spell/Trap Card on the field; destroy that target.', 'S/T Destruction', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12181376,3,0,0,2,0,0,0,0,0,-2147475456);
INSERT OR REPLACE INTO "texts" VALUES (12181376, 'Triangle Ecstasy Spark', 'Until the End Phase, the ATK of all "Harpie Lady Sisters" currently on the field becomes 2700, your opponent cannot activate any Trap Cards, also negate all your opponent''s Trap Card effects on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48576971,3,0,0,262146,0,0,0,0,0,320);
INSERT OR REPLACE INTO "texts" VALUES (48576971, 'Necklace of Command', 'When a monster you control that''s equipped with this card is destroyed by battle, and this card is sent to the Graveyard, you can either:
● Draw 1 card. OR
● Discard 1 random card from your opponent''s hand.', 'Select effect', 'Draw 1 card', 'Discard 1 random card from your opponent''s hand', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63995093,3,0,0,2,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (63995093, 'Machine Duplication', 'Select 1 face-up Machine-Type monster you control with 500 or less ATK. You can Special Summon up to 2 cards with the same name from your Deck.', 'Select 1 face-up Machine-Type monster with 500 or less ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75560629,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (75560629, 'Flint', 'A monster equipped with this card loses 300 ATK and cannot change its Battle Position or attack. If the equipped monster is destroyed, select 1 monster on the field and equip this card to that monster.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1965724,3,0,0,131074,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (1965724, 'Mokey Mokey Smackdown', 'While a face-up "Mokey Mokey" is on your side of the field, if a Fairy-Type monster on your side of the field is destroyed, the ATK of all "Mokey Mokey" on your side of the field becomes 3000 until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47453433,3,0,0,2,0,0,0,0,0,40);
INSERT OR REPLACE INTO "texts" VALUES (47453433, 'Back to Square One', 'Discard 1 card, then target 1 monster on the field; place that target on the top of the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74848038,3,0,0,2,0,0,0,0,0,1048);
INSERT OR REPLACE INTO "texts" VALUES (74848038, 'Monster Reincarnation', 'Discard 1 card, then target 1 monster in your Graveyard; add it to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (242146,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (242146, 'Ballista of Rampart Smashing', 'If the equipped monster attacks a face-down Defense Position monster, it gains 1500 ATK during damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37231841,3,0,0,131074,0,0,0,0,0,288);
INSERT OR REPLACE INTO "texts" VALUES (37231841, 'Lighten the Load', 'Once per turn, you can add 1 Level 7 or higher monster from your hand to your Deck and shuffle it, then draw 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13626450,3,0,0,65538,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (13626450, 'Malice Dispersion', 'Discard 1 card from your hand. Destroy all face-up Continuous Trap Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35686187,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (35686187, 'Tragedy', 'Activate only when a monster on your opponent''s side of the field in face-up Attack Position is changed to face-up Defense Position. Destroy all Defense Position monsters on your opponent''s side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49010598,3,0,0,1048580,0,0,0,0,0,-2147483638);
INSERT OR REPLACE INTO "texts" VALUES (49010598, 'Divine Wrath', 'When a monster effect is activated: Discard 1 card; negate the activation, and if you do, destroy that monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76515293,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (76515293, 'Xing Zhen Hu', 'Activate by selecting 2 Set Spell or Trap Cards on the field. The selected Spell or Trap Cards cannot be activated.', 'セットされた魔法・罠カードを２枚選んで下さい', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12503902,3,0,0,131076,0,0,0,0,0,33562624);
INSERT OR REPLACE INTO "texts" VALUES (12503902, 'Rare Metalmorph', 'Activate this card by targeting 1 Machine-Type monster on the field; it gains 500 ATK. Once, negate a Spell effect that targets that monster. When that monster leaves the field, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49998907,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (49998907, 'Fruits of Kozaky''s Studies', 'Look at the top 3 cards of your Deck and return those cards to the top of the Deck in any order.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75392615,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (75392615, 'Mind Haxorz', 'Pay 500 Life Points. Look at your opponent''s hand and all Set cards on their side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1781310,3,0,0,4,0,0,0,0,0,323);
INSERT OR REPLACE INTO "texts" VALUES (1781310, 'Fuh-Rin-Ka-Zan', 'You can only activate this card when there are at least 1 monster each of WIND, WATER, FIRE and EARTH Attributes face-up on the field. Select and apply 1 of these effects: ● Destroy all monsters on your opponent''s side of the field. ● Destroy all Spell and Trap Cards on your opponent''s side of the field. ● Randomly discard 2 cards from your opponent''s hand. ● Draw 2 cards.', 'Destroy all monsters on your opponent''s side of the field', 'Destroy all Spell and Trap Cards on your opponent''s side of the field', 'Randomly discard 2 cards from your opponent''s hand', 'Draw 2 cards', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48276469,3,0,0,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (48276469, 'Chain Burst', 'Each time a player activates a Trap Card, they take 1000 damage immediately after it resolves.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74270067,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (74270067, 'Pikeru''s Circle of Enchantment', 'Damage to you from card effects becomes 0 until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1669772,3,0,0,4,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (1669772, 'Spell Purification', 'Discard 1 card from your hand. Destroy all face-up Continuous Spell Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37053871,3,0,0,131076,0,0,0,0,0,131072);
INSERT OR REPLACE INTO "texts" VALUES (37053871, 'Astral Barrier', 'If your opponent''s monster attacks a monster on your side of the field, you can make the attack a direct attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74458486,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (74458486, 'Covering Fire', 'During the Damage Step, while an opponent''s monster is attacking a monster you control: Target 1 other face-up monster you control; your attacked monster gains ATK equal to that target''s ATK during the Damage Step only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36119641,3,0,0,17,1700,1000,4,131072,2,0);
INSERT OR REPLACE INTO "texts" VALUES (36119641, 'Space Mambo', 'A Space Mambo floating in the vast universe. This living relic was found in the ruins of a super civilization on Alphard 4.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62113340,3,0,0,17,1500,1000,4,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (62113340, 'Divine Dragon Ragnarok', 'A legendary dragon sent by the gods as their instrument. Legends say that if provoked, the whole world will sink beneath the sea.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8508055,3,0,0,17,1200,0,3,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (8508055, 'Chu-Ske the Mouse Fighter', 'A fiery mouse, travelling the world to become the strongest fighter in the world of mice. Be careful not to touch him, or you will get burned.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35052053,3,0,0,17,1900,1500,4,2048,1,0);
INSERT OR REPLACE INTO "texts" VALUES (35052053, 'Insect Knight', 'Of all Insect fighters, he is the paragon of the Indestructible Insect Invaders, which only the elite of the elite can join. We can no longer ignore their unmatched battle prowess.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61441708,3,0,0,33,2400,1600,8,512,4,262145);
INSERT OR REPLACE INTO "texts" VALUES (61441708, 'Sacred Phoenix of Nephthys', 'During your next Standby Phase after this card was destroyed by a card effect and sent to the Graveyard: Special Summon this card from the Graveyard. When you do: Destroy all Spell and Trap Cards on the field.', 'Special Summon', 'Destroy all Spell/Trap cards', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98446407,3,0,0,33,600,600,2,2,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (98446407, 'Hand of Nephthys', 'You can Tribute this card and 1 other monster to Special Summon 1 "Sacred Phoenix of Nephthys" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34830502,3,0,65,33,2300,900,5,2048,8,270848);
INSERT OR REPLACE INTO "texts" VALUES (34830502, 'Ultimate Insect LV5', 'If this card was Special Summoned by the effect of "Ultimate Insect LV3", while it remains on the field all of your opponent''s monsters lose 500 ATK. During your Standby Phase, by sending this face-up card to the Graveyard, Special Summon 1 "Ultimate Insect LV7" from your hand or Deck. (You cannot activate this effect the turn this card is Normal Summoned, Special Summoned, or flipped face-up.)', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74388798,3,0,65,33,2300,1000,5,1,16,33816584);
INSERT OR REPLACE INTO "texts" VALUES (74388798, 'Silent Swordsman LV5', 'This card is unaffected by your opponent''s Spell effects. During your next Standby Phase after this card inflicts battle damage to your opponent by a direct attack: You can send this face-up card to the Graveyard; Special Summon 1 "Silent Swordsman LV7" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60229110,3,0,190,33,2400,1000,6,256,1,3);
INSERT OR REPLACE INTO "texts" VALUES (60229110, 'Granmarg the Rock Monarch', 'When this card is Tribute Summoned, destroy 1 face-down card on the field.', 'Select face-down card to destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97623219,3,0,0,33,1500,1200,4,4,16,2105344);
INSERT OR REPLACE INTO "texts" VALUES (97623219, 'Element Valkyrie', 'This monster gets the following effect(s) while there is a monster(s) with the following Attribute(s) on the field: ● FIRE: This card gains 500 ATK. ● WATER: Control of this card cannot switch.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23118924,3,0,0,33,1500,1200,4,8,32,-2145353728);
INSERT OR REPLACE INTO "texts" VALUES (23118924, 'Element Doom', 'This monster gets the following effect(s) while there is a monster(s) with the following Attribute(s) on the field: ● EARTH: Negate the effect of an Effect Monster that this card destroyed by battle. ● WIND: If this card destroyed your opponent''s monster by battle, it can attack once again in a row.', 'Attack again', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60102563,3,0,0,33,1000,800,4,16384,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (60102563, 'Maji-Gire Panda', 'Each time a Beast-Type monster(s) on the field is destroyed, this card gains 500 ATK.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96501677,3,0,0,33,0,500,2,16384,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (96501677, 'Catnipped Kitty', 'This card cannot be attacked if there is another Beast-Type monster on your side of the field. Once per turn, you can make the DEF of 1 monster on your opponent''s side of the field 0 until the end of this turn.', '守備力を０にする', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22996376,3,0,0,33,2700,1500,7,16384,1,9232);
INSERT OR REPLACE INTO "texts" VALUES (22996376, 'Behemoth the King of All Animals', 'This card can be Normal Summoned or Set with 1 Tribute. In that case, the original ATK of this card becomes 2000. When this card is Tribute Summoned, you can return from your Graveyard to the owner''s hand a number of Beast-Type monsters equal to the number of Tributed monsters.', 'Summon with 1 Tribute', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59380081,3,0,0,33,2000,1000,5,16384,1,65536);
INSERT OR REPLACE INTO "texts" VALUES (59380081, 'Big-Tusked Mammoth', 'Monsters your opponent controls cannot attack the turn they are Summoned.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95789089,3,0,0,33,800,700,4,16384,1,2048);
INSERT OR REPLACE INTO "texts" VALUES (95789089, 'Kangaroo Champ', 'A monster that battles with this card is changed to Defense Position after damage calculation.', '守備表示になる', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22873798,3,0,0,33,1000,300,3,16384,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (22873798, 'Hyena', 'When this card is sent to the Graveyard by battle, you can Special Summon any "Hyena"(s) from your Deck. Then shuffle your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58268433,3,0,0,33,400,300,2,16384,1,2050);
INSERT OR REPLACE INTO "texts" VALUES (58268433, 'Blade Rabbit', 'When this card is changed from Attack Position to face-up Defense Position, destroy 1 monster on your opponent''s side of the field.', '破坏对方场上1只怪兽', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94667532,3,0,0,33,1000,1000,4,32,16,4194304);
INSERT OR REPLACE INTO "texts" VALUES (94667532, 'Mecha-Dog Marron', 'When this card is destroyed by battle and sent to the Graveyard, inflict 1000 damage to both players. When this card on the field is destroyed and sent to the Graveyard except by battle, inflict 1000 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21051146,3,0,0,33,1400,1700,4,2,4,67108866);
INSERT OR REPLACE INTO "texts" VALUES (21051146, 'Blast Magician', 'Each time a Spell Card is activated, place 1 Spell Counter on this card. You can remove any number of Spell Counters from this card to destroy 1 face-up monster on the field with ATK equal to or less than 700 x the number of counters you removed.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16956455,3,0,0,33,1800,1000,4,32768,1,1);
INSERT OR REPLACE INTO "texts" VALUES (16956455, 'Chiron the Mage', 'Once per turn: You can discard 1 Spell Card, then target 1 Spell/Trap Card your opponent controls; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57046845,3,0,0,33,2600,2200,7,1,16,2);
INSERT OR REPLACE INTO "texts" VALUES (57046845, 'Gearfried the Swordmaster', 'Cannot be Normal Summoned/Set. Must be Special Summoned with "Release Restraint" and cannot be Special Summoned by other ways. When an Equip Card(s) is equipped to this card: Target 1 monster your opponent controls; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84430950,3,0,0,33,500,800,4,1,32,32768);
INSERT OR REPLACE INTO "texts" VALUES (84430950, 'Armed Samurai - Ben Kei', 'In addition to a normal attack, this card can attack during the same Battle Phase as many times as the number of Equip Cards equipped to it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20939559,3,0,0,33,1400,200,4,8,32,131072);
INSERT OR REPLACE INTO "texts" VALUES (20939559, 'Shadowslayer', 'If all monsters your opponent controls are in Defense Position, this card can attack your opponent directly.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52323207,3,0,0,33,800,1800,4,256,1,2064);
INSERT OR REPLACE INTO "texts" VALUES (52323207, 'Golem Sentry', 'Once per turn: You can change this card to face-down Defense Position. When this card is Flip Summoned: Target 1 monster your opponent controls; return that target to the hand.', 'Flip into face-down Defense Position', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89718302,3,0,0,33,1200,1200,4,32768,1,138412032);
INSERT OR REPLACE INTO "texts" VALUES (89718302, 'Abare Ushioni', 'Once per turn, you can toss a coin and call it. If you call it right, inflict 1000 damage to your opponent. If you call it wrong, you take 1000 damage.', 'Coin toss', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15717011,3,0,70,33,1000,1600,3,256,16,270794752);
INSERT OR REPLACE INTO "texts" VALUES (15717011, 'The Light - Hex-Sealed Fusion', 'You can substitute this card for any 1 Fusion Material Monster. The other Fusion Material Monster(s) must be the correct one(s). By Tributing Fusion Material Monsters on the field, including this card, Special Summon 1 LIGHT Fusion Monster from your Fusion Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52101615,3,0,70,33,1000,1600,3,256,32,270794752);
INSERT OR REPLACE INTO "texts" VALUES (52101615, 'The Dark - Hex-Sealed Fusion', 'You can substitute this card for any 1 Fusion Material Monster. The other Fusion Material Monster(s) must be the correct one(s). By Tributing Fusion Material Monsters on the field, including this card, Special Summon 1 DARK Fusion Monster from your Fusion Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88696724,3,0,70,33,1000,1600,3,256,1,270794752);
INSERT OR REPLACE INTO "texts" VALUES (88696724, 'The Earth - Hex-Sealed Fusion', 'You can substitute this card for any 1 Fusion Material Monster. The other Fusion Material Monster(s) must be the correct one(s). By Tributing Fusion Material Monsters on the field, including this card, Special Summon 1 EARTH Fusion Monster from your Fusion Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15090429,3,0,0,33,1500,1600,4,4,8,2097152);
INSERT OR REPLACE INTO "texts" VALUES (15090429, 'Whirlwind Prodigy', 'When Tribute Summoning a WIND monster, you can treat this 1 monster as 2 Tributes.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41089128,3,0,0,33,1500,1600,4,128,4,2097152);
INSERT OR REPLACE INTO "texts" VALUES (41089128, 'Flame Ruler', 'This card is treated as 2 Tributes for the Tribute Summon of a FIRE monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87473172,3,0,0,33,1000,800,4,512,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (87473172, 'Firebird', 'Each time a Winged Beast-Type monster(s) on your side of the field is destroyed, this card gains 500 ATK.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14878871,3,0,0,33,300,100,4,16384,1,1311232);
INSERT OR REPLACE INTO "texts" VALUES (14878871, 'Rescue Cat', 'You can send this face-up card to the Graveyard to Special Summon 2 Level 3 or lower Beast-Type monsters from your Deck. Those monsters are destroyed during the End Phase.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40267580,3,0,0,2097185,200,900,2,8,32,8392704);
INSERT OR REPLACE INTO "texts" VALUES (40267580, 'Brain Jacker', 'FLIP: Equip this card to a monster on your opponent''s side of the field and treat it as an Equip Card. Take control of the equipped monster. Your opponent gains 500 Life Points during each of their Standby Phases.', 'Equip', 'Gain LP', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87751584,3,0,0,97,2600,1200,8,32,32,134217730);
INSERT OR REPLACE INTO "texts" VALUES (87751584, 'Gatling Dragon', '"Barrel Dragon" + "Blowback Dragon"
Once per turn: You can toss a coin 3 times and destroy as many monsters on the field as possible, but not more than the number of Heads.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13756293,3,0,12397,97,2400,1100,7,8192,32,34865152);
INSERT OR REPLACE INTO "texts" VALUES (13756293, 'King Dragun', '"Lord of D." + "Divine Dragon Ragnarok"
Your opponent cannot select any Dragon-Type monsters as the target(s) of Spell, Trap, or Monster Card effects. Once per turn, you can Special Summon 1 Dragon-Type monster from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49140998,3,0,0,2,0,0,0,0,0,1064);
INSERT OR REPLACE INTO "texts" VALUES (49140998, 'A Feather of the Phoenix', 'Discard 1 card. Select 1 card from your Graveyard and return it to the top of your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76539047,3,0,0,131074,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (76539047, 'Poison Fangs', 'Each time a Beast-Type monster inflicts Battle Damage to your opponent, inflict 500 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51481927,3,0,0,131074,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (51481927, 'Spell Absorption', 'Each time a Spell Card is activated, gain 500 Life Points immediately after it resolves.', '恢复LP', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69162969,3,0,0,2,0,0,0,0,0,10);
INSERT OR REPLACE INTO "texts" VALUES (69162969, 'Lightning Vortex', 'Discard 1 card; destroy all face-up monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33767325,3,0,0,2,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (33767325, 'Meteor of Destruction', 'If your opponent''s Life Points are higher than 3000: Inflict 1000 damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12923641,3,0,0,131074,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (12923641, 'Swords of Concealing Light', 'When this card resolves, all monsters your opponent controlled when this card was activated are changed to face-down Defense Position. Monsters your opponent controls cannot change their battle positions. Destroy this card during your 2nd Standby Phase after activation.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49328340,3,0,0,131074,0,0,0,0,0,16640);
INSERT OR REPLACE INTO "texts" VALUES (49328340, 'Spiral Spear Strike', 'When a "Gaia the Fierce Knight", "Swift Gaia the Fierce Knight" or "Gaia the Dragon Champion" you control attacks a Defense Position monster, if the ATK of that card is higher than the DEF of the Defense Position monster, inflict the difference as Battle Damage to your opponent. If "Gaia the Dragon Champion" inflicts Battle Damage with this effect, draw 2 cards and discard 1 card.', 'Draw', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75417459,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (75417459, 'Release Restraint', 'Tribute 1 "Gearfried the Iron Knight"; Special Summon 1 "Gearfried the Swordmaster" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1801154,3,0,0,524290,0,0,0,0,0,268697600);
INSERT OR REPLACE INTO "texts" VALUES (1801154, 'Centrifugal Field', 'When a Fusion Monster is destroyed and sent to the Graveyard by a card effect, select 1 of the Fusion Material Monsters written in the card text of that Fusion Monster from your Graveyard and Special Summon it to your side of the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48206762,3,0,0,262146,0,0,0,0,0,262148);
INSERT OR REPLACE INTO "texts" VALUES (48206762, 'Fulfillment of the Contract', 'Pay 800 Life Points. Select 1 Ritual Monster from your Graveyard, Special Summon it, and equip it with this card. When this card is destroyed, remove the equipped monster from play.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74694807,3,0,70,262146,0,0,0,0,0,262148);
INSERT OR REPLACE INTO "texts" VALUES (74694807, 'Re-Fusion', 'Pay 800 Life Points. Select 1 Fusion Monster from your Graveyard, Special Summon it, and equip it with this card. When this card is destroyed, remove the equipped monster from play.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1689516,3,0,0,65538,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (1689516, 'The Big March of Animals', 'Until the end of this turn, all face-up Beast-Type monsters on your side of the field gain 200 ATK for each Beast-Type monster on your side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37083210,3,0,0,4,0,0,0,0,0,8194);
INSERT OR REPLACE INTO "texts" VALUES (37083210, 'Cross Counter', 'If the DEF of an attacked Defense Position monster is higher than the ATK of your opponent''s attacking monster, the Battle Damage inflicted to your opponent is doubled. Destroy the attacking monster after damage calculation.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73578229,3,0,0,131076,0,0,0,0,0,33554434);
INSERT OR REPLACE INTO "texts" VALUES (73578229, 'Pole Position', 'The face-up monster(s) with the highest ATK on the field is unaffected by the effects of Spell Cards. When "Pole Position" is removed from the field, destroy the face-up monster(s) with the highest ATK on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (967928,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (967928, 'Penalty Game!', 'When your opponent has 4 cards in their hand, select and activate 1 of these effects: ● Your opponent cannot draw during their next Draw Phase. ● Your opponent cannot activate any Spell or Trap Cards this turn.', 'Your opponent cannot draw during their next Draw Phase', 'Your opponent cannot activate any Spell or Trap Cards this turn', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36361633,3,0,0,4,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (36361633, 'Threatening Roar', 'Your opponent cannot declare an attack this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63356631,3,0,0,4,0,0,0,0,0,40);
INSERT OR REPLACE INTO "texts" VALUES (63356631, 'Phoenix Wing Wind Blast', 'Discard 1 card to target 1 card your opponent controls; return that target to the top of the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9744376,3,0,172,4,0,0,0,0,0,288);
INSERT OR REPLACE INTO "texts" VALUES (9744376, 'Good Goblin Housekeeping', 'Draw cards equal to the number of "Good Goblin Housekeeping" cards in your Graveyard +1, then select 1 card from your hand and return it to the bottom of your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35149085,3,0,0,4,0,0,0,0,0,262160);
INSERT OR REPLACE INTO "texts" VALUES (35149085, 'Beast Soul Swap', 'Return to the owner''s hand 1 face-up Beast-Type monster on your side of the field, then the owner of that card Special Summons 1 Beast-Type monster from their hand with the same Level as the monster you returned.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62633180,3,0,0,4,0,0,0,0,0,130);
INSERT OR REPLACE INTO "texts" VALUES (62633180, 'Assault on GHQ', 'Select 1 monster on your side of the field to activate this card. Destroy the selected card and send 2 cards from the top of your opponent''s Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8628798,3,0,0,4,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (8628798, 'D.D. Dynamite', 'Inflict 300 damage to your opponent for each of their removed from play cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35027493,3,0,0,4,0,0,0,0,0,2097218);
INSERT OR REPLACE INTO "texts" VALUES (35027493, 'Deck Devastation Virus', 'Tribute 1 DARK monster with 2000 or more ATK; check your opponent''s hand, all monsters they control, and all cards they draw until the end of their 3rd turn after this card''s activation, and destroy all those monsters with 1500 or less ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61411502,3,0,0,4,0,0,0,0,0,3);
INSERT OR REPLACE INTO "texts" VALUES (61411502, 'Elemental Burst', 'Tribute 1 each of WIND, WATER, FIRE, and EARTH monsters to activate this card. Destroy all cards on your opponent''s side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97806240,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (97806240, 'Forced Ceasefire', 'Discard 1 card from your hand. No Trap Cards can be activated until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21844576,3,0,12296,17,1000,1000,3,1,8,0);
INSERT OR REPLACE INTO "texts" VALUES (21844576, 'Elemental HERO Avian', 'A winged Elemental HERO who wheels through the sky and manipulates the wind. His signature move, Featherbreak, gives villainy a blow from sky-high.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58932615,3,0,12296,17,1200,800,3,1,4,0);
INSERT OR REPLACE INTO "texts" VALUES (58932615, 'Elemental HERO Burstinatrix', 'A flame manipulator who was the first Elemental HERO woman. Her Burstfire burns away villainy.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84327329,3,0,12296,17,800,2000,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (84327329, 'Elemental HERO Clayman', 'An Elemental HERO with a clay body built-to-last. He''ll preserve his Elemental HERO colleagues at any cost.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20721928,3,0,12296,17,1600,1400,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (20721928, 'Elemental HERO Sparkman', 'An Elemental HERO and a warrior of light who proficiently wields many kinds of armaments. His Static Shockwave cuts off the path of villainy.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57116033,3,0,164,33,300,200,1,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (57116033, 'Winged Kuriboh', 'If this card on the field is destroyed and sent to the Graveyard: Any further Battle Damage you take this turn becomes 0.', 'Reduce damage to 0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83104731,3,0,7,33,3000,3000,8,32,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (83104731, 'Ancient Gear Golem', 'Cannot be Special Summoned. If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. If this card attacks, your opponent cannot activate any Spell/Trap Cards until the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10509340,3,0,7,33,2000,2000,6,32,1,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (10509340, 'Ancient Gear Beast', 'This card cannot be Special Summoned. The effects of your opponent''s monsters that this card destroys by battle are negated. If this card attacks, your opponent cannot activate any Spell or Trap Cards until the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56094445,3,0,7,33,1300,1300,4,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (56094445, 'Ancient Gear Soldier', 'If this card attacks, your opponent cannot activate any Spell or Trap Cards until the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82482194,3,0,0,33,2000,1800,5,2048,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (82482194, 'Millennium Scorpion', 'Each time this card destroys 1 monster on your opponent''s side of the field by battle and sends it to the Graveyard, this card gains 500 ATK.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19877898,3,0,65,33,2600,1200,7,2048,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (19877898, 'Ultimate Insect LV7', 'If this card was Special Summoned by the effect of "Ultimate Insect LV5", while it remains on the field all your opponent''s monsters lose 700 ATK and DEF.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45871897,3,0,82,33,100,-2,4,256,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (45871897, 'Lost Guardian', 'The original DEF of this card becomes the number of your Rock-Type monsters that are removed from play × 700.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82260502,3,0,92,33,2400,1200,6,256,1,65536);
INSERT OR REPLACE INTO "texts" VALUES (82260502, 'Hieracosphinx', 'Your opponent cannot select a face-down Defense Position monster as an attack target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18654201,3,0,92,33,1200,2400,6,256,1,8);
INSERT OR REPLACE INTO "texts" VALUES (18654201, 'Criosphinx', 'When a monster is returned from the field to the owner''s hand, the owner of the returned monster selects and sends 1 card in their hand to the Graveyard.', 'Send to Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45159319,3,0,0,33,1100,2000,4,256,1,2048);
INSERT OR REPLACE INTO "texts" VALUES (45159319, 'Moai Interceptor Cannons', 'Once per turn, you can flip this card into face-down Defense Position.', 'Flip into face-down Defense Position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71544954,3,0,0,33,-2,-2,7,256,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (71544954, 'Megarock Dragon', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by removing from play a Rock-Type monster(s) in your Graveyard. The original ATK and DEF of this card become the number of Rock-Type monsters you removed from play when you Special Summoned this card x 700.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13532663,3,0,0,2097185,800,800,2,256,1,4096);
INSERT OR REPLACE INTO "texts" VALUES (13532663, 'Dummy Golem', 'FLIP: Your opponent selects 1 monster that they control. Switch control of the selected monster and this card.', 'コントロールを入れ替える', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40937767,3,0,0,33,1600,1500,4,256,1,4194304);
INSERT OR REPLACE INTO "texts" VALUES (40937767, 'Grave Ohja', 'While there is a face-down Defense Position monster(s) on your side of the field, no player can select this card as an attack target. Each time a monster on your side of the field is Flip Summoned, inflict 300 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76321376,3,0,0,33,1000,1900,3,256,1,4194304);
INSERT OR REPLACE INTO "texts" VALUES (76321376, 'Mine Golem', 'When this card is destroyed by battle and sent to the Graveyard, inflict 500 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3810071,3,0,0,33,1300,1000,3,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (3810071, 'Monk Fighter', 'Battle Damage to this card''s controller from a battle involving this card becomes 0.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49814180,3,0,0,33,1900,1000,5,256,1,294912);
INSERT OR REPLACE INTO "texts" VALUES (49814180, 'Master Monk', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by Tributing 1 "Monk Fighter". This card can attack twice during the same turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75209824,3,0,82,33,800,1400,4,256,1,2064);
INSERT OR REPLACE INTO "texts" VALUES (75209824, 'Guardian Statue', 'Once per turn, you can flip this card into face-down Defense Position. When this card is Flip Summoned, return 1 monster on your opponent''s side of the field to its owner''s hand.', 'Flip into face-down Defense Position', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2694423,3,0,62,33,500,600,2,256,1,2050);
INSERT OR REPLACE INTO "texts" VALUES (2694423, 'Medusa Worm', 'Once per turn, you can flip this card into face-down Defense Position. When this card is Flip Summoned, destroy 1 monster on your opponent''s side of the field.', 'Flip into face-down Defense Position', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48092532,3,0,0,33,1800,200,4,1,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (48092532, 'D.D. Survivor', 'During the End Phase, if this card was banished while face-up, on your side of the field, this turn: Special Summon this banished card. This effect can only activate once per turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75487237,3,0,0,33,100,1800,4,1,1,-2147481600);
INSERT OR REPLACE INTO "texts" VALUES (75487237, 'Mid Shield Gardna', 'Once per turn, you can flip this card into face-down Defense Position. Negate the activation of a Spell Card that targets this 1 face-down monster. At that time, flip this card into face-up Defense Position.', 'Flip into face-down Defense Position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1571945,3,0,43,2097185,1500,800,4,1,16,2);
INSERT OR REPLACE INTO "texts" VALUES (1571945, 'White Ninja', 'FLIP: Destroy 1 Defense Position monster.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37970940,3,0,191,2097185,500,1500,3,2,1,2101248);
INSERT OR REPLACE INTO "texts" VALUES (37970940, 'Aussa the Earth Charmer', 'FLIP: While this card is face-up on the field, take control of 1 EARTH monster your opponent controls.', 'Take control of 1 opponent EARTH monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74364659,3,0,191,2097185,500,1500,3,2,2,2101248);
INSERT OR REPLACE INTO "texts" VALUES (74364659, 'Eria the Water Charmer', 'FLIP: Take control of 1 WATER monster on your opponent''s side of the field for as long as this card remains face-up on the field.', 'Take control of 1 opponent WATER monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (759393,3,0,191,2097185,500,1500,3,2,4,4096);
INSERT OR REPLACE INTO "texts" VALUES (759393, 'Hiita the Fire Charmer', 'FLIP: Take control of 1 FIRE monster on your opponent''s side of the field for as long as this card remains face-up on the field.', 'Take control of 1 FIRE monster on your opponent''s side of the field', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37744402,3,0,191,2097185,500,1500,3,2,8,2101248);
INSERT OR REPLACE INTO "texts" VALUES (37744402, 'Wynn the Wind Charmer', 'FLIP: While this card is face-up on the field, take control of 1 WIND monster your opponent controls.', 'Take control of 1 opponent WIND monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63142001,3,0,40,33,0,0,3,4096,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (63142001, 'Batteryman AA', 'If all "Batteryman AA"(s) you control are in Attack Position, this card gains 1000 ATK for each. If all "Batteryman AA"(s) you control are in Defense Position, this card gains 1000 DEF for each.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9637706,3,0,0,33,1600,300,3,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (9637706, 'Des Wombat', 'Any damage to you from a card effect becomes 0.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36021814,3,0,0,33,-2,0,1,16,32,270340);
INSERT OR REPLACE INTO "texts" VALUES (36021814, 'King of the Skull Servants', 'The original ATK of this card is the combined number of "King of the Skull Servants" and "Skull Servant" in your Graveyard x 1000. When this card is destroyed by battle and sent to the Graveyard: You can banish 1 other "King of the Skull Servants" or "Skull Servant" from your Graveyard; Special Summon this card.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62420419,3,0,0,161,2500,1500,8,8,16,4096);
INSERT OR REPLACE INTO "texts" VALUES (62420419, 'Reshef the Dark Being', 'This card can only be Ritual Summoned with the Ritual Spell Card, "Final Ritual of the Ancients". Once per turn, by discarding 1 Spell Card from your hand, take control of 1 monster on your opponent''s side of the field until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99414168,3,0,0,161,1200,1400,3,2,16,2097152);
INSERT OR REPLACE INTO "texts" VALUES (99414168, 'Elemental Mistress Doriado', 'This card can only be Ritual Summoned with the Ritual Spell Card, "Doriado''s Blessing". The Attribute of this card is also treated as WIND, WATER, FIRE, and EARTH while it is face-up on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35809262,3,0,12296,97,2100,1200,6,1,8,4194304);
INSERT OR REPLACE INTO "texts" VALUES (35809262, 'Elemental HERO Flame Wingman', '"Elemental HERO Avian" + "Elemental HERO Burstinatrix"
Must be Fusion Summoned and cannot be Special Summoned by other ways. When this card destroys a monster by battle and sends it to the Graveyard: Inflict damage to your opponent equal to the ATK of the destroyed monster.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61204971,3,0,12296,97,2400,1500,6,1,16,2);
INSERT OR REPLACE INTO "texts" VALUES (61204971, 'Elemental HERO Thunder Giant', '"Elemental HERO Sparkman" + "Elemental HERO Clayman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. Once per turn: You can discard 1 card to target 1 face-up monster on the field with original ATK less than the ATK of this card; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42664989,3,0,0,2,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (42664989, 'Card of Sanctity', 'Banish all other cards you control and in your hand (min.1 from each); draw until you have 2 cards in your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87910978,3,0,0,2,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (87910978, 'Brain Control', 'Pay 800 Life Points. Select 1 face-up monster your opponent controls. Take control of it until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98792570,3,0,0,2,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (98792570, 'Gift of the Martyr', 'Send 1 monster on your side of the field to the Graveyard. Select 1 monster on your side of the field. The selected monster gains ATK equal to the ATK of the sent monster until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34187685,3,0,0,2,0,0,0,0,0,32768);
INSERT OR REPLACE INTO "texts" VALUES (34187685, 'Double Attack', 'Discard 1 Monster Card from your hand to the Graveyard. Select 1 monster on your side of the field with a lower Level than the discarded monster. The selected monster can attack twice this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61181383,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (61181383, 'Battery Charger', 'Pay 500 Life Points. Special Summon 1 "Batteryman" monster from your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97570038,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (97570038, 'Kaminote Blow', 'Activate only if there is at least 1 face-up "Chu-Ske the Mouse Fighter", "Monk Fighter", or "Master Monk" on your side of the field. Destroy the monster(s) that battle with these monsters on your side of the field this turn, at the end of each Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23965037,3,0,0,130,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (23965037, 'Doriado''s Blessing', 'This card is used to Ritual Summon "Elemental Mistress Doriado". You must also Tribute monsters whose total Levels equal 3 or more from the field or your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60369732,3,0,0,130,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (60369732, 'Final Ritual of the Ancients', 'This card is used to Ritual Summon "Reshef the Dark Being". You must also Tribute monsters whose total Levels equal 8 or more from the field or your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96458440,3,0,0,262146,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (96458440, 'Legendary Black Belt', 'Equip only to "Chu-Ske the Mouse Fighter", "Monk Fighter", or "Master Monk". When the equipped monster destroys your opponent''s monster by battle and sends it to the Graveyard, inflict damage to your opponent equal to the DEF of the destroyed monster.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23842445,3,0,0,262146,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (23842445, 'Nitro Unit', 'Equip only to a monster on your opponent''s side of the field. When the equipped monster is destroyed by battle and sent to the Graveyard, inflict damage to your opponent equal to the ATK of the equipped monster.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59237154,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (59237154, 'Shifting Shadows', 'Once per turn, by paying 300 Life Points, rearrange the face-down Defense Position monsters on your side of the field, then return them in face-down Defense Position.', 'シャッフルして、再び裏側守備表示で並べ替える', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96631852,3,0,0,131074,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (96631852, 'Impenetrable Formation', 'Select 1 monster on your side of the field to activate this card. While you have 2 or more monsters on your side of the field, and all monsters on your side of the field are in Defense Position, the selected monster gains 700 DEF. When the selected monster is removed from the field, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22020907,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (22020907, 'Hero Signal', 'When a monster you control is destroyed by battle and sent to the Graveyard: Special Summon 1 Level 4 or lower "Elemental HERO" monster from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58015506,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (58015506, 'Pikeru''s Second Sight', 'Until your opponent''s second End Phase, your opponent shows you all the cards that they draw before adding them to their hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85519211,3,0,0,4,0,0,0,0,0,4194306);
INSERT OR REPLACE INTO "texts" VALUES (85519211, 'Minefield Eruption', 'Inflict 1000 damage to your opponent for each face-up "Mine Golem" on your side of the field. After that, destroy all face-up "Mine Golem"(s) on your side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21908319,3,0,0,4,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (21908319, 'Kozaky''s Self-Destruct Button', 'Inflict 1000 damage to the player who destroyed this Set card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58392024,3,0,70,4,0,0,0,0,0,32);
INSERT OR REPLACE INTO "texts" VALUES (58392024, 'Mispolymerization', 'Activate only when a Fusion Monster is Special Summoned. Return all face-up Fusion Monsters to their respective Fusion Decks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84397023,3,0,0,4,0,0,0,0,0,134217728);
INSERT OR REPLACE INTO "texts" VALUES (84397023, 'Level Conversion Lab', 'Select 1 monster in your hand and show it to your opponent, then roll a six-sided die. If the result is 1, send the selected monster to the Graveyard. If the result is 2-6, the Level of the selected monster becomes equal to the result until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20781762,3,0,0,4,0,0,0,0,0,4194312);
INSERT OR REPLACE INTO "texts" VALUES (20781762, 'Rock Bombardment', 'Select 1 Rock-Type monster in your Deck and send it to the Graveyard. Inflict 500 damage to your opponent. Then shuffle the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57270476,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (57270476, 'Grave Lure', 'Turn the top card of your opponent''s Deck face-up, then your opponent shuffles their Deck. When your opponent draws the face-up card, immediately send it to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83675475,3,0,0,4,0,0,0,0,0,4718594);
INSERT OR REPLACE INTO "texts" VALUES (83675475, 'Token Feastevil', 'Activate only when a Token(s) is Special Summoned. Destroy all Tokens on the field, and inflict 300 damage to your opponent for each destroyed Token.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10069180,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (10069180, 'Spell-Stopping Statute', 'Activate only when your opponent activates a Continuous Spell Card. Negate the activation and the effect of the card and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56058888,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (56058888, 'Royal Surrender', 'Activate only when your opponent activates a Continuous Trap Card. Negate the activation and the effect of the card and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82452993,3,0,0,131076,0,0,0,0,0,33554432);
INSERT OR REPLACE INTO "texts" VALUES (82452993, 'Lone Wolf', 'Activate only if the 1 and only monster on your side of the field is "Chu-Ske the Mouse Fighter", "Monk Fighter", or "Master Monk". That monster cannot be destroyed as a result of battle, and is unaffected by any of your opponent''s monster effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
