BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (7459013,3,0,6,17,1800,1500,4,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (7459013, 'Zure, Knight of Dark World', 'The name of this illustrious knight is known by all residents of Dark World. He never oppresses the commoners.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51638941,3,0,0,17,1600,1800,4,32,16,0);
INSERT OR REPLACE INTO "texts" VALUES (51638941, 'V-Tiger Jet', 'This ace fighter is unbeatable in a dogfight. It combines with other monsters to launch an array of encircling attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97023549,3,0,0,17,1400,1500,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (97023549, 'Blade Skater', 'An image of beauty on the ice, this gorgeous warrior rips her opponents into pieces with her stylish Accel Slicer attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25652259,3,0,0,17,1500,1600,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (25652259, 'Queen''s Knight', 'This knight catches her opponents off guard, dominating them with swift yet graceful attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25652259,3,0,0,17,1500,1600,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (25652259, 'Queen''s Knight', 'This knight catches her opponents off guard, dominating them with swift yet graceful attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90876561,3,0,0,17,1900,1000,5,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (90876561, 'Jack''s Knight', 'A strong master swordsman. His loyalty is to justice, his duty to protect the weak.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90876561,3,0,0,17,1900,1000,5,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (90876561, 'Jack''s Knight', 'A strong master swordsman. His loyalty is to justice, his duty to protect the weak.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64788463,3,0,0,33,1600,1400,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (64788463, 'King''s Knight', 'When this card is Normal Summoned while you control "Queen''s Knight": You can Special Summon 1 "Jack''s Knight" from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64788463,3,0,0,33,1600,1400,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (64788463, 'King''s Knight', 'When this card is Normal Summoned while you control "Queen''s Knight": You can Special Summon 1 "Jack''s Knight" from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59793705,3,0,12296,33,2600,1800,7,1,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (59793705, 'Elemental HERO Bladedge', 'If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59793705,3,0,12296,33,2600,1800,7,1,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (59793705, 'Elemental HERO Bladedge', 'If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86188410,3,0,12296,33,1500,1600,4,1,1,33554432);
INSERT OR REPLACE INTO "texts" VALUES (86188410, 'Elemental HERO Wildheart', 'This card is unaffected by the effects of Trap Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23421244,3,0,0,33,1000,1600,4,16,32,16777216);
INSERT OR REPLACE INTO "texts" VALUES (23421244, 'Reborn Zombie', 'While you have no cards in your hand and this card is in Attack Position, it cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50916353,3,0,0,33,1200,1400,4,1,32,4194304);
INSERT OR REPLACE INTO "texts" VALUES (50916353, 'Chthonian Soldier', 'When this card is destroyed by an opponent''s attacking monster and sent to the Graveyard, the Battle Damage you took from this battle is also inflicted to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50916353,3,0,0,33,1200,1400,4,1,32,4194304);
INSERT OR REPLACE INTO "texts" VALUES (50916353, 'Chthonian Soldier', 'When this card is destroyed by an opponent''s attacking monster and sent to the Graveyard, the Battle Damage you took from this battle is also inflicted to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96300057,3,0,0,1057,1300,1500,4,32,16,270336);
INSERT OR REPLACE INTO "texts" VALUES (96300057, 'W-Wing Catapult', 'Once per turn, during your Main Phase, if you control this card on the field, you can equip it to your "V-Tiger Jet" as an Equip Card, OR unequip the Union equipment and Special Summon this card in face-up Attack Position. While equipped to a monster by this card''s effect, increase the ATK and DEF of the equipped monster by 400 points. (1 monster can only be equipped with 1 Union Monster at a time. If the equipped monster is destroyed as a result of battle, destroy this card instead.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23309606,3,0,109,33,2800,1800,6,8,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (23309606, 'Infernal Incinerator', 'This card can only be Normal Summoned or Set by discarding all cards in your hand to the Graveyard except this card, and by Tributing 1 monster with 2000 or more ATK you control. This card gains 200 ATK for each monster your opponent controls. This card loses 500 ATK for each other monster you control.', '通常召喚できない', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22587018,3,0,0,33,1600,1000,4,65536,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (22587018, 'Hydrogeddon', 'When this card destroys a monster your opponent controls by battle and sends it to the Graveyard: You can Special Summon 1 "Hydrogeddon" from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58071123,3,0,0,33,1800,800,4,65536,8,4194304);
INSERT OR REPLACE INTO "texts" VALUES (58071123, 'Oxygeddon', 'When this card is destroyed by battle with a Pyro-Type monster and sent to the Graveyard, inflict 800 damage to both players.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85066822,3,0,0,33,2800,2600,8,262144,2,270336);
INSERT OR REPLACE INTO "texts" VALUES (85066822, 'Water Dragon', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by the effect of "Bonding - H2O". While this card is face-up on the field, the ATK of FIRE monsters and Pyro-Type monsters become 0. When this card is destroyed and sent to the Graveyard, you can Special Summon 2 "Hydrogeddons" and 1 "Oxygeddon" from your Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85066822,3,0,0,33,2800,2600,8,262144,2,270336);
INSERT OR REPLACE INTO "texts" VALUES (85066822, 'Water Dragon', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by the effect of "Bonding - H2O". While this card is face-up on the field, the ATK of FIRE monsters and Pyro-Type monsters become 0. When this card is destroyed and sent to the Graveyard, you can Special Summon 2 "Hydrogeddons" and 1 "Oxygeddon" from your Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11460577,3,0,147,33,1200,1600,4,1,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (11460577, 'Etoile Cyber', 'If this card attacks your opponent directly, it gains 500 ATK during the Damage Step only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44954628,3,0,21,33,1800,2300,6,32,8,83886083);
INSERT OR REPLACE INTO "texts" VALUES (44954628, 'B.E.S. Tetran', 'When this card is Normal Summoned, put 3 counters on it. This card cannot be destroyed by battle. If this card attacks or is attacked, remove 1 counter from this card at the end of the Damage Step. If you cannot, destroy it. Once per turn, you can remove 1 counter on this card to destroy 1 Spell or Trap Card on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44954628,3,0,21,33,1800,2300,6,32,8,83886083);
INSERT OR REPLACE INTO "texts" VALUES (44954628, 'B.E.S. Tetran', 'When this card is Normal Summoned, put 3 counters on it. This card cannot be destroyed by battle. If this card attacks or is attacked, remove 1 counter from this card at the end of the Damage Step. If you cannot, destroy it. Once per turn, you can remove 1 counter on this card to destroy 1 Spell or Trap Card on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70948327,3,0,0,33,1600,1800,4,32,1,2);
INSERT OR REPLACE INTO "texts" VALUES (70948327, 'Nanobreaker', 'If this card attacks a face-up Level 3 or lower monster, destroy the monster with this card''s effect without applying damage calculation.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6337436,3,0,0,33,1600,1200,4,2,32,4194304);
INSERT OR REPLACE INTO "texts" VALUES (6337436, 'Rapid-Fire Magician', 'Inflict 400 damage to your opponent each time you activate a Normal Spell Card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6337436,3,0,0,33,1600,1200,4,2,32,4194304);
INSERT OR REPLACE INTO "texts" VALUES (6337436, 'Rapid-Fire Magician', 'Inflict 400 damage to your opponent each time you activate a Normal Spell Card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33731070,3,0,6,33,1600,1300,4,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (33731070, 'Beiige, Vanguard of Dark World', 'If this card is discarded to the Graveyard by a card effect: Special Summon it from the Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79126789,3,0,6,33,1400,800,3,8,32,256);
INSERT OR REPLACE INTO "texts" VALUES (79126789, 'Broww, Huntsman of Dark World', 'If this card is discarded to the Graveyard by a card effect: Draw 1 card, plus another card if this card is discarded from your hand to your Graveyard by an opponent''s card effect.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79126789,3,0,6,33,1400,800,3,8,32,256);
INSERT OR REPLACE INTO "texts" VALUES (79126789, 'Broww, Huntsman of Dark World', 'If this card is discarded to the Graveyard by a card effect: Draw 1 card, plus another card if this card is discarded from your hand to your Graveyard by an opponent''s card effect.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6214884,3,0,6,33,1800,400,4,8,32,64);
INSERT OR REPLACE INTO "texts" VALUES (6214884, 'Brron, Mad King of Dark World', 'When this card inflicts Battle Damage to your opponent: You can discard 1 card.', 'Select card to discard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6214884,3,0,6,33,1800,400,4,8,32,64);
INSERT OR REPLACE INTO "texts" VALUES (6214884, 'Brron, Mad King of Dark World', 'When this card inflicts Battle Damage to your opponent: You can discard 1 card.', 'Select card to discard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32619583,3,0,6,33,2300,1400,5,8,32,262240);
INSERT OR REPLACE INTO "texts" VALUES (32619583, 'Sillva, Warlord of Dark World', 'If this card is discarded to the Graveyard by a card effect: Special Summon it from the Graveyard, then, if this card was discarded from your hand to your Graveyard by your opponent''s card effect, your opponent returns exactly 2 cards from their hand to the bottom of their Deck, in any order.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32619583,3,0,6,33,2300,1400,5,8,32,262240);
INSERT OR REPLACE INTO "texts" VALUES (32619583, 'Sillva, Warlord of Dark World', 'If this card is discarded to the Graveyard by a card effect: Special Summon it from the Graveyard, then, if this card was discarded from your hand to your Graveyard by your opponent''s card effect, your opponent returns exactly 2 cards from their hand to the bottom of their Deck, in any order.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78004197,3,0,6,33,2300,1400,5,8,32,262147);
INSERT OR REPLACE INTO "texts" VALUES (78004197, 'Goldd, Wu-Lord of Dark World', 'If this card is discarded to the Graveyard by a card effect: If it was discarded from your hand to your Graveyard by an opponent''s card effect, you can target up to 2 cards your opponent controls; Special Summon this card from the Graveyard, then destroy those cards (if any).', 'Special Summon', 'Destroy card(s) on your opponent''s field?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78004197,3,0,6,33,2300,1400,5,8,32,262147);
INSERT OR REPLACE INTO "texts" VALUES (78004197, 'Goldd, Wu-Lord of Dark World', 'If this card is discarded to the Graveyard by a card effect: If it was discarded from your hand to your Graveyard by an opponent''s card effect, you can target up to 2 cards your opponent controls; Special Summon this card from the Graveyard, then destroy those cards (if any).', 'Special Summon', 'Destroy card(s) on your opponent''s field?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5498296,3,0,6,33,500,500,2,8,32,512);
INSERT OR REPLACE INTO "texts" VALUES (5498296, 'Scarr, Scout of Dark World', 'When this card is destroyed by battle and sent to the Graveyard: Add 1 Level 4 or lower "Dark World" monster from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31887905,3,0,192,33,1850,1500,4,2,1,2375680);
INSERT OR REPLACE INTO "texts" VALUES (31887905, 'Familiar-Possessed - Aussa', 'You can send 1 "Aussa the Earth Charmer" and 1 EARTH monster you control to the Graveyard to Special Summon this card from your hand or Deck. If you do, this card gets the following effect: ● During battle between this attacking card and a Defense Position monster whose DEF is lower than the ATK of this card, inflict the difference as Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68881649,3,0,192,33,1850,1500,4,2,2,2375688);
INSERT OR REPLACE INTO "texts" VALUES (68881649, 'Familiar-Possessed - Eria', 'You can send 1 Eria the Water Charmer and 1 WATER monster you control to the Graveyard to Special Summon this card from your hand or Deck. If you do, this card gets the following effect: ● During battle between this attacking card and a Defense Position monster whose DEF is lower than the ATK of this card, inflict the difference as Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4376658,3,0,192,33,1850,1500,4,2,4,2375680);
INSERT OR REPLACE INTO "texts" VALUES (4376658, 'Familiar-Possessed - Hiita', 'By sending 1 "Hiita the Fire Charmer" and 1 FIRE monster from your side of the field to the Graveyard, you can Special Summon this card from your hand or Deck. If you Special Summon this card in this way, this card gets the following effect: During battle between this attacking card and a Defense Position monster whose DEF is lower than the ATK of this card, inflict the difference as Battle Damage to your opponent''s Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31764353,3,0,192,33,1850,1500,4,2,8,278528);
INSERT OR REPLACE INTO "texts" VALUES (31764353, 'Familiar-Possessed - Wynn', 'By sending 1 "Wynn the Wind Charmer" and 1 WIND monster from your side of the field to the Graveyard, you can Special Summon this card from your hand or Deck. If you Special Summon this card in this way, this card gets the following effect: During battle between this attacking card and a Defense Position monster whose DEF is lower than the ATK of this card, inflict the difference as Battle Damage to your opponent''s Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58859575,3,0,0,97,2000,2100,6,32,16,264192);
INSERT OR REPLACE INTO "texts" VALUES (58859575, 'VW-Tiger Catapult', '"V-Tiger Jet" + "W-Wing Catapult"
This card can only be Special Summoned from your Extra Deck by banishing the above cards on your side of the field. (You do not use "Polymerization"). By discarding 1 card from your hand, change the battle position of 1 monster on your opponent''s side of the field. (Flip Effects are not activated at this time.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84243274,3,0,0,97,3000,2800,8,32,16,264196);
INSERT OR REPLACE INTO "texts" VALUES (84243274, 'VWXYZ-Dragon Catapult Cannon', '"VW-Tiger Catapult" + "XYZ-Dragon Cannon"
This card can only be Special Summoned from your Extra Deck by removing from play the above cards you control (You do not use "Polymerization"). Once per turn, remove from play 1 card your opponent controls. When this card attacks, you can change the battle position of the attack target. (Flip Effects are not activated at this time.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84243274,3,0,0,97,3000,2800,8,32,16,264196);
INSERT OR REPLACE INTO "texts" VALUES (84243274, 'VWXYZ-Dragon Catapult Cannon', '"VW-Tiger Catapult" + "XYZ-Dragon Cannon"
This card can only be Special Summoned from your Extra Deck by removing from play the above cards you control (You do not use "Polymerization"). Once per turn, remove from play 1 card your opponent controls. When this card attacks, you can change the battle position of the attack target. (Flip Effects are not activated at this time.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10248389,3,0,147,97,2100,800,7,1,1,-2130698240);
INSERT OR REPLACE INTO "texts" VALUES (10248389, 'Cyber Blader', '"Etoile Cyber" + "Blade Skater"
A Fusion Summon of this card can only be conducted with the above Fusion Material Monsters. While your opponent controls only 1 monster, this card is not destroyed as a result of battle. While your opponent controls only 2 monsters, double the ATK of this card. While your opponent controls only 3 monsters, this card negates the effects of your opponent''s Spell, Trap and Effect Monster Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10248389,3,0,147,97,2100,800,7,1,1,-2130698240);
INSERT OR REPLACE INTO "texts" VALUES (10248389, 'Cyber Blader', '"Etoile Cyber" + "Blade Skater"
A Fusion Summon of this card can only be conducted with the above Fusion Material Monsters. While your opponent controls only 1 monster, this card is not destroyed as a result of battle. While your opponent controls only 2 monsters, double the ATK of this card. While your opponent controls only 3 monsters, this card negates the effects of your opponent''s Spell, Trap and Effect Monster Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47737087,3,0,12296,97,2000,2500,6,1,1,139264);
INSERT OR REPLACE INTO "texts" VALUES (47737087, 'Elemental HERO Rampart Blaster', '"Elemental HERO Clayman" + "Elemental HERO Burstinatrix"
Must be Fusion Summoned and cannot be Special Summoned by other ways. This card can attack while in face-up Defense Position, but only if your opponent controls no monsters, and if it does, this card''s ATK is halved during damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47737087,3,0,12296,97,2000,2500,6,1,1,139264);
INSERT OR REPLACE INTO "texts" VALUES (47737087, 'Elemental HERO Rampart Blaster', '"Elemental HERO Clayman" + "Elemental HERO Burstinatrix"
Must be Fusion Summoned and cannot be Special Summoned by other ways. This card can attack while in face-up Defense Position, but only if your opponent controls no monsters, and if it does, this card''s ATK is halved during damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83121692,3,0,12296,97,2800,2800,8,1,8,16777216);
INSERT OR REPLACE INTO "texts" VALUES (83121692, 'Elemental HERO Tempest', '"Elemental HERO Avian" + "Elemental HERO Sparkman" + "Elemental HERO Bubbleman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. You can send 1 other card you control to the Graveyard to target 1 monster you control; while this card is face-up on the field, that monster cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83121692,3,0,12296,97,2800,2800,8,1,8,16777216);
INSERT OR REPLACE INTO "texts" VALUES (83121692, 'Elemental HERO Tempest', '"Elemental HERO Avian" + "Elemental HERO Sparkman" + "Elemental HERO Bubbleman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. You can send 1 other card you control to the Graveyard to target 1 monster you control; while this card is face-up on the field, that monster cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10526791,3,0,12296,97,2600,2300,8,1,1,32768);
INSERT OR REPLACE INTO "texts" VALUES (10526791, 'Elemental HERO Wildedge', '"Elemental HERO Wildheart" + "Elemental HERO Bladedge"
Must be Fusion Summoned and cannot be Special Summoned by other ways. This card can attack every monster your opponent controls (one attack on each monster per Battle Phase).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10526791,3,0,12296,97,2600,2300,8,1,1,32768);
INSERT OR REPLACE INTO "texts" VALUES (10526791, 'Elemental HERO Wildedge', '"Elemental HERO Wildheart" + "Elemental HERO Bladedge"
Must be Fusion Summoned and cannot be Special Summoned by other ways. This card can attack every monster your opponent controls (one attack on each monster per Battle Phase).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25366484,3,0,12296,97,2500,2100,8,1,16,4202496);
INSERT OR REPLACE INTO "texts" VALUES (25366484, 'Elemental HERO Shining Flare Wingman', '"Elemental HERO Flame Wingman" + "Elemental HERO Sparkman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. This card gains 300 ATK for each "Elemental HERO" card in your Graveyard. When this card destroys a monster by battle and sends it to the Graveyard: Inflict damage to your opponent equal to the ATK of the destroyed monster in the Graveyard.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25366484,3,0,12296,97,2500,2100,8,1,16,4202496);
INSERT OR REPLACE INTO "texts" VALUES (25366484, 'Elemental HERO Shining Flare Wingman', '"Elemental HERO Flame Wingman" + "Elemental HERO Sparkman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. This card gains 300 ATK for each "Elemental HERO" card in your Graveyard. When this card destroys a monster by battle and sends it to the Graveyard: Inflict damage to your opponent equal to the ATK of the destroyed monster in the Graveyard.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67169062,3,0,0,2,0,0,0,0,0,1312);
INSERT OR REPLACE INTO "texts" VALUES (67169062, 'Pot of Avarice', 'Target 5 monsters in your Graveyard; shuffle all 5 into the Deck, then draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67169062,3,0,0,2,0,0,0,0,0,1312);
INSERT OR REPLACE INTO "texts" VALUES (67169062, 'Pot of Avarice', 'Target 5 monsters in your Graveyard; shuffle all 5 into the Deck, then draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93554166,3,0,6,2,0,0,0,0,0,11);
INSERT OR REPLACE INTO "texts" VALUES (93554166, 'Dark World Lightning', 'Target 1 Set card on the field; destroy that target, then discard 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61850482,3,0,0,2,0,0,0,0,0,262400);
INSERT OR REPLACE INTO "texts" VALUES (61850482, 'Level Modulation', 'Your opponent draws 2 cards. Special Summon 1 monster from your Graveyard that includes "LV" in its card name, ignoring the Summoning conditions. The monster that was Special Summoned by this effect cannot attack, nor activate or apply its effect this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24643836,3,0,15,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (24643836, 'Ojamagic', 'When this card is sent from the hand or the field to the Graveyard, add 1 each of "Ojama Green", "Ojama Yellow" and "Ojama Black" from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98259197,3,0,15,2,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (98259197, 'Ojamuscle', 'Select 1 face-up "Ojama King" on the field. Destroy all monster(s) on the field that include "Ojama" in their card name, except the selected "Ojama King". Increase the ATK of the selected "Ojama King" by 1000 points for each destroyed monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19394153,3,0,0,2,0,0,0,0,0,32768);
INSERT OR REPLACE INTO "texts" VALUES (19394153, 'Feather Shot', 'Target 1 face-up "Elemental HERO Avian" you control; during this turn, that target can attack a number of times equal to the number of monsters you control when this card resolves, but cannot attack directly, and other monsters you control cannot attack this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19394153,3,0,0,2,0,0,0,0,0,32768);
INSERT OR REPLACE INTO "texts" VALUES (19394153, 'Feather Shot', 'Target 1 face-up "Elemental HERO Avian" you control; during this turn, that target can attack a number of times equal to the number of monsters you control when this card resolves, but cannot attack directly, and other monsters you control cannot attack this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45898858,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (45898858, 'Bonding - H2O', 'Tribute 2 "Hydrogeddons" and 1 "Oxygeddon". Special Summon 1 "Water Dragon" from your hand, Deck or Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46910446,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (46910446, 'Chthonian Alliance', 'The equipped monster gains 800 ATK for each other face-up monster on the field that has the same name it does.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46910446,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (46910446, 'Chthonian Alliance', 'The equipped monster gains 800 ATK for each other face-up monster on the field that has the same name it does.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90374791,3,0,165,262146,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (90374791, 'Armed Changer', 'Send 1 Equip Spell Card from your hand to the Graveyard to activate this card. If the equipped monster destroys a monster by battle, the controller of this Equip Card can add 1 monster with ATK equal to or less than the equipped monster from their Graveyard to their hand.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90374791,3,0,165,262146,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (90374791, 'Armed Changer', 'Send 1 Equip Spell Card from your hand to the Graveyard to activate this card. If the equipped monster destroys a monster by battle, the controller of this Equip Card can add 1 monster with ATK equal to or less than the equipped monster from their Graveyard to their hand.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30548775,3,0,0,131074,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (30548775, 'Branch!', 'When a Fusion Monster on the field is destroyed and sent to the Graveyard, you can Special Summon from your Graveyard 1 of the Fusion Material Monsters that you used for the Fusion Summon of that Fusion Monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66947414,3,0,0,131074,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (66947414, 'Boss Rush', 'You cannot Normal Summon or Set. During the End Phase of the turn that a "B.E.S." monster or a "Big Core" is destroyed and sent to the Graveyard, you can Special Summon 1 "B.E.S." monster or 1 "Big Core" from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93431518,3,0,6,65538,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (93431518, 'Gateway to Dark World', 'Target 1 "Dark World" monster in your Graveyard; Special Summon that target. You cannot Summon other monsters the turn that you activate this card (but you can Set).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44676200,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (44676200, 'Hero Barrier', 'Negate 1 attack from an opponent''s monster. You must control a face-up "Elemental HERO" monster to resolve this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44676200,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (44676200, 'Hero Barrier', 'Negate 1 attack from an opponent''s monster. You must control a face-up "Elemental HERO" monster to resolve this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18271561,3,0,0,4,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (18271561, 'Chthonian Blast', 'When a face-up monster you control is destroyed and sent to the Graveyard: Destroy the 1 face-up monster on the field that has the lowest ATK (your choice, if tied), and if you do, inflict damage to both players equal to half of that monster''s ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18271561,3,0,0,4,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (18271561, 'Chthonian Blast', 'When a face-up monster you control is destroyed and sent to the Graveyard: Destroy the 1 face-up monster on the field that has the lowest ATK (your choice, if tied), and if you do, inflict damage to both players equal to half of that monster''s ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29826127,3,0,0,4,0,0,0,0,0,1024);
INSERT OR REPLACE INTO "texts" VALUES (29826127, 'The Forces of Darkness', 'Target 2 "Dark World" monsters in your Graveyard; add those targets to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65824822,3,0,0,4,0,0,0,0,0,72);
INSERT OR REPLACE INTO "texts" VALUES (65824822, 'Dark Deal', 'When your opponent activates a Normal Spell Card: Pay 1000 Life Points; the effect of that Normal Spell Card becomes "Your opponent discards 1 random card".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92219931,3,0,0,4,0,0,0,0,0,128);
INSERT OR REPLACE INTO "texts" VALUES (92219931, 'Simultaneous Loss', 'Each player sends the top card from their Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28604635,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (28604635, 'Weed Out', 'Pay 500 Life Points. Destroy all Level 3 monsters in face-up Attack Position on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55008284,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (55008284, 'The League of Uniform Nomenclature', 'Select 1 face-up Level 2 or lower Normal Monster on your side of the field to activate this card. Special Summon from your Deck to your side of the field as many cards as possible with the same name as the selected monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91597389,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (91597389, 'Roll Out!', 'Target 1 Union monster in your Graveyard; equip that target to an appropriate monster you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72287557,3,0,0,4,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (72287557, 'Chthonian Polymer', 'You can only activate this card when your opponent Fusion Summons a Fusion Monster. Tribute 1 monster on your side of the field to take control of that Fusion Monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71060915,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (71060915, 'Feather Wind', 'When a Spell/Trap Card is activated while you control a face-up "Elemental HERO Avian": Negate the activation and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27581098,3,0,70,131076,0,0,0,0,0,268435456);
INSERT OR REPLACE INTO "texts" VALUES (27581098, 'Non-Fusion Area', 'Neither player can Fusion Summon.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54976796,3,0,0,131076,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (54976796, 'Level Limit - Area A', 'All face-up Level 3 or lower monsters on the field are changed to Attack Position and remain in Attack Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
