BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (92125819,3,0,10948730,17,1800,1800,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (92125819, 'Noble Knight Artorigus', 'No one shall ever know the truth behind
 That fateful day. Artorigus went forth
 To where the brilliant sword didst lay.
 ''Twas the first of many feats so great,
 A legend through and through. We sing of him,
 Artorigus, the Noble and the brave.
  -From the Tales of the Noble Knights', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87151205,3,0,14,17,2500,1000,6,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (87151205, 'Wattaildragon', 'Capable of indefinite flight. Attacks by wrapping its body with electricity and ramming into opponents.
IMPORTANT: Capturing the "Wattaildragon" is forbidden by the Ancient Rules and is a Level 6 offense, the minimum sentence for which is imprisonment for no less than 2500 heliocycles.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13140300,3,0,105,17,0,0,8,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (13140300, 'Hieratic Seal of the Sun Dragon Overlord', 'A mysterious engraved Hieratic relic. It was thought to be a simple stone, but it was actually infused with the power of a sun-wielding dragon. Ages passed, and the power of the relic grew and grew until it finally shone like the sun itself.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59644958,3,0,0,33,800,1600,4,512,8,1073741824);
INSERT OR REPLACE INTO "texts" VALUES (59644958, 'Overlay Owl', 'Once per turn: You can pay 600 Life Points; detach 1 Xyz Material from a monster on the field.', '去除素材', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86039057,3,0,0,33,1700,100,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (86039057, 'Tasuke Knight', 'When an opponent''s monster declares an attack, while you have no cards in your hand and this card is in your Graveyard: You can Special Summon this card from your Graveyard, then end the Battle Phase. You can only use the effect of "Tasuke Knight" once per Duel.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12423762,3,0,84,33,1500,2000,4,1,1,17039360);
INSERT OR REPLACE INTO "texts" VALUES (12423762, 'Gagaga Gardna', 'When an opponent''s monster declares a direct attack: You can Special Summon this card from your hand. When this face-up card is targeted for an attack: You can discard 1 card; this card cannot be destroyed by that battle.', 'Special Summon', '不被战破', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45812361,3,0,0,33,800,400,2,32,1,256);
INSERT OR REPLACE INTO "texts" VALUES (45812361, 'Cardcar D', 'Cannot be Special Summoned. During your Main Phase 1, if this card was Normal Summoned this turn: You can Tribute this card; draw 2 cards, then it becomes the End Phase of this turn. You cannot Special Summon during the turn you activate this effect.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81816475,3,0,0,33,300,800,2,524288,16,1073741824);
INSERT OR REPLACE INTO "texts" VALUES (81816475, 'Overlay Eater', 'You can banish this card from your Graveyard; take 1 Xyz Material from a monster your opponent controls and attach it to an Xyz Monster you control as Xyz Material.', 'Material taken', 'Please select Xyz monster', 'Please select Xyz material to be transferred', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17201174,3,0,0,33,1700,1500,4,131072,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (17201174, 'Hammer Shark', 'Once per turn, during your Main Phase: You can decrease this card''s Level by 1, and Special Summon 1 Level 3 or lower WATER monster from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44790889,3,0,107,33,2300,2000,6,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (44790889, 'Hammer Bounzer', 'If your opponent controls a card and you control no cards, you can Normal Summon this card without Tributing. If this card attacks an opponent’s monster, as long as you control no Spell/Trap Cards, your opponent cannot activate any Spell/Trap Cards until the end of the Damage Step.', 'Normal Summon without Tributes', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70194827,3,0,107,33,1800,1400,4,1,1,32768);
INSERT OR REPLACE INTO "texts" VALUES (70194827, 'Blade Bounzer', 'Once per turn, if this card attacks and your opponent controls a monster at the end of the Damage Step: You can discard 1 card; this card can attack an opponent''s monster once again during this Battle Phase.', '再次攻击', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17189532,3,0,107,33,2400,1200,6,1,32,512);
INSERT OR REPLACE INTO "texts" VALUES (17189532, 'Phantom Bounzer', 'If this card on the field is destroyed and sent to the Graveyard: You can add 2 "Bounzer" cards from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43573231,3,0,106,33,1200,1600,4,1,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (43573231, 'Morpho Butterspy', 'Once per turn, when the battle position of an opponent''s monster(s) is changed (except during the Damage Step): You can target one of those monsters; it loses 1000 ATK and DEF.', '攻守下降', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79972330,3,0,106,33,1800,1200,4,1,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (79972330, 'Swallowtail Butterspy', 'When another monster you control inflicts Battle Damage to your opponent: Target 1 face-up monster your opponent controls; it loses ATK equal to the Battle Damage inflicted.', 'Lower attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16366944,3,0,0,33,1200,1600,4,2048,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (16366944, 'Moonlit Papillon', 'When this card is sent from the field to the Graveyard: You can Special Summon 1 Level 4 or lower "Butterspy" monster from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42851643,3,0,0,33,1800,100,4,32,1,18432);
INSERT OR REPLACE INTO "texts" VALUES (42851643, 'Jumbo Drill', 'When this card is Normal Summoned: You can increase the Levels of all Machine-Type monsters you currently control by 1. If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. If this card attacks, it is changed to Defense Position at the end of the Damage Step.', 'Increase level', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79850798,3,0,0,33,5000,0,10,32,1,262208);
INSERT OR REPLACE INTO "texts" VALUES (79850798, 'Rocket Arrow Express', 'Cannot be Normal Summoned or Set. Must be Special Summoned (from your hand) by controlling no cards, and cannot be Special Summoned by other ways. You cannot conduct your Battle Phase the turn you Special Summon this card. You cannot activate cards or effects, or Set any cards. During each of your Standby Phases, destroy this card unless you send all cards in your hand to the Graveyard (min. 1).', 'Select effect', 'Send all cards in your hand to the Graveyard?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5244497,3,0,0,33,1400,1600,4,1,16,2);
INSERT OR REPLACE INTO "texts" VALUES (5244497, 'Cameraclops', 'If this card attacks a face-up monster on the field, at the start of the Damage Step: Destroy that monster. Its DEF must be higher than this card''s ATK to activate and to resolve this effect.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41639001,3,0,105,33,1700,900,4,8192,16,1310720);
INSERT OR REPLACE INTO "texts" VALUES (41639001, 'Hieratic Dragon of Nuit', 'Once per turn, during either player´s turn, when this face-up card on the field is targeted by a Spell Card, Trap Card, or card effect: Special Summon 1 Dragon-Type Normal Monster from your hand, Deck, or Graveyard, and make its ATK and DEF 0.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78033100,3,0,105,33,1800,400,4,8192,16,1310720);
INSERT OR REPLACE INTO "texts" VALUES (78033100, 'Hieratic Dragon of Gebeb', 'When this card destroys an opponent''s monster by battle and sends it to the Graveyard: Special Summon 1 Dragon-Type Normal Monster from your hand, Deck, or Graveyard, and make its ATK and DEF 0. When this card is Tributed: Special Summon 1 "Hieratic" Normal Monster from your hand, Deck, or Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4022819,3,0,105,33,1900,1200,5,8192,16,270336);
INSERT OR REPLACE INTO "texts" VALUES (4022819, 'Hieratic Dragon of Eset', 'You can Normal Summon this card without Tributing, but its original ATK becomes 1000. Once per turn: You can target 1 face-up Dragon-Type Normal Monster on the field; the Levels of all face-up "Hieratic" monsters currently on the field become the Level of that monster, until the End Phase. When this card is Tributed: Special Summon 1 Dragon-Type Normal Monster from your hand, Deck, or Graveyard, and make its ATK and DEF 0.', 'Normal Summon this card without Tributing', 'Change level', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31516413,3,0,105,33,2000,1600,5,8192,16,270338);
INSERT OR REPLACE INTO "texts" VALUES (31516413, 'Hieratic Dragon of Nebthet', 'You can Special Summon this card (from your hand) by Tributing 1 "Hieratic" monster. Once per turn: You can Tribute 1 "Hieratic" monster, except this card, from your hand or your side of the field, to target 1 monster your opponent controls; destroy that target. When this card is Tributed: Special Summon 1 Dragon-Type Normal Monster from your hand, Deck, or Graveyard, and make its ATK and DEF 0.', 'Destroy', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77901552,3,0,105,33,2100,1400,6,8192,16,1376256);
INSERT OR REPLACE INTO "texts" VALUES (77901552, 'Hieratic Dragon of Tefnuit', 'If your opponent controls a monster and you control no monsters, you can Special Summon this card (from your hand). This card cannot attack during the turn it is Special Summoned this way. When this card is Tributed: Special Summon 1 Dragon-Type Normal Monster from your hand, Deck, or Graveyard, and make its ATK and DEF 0.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3300267,3,0,105,33,2200,1000,6,8192,16,1310721);
INSERT OR REPLACE INTO "texts" VALUES (3300267, 'Hieratic Dragon of Su', 'You can Special Summon this card (from your hand) by Tributing 1 "Hieratic" monster. Once per turn: You can Tribute 1 "Hieratic" monster, except this card, from your hand or your side of the field, to target 1 Spell/Trap Card your opponent controls; destroy that target. When this card is Tributed: Special Summon 1 Dragon-Type Normal Monster from your hand, Deck, or Graveyard, and make its ATK and DEF 0.', 'Destroy', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30794966,3,0,105,33,2600,700,7,8192,16,20185088);
INSERT OR REPLACE INTO "texts" VALUES (30794966, 'Hieratic Dragon of Asar', 'You can Special Summon this card (from your hand) by banishing 1 LIGHT Dragon-Type monster and 1 Dragon-Type Normal Monster from your Graveyard. If this face-up card on the field would be destroyed, you can Tribute 1 face-up "Hieratic" monster you control instead, except this card.', 'Activate "Hieroglyph Dragon - Usir Dragon" effect to avoid destruction?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66789970,3,0,105,33,2800,2000,8,8192,16,1310723);
INSERT OR REPLACE INTO "texts" VALUES (66789970, 'Hieratic Dragon of Sutekh', 'Cannot be Normal Summoned or Set. Must first be Special Summoned (from your hand) by banishing 3 Dragon-Type Normal Monsters in your Graveyard. Once per turn: You can banish 1 Dragon-Type monster from your Graveyard to target 1 card on the field; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3283679,3,0,12366,33,1200,500,3,524288,4,262152);
INSERT OR REPLACE INTO "texts" VALUES (3283679, 'Evoltile Lagosucho', 'When this card is Normal Summoned: You can send 1 "Evolsaur" monster from your Deck to the Graveyard. When this card is flipped face-up: You can Special Summon 1 "Evoltile" monster from your Deck.', 'Send to Graveyard', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39672388,3,0,24654,33,2200,700,5,65536,4,0);
INSERT OR REPLACE INTO "texts" VALUES (39672388, 'Evolsaur Darwino', 'When this card is Special Summoned by the effect of an "Evoltile" monster: You can target 1 face-up monster on the field; increase that target''s Level by up to 2.', 'Increase level', 'Increase Level by 1', 'Increase Level by 2', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66066482,3,0,86,33,100,100,1,2048,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (66066482, 'Inzektor Firefly', 'Once per turn: You can equip 1 "Inzektor" monster from your hand or Graveyard to this card. If an "Inzektor" card equips to this card: You can look at all Set cards your opponent controls. While this card is equipped to a monster, that monster''s Level is increased by 1, also it gains ATK and DEF equal to this card''s ATK and DEF.', 'Equip', 'Confirm set cards', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2461031,3,0,86,33,500,100,2,2048,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (2461031, 'Inzektor Ladybug', 'Once per turn: You can equip 1 "Inzektor" monster from your hand or Graveyard to this card. While this card is equipped to a monster, that monster''s Level is increased by 2, also it gains ATK and DEF equal to this card''s ATK and DEF. While this card is equipped to a monster: You can send this Equip Card to the Graveyard to target 1 face-up monster you control; increase that target''s Level by up to 2.', 'Equip', 'Increase level', 'Increase Level by 1', 'Increase Level by 2', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38450736,3,0,86,33,1000,1000,4,2048,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (38450736, 'Inzektor Earwig', 'Once per turn: You can equip 1 "Inzektor" monster from your hand or Graveyard to this card. While this card is equipped to a monster, that monster gains ATK and DEF equal to this card''s ATK and DEF. When this card is sent to the Graveyard while equipped to a monster: The monster this card was equipped to gains 1000 ATK, until the End Phase.', 'Equip', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65844845,3,0,86,33,2000,1300,5,2048,32,24576);
INSERT OR REPLACE INTO "texts" VALUES (65844845, 'Inzektor Giga-Cricket', 'If this card is in your Graveyard: You can banish 1 Insect-Type monster from your Graveyard to target 1 face-up "Inzektor" monster you control; equip this card from your Graveyard to that target. This effect of "Inzektor Giga-Cricket" can only be used once per turn. While this card is equipped to a monster, that monster''s original ATK becomes 2000, and if it attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', 'Equip', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91349449,3,0,108,33,2300,2000,6,2,16,2359332);
INSERT OR REPLACE INTO "texts" VALUES (91349449, 'Lightray Sorcerer', 'Cannot be Normal Summoned or Set. Must be Special Summoned (from your hand) while 3 or more of your LIGHT monsters are banished, and cannot be Special Summoned by other ways. Once per turn: You can target 1 of your banished LIGHT monsters and 1 face-up monster on the field; shuffle the first target into the Deck, and if you do, banish the second target. This card cannot attack during the turn you activate this effect.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38737148,3,0,108,33,2600,1500,7,262144,16,2359299);
INSERT OR REPLACE INTO "texts" VALUES (38737148, 'Lightray Daedalus', 'Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by having 4 or more LIGHT monsters in your Graveyard, and cannot be Special Summoned by other ways. Once per turn: You can target 1 Field Spell Card and 2 other cards on the field; destroy them.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4722253,3,0,108,33,2800,2200,8,1,16,-2146172927);
INSERT OR REPLACE INTO "texts" VALUES (4722253, 'Lightray Gearfried', 'Cannot be Normal Summoned or Set. Must be Special Summoned (from your hand) by having 5 or more LIGHT monsters with different names in your Graveyard, and cannot be Special Summoned by other ways. Once per turn, during either player´s turn, when a Spell/Trap Card is activated: You can banish 1 Warrior-Type monster from your Graveyard; negate the activation, and if you do, destroy it. All face-up monsters you control must be Warrior-Type to activate and to resolve this effect.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30126992,3,0,108,33,2800,1000,7,8192,16,-2145386464);
INSERT OR REPLACE INTO "texts" VALUES (30126992, 'Lightray Diabolos', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by having 5 or more LIGHT monsters with different names in your Graveyard. Once per turn: You can banish 1 LIGHT monster from your Graveyard, then target 1 Set card your opponent controls; reveal that target, then place that target on either the top or bottom of the Deck.', 'Return to deck', 'Return to the top of the Deck', 'Return to the bottom of the Deck', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67511500,3,0,0,33,1500,1100,4,2,32,34603008);
INSERT OR REPLACE INTO "texts" VALUES (67511500, 'Lady of D.', 'Your opponent cannot target face-up Dragon-Type monsters you control for attacks. If this card on the field would be destroyed by battle or by a card effect, you can send 1 Dragon-Type monster from your hand to the Graveyard instead.', 'Activate effect of "Dragon Witch, Protector of Dragons" to avoid destruction?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3900605,3,0,0,2097185,600,500,3,256,1,257);
INSERT OR REPLACE INTO "texts" VALUES (3900605, 'Absorbing Jar', 'FLIP: Destroy all Set Spell/Trap Cards on the field, then each player draws 1 card for each of the cards they controlled that was destroyed by this effect. You cannot Set any cards this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30494314,3,0,0,33,1700,1000,4,16,32,1074798592);
INSERT OR REPLACE INTO "texts" VALUES (30494314, 'Red-Headed Oni', 'When this card is Special Summoned from the Graveyard by the effect of a Zombie-Type monster: You can target 1 face-up Zombie-Type monster you control; detach 1 Xyz Material from a monster on the field, and if you do, increase the targeted monster''s Level by 1 and its ATK by 300 (even if the targeting conditions are no longer correct).', '等级攻击上升', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66499018,3,0,0,33,1800,0,4,16384,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (66499018, 'Flame Tiger', 'During your Draw Phase, if this card is in your Graveyard and you control no monsters, instead of conducting your normal draw: You can Special Summon this card from the Graveyard. If this card is Special Summoned with this effect, banish it when it leaves the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92887027,3,0,0,33,1700,1000,4,1,8,2);
INSERT OR REPLACE INTO "texts" VALUES (92887027, 'Nomadic Force', 'When this card destroys an opponent''s monster by battle and sends it to the Graveyard: You can Tribute this card to target 1 face-down Defense Position monster your opponent controls; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39272762,3,0,276496469,8388641,4500,3000,8,8192,16,-1073700864);
INSERT OR REPLACE INTO "texts" VALUES (39272762, 'Neo Galaxy-Eyes Photon Dragon', '3 Level 8 monsters
When this card is Xyz Summoned using "Galaxy-Eyes Photon Dragon" as any of its Materials: Negate the effects of all other face-up cards currently on the field. Once per turn: You can detach 1 Xyz Material from this card; detach all Xyz Materials from monsters your opponent controls, then this card gains 500 ATK for each, also it can attack up to that many times during each Battle Phase this turn.', 'Negate effect', '取除素材', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65676461,3,0,72,8388641,2800,2100,4,262144,2,303104);
INSERT OR REPLACE INTO "texts" VALUES (65676461, 'Number 32: Shark Drake', '3 Level 4 monsters
Once per turn, when this attacking card destroys an opponent''s monster by battle and sends it to the Graveyard: You can detach 1 Xyz Material from this card; Special Summon the destroyed monster to your opponent''s side of the field in face-up Attack Position, but it loses 1000 ATK, and if you do summon this way, this card can attack once again during this Battle Phase.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92661479,3,0,7012437,8388641,2700,2000,6,1,16,-2143289344);
INSERT OR REPLACE INTO "texts" VALUES (92661479, 'Photon Strike Bounzer', '2 Level 6 monsters
Once per turn, during either player''s turn, when a monster effect is activated on your opponent''s side of the field: You can detach 1 Xyz Material from this card; negate the effect, and if you do, inflict 1000 damage to your opponent.', 'Negate effect', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28150174,3,0,85,8388641,2100,1800,4,1,16,10240);
INSERT OR REPLACE INTO "texts" VALUES (28150174, 'Photon Papilloperative', '2 Level 4 monsters
Once per turn: You can detach 1 Xyz Material from this card to target 1 Defense Position monster on the field; change it to face-up Attack Position, and if you do, it loses 600 ATK.', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64554883,3,0,72,8388641,2800,2400,6,32,16,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (64554883, 'Number 25: Force Focus', '2 Level 6 monsters
Once per turn, during either player''s turn: You can detach 1 Xyz Material from this card to target 1 face-up Level 5 or higher Effect Monster your opponent controls; negate the effects of that opponent''s face-up monster, until the end of the turn.', 'Negate effect', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91949988,3,0,0,8388641,2600,2100,7,8192,8,16384);
INSERT OR REPLACE INTO "texts" VALUES (91949988, 'Gaia Dragon, the Thunder Charger', '2 Level 7 monsters
You can also Xyz Summon this card by using a Rank 5 or 6 Xyz Monster you control as the Xyz Material. (Xyz Materials attached to that monster also become Xyz Materials on this card.) If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', 'Place on top of a face-up Rank 5 or 6 monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27337596,3,0,105,8388641,2400,2100,6,8192,16,1310720);
INSERT OR REPLACE INTO "texts" VALUES (27337596, 'Hieratic Dragon King of Atum', '2 Level 6 Dragon-Type monsters
Once per turn: You can detach 1 Xyz Material from this card; Special Summon 1 Dragon-Type monster from your Deck, and make its ATK and DEF 0. This card cannot attack during the turn you activate this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64332231,3,0,105,8388641,3000,2400,8,8192,16,3);
INSERT OR REPLACE INTO "texts" VALUES (64332231, 'Hieratic Sun Dragon Overlord of Heliopolis', '2 Level 8 monsters
Once per turn: You can detach 1 Xyz Material from this card; Tribute any number of monsters from your hand and/or your side of the field (minimum 1), then destroy an equal number of cards on the field.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90726340,3,0,812449901,8388641,2200,1200,4,8192,32,18087936);
INSERT OR REPLACE INTO "texts" VALUES (90726340, 'Queen Dragun Djinn', '2 Level 4 monsters
Dragon-Type monsters you control cannot be destroyed by battle, except "Queen Dragun Djinn". Once per turn: You can detach 1 Xyz Material from this card to target 1 Level 5 or higher Dragon-Type monster in your Graveyard; Special Summon that target. It cannot attack this turn, and its effects are negated.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26211048,3,0,86,8388641,800,800,5,2048,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (26211048, 'Inzektor Exa-Stag', '2 Level 5 Insect-Type monsters
Once per turn: You can detach 1 Xyz Material from this card to target 1 monster your opponent controls or in their Graveyard; equip that target to this card. This card gains ATK and DEF equal to half the original ATK and DEF of the monster(s) equipped by this effect.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53610653,3,0,0,262146,0,0,0,0,0,1318912);
INSERT OR REPLACE INTO "texts" VALUES (53610653, 'Bound Wand', 'Equip only to a Spellcaster-Type monster that has a Level. It gains ATK equal to its Level × 100. If the equipped monster is destroyed by your opponent''s card (by battle or card effect) and sent to the Graveyard, and this card is sent to the Graveyard as a result: You can Special Summon that monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99004752,3,0,0,2,0,0,0,0,0,4202496);
INSERT OR REPLACE INTO "texts" VALUES (99004752, 'Mini-Guts', 'Tribute 1 monster to target 1 face-up monster your opponent controls; its ATK becomes 0 until the End Phase. This turn, when it is destroyed by battle and sent to their Graveyard: Inflict damage to your opponent equal to its original ATK in the Graveyard.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26099457,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (26099457, 'Falling Current', 'Target 1 face-up monster you control and declare a Level from 1 to 3; it becomes that Level.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52497105,3,0,0,65538,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (52497105, 'Berserk Scales', 'Target 1 face-up monster you control (except a monster that is attacking directly); it gains 1000 ATK, also it cannot attack your opponent directly for the rest of this turn. During the End Phase of this turn, it loses 2000 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89882100,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (89882100, 'Night Beam', 'Target 1 Set Spell/Trap Card your opponent controls; destroy that target. Your opponent cannot activate the targeted card in response to this card''s activation.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25377819,3,0,105,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (25377819, 'Hieratic Seal of Convocation', 'Add 1 "Hieratic" monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51365514,3,0,105,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (51365514, 'Hieratic Seal of Supremacy', 'Special Summon 1 "Hieratic" monster from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88760522,3,0,0,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (88760522, 'Evo-Diversity', 'Add 1 "Evoltile" or "Evolsaur" monster from your Deck to your hand. You can only activate 1 "Evo-Diversity" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14154221,3,0,0,131074,0,0,0,0,0,3);
INSERT OR REPLACE INTO "texts" VALUES (14154221, 'Evo-Price', 'Once per turn, if a monster is Special Summoned by an "Evoltile" monster (except during the damage step): You can target 1 card on the field; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51549976,3,0,0,2,0,0,0,0,0,3);
INSERT OR REPLACE INTO "texts" VALUES (51549976, 'Final Inzektion', 'Send 5 face-up "Inzektor" cards you control to the Graveyard; destroy all cards your opponent controls, also, during the Battle Phase of this turn, your opponent cannot activate monster effects that activate in the hand or Graveyard.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87047074,3,0,86,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (87047074, 'Inzektor Crossbow - Zektarrow', 'Equip only to an "Inzektor" monster. It gains 500 ATK. Your opponent cannot activate cards or effects in response to the equipped monster''s effects.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13032689,3,0,115,262146,0,0,0,0,0,1073750016);
INSERT OR REPLACE INTO "texts" VALUES (13032689, 'Xyz Unit', 'Equip only to an Xyz Monster. It gains ATK equal to its Rank × 200. If the equipped monster you control would detach its Xyz Material to activate its effect: You can detach this card as 1 of the Xyz Materials.', 'Activate effect of "Xyz Unit"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50427388,3,0,0,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (50427388, 'That Wacky Magic!', 'Banish all Spell Cards in your Graveyard; destroy all face-up monsters your opponent controls with DEF less than or equal to the number of Spell Cards you banished × 300.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86825483,3,0,83,131074,0,0,0,0,0,2097152);
INSERT OR REPLACE INTO "texts" VALUES (86825483, 'Constellar Belt', 'The activation of LIGHT monsters'' effects cannot be negated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13210191,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (13210191, 'Storm', 'Destroy all Spell and Trap Cards you control, then destroy as many Spell/Trap Cards your opponent controls as possible, up to the number of your own cards you destroyed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49204190,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (49204190, 'Nitwit Outwit', 'Discard 1 monster, then target 1 face-up monster on the field; it loses ATK equal to the discarded monster''s original ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85709845,3,0,0,4,0,0,0,0,0,4196352);
INSERT OR REPLACE INTO "texts" VALUES (85709845, 'Gamushara', 'When a Defense Position monster you control is targeted for an attack: Change that Defense Position monster to face-up Attack Position. Then, if the attacking monster is destroyed by that battle and sent to the Graveyard: Inflict damage to your opponent equal to that monster''s original ATK in the Graveyard.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12197543,3,0,0,4,0,0,0,0,0,65);
INSERT OR REPLACE INTO "texts" VALUES (12197543, 'Commander of Swords', 'When your opponent draws for their normal draw in their Draw Phase: They reveal the card(s) they drew, then if any is a Spell/Trap Card, you apply 1 of these effects.
● Discard all cards they drew.
● Destroy 1 Spell/Trap Card they control.', 'Discard the revealed card.', 'Target 1 Spell or Trap Card your opponent controls; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48582558,3,0,107,4,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (48582558, 'Bounzer Guard', 'Target 1 face-up "Bounzer" monster you control; this turn, it cannot be targeted by other card effects, or be destroyed by battle. This turn, if an opponent''s monster attacks, it must target that monster for an attack if it is still on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75987257,3,0,0,4,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (75987257, 'Butterflyoke', 'When an opponent''s monster declares an attack: Target the attacking monster; change that target to Defense Position, and if you do, equip this card to that monster. Once per turn, during either player''s Main Phase or Battle Phase: You can change the equipped monster''s Battle Position.', '变更表示形式', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11975962,3,0,105,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (11975962, 'Hieratic Seal of Banishment', 'Tribute 1 "Hieratic" monster to target 1 card your opponent controls; banish that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47360060,3,0,105,1048580,0,0,0,0,0,-2147483645);
INSERT OR REPLACE INTO "texts" VALUES (47360060, 'Hieratic Seal of Reflection', 'When a Spell Card, Trap Card, or monster effect is activated: Tribute 1 "Hieratic" monster; negate the activation, and if you do, destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74854609,3,0,0,4,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (74854609, 'Zekt Conversion', 'When a face-up "Inzektor" monster you control is targeted for an attack: Target the attacking monster; equip the attack target to that attacking monster. Take control of the equipped monster while it is equipped with an "Inzektor" monster by this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (259314,3,0,86,4,0,0,0,0,0,16785408);
INSERT OR REPLACE INTO "texts" VALUES (259314, 'Inzektor Gauntlet', 'Target 1 face-up "Inzektor" monster you control; equip this card to that target. It gains 1000 DEF, and cannot be destroyed by your opponent''s card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47247413,3,0,0,4,0,0,0,0,0,32);
INSERT OR REPLACE INTO "texts" VALUES (47247413, 'Return', 'When your opponent adds a card(s) from the Graveyard to their hand: They must shuffle 1 of those cards into their Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73632127,3,0,0,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (73632127, 'Dimension Slice', 'When a monster(s) is Special Summoned to your side of the field: Target 1 face-up monster your opponent controls; banish that target. If the Summon is an Xyz Summon, you can activate this card the turn it was Set.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5037726,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (5037726, 'Spiritual Light Art - Hijiri', 'Tribute 1 LIGHT monster to target 1 banished monster; your opponent can reveal 1 Trap Card from their hand to negate this card''s effect, otherwise you Special Summon that monster.', 'Reveal 1 Trap Card to negate "Spiritual Light Art - Hijiri"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42425831,3,0,0,131076,0,0,0,0,0,2359300);
INSERT OR REPLACE INTO "texts" VALUES (42425831, 'Sealing Ceremony of Raiton', 'Once per turn: You can return 1 face-up WIND monster you control to the bottom of the Main Deck to target up to 2 cards in your opponent''s Graveyard; banish those targets.', 'Banish', 'Activate effect of "Sealing Ceremony of Raiton"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78910579,3,0,0,4,0,0,0,0,0,2098192);
INSERT OR REPLACE INTO "texts" VALUES (78910579, 'Aquamirror Cycle', 'Target 1 face-up WATER monster you control and 2 WATER monsters in your Graveyard; shuffle the first target into the Deck, and if you do, add the second targets to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5914184,3,0,0,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (5914184, 'Double Payback', 'Activate only when you take 1000 or more damage from your opponent''s card effect: Place 1 Payback Counter on this card for every 1000 damage you took. During the End Phase of your opponent''s next turn: Destroy this card, and if you do, inflict 2000 damage to your opponent for each Payback Counter on this card.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38520918,3,0,0,33,1400,1300,4,8192,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (38520918, 'Ancient Dragon', 'When this card inflicts Battle Damage to your opponent by a direct attack: You can increase this card''s Level by 1 and ATK by 500.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64514622,3,0,105,2081,0,0,6,8192,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (64514622, 'Hieratic Seal of the Dragon King', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect.
● You can Tribute this card; Special Summon 1 "Hieratic" monster, except "Hieratic Seal of the Dragon King", from your hand, Deck, or Graveyard, in face-up Defense Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91903221,3,0,12366,33,0,0,2,524288,4,768);
INSERT OR REPLACE INTO "texts" VALUES (91903221, 'Evoltile Elginero', 'When this card on the field is Tributed and sent to the Graveyard: Draw 1 card, then, you can shuffle 1 Dinosaur-Type monster from your hand into the Deck, then add 1 "Evoltile" monster from your Deck to your hand.', 'Draw card', 'Add 1 "Evoltile" monster from your Deck to your hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27407330,3,0,108,33,1700,1600,4,1,16,2359300);
INSERT OR REPLACE INTO "texts" VALUES (27407330, 'Lightray Grepher', 'You can Special Summon this card (from your hand) by discarding 1 Level 5 or higher LIGHT monster. Once per turn: You can discard 1 LIGHT monster; banish 1 LIGHT monster from your Deck.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64892035,3,0,0,33,2200,0,4,8,32,65536);
INSERT OR REPLACE INTO "texts" VALUES (64892035, 'Tardy Orc ', 'This card cannot attack the turn it is Normal Summoned.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90887783,3,0,0,2,0,0,0,0,0,1049120);
INSERT OR REPLACE INTO "texts" VALUES (90887783, 'Draconnection', 'Reveal 1 Dragon-Type monster in your hand, add 1 Dragon-Type monster with the same Level from your Deck to your hand, then shuffle the revealed monster into the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26285788,3,0,0,2,0,0,0,0,0,1283);
INSERT OR REPLACE INTO "texts" VALUES (26285788, 'Trial and Tribulation', 'You can only activate 1 "Trial and Tribulation" per turn. During the End Phase of the turn this card was activated, apply this effect, depending on the number of the monsters you Tributed from the field and from your hand this turn, except Tokens.
● 1: Draw 1 card.
● 2: Add 2 monsters from your Graveyard to your hand.
● 3+: Destroy up to 3 face-up cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53670497,3,0,105,131076,0,0,0,0,0,262152);
INSERT OR REPLACE INTO "texts" VALUES (53670497, 'Hieratic Seal From the Ashes ', 'Once per turn, during your opponent''s turn: You can send 1 "Hieratic" monster from your Deck to your Graveyard. Once per turn, during your turn: You can target 1 of your banished "Hieratic" monsters; return that target to the Graveyard. When this face-up card on the field is sent to the Graveyard: Target 1 "Hieratic" monster in your Graveyard: Special Summon that target.', 'Activate effect of "Hieratic Seal From the Ashes "?', 'Send to graveyard', '特殊召唤', '特殊召唤', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99064191,3,0,115,131076,0,0,0,0,0,-2147483646);
INSERT OR REPLACE INTO "texts" VALUES (99064191, 'Xyz Wrath', 'Once per turn, when a Level 5 or higher monster''s effect is activated (except during the Damage Step), and you control an Xyz Monster: You can discard 1 card; negate that effect, and if you do, destroy that monster.', 'Negate and destroy', 'Activate effect of "Xyz Wrath"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80117527,3,0,72,8388641,2600,2000,7,2,32,4096);
INSERT OR REPLACE INTO "texts" VALUES (80117527, 'Number 11: Big Eye', '2 Level 7 monsters
Once per turn: You can detach 1 Xyz Material from this card, then target 1 monster your opponent controls; take control of that monster. This card cannot attack the turn you activate this effect.', '得到控制权', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82308875,3,0,72,8388641,700,700,7,4,16,134488328);
INSERT OR REPLACE INTO "texts" VALUES (82308875, 'Number 7: Lucky Straight', '3 Level 7 monsters
You can detach 1 Xyz Material from this card; roll a six-sided die twice and this card''s ATK becomes the larger number rolled × 700 until your opponent''s next End Phase, then if the total roll was exactly 7, apply 1 of these effects.
● Send all other cards on the field to the Graveyard.
● Special Summon 1 monster from your hand or from either Graveyard.
● Draw 3 cards, then discard 2 cards.', 'Roll dice', 'Send all other cards on the field to the Graveyard', 'Special Summon 1 monster from your hand or either player''s Graveyard', 'Draw 3 cards, then discard 2 cards', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30587695,3,0,0,33,1600,900,4,2048,32,1310720);
INSERT OR REPLACE INTO "texts" VALUES (30587695, 'Beetron', 'You can send 1 face-up Spell/Trap Card you control to the Graveyard to target 1 Level 4 or lower Insect-Type monster in your Graveyard; Special Summon that target in face-up Defense Position. The effect of "Beetron" can only be used once per turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54936498,3,0,0,4129,300,900,3,8192,8,1048576);
INSERT OR REPLACE INTO "texts" VALUES (54936498, 'Influence Dragon', 'Once per turn: You can target 1 face-up monster you control; it becomes Dragon-Type until the End Phase.', '种族变化', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16719802,3,0,0,33,1900,1000,4,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (16719802, 'Bright Star Dragon', 'When this card is Normal Summoned: You can target 1 face-up monster on the field, except this card; increase that target''s Level by 2 until the End Phase.', 'Increase level', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83991690,3,0,0,4129,200,300,1,4,16,540016640);
INSERT OR REPLACE INTO "texts" VALUES (83991690, 'Buten', 'During your Main Phase: You can banish this card from the Graveyard to target 1 face-up Level 4 or lower LIGHT Fairy-Type monster you control; it is treated as a Tuner monster while face-up on the field.', '当成调整使用', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10389794,3,0,0,2097185,0,0,1,8,32,2);
INSERT OR REPLACE INTO "texts" VALUES (10389794, 'Doom Donuts', 'FLIP: Destroy all face-up monsters on the field with an original ATK or DEF of 0.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46384403,3,0,120,33,800,100,2,131072,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (46384403, 'Nimble Manta', 'When this card is sent from the field to the Graveyard by a card effect: You can Special Summon any number of "Nimble Manta" from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97170107,3,0,0,8388641,1600,1000,2,2,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (97170107, 'Shining Elf', '2 Level 2 monsters
When your opponent Normal or Special Summons a monster(s) (except during the Damage Step): You can detach 1 Xyz Material from this card; that monster(s) loses 500 ATK.', 'Lower attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61807040,3,0,0,33,800,1300,2,2,8,0);
INSERT OR REPLACE INTO "texts" VALUES (61807040, 'Flelf', 'Once per turn: You can reveal 1 monster in your hand; increase the Level of this card by the Level of that monster, until the End Phase.', 'Increase level', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
