BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (26082117,3,0,84,33,1500,1000,4,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (26082117, 'Gagaga Magician', 'Once per turn: You can declare a Level from 1 to 8; this card becomes that Level until the End Phase. You can only control 1 "Gagaga Magician". This card cannot be used as a Synchro Material Monster.', 'Change level', 'Please select a Level from 1 to 8', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62476815,3,0,89,33,1800,1500,4,256,1,17039360);
INSERT OR REPLACE INTO "texts" VALUES (62476815, 'Gogogo Golem', 'Once per turn, this Defense Position card cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98865920,3,0,0,33,1200,600,3,1,4,4194304);
INSERT OR REPLACE INTO "texts" VALUES (98865920, 'Achacha Archer', 'When this card is Normal or Flip Summoned: Inflict 500 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25259669,3,0,172,33,1400,0,4,1,1,264192);
INSERT OR REPLACE INTO "texts" VALUES (25259669, 'Goblindbergh', 'When this card is Normal Summoned: You can Special Summon 1 Level 4 or lower monster from your hand, then change this card to Defense Position if you activated this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51254277,3,0,0,33,1800,300,3,131072,2,4);
INSERT OR REPLACE INTO "texts" VALUES (51254277, 'Big Jaws', 'At the end of the Battle Phase, if this card attacked: Banish it.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98649372,3,0,0,33,600,1600,3,64,32,2049);
INSERT OR REPLACE INTO "texts" VALUES (98649372, 'Skull Kraken', 'When this card is Normal Summoned: You can target 1 face-up Spell Card your opponent controls; destroy that target. Once per turn: You can change the Battle Position of this card.', 'Destroy Spell', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24137081,3,0,0,33,300,0,3,64,2,139264);
INSERT OR REPLACE INTO "texts" VALUES (24137081, 'Drill Barnacle', 'This card can attack your opponent directly. Each time this card inflicts Battle Damage to your opponent by a direct attack: This card gains 1000 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50532786,3,0,0,33,2600,1600,6,32768,2,8192);
INSERT OR REPLACE INTO "texts" VALUES (50532786, 'Jawsman', 'Cannot be Special Summoned. If you Tribute Summon this card, all Tributes must be WATER. This card gains 300 ATK for each face-up WATER monster you control, except this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87526784,3,0,0,33,0,2000,3,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (87526784, 'Crashbug X', 'When this card is Normal Summoned: You can Special Summon 1 "Crashbug Z" from your Deck. You must control a face-up "Crashbug Y" to activate and to resolve this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23915499,3,0,0,33,1400,1600,3,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (23915499, 'Crashbug Y', 'When this card is Normal Summoned: You can Special Summon 1 "Crashbug X" from your Deck. You must control a face-up "Crashbug Z" to activate and to resolve this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50319138,3,0,0,33,0,1500,3,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (50319138, 'Crashbug Z', 'When this card is Normal Summoned: You can Special Summon 1 "Crashbug Y" from your Deck. You must control a face-up "Crashbug X" to activate and to resolve this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86804246,3,0,0,33,0,3000,4,8,32,270336);
INSERT OR REPLACE INTO "texts" VALUES (86804246, 'Super Crashbug', 'Cannot be Normal Summoned or Set. Must first be Special Summoned (from your hand) in face-up Defense Position, by banishing "Crashbug X", "Crashbug Y", and "Crashbug Z" from your Graveyard. Switch the ATK and DEF of all face-up Attack Position monsters on the field. There can only be 1 face-up "Super Crashbug" on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12299841,3,0,88,33,1800,1200,4,1,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (12299841, 'Wind-Up Soldier', 'During your Main Phase: You can increase this card''s Level by 1 and ATK by 400, until the End Phase. This effect can only be used once while this card is face-up on the field.', 'Increase Level and ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59297550,3,0,88,33,600,1800,4,2,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (59297550, 'Wind-Up Magician', 'If the effect of a "Wind-Up" monster is activated, except "Wind-Up Magician": You can Special Summon 1 Level 4 or lower "Wind-Up" monster from your Deck in face-up Defense Position. This effect can only be used once while this card is face-up on the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85682655,3,0,88,33,1700,1000,4,1048576,8,2);
INSERT OR REPLACE INTO "texts" VALUES (85682655, 'Wind-Up Juggler', 'After damage calculation, if this card battled an opponent''s monster: You can destroy the opponent''s monster. This effect can only be used once while this card is face-up on the field.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12076263,3,0,88,33,1200,900,3,16384,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (12076263, 'Wind-Up Dog', 'During your Main Phase: You can increase this card''s Level by 2 and ATK by 600, until the End Phase. This effect can be used only once while this card is face-up on the field.', 'Increase Level and ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58475908,3,0,88,33,100,2000,2,64,2,16);
INSERT OR REPLACE INTO "texts" VALUES (58475908, 'Wind-Up Snail', 'During your Main Phase: You can target 1 Set card on the field; return that target to the hand. This effect can be used only once while this card is face-up on the field.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84569017,3,0,0,33,1700,1100,4,262144,8,270336);
INSERT OR REPLACE INTO "texts" VALUES (84569017, 'Spearfish Soldier', 'This card gains 100 ATK for each of your banished Fish, Sea Serpent, and Aqua-Type monsters.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11954712,3,0,0,33,1600,300,3,131072,8,16388);
INSERT OR REPLACE INTO "texts" VALUES (11954712, 'Flyfang', 'If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent. At the end of the Battle Phase, if this card inflicted Battle Damage to your opponent: Banish this card until your next Standby Phase.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47349310,3,0,0,33,600,300,3,262144,8,131076);
INSERT OR REPLACE INTO "texts" VALUES (47349310, 'Skystarray', 'This card can attack your opponent directly. At the end of the Battle Phase, if this card attacked directly: Banish this card until your next Standby Phase.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84747429,3,0,0,33,1400,300,3,262144,8,7);
INSERT OR REPLACE INTO "texts" VALUES (84747429, 'Airorca', 'Once per turn: You can banish 1 Fish, Sea Serpent, or Aqua-Type monster from your hand, then target 1 face-up card your opponent controls; destroy that target, then banish this card until your next Standby Phase.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10132124,3,0,0,33,1500,1400,3,64,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (10132124, 'Wingtortoise', 'When a face-up Fish, Sea Serpent, or Aqua-Type monster(s) you control is banished: You can Special Summon this card from your hand or Graveyard. (The banished monster(s) must be Fish, Sea Serpent, or Aqua-Type even after being banished.)', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47126872,3,0,0,33,2300,1500,5,1048576,8,262148);
INSERT OR REPLACE INTO "texts" VALUES (47126872, 'Space-Time Police', 'When this card is Special Summoned: Target 1 face-up card your opponent controls; banish that target. When this card leaves the field: Set the card that was banished by this effect to your opponent''s side of the field.', 'Banish', '盖放', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73625877,3,0,0,33,500,100,2,1048576,1,1048580);
INSERT OR REPLACE INTO "texts" VALUES (73625877, 'Time Escaper', 'During either player''s turn: You can discard this card, then target 1 Psychic-Type monster you control; banish it until your next Standby Phase.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19019586,3,0,71,33,400,1900,3,256,1,8208);
INSERT OR REPLACE INTO "texts" VALUES (19019586, 'Gem-Elephant', 'During your Main Phase: You can return this face-up card on the field to the hand. During damage calculation, if this card attacked or was attacked: You can send 1 Normal Monster from your hand to the Graveyard; this card gains 1000 DEF.', 'Return to hand', '守备上升1000', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46404281,3,0,57,33,1700,200,4,128,4,5242888);
INSERT OR REPLACE INTO "texts" VALUES (46404281, 'Laval Magma Cannoneer', 'Up to twice per turn: You can send 1 FIRE monster from your hand to the Graveyard; inflict 500 damage to your opponent.', '给与对方500伤害', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72403299,3,0,58,33,1200,800,3,262144,2,544);
INSERT OR REPLACE INTO "texts" VALUES (72403299, 'Gishki Diviner', 'Once per turn: You can declare 1 card name; reveal the top card of your Deck, and if it is the declared card, add it to your hand. Otherwise, return it to the top of the Deck.', '宣言卡名', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9897998,3,0,16,33,1000,400,3,512,8,3408384);
INSERT OR REPLACE INTO "texts" VALUES (9897998, 'Gusto Codor', 'When this card destroys an opponent''s monster by battle and sends it to the Graveyard: You can Special Summon 1 WIND Psychic-Type monster with 1500 or less DEF from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45282603,3,0,0,33,600,400,2,2,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (45282603, 'Saambell the Summoner', 'During your Main Phase: You can Special Summon 1 monster from your hand with the same Level as this card. This effect can only be used once while this card is face-up on the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8175346,3,0,0,33,200,100,3,8192,4,512);
INSERT OR REPLACE INTO "texts" VALUES (8175346, 'Poki Draco', 'When this card is Normal Summoned: You can add 1 "Poki Draco" from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34160055,3,0,0,33,1800,1200,4,1,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (34160055, 'Master of the Flaming Dragonswords', 'When a monster is Normal Summoned to your side of the field, except "Master of the Flaming Dragonswords": You can increase that monster''s Level by 1, and this card gains 300 ATK until the End Phase.', '等级攻击上升', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71564150,3,0,109,33,2700,500,7,8,32,4096);
INSERT OR REPLACE INTO "texts" VALUES (71564150, 'Perditious Puppeteer', 'Once per turn: You can discard 1 card; gain control of all face-up Level 3 or lower monsters your opponent controls, until the End Phase. These monsters cannot activate their effects, and cannot be Tributed or used as a Synchro Material Monster.', 'Take control', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7953868,3,0,0,33,1000,1700,4,16,32,1313792);
INSERT OR REPLACE INTO "texts" VALUES (7953868, 'Blue-Blooded Oni', 'When this card is Normal or Flip Summoned: It is changed to Defense Position. Once per turn: You can detach 1 Xyz Material you control to target 1 Level 4 Zombie-Type monster in your Graveyard; Special Summon that target.', 'Change to defense position', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33347467,3,0,0,33,1900,1000,5,8,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (33347467, 'Ghost Ship', 'Cannot be Normal Summoned or Set. Must first be Special Summoned (from your hand) by banishing 1 LIGHT monster from your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70832512,3,0,0,33,1800,1200,4,1,1,2);
INSERT OR REPLACE INTO "texts" VALUES (70832512, 'Absolute Crusader', 'When a Level 5 or higher monster is Special Summoned: Tribute this face-up card on the field; destroy that Level 5 or higher monster.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6836211,3,0,90,33,1800,1500,5,64,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (6836211, 'The Great Emperor Penguin', 'You can Tribute this card; Special Summon up to 2 "Penguin" monsters from your Deck, except "The Great Emperor Penguin".', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33225925,3,0,0,33,1800,1000,4,2,16,0);
INSERT OR REPLACE INTO "texts" VALUES (33225925, 'Milla the Temporal Magician', 'When this card is Normal Summoned: Target 1 Set card your opponent controls; look at it. Your opponent cannot activate Spell/Trap Cards in response to this effect''s activation.', 'Confirm 1 Set card', 'Please select 1 Set card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67775894,3,0,0,262146,0,0,0,0,0,1057032);
INSERT OR REPLACE INTO "texts" VALUES (67775894, 'Wonder Wand', 'Equip only to a Spellcaster-Type monster. It gains 500 ATK. If you control the equipped monster and this card: You can send both to the Graveyard; draw 2 cards.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94770493,3,0,0,65538,0,0,0,0,0,40960);
INSERT OR REPLACE INTO "texts" VALUES (94770493, 'Double or Nothing!', 'When a monster''s attack is negated: Target that monster; during this Battle Phase, it can attack again, and if it does, its ATK is doubled during the Damage Step only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20264508,3,0,0,2,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (20264508, 'Thunder Short', 'Inflict 400 damage to your opponent for each monster they control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7653207,3,0,0,2,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (7653207, 'Aqua Jet', 'Target 1 face-up Fish, Sea Serpent, or Aqua-Type monster you control; it gains 1000 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33057951,3,0,0,2,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (33057951, 'Surface', 'Target 1 Level 3 or lower Fish, Sea Serpent, or Aqua-Type monster in your Graveyard; Special Summon it in face-up Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69042950,3,0,0,65538,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (69042950, 'Crashbug Road', 'Each player can Special Summon 1 monster from their hand with the same Level as 1 face-up Level 4 or lower monster they control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6430659,3,0,0,131074,0,0,0,0,0,131136);
INSERT OR REPLACE INTO "texts" VALUES (6430659, 'Infected Mail', 'Once per turn: You can target 1 Level 4 or lower monster you control; it can attack your opponent directly this turn. Send it to the Graveyard at the end of the Battle Phase.', 'Direct attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32835363,3,0,0,131074,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (32835363, 'Cracking', 'Once per turn, when a monster(s) is sent from the field to the Graveyard by a card effect: Inflict 800 damage to the owner of the monster(s).', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69320362,3,0,88,65538,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (69320362, 'Legendary Wind-Up Key', 'Change all face-up "Wind-Up" monsters you control to face-down Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95714077,3,0,88,131074,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (95714077, 'Wind-Up Factory', 'Once per turn, if an effect of a "Wind-Up" monster is activated: You can add 1 Level 4 or lower "Wind-Up" monster from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32703716,3,0,0,2,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (32703716, 'Fish and Kicks', 'If you have 3 or more banished Fish, Sea Serpent, or Aqua-Type monsters: Target 1 card on the field; banish it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64107820,3,0,0,131074,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (64107820, 'Future Glow', 'Banish 1 Psychic-Type monster from your Graveyard, and note its Level. All face-up Psychic-Type monsters you control gain ATK equal to that Level × 200.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90592429,3,0,48,262146,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (90592429, 'Vylon Filament', 'Equip only to a "Vylon" monster. If the equipped monster attacks, your opponent cannot activate any Spell/Trap Cards until the end of the Damage Step. If this face-up card on the field is sent to the Graveyard: You can add 1 "Vylon" Spell Card from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27980138,3,0,0,2,0,0,0,0,0,2097200);
INSERT OR REPLACE INTO "texts" VALUES (27980138, 'Quill Pen of Gulldos', 'Target 2 WIND monsters in your Graveyard and 1 card on the field; shuffle both of those first 2 targets into your Deck and return the other to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63485233,3,0,165,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (63485233, 'Star Changer', 'Target 1 face-up monster on the field and activate 1 of these effects:
● Increase that target''s Level by 1.
● Reduce that target''s Level by 1.', 'Increase 1 level', 'Decrease 1 level', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90470931,3,0,0,2,0,0,0,0,0,32768);
INSERT OR REPLACE INTO "texts" VALUES (90470931, 'Oni-Gami Combo', 'Target 1 face-up Xyz Monster you control and detach all of its Xyz Material; this turn, that target can attack twice during the same Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26864586,3,0,0,2,0,0,0,0,0,3145728);
INSERT OR REPLACE INTO "texts" VALUES (26864586, 'Resonance Device', 'Target 2 face-up monsters you control with the same Type and Attribute; change one of their Levels to the current Level of the other, until the End Phase.', 'Select the monster whose Level should be changed', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52263685,3,0,172,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (52263685, 'Peeking Goblin', 'Your opponent reveals the top 3 cards of their Deck. Choose one to place on the bottom of the Deck and place the other two on top of the Deck in any order.', 'Select card to place on the bottom of Deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99657399,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (99657399, 'Asleep at the Switch', 'When your opponent gains Life Points: Target 1 monster your opponent controls; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25642998,3,0,0,4,0,0,0,0,0,5308416);
INSERT OR REPLACE INTO "texts" VALUES (25642998, 'Poseidon Wave', 'When an opponent''s monster declares an attack: Target the attacking monster; negate the attack, and if you do, inflict 800 damage to your opponent for each face-up Fish, Sea Serpent, or Aqua-Type monster you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52140003,3,0,0,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (52140003, 'Explosive Urchin', 'Activate only when your opponent activates a Trap Card. During your Standby Phase: Inflict 1000 damage to your opponent. Your opponent must control a face-up Trap Card for you to activate and resolve this effect. During your 3rd End Phase after activation, send this card to the Graveyard.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98535702,3,0,0,4,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (98535702, 'Damage Vaccine Ω MAX', 'When you take damage by battle or by a card effect: Gain Life Points equal to the damage you took.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24920410,3,0,0,4,0,0,0,0,0,8208);
INSERT OR REPLACE INTO "texts" VALUES (24920410, 'Overwind', 'Target 1 face-up "Wind-Up" monster you control; its ATK and DEF are doubled, and it returns to the hand during the End Phase. You can only activate 1 "Overwind" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69610924,3,0,72,8388641,2000,0,3,8192,2,1073815552);
INSERT OR REPLACE INTO "texts" VALUES (69610924, 'Number 17: Leviathan Dragon', '2 Level 3 monsters
Once per turn: You can detach 1 Xyz Material from this card; this card gains 500 ATK. If this card has no Xyz Material, it cannot attack your opponent directly.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5014629,3,0,0,8388641,1900,1000,3,131072,2,4194304);
INSERT OR REPLACE INTO "texts" VALUES (5014629, 'Submersible Carrier Aero Shark', '2 Level 3 monsters
Once per turn: You can detach 1 Xyz Material from this card; inflict 100 damage to your opponent for each of your banished monsters.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32003338,3,0,72,8388641,0,2900,3,32,32,4096);
INSERT OR REPLACE INTO "texts" VALUES (32003338, 'Number 34: Terror-Byte', '3 Level 3 monsters
Once per turn: You can detach 1 Xyz Material from this card to target 1 Level 4 or lower Attack Position monster your opponent controls; gain control of it until the End Phase.', 'Take control', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68597372,3,0,88,8388641,1900,1500,4,32,1,10240);
INSERT OR REPLACE INTO "texts" VALUES (68597372, 'Wind-Up Zenmaister', '2 Level 4 monsters
This card gains 300 ATK for each Xyz Material attached to this card. Once per turn: You can detach 1 Xyz Material from this card to target 1 face-up monster you control; change that face-up monster to face-down Defense Position, and if you do, during the End Phase of this turn, change it to face-up Attack Position.', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95992081,3,0,0,8388641,1800,1600,3,64,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (95992081, 'Leviair the Sea Dragon', '2 Level 3 monsters
Once per turn: You can detach 1 Xyz Material from this card to target 1 banished Level 4 or lower monster; Special Summon that target to your side of the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31386180,3,0,0,8388641,2600,1700,5,4,16,1090519043);
INSERT OR REPLACE INTO "texts" VALUES (31386180, 'Tiras, Keeper of Genesis', '2 Level 5 monsters
 
This card''s effects can only be applied/resolved while it has Xyz Material. This card cannot be destroyed by card effects. At the end of the Battle Phase, if this card attacked or was attacked: Target 1 card your opponent controls; destroy that target. During each of your End Phases: Detach 1 Xyz Material from this card.', 'Target 1 card to destroy', 'Detach 1 Xyz Material from this card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87313164,3,0,0,1048580,0,0,0,0,0,-2147483646);
INSERT OR REPLACE INTO "texts" VALUES (87313164, 'Oh F!sh!', 'When an Effect Monster''s effect activates: Shuffle 1 of your banished Fish, Sea Serpent, or Aqua-Type monsters into the Main Deck; negate the activation and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24707869,3,0,0,4,0,0,0,0,0,1048832);
INSERT OR REPLACE INTO "texts" VALUES (24707869, 'Bright Future', 'Target 2 of your banished Psychic-Type monsters; return both those targets to the Graveyard and draw 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50292967,3,0,0,4,0,0,0,0,0,1048580);
INSERT OR REPLACE INTO "texts" VALUES (50292967, 'Past Image', 'If you control a face-up Psychic-Type monster: Target 1 monster your opponent controls; banish it. During the next Standby Phase, it returns to the opponent''s side of the field in the same Battle Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86690572,3,0,0,1048580,0,0,0,0,0,-2147482611);
INSERT OR REPLACE INTO "texts" VALUES (86690572, 'Burgeoning Whirlflame', 'When a Trap Card is activated: Send 1 "Laval" monster from your hand to the Graveyard; negate the activation and destroy it. If this card is in the Graveyard: You can banish 2 FIRE monsters from your Graveyard; add this card to your hand.', '这张卡加入手卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13685271,3,0,0,4,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (13685271, 'Treaty on Uniform Nomenclature', 'If you control 2 or more face-up monsters with the same name, except Tokens: Apply this effect, depending on how many you control.
● Exactly 2: Destroy 1 Spell/Trap Card your opponent controls.
● Exactly 3: Destroy all Spell/Trap Cards your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59070329,3,0,0,4,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (59070329, 'Utopian Aura', 'Detach 1 Xyz Material you control; the face-up Xyz Monsters you control cannot be destroyed by card effects until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86474024,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (86474024, 'United Front', 'When a Trap Card is activated while you control 2 or more face-up monsters with the same Level: Negate the activation and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12863633,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (12863633, 'Curse of the Circle', 'Target 1 monster your opponent controls; your opponent cannot Tribute it, or use it as a Synchro Material Monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48357738,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (48357738, 'Tyrant''s Tummyache', 'Activate by Tributing 1 monster. Neither player can Special Summon a Level 6 or higher monster. If you have 3 or more cards in your hand, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11741041,3,0,0,131076,0,0,0,0,0,67108866);
INSERT OR REPLACE INTO "texts" VALUES (11741041, 'Raigeki Bottle', 'Each time a monster you control declares an attack, place 1 Thunder Counter on this card. You can send this card with 4 or more Thunder Counters to the Graveyard; destroy all monsters your opponent controls.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48135190,3,0,0,4,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (48135190, 'Gravelstorm', 'Target 1 Spell/Trap Card on each side of the field; return them to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85352446,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (85352446, 'Attention!', 'Target 1 face-up Level 5 or lower monster your opponent controls; destroy all face-up monsters on the field with a different Level than it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96457619,3,0,115,131076,0,0,0,0,0,33554432);
INSERT OR REPLACE INTO "texts" VALUES (96457619, 'Xyz Veil', 'Face-up Xyz Monsters with Xyz Material cannot be targeted by card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69846323,3,0,0,33,1500,500,4,131072,2,1073152);
INSERT OR REPLACE INTO "texts" VALUES (69846323, 'Piercing Moray', 'Once per turn: You can Tribute 1 Fish, Sea Serpent, or Aqua-Type monster; this card gains 600 ATK. If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95231062,3,0,0,33,1400,0,3,262144,2,1);
INSERT OR REPLACE INTO "texts" VALUES (95231062, 'Lost Blue Breaker', 'If there is another face-up Fish, Sea Serpent, or Aqua-Type monster on the field: You can Tribute this card to target 1 Spell/Trap Card on the field; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21620076,3,0,0,4129,400,200,2,16,32,537919488);
INSERT OR REPLACE INTO "texts" VALUES (21620076, 'Pain Painter', 'While this card is face-up on the field, its name is treated as "Plaguespreader Zombie". Once per turn: You can target up to 2 face-up Zombie-Type monsters you control, except this card; they become Level 2 until the End Phase. They cannot be used as Synchro Material Monsters except for the Synchro Summon of a Zombie-Type monster.', 'Change level', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21507589,3,0,0,2,0,0,0,0,0,1049600);
INSERT OR REPLACE INTO "texts" VALUES (21507589, 'Fish and Swaps', 'Discard 1 card to target 2 of your banished Fish, Sea Serpent, or Aqua-Type monsters; add them to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57902193,3,0,0,2,0,0,0,0,0,1024);
INSERT OR REPLACE INTO "texts" VALUES (57902193, 'Painful Return', 'Your opponent chooses 1 monster in your Graveyard. During the End Phase, add that monster to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93396832,3,0,0,1048580,0,0,0,0,0,-2147483645);
INSERT OR REPLACE INTO "texts" VALUES (93396832, 'Smashing Horn', 'When a monster effect or Trap Card is activated that negates the Normal or Special Summon of a monster(s): Negate the activation and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68124775,3,0,0,8225,2300,1000,6,8192,8,4);
INSERT OR REPLACE INTO "texts" VALUES (68124775, 'Orient Dragon', '1 Tuner + 1 or more non-Tuner monsters
When this card is Synchro Summoned: Target 1 face-up Synchro Monster your opponent controls; banish that target.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94119480,3,0,0,8388641,2600,1700,5,8,32,3);
INSERT OR REPLACE INTO "texts" VALUES (94119480, 'Adreus, Keeper of Armageddon', '2 Level 5 monsters
Once per turn: You can detach 1 Xyz Material from this card to target 1 face-up card your opponent controls; destroy it.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69572169,3,0,12296,33,1100,1600,4,1,16,1040);
INSERT OR REPLACE INTO "texts" VALUES (69572169, 'Elemental HERO Flash', 'When this card is destroyed by battle and sent to the Graveyard: You can banish this card and 3 "Elemental HERO" Monster Cards with different names from your Graveyard to target 1 Normal Spell Card in your Graveyard; add that target to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24103628,3,0,0,33,600,700,3,2,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (24103628, 'Phantom Magician', 'When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 "HERO" monster with 1000 or less ATK from your Deck in face-up Defense Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21143940,3,0,165,65538,0,0,0,0,0,268697600);
INSERT OR REPLACE INTO "texts" VALUES (21143940, 'Mask Change', 'Target 1 face-up "HERO" monster you control; send it to the Graveyard, then Special Summon 1 "Masked HERO" monster from the Extra Deck with the same Attribute that the "HERO" monster had when it was on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8949584,3,0,0,2,0,0,0,0,0,262656);
INSERT OR REPLACE INTO "texts" VALUES (8949584, 'A Hero Lives', 'When you control no face-up monsters: Pay half your Life Points; Special Summon 1 Level 4 or lower "Elemental HERO" monster from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46759931,3,0,20488,97,2500,2000,8,1,32,106496);
INSERT OR REPLACE INTO "texts" VALUES (46759931, 'Vision HERO Trinity', '3 "HERO" monsters
During the turn this card was Fusion Summoned, its ATK is double its original ATK. This Fusion Summoned card can attack 3 times during each Battle Phase. This card cannot attack your opponent directly.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1945387,3,0,12296,97,2600,2100,8,1,4,256);
INSERT OR REPLACE INTO "texts" VALUES (1945387, 'Elemental HERO Nova Master', '1 "Elemental HERO" monster + 1 FIRE monster
Must be Fusion Summoned and cannot be Special Summoned in other ways. If this card destroys an opponent''s monster by battle: Draw 1 card.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58147549,3,0,40968,97,2200,1800,6,1,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (58147549, 'Masked HERO Goka', 'Must be Special Summoned with "Mask Change" and cannot be Special Summoned by other ways. This card gains 100 ATK for each "HERO" monster in your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10920352,3,0,40968,97,2400,2000,6,1,2,16777216);
INSERT OR REPLACE INTO "texts" VALUES (10920352, 'Masked HERO Vapor', 'Must be Special Summoned with "Mask Change", and cannot be Special Summoned by other ways. This card cannot be destroyed by card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45170821,3,0,20488,97,2800,2100,8,1,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (45170821, 'Vision HERO Adoration', '2 "HERO" monsters 
 Once per turn: You can target 1 face-up monster your opponent controls and 1 face-up "HERO" monster you control, except this card; the opponent''s targeted monster loses ATK and DEF equal to the ATK of your targeted monster, until the End Phase.', 'Decrease ATK and DEF', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37926346,3,0,4106,8388641,1900,0,4,8,32,-1073741822);
INSERT OR REPLACE INTO "texts" VALUES (37926346, 'Steelswarm Roach', '2 Level 4 monsters
When a Level 5 or higher monster would be Special Summoned: You can detach 1 Xyz Material from this card; negate the Special Summon and destroy it.', '5星以上的怪兽的特殊召唤无效并破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
