BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (32012841,3,0,0,17,0,3000,5,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (32012841, 'Millennium Shield', 'A famous shield said to belong to an ancient Egyptian Pharaoh. Legends tell of its power to block any strong attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24433920,3,0,0,17,1750,2000,6,32,32,0);
INSERT OR REPLACE INTO "texts" VALUES (24433920, 'Pendulum Machine', 'A horrible torture machine with a large pendulum blade.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6285791,3,0,62,33,1400,700,3,16384,1,16);
INSERT OR REPLACE INTO "texts" VALUES (6285791, 'The Wicked Worm Beast', 'This face-up card on the field is returned to the owner''s hand during the End Phase of your turn.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53493204,3,0,0,33,1200,1000,4,4,16,268435456);
INSERT OR REPLACE INTO "texts" VALUES (53493204, 'Goddess with the Third Eye', 'You can substitute this card for any 1 Fusion Material Monster. When you do this, the other Fusion Material Monster(s) must be the correct one(s).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99426834,3,0,0,33,1000,1100,4,64,2,268435456);
INSERT OR REPLACE INTO "texts" VALUES (99426834, 'Beastking of the Swamps', 'You can substitute this card for any 1 Fusion-Material Monster. When you do this, the other Fusion-Material Monster(s) must be the correct one(s).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50259460,3,0,0,33,1100,900,3,8,32,268435456);
INSERT OR REPLACE INTO "texts" VALUES (50259460, 'Versago the Destroyer', 'You can substitute this card for any 1 Fusion Material Monster. When you do this, the other Fusion Material Monster(s) must be the correct one(s).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33508719,3,0,0,2097185,700,600,2,256,1,264);
INSERT OR REPLACE INTO "texts" VALUES (33508719, 'Morphing Jar', 'FLIP: Both players discard all the cards in their hands, then draw 5 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67959180,3,0,0,33,950,700,3,4,16,134225920);
INSERT OR REPLACE INTO "texts" VALUES (67959180, 'Goddess of Whim', 'Toss a coin and call Heads or Tails. Call it right and this card''s ATK will be doubled during this turn. Call it wrong and it will be halved during this turn.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79575620,3,0,0,33,400,1500,3,2,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (79575620, 'Injection Fairy Lily', 'If this card attacks or is attacked, during damage calculation (in either player''s turn): You can pay 2000 Life Points once per battle; this card gains 3000 ATK during that damage calculation only.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24317029,3,0,46,2097185,1200,2000,4,2,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (24317029, 'Gravekeeper''s Spy', 'FLIP: Special Summon 1 "Gravekeeper''s" monster with 1500 or less ATK from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23205979,3,0,0,33,300,200,3,16,32,16777282);
INSERT OR REPLACE INTO "texts" VALUES (23205979, 'Spirit Reaper', 'Cannot be destroyed by battle. After resolving a card effect that targets this face-up card, destroy this card. When this card inflicts battle damage to your opponent by a direct attack: Discard 1 random card from their hand.', 'Discard hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9596126,3,0,0,33,2300,2000,6,2,32,1310724);
INSERT OR REPLACE INTO "texts" VALUES (9596126, 'Chaos Sorcerer', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your Graveyard. Once per turn: You can target 1 face-up monster on the field; banish that target. This card cannot attack the turn you activate this effect.', 'Special Summon', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72989439,3,0,4979,33,3000,2500,8,1,16,2457604);
INSERT OR REPLACE INTO "texts" VALUES (72989439, 'Black Luster Soldier - Envoy of the Beginning', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your Graveyard. Once per turn, you can activate 1 of these effects.
● Target 1 monster on the field; banish that target face-up. This card cannot attack the turn you activate this effect.
● During the Damage Step, if this attacking card destroys an opponent''s monster by battle: It can make a second attack in a row.', 'Special Summon', 'Banish', 'Attack again', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73891874,3,0,0,33,2200,1400,6,8192,32,8196);
INSERT OR REPLACE INTO "texts" VALUES (73891874, 'White-Horned Dragon', 'When this card is Normal Summoned or Special Summoned, select up to 5 Spell Cards from your opponent''s Graveyard and remove them from play. This card gains 300 ATK for each card removed from play by this card''s effect.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90960358,3,0,18287981363298,4194337,2000,1700,6,2,32,401408);
INSERT OR REPLACE INTO "texts" VALUES (90960358, 'Toon Dark Magician Girl', 'This card cannot be Normal Summoned or Set. This card can only be Special Summoned while "Toon World" is on your side of the field. You can Special Summon this monster from your hand, but Tributes are required for monsters Level 5 or more. When "Toon World" on the field is destroyed, this card is also destroyed. If your opponent doesn''t control a Toon Monster, this card can attack your opponent directly. If a face-up Toon Monster is on your opponent''s side of the field, you must select the Toon Monster as an attack target. This card gains 300 ATK for each "Dark Magician" or "Magician of Black Chaos" in either player''s Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49905576,3,0,0,33,1600,1200,4,4,16,8388611);
INSERT OR REPLACE INTO "texts" VALUES (49905576, 'Meltiel, Sage of the Sky', 'Each time a Counter Trap Card is activated, gain 1000 Life Points, and if "The Sanctuary in the Sky" is face-up on the field, destroy 1 card your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84177693,3,0,0,33,1000,2000,4,4,16,8388608);
INSERT OR REPLACE INTO "texts" VALUES (84177693, 'Radiant Jeral', 'When this card is sent to the Graveyard (except if destroyed by battle), gain 1000 Life Points if "The Sanctuary in the Sky" is on the field.', 'Gain LP', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29424328,3,0,0,33,2800,1000,7,8192,32,0);
INSERT OR REPLACE INTO "texts" VALUES (29424328, 'Diabolos, King of the Abyss', 'This card cannot be Special Summoned. If you Tribute Summon this card, the Tributes must be DARK. This card cannot be Tributed by a card''s effect. During your opponent''s Draw Phase, before their draw, look at the top card of their Deck, then put that card on the top or bottom of their Deck.', 'Check the card', 'Put card at top of deck', 'Put card at bottom of deck', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55818463,3,0,0,33,2400,1200,6,16,32,16);
INSERT OR REPLACE INTO "texts" VALUES (55818463, 'Lich Lord, King of the Underworld', 'If you Tribute Summon this card, the Tribute must be DARK. If this card is Tributed by a card''s effect and sent to the Graveyard, it returns to its owner''s hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82213171,3,0,0,33,1200,800,4,8,32,8196);
INSERT OR REPLACE INTO "texts" VALUES (82213171, 'Prometheus, King of the Shadows', 'When you Normal Summon this card, remove from play any number of DARK monsters from your Graveyard. This card gains 400 ATK for each removed card, until the End Phase of this turn.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71717923,3,0,0,33,1000,900,4,256,1,2);
INSERT OR REPLACE INTO "texts" VALUES (71717923, 'Mormolith', 'You can Tribute 1 face-up EARTH monster to destroy all face-up monsters with DEF equal to or less than the ATK of the Tributed monster.', 'Monster desrtuction', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40921744,3,0,0,33,2800,2300,8,4,32,2);
INSERT OR REPLACE INTO "texts" VALUES (40921744, 'Darklord Zerato', 'If you have 4 or more DARK monsters with different names in your Graveyard, you can Tribute Summon this card by Tributing 1 DARK monster. You can send 1 DARK monster from your hand to the Graveyard; destroy all monsters your opponent controls. During the End Phase, if you activated this effect this turn: Destroy this card.', 'Send 1 DARK monster to Graveyard', 'Destroy', 'Self-Destruct', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78700060,3,0,0,33,1900,1800,4,8,32,-2147483646);
INSERT OR REPLACE INTO "texts" VALUES (78700060, 'Doomcaliber Knight', 'Cannot be Special Summoned. During either player''s turn, when a monster effect is activated: Tribute this face-up card; negate the activation, and if you do, destroy that monster.', '不能特殊召唤', '怪物效果效果发动无效并破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21502796,3,0,56,2097185,200,100,2,16384,16,131);
INSERT OR REPLACE INTO "texts" VALUES (21502796, 'Ryko, Lightsworn Hunter', 'FLIP: Apply these effects in sequence.
● You can target 1 card on the field; destroy that target.
● Send the top 3 cards of your Deck to the Graveyard.', 'Destroy', 'Destroy a card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94381039,3,0,56,33,2300,200,5,4,16,11);
INSERT OR REPLACE INTO "texts" VALUES (94381039, 'Celestia, Lightsworn Angel', 'When you Tribute Summon this card by Tributing a "Lightsworn" monster: You can send the top 4 cards of your Deck to the Graveyard, then target up to 2 cards your opponent controls; destroy those targets.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11819616,3,0,0,33,2800,2600,8,1024,8,-2146435069);
INSERT OR REPLACE INTO "texts" VALUES (11819616, 'Tytannial, Princess of Camellias', 'You can Tribute 1 face-up Plant-Type monster you control to negate the activation of a card or effect that targets a card(s) on the field and destroy it.', '效果无效并破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (423585,3,0,0,33,800,1600,4,2,32,264704);
INSERT OR REPLACE INTO "texts" VALUES (423585, 'Summoner Monk', 'Cannot be Tributed. When this card is Normal or Flip Summoned: Change this card to Defense Position. Once per turn: You can discard 1 Spell Card; Special Summon 1 Level 4 monster from your Deck, but that monster cannot attack this turn.', 'Change to defense position', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31038159,3,0,0,33,2200,1800,6,8192,16,1048624);
INSERT OR REPLACE INTO "texts" VALUES (31038159, 'Genesis Dragon', 'Once per turn, you can send 1 Dragon-Type monster from your hand to the Graveyard to add 1 Dragon-Type monster from your Graveyard to your hand. When this card is sent from the field to the Graveyard, you can return all Dragon-Type monsters from your Graveyard to your Deck.', 'Add to hand', 'Return to deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7634581,3,0,0,33,-2,0,10,32,32,17047552);
INSERT OR REPLACE INTO "texts" VALUES (7634581, 'Orichalcos Shunoros', 'This card cannot be Normal Summoned or Set. If a Normal Monster you control is destroyed by battle, you can Special Summon this card from your hand. This card gains 1000 ATK for each monster your opponent controls. Face-up Level 4 Normal Monsters on the field cannot be destroyed by card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99267150,3,0,0,97,5000,5000,12,8192,32,19922944);
INSERT OR REPLACE INTO "texts" VALUES (99267150, 'Five-Headed Dragon', '5 Dragon-Type monsters
This monster cannot be Special Summoned except by Fusion Summon. This card cannot be destroyed by battle with an EARTH, WATER, FIRE, WIND, or DARK monster. (Damage calculation is applied normally.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48156348,3,0,25,97,2400,1500,6,512,32,262179);
INSERT OR REPLACE INTO "texts" VALUES (48156348, 'Gladiator Beast Gyzarus', '"Gladiator Beast Bestiari" + 1 "Gladiator Beast" monster
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization".) When this card is Special Summoned: You can target up to 2 cards on the field; destroy those targets. At the end of the Battle Phase, if this card attacked or was attacked: You can shuffle it into the Extra Deck; Special Summon 2 "Gladiator Beast" monsters from your Deck, except "Gladiator Beast Bestiari".', 'Destroy', 'Special Summon', 'Please select 1 "Gladiator Beast Bestiari"', 'Please select 1 "Gladiator Beast" monster', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56606928,3,0,0,2,0,0,0,0,0,1048578);
INSERT OR REPLACE INTO "texts" VALUES (56606928, 'Eternal Drought', 'Destroy all face-up Fish-Type monsters on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94716515,3,0,0,2,0,0,0,0,0,1048578);
INSERT OR REPLACE INTO "texts" VALUES (94716515, 'Eradicating Aerosol', 'Destroy all face-up Insect-Type monsters on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68005187,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (68005187, 'Soul Exchange', 'Target 1 monster your opponent controls; this turn, if you Tribute a monster, you must Tribute that monster, as if you controlled it. You cannot conduct your Battle Phase the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15259703,3,0,98,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (15259703, 'Toon World', 'Pay 1000 Life Points to activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74137509,3,0,0,65538,0,0,0,0,0,134225920);
INSERT OR REPLACE INTO "texts" VALUES (74137509, 'Graceful Dice', 'Roll a six-sided die. All monsters you currently control gain ATK and DEF equal to the result x 100, until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13604200,3,0,0,2,0,0,0,0,0,262656);
INSERT OR REPLACE INTO "texts" VALUES (13604200, 'Sage''s Stone', 'Activate only if you control a face-up "Dark Magician Girl". Special Summon 1 "Dark Magician" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89997728,3,0,98,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (89997728, 'Toon Table of Contents', 'Add 1 card from your Deck to your hand that includes "Toon" in its card name, or is named "Manga Ryu-Ran".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67169062,3,0,0,2,0,0,0,0,0,1312);
INSERT OR REPLACE INTO "texts" VALUES (67169062, 'Pot of Avarice', 'Target 5 monsters in your Graveyard; shuffle all 5 into the Deck, then draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17589298,3,0,0,262146,0,0,0,0,0,8208);
INSERT OR REPLACE INTO "texts" VALUES (17589298, 'Sword of Dark Rites', 'Equip only to a DARK monster. It gains 400 ATK. When the equipped monster is Tributed and this card is sent to the Graveyard, return this card to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81191584,3,0,0,2,0,0,0,0,0,2098192);
INSERT OR REPLACE INTO "texts" VALUES (81191584, 'Recurring Nightmare', 'Select 2 DARK monsters with 0 DEF in your Graveyard and return them to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38120068,3,0,0,2,0,0,0,0,0,264);
INSERT OR REPLACE INTO "texts" VALUES (38120068, 'Trade-In', 'Discard 1 Level 8 monster; draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67227834,3,0,0,262146,0,0,0,0,0,8396800);
INSERT OR REPLACE INTO "texts" VALUES (67227834, 'Magic Formula', 'Equip only to "Dark Magician" or "Dark Magician Girl". The equipped monster gains 700 ATK. When this card is sent from the field to the Graveyard, gain 1000 Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88279736,3,0,172,131076,0,0,0,0,0,64);
INSERT OR REPLACE INTO "texts" VALUES (88279736, 'Robbin'' Goblin', 'Each time a monster you control inflicts Battle Damage to your opponent, your opponent discards 1 random card.', '对方随机丢弃1张手牌', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (126218,3,0,0,4,0,0,0,0,0,134225920);
INSERT OR REPLACE INTO "texts" VALUES (126218, 'Skull Dice', 'Roll a six-sided die. All monsters your opponent currently controls lose ATK and DEF equal to the result x 100, until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93016201,3,0,0,131076,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (93016201, 'Royal Oppression', 'Either player can pay 800 Life Points to negate the Special Summon of a monster(s), and/or an effect that Special Summons a monster(s), and destroy those cards.', 'Negate Special Summon', 'Activate effect of "Royal Oppression"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76515293,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (76515293, 'Xing Zhen Hu', 'Activate by selecting 2 Set Spell or Trap Cards on the field. The selected Spell or Trap Cards cannot be activated.', 'セットされた魔法・罠カードを２枚選んで下さい', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35027493,3,0,0,4,0,0,0,0,0,2097218);
INSERT OR REPLACE INTO "texts" VALUES (35027493, 'Deck Devastation Virus', 'Tribute 1 DARK monster with 2000 or more ATK; check your opponent''s hand, all monsters they control, and all cards they draw until the end of their 3rd turn after this card''s activation, and destroy all those monsters with 1500 or less ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59616123,3,0,0,4,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (59616123, 'Trap Stun', 'Negate the effects of all other Trap Cards on the field during this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
