BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (89631139,3,0,0,17,3000,2500,8,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (89631139, 'Blue-Eyes White Dragon', 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19153634,3,0,0,33,2000,1400,5,16,32,0);
INSERT OR REPLACE INTO "texts" VALUES (19153634, 'Patrician of Darkness', 'You choose the attack targets for your opponent''s attacks.', 'Do you want to change attack target?', 'Select target', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77044671,3,0,0,33,1200,1400,4,16,1,1310720);
INSERT OR REPLACE INTO "texts" VALUES (77044671, 'Pyramid Turtle', 'When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 Zombie-Type monster with 2000 or less DEF from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40933924,3,0,26,33,1000,1000,4,1,32,128);
INSERT OR REPLACE INTO "texts" VALUES (40933924, 'Dark Scorpion Burglars', 'When this card inflicts Battle Damage to your opponent''s Life Points, your opponent selects 1 Spell Card from their Deck and sends it to the Graveyard. Then shuffle the Deck.', 'Select 1 Spell Card to send to the Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76922029,3,0,0,33,1400,1500,4,1,32,200);
INSERT OR REPLACE INTO "texts" VALUES (76922029, 'Don Zaloog', 'When this card inflicts Battle Damage to your opponent, you can either:
● Discard 1 random card from your opponent''s hand. OR
● Send the top 2 cards of your opponent''s Deck to the Graveyard.', 'Select effect', 'Discard 1 random card from your opponent''s hand.', 'Send the top 2 cards of your opponent''s Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76052811,3,0,0,33,2000,1400,5,8,32,64);
INSERT OR REPLACE INTO "texts" VALUES (76052811, 'Helpoemer', 'Cannot be Special Summoned from the Graveyard. If this card was destroyed by battle and sent to the Graveyard, this effect activates at the end of each of your opponent''s Battle Phases: Discard 1 random card from your opponent''s hand. This card must be in the Graveyard to activate and to resolve this effect', '戦闘によって破壊され墓地に送られた場合効果が発動', 'カードを捨てる', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6967870,3,0,26,33,1200,1000,3,1,32,129);
INSERT OR REPLACE INTO "texts" VALUES (6967870, 'Cliff the Trap Remover', 'When this card inflicts Battle Damage to your opponent''s Life Points, you can select and activate 1 of the following effects:
● Destroy 1 Spell Card or Trap Card on the field.
● Send 2 cards from the top of your opponent''s Deck to his/her Graveyard.', 'Select effect', 'Destroy 1 Spell Card or Trap Card on the field.', 'Send 2 cards from the top of your opponent''s Deck to his/her Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71200730,3,0,0,33,2800,3000,8,16,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (71200730, 'Despair from the Dark', 'When this card is sent from your hand or Deck to your Graveyard by an opponent''s card effect: Special Summon this card.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34193084,3,0,0,33,1700,1500,4,16,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (34193084, 'Fear from the Dark', 'When this card is sent from your hand or Deck to your Graveyard by an opponent''s card effect: Special Summon this card.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61587183,3,0,26,33,1000,1000,3,1,32,16);
INSERT OR REPLACE INTO "texts" VALUES (61587183, 'Dark Scorpion - Chick the Yellow', 'When this card inflicts Battle Damage to your opponent''s Life Points, you can select and activate 1 of the following effects:
● Return 1 card on the field to its owner''s hand.
● Pick up 1 card on the top of your opponent''s Deck (Your opponent does not look at the card). Select the top or the bottom of the Deck and return the card there.', 'Select effect', 'Return 1 card on the field to its owner''s hand.', 'Pick up 1 card on the top of your opponent''s Deck', 'Return to top of deck', 'Return to bottom of deck', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48768179,3,0,26,33,1800,1500,5,1,32,168);
INSERT OR REPLACE INTO "texts" VALUES (48768179, 'Dark Scorpion - Gorg the Strong', 'When this card inflicts Battle Damage to your opponent''s Life Points, you can select and activate 1 of the following effects:
● Return 1 Monster Card on your opponent''s side of the field to the top of its owner''s Deck.
● Send 1 card from the top of your opponent''s Deck to the Graveyard.', 'Select effect', 'Return 1 Monster Card on your opponent''s side of the field to the top of its owner''s Deck.', 'Send 1 card from the top of your opponent''s Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74153887,3,0,26,33,1000,1800,4,1,32,1552);
INSERT OR REPLACE INTO "texts" VALUES (74153887, 'Dark Scorpion - Meanae the Thorn', 'When this card inflicts Battle Damage to your opponent''s Life Points, you can select and activate 1 of the following effects:
● Add 1 card that includes "Dark Scorpion" in its card name, or is named "Cliff the Trap Remover", from your Deck to your hand.
● Add 1 card that includes "Dark Scorpion" in its card name, or is named "Cliff the Trap Remover", from your Graveyard to your hand.', 'Select effect', 'Add 1 card that includes "Dark Scorpion" in its card name, or is named "Cliff the Trap Remover", from your Deck to your hand.', 'Add 1 card that includes "Dark Scorpion" in its card name, or is named "Cliff the Trap Remover", from your Graveyard to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57281778,3,0,0,33,2400,2000,6,16,32,1048578);
INSERT OR REPLACE INTO "texts" VALUES (57281778, 'Ryu Kokki', 'At the end of the Damage Step, if this card battled a Warrior or Spellcaster-Type monster: Destroy that monster.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26495087,3,0,142,33,1550,1550,4,16,32,8);
INSERT OR REPLACE INTO "texts" VALUES (26495087, 'Vampire Lady', 'When this card inflicts battle damage to your opponent: Declare 1 card type (Monster, Spell, or Trap); your opponent sends 1 card of that type from their Deck to the Graveyard.', 'Card type to send to Graveyard', 'Monster card', 'Spell card', 'Trap card', 'Please declare type', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44436472,3,0,0,33,1700,1650,4,16,32,2097152);
INSERT OR REPLACE INTO "texts" VALUES (44436472, 'Double Coston', 'This card can be treated as 2 Tributes for the Tribute Summon of a DARK monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70821187,3,0,0,33,1800,1500,4,16,32,16);
INSERT OR REPLACE INTO "texts" VALUES (70821187, 'Regenerating Mummy', 'When this card is sent from your hand to your Graveyard by an opponent''s card effect: Return this card to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74713516,3,0,65,2097185,100,1000,1,8,32,262400);
INSERT OR REPLACE INTO "texts" VALUES (74713516, 'Dark Mimic LV1', 'FLIP: Draw 1 card. During your Standby Phase, by sending this face-up card to the Graveyard, Special Summon 1 "Dark Mimic LV3" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1102515,3,0,65,33,1000,1000,3,8,32,256);
INSERT OR REPLACE INTO "texts" VALUES (1102515, 'Dark Mimic LV3', 'If this card is sent to the Graveyard by battle, the controller of this card draws 1 card. If this card was Special Summoned by the effect of "Dark Mimic LV1", they draw 2 cards instead.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17259470,3,0,0,33,1800,0,4,16,32,1311744);
INSERT OR REPLACE INTO "texts" VALUES (17259470, 'Zombie Master', 'Once per turn: You can send 1 monster from your hand to the Graveyard, then target 1 Level 4 or lower Zombie-Type monster in either player''s Graveyard; Special Summon that target. This card must be face-up on the field to activate and to resolve this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77936940,3,0,0,33,1300,1200,4,16,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (77936940, 'Gernia', 'During your next Standby Phase, after this face-up card you control was destroyed and sent to your Graveyard by an opponent''s card effect: Special Summon it.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63665875,3,0,172,33,1100,1050,4,16,32,1049216);
INSERT OR REPLACE INTO "texts" VALUES (63665875, 'Goblin Zombie', 'When this card inflicts battle damage to your opponent: Send the top card of their Deck to the Graveyard. When this card is sent from the field to the Graveyard: Add 1 Zombie-Type monster with 1200 or less DEF from your Deck to your hand.', '对方卡组最上面的1张卡送去墓地', 'Search card group', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40991587,3,0,0,33,0,2200,3,16,32,51380224);
INSERT OR REPLACE INTO "texts" VALUES (40991587, 'The Lady in Wight', 'Face-up Level 3 or lower Zombie-Type monsters on the field, except "The Lady in Wight", cannot be destroyed by battle and are unaffected by Spell/Trap effects. This card''s name becomes "Skull Servant" while it is in the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68722455,3,0,0,33,2800,2100,7,16,1,16);
INSERT OR REPLACE INTO "texts" VALUES (68722455, 'Red Ogre', 'When this card is Normal Summoned: You can send any number of cards from your hand to the Graveyard, then target the same number of cards on the field; return those targets to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44330098,3,0,0,33,2700,2500,7,8,32,4456448);
INSERT OR REPLACE INTO "texts" VALUES (44330098, 'Gorz the Emissary of Darkness', 'When you take damage from a card your opponent control: You can Special Summon this card from your hand. You must control no cards to activate and to resolve this effect. When Special Summoned this way, activate the appropriate effect, based on the type of damage:
● Battle Damage: Special Summon 1 "Emissary of Darkness Token" (Fairy-Type/LIGHT/Level 7/ATK ?/DEF ?). Its ATK and DEF are each equal to the amount of Battle Damage you took.
● Effect Damage: Inflict damage to your opponent equal to the amount of damage you took.', 'Special Summon', 'Special Summon token', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37675138,3,0,0,33,1600,200,4,16,1,1);
INSERT OR REPLACE INTO "texts" VALUES (37675138, 'Bone Crusher', 'When this card is Special Summoned from your Graveyard by the effect of a Zombie-Type monster, you can destroy 1 Spell or Trap Card your opponent controls. Destroy this card during the End Phase of the turn it was Special Summoned.', 'Destroy', 'Self Destruct', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24040093,3,0,53,33,1700,1000,4,8,16,512);
INSERT OR REPLACE INTO "texts" VALUES (24040093, 'Fabled Grimro', 'If you control a face-up "Fabled" monster, you can send this card from your hand to the Graveyard to add 1 "Fabled" monster from your Deck to your hand, except "Fabled Grimro".', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55794644,3,0,0,33,2700,2100,8,4,16,3407879);
INSERT OR REPLACE INTO "texts" VALUES (55794644, 'Master Hyperion', 'You can Special Summon this card from your hand by removing from play 1 "The Agent" monster in your hand, field, or Graveyard. Once per turn, you can remove from play 1 LIGHT Fairy-Type monster from your Graveyard to select 1 card on the field, and destroy it. If "The Sanctuary in the Sky" is face-up on the field, you can activate this effect up to twice per turn.', '场上存在的1张卡破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34230233,3,0,6,33,2700,1800,8,8,32,262163);
INSERT OR REPLACE INTO "texts" VALUES (34230233, 'Grapha, Dragon Lord of Dark World', 'You can Special Summon this card (from your Graveyard) by returning 1 face-up "Dark World" monster you control to the hand, except "Grapha, Dragon Lord of Dark World". If this card is discarded to the Graveyard by a card effect: Target 1 card your opponent controls; destroy that target, then, if this card was discarded from your hand to your Graveyard by an opponent''s card effect, look at 1 random card in your opponent''s hand, then, if it was a monster, you can Special Summon it to your side of the field.', 'Destroy card on opponent''s field', 'Special Summon another monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8967776,3,0,74,33,4000,4000,10,4,16,271360);
INSERT OR REPLACE INTO "texts" VALUES (8967776, 'Sephylon, the Ultimate Timelord', 'Cannot be Normal Summoned or Set. Must be Special Summoned (from your hand) by having 10 or more monsters in your Graveyard, and cannot be Special Summoned by other ways. Once per turn: You can Special Summon 1 Level 8 or higher Fairy-Type monster from your hand or Graveyard. Its effect(s) are negated, and its ATK becomes 4000.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44665365,3,0,0,161,1800,2800,6,4,16,-2146435061);
INSERT OR REPLACE INTO "texts" VALUES (44665365, 'Herald of Perfection', 'You can Ritual Summon this card with "Dawn of the Herald". During either player''s turn, when your opponent activates a Spell Card, Trap Card, or monster effect: You can send 1 Fairy-Type monster from your hand to the Graveyard; negate the activation, and if you do, destroy it.', '效果怪兽的效果·魔法·陷阱卡的发动无效并破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50321796,3,0,47,8225,2300,1400,6,262144,2,24);
INSERT OR REPLACE INTO "texts" VALUES (50321796, 'Brionac, Dragon of the Ice Barrier', '1 Tuner + 1 or more non-Tuner monsters
You can discard any number of cards to the Graveyard to target the same number of cards from the field; return them to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33198837,3,0,42,8225,2200,1700,5,16384,1,-2147483639);
INSERT OR REPLACE INTO "texts" VALUES (33198837, 'Naturia Beast', '1 EARTH Tuner + 1 or more non-Tuner EARTH monsters 
While this card is face-up on the field, you can send the top 2 cards of your Deck to the Graveyard to negate the activation of a Spell Card and destroy it.', '魔法卡的发动无效并破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2956282,3,0,42,8225,2500,1800,6,8192,1,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (2956282, 'Naturia Barkion', '1 EARTH Tuner + 1 or more non-Tuner EARTH monsters 
While this card is face-up on the field, you can remove from play 2 cards in your Graveyard to negate the activation of a Trap Card and destroy it.', '陷阱卡的发动无效并破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50091196,3,0,23,12321,200,1500,2,32,16,536871168);
INSERT OR REPLACE INTO "texts" VALUES (50091196, 'Formula Synchron', '1 Tuner + 1 non-Tuner monster
When this card is Synchro Summoned, you can draw 1 card. During your opponent''s Main Phase, you can Synchro Summon using this face-up card you control as a Synchro Material Monster.', 'Draw card', '同调召唤', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66976526,3,0,17,8225,2800,1700,8,32,1,262400);
INSERT OR REPLACE INTO "texts" VALUES (66976526, 'Karakuri Steel Shogun mdl 00X "Bureido"', '1 Tuner + 1 or more non-Tuner Machine-Type monsters
When this card is Synchro Summoned, you can Special Summon 1 "Karakuri" monster from your Deck. Once per turn, when the battle position of a face-up "Karakuri" monster you control is changed, draw 1 card.', 'Special Summon', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84013237,3,0,8323144,8388641,2500,2000,4,1,16,65536);
INSERT OR REPLACE INTO "texts" VALUES (84013237, 'Number 39: Utopia', '2 Level 4 monsters
When any player''s monster declares an attack: You can detach 1 Xyz Material from this card; negate the attack. When this card is targeted for an attack, while it has no Xyz Materials: Destroy this card.', 'Negate attack', 'Self Destruct', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53129443,3,0,137,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (53129443, 'Dark Hole', 'Destroy all monsters on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5318639,3,0,0,65538,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (5318639, 'Mystical Space Typhoon', 'Target 1 Spell/Trap Card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2204140,3,0,0,2,0,0,0,0,0,1311748);
INSERT OR REPLACE INTO "texts" VALUES (2204140, 'Book of Life', 'Target 1 Zombie-Type monster in your Graveyard and 1 monster in your opponent''s Graveyard; Special Summon the first target, also banish the second target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4861205,3,0,0,131074,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (4861205, 'Call of the Mummy', 'Once per turn: You can Special Summon 1 Zombie-Type monster from your hand. You must control no monsters to activate and to resolve this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96677818,3,0,4206,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (96677818, 'Spellbook Organization', 'Look at the top 3 cards of your Deck, then return them to the top of the Deck in any order.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68191243,3,0,26,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (68191243, 'Mustering of the Dark Scorpions', 'You can only activate this card when there is a face-up "Don Zaloog"(s) on your side of the field. You can Special Summon from your hand any of the cards that include "Dark Scorpion" in their card name, or are named "Cliff the Trap Remover". (You can only Special Summon up to 1 card with each card name.)', 'Continue Special Summoning?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66835946,3,0,0,131074,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (66835946, 'Pyramid of Wonders', 'All Zombie-Type monsters you control gain 200 ATK for each monster your opponent controls. If exactly 1 Zombie-Type monster you control (and no other cards) would be destroyed, you can send this card to the Graveyard instead.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27383110,3,0,0,130,0,0,0,0,0,263168);
INSERT OR REPLACE INTO "texts" VALUES (27383110, 'Dawn of the Herald', 'This card is used to Ritual Summon "Herald of Perfection". You must also Tribute monsters whose total Levels equal exactly 6 from the field or your hand. When "Herald of Perfection" is Ritual Summoned by this card''s effect, you can remove from play this card in your Graveyard to select 1 of the monsters Tributed for that Ritual Summon, and return it from your Graveyard to your hand.', '一只仪式解放的怪兽回到手卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41420027,3,0,0,1048580,0,0,0,0,0,-2147483645);
INSERT OR REPLACE INTO "texts" VALUES (41420027, 'Solemn Judgment', 'When a monster would be Summoned, OR a Spell/Trap Card is activated: Pay half your Life Points; negate the Summon or activation, and if you do, destroy that card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97077563,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (97077563, 'Call of the Haunted', 'Activate this card by targeting 1 monster in your Graveyard; Special Summon that target in Attack Position. When this card leaves the field, destroy that target. When that target is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63442604,3,0,0,4,0,0,0,0,0,786432);
INSERT OR REPLACE INTO "texts" VALUES (63442604, 'Physical Double', 'During your opponent''s turn: Target 1 face-up monster your opponent controls; Special Summon 1 "Mirage Token" with the same Level, Type, Attribute, ATK, and DEF as that target. Destroy this Token during the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21840375,3,0,4206,4,0,0,0,0,0,32);
INSERT OR REPLACE INTO "texts" VALUES (21840375, 'Hidden Spellbook', 'During your turn: Target 2 Spell Cards in your Graveyard; shuffle those targets into the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79852326,3,0,0,131076,0,0,0,0,0,4456448);
INSERT OR REPLACE INTO "texts" VALUES (79852326, 'Zoma the Spirit', 'Special Summon this card in Defense Position as an Effect Monster (Zombie-Type/DARK/Level 4/ATK 1800/DEF 500). (This card is also still a Trap Card.) If this card is destroyed by battle: Inflict damage to your opponent equal to the ATK of the monster that destroyed it.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28649820,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (28649820, 'Embodiment of Apophis', 'During either player''s Main Phase: Special Summon this card as a Normal Monster (Reptile-Type/EARTH/Level 4/ATK 1600/DEF 1800). (This card is also still a Trap Card.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70406920,3,0,0,131076,0,0,0,0,0,270336);
INSERT OR REPLACE INTO "texts" VALUES (70406920, 'Machine King - 3000 B.C.', 'After activation, Special Summon this card; it is treated as an Effect Monster Card (Machine-Type/EARTH/Level 4/ATK 1000/DEF 1000). You cannot Normal or Special Summon another monster the turn you activate this card. Once per turn, you can Tribute 1 Machine-Type monster to have this card gain ATK equal to the Tributed monster''s ATK, until the End Phase. (This card is still treated as a Trap Card.)', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58120309,3,0,0,4,0,0,0,0,0,-2147221501);
INSERT OR REPLACE INTO "texts" VALUES (58120309, 'Starlight Road', 'Activate only when an effect is activated that would destroy 2 or more cards you control. Negate the effect and destroy that card. Then, you can Special Summon 1 "Stardust Dragon" from your Extra Deck.', 'Do you want to Special Summon?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3129635,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (3129635, 'Tiki Curse', 'Special Summon this card as an Effect Monster (Rock-Type/DARK/Level 4/ATK 1800/DEF 1000). (This card is also still a Trap Card.) While this card is an Effect Monster, if another Trap Card that is a monster battles an opponent''s monster, after damage calculation: Destroy that opponent''s monster.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49514333,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (49514333, 'Tiki Soul', 'Special Summon this card as an Effect Monster (Rock-Type/LIGHT/Level 4/ATK 1000/DEF 1800). (This card is also still a Trap Card.) While this card is an Effect Monster, if another Trap Card you control that is a monster would be destroyed by your opponent''s card (either by battle or by card effect) and sent to your Graveyard, you can Set it in the Spell & Trap Card Zone instead.', 'Activate effect of "Tiki Soul"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21843307,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (21843307, 'Copy Knight', 'When a Level 4 or lower Warrior-Type monster is Normal Summoned to your side of the field: Special Summon this card as a Normal Monster Card with the same name and Level as the Normal Summoned monster (Warrior-Type/LIGHT/ATK 0/DEF 0). (This card is still treated as a Trap Card.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
