BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (54455435,3,0,16,33,1000,400,2,1048576,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (54455435, 'Winda, Priestess of Gusto', 'When this card is destroyed by battle with an opponent''s attacking monster and sent to your Graveyard: You can Special Summon 1 "Gusto" Tuner monster from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47658964,3,0,0,65538,0,0,0,0,0,262148);
INSERT OR REPLACE INTO "texts" VALUES (47658964, 'Searing Fire Wall', 'Banish any number of "Laval" monsters from your Graveyard; Special Summon an equal number of "Laval Tokens" (Pyro-Type/FIRE/Level 1/ATK 0/DEF 0) in Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54620698,3,0,4167,17,1600,1800,4,4096,1,0);
INSERT OR REPLACE INTO "texts" VALUES (54620698, 'Gem-Knight Tourmaline', 'He channels mystic energies and changes them into fighting strength through the power of Tourmaline. Many admire his way of life.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76614340,3,0,4167,97,2500,1300,6,128,1,24584);
INSERT OR REPLACE INTO "texts" VALUES (76614340, 'Gem-Knight Ruby', '"Gem-Knight Garnet" + 1 "Gem-Knight" monster
Must first be Fusion Summoned with the above Fusion Material Monsters. Once per turn: You can Tribute 1 face-up "Gem-" monster; this card gains ATK equal to the Tributed monster''s ATK on the field, until the End Phase. If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91449144,3,0,16,33,1700,1100,4,1048576,8,1280);
INSERT OR REPLACE INTO "texts" VALUES (91449144, 'Caam, Serenity of Gusto', 'Once per turn: You can shuffle 2 "Gusto" monsters from your Graveyard into the Main Deck; draw 1 card.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74657662,3,0,48,262146,0,0,0,0,0,8704);
INSERT OR REPLACE INTO "texts" VALUES (74657662, 'Vylon Material', 'Equip only to a "Vylon" monster. It gains 600 ATK. If this face-up card is sent from the field to the Graveyard: You can add 1 "Vylon" Spell Card from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90019393,3,0,4167,33,1800,1200,4,256,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (90019393, 'Gem-Knight Alexandrite', 'You can Tribute this card; Special Summon 1 "Gem-Knight" Normal Monster from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13108445,3,0,4167,97,1400,2600,6,64,1,2064);
INSERT OR REPLACE INTO "texts" VALUES (13108445, 'Gem-Knight Aquamarine', '"Gem-Knight Sapphire" + 1 "Gem-Knight" monster
Must first be Fusion Summoned with the above Fusion Material Monsters. If this card attacks, it is changed to Defense Position at the end of the Battle Phase. When this card is sent from the field to the Graveyard: Target 1 card your opponent controls; return that target to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27944249,3,0,16,33,2000,1000,6,1048576,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (27944249, 'Windaar, Sage of Gusto', 'When this card destroys a monster by battle and sends it to the Graveyard: You can target 1 Level 3 or lower "Gusto" monster in your Graveyard; Special Summon that target in face-up Defense Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46159582,3,0,58,130,0,0,0,0,0,1080);
INSERT OR REPLACE INTO "texts" VALUES (46159582, 'Gishki Aquamirror', 'This card can be used to Ritual Summon any "Gishki" Ritual Monster. You must also Tribute monsters from the field or your hand whose total Levels equal the Level of the Ritual Monster you Ritual Summon. You can shuffle this card from the Graveyard into the Deck to target 1 "Gishki" Ritual Monster in your Graveyard; return that target to your hand.', '墓地的仪式怪兽回到手卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27004302,3,0,71,33,1700,500,4,256,1,512);
INSERT OR REPLACE INTO "texts" VALUES (27004302, 'Gem-Armadillo', 'When this card is Normal Summoned: You can add 1 "Gem-Knight" monster from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49597193,3,0,4167,97,1800,1800,6,4096,1,4227072);
INSERT OR REPLACE INTO "texts" VALUES (49597193, 'Gem-Knight Topaz', '"Gem-Knight Tourmaline" + 1 "Gem-Knight" monster
Must first be Fusion Summoned with the above Fusion Material Monsters. This card can attack twice during each Battle Phase. When this card destroys a monster by battle and sends it to the Graveyard: Inflict damage to your opponent equal to the ATK of the destroyed monster in the Graveyard.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54338958,3,0,4106,33,0,0,1,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (54338958, 'Steelswarm Cell', 'If you control no monsters, you can Special Summon this card (from your hand). While this card is face-up on the field, it cannot be Tributed, except for the Tribute Summon of a "Steelswarm" monster, and cannot be used as a Synchro Material Monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83544697,3,0,16,2,0,0,0,0,0,1026);
INSERT OR REPLACE INTO "texts" VALUES (83544697, 'Contact with Gusto', 'Target 2 "Gusto" monsters in your Graveyard and 1 card your opponent controls; shuffle both targets in your Graveyard into the Deck, then destroy the opponent''s target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53408006,3,0,71,33,1000,1000,3,2,1,8200);
INSERT OR REPLACE INTO "texts" VALUES (53408006, 'Gem-Merchant', 'During the Damage Step, in either player''s turn, when a face-up EARTH Normal Monster you control attacks or is attacked: You can send this card from your hand to the Graveyard; that monster gains 1000 ATK and DEF until the End Phase.', 'Increase ATK and DEF', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75991898,3,0,57,8225,2000,1100,5,8192,4,1072);
INSERT OR REPLACE INTO "texts" VALUES (75991898, 'Lavalval Dragon', '1 Tuner + 1 or more non-Tuner FIRE monsters.
 You can shuffle 2 "Laval" monsters from your Graveyard into your Main Deck to target 1 card your opponent controls; return it to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90727556,3,0,4106,33,200,0,1,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (90727556, 'Steelswarm Scout', 'At the start of your Main Phase 1, if you control no Spell/Trap Cards: You can Special Summon this card from your Graveyard. You cannot Special Summon another monster(s) the turn you activate this effect. While this card is face-up on the field, it cannot be Tributed, expect for the Tribute Summon of a "Steelswarm" monster, and cannot be used as a Synchro Material Monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19932396,3,0,101,65538,0,0,0,0,0,272);
INSERT OR REPLACE INTO "texts" VALUES (19932396, 'First Step Towards Infestation', 'Return 1 face-up Tribute Summoned "Steelswarm" monster you control to the hand; draw 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89893715,3,0,57,33,300,400,3,128,4,8);
INSERT OR REPLACE INTO "texts" VALUES (89893715, 'Laval Miller', 'When this card is destroyed by battle and sent to the Graveyard: You can send 2 "Laval" monsters from your Deck to the Graveyard.', 'Send to Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12986807,3,0,57,8225,2400,800,6,1,4,16777228);
INSERT OR REPLACE INTO "texts" VALUES (12986807, 'Laval the Greater', '1 Tuner + 1 or more non-Tuner FIRE monsters
When this card is Synchro Summoned: Send 1 card from your hand to the Graveyard. If this card would be destroyed by a card effect, you can banish 1 "Laval" monster from your Graveyard instead.', 'Send 1 card from Hand to Graveyard', 'Banish 1 "Laval" monster from your Graveyard to avoid destruction?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48370501,3,0,48,8225,1800,1000,7,4,16,66048);
INSERT OR REPLACE INTO "texts" VALUES (48370501, 'Vylon Sigma', '1 LIGHT Tuner + 1 or more non-Tuner LIGHT monsters
 When this card declares an attack, if it is the only monster you control: You can equip 1 Equip Spell Card from your Deck to this face-up card.', 'Equip', 'Please select equip Spell Card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26722601,3,0,4106,33,1500,1900,4,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (26722601, 'Steelswarm Gatekeeper', 'If a "Steelswarm" monster is Tribute Summoned face-up while this card is face-up on the field, you can Normal Summon or Set 1 monster in addition to your Normal Summon or Set that turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26381750,3,0,0,4129,100,0,1,512,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (26381750, 'Soaring Eagle Above the Searing Land', 'If this card is sent to the Graveyard for a Synchro Summon: You can Special Summon this card. You must have 3 or more "Laval" monsters with different names in your Graveyard to activate and to resolve this effect. If this card is Special Summoned with this effect, banish it when it leaves the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75779210,3,0,48,8225,2800,1200,8,4,16,33554442);
INSERT OR REPLACE INTO "texts" VALUES (75779210, 'Vylon Epsilon', '1 LIGHT Tuner + 1 or more non-Tuner monsters
Equip Cards equipped to this card cannot be targeted by cards or effects. Once per turn: You can send 1 Equip Card equipped to this card to the Graveyard to target 1 monster your opponent controls; destroy that target.', '对方场上的1只怪兽破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53116300,3,0,4106,33,1700,0,4,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (53116300, 'Steelswarm Caller', 'When a "Steelswarm" monster is Tribute Summoned face-up by Tributing this card: You can Special Summon 1 Level 4 or lower "Steelswarm" monster from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52786469,3,0,57,33,1800,500,4,1,4,4194304);
INSERT OR REPLACE INTO "texts" VALUES (52786469, 'Laval Warrior', 'When this card destroys an opponent''s monster by battle: Inflict damage to your opponent equal to the original ATK of the destroyed monster. You must have 4 or more "Laval" monsters with different names in your Graveyard to activate and to resolve this effect.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67111213,3,0,7667770,33,800,500,2,131072,2,512);
INSERT OR REPLACE INTO "texts" VALUES (67111213, 'Gishki Abyss', 'When this card is Summoned: You can add 1 "Gishki" monster with 1000 or less DEF from your Deck to your hand, except "Gishki Abyss".', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85505315,3,0,4106,33,2200,0,5,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (85505315, 'Steelswarm Mantis', 'When this card is Tribute Summoned by Tributing a "Steelswarm" monster: You can pay 1000 Life Points to target 1 "Steelswarm" monster in your Graveyard; Special Summon that target.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89770167,3,0,0,33,1800,600,4,32768,4,8196);
INSERT OR REPLACE INTO "texts" VALUES (89770167, 'Prominence, Molten Swordsman', 'Once per turn, during either player''s turn: You can banish 1 "Laval" monster from your Graveyard; this card gains 300 ATK until the End Phase.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93506862,3,0,58,33,1000,800,2,64,2,8);
INSERT OR REPLACE INTO "texts" VALUES (93506862, 'Gishki Vanity', 'During your Main Phase: You can discard this card; this turn, your opponent cannot activate Spells, Traps, Spell/Trap effects, or Monster Card effects when a "Gishki" monster is Ritual Summoned, or when a "Gishki" Ritual Spell Card is activated.', '发动限制', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22009013,3,0,4106,33,2400,0,6,8,32,16);
INSERT OR REPLACE INTO "texts" VALUES (22009013, 'Steelswarm Moth', 'When this card is Tribute Summoned by Tributing 1 "Steelswarm" monster: You can pay 1000 Life Points to target up to 2 cards your opponent controls; return those targets to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15169262,3,0,57,4129,300,200,2,128,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (15169262, 'Laval Forest Sprite', 'When this card is sent from the field to the Graveyard: All face-up "Laval" monsters you currently control gain 200 ATK for each "Laval" monster in your Graveyard, until the End Phase.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39905966,3,0,58,33,1600,1200,4,64,2,1040);
INSERT OR REPLACE INTO "texts" VALUES (39905966, 'Gishki Marker', 'When this card is Summoned: You can target 1 "Gishki" Ritual Monster or "Gishki" Ritual Spell Card in your Graveyard; add that target to your hand.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58494728,3,0,4106,33,2600,0,7,8,32,8388616);
INSERT OR REPLACE INTO "texts" VALUES (58494728, 'Steelswarm Girastag', 'You can Tribute Summon this card in face-up Attack Position by Tributing 1 "Steelswarm" monster. When this card is Tribute Summoned by Tributing a "Steelswarm" monster(s): You can target 1 card your opponent controls; send that target to the Graveyard and gain 1000 Life Points.', 'Tribute 1 monster to Tribute Summon this card', 'Send to Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41777,3,0,71,4,0,0,0,0,0,263168);
INSERT OR REPLACE INTO "texts" VALUES (41777, 'Gem-Enhancement', 'Tribute 1 "Gem-Knight" monster, then target 1 "Gem-Knight" monster in your Graveyard; Special Summon that target from the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51554871,3,0,0,33,1200,200,3,256,4,8196);
INSERT OR REPLACE INTO "texts" VALUES (51554871, 'Kayenn, the Master Magma Blacksmith', 'You can banish this card from your Graveyard; all face-up "Laval" monsters you currently control gain 400 ATK.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66399675,3,0,58,33,1800,1000,4,262144,2,512);
INSERT OR REPLACE INTO "texts" VALUES (66399675, 'Gishki Chain', 'When this card is Normal Summoned: Look at the top 3 cards of your Deck. If there is a Ritual Monster(s) or Ritual Spell Card(s), you can reveal one of them to your opponent and add it to your hand. Then return the other cards to your Deck in the order of your choice.', 'Confirm card group', 'Reveal a Ritual Monster of Ritual Spell card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84488827,3,0,4106,33,2800,0,8,8,32,3);
INSERT OR REPLACE INTO "texts" VALUES (84488827, 'Steelswarm Caucastag', 'When this card is Tribute Summoned by Tributing 2 "Steelswarm" monsters: Activate 1 of these effects. 
● Destroy all monsters on the field, except this card. 
● Destroy all Spell and Trap Cards on the field.', 'Select effect', 'Destroy all monsters on the field, except this card. ', 'Destroy all Spell and Trap Cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37436476,3,0,0,131076,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (37436476, 'Molten Whirlwind Wall', 'All face-up "Laval" monsters you control gain 100 ATK for each "Laval" monster in your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88958576,3,0,57,33,2100,1000,5,128,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (88958576, 'Laval Burner', 'If you have 3 or more "Laval" monsters with different names in your Graveyard, you can Special Summon this card (from your hand).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92784374,3,0,58,2097185,1000,1800,4,2,2,512);
INSERT OR REPLACE INTO "texts" VALUES (92784374, 'Gishki Ariel', 'FLIP: You can add 1 "Gishki" monster from your Deck to your hand.', 'Add to hand', 'Add 1 "Gishki" monster from your Deck to your hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11877465,3,0,58,161,2500,2000,6,64,2,32);
INSERT OR REPLACE INTO "texts" VALUES (11877465, 'Evigishki Mind Augus', 'Cannot be Normal Summoned or Set. Must first be Ritual Summoned. You can Ritual Summon this card with any "Gishki" Ritual Spell Card. When this card is Ritual Summoned: Target up to 5 cards in any Graveyard(s); shuffle those targets to the Deck.', 'Return to deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46337945,3,0,0,4,0,0,0,0,0,1040);
INSERT OR REPLACE INTO "texts" VALUES (46337945, 'Aquamirror Meditation', 'Reveal 1 Ritual Spell Card in your hand to target 2 "Gishki" monsters in your Graveyard; return them to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14047624,3,0,57,33,2700,1800,7,1,4,4194304);
INSERT OR REPLACE INTO "texts" VALUES (14047624, 'Laval Judgment Lord', 'Once per turn: You can banish 1 "Laval" monster from your Graveyard; inflict 1000 damage to your opponent. "Laval Judgment Lord" cannot declare an attack the turn this effect is activated.', '给与对方1000伤害', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29888389,3,0,58,33,1200,1000,4,262144,2,2097664);
INSERT OR REPLACE INTO "texts" VALUES (29888389, 'Gishki Shadow', 'If you Ritual Summon a WATER Ritual Monster, this card can be used as the entire Tribute. You can discard this card; add 1 "Gishki" Ritual Spell Card from your Deck to your hand.', '仪式魔法卡加入手卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57272170,3,0,58,161,2800,2800,8,64,2,40);
INSERT OR REPLACE INTO "texts" VALUES (57272170, 'Evigishki Soul Ogre', 'Cannot be Normal Summoned or Set. Must first be Ritual Summoned. You can Ritual Summon this card with any "Gishki" Ritual Spell Card. Once per turn: You can discard 1 "Gishki" monster to target 1 face-up card your opponent controls; shuffle that target into the Deck.', 'Return to deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82422049,3,0,16,4,0,0,0,0,0,263200);
INSERT OR REPLACE INTO "texts" VALUES (82422049, 'Blessings for Gusto', 'Target 2 "Gusto" monsters in your Graveyard, plus a third "Gusto" monster in your Graveyard; shuffle both of the first 2 targets into your Deck, then Special Summon the third target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41431329,3,0,48,4129,800,800,3,32,16,2097664);
INSERT OR REPLACE INTO "texts" VALUES (41431329, 'Vylon Cube', 'If this card is sent to the Graveyard for the Synchro Summon of a LIGHT monster: You can add 1 Equip Spell Card from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65277087,3,0,16,4129,500,500,3,512,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (65277087, 'Gusto Gulldo', 'When this card is sent from the field to the Graveyard: You can Special Summon 1 Level 2 or lower "Gusto" monster from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84766279,3,0,16,8225,2200,800,5,1048576,8,1026);
INSERT OR REPLACE INTO "texts" VALUES (84766279, 'Daigusto Gulldos', '1 Tuner + 1 or more non-Tuner "Gusto" monsters
Once per turn: You can shuffle 2 "Gusto" monsters from your Graveyard into the Main Deck to target 1 face-up monster your opponent controls; destroy that target.', '对方场上表侧表示存在的1只怪兽破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18816758,3,0,101,4,0,0,0,0,0,19);
INSERT OR REPLACE INTO "texts" VALUES (18816758, 'Infestation Wave', 'Return 1 face-up Tribute Summoned "Steelswarm" monster you control to the hand to target 1 card your opponent controls; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87836938,3,0,48,33,1400,1000,4,4,16,256);
INSERT OR REPLACE INTO "texts" VALUES (87836938, 'Vylon Vanguard', 'When this card is destroyed by a card effect and sent to the Graveyard: You can draw 1 card for each Equip Card that was equipped to this card.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91662792,3,0,16,4129,200,400,1,512,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (91662792, 'Gusto Egul', 'When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 Level 4 or lower non-Tuner "Gusto" monster from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10755984,3,0,16,8225,2600,1800,7,1048576,8,2097159);
INSERT OR REPLACE INTO "texts" VALUES (10755984, 'Daigusto Eguls', '1 Tuner + 1 or more non-Tuner "Gusto" monsters
Once per turn, during your End Phase: You can banish 1 WIND monster from your Graveyard to target 1 face-down card your opponent controls; destroy that target.', '场上里侧表示存在的1张卡破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91731841,3,0,4167,17,1900,0,4,128,1,0);
INSERT OR REPLACE INTO "texts" VALUES (91731841, 'Gem-Knight Garnet', 'The Gem-Knight Warrior who carries the Garnet Soul. His Flaming Iron Fist crushes all enemies.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13220032,3,0,48,33,1000,1000,4,4,16,2105344);
INSERT OR REPLACE INTO "texts" VALUES (13220032, 'Vylon Charger', 'All face-up LIGHT monsters you control gain 300 ATK for each Equip Card equipped to this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28066831,3,0,16,33,1500,1200,4,4096,8,262148);
INSERT OR REPLACE INTO "texts" VALUES (28066831, 'Gusto Thunbolt', 'At the end of the Battle Phase, if this card is in the Graveyard because it was destroyed by battle and sent to the Graveyard this turn: You can banish 1 "Gusto" monster from your Graveyard; Special Summon 1 WIND Psychic-Type monster with 1500 or less DEF from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1264319,3,0,4591687,2,0,0,0,0,0,268698624);
INSERT OR REPLACE INTO "texts" VALUES (1264319, 'Gem-Knight Fusion', 'Send, from your hand or your side of the field to the Graveyard, the Fusion Material Monsters that are listed on a "Gem-Knight" Fusion Monster Card, then Special Summon that Fusion Monster from the Extra Deck. (This Special Summon is treated as a Fusion Summon.) If this card is in the Graveyard: You can banish 1 "Gem-Knight" monster from your Graveyard; add this card to your hand.', 'Add card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27126980,3,0,4167,17,0,2100,4,64,1,0);
INSERT OR REPLACE INTO "texts" VALUES (27126980, 'Gem-Knight Sapphire', 'His Sapphire power commands the waters to protect him from attack. His comrades trust in his silent protection.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40619741,3,0,48,33,1700,1000,4,4,16,2048);
INSERT OR REPLACE INTO "texts" VALUES (40619741, 'Vylon Soldier', 'When this card declares an attack: You can target monsters your opponent controls, up to the number of Equip Cards equipped to this card; change those targets'' battle positions.', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
