BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (76908448,3,0,4167,17,2450,1950,7,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (76908448, 'Gem-Knight Crystal', 'A Gem-Knight officer of high rank, who has optimized the use of the crystal powers. Despite his ability to overwhelm most opponents, he''s wary of stretching himself too thin, and opts for solidarity with his comrades.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2407147,3,0,57,4129,100,200,1,128,4,8);
INSERT OR REPLACE INTO "texts" VALUES (2407147, 'Laval Volcano Handmaiden', 'When this card is sent to the Graveyard while a "Laval" monster, except "Tender of the Laval Volcano", is in your Graveyard: You can send 1 "Laval" monster from your Deck to the Graveyard.', 'Send to Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38492752,3,0,57,33,1600,900,4,1,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (38492752, 'Laval Cannon', 'When this card is Normal or Flip Summoned: You can target 1 of your banished "Laval" monsters; Special Summon it.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75886890,3,0,48,4129,400,400,1,32,16,1032);
INSERT OR REPLACE INTO "texts" VALUES (75886890, 'Vylon Sphere', 'If this card is sent from the Monster Card Zone to the Graveyard: You can pay 500 Life Points; equip it to 1 face-up monster you control. You can send this card equipped to a monster to the Graveyard to target 1 Equip Spell Card in your Graveyard; equip the target to the monster equipped with this card.', 'Become equip card', 'Select 1 Equip Spell Card', 'Please select 1 Equip Spell Card', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1281505,3,0,48,4129,900,900,2,32,16,16778240);
INSERT OR REPLACE INTO "texts" VALUES (1281505, 'Vylon Tetra', 'If this card is sent from the Monster Card Zone to the Graveyard: You can pay 500 Life Points, then target 1 face-up monster you control; equip this card to that target. If the equipped monster would be destroyed, you can destroy this Equip Card instead.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38679204,3,0,48,4129,1400,200,3,4,16,2);
INSERT OR REPLACE INTO "texts" VALUES (38679204, 'Vylon Stella', 'If this card is sent from the Monster Card Zone to the Graveyard: You can pay 500 Life Points, then target 1 face-up monster you control; equip this card to that target. At the end of the Damage Step, if the equipped monster battled an opponent''s monster: Destroy that opponent''s monster.', 'Become equip card', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74064212,3,0,48,4129,1500,1500,4,4096,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (74064212, 'Vylon Prism', 'If this card is sent from the Monster Card Zone to the Graveyard: You can pay 500 Life Points, then target 1 face-up monster you control; equip this card to that target. If the equipped monster attacks or is attacked: It gains 1000 ATK during the Damage Step only.', 'Become equip card', 'Become equip card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (168917,3,0,48,33,1800,800,4,4,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (168917, 'Vylon Hept', 'Once per turn: You can target 1 face-up "Vylon" monster you control treated as an Equip Card; Special Summon it in face-up Defense Position. When that monster leaves the field, banish it.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37557626,3,0,58,33,500,800,2,64,2,16);
INSERT OR REPLACE INTO "texts" VALUES (37557626, 'Gishki Reliever', 'When this card is Normal or Flip Summoned while you control another face-up "Gishki" monster: You can target 1 monster you control, except this card; return it to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63942761,3,0,58,33,1700,1000,4,2,2,8);
INSERT OR REPLACE INTO "texts" VALUES (63942761, 'Gishki Noellia', 'When this card is Normal Summoned: Reveal the top 5 cards from your Deck. If there is a Ritual Spell Card or "Gishki" monster among these cards, send them to the Graveyard, and return the other cards to the bottom of your Deck in any order.', '卡组确认', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (336369,3,0,16,4129,0,1800,2,4096,8,262656);
INSERT OR REPLACE INTO "texts" VALUES (336369, 'Gusto Squirro', 'When this card is destroyed by a card effect and sent to the Graveyard: You can Special Summon 1 Level 5 or higher "Gusto" monster from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36331074,3,0,16,33,1900,1400,5,1048576,8,4128);
INSERT OR REPLACE INTO "texts" VALUES (36331074, 'Reeze, Whirlwind of Gusto', 'Once per turn: You can shuffle 1 card from your hand into the bottom of the Deck to target 1 monster your opponent controls and 1 face-up "Gusto" monster you control, and switch control of those targets.', '控制权交换', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62729173,3,0,4106,33,1000,0,2,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (62729173, 'Steelswarm Genome', 'If this card is used to Tribute Summon a "Steelswarm" monster, this card can be treated as 2 Tributes.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99214782,3,0,4106,33,1100,0,3,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (99214782, 'Steelswarm Sentinel', 'While this card is in face-up Attack Position, Level 5 or higher Special Summoned monsters on the field cannot activate their effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35618486,3,0,4106,33,1850,0,4,8,32,805306370);
INSERT OR REPLACE INTO "texts" VALUES (35618486, 'Steelswarm Sting', 'When this card you control is sent to the Graveyard: Target 1 face-up Ritual, Fusion, or Synchro Monster on the field; destroy it.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62007535,3,0,4106,33,3000,0,9,8,32,2);
INSERT OR REPLACE INTO "texts" VALUES (62007535, 'Steelswarm Longhorn', 'If you Tribute Summon this card by Tributing a "Steelswarm" monster(s): It gains this effect: Once per turn: You can pay 1000 Life Points to target 1 monster on the field; destroy it.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94092230,3,0,4106,33,3200,0,10,8,32,3);
INSERT OR REPLACE INTO "texts" VALUES (94092230, 'Steelswarm Hercules', 'Cannot be Special Summoned. You must Tribute 3 "Steelswarm" monsters to Normal Summon this card (you cannot Set this card). Once per turn: You can pay half your Life Points; destroy all other cards on the field.', 'Tribute 3 "Steelswarm" monsters to Normal Summon this card', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21496848,3,0,58,161,2600,2100,6,64,2,520);
INSERT OR REPLACE INTO "texts" VALUES (21496848, 'Evigishki Tetrogre', 'Cannot be Normal Summon or Set. Must first be Special Summoned by Ritual Summoning with any "Gishki" Ritual Spell Card. Once per turn: You can declare a card type (Monster, Spell, or Trap); each player must send 1 card of the declared type from their Deck to the Graveyard. Your opponent can discard 1 card from their hand to negate this card''s effect.', 'Declare card type to send to Graveyard', 'Monster card', 'Spell card', 'Trap card', 'Negate "Evigishki Tetrogre" effect by discarding a card from your hand?', 'Declare the Type', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67985943,3,0,4167,97,2200,1950,7,128,1,0);
INSERT OR REPLACE INTO "texts" VALUES (67985943, 'Gem-Knight Citrine', '1 "Gem-Knight" monster + 1 Pyro-Type monster
Must first be Fusion Summoned. If this card attacks or is attacked, your opponent cannot activate cards or effects until the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93379652,3,0,4167,97,2450,1400,7,4096,1,11);
INSERT OR REPLACE INTO "texts" VALUES (93379652, 'Gem-Knight Prismaura', '1 "Gem-Knight" monster + 1 Thunder-Type monster
Must first be Fusion Summoned. Once per turn: You can send 1 "Gem-Knight" card from your hand to the Graveyard to target 1 face-up card on the field; destroy that target.', '表侧表示的1张卡破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20374351,3,0,57,8225,2700,1800,7,128,4,-2147483581);
INSERT OR REPLACE INTO "texts" VALUES (20374351, 'Laval Stennon', '1 Tuner + 1 or more non-Tuner FIRE monsters
When this card is Synchro Summoned: Send 1 card from your hand to the Graveyard. When this card is targeted by a card effect: You can banish 1 "Laval" monster in your Graveyard; negate its activation, and destroy that card.', '把1张手卡送去墓地', '效果发动无效并破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56768355,3,0,48,8225,2200,1100,9,32,16,16778240);
INSERT OR REPLACE INTO "texts" VALUES (56768355, 'Vylon Alpha', '1 "Vylon" Tuner + 1 or more non-Tuner monsters
When this card is Synchro Summoned: Target 1 Equip Spell Card in your Graveyard; equip it to this card. While this card is equipped with an Equip Card, this card cannot be destroyed by the effects of Spell/Trap Cards, except Equip Cards.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93157004,3,0,48,8225,3200,1900,10,4,16,-2147483646);
INSERT OR REPLACE INTO "texts" VALUES (93157004, 'Vylon Omega', '2 Tuners + 1 non-Tuner "Vylon" monster
When this card is Synchro Summoned: Destroy all face-up Normal Summoned monsters on the field. Once per turn: You can target 1 "Vylon" monster in your Graveyard; equip it to this card. When the effect of an Effect Monster is activated: You can send 1 Equip Card equipped to this card to the Graveyard; negate that activation, and destroy that monster.', '通常召唤的怪兽全部破坏', 'Equip', '效果怪兽的效果发动无效并破坏', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29552709,3,0,16,8225,2000,1300,6,1048576,8,16778240);
INSERT OR REPLACE INTO "texts" VALUES (29552709, 'Daigusto Sphreeze', '1 Tuner + 1 or more non-Tuner "Gusto" monsters
 When this card is Synchro Summoned: You can add 1 "Gusto" card from your Graveyard to your hand. Your opponent takes all Battle Damage you would take from battles involving "Gusto" monsters you control. This card cannot be destroyed by battle.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55046718,3,0,48,262146,0,0,0,0,0,16896);
INSERT OR REPLACE INTO "texts" VALUES (55046718, 'Vylon Component', 'Equip only to a "Vylon" monster. During battle between that equipped monster and a Defense Position, inflict piercing Battle Damage to your opponent. If this face-up card is sent to the Graveyard: You can add 1 "Vylon" Spell Card from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92035412,3,0,48,131074,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (92035412, 'Vylon Element', 'When a face-up "Vylon" Equip Card(s) you control is destroyed: You can Special Summon "Vylon" Tuner monsters from your Deck up to the number of Equip Cards destroyed. The Special Summoned monster(s) can only be used as a Synchro Material Monster for the Synchro Summon of a "Vylon" monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28429121,3,0,58,130,0,0,0,0,0,335872);
INSERT OR REPLACE INTO "texts" VALUES (28429121, 'Forbidden Arts of the Gishki', 'This card is used to Ritual Summon a "Gishki" Ritual Monster. You must also Tribute monsters from either side of the field whose total Levels are equal to the Level of the Ritual Monster you are attempting to Ritual Summon. The ATK of the monster Ritual Summoned by this effect is halved. You cannot conduct your Battle Phase during the same turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55824220,3,0,70,4,0,0,0,0,0,268697600);
INSERT OR REPLACE INTO "texts" VALUES (55824220, 'Pyroxene Fusion', 'Send, from your hand or side of the field to your Graveyard, Fusion Material Monsters listed on a "Gem-Knight" Fusion Monster Card, and Special Summon that monster from your Extra Deck (This Special Summon is treated as a Fusion Summon).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81218874,3,0,101,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (81218874, 'Infestation Ripples', 'Pay 500 Life Points to target 1 Level 4 or lower "Steelswarm" monster in your Graveyard; Special Summon it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27207573,3,0,101,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (27207573, 'Infestation Tool', 'Send 1 "Steelswarm" monster from your Deck to the Graveyard to target 1 face-up "Steelswarm" monster you control; that target gains 800 ATK until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19163116,3,0,4167,33,1500,1200,3,256,1,263168);
INSERT OR REPLACE INTO "texts" VALUES (19163116, 'Gem-Knight Obsidian', 'If this card is sent from the hand to your Graveyard: You can target 1 Level 4 or lower Normal Monster in your Graveyard; Special Summon that target.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45662855,3,0,4167,2081,1300,2000,4,64,1,1044);
INSERT OR REPLACE INTO "texts" VALUES (45662855, 'Gem-Knight Iolite', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect:
● Once per turn: You can banish 1 "Gem" monster from your Graveyard to target 1 "Gem-Knight" card in your Graveyard; add that target to your hand.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72056560,3,0,4167,2081,1600,1400,4,4096,1,1048);
INSERT OR REPLACE INTO "texts" VALUES (72056560, 'Gem-Knight Amber', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect:
● Once per turn: You can discard 1 "Gem-Knight" card; add 1 of your banished monsters to your hand.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8041569,3,0,57,4129,200,200,3,128,4,3);
INSERT OR REPLACE INTO "texts" VALUES (8041569, 'Laval Lakeside Lady', 'If there are 3 or more different "Laval" monsters in your Graveyard: You can banish 1 "Laval" monster and this card from your Graveyard to target 1 Set card your opponent controls; destroy that card.', '对方场上盖放的1张卡破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45439263,3,0,57,4129,1300,700,2,128,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (45439263, 'Laval Coatl', 'If you have 3 or more different "Laval" monsters in your Graveyard, you can Special Summon this card from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11834972,3,0,57,33,1200,800,4,1,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (11834972, 'Laval Blaster', 'When this card is Normal Summoned while you have a "Laval" monster in your Graveyard, except "Laval Gunner": You can send the top 5 cards of your Deck to the Graveyard, then this card gains 200 ATK for each "Laval" monster sent to the Graveyard by this effect.', 'Gain attack', 'Select number of cards to send to Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47228077,3,0,48,1057,500,400,4,32,16,262147);
INSERT OR REPLACE INTO "texts" VALUES (47228077, 'Vylon Pentachloro', 'Once per turn, during your Main Phase: You can equip this card to a face-up "Vylon" monster you control, OR unequip it to Special Summon this card in face-up Attack Position. While this card is equipped to a monster, if the equipped monster destroys an opponent''s monster by battle: You can target 1 card your opponent controls; destroy it. (A monster can only be equipped with 1 Union Monster at a time. If the equipped monster would be destroyed, destroy this card instead.)', '变成装备卡', 'Special Summon', '对方场上的1张卡破坏', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84313685,3,0,48,1057,800,600,4,32,16,17039360);
INSERT OR REPLACE INTO "texts" VALUES (84313685, 'Vylon Tesseract', 'Once per turn, during your Main Phase: You can equip this card to a face-up "Vylon" monster you control, OR unequip it to Special Summon this card in face-up Attack Position. While equipped to a monster by this effect, if the equipped monster destroys an opponent''s monster by battle: You can Special Summon 1 Level 4 or lower "Vylon" monster from your Graveyard. (A monster can only be equipped with 1 Union Monster at a time. If the equipped monster would be destroyed, destroy this card instead.)', '变成装备卡', 'Special Summon', '墓地特殊召唤', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10712320,3,0,48,33,1600,1000,4,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (10712320, 'Vylon Stigma', 'Once per turn, during either player''s turn: You can target 1 face-up "Vylon" Equip Card; unequip it, and equip it to another appropriate monster.', '装备转移', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47106439,3,0,58,33,700,500,2,262144,2,2097672);
INSERT OR REPLACE INTO "texts" VALUES (47106439, 'Gishki Vision', 'If you Ritual Summon a WATER Ritual Monster, this 1 card can be used as the entire Tribute. You can discard this card; add 1 "Gishki" Ritual Monster from your Deck to your hand.', '仪式怪兽加入手卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73551138,3,0,58,545,1600,800,4,2,2,-2147482608);
INSERT OR REPLACE INTO "texts" VALUES (73551138, 'Gishki Emilia', 'Cannot be Special Summoned. This card returns to the hand during the End Phase of the turn it is Normal Summoned or flipped face-up. If this card is Normal Summoned or flipped face-up while you control another face-up "Gishki" monster: Negate the effects of Trap Cards on the field, until the End Phase.', 'Return to hand', 'Negate Trap cards', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19959742,3,0,58,33,1700,900,4,64,2,0);
INSERT OR REPLACE INTO "texts" VALUES (19959742, 'Gishki Mollusk', 'When this card is sent to the Graveyard by a card effect: Reveal the top 3 cards of your Deck, and return them to the top or bottom of your Deck in any order.', '卡组确认', '回到卡组最上面', '回到卡组最下面', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46044841,3,0,16,4129,600,1400,2,512,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (46044841, 'Gusto Falco', 'When this face-up card on the field is sent to the Graveyard, except when destroyed by battle: You can Special Summon 1 "Gusto" monster from your Deck in face-down Defense Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72439556,3,0,16,2097185,200,1000,2,1048576,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (72439556, 'Kamui, Hope of Gusto', 'FLIP: Special Summon 1 "Gusto" Tuner monster from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9837195,3,0,16,33,1800,900,4,1048576,8,-2147483616);
INSERT OR REPLACE INTO "texts" VALUES (9837195, 'Musto, Oracle of Gusto', 'Once per turn: Target 1 "Gusto" monster in your Graveyard and 1 face-up monster on the field; shuffle the target from your Graveyard into the Deck and negate the effect(s) of the target on the field, until the End Phase.', 'Negate effect', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45222299,3,0,58,161,2400,1000,6,64,2,32);
INSERT OR REPLACE INTO "texts" VALUES (45222299, 'Evigishki Gustkraken', 'Cannot be Normal Summoned or Set. Must first be Ritual Summoned. You can Ritual Summon this card with any "Gishki" Ritual Spell Card. When this card is Ritual Summoned: Look at up to 2 random cards in your opponent''s hand, and shuffle 1 of them into the Deck.', '确认手卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71616908,3,0,4167,97,1950,2450,7,64,1,16);
INSERT OR REPLACE INTO "texts" VALUES (71616908, 'Gem-Knight Amethyst', '1 "Gem-Knight" monster + 1 Aqua-Type monster
Must first be Fusion Summoned. When this card is sent from the field to the Graveyard: Return all Set Spell and Trap Cards on the field to the hand.', 'Return all Set Spell & Trap Cards on the field to the hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8611007,3,0,57,8225,2500,1200,6,8192,4,520);
INSERT OR REPLACE INTO "texts" VALUES (8611007, 'Lavalval Dragun', '1 Tuner + 1 or more non-Tuner FIRE monsters
Once per turn, during your Main Phase: You can add 1 "Laval" monster from your Deck to your hand then send 1 "Laval" monster from your hand to the Graveyard.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34109611,3,0,16,8225,1400,1200,4,1048576,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (34109611, 'Daigusto Falcos', '1 Tuner + 1 or more non-Tuner "Gusto" monsters
When this card is Synchro Summoned: All "Gusto" monsters currently on the field gain 600 ATK.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71594310,3,0,4167,8388609,2600,1900,4,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (71594310, 'Gem-Knight Pearl', '2 Level 4 monsters', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3989465,3,0,57,8388641,1800,1400,3,1,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (3989465, 'Lavalval Ignis', '2 Level 3 monsters
If this card attacks or is attacked, during the Damage Step (in either player''s turn): You can detach 1 Xyz Material from this card once per battle; this card gains 500 ATK until the end of this turn.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39987164,3,0,48,8388641,2500,2100,4,4,16,1075843074);
INSERT OR REPLACE INTO "texts" VALUES (39987164, 'Vylon Disigma', '3 Level 4 monsters
Once per turn: You can detach 1 Xyz Material from this card to target 1 face-up Attack Position Effect Monster your opponent controls; equip that target to this card. When this card battles a monster with the same Attribute as the monster(s) equipped to this card by this card''s effect: Destroy that monster at the start of the Damage Step (without applying damage calculation).', 'Equip', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76372778,3,0,58,8388641,2100,1600,4,64,2,32);
INSERT OR REPLACE INTO "texts" VALUES (76372778, 'Evigishki Merrowgeist', '2 Level 4 monsters
After damage calculation, if this card destroys an opponent''s monster by battle: You can detach 1 Xyz Material from this card; shuffle the destroyed monster into the Deck instead of sending it to the Graveyard.', '战斗破坏的怪兽返回卡组', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2766877,3,0,16,8388641,1500,1100,2,128,8,2129920);
INSERT OR REPLACE INTO "texts" VALUES (2766877, 'Daigusto Phoenix', '2 Level 2 monsters
Once per turn: You can detach 1 Xyz Material from this card to target 1 face-up WIND monster you control; that target can attack twice during this turn''s Battle Phase.', '两次攻击', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39261576,3,0,70,2,0,0,0,0,0,268705796);
INSERT OR REPLACE INTO "texts" VALUES (39261576, 'Particle Fusion', 'Send, from your side of the field to the Graveyard, Fusion Material Monsters listed on a "Gem-Knight" Fusion Monster Card, and Special Summon that monster from your Extra Deck. (This Special Summon is treated as a Fusion Summon.) Then, you can banish this card from your Graveyard to target 1 "Gem-Knight" Fusion Material Monster used for that Fusion Summon; until the End Phase, the Fusion Monster gains ATK equal to the target''s ATK.', 'Gain attack', 'Please select 1 Fusion Material Monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65659181,3,0,48,65538,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (65659181, 'Vylon Polytope', 'Target any number of "Vylon" monsters you control that are treated as Equip Cards; Special Summon them in face-up Defense Position. When that monster(s) leaves the field, banish it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1644289,3,0,48,262146,0,0,0,0,0,33554944);
INSERT OR REPLACE INTO "texts" VALUES (1644289, 'Vylon Segment', 'Equip only to a "Vylon" monster. It cannot be targeted by the effects of your opponent''s Trap Cards or Effect Monsters. If this face-up card is sent to the Graveyard: You can add 1 "Vylon" Spell Card from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38049934,3,0,0,4,0,0,0,0,0,7);
INSERT OR REPLACE INTO "texts" VALUES (38049934, 'Dustflame Blast', 'Banish all "Laval" monsters from your Graveyard, then destroy cards on the field, up to the number of monsters banished by this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64437633,3,0,0,4,0,0,0,0,0,327696);
INSERT OR REPLACE INTO "texts" VALUES (64437633, 'Aquamirror Illusion', 'Special Summon a "Gishki" Ritual Monster from your hand, ignoring the Summoning conditions. That monster cannot attack. During the End Phase, return it to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91822647,3,0,16,4,0,0,0,0,0,263168);
INSERT OR REPLACE INTO "texts" VALUES (91822647, 'Whirlwind of Gusto', 'If you control no monsters: Target 2 "Gusto" monsters in your Graveyard; shuffle those targets into the Deck, and Special Summon 1 "Gusto" monster with 1000 or less DEF from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
