BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (6330307,3,0,126,33,0,0,1,8,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (6330307, 'DZW - Chimera Clad', 'You can target 1 "Number C39" monster you control; equip this monster from your hand or your side of the field to that target. The equipped monster cannot be destroyed by battle. At the end of the Damage Step, when the equipped monster attacks an opponent''s monster, but the opponent''s monster was not destroyed by the battle: You can make the opponent''s monster''s ATK 0 (even after this card leaves the field or the monster becomes unaffected by card effects), and if you do, the equipped monster can make a second attack on the same monster in a row.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33725002,3,0,0,33,1500,1300,4,2,4,-2143289344);
INSERT OR REPLACE INTO "texts" VALUES (33725002, 'V Salamander', 'When this card is Normal Summoned: You can target 1 "Utopia" monster in your Graveyard; Special Summon that target. You can target 1 "Number C39: Utopia Ray V" you control; equip this monster you control to that target. Once per turn, while this card is equipped to a monster: You can detach 1 Xyz Material from the equipped monster; negate the equipped monster''s effects, (even after this card leaves the field or the monster becomes unaffected by card effects), and if you do, destroy all monsters your opponent controls, and if you do that, inflict 1000 damage to your opponent for each monster destroyed by this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19113101,3,0,0,33,800,800,2,1024,1,-2147483644);
INSERT OR REPLACE INTO "texts" VALUES (19113101, 'Interceptomato', 'During your opponent''s turn: You can banish this card from your Graveyard; this turn, any effect damage you take becomes 0 (this is a Quick Effect).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45118716,3,0,0,33,0,0,1,2,32,44);
INSERT OR REPLACE INTO "texts" VALUES (45118716, 'Spell Recycler', 'When an opponent''s monster declares an attack: You can banish this card from your Graveyard, then target 1 Spell Card in your Graveyard; send the top card of your Deck to the Graveyard, and if you do, return the target to the bottom of your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72502414,3,0,115,33,900,300,2,2,16,1073741824);
INSERT OR REPLACE INTO "texts" VALUES (72502414, 'Xyz Agent', 'If this card is in your Graveyard: You can target 1 "Utopia" Xyz Monster you control; attach this card from the Graveyard to it as an Xyz Material. You can only use the effect of "Xyz Agent" once per Duel.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8091563,3,0,133,33,1200,1600,4,32,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (8091563, 'Super Defense Robot Lio', 'When this card is Normal Summoned: You can Special Summon 1 "Super Defense Robot" monster or "Orbital 7" from your hand. Once per turn, when exactly 1 "Super Defense Robot" monster or "Orbital 7" (and no other cards) is added from your Graveyard to your hand (except during the Damage Step): You can Special Summon it from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45496268,3,0,133,33,1400,2500,8,32,1,1074003968);
INSERT OR REPLACE INTO "texts" VALUES (45496268, 'Super Defense Robot Elephan', 'When this card is Normal Summoned: You can Special Summon 1 "Super Defense Robot" monster or "Orbital 7" from your hand. Once per turn: You can target 1 "Super Defense Robot" monster or "Orbital 7" you control; it becomes Level 8 until the End Phase. This card cannot be used as an Xyz Material for an Xyz Summon, except for the Xyz Summon of a Machine-Type monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71880877,3,0,133,33,800,1200,3,32,1,262164);
INSERT OR REPLACE INTO "texts" VALUES (71880877, 'Super Defense Robot Monki', 'When this card is Normal Summoned: You can Special Summon 1 "Super Defense Robot" monster or "Orbital 7" from your hand. Once per turn: You can banish 1 Machine-Type monster from your Graveyard, then target 1 "Super Defense Robot" monster or "Orbital 7" in your Graveyard; add that target to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8875971,3,0,134,33,1200,1800,4,4,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (8875971, 'Star Seraph Scout', 'When this card is Normal Summoned: You can Special Summon 1 "Star Seraph" monster from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44273680,3,0,134,33,1600,1400,4,4,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (44273680, 'Star Seraph Sage', 'Once per turn: You can send 1 Spell Card from your hand to the Graveyard; Special Summon 1 "Star Seraph" monster from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70668285,3,0,134,33,1400,1000,4,4,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (70668285, 'Star Seraph Sword', 'Once per turn: You can send 1 "Star Seraph" monster from your hand to the Graveyard; this card gains ATK equal to the original ATK of the sent monster, until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7152333,3,0,135,33,1800,0,4,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (7152333, 'Umbral Horror Ghoul', 'Once per turn: You can make this card''s ATK 0, and if you do, Special Summon 1 "Umbral Horror" monster with 0 ATK from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33551032,3,0,135,33,0,0,4,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (33551032, 'Umbral Horror Unform', 'When this card is destroyed by battle and sent to the Graveyard while attacking a monster: You can Special Summon 2 "Umbral Horror" monsters from your Deck. You can only use the effect of "Umbral Horror Unform" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70546737,3,0,135,33,0,0,1,8,32,2);
INSERT OR REPLACE INTO "texts" VALUES (70546737, 'Umbral Horror Will o'' the Wisp', 'When this card is Normal or Special Summoned: You can target 1 "Umbral Horror" monster you control or in your Graveyard, except this card; this card''s Level becomes the current Level of that monster. When this Attack Position card is destroyed by battle and sent to the Graveyard, and was in face-up Attack Position at the start of the Damage Step: Destroy the monster that destroyed this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6930746,3,0,0,33,2000,0,8,8192,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (6930746, 'Schwarzschild Limit Dragon', 'If your opponent controls a monster with 2000 or more ATK, you can Special Summon this card (from your hand).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32339440,3,0,136,33,1800,200,4,32768,16,520);
INSERT OR REPLACE INTO "texts" VALUES (32339440, 'Bujin Yamato', 'Once per turn, during your End Phase: You can add 1 "Bujin" monster from your Deck to your hand, then send 1 card from your hand to the Graveyard. You can only control 1 "Bujin Yamato".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69723159,3,0,136,33,1600,900,4,16384,16,7);
INSERT OR REPLACE INTO "texts" VALUES (69723159, 'Bujingi Quilin', 'If you control a Beast-Warrior-Type "Bujin" monster: You can banish this card from your Graveyard, then target 1 face-up card your opponent controls; destroy that target. You can only use the effect of "Bujingi Quilin" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5818294,3,0,136,33,1700,1200,4,16384,16,7);
INSERT OR REPLACE INTO "texts" VALUES (5818294, 'Bujingi Turtle', 'During either player''s turn, when a card or effect is activated that targets a "Bujin" monster you control (except during the Damage Step): You can banish this card from your Graveyard; negate that effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32202803,3,0,136,33,1100,2000,4,16384,16,16777216);
INSERT OR REPLACE INTO "texts" VALUES (32202803, 'Bujingi Wolf', 'Other Beast, Beast-Warrior, and Winged Beast-Type monsters you control cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68601507,3,0,136,33,1600,300,4,512,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (68601507, 'Bujingi Crane', 'During damage calculation (in either player''s turn), if a Beast-Warrior-Type "Bujin" monster you control battles an opponent''s monster: You can send this card from your hand to the Graveyard; the ATK of your monster becomes double its original ATK, during that damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94096616,3,0,136,33,1700,500,4,512,16,131072);
INSERT OR REPLACE INTO "texts" VALUES (94096616, 'Bujingi Ophidian', 'During your Main Phase 1: You can send this card from your hand to the Graveyard, then target 1 "Bujin" monster you control; it can attack your opponent directly this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31480215,3,0,270204955,4129,300,300,1,32,8,0);
INSERT OR REPLACE INTO "texts" VALUES (31480215, 'Mecha Phantom Beast Warbluran', 'If this card is sent to the Graveyard for the Synchro Summon of a Machine-Type monster: Special Summon 1 "Mecha Phantom Beast Token" (Machine-Type/WIND/Level 3/ATK 0/DEF 0), also, for the rest of this turn, you cannot Special Summon any other monsters, except WIND monsters. While you control a Token, this card cannot be destroyed by battle or card effects. You can Tribute 1 other "Mecha Phantom Beast" monster; increase this card''s Level by 1. You can only use 1 "Mecha Phantom Beast Warbluran" effect per turn, and only once that turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67489919,3,0,270204955,4129,1400,1100,3,32,8,262148);
INSERT OR REPLACE INTO "texts" VALUES (67489919, 'Mecha Phantom Beast Blue Impala', 'Cannot be used as a Synchro Material Monster, except for the Synchro Summon of a Machine-Type monster. The other Synchro Material Monster(s) are "Mecha Phantom Beast" monsters in your hand or on your side of the field. While you control a Token, this card cannot be destroyed by battle or card effects. If your opponent controls a monster and you control no monsters: You can banish this card from your Graveyard; Special Summon 1 "Mecha Phantom Beast Token" (Machine-Type/WIND/Level 3/ATK 0/DEF 0).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94973028,3,0,270204955,33,1600,1500,4,32,8,262148);
INSERT OR REPLACE INTO "texts" VALUES (94973028, 'Mecha Phantom Beast Coltwing', 'When this card is Special Summoned: Special Summon 2 "Mecha Phantom Beast Tokens" (Machine-Type/WIND/Level 3/ATK 0/DEF 0). You must control another "Mecha Phantom Beast" monster to activate and to resolve this effect. This card''s Level is increased by the total Levels of all "Mecha Phantom Beast Tokens" you control. While you control a Token, this card cannot be destroyed by battle or card effects. Once per turn: You can Tribute 2 Tokens, then target 1 card your opponent controls; destroy that target, and if you do, banish it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20368763,3,0,270204955,33,1800,800,4,32,8,786432);
INSERT OR REPLACE INTO "texts" VALUES (20368763, 'Mecha Phantom Beast Harrliard', 'Once per turn, when a monster(s) you control is Tributed to activate a card or effect other than this card''s: Special Summon 1 "Mecha Phantom Beast Token" (Machine-Type/WIND/Level 3/ATK 0/DEF 0). This card''s Level is increased by the total Levels of all "Mecha Phantom Beast Tokens" you control. While you control a Token, this card cannot be destroyed by battle or card effects. Once per turn: You can Tribute 1 Token; Special Summon 1 "Mecha Phantom Beast" monster from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66762372,3,0,121,4129,1100,1400,4,32768,4,262656);
INSERT OR REPLACE INTO "texts" VALUES (66762372, 'Brotherhood of the Fire Fist - Boar', 'Cannot be used as a Synchro Material Monster, except for the Synchro Summon of a FIRE monster. When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 Level 4 "Fire Fist" monster from your Deck, except "Brotherhood of the Fire Fist - Boar". Once per turn, when a "Fire Fist" monster is Special Summoned from your Extra Deck: You can Set 1 "Fire Formation" Spell Card directly from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93751476,3,0,121,33,1100,2000,4,32768,4,262656);
INSERT OR REPLACE INTO "texts" VALUES (93751476, 'Brotherhood of the Fire Fist - Caribou', 'During the End Phase, if this card is in the Graveyard because it was destroyed by a card effect and sent there this turn: You can Special Summon 1 Level 4 "Fire Fist" monster from your Deck, except "Brotherhood of the Fire Fist - Caribou". If this card is sent to the Graveyard for the Synchro Summon of a "Fire Fist" monster: You can Set 1 "Fire Formation" Spell Card directly from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29146185,3,0,110,33,2900,2400,9,2,16,17039379);
INSERT OR REPLACE INTO "texts" VALUES (29146185, 'World of Prophecy', 'When this card is Special Summoned by the effect of a Spellcaster-Type monster or a "Spellbook" Spell Card: You can target 2 "Spellbook" Spell Cards in your Graveyard; add those targets to your hand. You cannot Special Summon other monsters during the turn you activate this effect. When you add card(s) to your hand by this effect: You can reveal 4 "Spellbook" Spell Cards with different names in your hand; destroy all other cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66540884,3,0,69,33,1000,0,3,8,32,512);
INSERT OR REPLACE INTO "texts" VALUES (66540884, 'Archfiend Heiress', 'If this card is sent to the Graveyard because of a card effect or being destroyed by battle: You can add 1 "Archfiend" card from your Deck to your hand, except "Archfiend Heiress". You can only use the effect of "Archfiend Heiress" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92039899,3,0,69,33,1900,0,4,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (92039899, 'Archfiend Cavalry', 'If this card on the field is destroyed by a card effect and sent to the Graveyard: You can target 1 "Archfiend" monster in your Graveyard, except "Archfiend Cavalry"; Special Summon that target. It cannot attack this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28423537,3,0,69,33,3000,2000,8,8,32,3);
INSERT OR REPLACE INTO "texts" VALUES (28423537, 'Archfiend Emperor, the First Lord of Horror', 'You can Normal Summon this card without Tributing, but its original ATK and DEF become halved. If Summoned this way, it is destroyed during the End Phase. You cannot Special Summon any monsters, except Fiend-Type monsters. Once per turn: You can banish 1 "Archfiend" card from your hand or Graveyard, then target 1 card on the field; destroy that target.', 'Normal Summon Without Tributing', 'Destroy a card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55428242,3,0,277479562,33,1800,1000,4,2048,1,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (55428242, 'Traptrix Atrax', 'This card is unaffected by the effects of "Hole" Normal Trap Cards. You can activate "Hole" Normal Trap Cards from your hand. The activation and effects of Normal Trap Cards activated on your side of the field cannot be negated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91812341,3,0,277479562,33,1600,1200,4,2048,1,1);
INSERT OR REPLACE INTO "texts" VALUES (91812341, 'Traptrix Myrmeleo', 'This card is unaffected by the effects of "Hole" Normal Trap Cards. When this card is Normal Summoned: You can add 1 "Hole" Normal Trap Card from your Deck to your hand. When this card is Special Summoned: Target 1 Spell/Trap Card your opponent controls; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28201945,3,0,277479562,33,800,2000,4,1024,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (28201945, 'Traptrix Nepenthes', 'This card is unaffected by the effects of "Hole" Normal Trap Cards. If you activate a "Hole" Normal Trap Card (except during the Damage Step): You can add to your hand, or Special Summon, 1 "Traptrix" monster from your Deck, except "Traptrix Nepenthes". You can only use the effect of "Traptrix Nepenthes" once per turn.', 'Add 1 "Fascinating" Monster to your hand', 'Special Summon 1 "Fascinating" Monster from the Deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54706054,3,0,0,33,1500,1500,4,4096,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (54706054, 'The Calibrator', 'This card gains ATK equal to the combined Ranks of all face-up Xyz Monsters your opponent controls x 300.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80190753,3,0,0,33,2800,1200,8,1024,2,8192);
INSERT OR REPLACE INTO "texts" VALUES (80190753, 'Talaya, Princess of Cherry Blossoms', 'This card gains 100 ATK for each Plant-Type monster you control. Other Plant-Type monsters on the field cannot be destroyed by card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27189308,3,0,0,33,300,200,1,512,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (27189308, 'Cheepcheepcheep', 'FLIP: You can Special Summon 1 Level 5 or higher Tuner monster from your Deck.', 'Special Summon a Monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53573406,3,0,0,4129,1600,1100,4,524288,1,-2147221504);
INSERT OR REPLACE INTO "texts" VALUES (53573406, 'Masked Chameleon', 'Cannot be Normal Summoned if you control a Level 5 or higher monster. When this card is Normal Summoned: You can target 1 monster with 0 DEF in your Graveyard; Special Summon that target in face-up Defense Position. Its effects are negated. You cannot Special Summon any other monsters, except from the Extra Deck, during the turn you activate this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80978111,3,0,0,33,700,700,3,2048,1,1074003968);
INSERT OR REPLACE INTO "texts" VALUES (80978111, 'Flying "C"', 'When your opponent Normal or Special Summons a monster(s), except during the Damage Step: You can Special Summon this card from your hand to the opponent''s side of the field in face-up Defense Position. The controller of this card cannot Xyz Summon.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16366810,3,0,128,33,0,1000,1,8,1,32);
INSERT OR REPLACE INTO "texts" VALUES (16366810, 'Yellow Duston', 'Cannot be used as a Fusion, Synchro, or Xyz Material for a Summon. While this card is face-up on the field, it cannot be Tributed. When this card on the field is destroyed: The controller targets 1 monster card in their Graveyard; shuffle that target into the Deck. You can only control 1 face-up "Yellow Duston".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53451824,3,0,270204955,8225,2400,1200,7,32,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (53451824, 'Mecha Phantom Beast Concoruda', '1 Tuner + 1 or more non-Tuner monsters
Tokens you control cannot be destroyed by battle or card effects. If this card you control is destroyed by your opponent''s card (either by battle or by card effect) and sent to your Graveyard: You can Tribute all Tokens you control, then target 1 Level 4 or lower "Mecha Phantom Beast" monster in your Graveyard; Special Summon that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89856523,3,0,121,8225,2000,2800,8,32768,4,8704);
INSERT OR REPLACE INTO "texts" VALUES (89856523, 'Brotherhood of the Fire Fist - Kirin', '1 FIRE Tuner + 1 or more non-Tuner "Fire Fist" monsters
When this card is Synchro Summoned: You can Set 1 "Fire Formation" Spell/Trap Card directly from your Deck. All monsters your opponent controls lose 100 ATK for each face-up Spell/Trap Card you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15240238,3,0,0,8225,0,2300,3,512,8,-2147475456);
INSERT OR REPLACE INTO "texts" VALUES (15240238, 'Mist Bird Clausolas', '1 Tuner + 1 or more non-Tuner monsters
Once per turn: You can target 1 face-up monster your opponent controls; until the end of this turn, that monster''s ATK becomes 0, and its effects are negated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52639377,3,0,0,8225,2100,800,4,1,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (52639377, 'Underworld Fighter Balmung', '1 Tuner + 1 or more non-Tuner monsters
When this card is destroyed by a card effect and sent to the Graveyard: You can target 1 Level 4 or lower monster in your Graveyard, except this card; Special Summon that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88033975,3,0,0,8225,2300,1500,5,8,16,0);
INSERT OR REPLACE INTO "texts" VALUES (88033975, 'Armades, Keeper of Boundaries', '1 Tuner + 1 or more non-Tuner monsters
If this card attacks or is attacked, your opponent cannot activate cards or effects until the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15028680,3,0,0,8225,2400,1800,6,1048576,1,4);
INSERT OR REPLACE INTO "texts" VALUES (15028680, 'HTS Psyhemuth', '1 Tuner + 1 or more non-Tuner monsters
After damage calculation, when this card battles an opponent''s monster: You can banish that monster, also banish this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41517789,3,0,0,8225,3200,2800,11,8192,16,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (41517789, 'Star Eater', '1 Tuner + 1 or more non-Tuner monsters
Must be Synchro Summoned, and cannot be Special Summoned by other ways. This card''s Synchro Summon cannot be negated. When Synchro Summoned, cards and effects cannot be activated. If this card attacks, it is unaffected by other card effects until the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87911394,3,0,273154175,8388641,2800,2500,5,1,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (87911394, 'Number C39: Utopia Ray Victory', '3 Level 5 monsters
If this card attacks, your opponent cannot activate any Spell/Trap Cards until the end of the Damage Step. If this card has a "Utopia" monster as an Xyz Material, it gains this effect.
● When this card declares an attack on a face-up monster your opponent controls: You can detach 1 Xyz Material from this card; negate that opponent''s face-up monster''s effects, also this card gains ATK equal to that opponent''s monster''s ATK. These changes last until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14306092,3,0,0,8388641,1800,2000,3,131072,2,8192);
INSERT OR REPLACE INTO "texts" VALUES (14306092, 'Shark Caesar', '3 or more (max. 5) Level 3 monsters
Once per turn: You can detach 1 Xyz Material from this card; place 1 Shark Counter on this card. If this card attacks or is attacked, it gains 1000 ATK for each Shark Counter on it during the Damage Step only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40390147,3,0,0,8388641,2000,2100,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (40390147, 'Starliege Lord Galaxion', '2 Level 4 "Photon" monsters
Once per turn: You can detach 1 or 2 Xyz Materials from this card; apply this effect, depending on the number you detached.
● 1: Special Summon 1 "Galaxy-Eyes Photon Dragon" from your hand.
● 2: Special Summon 1 "Galaxy-Eyes Photon Dragon" from your Deck.', 'Special Summon from deck', 'Special Summon from hand', 'Special Summon from deck', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77799846,3,0,0,8388641,3000,2500,8,32,1,270336);
INSERT OR REPLACE INTO "texts" VALUES (77799846, 'Googly-Eyes Drum Dragon', '2 Level 8 Machine-Type monsters
Once per turn: You can detach 1 Xyz Material from this card; it gains 1000 ATK, until your opponent''s next End Phase. If this card is destroyed while it has Xyz Material: You can banish 1 "Super Defense Robot" monster from your Graveyard; Special Summon this card from your Graveyard, then, you can attach 1 "Super Defense Robot" monster from your Graveyard to this card as an Xyz Material.', 'Attach material?', 'Attach material?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13183454,3,0,0,8388641,2500,2100,5,512,2,8192);
INSERT OR REPLACE INTO "texts" VALUES (13183454, 'Ice Princess Zereort', '2 Level 5 Winged Beast-Type monsters
You can detach 1 Xyz Material from this card, then target 1 face-up monster your opponent controls; its ATK becomes 0.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49678559,3,0,8781896,8388641,2500,2000,4,4,16,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (49678559, 'Number 102: Star Seraph Sentry', '3 Level 4 LIGHT monsters
Once per turn: You can detach 1 Xyz Material from this card, then target 1 face-up monster your opponent controls; halve its ATK, also, negate its effect. If this face-up card on the field would be destroyed, you can detach all of its Xyz Materials instead. If you do, any battle damage you take this turn is halved.', 'Detach all material?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76067258,3,0,72,8388641,2500,800,4,2048,32,0);
INSERT OR REPLACE INTO "texts" VALUES (76067258, 'Number 66: Master Key Beetle', '2 Level 4 DARK monsters
Once per turn: You can detach 1 Xyz Material from this card, then target 1 card you control, except this card; while this card is face-up on the field, that card(s) cannot be destroyed by card effects. If this face-up card on the field would be destroyed, you can send one of its targets to the Graveyard instead.', 'Send 1 selected target.', 'Send 1 selected target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2061963,3,0,72,8388641,2700,1200,4,2,16,-2143289344);
INSERT OR REPLACE INTO "texts" VALUES (2061963, 'Number 104: Masquerade', '3 Level 4 monsters
During either player''s Battle Phase, when an opponent''s monster effect is activated: You can detach 1 Xyz Material from this card; negate the activation, and if you do, inflict 800 damage to your opponent. Once per turn: You can send the top card of your opponent''s Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49456901,3,0,273154120,8388641,3000,1500,5,2,32,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (49456901, 'Number C104: Umbral Horror Masquerade', '4 Level 5 monsters
When this card is Special Summoned: You can target 1 Spell/Trap Card on the field; destroy that target. If this card has "Number 104: Masquerade" as an Xyz Material, it gains this effect.
● Once per turn, during either player''s turn, when a monster effect is activated on your opponent''s side of the field: You can detach 1 Xyz Material from this card; negate the activation, then you can send 1 random card from your opponent''s hand to the Graveyard, and if you do, halve your opponent''s Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75840616,3,0,136,8388641,2400,1600,4,32768,16,33288);
INSERT OR REPLACE INTO "texts" VALUES (75840616, 'Bujintei Susanowo', '2 Level 4 "Bujin" monsters
This card can attack all monsters your opponent controls once each. Once per turn: You can detach 1 Xyz Material from this card; take 1 "Bujin" monster from your Deck, and either add it to your hand or send it to the Graveyard. You can only control 1 "Bujintei Susanowo".', 'Send to the grave?', 'Add to the hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1249315,3,0,0,8388641,600,1000,2,4,16,56);
INSERT OR REPLACE INTO "texts" VALUES (1249315, 'Herald of Pure Light', '2 Level 2 monsters
You can detach 1 Xyz Material from this card, then target 1 monster in your Graveyard; add it to your hand, then shuffle 1 card from your hand into the Deck. You can only use the effect of "Herald of Pure Light" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48333324,3,0,149,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (48333324, 'Rank-Up-Magic Numeron Force', 'Target 1 face-up Xyz Monster you control; Special Summon from your Extra Deck, 1 "Number C" monster with the same Type as that monster you control, but 1 Rank higher, by using it as the Xyz Material. (This Special Summon is treated as an Xyz Summon. Xyz Materials attached to it also become Xyz Materials on the Summoned monster.) Then, if any face-up cards are on the field other than this card and the monster Summoned by it, negate the effects of those other cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74728028,3,0,115,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (74728028, 'Xyz Reception', 'Target 1 face-up monster you control that has a Level; Special Summon 1 monster with the same Level as that monster from your hand. Its effects are negated, also its ATK and DEF become 0.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1127737,3,0,0,524290,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (1127737, 'Sargasso the D.D. Battlefield', 'When a player Xyz Summons a monster: That player takes 500 damage. During each End Phase, if the turn player controls an Xyz Monster, that player takes 500 damage.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37511832,3,0,0,65538,0,0,0,0,0,-2147483136);
INSERT OR REPLACE INTO "texts" VALUES (37511832, 'Sargasso Lighthouse', 'When a Spell effect that would inflict damage to you is activated: You take no damage from that effect. While this card is in your Graveyard, you take no damage from the effect of "Sargasso the D.D. Battlefield". When this Set card is sent to the Graveyard: You can add 1 "Sargasso the D.D. Battlefield" from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73906480,3,0,136,2,0,0,0,0,0,1074003972);
INSERT OR REPLACE INTO "texts" VALUES (73906480, 'Bujincarnation', 'If your opponent controls a monster and you control no monsters: Target 1 "Bujin" monster in your Graveyard and 1 of your banished "Bujin" monsters; Special Summon both targets. They cannot be used as Xyz Material for an Xyz Summon, except for the Xyz Summon of a Beast, Beast-Warrior, or Winged Beast-Type monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (904185,3,0,0,65538,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (904185, 'Vertical Landing', 'Tribute any number of WIND monsters, except Tokens; Special Summon an equal number of "Mecha Phantom Beast Tokens" (Machine-Type/WIND/Level 3/ATK 0/DEF 0). You can only activate 1 "Vertical Landing" per turn.', 'Special Summon "Mecha Phantom Beast Token"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36499284,3,0,124,131074,0,0,0,0,0,16777224);
INSERT OR REPLACE INTO "texts" VALUES (36499284, 'Fire Formation - Yoko', 'When you activate this card, you can target 1 face-up card your opponent controls; discard 1 Beast-Warrior-Type monster, and if you do, destroy that card. All Beast-Warrior-Type monsters you control gain 100 ATK.', 'Destroy a face-up card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63883999,3,0,69,524290,0,0,0,0,0,262148);
INSERT OR REPLACE INTO "texts" VALUES (63883999, 'Archfiend Palabyrinth', 'All Fiend-Type monsters you control gain 500 ATK. You can target 1 "Archfiend" monster you control; banish 1 other Fiend-Type monster you control, and if you do, Special Summon from your hand, Deck, or Graveyard, 1 "Archfiend" monster with same Level as the targeted monster. You can only use this effect of "Archfiend Palabyrinth" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5288597,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (5288597, 'Transmodify', 'Send 1 face-up monster you control to the Graveyard; Special Summon from your Deck, 1 monster with the same Type and Attribute as that monster in the Graveyard, but 1 Level higher. You can only activate 1 "Transmodify" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31677606,3,0,0,65538,0,0,0,0,0,1073742080);
INSERT OR REPLACE INTO "texts" VALUES (31677606, 'Black and White Wave', 'If there is a face-up Xyz Monster on the field with a Synchro Monster as Xyz Material: Target 1 card on the field; banish that target, and if you do, draw 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68661341,3,0,0,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (68661341, 'Single Purchase', 'If you have 3 or more cards in your hand (other than this card), and none of them are monsters: Banish your entire hand face-up; add 1 monster from your Deck to your hand. If you do, you cannot Normal or Special Summon any monsters for the rest of this turn, except monsters with that name.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94156050,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (94156050, 'Reverse Glasses', 'Halve the ATK of all face-up monsters currently on the field, until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31554054,3,0,115,4,0,0,0,0,0,1074003968);
INSERT OR REPLACE INTO "texts" VALUES (31554054, 'Xyz Revenge Shuffle', 'When a face-up Xyz Monster you control is targeted for an attack: Target 1 Xyz Monster in your Graveyard; shuffle the attacked monster into the Extra Deck, then Special Summon that target, and if you do, attach this card as an Xyz Material to it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67949763,3,0,0,4,0,0,0,0,0,786432);
INSERT OR REPLACE INTO "texts" VALUES (67949763, 'Corrupted Keys', 'Target 1 face-up Xyz Monster you control; Special Summon 3 "Umbral Horror Mirage Tokens" (Fiend-Type/DARK/Level 1/ATK ?/DEF 0). (When Summoned, each Token''s ATK becomes equal to that Xyz Monster''s current ATK. They cannot attack your opponent directly or be Tributed, except for a Tribute Summon.) When that face-up Xyz Monster leaves the field, destroy these Tokens.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94933468,3,0,0,131076,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (94933468, 'Vain Betrayer', 'When an opponent''s Xyz Monster declares an attack: Activate this card by targeting the attacking monster. It cannot attack, also its effects are negated. While that monster is on the field, during each of your opponent''s End Phases: Send the top 3 cards of the opponent''s Deck to the Graveyard. When that monster leaves the field, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30338466,3,0,136,4,0,0,0,0,0,528);
INSERT OR REPLACE INTO "texts" VALUES (30338466, 'Bujin Regalia - The Sword', 'Activate 1 of these effects.
● Target 1 "Bujin" monster in your Graveyard; add that target to your hand.
● Target 1 of your banished "Bujin" monsters; send that target to the Graveyard.', 'Add 1 War God from the Grave', 'Return 1 War God to the Grave', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66727115,3,0,136,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (66727115, 'Bujinfidel', 'Tribute 1 Beast-Warrior-Type "Bujin" monster, then target 1 "Bujin" monster with a different name in your Graveyard; Special Summon that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93211810,3,0,0,4,0,0,0,0,0,16386);
INSERT OR REPLACE INTO "texts" VALUES (93211810, 'Sonic Boom', 'During your turn: Target 1 "Mecha Phantom Beast" monster on the field; this turn, its ATK becomes double its original ATK, it is unaffected by other Spell/Trap effects, also if it attacks a Defense Position monster, inflict piercing battle damage to your opponent. If this effect is applied to that monster, destroy all Machine-Type monsters you control during the End Phase of this turn. Other monsters cannot attack during the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29616929,3,0,4980874,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (29616929, 'Traptrix Trap Hole Nightmare', 'When a monster that was Special Summoned this turn activates its effect on your opponent''s side of the field: Negate that effect, and if you do, destroy that card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66604523,3,0,115,4,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (66604523, 'Xyz Reversal', 'Target 1 face-up Xyz Monster your opponent controls and 1 face-up Xyz Monster you control, switch control of both monsters.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92099232,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (92099232, 'Shapesister', 'Special Summon this card as a Normal Monster (Fiend-Type/Tuner/EARTH/Level 2/ATK 0/DEF 0). (This card is also still a Trap Card.) You can only activate 1 "Shapesister" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28493337,3,0,0,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (28493337, 'Armageddon Designator', 'Banish 1 card from your hand; neither player can activate cards, or the effects of cards, with that name for the rest of this Duel.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
