BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (32754886,1,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (32754886, 'Dark Illusion', 'All DARK Spellcaster-Type monsters you currently control with 2000 or more ATK cannot be destroyed by battle, they are unaffected by your opponent''s card effects, also their effects are negated. These changes last until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30208479,3,0,0,129,2800,2600,8,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (30208479, 'Magician of Black Chaos', 'You can Ritual Summon this card with "Black Magic Ritual".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40737112,3,0,162,33,2800,2600,8,2,32,1044);
INSERT OR REPLACE INTO "texts" VALUES (40737112, 'Dark Magician of Chaos', 'During the End Phase, if this card was Normal or Special Summoned this turn: You can target 1 Spell Card in your Graveyard; add it to your hand. You can only use this effect of "Dark Magician of Chaos" once per turn. At the end of the Damage Calculations, if this card destroyed an opponent’s monster by battle: Banish that monster. If this card would leave the field, banish it instead.', 'Spell recovery', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64681432,3,0,0,33,0,0,8,8192,32,8207);
INSERT OR REPLACE INTO "texts" VALUES (64681432, 'Gandora the Dragon of Destruction', 'Cannot be Special Summoned. You can pay half your Life Points; destroy all other cards on the field, and if you do, banish them. This card gains 300 ATK for each card destroyed this way. During the End Phase of the turn this card was Summoned: Send it to the Graveyard.', 'Destroy', 'Send to Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72443568,3,0,65,33,3500,1000,8,2,16,33554432);
INSERT OR REPLACE INTO "texts" VALUES (72443568, 'Silent Magician LV8', 'Cannot be Normal Summoned/Set. Must be Special Summoned by "Silent Magician LV4" and cannot be Special Summoned by other ways. This card is unaffected by your opponent''s Spell effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73665146,3,0,65,33,1000,1000,4,2,16,67379208);
INSERT OR REPLACE INTO "texts" VALUES (73665146, 'Silent Magician LV4', 'Each time your opponent draws a card(s), place 1 Spell Counter on this card (max. 5). This card gains 500 ATK for each Spell Counter on it. During the Standby Phase of your next turn after the 5th Spell Counter is placed on this card: You can send this face-up card with 5 Spell Counters on it to the Graveyard; Special Summon 1 "Silent Magician LV8" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37267041,3,0,65,33,2800,1000,7,1,16,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (37267041, 'Silent Swordsman LV7', 'Cannot be Normal Summoned/Set. Must be Special Summoned by "Silent Swordsman LV5", and cannot be Special Summoned by other ways. Negate all Spell effects on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74388798,3,0,65,33,2300,1000,5,1,16,33816584);
INSERT OR REPLACE INTO "texts" VALUES (74388798, 'Silent Swordsman LV5', 'This card is unaffected by your opponent''s Spell effects. During your next Standby Phase after this card inflicts battle damage to your opponent by a direct attack: You can send this face-up card to the Graveyard; Special Summon 1 "Silent Swordsman LV7" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1995985,3,0,65,33,1000,1000,3,1,16,262656);
INSERT OR REPLACE INTO "texts" VALUES (1995985, 'Silent Swordsman LV3', 'Negate your opponent''s Spell effects that target this card. During your Standby Phase: You can send this face-up card to the Graveyard; Special Summon 1 "Silent Swordsman LV5" from your hand or Deck. You cannot activate this effect the turn this card is Summoned or flipped face-up.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46986414,3,0,162,17,2500,2100,7,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (46986414, 'Dark Magician', 'The ultimate wizard in terms of attack and defense.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38033121,3,0,279052450,33,2000,1700,6,2,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (38033121, 'Dark Magician Girl', 'This card gains 300 ATK for every "Dark Magician" or "Magician of Black Chaos" in either player''s Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78193831,3,0,0,33,2600,2300,7,1,1,1056768);
INSERT OR REPLACE INTO "texts" VALUES (78193831, 'Buster Blader', 'This card gains 500 ATK for each Dragon-Type monster your opponent controls or is in their Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14778250,3,0,0,33,2000,1200,5,2,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (14778250, 'The Tricky', 'You can Special Summon this card (from your hand) by discarding 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90876561,3,0,0,17,1900,1000,5,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (90876561, 'Jack''s Knight', 'A strong master swordsman. His loyalty is to justice, his duty to protect the weak.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25652259,3,0,0,17,1500,1600,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (25652259, 'Queen''s Knight', 'This knight catches her opponents off guard, dominating them with swift yet graceful attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64788463,3,0,0,33,1600,1400,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (64788463, 'King''s Knight', 'When this card is Normal Summoned while you control "Queen''s Knight": You can Special Summon 1 "Jack''s Knight" from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41172955,3,0,81,33,1400,600,4,32,1,512);
INSERT OR REPLACE INTO "texts" VALUES (41172955, 'Green Gadget', 'When this card is Normal or Special Summoned: You can add 1 "Red Gadget" from your Deck to your hand.', 'Add 1 "Red Gadget" from your Deck to your hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86445415,3,0,81,33,1300,1500,4,32,1,512);
INSERT OR REPLACE INTO "texts" VALUES (86445415, 'Red Gadget', 'When this card is Normal or Special Summoned: You can add 1 "Yellow Gadget" from your Deck to your hand.', 'Add 1 "Yellow Gadget" from your Deck to your hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13839120,3,0,81,33,1200,1200,4,32,1,512);
INSERT OR REPLACE INTO "texts" VALUES (13839120, 'Yellow Gadget', 'When this card is Normal or Special Summoned: You can add 1 "Green Gadget" from your Deck to your hand.', 'Add 1 "Green Gadget" from your Deck to your hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73752131,3,0,0,33,1900,1700,4,2,32,67371016);
INSERT OR REPLACE INTO "texts" VALUES (73752131, 'Skilled Dark Magician', 'Each time a Spell Card is activated, place 1 Spell Counter on this card when that Spell Card resolves (max. 3). You can Tribute this card with 3 Spell Counters on it; Special Summon 1 "Dark Magician" from your hand, Deck, or Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46363422,3,0,110,33,1700,1900,4,2,16,67371008);
INSERT OR REPLACE INTO "texts" VALUES (46363422, 'Skilled White Magician', 'Each time a Spell Card is activated, place 1 Spell Counter on this card when that Spell Card resolves (max 3). You can Tribute this card with 3 Spell Counters on it; Special Summon 1 "Buster Blader" from your hand, Deck, or Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48115277,3,0,0,33,1000,1500,4,256,1,786432);
INSERT OR REPLACE INTO "texts" VALUES (48115277, 'Blockman', 'You can Tribute this card; Special Summon in Defense Position, a number of "Block Tokens" (Rock-Type/EARTH/Level 4/ATK 1000/DEF 1500) equal to the number of your turns this card has been face-up on your side of the field. These Tokens cannot declare an attack.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31305911,3,0,0,33,300,500,3,4,16,20971520);
INSERT OR REPLACE INTO "texts" VALUES (31305911, 'Marshmallon', 'After damage calculation, if this card was attacked, and was face-down at the start of the Damage Step: The attacking player takes 1000 damage. Cannot be destroyed by battle.', '1000damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40640057,3,0,0,33,300,200,1,8,32,8);
INSERT OR REPLACE INTO "texts" VALUES (40640057, 'Kuriboh', 'uring your opponent''s turn, at damage calculation: You can discard this card; you take no battle damage from that battle (this is a Quick Effect).', 'Reduce damage to 0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83764718,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (83764718, 'Monster Reborn', 'Target 1 monster in either player''s Graveyard; Special Summon it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72302403,3,0,0,2,0,0,0,0,0,67584);
INSERT OR REPLACE INTO "texts" VALUES (72302403, 'Swords of Revealing Light', 'Flip all monsters your opponent controls face-up. This card remains on the field for 3 of your opponent''s turns. While this card is face-up on the field, monsters your opponent controls cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75500286,3,0,0,2,0,0,0,0,0,1044);
INSERT OR REPLACE INTO "texts" VALUES (75500286, 'Gold Sarcophagus', 'Banish 1 card from your Deck, face-up. During your second Standby Phase after this card''s activation, add that card to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42664989,3,0,0,2,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (42664989, 'Card of Sanctity', 'Banish all other cards you control and in your hand (min.1 from each); draw until you have 2 cards in your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24094653,3,0,70,2,0,0,0,0,0,268697608);
INSERT OR REPLACE INTO "texts" VALUES (24094653, 'Polymerization', 'Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters from your hand or your side of the field as Fusion Materials.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2314238,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (2314238, 'Dark Magic Attack', 'If you control a "Dark Magician": Destroy all Spell and Trap Cards your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36045450,3,0,0,2,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (36045450, 'Magicians Unite', 'If you control 2 or more Attack Position Spellcaster-Type monsters: Target 1 of them; its ATK becomes 3000 until the end of this turn, but other Spellcaster-Type monsters you control cannot attack this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69542930,3,0,0,65538,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (69542930, 'Dedication through Light and Darkness', 'Tribute 1 "Dark Magician"; Special Summon 1 "Dark Magician of Chaos" from your hand, Deck, or Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76792184,3,0,0,130,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (76792184, 'Black Magic Ritual', 'This card is used to Ritual Summon "Magician of Black Chaos". You must also Tribute monsters from your hand or field whose total Levels equal 8 or more.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75622824,3,0,0,65538,0,0,0,0,0,786432);
INSERT OR REPLACE INTO "texts" VALUES (75622824, 'Tricky Spell 4', 'Send 1 face-up "The Tricky" you control to the Graveyard; Special Summon "Tricky Tokens" (Spellcaster-Type/WIND/Level 5/ATK 2000/DEF 1200) in Defense Position, equal to the number of monsters your opponent controls. "Tricky Tokens" cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6390406,3,0,0,2,0,0,0,0,0,1536);
INSERT OR REPLACE INTO "texts" VALUES (6390406, 'Emblem of Dragon Destroyer', 'Add 1 "Buster Blader" from your Deck or your Graveyard to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66865880,3,0,0,131074,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (66865880, 'Marshmallon Glasses', 'While this card and "Marshmallon" are face-up on your side of the field, your opponent cannot select a card other than "Marshmallon" as an attack target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44095762,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (44095762, 'Mirror Force', 'When an opponent''s monster declares an attack: Destroy all Attack Position monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50755,3,0,0,4,0,0,0,0,0,262656);
INSERT OR REPLACE INTO "texts" VALUES (50755, 'Magician''s Circle', 'When a Spellcaster-Type monster declares an attack: Each player Special Summons 1 Spellcaster-Type monster with 2000 or less ATK from their Deck in Attack Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12117532,3,0,0,131076,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (12117532, 'Shattered Axe', 'Activate this card by targeting 1 face-up monster on the field. During each of your Standby Phases: It loses 500 ATK. When that target is destroyed, destroy this card.', 'Lose attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13955608,3,0,0,131076,0,0,0,0,0,270336);
INSERT OR REPLACE INTO "texts" VALUES (13955608, 'Stronghold the Moving Fortress', 'Special Summon this card in Defense Position as an Effect Monster (Machine-Type/EARTH/Level 4/ATK 0/DEF 2000). (This card is also still a Trap Card.) While you control a "Green Gadget", "Red Gadget", and "Yellow Gadget", this card gains 3000 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68334074,3,0,0,4,0,0,0,0,0,67371008);
INSERT OR REPLACE INTO "texts" VALUES (68334074, 'Miracle Restoring', 'Remove 2 Spell Counters from your side of the field, then target 1 "Dark Magician" or "Buster Blader" in your Graveyard; Special Summon that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98502113,3,0,110,97,2900,2400,8,2,32,-2146426871);
INSERT OR REPLACE INTO "texts" VALUES (98502113, 'Dark Paladin', '"Dark Magician" + "Buster Blader"
Must be Fusion Summoned and cannot be Special Summoned by other ways. During either player''s turn, when a Spell Card is activated: You can discard 1 card; negate the activation, and if you do, destroy it. This card must be face-up on the field to activate and to resolve this effect. This card gains 500 ATK for each Dragon-Type monster on the field or in either player''s Graveyard.', 'Negate and Destroy Spell Card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
