BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (21844576,3,0,12296,17,1000,1000,3,1,8,0);
INSERT OR REPLACE INTO "texts" VALUES (21844576, 'Elemental HERO Avian', 'A winged Elemental HERO who wheels through the sky and manipulates the wind. His signature move, Featherbreak, gives villainy a blow from sky-high.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58932615,3,0,12296,17,1200,800,3,1,4,0);
INSERT OR REPLACE INTO "texts" VALUES (58932615, 'Elemental HERO Burstinatrix', 'A flame manipulator who was the first Elemental HERO woman. Her Burstfire burns away villainy.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84327329,3,0,12296,17,800,2000,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (84327329, 'Elemental HERO Clayman', 'An Elemental HERO with a clay body built-to-last. He''ll preserve his Elemental HERO colleagues at any cost.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20721928,3,0,12296,17,1600,1400,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (20721928, 'Elemental HERO Sparkman', 'An Elemental HERO and a warrior of light who proficiently wields many kinds of armaments. His Static Shockwave cuts off the path of villainy.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89943723,3,0,602120,17,2500,2000,7,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (89943723, 'Elemental HERO Neos', 'A new Elemental HERO has arrived from Neo-Space! When he initiates a Contact Fusion with a Neo-Spacian, his unknown powers are unleashed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57116033,3,0,164,33,300,200,1,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (57116033, 'Winged Kuriboh', 'If this card on the field is destroyed and sent to the Graveyard: Any further Battle Damage you take this turn becomes 0.', 'Reduce damage to 0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98585345,3,0,10747969,33,300,200,10,4,16,4194306);
INSERT OR REPLACE INTO "texts" VALUES (98585345, 'Winged Kuriboh LV10', 'Cannot be Normal Summoned or Set. Must be Special Summoned with "Transcendent Wings" and cannot be Special Summoned by other ways. During your opponent''s Battle Phase: You can Tribute this face-up card; destroy all Attack Position monsters your opponent controls and inflict damage to your opponent equal to the combined original ATK of those destroyed monster(s).', 'Destroy and inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6480253,3,0,0,33,800,1200,3,32,1,1040);
INSERT OR REPLACE INTO "texts" VALUES (6480253, 'Wroughtweiler', 'When this card is destroyed by battle and sent to the Graveyard: Target 1 "Elemental HERO" card and 1 "Polymerization" in your Graveyard; add both those targets to your hand.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79979666,3,0,12296,33,800,1200,4,1,2,262400);
INSERT OR REPLACE INTO "texts" VALUES (79979666, 'Elemental HERO Bubbleman', 'If this is the only card in your hand, you can Special Summon it (from your hand). When this card is Summoned: You can draw 2 cards. You must control no other cards and have no cards in your hand to activate and to resolve this effect.', 'Special Summon', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59793705,3,0,12296,33,2600,1800,7,1,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (59793705, 'Elemental HERO Bladedge', 'If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86188410,3,0,12296,33,1500,1600,4,1,1,33554432);
INSERT OR REPLACE INTO "texts" VALUES (86188410, 'Elemental HERO Wildheart', 'This card is unaffected by the effects of Trap Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89252153,3,0,12296,33,1600,1800,5,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (89252153, 'Elemental HERO Necroshade', ' Once, while this card is in the Graveyard, you can Normal Summon 1 Level 5 or higher "Elemental HERO" monster from your hand without Tributes.', 'Effect of "Elemental HERO Necroshade"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32679370,3,0,0,33,300,600,2,1,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (32679370, 'Hero Kid', 'When this card is Special Summoned: You can Special Summon any number of "Hero Kid"(s) from your Deck.', 'Special Summon', 'Special Summon "Hero Kid"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17955766,3,0,31,33,600,800,3,1,2,4194306);
INSERT OR REPLACE INTO "texts" VALUES (17955766, 'Neo-Spacian Aqua Dolphin', 'Once per turn: You can discard 1 card; look at your opponent''s hand and choose 1 Monster Card in it. If you control a monster with ATK greater than or equal to the ATK of the chosen card, destroy the chosen card and inflict 500 damage to your opponent. Otherwise, take 500 damage.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89621922,3,0,31,33,500,500,3,2048,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (89621922, 'Neo-Spacian Flare Scarab', 'This card gains 400 ATK for each Spell/Trap Card your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43237273,3,0,31,33,1000,500,3,16384,32,0);
INSERT OR REPLACE INTO "texts" VALUES (43237273, 'Neo-Spacian Dark Panther', 'Once per turn: You can target 1 face-up monster your opponent controls; until the End Phase, while you control this face-up card, this card''s name and effects become those of that target.', '效果复制', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85087012,3,0,0,33,400,400,3,32,1,8456);
INSERT OR REPLACE INTO "texts" VALUES (85087012, 'Card Trooper', 'Once per turn: You can choose a number from 1 to 3, then send that many cards from the top of your Deck to the Graveyard; this card gains 500 ATK for each card sent to the Graveyard this way, until the end of this turn. If this card you control is destroyed and sent to your Graveyard: Draw 1 card.', 'Gain attack', 'Draw card', 'Send how many cards to Graveyard?', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54959865,3,0,31,33,800,600,3,512,8,8388608);
INSERT OR REPLACE INTO "texts" VALUES (54959865, 'Neo-Spacian Air Hummingbird', 'Once per turn: You can gain 500 Life Points for each card in your opponent''s hand.', 'LP Recovery', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80344569,3,0,31,33,900,300,3,256,1,1040);
INSERT OR REPLACE INTO "texts" VALUES (80344569, 'Neo-Spacian Grand Mole', 'At the start of the Damage Step, if this card battles an opponent''s monster: You can return both monsters to the hand (without damage calculation).', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17732278,3,0,31,33,300,900,3,1024,16,133376);
INSERT OR REPLACE INTO "texts" VALUES (17732278, 'Neo-Spacian Glow Moss', 'When this card attacks or is attacked: Your opponent draws 1 card. Reveal it, and based on its type apply this effect. ● Monster: End the Battle Phase. ● Spell: If this card is attacking, you can change it to a direct attack instead. ● Trap: Change this card to Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40044918,3,0,12296,33,1800,300,4,1,8,513);
INSERT OR REPLACE INTO "texts" VALUES (40044918, 'Elemental HERO Stratos', 'When this card is Normal or Special Summoned: You can activate 1 of these effects.
● You can destroy Spell/Trap Cards on the field, up to the number of "HERO" monsters you control, except this card.
● Add 1 "HERO" monster from your Deck to your hand.', 'Select effect', 'You destroy Spell/Trap Cards on the field, up to the number of other "HERO" monsters you control.', 'Add 1 "HERO" monster from your Deck to your hand.', 'Do you want to destroy Spell/Trap Cards on the field?', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37195861,3,0,12296,33,1500,1200,4,1,2,1040);
INSERT OR REPLACE INTO "texts" VALUES (37195861, 'Elemental HERO Ocean', 'Once per turn, during your Standby Phase: You can target 1 "HERO" monster you control or in your Graveyard; return that target to the hand.', 'Return "HERO" monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80908502,3,0,12296,33,2100,800,4,1,16,520);
INSERT OR REPLACE INTO "texts" VALUES (80908502, 'Elemental HERO Captain Gold', 'You can discard this card to the Graveyard; add 1 "Skyscraper" from your Deck to your hand. If "Skyscraper" is not face-up on the field, destroy this card.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4906301,3,0,0,33,600,1300,3,1,32,65536);
INSERT OR REPLACE INTO "texts" VALUES (4906301, 'Necro Gardna', 'During your opponent''s turn: You can banish this card from your Graveyard; negate the next attack this turn from a monster your opponent controls (this is a Quick Effect).', '1次攻击无效', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69884162,3,0,602120,2081,1900,1300,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (69884162, 'Elemental HERO Neos Alius', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it become an Effect Monster with this effect.
● This face-up card''s name becomes "Elemental HERO Neos".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58554959,3,0,24584,33,2600,1800,7,8,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (58554959, 'Evil HERO Malicious Edge', 'If your opponent controls a monster, you can Tribute Summon this card with 1 Tribute. If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', 'Tribute Summon with 1 tribute', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95943058,3,0,24584,33,1600,0,4,8,1,294912);
INSERT OR REPLACE INTO "texts" VALUES (95943058, 'Evil HERO Infernal Gainer', 'During your Main Phase 1: You can banish this card, then target 1 Fiend-Type monster you control; that target can make a second attack during each Battle Phase. During your second Standby Phase after this effect was activated: Special Summon this banished card in Attack Position.', 'Attack twice', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50304345,3,0,24584,33,300,600,2,8,32,256);
INSERT OR REPLACE INTO "texts" VALUES (50304345, 'Evil HERO Infernal Prodigy', 'If you control no monsters, you can Special Summon this card (from your hand) in face-up Attack Position. During the End Phase, if you Tributed this card this turn to Tribute Summon a "HERO" monster: Draw 1 card.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26701483,3,0,0,33,400,400,3,2,1,4);
INSERT OR REPLACE INTO "texts" VALUES (26701483, 'Card Ejector', 'Once per turn: You can target 1 card in your opponent''s Graveyard; banish that target.', '对方墓地存在的1张卡从游戏中除外', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89312388,3,0,12296,33,1700,1100,4,1,16,268435464);
INSERT OR REPLACE INTO "texts" VALUES (89312388, 'Elemental HERO Prisma', 'Once per turn: You can reveal 1 Fusion Monster from your Extra Deck, then send 1 of the Fusion Material Monsters listed on that card from your Main Deck to the Graveyard; this card''s name becomes the sent monster''s name until the End Phase.', 'Change name', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75434695,3,0,12296,33,1000,2000,4,1,1,1552);
INSERT OR REPLACE INTO "texts" VALUES (75434695, 'Elemental HERO Woodsman', 'Once per turn, during your Standby Phase: You can add 1 "Polymerization" from your Deck or Graveyard to your hand.', 'Add 1 "Polymerization" to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62107981,3,0,12296,33,600,1000,3,1024,1,139266);
INSERT OR REPLACE INTO "texts" VALUES (62107981, 'Elemental HERO Knospe', 'Each time this card inflicts Battle Damage to your opponent: It gains 100 ATK and loses 100 DEF. While you control another face-up "Elemental HERO" monster, your opponent cannot target this card for an attack, and this card can attack your opponent directly.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51085303,3,0,12296,33,1900,2000,6,1024,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (51085303, 'Elemental HERO Poison Rose', 'Cannot be Normal Summoned or Set. Must be Special Summoned with "Rose Bud" and cannot be Special Summoned by other ways. Each time this card inflicts Battle Damage to your opponent: It gains 200 ATK and loses 200 DEF. Your opponent can only target "Elemental HERO Poison Rose" for attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98266377,3,0,12296,33,1600,1200,4,128,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (98266377, 'Elemental HERO Heat', 'This card gains 200 ATK for each face-up "Elemental HERO" monster you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95362816,3,0,12296,33,1300,1000,4,128,4,4194304);
INSERT OR REPLACE INTO "texts" VALUES (95362816, 'Elemental HERO Lady Heat', 'During each of your End Phases: Inflict 200 damage to your opponent for each face-up "Elemental HERO" monster you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9327502,3,0,12296,33,1000,1500,4,4096,16,263168);
INSERT OR REPLACE INTO "texts" VALUES (9327502, 'Elemental HERO Voltic', 'When this card inflicts Battle Damage to your opponent: You can target 1 of your banished "Elemental HERO" monsters; Special Summon that target.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5126490,3,0,9,33,3000,3000,10,2,16,29622272);
INSERT OR REPLACE INTO "texts" VALUES (5126490, 'Neos Wiseman', 'Cannot be Normal Summoned or Set. Must be Special Summoned (from your hand) by sending 1 face-up "Elemental HERO Neos" and 1 face-up "Yubel" you control to the Graveyard, and cannot be Special Summoned by other ways. This card cannot be destroyed by card effects. At the end of the Damage Step, if this card battled an opponent''s monster: Inflict damage to your opponent equal to the ATK of the monster it battled, and you gain Life Points equal to that monster''s DEF.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30915572,3,0,0,33,800,800,3,16384,1,4456448);
INSERT OR REPLACE INTO "texts" VALUES (30915572, 'Gallis the Star Beast', 'You can reveal this card in your hand; send the top card of your Deck to the Graveyard, then, if it was a monster, inflict damage to your opponent equal to its Level x 200 and Special Summon this card from your hand, otherwise destroy this card.', '卡组最上面的卡送去墓地', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15341821,3,0,0,33,300,300,3,1024,1,786432);
INSERT OR REPLACE INTO "texts" VALUES (15341821, 'Dandylion', 'When this card is sent to the Graveyard: Special Summon 2 "Fluff Tokens" (Plant-Type/WIND/Level 1/ATK 0/DEF 0) in Defense Position. These Tokens cannot be Tributed for a Tribute Summon during the turn they are Special Summoned.', 'Special Summon token', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33776734,3,0,10747969,33,-2,-2,9,4,16,270340);
INSERT OR REPLACE INTO "texts" VALUES (33776734, 'Winged Kuriboh LV9', 'During either player''s turn, as Chain Link 3 or higher: You can Special Summon this card from your hand. Spell Cards that have been activated are banished instead of being sent to the Graveyard. The ATK and DEF of this card are each equal to the number of Spell Cards in your opponent''s Graveyard x 500. You can only control 1 face-up "Winged Kuriboh LV9".', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42256406,3,0,0,33,400,400,3,1,1,10240);
INSERT OR REPLACE INTO "texts" VALUES (42256406, 'Card Blocker', 'When this card is Summoned: Change it to Defense Position. When a face-up monster you control is targeted for an attack: You can change the target to this card. When this card is targeted for an attack: You can choose a number from 1 to 3, then send that many cards from the top of your Deck to the Graveyard; this card gains 500 DEF for each card sent, until the End Phase.', 'Defense Position', 'Change attack target', 'Gain DEF', 'Select number of cards to send to Graveyard', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35809262,3,0,12296,97,2100,1200,6,1,8,4194304);
INSERT OR REPLACE INTO "texts" VALUES (35809262, 'Elemental HERO Flame Wingman', '"Elemental HERO Avian" + "Elemental HERO Burstinatrix"
Must be Fusion Summoned and cannot be Special Summoned by other ways. When this card destroys a monster by battle and sends it to the Graveyard: Inflict damage to your opponent equal to the ATK of the destroyed monster.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61204971,3,0,12296,97,2400,1500,6,1,16,2);
INSERT OR REPLACE INTO "texts" VALUES (61204971, 'Elemental HERO Thunder Giant', '"Elemental HERO Sparkman" + "Elemental HERO Clayman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. Once per turn: You can discard 1 card to target 1 face-up monster on the field with original ATK less than the ATK of this card; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47737087,3,0,12296,97,2000,2500,6,1,1,139264);
INSERT OR REPLACE INTO "texts" VALUES (47737087, 'Elemental HERO Rampart Blaster', '"Elemental HERO Clayman" + "Elemental HERO Burstinatrix"
Must be Fusion Summoned and cannot be Special Summoned by other ways. This card can attack while in face-up Defense Position, but only if your opponent controls no monsters, and if it does, this card''s ATK is halved during damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83121692,3,0,12296,97,2800,2800,8,1,8,16777216);
INSERT OR REPLACE INTO "texts" VALUES (83121692, 'Elemental HERO Tempest', '"Elemental HERO Avian" + "Elemental HERO Sparkman" + "Elemental HERO Bubbleman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. You can send 1 other card you control to the Graveyard to target 1 monster you control; while this card is face-up on the field, that monster cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10526791,3,0,12296,97,2600,2300,8,1,1,32768);
INSERT OR REPLACE INTO "texts" VALUES (10526791, 'Elemental HERO Wildedge', '"Elemental HERO Wildheart" + "Elemental HERO Bladedge"
Must be Fusion Summoned and cannot be Special Summoned by other ways. This card can attack every monster your opponent controls (one attack on each monster per Battle Phase).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25366484,3,0,12296,97,2500,2100,8,1,16,4202496);
INSERT OR REPLACE INTO "texts" VALUES (25366484, 'Elemental HERO Shining Flare Wingman', '"Elemental HERO Flame Wingman" + "Elemental HERO Sparkman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. This card gains 300 ATK for each "Elemental HERO" card in your Graveyard. When this card destroys a monster by battle and sends it to the Graveyard: Inflict damage to your opponent equal to the ATK of the destroyed monster in the Graveyard.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81197327,3,0,12296,97,1800,1000,5,1,2,8388608);
INSERT OR REPLACE INTO "texts" VALUES (81197327, 'Elemental HERO Steam Healer', '"Elemental HERO Burstinatrix" + "Elemental HERO Bubbleman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. When this card destroys a monster by battle and sends it to the Graveyard: Gain Life Points equal to the ATK of that destroyed monster in the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29343734,3,0,12296,97,2900,2600,10,1,16,2105376);
INSERT OR REPLACE INTO "texts" VALUES (29343734, 'Elemental HERO Electrum', '"Elemental HERO Avian" + "Elemental HERO Burstinatrix" + "Elemental HERO Clayman" + "Elemental HERO Bubbleman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. While face-up on the field, this card is also WIND, WATER, FIRE, and EARTH-Attribute. When this card is Fusion Summoned: Shuffle all banished cards into the Deck(s). This card gains 300 ATK for each monster your opponent controls that shares an Attribute with this card.', 'Return to deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52031567,3,0,12296,97,1900,3000,6,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (52031567, 'Elemental HERO Mudballman', '"Elemental HERO Bubbleman" + "Elemental HERO Clayman"
Must be Fusion Summoned and cannot be Special Summoned by other ways.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14225239,3,0,12296,97,1400,1000,5,1,2,131072);
INSERT OR REPLACE INTO "texts" VALUES (14225239, 'Elemental HERO Mariner', '"Elemental HERO Bubbleman" + "Elemental HERO Avian"
Must be Fusion Summoned and cannot be Special Summoned by other ways. While you have any face-down card(s) in your Spell & Trap Card Zones, this card can attack your opponent directly.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55615891,3,0,12296,97,1900,2300,8,1,1,1);
INSERT OR REPLACE INTO "texts" VALUES (55615891, 'Elemental HERO Wild Wingman', '"Elemental HERO Wildheart" + "Elemental HERO Avian"
Must be Fusion Summoned and cannot be Special Summoned by other ways. You can discard 1 card to target 1 Spell/Trap Card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81003500,3,0,1454088,97,1900,1800,6,1,32,262146);
INSERT OR REPLACE INTO "texts" VALUES (81003500, 'Elemental HERO Necroid Shaman', '"Elemental HERO Wildheart" + "Elemental HERO Necroshade"
Must be Fusion Summoned and cannot be Special Summoned by other ways. When this card is Special Summoned: Target 1 monster your opponent controls; destroy that target, then Special Summon 1 monster from your opponent''s Graveyard to their side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55171412,3,0,602120,97,2500,2000,7,1,2,96);
INSERT OR REPLACE INTO "texts" VALUES (55171412, 'Elemental HERO Aqua Neos', '"Elemental HERO Neos" + "Neo-Spacian Aqua Dolphin"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization".) Once per turn: You can discard 1 card; destroy 1 random card in your opponent''s hand. During the End Phase: Shuffle this card into the Extra Deck.', 'Destroy card in opponent''s hand', 'Back to Extra Deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81566151,3,0,602120,97,2500,2000,7,1,4,8224);
INSERT OR REPLACE INTO "texts" VALUES (81566151, 'Elemental HERO Flare Neos', '"Elemental HERO Neos" + "Neo-Spacian Flare Scarab"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization".) This card gains 400 ATK for each Spell/Trap Card on the field. During the End Phase: Shuffle this card into the Extra Deck.', 'Back to Extra Deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28677304,3,0,602120,97,2500,2000,7,1,32,-2147483616);
INSERT OR REPLACE INTO "texts" VALUES (28677304, 'Elemental HERO Dark Neos', '"Elemental HERO Neos" + "Neo-Spacian Dark Panther"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization".) If this card is not already targeting a monster with its effect: You can target 1 face-up Effect Monster on the field; while you control this face-up card, that target''s effect on the field is negated. During the End Phase: Shuffle this card into the Extra Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48996569,3,0,602120,97,2500,2000,7,1,1,48);
INSERT OR REPLACE INTO "texts" VALUES (48996569, 'Elemental HERO Grand Neos', '"Elemental HERO Neos" + "Neo-Spacian Grand Mole"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization".) Once per turn: You can target 1 monster your opponent controls; return that target to the hand. During the End Phase: Shuffle this card into the Extra Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85507811,3,0,602120,97,2500,2000,7,1,16,35);
INSERT OR REPLACE INTO "texts" VALUES (85507811, 'Elemental HERO Glow Neos', '"Elemental HERO Neos" + "Neo-Spacian Glow Moss"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization".) During the End Phase: Shuffle this card into the Extra Deck. Once per turn, during your Main Phase 1: You can target 1 face-up card your opponent controls; destroy that target, then apply the effect based on its type. ● Monster: This card cannot attack this turn. ● Spell: This card can attack your opponent directly this turn. ● Trap: Change this card to Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5128859,3,0,602120,97,2800,2300,8,1,2,64);
INSERT OR REPLACE INTO "texts" VALUES (5128859, 'Elemental HERO Marine Neos', '"Elemental HERO Neos" + "Neo-Spacian Marine Dolphin"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization"). Once per turn: You can destroy 1 random card in your opponent''s hand.', '手札破壊', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41517968,3,0,12296,97,2000,1000,6,1,32,16386);
INSERT OR REPLACE INTO "texts" VALUES (41517968, 'Elemental HERO Darkbright', '"Elemental HERO Sparkman" + "Elemental HERO Necroshade"
Must be Fusion Summoned and cannot be Special Summoned by other ways. If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent. If this card attacks, change it to Defense Position at the end of the Damage Step. If this card is destroyed: Target 1 monster your opponent controls; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78512663,3,0,602120,97,3000,2500,9,1,4,8240);
INSERT OR REPLACE INTO "texts" VALUES (78512663, 'Elemental HERO Magma Neos', '"Elemental HERO Neos" + "Neo-Spacian Flare Scarab" + "Neo-Spacian Grand Mole"
Must be first Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization"). This card gains 400 ATK for each card on the field. During the End Phase: Shuffle this card into the Extra Deck. When this card is shuffled into the Extra Deck this way: Return all cards on the field to the hand.', 'Back to Extra Deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17032740,3,0,602120,97,3000,2500,9,1,32,-2013263822);
INSERT OR REPLACE INTO "texts" VALUES (17032740, 'Elemental HERO Chaos Neos', '"Elemental HERO Neos" + "Neo-Spacian Dark Panther" + "Neo-Spacian Glow Moss"
Must be first Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization"). During the End Phase: Shuffle this card into the Extra Deck, then Set all face-up monsters on the field. Once per turn, during your Main Phase 1: You can toss a coin 3 times. ● 3 Heads: Destroy all monsters your opponent controls. ● 2 Heads: For the rest of the turn, the effects of all face-up monsters your opponent controls are negated. ● 1 Head: Return all monsters you control to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60493189,3,0,12296,97,2600,2300,8,1,1,16386);
INSERT OR REPLACE INTO "texts" VALUES (60493189, 'Elemental HERO Plasma Vice', '"Elemental HERO Sparkman" + "Elemental HERO Bladedge"
Must be Fusion Summoned and cannot be Special Summoned by other ways. If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent. You can discard 1 card to target 1 Attack Position monster your opponent controls; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22160245,3,0,16932872,97,2100,1200,6,8,4,4210688);
INSERT OR REPLACE INTO "texts" VALUES (22160245, 'Evil HERO Inferno Wing', '"Elemental HERO Avian" + "Elemental HERO Burstinatrix"
Must be Special Summoned with "Dark Fusion" and cannot be Special Summoned by other ways. If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent. When this card destroys a monster by battle and sends it to the Graveyard: Inflict damage to your opponent equal to either the ATK or DEF (whichever is higher) of the destroyed monster in the Graveyard.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21947653,3,0,16932872,97,2400,1500,6,8,16,2);
INSERT OR REPLACE INTO "texts" VALUES (21947653, 'Evil HERO Lightning Golem', '"Elemental HERO Sparkman" + "Elemental HERO Clayman"
Must be Special Summoned with "Dark Fusion" and cannot be Special Summoned by other ways. Once per turn: You can target 1 monster on the field; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58332301,3,0,16932872,97,-2,0,8,8,1,10240);
INSERT OR REPLACE INTO "texts" VALUES (58332301, 'Evil HERO Dark Gaia', '1 Fiend-Type monster + 1 Rock-Type monster
Must be Special Summoned with "Dark Fusion" and cannot be Special Summoned by other ways. The original ATK of this card is equal to the combined original ATK of the Fusion Material Monsters used to Fusion Summon it. When this card declares an attack: You can change all Defense Position monsters your opponent controls to face-up Attack Position. (Flip Effects are not activated at this time.)', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13293158,3,0,16932872,97,1900,2300,8,8,1,1);
INSERT OR REPLACE INTO "texts" VALUES (13293158, 'Evil HERO Wild Cyclone', '"Elemental HERO Avian" + "Elemental HERO Wildheart"
Must be Special Summoned with "Dark Fusion" and cannot be Special Summoned by other ways. If this card attacks, your opponent cannot activate any Spell/Trap Cards until the end of the Damage Step. When this card inflicts Battle Damage to your opponent: Destroy all face-down Spell and Trap Cards your opponent controls.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50282757,3,0,16932872,97,2000,2500,6,8,4,4194304);
INSERT OR REPLACE INTO "texts" VALUES (50282757, 'Evil HERO Infernal Sniper', '"Elemental HERO Clayman" + "Elemental HERO Burstinatrix"
Must be Special Summoned with "Dark Fusion" and cannot be Special Summoned by other ways. This card cannot be destroyed by Spell Cards. During each of your Standby Phase: Inflict 1000 damage to your opponent. This card must be in face-up Defense Position to activate and to resolve this effect.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86676862,3,0,16932872,97,3500,2100,8,8,4,65536);
INSERT OR REPLACE INTO "texts" VALUES (86676862, 'Evil HERO Malicious Fiend', '"Evil HERO Malicious Edge" + 1 Level 6 or higher Fiend-Type monster
Must be Special Summoned with "Dark Fusion" and cannot be Special Summoned by other ways. During your opponent''s Battle Phase, all monsters they control are changed to face-up Attack Position, and each monster they control must attack this card, if able.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49352945,3,0,602120,97,3000,2500,9,1,8,2081);
INSERT OR REPLACE INTO "texts" VALUES (49352945, 'Elemental HERO Storm Neos', '"Elemental HERO Neos" + "Neo-Spacian Air Hummingbird" + "Neo-Spacian Aqua Dolphin"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization".) Once per turn: You can destroy all Spell and Trap Cards on the field. During the End Phase: Shuffle this card into the Extra Deck. When this card is shuffled into the Extra Deck this way: Shuffle all cards on the field into the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86346643,3,0,9,97,4500,3000,10,1,16,32);
INSERT OR REPLACE INTO "texts" VALUES (86346643, 'Rainbow Neos', '"Elemental HERO Neos" + "Rainbow Dragon" or "Rainbow Dark Dragon"
Must be Fusion Summoned with the above Fusion Material Monsters and cannot be Special Summoned by other ways. Once per turn: You can activate 1 of these effects. ● Send 1 monster you control to the Graveyard; shuffle all monsters your opponent controls into the Deck. ● Send 1 Spell/Trap Card you control to the Graveyard; shuffle all Spell and Trap Cards your opponent controls into the Deck. ● Send 1 card from the top of your Deck to the Graveyard; shuffle all cards in your opponent''s Graveyard into the Deck.', 'Select effect', 'Send 1 monster you control to the Graveyard; shuffle all monsters your opponent controls into the Deck.', 'Send 1 Spell/Trap Card you control to the Graveyard; shuffle all Spell and Trap Cards your opponent controls into the Deck.', 'Send 1 card from the top of your Deck to the Graveyard; shuffle all cards in your opponent''s Graveyard into the Deck.', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74711057,3,0,12296,97,2500,2000,8,1,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (74711057, 'Elemental HERO Terra Firma', '"Elemental HERO Ocean" + "Elemental HERO Woodsman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. You can Tribute 1 face-up "Elemental HERO" monster; this card gains ATK equal to the Tributed monster''s ATK, until the End Phase.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68745629,3,0,12296,97,2300,1600,8,128,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (68745629, 'Elemental HERO Inferno', '"Elemental HERO Heat" + "Elemental HERO Lady Heat"
Must be Fusion Summoned and cannot be Special Summoned by other ways. If this card battles a WATER monster, this card gains 1000 ATK during the Damage Step only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31111109,3,0,602120,97,2500,2500,12,1,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (31111109, 'Elemental HERO Divine Neos', 'Must be Fusion Summoned using any 5 "Neos", "Neo Space", "Neo-Spacian", or "HERO" monsters, including at least 1 "Neos" or "Neo Space" monster, 1 "Neo-Spacian" monster, and 1 "HERO" monster, and cannot be Special Summoned by other ways. Once per turn: You can banish 1 "Neos", "Neo Space", "Neo-Spacian", or "HERO" monster from your Graveyard; this card gains 500 ATK, and until the End Phase it also gains the banished monster''s effects.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45906428,3,0,70,2,0,0,0,0,0,268697604);
INSERT OR REPLACE INTO "texts" VALUES (45906428, 'Miracle Fusion', 'Banish, from your side of the field or your Graveyard, the Fusion Material Monsters that are listed on an "Elemental HERO" Fusion Monster Card, then Special Summon that Fusion Monster from your Extra Deck. (This Special Summon is treated as a Fusion Summon.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25573054,3,0,0,65538,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (25573054, 'Transcendent Wings', 'Send 1 "Winged Kuriboh" you control and 2 cards from your hand to the Graveyard; Special Summon 1 "Winged Kuriboh LV10" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61968753,3,0,0,65538,0,0,0,0,0,264192);
INSERT OR REPLACE INTO "texts" VALUES (61968753, 'Bubble Shuffle', 'Target 1 face-up Attack Position "Elemental HERO Bubbleman" you control and 1 face-up Attack Position monster your opponent controls; change both those targets to Defense Position, then Tribute that 1 "Elemental HERO Bubbleman", then Special Summon 1 "Elemental HERO" monster from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97362768,3,0,0,262146,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (97362768, 'Spark Blaster', 'Equip only to "Elemental HERO Sparkman". During your Main Phase: You can target 1 face-up monster; change the battle position of that target. After you use this effect 3 times, destroy this card.', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63035430,3,0,0,524290,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (63035430, 'Skyscraper', 'When an "Elemental HERO" monster attacks, if its ATK is lower than the ATK of the attack target, the attacking monster gains 1000 ATK during damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19394153,3,0,0,2,0,0,0,0,0,32768);
INSERT OR REPLACE INTO "texts" VALUES (19394153, 'Feather Shot', 'Target 1 face-up "Elemental HERO Avian" you control; during this turn, that target can attack a number of times equal to the number of monsters you control when this card resolves, but cannot attack directly, and other monsters you control cannot attack this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27191436,3,0,0,2,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (27191436, 'Burst Return', 'If you control a face-up "Elemental HERO Burstinatrix": Return all face-up "Elemental HERO" monsters on the field to the hand, except "Elemental HERO Burstinatrix".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67951831,3,0,0,2,0,0,0,0,0,40960);
INSERT OR REPLACE INTO "texts" VALUES (67951831, 'Hero Heart', 'Target 1 face-up "Elemental HERO" monster you control; halve its ATK until the end of this turn, but it can attack twice during this turn''s Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29612557,3,0,0,262146,0,0,0,0,0,4202497);
INSERT OR REPLACE INTO "texts" VALUES (29612557, 'Cyclone Boomerang', 'Equip only to "Elemental HERO Wildheart". It gains 500 ATK. When the equipped monster is destroyed by a card effect and sent to the Graveyard: Destroy all Spell and Trap Cards on the field, then inflict 100 damage to your opponent for each Spell/Trap Card destroyed by this effect.', 'Destroy and inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20065322,3,0,0,65538,0,0,0,0,0,262656);
INSERT OR REPLACE INTO "texts" VALUES (20065322, 'The Flute of Summoning Kuriboh', 'Add 1 "Kuriboh" or 1 "Winged Kuriboh" from your Deck to your hand, OR Special Summon 1 "Kuriboh" or 1 "Winged Kuriboh" from your Deck.', 'Add card', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74825788,3,0,0,2,0,0,0,0,0,24576);
INSERT OR REPLACE INTO "texts" VALUES (74825788, 'H - Heated Heart', 'Target 1 face-up monster you control; until the End Phase, it gains 500 ATK, and if it attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (213326,3,0,0,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (213326, 'E - Emergency Call', 'Add 1 "Elemental HERO" monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37318031,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (37318031, 'R - Righteous Justice', 'Destroy Spell/Trap Cards equal to the number of face-up "Elemental HERO" cards you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63703130,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (63703130, 'O - Oversoul', 'Target 1 "Elemental HERO" Normal Monster in your Graveyard; Special Summon that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (191749,3,0,0,2,0,0,0,0,0,393216);
INSERT OR REPLACE INTO "texts" VALUES (191749, 'Hero Flash!!', 'Banish "H - Heated Heart", "E - Emergency Call", "R - Righteous Justice" and "O - Oversoul" from your Graveyard; Special Summon 1 "Elemental HERO" Normal Monster from your Deck. All "Elemental HERO" Normal Monsters you currently control can attack your opponent directly this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78387742,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (78387742, 'Fake Hero', 'Special Summon 1 "Elemental HERO" monster from your hand. That monster cannot attack, and returns to the hand during the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42015635,3,0,9,524290,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (42015635, 'Neo Space', '"Elemental HERO Neos" and all Fusion Monsters that list "Elemental HERO Neos" as a Fusion Material Monster gain 500 ATK. Fusion Monsters that list "Elemental HERO Neos" as a Fusion Material Monster do not have to have activate their effects during the End Phase that shuffle them into the Extra Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1845204,3,0,70,2,0,0,0,0,0,268697600);
INSERT OR REPLACE INTO "texts" VALUES (1845204, 'Instant Fusion', 'Pay 1000 Life Points; Special Summon 1 Level 5 or lower Fusion Monster from your Extra Deck. (This Special Summon is treated as a Fusion Summon). The Fusion Monster Special Summoned by this effect cannot attack, and is destroyed during the End Phase. Only 1 "Instant Fusion" can be activated per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47274077,3,0,9,262146,0,0,0,0,0,4202528);
INSERT OR REPLACE INTO "texts" VALUES (47274077, 'Neos Force', 'Equip only to "Elemental HERO Neos". It gains 800 ATK. When it destroys a monster by battle and sends it to the Graveyard: Inflict damage to your opponent equal to the original ATK of the destroyed monster. During the End Phase: Shuffle this card into the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47596607,3,0,0,524290,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (47596607, 'Skyscraper 2 - Hero City', 'Once per turn, during your Main Phase, if you can control this card: You can target 1 "Elemental HERO" monster in your Graveyard that was destroyed by battle; Special Summon that target.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55428811,3,0,0,2,0,0,0,0,0,288);
INSERT OR REPLACE INTO "texts" VALUES (55428811, 'Fifth Hope', 'Target 5 "Elemental HERO" cards in your Graveyard; shuffle them into the Deck, then draw 2 cards (draw 3 cards instead, if you had no other cards on your side of the field and in your hand when you activated this card).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94820406,3,0,70,2,0,0,0,0,0,269746176);
INSERT OR REPLACE INTO "texts" VALUES (94820406, 'Dark Fusion', 'Send, from your hand or your side of the field to the Graveyard, the Fusion Material Monsters that are listed on a Fiend-Type Fusion Monster Card, then Special Summon that Fusion Monster from your Extra Deck. (This Special Summon is treated as a Fusion Summon). The Special Summoned monster cannot be targeted by the opponent''s Spells, Traps, or card effects this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12071500,3,0,0,2,0,0,0,0,0,268697600);
INSERT OR REPLACE INTO "texts" VALUES (12071500, 'Dark Calling', 'Banish, from your hand or your Graveyard, the Fusion Material Monsters listed on a Fusion Monster Card that can only be Special Summoned with "Dark Fusion", then Special Summon that monster from your Extra Deck. (This Special Summon is treated as a Fusion Summon with "Dark Fusion".)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
