BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (46986414,3,0,162,17,2500,2100,7,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (46986414, 'Dark Magician', 'The ultimate wizard in terms of attack and defense.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6368038,3,0,189,17,2300,2100,7,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (6368038, 'Gaia The Fierce Knight', 'A knight whose horse travels faster than the wind. His battle-charge is a force to be reckoned with.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91152256,3,0,0,17,1400,1200,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (91152256, 'Celtic Guardian', 'An elf who learned to wield a sword, he baffles enemies with lightning-swift attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90357090,3,0,0,17,1200,800,3,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (90357090, 'Silver Fang', 'A snow wolf that''s beautiful to the eye, but absolutely vicious in battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15025844,3,0,0,17,800,2000,4,2,16,0);
INSERT OR REPLACE INTO "texts" VALUES (15025844, 'Mystical Elf', 'A delicate elf that lacks offense, but has a terrific defense backed by mystical power.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28279543,3,0,0,17,2000,1500,5,8192,32,0);
INSERT OR REPLACE INTO "texts" VALUES (28279543, 'Curse of Dragon', 'A wicked dragon that taps into dark forces to execute a powerful attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13039848,3,0,0,17,1300,2000,3,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (13039848, 'Giant Soldier of Stone', 'A giant warrior made of stone. A punch from this creature has earth-shaking results.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41392891,3,0,0,17,1300,1400,4,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (41392891, 'Feral Imp', 'A playful little fiend that lurks in the dark, waiting to attack an unwary enemy.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87796900,3,0,0,17,1400,1200,4,8192,8,0);
INSERT OR REPLACE INTO "texts" VALUES (87796900, 'Winged Dragon, Guardian of the Fortress 1', 'A dragon commonly found guarding mountain fortresses. Its signature attack is a sweeping dive from out of the blue.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70781052,3,0,69,17,2500,1200,6,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (70781052, 'Summoned Skull', 'A fiend with dark powers for confusing the enemy. Among the Fiend-Type monsters, this monster boasts considerable force.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5818798,3,0,27,17,1500,1200,4,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (5818798, 'Gazelle the King of Mythical Beasts', 'This monster moves so fast that it looks like an illusion to mortal eyes.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99785935,3,0,0,17,1400,1700,4,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (99785935, 'Alpha the Magnet Warrior', 'Alpha, Beta, and Gamma meld as one to form a powerful monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39256679,3,0,0,17,1700,1600,4,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (39256679, 'Beta the Magnet Warrior', 'Alpha, Beta, and Gamma meld as one to form a powerful monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11549357,3,0,0,17,1500,1800,4,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (11549357, 'Gamma the Magnet Warrior', 'Alpha, Beta, and Gamma meld as one to form a powerful monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25652259,3,0,0,17,1500,1600,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (25652259, 'Queen''s Knight', 'This knight catches her opponents off guard, dominating them with swift yet graceful attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90876561,3,0,0,17,1900,1000,5,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (90876561, 'Jack''s Knight', 'A strong master swordsman. His loyalty is to justice, his duty to protect the weak.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64788463,3,0,0,33,1600,1400,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (64788463, 'King''s Knight', 'When this card is Normal Summoned while you control "Queen''s Knight": You can Special Summon 1 "Jack''s Knight" from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40640057,3,0,0,33,300,200,1,8,32,8);
INSERT OR REPLACE INTO "texts" VALUES (40640057, 'Kuriboh', 'uring your opponent''s turn, at damage calculation: You can discard this card; you take no battle damage from that battle (this is a Quick Effect).', 'Reduce damage to 0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95727991,3,0,0,33,1000,2000,5,64,2,4194304);
INSERT OR REPLACE INTO "texts" VALUES (95727991, 'Catapult Turtle', 'Once per turn: You can Tribute 1 monster; inflict damage to your opponent equal to half the Tributed monster''s ATK on the field.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78193831,3,0,0,33,2600,2300,7,1,1,1056768);
INSERT OR REPLACE INTO "texts" VALUES (78193831, 'Buster Blader', 'This card gains 500 ATK for each Dragon-Type monster your opponent controls or is in their Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75347539,3,0,0,33,3500,3850,8,256,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (75347539, 'Valkyrion the Magna Warrior', 'This card cannot be Normal Summoned or Set. This card can only be Special Summoned by Tributing "Alpha The Magnet Warrior", "Beta The Magnet Warrior", and "Gamma The Magnet Warrior" from your hand or your side of the field. You can Tribute this card to Special Summon "Alpha The Magnet Warrior", "Beta The Magnet Warrior", and "Gamma The Magnet Warrior" from your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38033121,3,0,279052450,33,2000,1700,6,2,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (38033121, 'Dark Magician Girl', 'This card gains 300 ATK for every "Dark Magician" or "Magician of Black Chaos" in either player''s Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71413901,3,0,110,33,1600,1000,4,2,32,67117057);
INSERT OR REPLACE INTO "texts" VALUES (71413901, 'Breaker the Magical Warrior', 'If this card is Normal Summoned: Place 1 Spell Counter on it (max. 1). This card gains 300 ATK for each Spell Counter on it. You can remove 1 Spell Counter from this card, then target 1 Spell/Trap Card on the field; destroy that target.', 'Place spell counter', 'Gain attack', 'Destroy 1 Spell or Trap Card', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49217579,3,0,0,33,2800,2000,8,1,16,270340);
INSERT OR REPLACE INTO "texts" VALUES (49217579, 'Mirage Knight', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by the effect of "Dark Flare Knight". When this card battles another monster, during damage calculation increase the ATK of this card by the original ATK of the opponent''s monster. During the End Phase after this card was involved in battle, remove this card from play.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72989439,3,0,0,33,3000,2500,8,1,16,2457604);
INSERT OR REPLACE INTO "texts" VALUES (72989439, 'Black Luster Soldier - Envoy of the Beginning', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your Graveyard. Once per turn, you can activate 1 of these effects.
● Target 1 monster on the field; banish that target face-up. This card cannot attack the turn you activate this effect.
● During the Damage Step, if this attacking card destroys an opponent''s monster by battle: It can make a second attack in a row.', 'Special Summon', 'Banish', 'Attack again', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40737112,3,0,162,33,2800,2600,8,2,32,1044);
INSERT OR REPLACE INTO "texts" VALUES (40737112, 'Dark Magician of Chaos', 'During the End Phase, if this card was Normal or Special Summoned this turn: You can target 1 Spell Card in your Graveyard; add it to your hand. You can only use this effect of "Dark Magician of Chaos" once per turn. At the end of the Damage Calculations, if this card destroyed an opponent’s monster by battle: Banish that monster. If this card would leave the field, banish it instead.', 'Spell recovery', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92377303,3,0,0,33,2800,3200,9,2,32,262656);
INSERT OR REPLACE INTO "texts" VALUES (92377303, 'Dark Sage', 'This card cannot be Normal Summoned or Set. This card can only be Special Summoned from your hand or your Deck by Tributing 1 "Dark Magician" on your side of the field when you succeed in the effect of "Time Wizard". At that time, select 1 Spell Card from your Deck, add it to your hand, and then shuffle your Deck.', 'Special Summon', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50725996,3,0,162,33,2500,2100,7,1,32,3);
INSERT OR REPLACE INTO "texts" VALUES (50725996, 'Dark Magician Knight', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by the effect of "Knight''s Title". If this card is Special Summoned successfully, select 1 card on the field and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88619463,3,0,0,33,3200,2800,9,2,32,-2147221503);
INSERT OR REPLACE INTO "texts" VALUES (88619463, 'Sorcerer of Dark Magic', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by Tributing 2 Level 6 or higher Spellcaster-Type monsters. You can negate the activation of any Trap Cards and destroy them.', '無効', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87774234,3,0,0,33,200,300,1,4,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (87774234, 'Watapon', 'If this card is added to your hand from your Deck by the effect of a Spell, Trap or Monster Card, you can Special Summon this card on your side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16589042,3,0,189,33,2300,2100,7,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (16589042, 'Swift Gaia the Fierce Knight', 'If this is the only card in your hand, you can Normal Summon it without Tributing.', 'リリースなしで召喚', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65240384,3,0,0,33,100,2600,4,1,1,-2113927168);
INSERT OR REPLACE INTO "texts" VALUES (65240384, 'Big Shield Gardna', 'During either player''s turn, when this face-down card (and no other cards) is targeted by a Spell Card: Change this card to face-up Defense Position, and if you do, negate the Spell Card''s activation. If this card is attacked, change it to Attack Position at the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1995985,3,0,65,33,1000,1000,3,1,16,262656);
INSERT OR REPLACE INTO "texts" VALUES (1995985, 'Silent Swordsman LV3', 'Negate your opponent''s Spell effects that target this card. During your Standby Phase: You can send this face-up card to the Graveyard; Special Summon 1 "Silent Swordsman LV5" from your hand or Deck. You cannot activate this effect the turn this card is Summoned or flipped face-up.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74388798,3,0,65,33,2300,1000,5,1,16,33816584);
INSERT OR REPLACE INTO "texts" VALUES (74388798, 'Silent Swordsman LV5', 'This card is unaffected by your opponent''s Spell effects. During your next Standby Phase after this card inflicts battle damage to your opponent by a direct attack: You can send this face-up card to the Graveyard; Special Summon 1 "Silent Swordsman LV7" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37267041,3,0,65,33,2800,1000,7,1,16,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (37267041, 'Silent Swordsman LV7', 'Cannot be Normal Summoned/Set. Must be Special Summoned by "Silent Swordsman LV5", and cannot be Special Summoned by other ways. Negate all Spell effects on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52077741,3,0,0,33,1400,1200,4,1,1,16777216);
INSERT OR REPLACE INTO "texts" VALUES (52077741, 'Obnoxious Celtic Guard', 'This card cannot be destroyed by battle with a monster that has 1900 or more ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73665146,3,0,65,33,1000,1000,4,2,16,67379208);
INSERT OR REPLACE INTO "texts" VALUES (73665146, 'Silent Magician LV4', 'Each time your opponent draws a card(s), place 1 Spell Counter on this card (max. 5). This card gains 500 ATK for each Spell Counter on it. During the Standby Phase of your next turn after the 5th Spell Counter is placed on this card: You can send this face-up card with 5 Spell Counters on it to the Graveyard; Special Summon 1 "Silent Magician LV8" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72443568,3,0,65,33,3500,1000,8,2,16,33554432);
INSERT OR REPLACE INTO "texts" VALUES (72443568, 'Silent Magician LV8', 'Cannot be Normal Summoned/Set. Must be Special Summoned by "Silent Magician LV4" and cannot be Special Summoned by other ways. This card is unaffected by your opponent''s Spell effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41172955,3,0,81,33,1400,600,4,32,1,512);
INSERT OR REPLACE INTO "texts" VALUES (41172955, 'Green Gadget', 'When this card is Normal or Special Summoned: You can add 1 "Red Gadget" from your Deck to your hand.', 'Add 1 "Red Gadget" from your Deck to your hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86445415,3,0,81,33,1300,1500,4,32,1,512);
INSERT OR REPLACE INTO "texts" VALUES (86445415, 'Red Gadget', 'When this card is Normal or Special Summoned: You can add 1 "Yellow Gadget" from your Deck to your hand.', 'Add 1 "Yellow Gadget" from your Deck to your hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13839120,3,0,81,33,1200,1200,4,32,1,512);
INSERT OR REPLACE INTO "texts" VALUES (13839120, 'Yellow Gadget', 'When this card is Normal or Special Summoned: You can add 1 "Green Gadget" from your Deck to your hand.', 'Add 1 "Green Gadget" from your Deck to your hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50287060,3,0,69,33,2200,2500,6,8,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (50287060, 'Archfiend of Gilfer', 'When this card is sent to the Graveyard: You can target 1 face-up monster on the field; equip that target with this card. That monster loses 500 ATK while equipped with this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14778250,3,0,0,33,2000,1200,5,2,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (14778250, 'The Tricky', 'You can Special Summon this card (from your hand) by discarding 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44330098,3,0,0,33,2700,2500,7,8,32,4456448);
INSERT OR REPLACE INTO "texts" VALUES (44330098, 'Gorz the Emissary of Darkness', 'When you take damage from a card your opponent control: You can Special Summon this card from your hand. You must control no cards to activate and to resolve this effect. When Special Summoned this way, activate the appropriate effect, based on the type of damage:
● Battle Damage: Special Summon 1 "Emissary of Darkness Token" (Fairy-Type/LIGHT/Level 7/ATK ?/DEF ?). Its ATK and DEF are each equal to the amount of Battle Damage you took.
● Effect Damage: Inflict damage to your opponent equal to the amount of damage you took.', 'Special Summon', 'Special Summon token', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77207191,3,0,0,33,1400,1800,5,8,32,512);
INSERT OR REPLACE INTO "texts" VALUES (77207191, 'Berfomet', 'When this card is Normal or Flip Summoned, you can add 1 "Gazelle the King of Mythical Beasts" from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5405694,3,0,0,129,3000,2500,8,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (5405694, 'Black Luster Soldier', 'This monster can only be Ritual Summoned with the Ritual Spell Card, "Black Luster Ritual".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30208479,3,0,0,129,2800,2600,8,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (30208479, 'Magician of Black Chaos', 'You can Ritual Summon this card with "Black Magic Ritual".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98502113,3,0,110,97,2900,2400,8,2,32,-2146426871);
INSERT OR REPLACE INTO "texts" VALUES (98502113, 'Dark Paladin', '"Dark Magician" + "Buster Blader"
Must be Fusion Summoned and cannot be Special Summoned by other ways. During either player''s turn, when a Spell Card is activated: You can discard 1 card; negate the activation, and if you do, destroy it. This card must be face-up on the field to activate and to resolve this effect. This card gains 500 ATK for each Dragon-Type monster on the field or in either player''s Graveyard.', 'Negate and Destroy Spell Card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13722870,3,0,0,97,2200,800,6,1,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (13722870, 'Dark Flare Knight', '"Dark Magician" + "Flame Swordsman"
Any damage to this card''s controller caused as a result of battle involving this monster becomes 0. When this card is destroyed and sent to the Graveyard as a result of battle, Special Summon 1 "Mirage Knight" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62873545,3,0,0,97,5000,5000,12,8192,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (62873545, 'Dragon Master Knight', '"Black Luster Soldier" + "Blue-Eyes Ultimate Dragon"
This monster cannot be Special Summoned except by Fusion Summon. This card gains 500 ATK for each other Dragon-Type monster you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6150044,3,0,0,97,3800,2500,9,1,16,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (6150044, 'Arcana Knight Joker', '"Queen''s Knight" + "Jack''s Knight" + "King''s Knight"
A Fusion Summon of this card can only be conducted with the above Fusion Material Monsters. Once per turn, if this face-up card on the field is targeted by a Spell Card, Trap Card, or Effect Monster''s effect, you can negate that effect by discarding the same kind of card (Spell, Trap, or Monster Card).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4796100,3,0,27,97,2100,1800,6,16384,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (4796100, 'Chimera the Flying Mythical Beast', '"Gazelle the King of Mythical Beasts" + "Berfomet"
(This monster is always treated as a "Phantom Beast" monster.) When this card is destroyed, you can select and Special Summon either "Berfomet" or "Gazelle the King of Mythical Beasts" from your Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53129443,3,0,137,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (53129443, 'Dark Hole', 'Destroy all monsters on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12580477,3,0,0,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (12580477, 'Raigeki', 'Destroy all monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66788016,3,0,0,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (66788016, 'Fissure', 'Destroy the 1 face-up monster your opponent controls that has the lowest ATK (your choice, if tied).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24094653,3,0,70,2,0,0,0,0,0,268697608);
INSERT OR REPLACE INTO "texts" VALUES (24094653, 'Polymerization', 'Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters from your hand or your side of the field as Fusion Materials.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72302403,3,0,0,2,0,0,0,0,0,67584);
INSERT OR REPLACE INTO "texts" VALUES (72302403, 'Swords of Revealing Light', 'Flip all monsters your opponent controls face-up. This card remains on the field for 3 of your opponent''s turns. While this card is face-up on the field, monsters your opponent controls cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83764718,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (83764718, 'Monster Reborn', 'Target 1 monster in either player''s Graveyard; Special Summon it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55144522,3,0,0,2,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (55144522, 'Pot of Greed', 'Draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72892473,3,0,0,2,0,0,0,0,0,328);
INSERT OR REPLACE INTO "texts" VALUES (72892473, 'Card Destruction', 'Each player discards their entire hand, then draws the same number of cards they discarded.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19613556,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (19613556, 'Heavy Storm', 'Destroy all Spell and Trap Cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5318639,3,0,0,65538,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (5318639, 'Mystical Space Typhoon', 'Target 1 Spell/Trap Card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95286165,3,0,70,65538,0,0,0,0,0,262176);
INSERT OR REPLACE INTO "texts" VALUES (95286165, 'De-Fusion', 'Select 1 face-up Fusion Monster on the field and return it to the Extra Deck. If all the Fusion Material Monsters that were used for the Fusion Summon of that Fusion Monster are in your Graveyard, you can Special Summon them.', 'Special Summon Fusion Material Monsters?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79571449,3,0,0,2,0,0,0,0,0,264);
INSERT OR REPLACE INTO "texts" VALUES (79571449, 'Graceful Charity', 'Draw 3 cards, then discard 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24096228,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (24096228, 'Double Spell', 'Discard 1 Spell Card from your hand. Select 1 Spell Card from your opponent''s Graveyard and use it from the Graveyard as your Spell Card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87880531,3,0,0,2,0,0,0,0,0,32768);
INSERT OR REPLACE INTO "texts" VALUES (87880531, 'Diffusion Wave-Motion', 'Pay 1000 Life Points. Select 1 Level 7 or higher Spellcaster-Type monster on your side of the field. During this turn, only the selected monster can attack and it attacks all monsters on your opponent''s side of the field once each. The effects of Effect Monsters destroyed by this attack(s) are not activated.', '相手モンスター全てに１回ずつ攻撃', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63391643,3,0,0,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (63391643, 'Thousand Knives', 'Activate only while you control a face-up "Dark Magician". Destroy one monster your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35762283,3,0,0,131074,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (35762283, 'Heart of the Underdog', 'During your Draw Phase, when you draw a Normal Monster Card(s), you can draw 1 more card by showing it to your opponent.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69542930,3,0,0,65538,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (69542930, 'Dedication through Light and Darkness', 'Tribute 1 "Dark Magician"; Special Summon 1 "Dark Magician of Chaos" from your hand, Deck, or Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55761792,3,0,0,130,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (55761792, 'Black Luster Ritual', 'This card is used to Ritual Summon "Black Luster Soldier". You must also Tribute monsters from the field or your hand whose total Levels equal 8 or more.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2314238,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (2314238, 'Dark Magic Attack', 'If you control a "Dark Magician": Destroy all Spell and Trap Cards your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87210505,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (87210505, 'Knight''s Title', 'Activate this card by offering 1 face-up "Dark Magician" on your side of the field as a Tribute. Special Summon 1 "Dark Magician Knight" from your hand, Deck or Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13604200,3,0,0,2,0,0,0,0,0,262656);
INSERT OR REPLACE INTO "texts" VALUES (13604200, 'Sage''s Stone', 'Activate only if you control a face-up "Dark Magician Girl". Special Summon 1 "Dark Magician" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87910978,3,0,0,2,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (87910978, 'Brain Control', 'Pay 800 Life Points. Select 1 face-up monster your opponent controls. Take control of it until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28553439,3,0,0,65538,0,0,0,0,0,1310722);
INSERT OR REPLACE INTO "texts" VALUES (28553439, 'Magical Dimension', 'If you control a face-up Spellcaster-Type monster: Target 1 monster you control; Tribute it, then Special Summon 1 Spellcaster-Type monster from your hand, then you can destroy 1 monster on the field.', 'Destroy 1 monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25774450,3,0,0,2,0,0,0,0,0,4098);
INSERT OR REPLACE INTO "texts" VALUES (25774450, 'Mystic Box', 'Target 1 monster your opponent controls and 1 monster you control; destroy the first target, then give control of the second target to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36045450,3,0,0,2,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (36045450, 'Magicians Unite', 'If you control 2 or more Attack Position Spellcaster-Type monsters: Target 1 of them; its ATK becomes 3000 until the end of this turn, but other Spellcaster-Type monsters you control cannot attack this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76792184,3,0,0,130,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (76792184, 'Black Magic Ritual', 'This card is used to Ritual Summon "Magician of Black Chaos". You must also Tribute monsters from your hand or field whose total Levels equal 8 or more.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99789342,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (99789342, 'Dark Magic Curtain', 'If you activate this card, you cannot Normal Summon, Flip Summon or Special Summon this turn. Pay half your Life Points to Special Summon 1 "Dark Magician" from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75500286,3,0,0,2,0,0,0,0,0,1044);
INSERT OR REPLACE INTO "texts" VALUES (75500286, 'Gold Sarcophagus', 'Banish 1 card from your Deck, face-up. During your second Standby Phase after this card''s activation, add that card to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81510157,3,0,0,2,0,0,0,0,0,8388610);
INSERT OR REPLACE INTO "texts" VALUES (81510157, 'Soul Taker', 'Destroy 1 face-up monster your opponent controls. Then, your opponent gains 1000 Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67227834,3,0,0,262146,0,0,0,0,0,8396800);
INSERT OR REPLACE INTO "texts" VALUES (67227834, 'Magic Formula', 'Equip only to "Dark Magician" or "Dark Magician Girl". The equipped monster gains 700 ATK. When this card is sent from the field to the Graveyard, gain 1000 Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60399954,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (60399954, 'Union Attack', 'Target 1 face-up monster you control; add up the total ATK of all other face-up Attack Position monsters you currently control, then during the Battle Phase of this turn only, the monster gains that much ATK, but cannot inflict battle damage to your opponent, also other face-up Attack Position monsters cannot attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75622824,3,0,0,65538,0,0,0,0,0,786432);
INSERT OR REPLACE INTO "texts" VALUES (75622824, 'Tricky Spell 4', 'Send 1 face-up "The Tricky" you control to the Graveyard; Special Summon "Tricky Tokens" (Spellcaster-Type/WIND/Level 5/ATK 2000/DEF 1200) in Defense Position, equal to the number of monsters your opponent controls. "Tricky Tokens" cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93260132,3,0,0,65538,0,0,0,0,0,4194305);
INSERT OR REPLACE INTO "texts" VALUES (93260132, 'Spell Shattering Arrow', 'Destroy all face-up Spell Cards your opponent controls. For each destroyed Spell Card, inflict 500 damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40703222,3,0,0,65538,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (40703222, 'Multiply', 'Tribute 1 face-up "Kuriboh". Special Summon as many "Kuriboh Token" (Fiend-Type/DARK/Level 1/ATK 300/DEF 200) as possible in Defense Position. These Tokens cannot be Tributed for a Tribute Summon.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27827272,3,0,0,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (27827272, 'Makiu, the Magical Mist', 'Select 1 "Summoned Skull" or Thunder-Type monster you control. Destroy all monsters your opponent controls whose DEF is lower than the ATK of the selected monster. You cannot conduct your Battle Phase the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89086566,3,0,0,65538,0,0,0,0,0,3);
INSERT OR REPLACE INTO "texts" VALUES (89086566, 'Detonate', 'Destroy all face-up "Kuriboh" and "Kuriboh Tokens" you control, along with a number of cards your opponent controls, up to the number of "Kuriboh" and "Kuriboh Tokens" destroyed by this effect.', 'Destroy opponent card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3819470,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (3819470, 'Seven Tools of the Bandit', 'When a Trap Card is activated: Pay 1000 LP; negate the activation, and if you do, destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98069388,3,0,0,1048580,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (98069388, 'Horn of Heaven', 'When a monster would be Summoned: Tribute 1 monster; negate the Summon, and if you do, destroy that monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44095762,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (44095762, 'Mirror Force', 'When an opponent''s monster declares an attack: Destroy all Attack Position monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18807108,3,0,0,131076,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (18807108, 'Spellbinding Circle', 'Select 1 monster. It cannot attack or change its Battle position. When that monster is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49587034,3,0,0,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (49587034, 'Lightforce Sword', 'Select 1 random card from your opponent''s hand and remove it from play face-down. During your opponent''s 4th Standby Phase after this card''s activation, return that card to their hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1248895,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (1248895, 'Chain Destruction', 'When a monster(s) with 2000 or less ATK is Summoned: Target 1 of them; destroy all cards with that name in its controller''s hand and Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60082869,3,0,0,4,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (60082869, 'Dust Tornado', 'Target 1 Spell/Trap Card your opponent controls; destroy that target, then you can Set 1 Spell/Trap Card from your hand.', 'Set 1 Card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81210420,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (81210420, 'Magical Hats', 'Activate only during your opponent''s Battle Phase. Select 2 non-Monster Cards from your Deck and 1 monster you control. Shuffle those 3 cards and Set them on the field in face-down Defense Position. The 2 cards selected from your Deck are treated as monsters (ATK 0/DEF 0) and are destroyed at the end of the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59560625,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (59560625, 'Shift', 'When your opponent targets exactly 1 monster you control (and no other cards) for an attack, or with a Spell/Trap effect: Target another monster you control that would be an appropriate target; that attack/Spell/Trap now targets the new target.', '改变对方的效果的对象', '改变对方的战斗对象', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7565547,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (7565547, 'Collected Power', 'Target 1 face-up monster on the field; equip it with all Equip Cards on the field. If any of those Equip Cards is now equipped to an incorrect target, destroy that Equip Card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62279055,3,0,0,4,0,0,0,0,0,4259840);
INSERT OR REPLACE INTO "texts" VALUES (62279055, 'Magic Cylinder', 'When an opponent''s monster declares an attack: Target the attacking monster; negate the attack, and if you do, inflict damage to your opponent equal to its ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50755,3,0,0,4,0,0,0,0,0,262656);
INSERT OR REPLACE INTO "texts" VALUES (50755, 'Magician''s Circle', 'When a Spellcaster-Type monster declares an attack: Each player Special Summons 1 Spellcaster-Type monster with 2000 or less ATK from their Deck in Attack Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
