BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (3580032,3,0,0,33,1400,500,3,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (3580032, 'Merlin', 'You can only use each effect of "Merlin" once per turn.
● You can Tribute this card; Special Summon 1 "Noble Knight" monster from your Deck. You cannot Special Summon monsters the turn you activate this effect, except "Noble Knight" monsters.
● During either player''s turn: You can banish this card from your Graveyard; immediately after this effect resolves, Synchro Summon 1 "Noble Knight" Synchro Monster using monsters you control.
● During either player''s turn: You can banish this card from your Graveyard; immediately after this effect resolves, Xyz Summon 1 "Noble Knight" Xyz Monster using monsters you control.', 'Synchro Summon', 'Xyz Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30575681,3,0,4218,33,1600,1500,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (30575681, 'Noble Knight Bedwyr', 'When this card is Normal or Special Summoned: You can send 1 "Noble Arms" Equip Spell Card from your Deck to the Graveyard. During either player''s turn: You can target 1 "Noble Arms" Equip Spell Card and 1 appropriate monster on the field; equip that Equip Spell Card to that appropriate monster. This effect can only be used once while this card is face-up on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92125819,3,0,10948730,17,1800,1800,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (92125819, 'Noble Knight Artorigus', 'No one shall ever know the truth behind
 That fateful day. Artorigus went forth
 To where the brilliant sword didst lay.
 ''Twas the first of many feats so great,
 A legend through and through. We sing of him,
 Artorigus, the Noble and the brave.
  -From the Tales of the Noble Knights', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19680539,3,0,4218,33,1900,500,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (19680539, 'Noble Knight Gawayn', 'If you control a LIGHT Normal Monster, you can Special Summon this card (from your hand) in face-up Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95772051,3,0,721562505338,33,2000,800,5,1,32,262656);
INSERT OR REPLACE INTO "texts" VALUES (95772051, 'Ignoble Knight of Black Laundsallyn', 'You can send 1 face-up LIGHT Normal Monster you control to the Graveyard; Special Summon this card from your hand or Graveyard. You can Tribute 1 "Noble Knight" monster; add 1 "Noble Arms" card from your Deck to your hand. You can only use this effect of "Ignoble Knight of Black Laundsallyn" once per turn. You can control only 1 face-up "Ignoble Knight of Black Laundsallyn".', 'Special Summon', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59057152,3,0,4218,33,1700,1000,4,1,16,262145);
INSERT OR REPLACE INTO "texts" VALUES (59057152, 'Noble Knight Medraut', 'This card is treated as a Normal Monster while face-up on the field. While equipped with a "Noble Arms" Equip Spell Card, this card becomes an Effect Monster with these effects.
● This card becomes DARK and its Level is increased by 1. Once per turn, if you control no other monsters: You can Special Summon 1 "Noble Knight" monster from your Deck in face-up Defense Position, except "Noble Knight Medraut", and if you do, destroy 1 Equip Spell Card you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13391185,3,0,4218,33,1500,1800,4,1,16,16);
INSERT OR REPLACE INTO "texts" VALUES (13391185, 'Noble Knight Gwalchavad', 'This card is treated as a Normal Monster while face-up on the field. While equipped with a "Noble Arms" Equip Spell Card, this card becomes an Effect Monster with this effect.
● You can target 1 "Noble Knight" monster in your Graveyard; add it to your hand, and if you do, destroy 1 "Noble Arms" Equip Spell Card you control. You can only use this effect of "Noble Knight Gwalchavad" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53550467,3,0,4218,33,1800,800,4,1,16,16777216);
INSERT OR REPLACE INTO "texts" VALUES (53550467, 'Noble Knight Drystan', 'While you control another "Noble Knight" monster, your opponent cannot target your monsters with less than 1800 ATK, except this card, for attacks or with card effects. When a "Noble Arms" Equip Spell Card is equipped to this card: Target 1 face-up card on the field; destroy that target. You can only use this effect of "Noble Knight Drystan" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47120245,3,0,4218,33,1700,900,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (47120245, 'Noble Knight Borz', 'This card is treated as a Normal Monster while face-up on the field. While equipped with a "Noble Arms" Equip Spell Card, this card becomes an Effect Monster with these effects.
● This card becomes DARK and its Level is increased by 1. During your Main Phase: You can reveal 3 "Noble Arms" cards from your Deck, have your opponent randomly add 1 of them to your hand, and send the rest to the Graveyard. You can only use this effect of "Noble Knight Borz" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73359475,3,0,4218,33,1900,300,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (73359475, 'Noble Knight Peredur', 'While equipped with a "Noble Arms" Equip Spell Card, this card becomes DARK and its Level is increased by 1. When this card is sent to the Graveyard while equipped with a "Noble Arms" Equip Spell Card: Target 1 "Noble Arms" card in your Graveyard; add that target to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93085839,3,0,4218,33,1600,2000,5,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (93085839, 'Noble Knight Eachtar', 'You can banish 2 "Noble Knight" monsters from your Graveyard; Special Summon this card from your hand or Graveyard. You can only use this effect of "Noble Knight Eachtar" once per turn. A Synchro or Xyz Summon of a "Noble Knight" monster using this card as a Material cannot be negated, also your opponent cannot activate cards or effects when that monster is Special Summoned.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19748583,3,0,8314,33,300,300,2,2,16,0);
INSERT OR REPLACE INTO "texts" VALUES (19748583, 'Gwenhwyfar, Queen of Noble Arms', 'You can target 1 "Noble Knight" monster you control; equip this card from your hand or Graveyard to that target. You can only use this effect of "Gwenhwyfar, Queen of Noble Arms" once per turn. The equipped monster gains 300 ATK. Apply the appropriate effect, depending on the Attribute of the equipped monster.
● LIGHT: If the equipped monster would be destroyed by a card effect, you can destroy this card instead.
● DARK: If the equipped monster battles an opponent''s monster, at the start of the Damage Step: You can destroy that monster, then destroy this card.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10736540,3,0,0,4129,200,1800,1,64,16,0);
INSERT OR REPLACE INTO "texts" VALUES (10736540, 'Lady of the Lake', 'Cannot be used as a Synchro Material Monster, except for the Synchro Summon of a Warrior-Type monster. If this card is used for a Synchro Summon, banish it. When this card is Normal Summoned: You can target 1 "Noble Knight" Normal Monster in your Graveyard; Special Summon that target. If this card is in your Graveyard: You can target 1 Level 5 "Noble Knight" monster you control; reduce its Level by 1, and if you do, Special Summon this card from the Graveyard.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37742478,3,0,0,33,1100,1900,4,4,16,2105368);
INSERT OR REPLACE INTO "texts" VALUES (37742478, 'Honest', 'During your Main Phase: You can return this face-up card from the field to the hand. During either player''s Damage Step, when a LIGHT monster you control battles: You can send this card from your hand to the Graveyard; that monster gains ATK equal to the ATK of the opponent''s monster it is battling, until the end of this turn.', 'Return to hand', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15767889,3,0,0,2081,1700,1600,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (15767889, 'Knight Day Grepher', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it become an Effect Monster with this effect.
● During your End Phase: You can target 1 Equip Spell Card in your Graveyard; add that target to your hand. You can only use this effect of "Knight Day Grepher" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6351548,3,0,0,33,1400,1200,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (6351548, 'Dawn Knight', 'If this card is sent from the field to the Graveyard: You can send 1 LIGHT monster from your Deck to the Graveyard. If this card is sent from your Deck to the Graveyard: Target 1 LIGHT monster in your Graveyard; place that target on the top of your Deck. You can only use 1 "Dawn Knight" effect per turn, and only once that turn.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66970385,3,0,4218,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (66970385, 'Last Chapter of the Noble Knights', 'If your opponent controls a monster and you control no monsters: You can target 1 "Noble Arms" Equip Spell Card and 1 appropriate "Noble Knight" monster in your Graveyard; Special Summon that monster, and if you do, equip that Equip Spell Card to that appropriate monster. You can only activate 1 "Last Chapter of the Noble Knights" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55742055,3,0,4218,524290,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (55742055, 'Noble Knights of the Round Table', 'During your End Phase: You can activate each of these effects up to once per turn, depending on the total number of "Noble Knight" cards with different names in your Graveyard and/or you control.
● 3 or more: Send 1 "Noble Knight" card from your Deck to the Graveyard.
● 6 or more: Special Summon 1 "Noble Knight" monster from your hand, then you can equip 1 "Noble Arms" Equip Spell Card from your hand to that monster.
● 9 or more: Target 1 "Noble Knight" monster in your Graveyard; add that target to your hand.
● 12: Draw 1 card.', 'Send 1 "Noble Knight" card from your Deck to the Graveyard.', 'Special Summon 1 "Noble Knight" monster from your hand, then you can equip 1 "Noble Arms" Equip Spell Card from your hand to that monster.', 'Target 1 "Noble Knight" monster in your Graveyard; add that target to your hand.', 'Draw 1 card.', 'Equip 1 "Noble Arms" Equip Spell Card from your hand', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14745409,3,0,8314,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (14745409, 'Noble Arms - Gallatin', 'You can only control 1 face-up "Noble Arms - Gallatin". Equip only to a Warrior-Type monster. It gains 1000 ATK. During each of your Standby Phases, it loses 200 ATK. If this face-up card on the field is destroyed and sent to the Graveyard: You can target 1 face-up Warrior-Type "Noble Knight" monster you control; equip this card to that target. This effect of "Noble Arms - Gallatin" can only be used once per turn.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83438826,3,0,8314,262146,0,0,0,0,0,8193);
INSERT OR REPLACE INTO "texts" VALUES (83438826, 'Noble Arms - Arfeudutyr', 'You can only control 1 "Noble Arms - Arfeudutyr". Equip only to a Warrior-Type monster. Once per turn: You can target 1 Set card your opponent controls; the equipped monster loses exactly 500 ATK, and if it does, destroy that target. (This ATK loss remains even if this card leaves the field or the monster becomes unaffected by card effects.) If this face-up card on the field is destroyed and sent to the Graveyard: You can target 1 Warrior-Type "Noble Knight" monster you control; equip this card to that target. You can only use this effect of "Noble Arms - Arfeudutyr" once per turn.', 'S/T Destruction', '装备', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23562407,3,0,8314,262146,0,0,0,0,0,8396800);
INSERT OR REPLACE INTO "texts" VALUES (23562407, 'Noble Arms - Caliburn', 'You can only control 1 "Noble Arms - Caliburn". Equip only to a Warrior-Type monster. It gains 500 ATK. Once per turn: You can gain 500 LP. If this face-up card on the field is destroyed and sent to the Graveyard: You can target 1 Warrior-Type "Noble Knight" monster you control; equip this card to that target. You can only use this effect of "Noble Arms - Caliburn" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7452945,3,0,8314,262146,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (7452945, 'Noble Arms of Destiny', 'You can only control 1 face-up "Noble Arms of Destiny". Equip only to a Warrior-Type monster. Once per turn, the equipped monster cannot be destroyed by battle or by card effects. If this face-up card on the field is destroyed and sent to the Graveyard: You can target 1 Warrior-Type "Noble Knight" monster you control; equip this card to that target. You can only use this effect of "Noble Arms of Destiny" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46008667,3,0,8314,262146,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (46008667, 'Noble Arms - Excaliburn', 'Equip only to a "Noble Knight" monster. It cannot be targeted by an opponent''s card effects. During your turn, except the turn this card was sent to the Graveyard: You can banish this card from your Graveyard, then target 1 "Noble Knight" Xyz Monster you control; Special Summon from your Extra Deck, 1 "Noble Knight" Xyz Monster with a different name, by using that target as the Xyz Material. (This Special Summon is treated as an Xyz Summon. Xyz Materials attached to it also become Xyz Materials on the Summoned monster.) You can only use this effect of "Noble Arms - Excaliburn" once per turn.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53129443,3,0,137,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (53129443, 'Dark Hole', 'Destroy all monsters on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72302403,3,0,0,2,0,0,0,0,0,67584);
INSERT OR REPLACE INTO "texts" VALUES (72302403, 'Swords of Revealing Light', 'Flip all monsters your opponent controls face-up. This card remains on the field for 3 of your opponent''s turns. While this card is face-up on the field, monsters your opponent controls cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32807846,3,0,0,2,0,0,0,0,0,1049088);
INSERT OR REPLACE INTO "texts" VALUES (32807846, 'Reinforcement of the Army', 'Add 1 Level 4 or lower Warrior-Type monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14087893,3,0,0,65538,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (14087893, 'Book of Moon', 'Target 1 face-up monster on the field; change that target to face-down Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81439173,3,0,0,2,0,0,0,0,0,8);
INSERT OR REPLACE INTO "texts" VALUES (81439173, 'Foolish Burial', 'Send 1 monster from your Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98847704,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (98847704, 'Release Restraint Wave', 'Target 1 face-up Equip Spell Card you control; destroy the Equip Spell Card and all face-down Spell and Trap Cards your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25067275,3,0,0,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (25067275, 'Swords at Dawn', 'Target 1 Equip Spell Card in your Graveyard and 1 appropriate monster on the field; equip the Equip Spell Card to that monster. Destroy that Equip Spell Card during the End Phase. If you activate this card, you cannot Special Summon for the rest of this turn. You can only activate 1 "Swords at Dawn" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82140600,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (82140600, 'Avalon', 'Target 5 "Noble Knight" monsters in your Graveyard, including at least 1 "Artorigus" monster and 1 "Laundsallyn" monster; banish those targets, and if you do, destroy all cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97077563,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (97077563, 'Call of the Haunted', 'Activate this card by targeting 1 monster in your Graveyard; Special Summon that target in Attack Position. When this card leaves the field, destroy that target. When that target is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1224927,3,0,0,4,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (1224927, 'Malevolent Catastrophe', 'When an opponent''s monster declares an attack: Destroy all Spell and Trap Cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70342110,3,0,0,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (70342110, 'Dimensional Prison', 'When an opponent declares an attack: Target that monster; banish that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84749824,3,0,0,1048580,0,0,0,0,0,-2147483645);
INSERT OR REPLACE INTO "texts" VALUES (84749824, 'Solemn Warning', 'When a monster would be Summoned, OR when a Spell Card, Trap Card, or monster effect is activated that includes an effect that Special Summons a monster(s): Pay 2000 Life Points; negate the Summon or activation, and if you do, destroy that card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83519853,3,0,721830936698,8225,2100,900,5,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (83519853, 'Ignoble Knight of High Laundsallyn', '1 Tuner + 1 or more non-Tuner "Noble Knight" monsters
When this card is Synchro Summoned: You can equip 1 "Noble Arms" Equip Spell Card from your Deck to this card. At the end of the Battle Phase, if this card destroyed a monster by battle and sent it to the Graveyard: You can add 1 "Noble Knight" or "Noble Arms" card from your Deck to your hand. You can only control 1 "Ignoble Knight of High Laundsallyn".
', 'Equip 1 "Noble Arms" Equip Spell Card from your Deck?', 'Add 1 "Noble Knight" or "Noble Arms" card from your Deck to your hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21223277,3,0,10948730,8388641,2000,2000,4,1,16,1);
INSERT OR REPLACE INTO "texts" VALUES (21223277, 'Artorigus, King of the Noble Knights', '2 Level 4 "Noble Knight" monsters
When this card is Xyz Summoned: You can target up to 3 "Noble Arms" Equip Spell Cards with different names in your Graveyard; equip those targets to this card. Once per turn: You can detach 1 Xyz Material from this card; destroy any number of Spell/Trap Cards on the field, up to the number of "Noble Arms" Equip Spell Cards you control.', 'Equip', 'Destroy', 'Equip another card?', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10613952,3,0,10948730,8388641,2200,2200,5,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (10613952, 'Sacred Noble Knight of King Artorigus', '2 Level 5 "Noble Knight" monsters
When this card is Xyz Summoned: You can target up to 3 "Noble Arms" Equip Spell Cards with different names in your Graveyard; equip those targets to this card. Once per turn: You can detach 1 Xyz Material from this card, then target 1 other monster on the field; destroy that target. If this card on the field is sent to the Graveyard: You can target 1 Level 4 or higher "Noble Knight" monster in your Graveyard; Special Summon that target.', 'Add another? ', 'Add another?', '          ', 'Add another? ', '        ', '           ', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97268402,3,0,0,4129,0,0,1,2,16,-2147483640);
INSERT OR REPLACE INTO "texts" VALUES (97268402, 'Effect Veiler', 'During your opponent''s Main Phase: You can send this card from your hand to the Graveyard, then target 1 face-up Effect Monster your opponent controls; negate that opponent''s face-up monster''s effects until the End Phase (this is a Quick Effect).', '怪兽的效果无效', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5318639,3,0,0,65538,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (5318639, 'Mystical Space Typhoon', 'Target 1 Spell/Trap Card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75500286,3,0,0,2,0,0,0,0,0,1044);
INSERT OR REPLACE INTO "texts" VALUES (75500286, 'Gold Sarcophagus', 'Banish 1 card from your Deck, face-up. During your second Standby Phase after this card''s activation, add that card to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27243130,3,0,0,65538,0,0,0,0,0,33562624);
INSERT OR REPLACE INTO "texts" VALUES (27243130, 'Forbidden Lance', 'Target 1 face-up monster on the field; until the end of this turn, that target loses 800 ATK, but is unaffected by the effects of other Spell/Trap Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53582587,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (53582587, 'Torrential Tribute', 'When a monster(s) is Summoned: Destroy all monsters on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94192409,3,0,0,4,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (94192409, 'Compulsory Evacuation Device', 'Target 1 monster on the field; return that target to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
