BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (38033121,3,0,279052450,33,2000,1700,6,2,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (38033121, 'Dark Magician Girl', 'This card gains 300 ATK for every "Dark Magician" or "Magician of Black Chaos" in either player''s Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63391643,3,0,0,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (63391643, 'Thousand Knives', 'Activate only while you control a face-up "Dark Magician". Destroy one monster your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99789342,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (99789342, 'Dark Magic Curtain', 'If you activate this card, you cannot Normal Summon, Flip Summon or Special Summon this turn. Pay half your Life Points to Special Summon 1 "Dark Magician" from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25774450,3,0,0,2,0,0,0,0,0,4098);
INSERT OR REPLACE INTO "texts" VALUES (25774450, 'Mystic Box', 'Target 1 monster your opponent controls and 1 monster you control; destroy the first target, then give control of the second target to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62279055,3,0,0,4,0,0,0,0,0,4259840);
INSERT OR REPLACE INTO "texts" VALUES (62279055, 'Magic Cylinder', 'When an opponent''s monster declares an attack: Target the attacking monster; negate the attack, and if you do, inflict damage to your opponent equal to its ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
