BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (83555666,3,0,0,4,0,0,0,0,0,4194306);
INSERT OR REPLACE INTO "texts" VALUES (83555666, 'Ring of Destruction', 'You can only activate 1 “Ring of Destruction” per turn. During your opponent’s turn: Target 1 face-up monster your opponent controls whose ATK is lower than or equal to your opponent’s LP; destroy that face-up monster, and if you do, you take damage equal to that monster’s original ATK, then, inflict damage to your opponent equal to the damage you took.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17192817,3,0,0,17,1000,2200,5,128,4,0);
INSERT OR REPLACE INTO "texts" VALUES (17192817, 'Molten Behemoth', 'A giant born from magma, it attacks with a magma punch.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4035199,3,0,0,17,1200,1700,5,32,32,0);
INSERT OR REPLACE INTO "texts" VALUES (4035199, 'Shapesnatch', 'A bow tie with horrible power, it attacks an opponent by controlling others.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31242786,3,0,0,17,1200,0,4,131072,1,0);
INSERT OR REPLACE INTO "texts" VALUES (31242786, 'Souleater', 'A living wonder of mystery.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83986578,3,0,0,33,1700,1000,4,16384,1,2);
INSERT OR REPLACE INTO "texts" VALUES (83986578, 'King Tiger Wanghu', 'When a monster(s) with 1400 or less ATK is Normal Summoned or Special Summoned: Destroy those monsters with 1400 or less ATK. This card must be face-up on the field to activate and to resolve this effect.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45547649,3,0,0,33,1600,1600,4,512,8,512);
INSERT OR REPLACE INTO "texts" VALUES (45547649, 'Birdface', 'When this card is sent to the Graveyard as a result of battle, you can add 1 "Harpie Lady" from your Deck to your hand. Then shuffle your Deck.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82642348,3,0,0,33,1000,1700,4,8,32,134217730);
INSERT OR REPLACE INTO "texts" VALUES (82642348, 'Kryuel', 'When this card is sent to the Graveyard as a result of battle, toss a coin and call it. If you call it right, destroy 1 monster on your opponent''s side of the field.', 'Coin toss', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42364374,3,0,0,33,2000,2000,3,2048,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (42364374, 'Arsenal Bug', 'If you control no other Insect-Type monsters, this card''s ATK and DEF become 1000.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17214465,3,0,0,33,700,2000,4,64,2,0);
INSERT OR REPLACE INTO "texts" VALUES (17214465, 'Maiden of the Aqua', 'As long as this card remains face-up on the field, the field is treated as "Umi" (however there is no increasing or decreasing of ATK/DEF due to "Umi"''s effect). If there is an active Field Spell Card on the field, this effect is not applied.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5257687,3,0,0,2097185,200,100,2,8,2,135168);
INSERT OR REPLACE INTO "texts" VALUES (5257687, 'Jowls of Dark Demise', 'FLIP: Take control of 1 monster on your opponent''s side of the field until the end of the turn that this card''s effect is activated. When the controlled monster attacks, it may attack your opponent''s Life Points directly.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44913552,3,0,0,33,1900,1700,6,32,32,0);
INSERT OR REPLACE INTO "texts" VALUES (44913552, 'Timeater', 'If this card destroys an opponent''s monster by battle: Your opponent skips their next Main Phase 1.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70307656,3,0,0,33,0,100,3,64,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (70307656, 'Mucus Yolk', 'This card can attack your opponent''s Life Points directly. Each time this card inflicts Battle Damage to your opponent''s Life Points, increase the ATK of this card by 1000 points during your next Standby Phase. The ATK increase lasts as long as this card remains face-up on the field.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2792265,3,0,0,33,700,500,3,64,16,131072);
INSERT OR REPLACE INTO "texts" VALUES (2792265, 'Servant of Catabolism', 'This monster may attack your opponent''s Life Points directly.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75285069,3,0,0,33,2800,2900,9,4,16,1);
INSERT OR REPLACE INTO "texts" VALUES (75285069, 'Moisture Creature', 'If you Tribute Summon this monster by Tributing 3 monsters on the field, destroy all Spell and Trap Cards on your opponent''s side of the field.', 'Tribute Summon this monster by Tributing 3 monsters on the field', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80233946,3,0,0,33,1100,1100,3,64,2,65536);
INSERT OR REPLACE INTO "texts" VALUES (80233946, 'Gora Turtle', 'As long as this card remains face-up on the field, monsters with an ATK equal to 1900 or more cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16222645,3,0,0,33,500,800,2,1,8,2);
INSERT OR REPLACE INTO "texts" VALUES (16222645, 'Sasuke Samurai', 'At the start of the Damage Step, if this card attacks a face-down Defense Position monster: Destroy that face-down monster.', '里侧守备的攻击对象怪兽破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43716289,3,0,0,2097185,1000,1800,4,16,1,4194304);
INSERT OR REPLACE INTO "texts" VALUES (43716289, 'Poison Mummy', 'FLIP: Inflict 500 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89111398,3,0,0,545,2200,1800,6,16,1,18);
INSERT OR REPLACE INTO "texts" VALUES (89111398, 'Dark Dust Spirit', 'Cannot be Special Summoned. During the End Phase of the turn this card is Normal Summoned or flipped face-up: Return it to the hand. When this card is Normal Summoned or flipped face-up: Destroy all other face-up monsters on the field.', 'Spirit', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16509093,3,0,0,33,1600,1700,4,16,1,10240);
INSERT OR REPLACE INTO "texts" VALUES (16509093, 'Royal Keeper', 'Once per turn, you can flip this card into face-down Defense Position. When this card is flipped face-up, it gains 300 ATK and DEF until the end of the turn. (If attacked, this effect resolves after damage calculation.)', '变成里侧守备', '攻守上升', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42994702,3,0,0,33,1500,1500,4,16,1,10240);
INSERT OR REPLACE INTO "texts" VALUES (42994702, 'Wandering Mummy', 'You can flip this card into face-down Defense Position once per turn during your Main Phase. After you use this effect, rearrange the face-down Defense Position monsters on your side of the field, then return them in face-down Defense Position.', '变成里侧守备', '攻守上升', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88989706,3,0,0,33,1900,2300,6,2,32,-2147221504);
INSERT OR REPLACE INTO "texts" VALUES (88989706, 'Great Dezard', 'When this monster destroys the following number of monsters as a result of battle, the following effects are activated in order:  One: As long as this card remains face-up on the field, negate the activation and effects of all Spell and Trap Cards that target this card and destroy them.  Two: You can Special Summon 1 "Fushioh Richie" from your hand or your Deck by Tributing this card during your Main Phase.', 'Destroy', '無効', '特殊召喚', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15383415,3,0,0,33,500,1000,3,2048,32,2050);
INSERT OR REPLACE INTO "texts" VALUES (15383415, 'Swarm of Scarabs', 'Once per turn, you can flip this card into face-down Defense Position. When this card is Flip Summoned, destroy 1 monster your opponent controls.', '变成里侧守备表示', '破坏对方1只怪兽', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41872150,3,0,0,33,1000,500,3,2048,32,2049);
INSERT OR REPLACE INTO "texts" VALUES (41872150, 'Swarm of Locusts', 'Once per turn, you can flip this card into face-down Defense Position. When this card is Flip Summoned, destroy 1 Spell or Trap Card your opponent controls.', '变成里侧守备表示', '破坏对方1张魔法·陷阱卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78266168,3,0,0,33,1700,2000,5,16,1,2050);
INSERT OR REPLACE INTO "texts" VALUES (78266168, 'Giant Axe Mummy', 'You can flip this card into face-down Defense Position once per turn during your Main Phase. If the ATK of a monster on your opponent''s side of the field that attacks this card in face-down Defense Position is lower than the DEF of this monster, the attacking monster is destroyed.', 'Destroy', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14261867,3,0,0,33,300,200,2,2048,32,10240);
INSERT OR REPLACE INTO "texts" VALUES (14261867, '8-Claws Scorpion', 'Once per turn, you can flip this card into face-down Defense Position. When this card attacks an opponent''s face-down Defense Position monster, this card''s ATK becomes 2400 during damage calculation only.', '变成里侧守备', '攻击变化', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40659562,3,0,5374044,33,1700,2400,5,256,1,2064);
INSERT OR REPLACE INTO "texts" VALUES (40659562, 'Guardian Sphinx', 'Once per turn: You can change this card to face-down Defense Position. When this card is Flip Summoned: Return all monsters your opponent controls to the hand.', '变成里侧守备表示', '对方场上的全部怪兽返回手牌', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77044671,3,0,0,33,1200,1400,4,16,1,1310720);
INSERT OR REPLACE INTO "texts" VALUES (77044671, 'Pyramid Turtle', 'When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 Zombie-Type monster with 2000 or less DEF from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3549275,3,0,0,2097185,200,300,3,256,16,138412032);
INSERT OR REPLACE INTO "texts" VALUES (3549275, 'Dice Jar', 'FLIP: Both players roll a six-sided die. The player with the lower result takes damage equal to their opponent''s roll x 500. However, if the winner rolled a 6, the loser takes 6000 damage. If the rolls are the same, both players roll again.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40933924,3,0,26,33,1000,1000,4,1,32,128);
INSERT OR REPLACE INTO "texts" VALUES (40933924, 'Dark Scorpion Burglars', 'When this card inflicts Battle Damage to your opponent''s Life Points, your opponent selects 1 Spell Card from their Deck and sends it to the Graveyard. Then shuffle the Deck.', 'Select 1 Spell Card to send to the Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76922029,3,0,0,33,1400,1500,4,1,32,200);
INSERT OR REPLACE INTO "texts" VALUES (76922029, 'Don Zaloog', 'When this card inflicts Battle Damage to your opponent, you can either:
● Discard 1 random card from your opponent''s hand. OR
● Send the top 2 cards of your opponent''s Deck to the Graveyard.', 'Select effect', 'Discard 1 random card from your opponent''s hand.', 'Send the top 2 cards of your opponent''s Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2326738,3,0,0,33,500,600,3,16,1,2304);
INSERT OR REPLACE INTO "texts" VALUES (2326738, 'Des Lacooda', 'Once per turn, you can flip this card into face-down Defense Position. When this card is Flip Summoned, draw 1 card.', '变成里侧守备表示', 'Draw 1 Card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39711336,3,0,0,33,2600,2900,7,16,32,-2147221504);
INSERT OR REPLACE INTO "texts" VALUES (39711336, 'Fushioh Richie', 'This card cannot be Normal Summoned or Set. This card can only be Special Summoned from your hand or your Deck by Tributing 1 "Great Dezard" that has fulfilled the condition. You can flip this card into face-down Defense Position once per turn during your Main Phase. As long as this monster remains face-up on the field, negate the activation and effects of all Spell and Trap Cards that target this card and destroy them. When this card is flipped face-up, you can Special Summon 1 Zombie-Type monster from your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2204140,3,0,0,2,0,0,0,0,0,1311748);
INSERT OR REPLACE INTO "texts" VALUES (2204140, 'Book of Life', 'Target 1 Zombie-Type monster in your Graveyard and 1 monster in your opponent''s Graveyard; Special Summon the first target, also banish the second target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38699854,3,0,0,2,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (38699854, 'Book of Taiyou', 'Flip 1 face-down monster on the field into face-up Attack Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14087893,3,0,0,65538,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (14087893, 'Book of Moon', 'Target 1 face-up monster on the field; change that target to face-down Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41482598,3,0,0,131074,0,0,0,0,0,264);
INSERT OR REPLACE INTO "texts" VALUES (41482598, 'Mirage of Nightmare', 'During your opponent''s Standby Phase, draw cards until you have 4 cards in your hand. During your Standby Phase, discard to the Graveyard the same number of random cards you drew with this card''s effect.', 'Draw card', '丢弃', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77876207,3,0,0,2,0,0,0,0,0,131072);
INSERT OR REPLACE INTO "texts" VALUES (77876207, 'Secret Pass to the Treasures', 'Select 1 face-up monster with an ATK equal to 1000 points or less on your side of the field. During the turn this card is activated, the selected monster can attack your opponent''s Life Points directly.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4861205,3,0,0,131074,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (4861205, 'Call of the Mummy', 'Once per turn: You can Special Summon 1 Zombie-Type monster from your hand. You must control no monsters to activate and to resolve this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40350910,3,0,0,2,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (40350910, 'Timidity', 'Neither player can destroy Set Spell and Trap Cards on the field until your opponent''s next End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76754619,3,0,0,65538,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (76754619, 'Pyramid Energy', 'You can select and activate 1 of the following effects:
● Increase the ATK of all face-up monsters on your side of the field by 200 points until the End Phase of the turn this card is activated.
● Increase the DEF of all face-up monsters on your side of the field by 500 points until the End Phase of the turn this card is activated.', 'Increase the ATK of all face-up monsters on your side of the field by 200 points until the End Phase', 'Increase the DEF of all face-up monsters on your side of the field by 500 points until the End Phase', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3149764,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (3149764, 'Tutan Mask', 'When a Spell/Trap Card is activated that targets exactly 1 Zombie-Type monster on the field (and no other cards): Negate the activation, and if you do, destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39537362,3,0,0,131076,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (39537362, 'Ordeal of a Traveler', 'You can activate this card''s effect when your opponent declares an attack. Your opponent selects 1 random card in your hand and calls the type of the card (Monster, Spell, or Trap). If your opponent calls it wrong, the attacking monster is returned to its owner''s hand.', 'Declare card type', 'Use the effect of "Ordeal of a Traveler"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76532077,3,0,0,131076,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (76532077, 'Bottomless Shifting Sand', 'At the end of your opponent''s turn, destroy the face-up monster(s) with the highest ATK on the field. During your own Standby Phase, if you have 4 or less cards in your hand, this card is destroyed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2926176,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (2926176, 'Curse of Royal', 'Negate the activation and the effect of a Spell or Trap Card that includes the effect of destroying 1 Spell or Trap Card and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38411870,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (38411870, 'Needle Ceiling', 'When there are 4 or more monsters on the field: Destroy all face-up monsters.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65810489,3,0,0,4,0,0,0,0,0,786432);
INSERT OR REPLACE INTO "texts" VALUES (65810489, 'Statue of the Wicked', 'When this face-down card is destroyed and sent to the Graveyard, Special Summon 1 "Wicked Token" (Fiend-Type/DARK/Level 4 /ATK 1000/DEF 1000) on your side of the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1804528,3,0,0,4,0,0,0,0,0,66);
INSERT OR REPLACE INTO "texts" VALUES (1804528, 'Dark Coffin', 'When this face-down card is destroyed and sent to the Graveyard, your opponent selects and executes 1 of the following effects:
● Discard 1 random card in their hand.
● Select 1 monster on their side of the field and destroy it.', 'Select effect', 'Discard 1 random card', 'Select 1 monster on your side of the field and destroy it', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38299233,3,0,0,131076,0,0,0,0,0,134217730);
INSERT OR REPLACE INTO "texts" VALUES (38299233, 'Needle Wall', 'Once per turn, during your Standby Phase: Roll a six-sided die. Treat your opponent''s Monster Card Zones as numbers 1-5, counting from your right, and destroy the monster that is in the same Monster Card Zone as the result. If the result is 6, roll again.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64697231,3,0,0,4,0,0,0,0,0,96);
INSERT OR REPLACE INTO "texts" VALUES (64697231, 'Trap Dustshoot', 'Activate only if your opponent has 4 or more cards in their hand. Look at your opponent''s hand, select 1 Monster Card in it, and return that card to its owner''s Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1082946,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (1082946, 'Pyro Clock of Destiny', 'Move the turn count forward by 1 turn. The turn in which this card is activated continues as normal.', 'Please select the card to mova turn count forward', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37576645,3,0,0,4,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (37576645, 'Reckless Greed', 'Draw 2 cards and skip your next 2 Draw Phases.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63571750,3,0,0,4,0,0,0,0,0,1024);
INSERT OR REPLACE INTO "texts" VALUES (63571750, 'Pharaoh''s Treasure', 'After activation, put this card face-up in your Deck and shuffle it. When you draw this card, send it to the Graveyard and add 1 card in your Graveyard (except this card) to your hand.', '回收', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24530661,3,0,0,17,1750,1000,4,16,1,0);
INSERT OR REPLACE INTO "texts" VALUES (24530661, 'Master Kyonshee', 'A wandering Kyonshee searching for a strong rival to defeat. They say he was known as the master of all martial arts.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51934376,3,0,0,17,1700,1500,4,65536,2,0);
INSERT OR REPLACE INTO "texts" VALUES (51934376, 'Kabazauls', 'A huge monster in the shape of a hippopotamus. The sneezing from his gigantic body is so fierce that people mistake it for a hurricane.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97923414,3,0,0,17,1600,1900,4,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (97923414, 'Inpachi', 'A log that attacks lost travelers in the forest. Originally a big tree, it was cut down and possessed by a wicked spirit.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90980792,3,0,22,33,1200,1500,4,8,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (90980792, 'Dark Jeroid', 'When this card is Summoned: Target 1 face-up monster on the field; it loses 800 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4335645,3,0,0,33,1200,800,4,8,32,2);
INSERT OR REPLACE INTO "texts" VALUES (4335645, 'Newdoria', 'When this card is destroyed by battle and sent to the Graveyard: Target 1 monster on the field; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76052811,3,0,0,33,2000,1400,5,8,32,64);
INSERT OR REPLACE INTO "texts" VALUES (76052811, 'Helpoemer', 'Cannot be Special Summoned from the Graveyard. If this card was destroyed by battle and sent to the Graveyard, this effect activates at the end of each of your opponent''s Battle Phases: Discard 1 random card from your opponent''s hand. This card must be in the Graveyard to activate and to resolve this effect', '戦闘によって破壊され墓地に送られた場合効果が発動', 'カードを捨てる', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24317029,3,0,46,2097185,1200,2000,4,2,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (24317029, 'Gravekeeper''s Spy', 'FLIP: Special Summon 1 "Gravekeeper''s" monster with 1500 or less ATK from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50712728,3,0,46,33,800,800,3,2,32,4194304);
INSERT OR REPLACE INTO "texts" VALUES (50712728, 'Gravekeeper''s Curse', 'When this card is Summoned: Inflict 500 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37101832,3,0,46,2097185,1000,1900,4,2,32,16);
INSERT OR REPLACE INTO "texts" VALUES (37101832, 'Gravekeeper''s Guard', 'FLIP: Select 1 monster your opponent controls and return it to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63695531,3,0,46,33,1500,1000,4,2,32,16384);
INSERT OR REPLACE INTO "texts" VALUES (63695531, 'Gravekeeper''s Spear Soldier', 'During battle between this attacking card and a Defense Position monster whose DEF is lower than the ATK of this card, inflict the difference as Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99690140,3,0,46,33,700,500,3,2,32,4194304);
INSERT OR REPLACE INTO "texts" VALUES (99690140, 'Gravekeeper''s Vassal', 'Any battle damage this card inflicts to your opponent is treated as effect damage instead.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26084285,3,0,46,33,1000,1000,4,2,32,-2147483645);
INSERT OR REPLACE INTO "texts" VALUES (26084285, 'Gravekeeper''s Watcher', 'When your opponent activates an effect whereby your opponent discards a card(s) from his/her hand, you can send this card from your hand to the Graveyard to negate the activation of the effect and destroy it.', '丢弃手牌效果无效并且破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62473983,3,0,46,33,1900,1200,5,2,32,33816576);
INSERT OR REPLACE INTO "texts" VALUES (62473983, 'Gravekeeper''s Chief', 'You can only control 1 "Gravekeeper''s Chief". Cards in your Graveyard are unaffected by "Necrovalley". When this card is Tribute Summoned, you can select 1 "Gravekeeper''s" monster from your Graveyard and Special Summon it.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99877698,3,0,46,33,1400,1200,4,2,32,4194304);
INSERT OR REPLACE INTO "texts" VALUES (99877698, 'Gravekeeper''s Cannonholder', 'You can Tribute 1 "Gravekeeper''s" monster, except "Gravekeeper''s Cannonholder", to inflict 700 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25262697,3,0,46,33,1500,1500,4,2,32,2048);
INSERT OR REPLACE INTO "texts" VALUES (25262697, 'Gravekeeper''s Assailant', 'If "Necrovalley" is on the field when this card declares an attack, you can select 1 face-up monster your opponent controls and change its battle position.', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51351302,3,0,0,33,1600,1600,4,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (51351302, 'A Man with Wdjat', 'When you Normal Summon this card, and during each of your Standby Phases, select 1 Set card on your opponent''s side of the field. Pick it up and look at it, then return it to its original position.', '-', 'めくって確認するカードを選んでください', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98745000,3,0,0,33,2700,1200,7,32768,16,32);
INSERT OR REPLACE INTO "texts" VALUES (98745000, 'Mystical Knight of Jackal', 'When this card destroys 1 monster on your opponent''s side of the field and sends it to your opponent''s Graveyard as a result of battle, you can then return the card to the top of your opponent''s Deck.', 'Return to deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24140059,3,0,0,2097185,500,300,2,16384,32,512);
INSERT OR REPLACE INTO "texts" VALUES (24140059, 'A Cat of Ill Omen', 'FLIP: Select 1 Trap Card from your Deck and place it on top of your Deck. If "Necrovalley" is on the field, you can add the selected card to your hand instead.', 'Add to hand?', 'Select Trap card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51534754,3,0,0,33,800,1400,3,64,2,2);
INSERT OR REPLACE INTO "texts" VALUES (51534754, 'Yomi Ship', 'When this card is destroyed by battle and sent to the Graveyard: Destroy the monster that destroyed this card.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87523462,3,0,0,33,1700,1200,4,512,8,32);
INSERT OR REPLACE INTO "texts" VALUES (87523462, 'Winged Sage Falcos', 'When this card destroys an opponent''s face-up Attack Position monster by battle and sends it to their Graveyard: You can place that monster on top of their Deck.', 'Return to deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23927567,3,0,0,2097185,300,500,2,512,8,512);
INSERT OR REPLACE INTO "texts" VALUES (23927567, 'An Owl of Luck', 'FLIP: Select 1 Field Spell Card from your Deck and place it on top of your Deck. If "Necrovalley" is on the field, you can add the selected Field Spell Card to your hand, instead.', 'Add to hand?', 'Select Field Spell card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50412166,3,0,0,33,100,100,1,256,1,8);
INSERT OR REPLACE INTO "texts" VALUES (50412166, 'Charm of Shabti', 'During either player''s turn: You can discard this card; until the End Phase, "Gravekeeper''s" monsters you control cannot be destroyed by battle.', '名称中带有「守墓」的怪兽卡所受战斗伤害为0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86801871,3,0,0,2097185,600,300,2,524288,1,4980736);
INSERT OR REPLACE INTO "texts" VALUES (86801871, 'Cobra Jar', 'FLIP: Special Summon 1 "Poisonous Snake Token" (Reptile-Type/EARTH/3 Stars/ATK 1200/DEF 1200). When the "Poisonous Snake Token" is destroyed as a result of battle, inflict 500 points of damage to your opponent''s Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23205979,3,0,0,33,300,200,3,16,32,16777282);
INSERT OR REPLACE INTO "texts" VALUES (23205979, 'Spirit Reaper', 'Cannot be destroyed by battle. After resolving a card effect that targets this face-up card, destroy this card. When this card inflicts battle damage to your opponent by a direct attack: Discard 1 random card from their hand.', 'Discard hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59290628,3,0,0,33,500,400,2,16,32,131072);
INSERT OR REPLACE INTO "texts" VALUES (59290628, 'Nightmare Horse', 'This card can attack your opponent''s Life Points directly even if there is a monster on your opponent''s side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85684223,3,0,0,97,800,600,5,16,32,16908352);
INSERT OR REPLACE INTO "texts" VALUES (85684223, 'Reaper on the Nightmare', '"Spirit Reaper" + "Nightmare Horse"
This card is not destroyed as a result of battle. Destroy this card when it is targeted by the effect of a Spell, Trap or Effect Monster. This card can attack your opponent''s Life Points directly even if there is a monster on your opponent''s side of the field. If this card successfully attacks your opponent''s Life Points directly, your opponent discards 1 card randomly from his/her hand.', 'Discard hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78053598,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (78053598, 'Dark Designator', 'Declare 1 Monster Card name. If the declared card is in your opponent''s Deck, add 1 of that card to your opponent''s hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12183332,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (12183332, 'Card Shuffle', 'Pay 300 Life Points to use this card''s effect. Shuffle either your or your opponent''s Deck. You can use this effect during your own turn, once per turn.', '-', '自分のデッキをシャッフルする', '相手のデッキをシャッフルする', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58577036,3,0,0,2,0,0,0,0,0,262152);
INSERT OR REPLACE INTO "texts" VALUES (58577036, 'Reasoning', 'Your opponent declares a monster Level. Excavate cards from the top of your Deck until you excavate a monster that can be Normal Summoned/Set. If that monster is the same Level as the one declared by your opponent, send all excavated cards to the Graveyard. If not, Special Summon the excavated monster, also send the remaining cards to the Graveyard.', 'Select monster Level', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85562745,3,0,0,131074,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (85562745, 'Dark Room of Nightmare', 'Each time your opponent takes damage from a card effect, except "Dark Room of Nightmare", inflict 300 damage to your opponent.', '给对方300伤害', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11961740,3,0,0,2,0,0,0,0,0,516);
INSERT OR REPLACE INTO "texts" VALUES (11961740, 'Different Dimension Capsule', 'Select 1 card from Deck and remove it from play face-down. During your 2nd Standby Phase after activation, destroy this card and add the removed card to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47355498,3,0,145,524290,0,0,0,0,0,-2147475456);
INSERT OR REPLACE INTO "texts" VALUES (47355498, 'Necrovalley', 'All "Gravekeeper''s" monsters gain 500 ATK and DEF. Cards in either player''s Graveyard cannot be banished. Negate any card effect that would move a card in the Graveyard, other than itself, to a different place.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84740193,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (84740193, 'Buster Rancher', 'Only a monster with an ATK of 1000 points or less can be equipped with this card. During damage calculation, increase the ATK of the monster equipped with this card by 2500 points if the opponent''s monster that battles it is in Attack Position and its ATK is 2500 or more, OR if the opponent''s monster that battles it is in Defense Position and its DEF is 2500 or more.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10248192,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (10248192, 'Hieroglyph Lithograph', 'Pay 1000 Life Points. During the current Duel, your hand size limit becomes 7.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47233801,3,0,0,131074,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (47233801, 'Dark Snake Syndrome', 'Inflict damage to both players'' Life Points during each of your Standby Phases. The first damage begins at 200 points and is doubled during each of your following Standby Phases.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73628505,3,0,0,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (73628505, 'Terraforming', 'Add 1 Field Spell Card from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10012614,3,0,0,131074,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (10012614, 'Banner of Courage', 'During your Battle Phase only, all face-up monsters you control gain 200 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46411259,3,0,0,2,0,0,0,0,0,268697608);
INSERT OR REPLACE INTO "texts" VALUES (46411259, 'Metamorphosis', 'Tribute 1 monster. Special Summon 1 Fusion Monster from your Extra Deck with the same Level as the Tributed monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72405967,3,0,0,2,0,0,0,0,0,72);
INSERT OR REPLACE INTO "texts" VALUES (72405967, 'Royal Tribute', 'If you control "Necrovalley": Both players discard any monsters in their hands.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5990062,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (5990062, 'Reversal Quiz', 'Send all cards in your hand and on your side of the field to the Graveyard. Call the type of card (Spell, Trap, or Monster) on top of your Deck. If you call it right, exchange your current Life Points with your opponent''s current ones.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65830223,3,0,0,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (65830223, 'Coffin Seller', 'Each time a monster(s) is sent to your opponent''s Graveyard: Inflict 300 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41398771,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (41398771, 'Curse of Aging', 'Discard 1 card from your hand. Decrease the ATK and DEF of all monsters on your opponent''s side of the field by 500 points until the end of the turn this card is activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78783370,3,0,0,1048580,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (78783370, 'Barrel Behind the Door', 'Activate only when a card''s effect that would inflict damage to you is activated. Your opponent takes the damage instead.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4178474,3,0,0,4,0,0,0,0,0,3);
INSERT OR REPLACE INTO "texts" VALUES (4178474, 'Raigeki Break', 'Discard 1 card, then target 1 card on the field; destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40172183,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (40172183, 'Narrow Pass', 'This card can only be activated when both players have 2 monsters or less on their respective sides of the field. Both players can only Normal Summon up to 2 additional monsters on their sides of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77561728,3,0,0,4,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (77561728, 'Disturbance Strategy', 'Your opponent adds all cards in his/her hand to the Deck and shuffles the Deck. Your opponent then draws the same number of cards that he/she added to the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3055837,3,0,0,1048580,0,0,0,0,0,64);
INSERT OR REPLACE INTO "texts" VALUES (3055837, 'Trap of Board Eraser', 'You can only activate this card when an effect that inflicts damage to your Life Points is activated (except Battle Damage). Negate the Effect Damage you receive and your opponent then selects 1 card from his/her hand and discards it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30450531,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (30450531, 'Rite of Spirit', 'Select 1 "Gravekeeper''s" monster in your Graveyard and Special Summon it. This card''s activation and effect are unaffected by "Necrovalley".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76848240,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (76848240, 'Non Aggression Area', 'You can only activate this card during your Standby Phase. Discard 1 card from your hand. Your opponent cannot Normal Summon, Set and/or Special Summon during his/her next turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2833249,3,0,0,4,0,0,0,0,0,1048576);
INSERT OR REPLACE INTO "texts" VALUES (2833249, 'D. Tribe', 'All monsters on your side of the field are treated as Dragon-Type until the End Phase of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17597059,3,0,0,33,800,600,5,8,32,16);
INSERT OR REPLACE INTO "texts" VALUES (17597059, 'Byser Shock', 'When this card is Normal Summoned, Flip Summoned, or Special Summoned, return all Set cards on the field to their owner''s respective hands.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38723936,3,0,0,2,0,0,0,0,0,262148);
INSERT OR REPLACE INTO "texts" VALUES (38723936, 'Question', 'When activating this card, your opponent cannot check cards in the Graveyard. Your opponent calls the name of the first monster found at the bottom of your Graveyard. If he/she calls it right, the monster is removed from play. If he/she calls it wrong, the monster is Special Summoned to your side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93382620,3,0,0,4,0,0,0,0,0,270336);
INSERT OR REPLACE INTO "texts" VALUES (93382620, 'Rope of Life', 'When a monster(s) is destroyed by battle and sent to your Graveyard: Discard your entire hand (min.1), then target 1 of those monsters; Special Summon it, and if you do, it gains 800 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54704216,3,0,0,131076,0,0,0,0,0,4259840);
INSERT OR REPLACE INTO "texts" VALUES (54704216, 'Nightmare Wheel', 'Activate this card by targeting 1 monster your opponent controls; it cannot attack or change its battle position. When it leaves the field, destroy this card. During each of your Standby Phases: Inflict 500 damage to your opponent. That monster must be on the field to activate and to resolve this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (102380,3,0,0,33,3000,2500,8,8,4,4456448);
INSERT OR REPLACE INTO "texts" VALUES (102380, 'Lava Golem', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) to your opponent''s side of the field by Tributing 2 monsters they control. You cannot Normal Summon/Set the turn you Special Summon this card. During each of the controller''s Standby Phases: The controller takes 1000 damage.', 'Special Summon', '1000 damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
