BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (92418590,3,0,131,33,0,0,8,32,32,1074003968);
INSERT OR REPLACE INTO "texts" VALUES (92418590, 'Gimmick Puppet Dreary Doll', 'If this card is in your Graveyard: You can banish 1 other "Gimmick Puppet" monster from your Graveyard; Special Summon this card from your Graveyard. You can only use this effect of "Gimmick Puppet Dreary Doll" once per turn. This card cannot be used as an Xyz Material for an Xyz Summon, except for the Xyz Summon of a "Gimmick Puppet" monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39806198,3,0,131,33,1000,1000,8,32,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (39806198, 'Gimmick Puppet Magnet Doll', 'If your opponent controls a monster and you control only "Gimmick Puppet" monsters, you can Special Summon this card (from your hand).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5291803,3,0,5374064,33,1800,900,5,256,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (5291803, 'Chronomaly Tula Guardian', 'If there is a face-up Field Spell Card on the field, you can Special Summon this card (from your hand). You can only control 1 "Chronomaly Tula Guardian".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32696942,3,0,0,33,1000,1600,4,1,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (32696942, 'Big Belly Knight', 'If this card as an Xyz Material is sent to the Graveyard to activate an Xyz Monster''s effect: You can Special Summon 1 Level 3 or lower monster from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68084557,3,0,0,8225,2300,2500,7,32,32,256);
INSERT OR REPLACE INTO "texts" VALUES (68084557, 'Power Tool Mecha Dragon', '1 Tuner + 1 or more non-Tuner monsters
During your turn, when an Equip Spell Card(s) is equipped to this card: You can draw 1 card. You can only use this effect of "Power Tool Mecha Dragon" once per turn. Once per turn, during either player''s turn: You can target 1 appropriate face-up Equip Card on the field; equip that target to this card.', 'Draw', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4179255,3,0,0,8225,2100,3000,7,8192,32,258);
INSERT OR REPLACE INTO "texts" VALUES (4179255, 'Ancient Pixie Dragon', '1 Tuner + 1 or more non-Tuner monsters
After resolving a Field Spell Card that was activated during your turn: Draw 1 card. You can only use this effect of "Ancient Pixie Dragon" once per turn. Once per turn: You can target 1 face-up Attack Position monster on the field; destroy that target. There must be a face-up Field Spell Card on the field to activate and to resolve this effect.', 'Add to hand', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67968069,3,0,67,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (67968069, 'Junk Puppet', 'Target 1 "Gimmick Puppet" monster in your Graveyard; Special Summon that monster. You can only activate 1 "Junk Puppet" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4357063,3,0,112,524290,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (4357063, 'Chronomaly City Babylon', 'Once per turn: You can banish 1 "Chronomaly" monster from your Graveyard, then target 1 "Chronomaly" monster in your Graveyard with the same Level as the banished monster; Special Summon it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30341772,3,0,0,2,0,0,0,0,0,4194306);
INSERT OR REPLACE INTO "texts" VALUES (30341772, 'Utopia Buster', 'If you control a "Utopia" monster: Destroy the 1 face-up monster your opponent controls that has the lowest ATK (if it''s a tie, you get to choose), and if you do, inflict damage to your opponent equal to the destroyed monster''s ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72837335,3,0,112,33,300,900,3,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (72837335, 'Chronomaly Gordian Knot', 'When this card is Normal Summoned: You can Special Summon 1 "Chronomaly" monster from your hand, and if you do, this card''s Level becomes the Summoned monster''s Level.', 'Special Summon 1 "Chronomaly" monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8226374,3,0,131,33,0,100,4,32,32,0);
INSERT OR REPLACE INTO "texts" VALUES (8226374, 'Gimmick Puppet Humpty Dumpty', 'When this card is Normal or Special Summoned: You can Special Summon 1 "Gimmick Puppet" monster from your hand. You can only use this effect of "Gimmick Puppet Humpty Dumpty" once per turn.', 'Special Summon 1 "Gimmick Puppet" monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34620088,3,0,131,33,1000,1000,8,32,32,0);
INSERT OR REPLACE INTO "texts" VALUES (34620088, 'Gimmick Puppet Shadow Feeler', 'Cannot be destroyed by battle. When you take battle damage from a direct attack while this card is in your Graveyard: You can Special Summon this card from your Graveyard in face-up Attack Position, and if you do, take 1000 damage. You can only use this effect of "Gimmick Puppet Shadow Feeler" once per turn. If this card as an Xyz Material would be sent to the Graveyard, banish it instead.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71015787,3,0,0,33,1000,2000,4,131072,2,0);
INSERT OR REPLACE INTO "texts" VALUES (71015787, 'Silent Wobby', 'During your Main Phase: You can Special Summon this card from your hand to your opponent''s side of the field. When Summoned this way: Draw 1 card, and if you do, your opponent gains 2000 Life Points. You can only use this effect of "Silent Wobby" once per turn. The hand size limit of this card''s controller becomes 3.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7409792,3,0,0,33,1600,600,4,16384,8,0);
INSERT OR REPLACE INTO "texts" VALUES (7409792, 'Dynatherium', 'You can Special Summon this card (from your hand). You can only Special Summon "Dynatherium" once per turn this way. When you do: Your opponent can target 1 Level 4 monster in either player''s Graveyard; they Special Summon that target to their side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8198620,3,0,0,97,3000,0,8,8192,32,270336);
INSERT OR REPLACE INTO "texts" VALUES (8198620, 'Dragonecro Nethersoul Dragon', '2 Zombie-Type monsters
Must first be Fusion Summoned. Monsters cannot be destroyed by battle with this card. At the end of the Damage Step, if this card battled a monster that has an original Level: That monster''s ATK becomes 0, also, if that monster is still face-up on the field, Special Summon 1 "Dark Soul Token" (Zombie-Type/DARK/Level ?/ATK ?/DEF 0). (When Summoned, its Level and ATK become equal to the original Level and ATK of that monster.) You can only control 1 "Dragonecro Nethersoul Dragon".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34408491,3,0,0,8225,3000,3000,8,8192,32,0);
INSERT OR REPLACE INTO "texts" VALUES (34408491, 'Beelze of the Diabolic Dragons', '1 DARK Tuner + 1 or more non-Tuner monsters
Cannot be destroyed by battle or by card effects. When you take damage from an attack involving this card, or from an opponent''s card effect: This card gains ATK equal to the damage you took.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60992105,3,0,0,8225,2800,1600,8,8192,32,0);
INSERT OR REPLACE INTO "texts" VALUES (60992105, 'Blackfeather Darkrage Dragon', '1 Tuner + 1 or more non-Tuner monsters
Once per turn, when you take damage from an attack or a card effect: You can send up to 5 cards from the top of your Deck to the Graveyard, then if any monsters were sent to the Graveyard by this effect, this card gains 400 ATK.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6387204,3,0,7344200,8388641,3300,3300,7,32,16,4194304);
INSERT OR REPLACE INTO "texts" VALUES (6387204, 'Number C6: Chronomaly Chaos Atlandis', '3 Level 7 monsters
If you activate any of this card''s effects, your opponent takes no damage for the rest of this turn. Once per turn: You can target 1 monster your opponent controls; equip it to this card. This card gains 1000 ATK for each monster equipped to it by this effect. If this card has "Number 6: Chronomaly Atlandis" as an Xyz Material, it gains this effect.
● You can detach 3 Xyz Materials from this card, then send all "Number" monsters (min. 1) equipped to this card by its own effect to the Graveyard; your opponent''s Life Points become 100.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33776843,3,0,8589384,8388641,2500,1500,9,32,32,0);
INSERT OR REPLACE INTO "texts" VALUES (33776843, 'Number C15: Gimmick Puppet Giant Hunter', '3 Level 9 monsters
Once per turn: You can detach 1 Xyz Material from this card, then target 1 card your opponent controls; destroy that target, and if you do, if that target was a monster, inflict damage to your opponent equal to its original ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69170557,3,0,8589384,8388641,3300,2000,9,32,32,0);
INSERT OR REPLACE INTO "texts" VALUES (69170557, 'Number C40: Gimmick Puppet of Dark Strings', '3 Level 9 monsters
When this card is Special Summoned: Destroy all monsters on the field with String Counters, and if you destroyed a monster(s) with this effect, draw 1 card, then inflict damage to your opponent equal to the highest original ATK among those destroyed monsters (your choice, if tied). Once per turn: You can detach 1 Xyz Material from this card; place 1 String Counter on each face-up monster your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6165656,3,0,8589384,8388641,3500,2500,9,32,32,0);
INSERT OR REPLACE INTO "texts" VALUES (6165656, 'Number C88: Gimmick Puppet Disaster Leo', '4 Level 9 monsters
Must be Special Summoned with a "Rank-Up-Magic" Spell Card that targeted "Number 88: Gimmick Puppet of Leo", and cannot be Special Summoned by other ways. This card cannot be targeted by card effects. Once per turn: You can detach 1 Xyz Material from this card; inflict 1000 damage to your opponent. During your End Phase, if your opponent''s Life Points are 2000 or less and this card has no Xyz Materials, you win the Duel.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32559361,3,0,4168,8388641,3600,3200,10,32,16,0);
INSERT OR REPLACE INTO "texts" VALUES (32559361, 'Number C9: Chaos Dyson Sphere', '3 Level 10 monsters
At the start of the Damage Step, if this card battles an opponent''s monster: You can attach that monster to this card as a face-up Xyz Material. Once per turn: You can inflict 300 damage to your opponent for each Xyz Material attached to this card. If this card has "Number 9: Dyson Sphere" as an Xyz Material, it gains this effect.
● Once per turn: You can detach any number of Xyz Materials from this card; inflict 800 damage to your opponent for each.', '  ', 'Inflict 300 damage to your opponent for each Xyz Material attached to this card.', 'Inflict 800 damage to your opponent for each card detached', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69058960,3,0,72,8388641,500,500,1,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (69058960, 'Number 13: Embodiment of Crime', '2 Level 1 monsters
Once per turn, during either player’s turn: You can detach 1 Xyz Material from this card; change all monsters your opponent controls to face-up Attack Position, also all monsters your opponent currently controls must attack this card this turn, if able. While you control "Number 31: Embodiment of Punishment", this card gains these effects.
● This card cannot be destroyed by battle or by card effects while it has Xyz Material.
● Your opponent takes any battle damage you would have taken from attacks on this card.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95442074,3,0,72,8388641,500,500,1,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (95442074, 'Number 31: Embodiment of Punishment', '2 Level 1 monsters
Once per turn, during either player''s turn: You can detach 1 Xyz Material from this card; change all monsters your opponent controls to face-up Attack Position, also all monsters your opponent currently controls must attack this card this turn, if able. While you control "Number 13: Embodiment of Crime", this card gains these effects.
● This card cannot be destroyed by battle or by card effects while it has Xyz Material.
● Your opponent takes any battle damage you would have taken from attacks on this card.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31437713,3,0,72,8388641,2000,1500,4,8192,1,0);
INSERT OR REPLACE INTO "texts" VALUES (31437713, 'Number 82: Heartlandraco', '2 Level 4 monsters
While you control a face-up Spell Card(s), this card cannot be targeted for attacks. Once per turn: You can detach 1 Xyz Material from this card; this turn, this card can attack your opponent directly, but other monsters cannot attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68836428,3,0,0,8388641,1800,1500,3,262144,2,0);
INSERT OR REPLACE INTO "texts" VALUES (68836428, 'Tri-Edge Levia', '3 Level 3 monsters
Banish any monster destroyed by battle with this card. Once per turn, during either player''s turn: You can detach 1 Xyz Material from this card, then target 1 face-up monster on the field; it loses 800 ATK, also its effects are negated. These changes last until the end of this turn.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94220427,3,0,149,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (94220427, 'Rank-Up-Magic Argent Chaos Force', 'Target 1 Rank 5 or higher Xyz Monster you control; Special Summon from your Extra Deck, 1 "Number C" or "CXyz" monster that is 1 Rank higher than that monster you control, by using it as the Xyz Material. (This Special Summon is treated as an Xyz Summon. Xyz Materials attached to it also become Xyz Materials on the Summoned monster.) When a Rank 5 or higher Xyz Monster is Special Summoned to your side of the field while this card is in your Graveyard (except during the Damage Step): You can add this card from your Graveyard to your hand. You can only use this effect of "Rank-Up-Magic Argent Chaos Force" once per Duel.', 'activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21715135,3,0,84,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (21715135, 'Gagaga Academy Emergency Network', 'If your opponent controls a monster and you control no monsters: Special Summon 1 "Gagaga" monster from your Deck. You cannot Special Summon any other monsters, except by Xyz Summon, during the turn you activate this card. You can only activate 1 "Gagaga Academy Emergency Network" per turn.
', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67113830,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (67113830, 'Ghost of a Grudge', 'If your opponent has 8 or more cards in their Graveyard: The ATK of all monsters your opponent currently controls become 0.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38033121,3,0,279052450,33,2000,1700,6,2,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (38033121, 'Dark Magician Girl', 'This card gains 300 ATK for every "Dark Magician" or "Magician of Black Chaos" in either player''s Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48686504,3,0,0,33,500,1400,3,1024,4,1310728);
INSERT OR REPLACE INTO "texts" VALUES (48686504, 'Lonefire Blossom', 'Once per turn, you can Tribute 1 face-up Plant-Type monster to Special Summon 1 Plant-Type monster from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37742478,3,0,0,33,1100,1900,4,4,16,2105368);
INSERT OR REPLACE INTO "texts" VALUES (37742478, 'Honest', 'During your Main Phase: You can return this face-up card from the field to the hand. During either player''s Damage Step, when a LIGHT monster you control battles: You can send this card from your hand to the Graveyard; that monster gains ATK equal to the ATK of the opponent''s monster it is battling, until the end of this turn.', 'Return to hand', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97268402,3,0,0,4129,0,0,1,2,16,-2147483640);
INSERT OR REPLACE INTO "texts" VALUES (97268402, 'Effect Veiler', 'During your opponent''s Main Phase: You can send this card from your hand to the Graveyard, then target 1 face-up Effect Monster your opponent controls; negate that opponent''s face-up monster''s effects until the End Phase (this is a Quick Effect).', '怪兽的效果无效', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26082117,3,0,84,33,1500,1000,4,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (26082117, 'Gagaga Magician', 'Once per turn: You can declare a Level from 1 to 8; this card becomes that Level until the End Phase. You can only control 1 "Gagaga Magician". This card cannot be used as a Synchro Material Monster.', 'Change level', 'Please select a Level from 1 to 8', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93717133,3,0,276496469,33,3000,2500,8,8192,16,1073750020);
INSERT OR REPLACE INTO "texts" VALUES (93717133, 'Galaxy-Eyes Photon Dragon', 'You can Special Summon this card (from your hand) by Tributing 2 monsters with 2000 or more ATK. During either player''s Battle Step, when this card battles an opponent''s monster: You can target the monster this card is battling; banish both it and this card. At the end of the Battle Phase, return any monsters banished by this effect to the field, and if the other monster was an Xyz Monster, this card gains 500 ATK for each Xyz Material it had when it was banished.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99365553,3,0,0,33,2500,1500,6,8192,16,3407872);
INSERT OR REPLACE INTO "texts" VALUES (99365553, 'Lightpulsar Dragon', 'You can Special Summon this card (from your hand) by banishing 1 LIGHT and 1 DARK monsters from your Graveyard. You can Special Summon this card (from your Graveyard) by sending 1 LIGHT and 1 DARK monsters from your hand to the Graveyard. When this card is sent from the field to the Graveyard: You can target 1 Level 5 or higher DARK Dragon-Type monster in your Graveyard; Special Summon that target.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25460258,3,0,0,33,2400,1200,5,8192,32,3407884);
INSERT OR REPLACE INTO "texts" VALUES (25460258, 'Darkflare Dragon', 'You can Special Summon this card (from your hand) by banishing 1 LIGHT and 1 DARK monster from your Graveyard. Once per turn: You can send 1 Dragon-Type monster each from your hand and Deck to the Graveyard to target 1 card from either player''s Graveyard; banish that target.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51858306,3,0,0,33,1600,1000,4,8192,16,3146772);
INSERT OR REPLACE INTO "texts" VALUES (51858306, 'Eclipse Wyvern', 'If this card is sent to the Graveyard: Banish 1 Level 7 or higher LIGHT or DARK Dragon-Type monster from your Deck. If this card in the Graveyard is banished: You can add the monster banished by this effect to your hand.', 'Banish', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28637168,3,0,0,33,300,900,3,512,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (28637168, 'Crane Crane', 'When this card is Normal Summoned: You can target 1 Level 3 monster in your Graveyard; Special Summon that target, but its effects are negated. You can only use the effect of "Crane Crane" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23693634,3,0,0,8225,2800,1000,8,1,32,1318912);
INSERT OR REPLACE INTO "texts" VALUES (23693634, 'Colossal Fighter', '1 Tuner + 1 or more non-Tuner monsters
This card gains 100 ATK for every Warrior-Type monster in any Graveyard. When this card is destroyed by battle and sent to the Graveyard, you can select 1 Warrior-Type monster from either player''s Graveyard, and Special Summon it.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65676461,3,0,72,8388641,2800,2100,4,262144,2,303104);
INSERT OR REPLACE INTO "texts" VALUES (65676461, 'Number 32: Shark Drake', '3 Level 4 monsters
Once per turn, when this attacking card destroys an opponent''s monster by battle and sends it to the Graveyard: You can detach 1 Xyz Material from this card; Special Summon the destroyed monster to your opponent''s side of the field in face-up Attack Position, but it loses 1000 ATK, and if you do summon this way, this card can attack once again during this Battle Phase.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96381979,3,0,121,8388641,2200,1800,4,32768,4,-2146172416);
INSERT OR REPLACE INTO "texts" VALUES (96381979, 'Brotherhood of the Fire Fist - Tiger King', '2 Level 4 Beast-Warrior-Type monsters
When this card is Xyz Summoned: You can Set 1 "Fire Formation" Spell/Trap Card directly from your Deck. Once per turn: You can detach 1 Xyz Material from this card; negate the effects of all face-up Effect Monsters currently on the field, except Beast-Warrior-Type, until the end of your opponent''s turn. When this card is sent from the field to the Graveyard: You can send 3 "Fire Formation" Spell/Trap Cards you control to the Graveyard; Special Summon 2 Level 4 or lower Beast-Warrior-Type monsters with the same ATK from your Deck, in face-up Defense Position.', 'Search and Set', 'Negate effect', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (691925,3,0,0,2,0,0,0,0,0,392);
INSERT OR REPLACE INTO "texts" VALUES (691925, 'Solar Recharge', 'Discard 1 "Lightsworn" monster; draw 2 cards, then send the top 2 cards of your Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25789292,3,0,0,65538,0,0,0,0,0,-2147475456);
INSERT OR REPLACE INTO "texts" VALUES (25789292, 'Forbidden Chalice', 'Target 1 face-up monster on the field; until the end of this turn, that target gains 400 ATK, but its effects are negated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27243130,3,0,0,65538,0,0,0,0,0,33562624);
INSERT OR REPLACE INTO "texts" VALUES (27243130, 'Forbidden Lance', 'Target 1 face-up monster on the field; until the end of this turn, that target loses 800 ATK, but is unaffected by the effects of other Spell/Trap Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96864811,3,0,0,65538,0,0,0,0,0,50339840);
INSERT OR REPLACE INTO "texts" VALUES (96864811, 'Forbidden Dress', 'Target 1 face-up monster on the field; until the end of this turn, that target loses 600 ATK, but cannot be targeted or destroyed by other card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57103969,3,0,124,131074,0,0,0,0,0,1057280);
INSERT OR REPLACE INTO "texts" VALUES (57103969, 'Fire Formation - Tenki', 'When this card is activated: You can add 1 Level 4 or lower Beast-Warrior-Type monster from your Deck to your hand. All Beast-Warrior-Type monsters you control gain 100 ATK. You can only activate 1 "Fire Formation - Tenki" per turn.', 'Add 1 Level 4 or lower Beast-Warrior-Type monster from your Deck to your hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77585513,3,0,188,33,2400,1500,6,32,32,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (77585513, 'Jinzo', 'Trap Cards, and their effects on the field, cannot be activated. Negate all Trap Card effects on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71413901,3,0,110,33,1600,1000,4,2,32,67117057);
INSERT OR REPLACE INTO "texts" VALUES (71413901, 'Breaker the Magical Warrior', 'If this card is Normal Summoned: Place 1 Spell Counter on it (max. 1). This card gains 300 ATK for each Spell Counter on it. You can remove 1 Spell Counter from this card, then target 1 Spell/Trap Card on the field; destroy that target.', 'Place spell counter', 'Gain attack', 'Destroy 1 Spell or Trap Card', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70095154,3,0,278069507,33,2100,1600,5,32,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (70095154, 'Cyber Dragon', 'If your opponent controls a monster and you control no monsters, you can Special Summon this card (from your hand).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78004197,3,0,6,33,2300,1400,5,8,32,262147);
INSERT OR REPLACE INTO "texts" VALUES (78004197, 'Goldd, Wu-Lord of Dark World', 'If this card is discarded to the Graveyard by a card effect: If it was discarded from your hand to your Graveyard by an opponent''s card effect, you can target up to 2 cards your opponent controls; Special Summon this card from the Graveyard, then destroy those cards (if any).', 'Special Summon', 'Destroy card(s) on your opponent''s field?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23995346,3,0,0,65,4500,3800,12,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (23995346, 'Blue-Eyes Ultimate Dragon', '"Blue-Eyes White Dragon" + "Blue-Eyes White Dragon" + "Blue-Eyes White Dragon"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64599569,3,0,259,97,-2,-2,9,32,32,40968);
INSERT OR REPLACE INTO "texts" VALUES (64599569, 'Chimeratech Overdragon', '"Cyber Dragon" + 1 or more Machine-Type monsters
Must be Fusion Summoned and cannot be Special Summoned by other ways. When this card is Fusion Summoned: Send all other cards you control to the Graveyard. The original ATK and DEF of this card each become equal to the number of Fusion Material Monsters used for its Fusion Summon x 800. Each turn, this card can attack your opponent''s monsters a number of times equal to the number of Fusion Material Monsters used for its Fusion Summon.', '这张卡以外的卡送去墓地', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72302403,3,0,0,2,0,0,0,0,0,67584);
INSERT OR REPLACE INTO "texts" VALUES (72302403, 'Swords of Revealing Light', 'Flip all monsters your opponent controls face-up. This card remains on the field for 3 of your opponent''s turns. While this card is face-up on the field, monsters your opponent controls cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32807846,3,0,0,2,0,0,0,0,0,1049088);
INSERT OR REPLACE INTO "texts" VALUES (32807846, 'Reinforcement of the Army', 'Add 1 Level 4 or lower Warrior-Type monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44095762,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (44095762, 'Mirror Force', 'When an opponent''s monster declares an attack: Destroy all Attack Position monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53582587,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (53582587, 'Torrential Tribute', 'When a monster(s) is Summoned: Destroy all monsters on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81059524,3,0,0,33,2200,1700,6,8192,1,4202496);
INSERT OR REPLACE INTO "texts" VALUES (81059524, 'Des Volstgalph', 'When this card destroys an opponent''s monster by battle and sends it to the Graveyard: Inflict 500 damage to your opponent. Each time a Normal or Quick-Play Spell Card resolves, this card gains 200 ATK until the End Phase.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73125233,3,0,190,33,2400,1000,6,512,8,32);
INSERT OR REPLACE INTO "texts" VALUES (73125233, 'Raiza the Storm Monarch', 'When this card is Tribute Summoned: Target 1 card on the field; return that target to the top of the Deck.', 'Return to deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4906301,3,0,0,33,600,1300,3,1,32,65536);
INSERT OR REPLACE INTO "texts" VALUES (4906301, 'Necro Gardna', 'During your opponent''s turn: You can banish this card from your Graveyard; negate the next attack this turn from a monster your opponent controls (this is a Quick Effect).', '1次攻击无效', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65192027,3,0,0,33,2800,1000,7,8192,32,2359303);
INSERT OR REPLACE INTO "texts" VALUES (65192027, 'Dark Armed Dragon', 'Cannot be Normal Summoned or Set. Must be Special Summoned (from your hand) by having exactly 3 DARK monsters in your Graveyard and cannot be Special Summoned by other ways. You can banish 1 DARK monster from your Graveyard to target 1 card on the field; destroy that target.', '不能通常召唤', '墓地暗属性三张时才能特殊召唤', '破坏场上一张卡', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12298909,3,0,0,33,2400,2000,6,8192,16,-2139095037);
INSERT OR REPLACE INTO "texts" VALUES (12298909, 'Prime Material Dragon', 'Any effect that would inflict damage to a player instead increases their Life Points by the same amount. When a card''s effect to destroy a monster(s) on the field is activated, you can send 1 card from your hand to the Graveyard to negate its activation and destroy the card.', 'Negate and destroy effect', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9748752,3,0,190,33,2400,1000,6,8,32,6291460);
INSERT OR REPLACE INTO "texts" VALUES (9748752, 'Caius the Shadow Monarch', 'When this card is Tribute Summoned: Target 1 card on the field; banish that target, and if you do, inflict 1000 damage to your opponent if it was a DARK monster.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37520316,3,0,0,2,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (37520316, 'Mind Control', 'Take control of 1 monster your opponent controls until the End Phase. It cannot declare an attack or be Tributed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75500286,3,0,0,2,0,0,0,0,0,1044);
INSERT OR REPLACE INTO "texts" VALUES (75500286, 'Gold Sarcophagus', 'Banish 1 card from your Deck, face-up. During your second Standby Phase after this card''s activation, add that card to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29401950,3,0,8978508,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (29401950, 'Bottomless Trap Hole', 'When your opponent Summons a monster(s) with 1500 or more ATK: Destroy that monster(s) with 1500 or more ATK, and if you do, banish it instead of sending it to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63356631,3,0,0,4,0,0,0,0,0,40);
INSERT OR REPLACE INTO "texts" VALUES (63356631, 'Phoenix Wing Wind Blast', 'Discard 1 card to target 1 card your opponent controls; return that target to the top of the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20586572,3,0,0,33,1000,0,3,8192,1,2);
INSERT OR REPLACE INTO "texts" VALUES (20586572, 'Exploder Dragon', 'If this card is destroyed by battle and sent to the Graveyard: Destroy the monster that destroyed it. Neither player takes any battle damage from attacks involving this attacking card.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57774843,3,0,0,33,3000,2600,8,8192,16,262155);
INSERT OR REPLACE INTO "texts" VALUES (57774843, 'Judgment Dragon', 'Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by having 4 or more "Lightsworn" monsters with different names in your Graveyard, and cannot be Special Summoned by other ways. You can pay 1000 Life Points; destroy all other cards on the field. During each of your End Phases: Send the top 4 cards of your Deck to the Graveyard.', 'Special Summon', 'Destroy', '从卡组送4张卡去墓地', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92826944,3,0,0,33,1700,800,4,16,1,1310724);
INSERT OR REPLACE INTO "texts" VALUES (92826944, 'Mezuki', 'You can banish this card from your Graveyard, then target 1 Zombie-Type monster in your Graveyard; Special Summon that target.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33420078,3,0,0,4129,400,200,2,16,32,262148);
INSERT OR REPLACE INTO "texts" VALUES (33420078, 'Plaguespreader Zombie', 'You can return 1 card from your hand to the top of the Deck; Special Summon this card from your Graveyard. If you do, banish this card when it leaves the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71564252,3,0,0,33,1900,800,4,4096,16,10);
INSERT OR REPLACE INTO "texts" VALUES (71564252, 'Thunder King Rai-Oh', 'Neither player can add cards from their Deck to their hand except by drawing them. During either player''s turn, when your opponent would Special Summon a monster: You can send this face-up card to the Graveyard; negate the Special Summon and destroy it.', '特殊召唤无效并破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44508094,3,0,163,8225,2500,2000,8,8192,8,-2147221501);
INSERT OR REPLACE INTO "texts" VALUES (44508094, 'Stardust Dragon', '1 Tuner + 1 or more non-Tuner monsters
When a Spell, Trap, Spell/Trap effect, or Effect Monster''s effect is activated that destroys a card(s) on the field: You can Tribute this card; negate the activation and destroy it. During the End Phase, if this card negated an effect this way during this turn: You can Special Summon this card from your Graveyard.', 'Negate and destroy card', 'Special Summon from your Graveyard during the End Phase', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69031175,3,0,51,8225,2500,1500,7,512,32,83894272);
INSERT OR REPLACE INTO "texts" VALUES (69031175, 'Blackwing Armor Master', '1 "Blackwing" Tuner + 1 or more non-Tuner monsters
This card cannot be destroyed by battle, and you take no Battle Damage from battles involving this card. If this card attacks a monster, you can place 1 Wedge Counter on that monster at the end of the Damage Step (max. 1). You can remove all Wedge Counters from your opponent''s monsters to reduce the ATK and DEF of each monster that had a Wedge Counter to 0, until the End Phase.', 'Place counter', '攻守变化', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76913983,3,0,51,8225,2300,1000,6,512,32,24576);
INSERT OR REPLACE INTO "texts" VALUES (76913983, 'Blackwing Armed Wing', '1 "Blackwing" Tuner + 1 or more non-Tuner monsters
 If this card attacks a Defense Position monster, it gains 500 ATK during the Damage Step only. During battle between this attacking card and a Defense Position monster whose DEF is lower then the ATK of this card, inflict the difference as Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5318639,3,0,0,65538,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (5318639, 'Mystical Space Typhoon', 'Target 1 Spell/Trap Card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53567095,3,0,0,4,0,0,0,0,0,1048587);
INSERT OR REPLACE INTO "texts" VALUES (53567095, 'Icarus Attack', 'Tribute 1 Winged Beast-Type monster to select 2 cards on the field. Destroy them.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33508719,3,0,0,2097185,700,600,2,256,1,264);
INSERT OR REPLACE INTO "texts" VALUES (33508719, 'Morphing Jar', 'FLIP: Both players discard all the cards in their hands, then draw 5 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24317029,3,0,46,2097185,1200,2000,4,2,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (24317029, 'Gravekeeper''s Spy', 'FLIP: Special Summon 1 "Gravekeeper''s" monster with 1500 or less ATK from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23205979,3,0,0,33,300,200,3,16,32,16777282);
INSERT OR REPLACE INTO "texts" VALUES (23205979, 'Spirit Reaper', 'Cannot be destroyed by battle. After resolving a card effect that targets this face-up card, destroy this card. When this card inflicts battle damage to your opponent by a direct attack: Discard 1 random card from their hand.', 'Discard hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9596126,3,0,0,33,2300,2000,6,2,32,1310724);
INSERT OR REPLACE INTO "texts" VALUES (9596126, 'Chaos Sorcerer', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your Graveyard. Once per turn: You can target 1 face-up monster on the field; banish that target. This card cannot attack the turn you activate this effect.', 'Special Summon', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72989439,3,0,4979,33,3000,2500,8,1,16,2457604);
INSERT OR REPLACE INTO "texts" VALUES (72989439, 'Black Luster Soldier - Envoy of the Beginning', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your Graveyard. Once per turn, you can activate 1 of these effects.
● Target 1 monster on the field; banish that target face-up. This card cannot attack the turn you activate this effect.
● During the Damage Step, if this attacking card destroys an opponent''s monster by battle: It can make a second attack in a row.', 'Special Summon', 'Banish', 'Attack again', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21502796,3,0,56,2097185,200,100,2,16384,16,131);
INSERT OR REPLACE INTO "texts" VALUES (21502796, 'Ryko, Lightsworn Hunter', 'FLIP: Apply these effects in sequence.
● You can target 1 card on the field; destroy that target.
● Send the top 3 cards of your Deck to the Graveyard.', 'Destroy', 'Destroy a card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94381039,3,0,56,33,2300,200,5,4,16,11);
INSERT OR REPLACE INTO "texts" VALUES (94381039, 'Celestia, Lightsworn Angel', 'When you Tribute Summon this card by Tributing a "Lightsworn" monster: You can send the top 4 cards of your Deck to the Graveyard, then target up to 2 cards your opponent controls; destroy those targets.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11819616,3,0,0,33,2800,2600,8,1024,8,-2146435069);
INSERT OR REPLACE INTO "texts" VALUES (11819616, 'Tytannial, Princess of Camellias', 'You can Tribute 1 face-up Plant-Type monster you control to negate the activation of a card or effect that targets a card(s) on the field and destroy it.', '效果无效并破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (423585,3,0,0,33,800,1600,4,2,32,264704);
INSERT OR REPLACE INTO "texts" VALUES (423585, 'Summoner Monk', 'Cannot be Tributed. When this card is Normal or Flip Summoned: Change this card to Defense Position. Once per turn: You can discard 1 Spell Card; Special Summon 1 Level 4 monster from your Deck, but that monster cannot attack this turn.', 'Change to defense position', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59616123,3,0,0,4,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (59616123, 'Trap Stun', 'Negate the effects of all other Trap Cards on the field during this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
