BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (69380702,3,0,0,17,150,2050,1,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (69380702, 'Bunilla', 'This rabbit''s got a sweet tooth! He''s on a quest for the world''s sweetest carrot, and just wants to nibble carrots all day today, tomorrow, and the day after that!', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95788410,3,0,0,17,2950,2900,8,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (95788410, 'Rabidragon', 'It''s a snowfield-dwelling, giant-ear-sporting, super-acoustic, snowball-shaped mutant dragon! There''s no way anybody can escape.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31173519,3,0,0,33,1200,1400,3,4096,16,65536);
INSERT OR REPLACE INTO "texts" VALUES (31173519, 'Rai Rider', 'If this card battles an opponent''s monster: That monster cannot attack while it is face-up on the field.', 'Cannot attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68167124,3,0,0,33,300,600,1,1,8,16);
INSERT OR REPLACE INTO "texts" VALUES (68167124, 'Stinging Swordsman', 'When this card inflicts Battle Damage to your opponent: Return all face-up cards in your opponent''s Spell & Trap Card Zones to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94656263,3,0,0,33,1100,1500,4,524288,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (94656263, 'Kagetokage', 'Cannot be Normal Summoned/Set. When you Normal Summon a Level 4 monster: You can Special Summon this card from your hand. This card cannot be used as a Synchro Material Monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21051977,3,0,0,33,200,400,1,1024,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (21051977, 'Acorno', 'During your Main Phase: You can send 1 "Pinecono" from your hand to the Graveyard, and Special Summon this card from the hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67445676,3,0,0,33,400,200,1,1024,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (67445676, 'Pinecono', 'If this card is sent to the Graveyard by the effect of "Acorno": You can Special Summon this card from the Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93830681,3,0,0,33,700,1500,3,131072,2,1056768);
INSERT OR REPLACE INTO "texts" VALUES (93830681, 'Friller Rabca', 'When a face-up Fish, Sea Serpent, or Aqua-Type monster you control is targeted for an attack: You can banish this card from your Graveyard to target the attacking monster; negate the attack, and if you do, that target loses 500 ATK until your next End Phase. You can only use the effect of "Friller Rabca" once per turn.', 'Negate attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20838380,3,0,0,33,200,1000,3,131072,2,1310720);
INSERT OR REPLACE INTO "texts" VALUES (20838380, 'Shark Stickers', 'When a Fish, Sea Serpent, or Aqua-Type monster is Normal or Special Summoned to your side of the field: You can Special Summon this card from your hand. This card cannot be used as a Synchro Material Monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56223084,3,0,0,33,1500,100,3,131072,2,270336);
INSERT OR REPLACE INTO "texts" VALUES (56223084, 'Needle Sunfish', 'When this card is sent to the Graveyard: Target 1 face-up monster your opponent controls; that target loses 500 ATK.', 'Lower attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93717133,3,0,276496469,33,3000,2500,8,8192,16,1073750020);
INSERT OR REPLACE INTO "texts" VALUES (93717133, 'Galaxy-Eyes Photon Dragon', 'You can Special Summon this card (from your hand) by Tributing 2 monsters with 2000 or more ATK. During either player''s Battle Step, when this card battles an opponent''s monster: You can target the monster this card is battling; banish both it and this card. At the end of the Battle Phase, return any monsters banished by this effect to the field, and if the other monster was an Xyz Monster, this card gains 500 ATK for each Xyz Material it had when it was banished.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29116732,3,0,0,33,1700,0,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (29116732, 'Daybreaker', 'When this card is Special Summoned: You can Special Summon 1 "Daybreaker" from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55501446,3,0,0,33,1200,800,3,524288,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (55501446, 'Lightserpent', 'If this card is sent from the hand to your Graveyard: You can Special Summon it from the Graveyard. This card cannot be used as a Synchro Material Monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92595545,3,0,0,33,900,900,3,4096,16,131074);
INSERT OR REPLACE INTO "texts" VALUES (92595545, 'Plasma Ball', 'This card can attack your opponent directly. When this card inflicts Battle Damage to your opponent by a direct attack: Destroy this card.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28990150,3,0,85,33,1300,600,3,16384,16,0);
INSERT OR REPLACE INTO "texts" VALUES (28990150, 'Photon Cerberus', 'During the turn this card was Normal Summoned, neither player can activate Trap Cards while this card is face-up on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55488859,3,0,12366,33,200,400,1,524288,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (55488859, 'Evoltile Gephyro', 'When this card is destroyed by battle and sent to the Graveyard: You can target 1 "Evolsaur" monster in your Graveyard; Special Summon that target.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81873903,3,0,12366,2097185,700,1900,3,524288,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (81873903, 'Evoltile Westlo', 'FLIP: Special Summon 1 "Evolsaur" monster from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28877602,3,0,12366,33,500,1200,2,524288,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (28877602, 'Evoltile Odonto', 'When this card is Normal Summoned: You can Special Summon 1 "Evolsaur" monster from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54266211,3,0,24654,33,1200,1000,4,65536,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (54266211, 'Evolsaur Vulcano', 'When this card is Special Summoned by the effect of an "Evoltile" monster: You can target 1 "Evolsaur" monster in your Graveyard; Special Summon that target. It cannot declare an attack.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80651316,3,0,24654,33,1900,1400,4,65536,4,8704);
INSERT OR REPLACE INTO "texts" VALUES (80651316, 'Evolsaur Cerato', 'When this card is Special Summoned by the effect of an "Evoltile" monster: It gains 200 ATK. If this card was Special Summoned by the effect of an "Evoltile" monster, each time this card destroys an opponent''s monster by battle: You can add 1 "Evoltile" monster from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17045014,3,0,24654,33,1600,800,4,65536,4,3);
INSERT OR REPLACE INTO "texts" VALUES (17045014, 'Evolsaur Diplo', 'When this card is Special Summoned by the effect of an "Evoltile" monster: Target 1 Spell/Trap Card your opponent controls; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53540729,3,0,88,33,1200,1800,4,1,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (53540729, 'Wind-Up Warrior', 'You can target 1 face-up "Wind-Up" monster you control; until the End Phase, increase its Level by 1 and its ATK by 600. This effect can only be used once while this card is face-up on the field.', 'Increase Level and ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80538728,3,0,88,33,1800,1200,4,1,16,65536);
INSERT OR REPLACE INTO "texts" VALUES (80538728, 'Wind-Up Knight', 'When a face-up "Wind-Up" monster you control is targeted for an attack: You can negate the attack. This effect can only be used once while this card is face-up on the field.', 'Negate attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16923472,3,0,88,33,1600,500,3,32768,32,64);
INSERT OR REPLACE INTO "texts" VALUES (16923472, 'Wind-Up Hunter', 'You can Tribute 1 face-up "Wind-Up" monster, except "Wind-Up Hunter"; send 1 random card from your opponent''s hand to the Graveyard. This effect can only be used once while this card is face-up on the field.', 'Hand destruction', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42328171,3,0,88,33,300,350,1,32,8,2560);
INSERT OR REPLACE INTO "texts" VALUES (42328171, 'Wind-Up Bat', 'You can target 1 "Wind-Up" monster in your Graveyard; change this face-up Attack Position card you control to face-up Defense Position, and add that target to your hand. This effect can only be used once while this card is face-up on the field.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25716180,3,0,88,33,800,500,2,16384,1,16);
INSERT OR REPLACE INTO "texts" VALUES (25716180, 'Wind-Up Kitten', 'You can target 1 monster your opponent controls; return that target to the hand. This effect can only be used once while this card is face-up on the field.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51701885,3,0,0,33,500,1800,2,1048576,1,262148);
INSERT OR REPLACE INTO "texts" VALUES (51701885, 'D.D. Telepon', 'If this face-up card you control is banished: You can banish 1 Psychic-Type monster with 1500 or less ATK from your Deck. Then, during your next Standby Phase, if this card is still banished: Special Summon that monster banished by this effect.', 'Banish', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88205593,3,0,14,33,1000,500,4,4096,16,131584);
INSERT OR REPLACE INTO "texts" VALUES (88205593, 'Wattcobra', 'This card can attack your opponent directly. When this card inflicts Battle Damage to your opponent by a direct attack: Add 1 "Watt" monster from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24694698,3,0,42,33,1200,700,3,1024,1,1288);
INSERT OR REPLACE INTO "texts" VALUES (24694698, 'Naturia Marron', 'When this card is Normal Summoned: You can send 1 "Naturia" monster from your Deck to the Graveyard. Once per turn: You can target 2 "Naturia" monsters in your Graveyard; shuffle both those targets into the Deck, then draw 1 card.', 'Send to Graveyard', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50088247,3,0,47,33,1000,400,2,64,2,262152);
INSERT OR REPLACE INTO "texts" VALUES (50088247, 'Prior of the Ice Barrier', 'If you control a face-up "Ice Barrier" monster, you can Special Summon this card (from your hand). You cannot Special Summon any Level 5 or higher monsters the turn you use this effect. You can Tribute this card to target 1 "Ice Barrier" monster in your Graveyard, except "Prior of the Ice Barrier"; Special Summon that target.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87483942,3,0,43,33,2300,2200,6,1,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (87483942, 'Senior Silver Ninja', 'When this card is flipped face-up: You can Special Summon any number of "Ninja" monsters, except "Senior Silver Ninja", from your hand and/or Graveyard in face-down Defense Position. There can only be 1 face-up "Senior Silver Ninja" on the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13478040,3,0,0,33,100,100,1,16384,1,67108866);
INSERT OR REPLACE INTO "texts" VALUES (13478040, 'Rodenut', 'Each time your opponent Special Summons a monster(s), place 1 Nut Counter on this card. You can remove 1 Nut Counter from this card to target 1 monster your opponent controls; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50866755,3,0,0,545,2100,1800,6,512,4,17);
INSERT OR REPLACE INTO "texts" VALUES (50866755, 'Fenghuang', 'Cannot be Special Summoned. During the End Phase of the turn this card is Normal Summoned or flipped face-up: Return it to the hand. When this card is Normal Summoned or flipped face-up: Destroy all Set Spell/Trap Cards your opponent controls.', 'Spirit', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86361354,3,0,0,33,1700,1000,4,4096,2,1048578);
INSERT OR REPLACE INTO "texts" VALUES (86361354, 'Tribe-Shocking Virus', 'Once per turn: You can banish 1 monster from your hand; destroy all face-up monsters on the field with the same Type as that monster.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12755462,3,0,172,33,1500,400,4,1,1,33554432);
INSERT OR REPLACE INTO "texts" VALUES (12755462, 'Goblin Pothole Squad', 'When this card is Normal Summoned, Trap Cards cannot be activated. Also, "Trap Hole" Trap Cards cannot be activated when a monster is Summoned, except "Dark Trap Hole".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49144107,3,0,0,2097185,1000,1900,3,16384,1,4194304);
INSERT OR REPLACE INTO "texts" VALUES (49144107, 'Creepy Coney', 'FLIP: Inflict 1000 damage to your opponent for each face-up Normal Monster you control, except Tokens.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85138716,3,0,0,33,300,100,4,16384,1,262148);
INSERT OR REPLACE INTO "texts" VALUES (85138716, 'Rescue Rabbit', 'This card cannot be Special Summoned from the Deck. You can banish this face-up card you control; Special Summon 2 Level 4 or lower Normal Monsters with the same name from your Deck. Destroy them during the End Phase. The effect of "Rescue Rabbit" can only be activated once per turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46083380,3,0,0,131074,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (46083380, 'Attraffic Control', 'If your opponent controls 3 or more monsters, they cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73178098,3,0,0,65538,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (73178098, 'Ego Boost', 'When a monster declares an attack: Target 1 face-up monster on the field; it gains 1000 ATK until the end of the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9576193,3,0,0,2,0,0,0,0,0,262404);
INSERT OR REPLACE INTO "texts" VALUES (9576193, 'Monster Slots', 'Target 1 face-up monster you control and 1 monster in your Graveyard with the same Level; banish the target from the Graveyard, then draw 1 card and reveal it, then if the card you drew is a monster with the same Level as the monster on the field, Special Summon it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46961802,3,0,0,2,0,0,0,0,0,196608);
INSERT OR REPLACE INTO "texts" VALUES (46961802, 'Cross Attack', 'Target 2 face-up Attack Position monsters you control with the same ATK; this turn, one of the them can attack your opponent directly and the other cannot attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72355441,3,0,115,2,0,0,0,0,0,1073742080);
INSERT OR REPLACE INTO "texts" VALUES (72355441, 'Xyz Gift', 'If you control 2 or more face-up Xyz Monsters: Detach 2 Xyz Materials from a monster you control and draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9354555,3,0,85,2,0,0,0,0,0,2097696);
INSERT OR REPLACE INTO "texts" VALUES (9354555, 'Photon Veil', 'Shuffle 3 LIGHT monsters from your hand into the Deck, then add 1 to 3 Level 4 or lower LIGHT monsters from your Deck to the hand. If you add 2 or more monsters, they must have the same name.', 'Add more cards to hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35848254,3,0,85,65538,0,0,0,0,0,2359296);
INSERT OR REPLACE INTO "texts" VALUES (35848254, 'Photon Lead', 'Special Summon 1 Level 4 or lower LIGHT monster from your hand in face-up Attack Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71233859,3,0,85,2,0,0,0,0,0,2105344);
INSERT OR REPLACE INTO "texts" VALUES (71233859, 'Photon Booster', 'Target 1 face-up Level 4 or lower LIGHT monster on the field, except a Token; all face-up monsters on the field with its name become 2000 ATK until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8632967,3,0,0,131074,0,0,0,0,0,33554432);
INSERT OR REPLACE INTO "texts" VALUES (8632967, 'Evo-Karma', 'When a monster(s) is Special Summoned by the effect of an "Evoltile" monster you control, your opponent cannot activate cards or effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34026662,3,0,0,65538,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (34026662, 'Evo-Miracle', 'Target 1 monster that was Special Summoned by the effect of an "Evoltile" monster; this turn, it cannot be destroyed by battle or by card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61011311,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (61011311, 'Zenmailfunction', 'Target 1 "Wind-Up" monster in your Graveyard; Special Summon it in face-up Defense Position. Its effect(s) is negated, and it cannot be Tributed or used as a Synchro Material Monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7405310,3,0,0,65538,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (7405310, 'Extra Gate', 'Declare a Level between 1 and 12; your opponent banishes 1 monster of that Level from their Extra Deck. If your opponent does not have a monster of that Level in their Extra Deck, you discard 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33904024,3,0,0,131074,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (33904024, 'Shard of Greed', 'Each time you draw a card(s) for your normal draw in your Draw Phase, place 1 Greed Counter on this card. You can send this card with 2 or more Greed Counters to the Graveyard; draw 2 cards.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60398723,3,0,0,2,0,0,0,0,0,2080);
INSERT OR REPLACE INTO "texts" VALUES (60398723, 'Murmur of the Forest', 'Target 1 face-up monster your opponent controls; change that target to face-down Defense Position, then you can return a Field Spell Card(s) on the field to the hand.', 'Return Field Spell Card to hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96383838,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (96383838, 'Tri-Wight', 'Target 3 Level 2 or lower Normal Monsters in your Graveyard; Special Summon them from the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33782437,3,0,0,2,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (33782437, 'One Day of Peace', 'Each player draws 1 card, and neither player takes damage until the end of the opponent''s next turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69176131,3,0,0,65538,0,0,0,0,0,1073743872);
INSERT OR REPLACE INTO "texts" VALUES (69176131, 'Space Cyclone', 'Detach 1 Xyz Material from a monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95561280,3,0,0,131074,0,0,0,0,0,1075849216);
INSERT OR REPLACE INTO "texts" VALUES (95561280, 'Poisonous Winds', 'WIND monsters cannot be Special Summoned. All face-up WIND monsters on the field lose 500 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32065885,3,0,0,4,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (32065885, 'Heartfelt Appeal', 'When you take battle damage from your opponent''s direct attack: Take control of the 1 face-up monster your opponent controls with the highest DEF, until your next End Phase. (If it''s a tie, you get to choose.) Its effects are negated, also it cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68054593,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (68054593, 'Fiery Fervor', 'Target 1 face-up monster you control; equip this card to that target. If your opponent controls a monster with ATK higher than that same monster''s original ATK, the ATK of the equipped monster becomes double the equipped monster''s original ATK, during the Damage Step only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95448692,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (95448692, 'Damage Diet', 'Halve all damage you take this turn. You can banish this card from your Graveyard; halve all effect damage you take this turn. (You cannot halve the same damage twice with this effect.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21843307,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (21843307, 'Copy Knight', 'When a Level 4 or lower Warrior-Type monster is Normal Summoned to your side of the field: Special Summon this card as a Normal Monster Card with the same name and Level as the Normal Summoned monster (Warrior-Type/LIGHT/ATK 0/DEF 0). (This card is still treated as a Trap Card.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12533811,3,0,0,8388641,900,900,1,8192,1,131072);
INSERT OR REPLACE INTO "texts" VALUES (12533811, 'Baby Tiragon', '3 Level 1 monsters
During your Main Phase 1: You can detach 1 Xyz Material from this card, then target 1 Level 1 monster you control; it can attack your opponent directly.', 'Direct attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48928529,3,0,8061000,8388641,500,500,1,2,32,1090535424);
INSERT OR REPLACE INTO "texts" VALUES (48928529, 'Number 83: Galaxy Queen', '3 Level 1 monsters
Once per turn: You can detach 1 Xyz Material from this card; until your opponent''s next End Phase, the monsters you currently control cannot be destroyed by battle, and if they attack a Defense Position monster, inflict piercing Battle Damage to your opponent.', '附加能力', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74416224,3,0,0,8388641,2100,600,3,32768,32,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (74416224, 'Black Ray Lancer', '2 Level 3 WATER monsters
Once per turn: You can detach 1 Xyz Material from this card to target 1 face-up monster on the field; negate that target''s effects, until the End Phase.', 'Negate effect', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11411223,3,0,72,8388641,2400,2400,4,1,16,256);
INSERT OR REPLACE INTO "texts" VALUES (11411223, 'Number 10: Illumiknight', '3 Level 4 monsters
Once per turn: You can detach 1 Xyz Material from this card; send 1 card from your hand to the Graveyard, and if you do, draw 1 card.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47805931,3,0,72,8388641,1800,1800,3,2048,16,1073750016);
INSERT OR REPLACE INTO "texts" VALUES (47805931, 'Number 20: Giga-Brilliant', '2 Level 3 monsters
Once per turn: You can detach 1 Xyz Material from this card; all face-up monsters you currently control gain 300 ATK.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74294676,3,0,1347289166,8388641,2400,2000,4,8192,4,-2147483645);
INSERT OR REPLACE INTO "texts" VALUES (74294676, 'Evolzar Laggia', '2 Level 4 Dinosaur-Type monsters
When a monster(s) would be Normal or Special Summoned, OR a Spell/Trap Card is activated: You can detach 2 Xyz Materials from this card; negate the Summon or activation, and destroy that card.', 'Negate and destroy Spell/Trap Card', 'Negate and destroy summon', 'Negate and destroy special summon', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (698785,3,0,0,8388641,3000,2000,8,8192,16,2);
INSERT OR REPLACE INTO "texts" VALUES (698785, 'Thunder End Dragon', '2 Level 8 Normal Monsters
Once per turn: You can detach 1 Xyz Material from this card; destroy all other monsters on the field.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67232306,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (67232306, 'Mirror Mail', 'When a face-up monster you control is targeted for an attack: Its ATK becomes equal to that of the attacking monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94626050,3,0,0,4,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (94626050, 'Fish Rain', 'When a face-up Fish, Sea Serpent, or Aqua-Type monster on the field is banished: Special Summon 1 Level 3 or lower Fish, Sea Serpent, or Aqua-Type monster from your hand. (The banished monster(s) must be Fish, Sea Serpent, or Aqua-Type even after being banished.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20721759,3,0,0,4,0,0,0,0,0,4194312);
INSERT OR REPLACE INTO "texts" VALUES (20721759, 'Icy Crevasse', 'When exactly 1 monster you control is destroyed and sent to the Graveyard by an opponent''s card effect: Target 1 monster your opponent controls; send that target to the Graveyard, and if you do, inflict damage to your opponent equal to its original ATK in the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57115864,3,0,0,4,0,0,0,0,0,2105344);
INSERT OR REPLACE INTO "texts" VALUES (57115864, 'Lumenize', 'When an opponent''s monster declares an attack: Target the attacking monster; negate the attack, and 1 face-up LIGHT monster you control gains ATK equal to that target''s ATK, until your next End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93504463,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (93504463, 'Evolutionary Bridge', 'When a monster you control is targeted for an attack: Target 1 "Evoltile" monster in your Graveyard; Special Summon that target, then switch the attack target to that monster and conduct damage calculation.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29999161,3,0,0,4,0,0,0,0,0,262160);
INSERT OR REPLACE INTO "texts" VALUES (29999161, 'Zenmairch', 'Target 1 face-up Level 4 or lower "Wind-Up" monster you control: Return that target to the hand (no matter its Level), then Special Summon 1 "Wind-Up" monster from the hand with the same Level as the returned monster''s.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56993276,3,0,14,1048580,0,0,0,0,0,10);
INSERT OR REPLACE INTO "texts" VALUES (56993276, 'Wattcancel', 'When your opponent would Normal or Special Summon a monster: Discard 1 "Watt" monster; negate the Summon and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82382815,3,0,0,1048580,0,0,0,0,0,-2147483645);
INSERT OR REPLACE INTO "texts" VALUES (82382815, 'Champion''s Vigilance', 'If you control a face-up Level 7 or higher Normal Monster, when a monster would be Summoned OR a Spell/Trap Card is activated: Negate the Summon or activation, and destroy that card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29876529,3,0,0,4,0,0,0,0,0,2097154);
INSERT OR REPLACE INTO "texts" VALUES (29876529, 'Darklight', 'Tribute 1 DARK monster with 1500 or more ATK; destroy all monsters that were Special Summoned this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55271628,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (55271628, 'Tyrant''s Throes', 'Activate by Tributing 2 Normal Monsters you control (except Tokens). Neither player can Normal or Special Summon Effect Monsters.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54059040,3,0,0,131076,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (54059040, 'Eisbahn', 'When a monster with an Attribute other than WATER is Normal or Special Summoned (including face-down Summons), and you control a face-up WATER monster: That Summoned monster is changed to Defense Position.', 'Change to defense position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28654932,3,0,8978508,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (28654932, 'Deep Dark Trap Hole', 'When a Level 5 or higher Effect Monster(s) is Special Summoned: Banish that Level 5 or higher Effect Monster(s).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81443745,3,0,0,131076,0,0,0,0,0,2097156);
INSERT OR REPLACE INTO "texts" VALUES (81443745, 'Sealing Ceremony of Suiton', 'Once per turn: You can send 1 WATER monster from your hand to the Graveyard to target 1 card in your opponent''s Graveyard; banish that target.', 'Banish', 'Activate effect of "Sealing Ceremony of Suiton"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81665333,3,0,0,4,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (81665333, 'Sound the Retreat!', 'Return all monsters you control to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80495985,3,0,85,33,2000,300,3,16384,16,8704);
INSERT OR REPLACE INTO "texts" VALUES (80495985, 'Photon Sabre Tiger', 'When this card is Normal or Flip Summoned: You can add 1 "Photon Sabre Tiger" from your Deck to your hand. If you do not control another "Photon Sabre Tiger", this card loses 800 ATK.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16480084,3,0,24654,33,1100,2000,4,65536,4,8704);
INSERT OR REPLACE INTO "texts" VALUES (16480084, 'Evolsaur Pelta', 'When this card is Special Summoned by the effect of an "Evoltile" monster: It gains 500 DEF. If this card was Special Summoned by the effect of an "Evoltile" monster, then is destroyed by battle: You can add 1 "Evoltile" monster from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42874792,3,0,88,33,1400,600,3,32768,1,4);
INSERT OR REPLACE INTO "texts" VALUES (42874792, 'Wind-Up Rabbit', 'During either player''s turn: You can target 1 "Wind-Up" monster you control; banish it until your next Standby Phase. This effect can be used only once while this card is face-up on the field.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79279397,3,0,0,2097185,100,1000,1,8,32,4456448);
INSERT OR REPLACE INTO "texts" VALUES (79279397, 'D-Boyz', 'FLIP: You can Special Summon any number of "D-Boyz" from your Deck in face-up Attack Position, then you take 1000 damage for each monster Special Summoned by this effect.', 'Special Summon', 'Do you want to Special Summon?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15667446,3,0,6,33,1500,2400,6,8,32,270336);
INSERT OR REPLACE INTO "texts" VALUES (15667446, 'Latinum, Exarch of Dark World', 'If this card is discarded to the Graveyard by a card effect: If it was discarded from your hand to your Graveyard by an opponent''s card effect, target 1 Fiend-Type monster on the field; Special Summon this card from the Graveyard, then that target (if any) gains 500 ATK.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4545854,3,0,115,524290,0,0,0,0,0,16785408);
INSERT OR REPLACE INTO "texts" VALUES (4545854, 'Xyz Territory', 'When an Xyz Monster battles another monster, that Xyz Monster gains 200 ATK & DEF × its Rank, during damage calculation only. If this face-up card on the field would be destroyed by a card effect, you can detach 1 Xyz Material from a monster you control instead.', 'Use the effect of "Xyz Territory" to avoid destruction?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41930553,3,0,0,131076,0,0,0,0,0,68);
INSERT OR REPLACE INTO "texts" VALUES (41930553, 'Dark Smog', 'Once per turn: You can target 1 monster in your opponent''s Graveyard; discard 1 Fiend-Type monster, and if you do, banish that target.', 'Activate effect of "Dark Smog"?', 'Discard and Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42752141,3,0,1347289166,8388641,2300,1700,4,8192,4,-2147483646);
INSERT OR REPLACE INTO "texts" VALUES (42752141, 'Evolzar Dolkka', '2 Level 4 Dinosaur-Type monsters
When an Effect Monster''s effect activates: You can detach 1 Xyz Material from this card; negate the activation and destroy it.', 'Negate and destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78156759,3,0,88,8388641,1500,2100,3,32,4,16777219);
INSERT OR REPLACE INTO "texts" VALUES (78156759, 'Wind-Up Zenmaines', '2 Level 3 monsters
If this face-up card on the field would be destroyed, you can detach 1 Xyz Material from this card instead. Once per turn, during the End Phase, if this effect was used this turn: Target 1 card on the field; destroy it.', 'Activate "Wind-Up Zenmaines" effect to avoid destruction?', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74530899,3,0,74,33,0,0,10,4,4,20971568);
INSERT OR REPLACE INTO "texts" VALUES (74530899, 'Metaion, the Timelord', 'Cannot be Special Summoned from the Deck. If you control no monsters, you can Normal Summon this card without Tributing. This card cannot be destroyed by battle or by card effects. You take no Battle Damage from battles involving this face-up Attack Position card. At the end of the Battle Phase, if this card attacked or was attacked: Return all other monsters on the field to the hand, and inflict 300 damage to your opponent for each card returned. During your Standby Phase: Shuffle this card into the Deck (even if face-down).', 'Normal Summon without Tributes', 'Return all other monsters on the field to the hand', '这张卡回到卡组', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (123709,3,0,57,33,2100,200,6,1,4,1032);
INSERT OR REPLACE INTO "texts" VALUES (123709, 'Laval Lancelord', 'You can Normal Summon this card without Tributing. If you do, during the End Phase: Send it to the Graveyard. When this card on the field is destroyed and sent to the Graveyard: You can target 1 of your banished FIRE monsters; add that target to your hand.', 'Normal Summon without Tributes', 'Send to Graveyard', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69243722,3,0,4167,33,1800,800,4,256,1,262148);
INSERT OR REPLACE INTO "texts" VALUES (69243722, 'Gem-Knight Emerald', 'You can banish this face-up card you control and 1 face-up Normal Monster you control to target 1 "Gem-Knight" Fusion Monster in your Graveyard; Special Summon it from the Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43359262,3,0,0,33,1600,1300,4,32,4,0);
INSERT OR REPLACE INTO "texts" VALUES (43359262, 'Sergeant Electro', 'Once per turn: You can target 1 face-down card in your opponent''s Spell & Trap Card Zone; while this card is face-up on the field, its target(s) cannot be activated.', 'Limit activation', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36227804,3,0,58,33,1500,1300,4,16384,2,0);
INSERT OR REPLACE INTO "texts" VALUES (36227804, 'Gishki Beast', 'When this card is Normal Summoned: You can target 1 Level 4 or lower "Gishki" monster in your Graveyard; Special Summon that target in face-up Defense Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5237827,3,0,48,33,1500,200,4,4,16,1028);
INSERT OR REPLACE INTO "texts" VALUES (5237827, 'Vylon Ohm', 'When this card is Normal Summoned: Target 1 Equip Spell Card in your Graveyard; banish that target. During your next Standby Phase, add it to your hand.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64734090,3,0,71,2097185,0,2000,4,256,1,512);
INSERT OR REPLACE INTO "texts" VALUES (64734090, 'Gem-Turtle', 'FLIP: You can add 1 "Gem-Knight Fusion" from your Deck to your hand.', 'Add to hand', 'Add 1 "Gem-Knight Fusion" to your hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71341529,3,0,11,33,1400,400,3,8,32,262152);
INSERT OR REPLACE INTO "texts" VALUES (71341529, 'Infernity Knight', 'When this card on the field is destroyed and sent to the Graveyard: You can discard 2 cards; Special Summon this card from your Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68120130,3,0,67,33,500,1800,3,1,1,270336);
INSERT OR REPLACE INTO "texts" VALUES (68120130, 'Junk Defender', 'When an opponent''s monster declares a direct attack: You can Special Summon this card from your hand. Once per turn, during either player''s turn: You can have this card gain 300 DEF until the end of this turn.', 'Special Summon', '守备上升', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31632536,3,0,57,8225,2400,200,5,1,4,49152);
INSERT OR REPLACE INTO "texts" VALUES (31632536, 'Laval Dual Slasher', '1 Tuner + 1 or more non-Tuner FIRE monsters
This card gains effects based on the number of "Laval" monsters in your Graveyard:
● 2+: Once per turn, if this card attacks a Defense Position monster, it can attack once again in a row.
● 3+: If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', 'Attack again?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
