BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (20292186,3,0,151,33,2200,900,5,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (20292186, 'Artifact Scythe', 'You can Set this card from your hand to your Spell & Trap Card Zone as a Spell Card. During your opponent''s turn, when this Set card in the Spell & Trap Card Zone is destroyed and sent to your Graveyard: Special Summon it. If this card is Special Summoned during your opponent''s turn: Your opponent cannot Special Summon monsters from the Extra Deck for the rest of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51865604,3,0,0,33,500,100,1,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (51865604, 'ZS - Vanish Sage', 'If you control a "Utopia" monster: You can draw 1 card. If a monster(s) you control is banished during the Battle Phase (except during the Damage Step): You can banish this card from the field, then target 1 of those banished monsters; Special Summon that target, and if you do, banish 1 monster your opponent controls that has 3000 or less ATK. You can only use 1 "ZS - Vanish Sage" effect per turn, and only once that turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98263709,3,0,123,2097185,0,800,3,2,16,0);
INSERT OR REPLACE INTO "texts" VALUES (98263709, 'Galaxy Mirror Sage', 'FLIP: You gain 500 Life Points for each "Galaxy" monster in your Graveyard.
When this card is destroyed and sent from the field to the Graveyard after being flipped face-up: You can Special Summon 1 Level 4 or lower "Galaxy" monster from your Deck or Graveyard in face-down Defense Position. Banish it when it leaves the field.', 'Special Summon 1 Level 4 or lower "Galaxy" monster from your Deck?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24658418,3,0,123,33,2000,0,8,65536,16,0);
INSERT OR REPLACE INTO "texts" VALUES (24658418, 'Galaxy Tyranno', 'When a "Galaxy" monster you control is targeted for an attack: You can Special Summon this card from your hand in face-up Defense Position. When Summoned this way, you can: Immediately after this effect resolves, Xyz Summon 1 "Galaxy" Xyz Monster using "Galaxy" monsters you control only.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51043053,3,0,0,33,0,1900,4,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (51043053, 'Heliosphere Dragon', 'While your opponent has 4 or less cards in their hand and this card is the only monster you control, your opponent cannot declare an attack. Once per turn, if you control a Level 8 Dragon-Type monster: You can make this card become Level 8 until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87047161,3,0,0,33,100,300,1,131072,2,0);
INSERT OR REPLACE INTO "texts" VALUES (87047161, 'Mermaid Shark', 'When this card is Normal Summoned: You can add 1 Level 3, 4 or 5 Fish-Type monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23536866,3,0,0,33,1000,1900,5,131072,2,0);
INSERT OR REPLACE INTO "texts" VALUES (23536866, 'Gazer Shark', 'You can banish this card from your Graveyard, then target 2 Level 5 WATER monsters in your Graveyard, except "Gazer Shark"; Special Summon both those monsters, but their effects are negated. Immediately after this effect resolves, Xyz Summon 1 WATER Xyz Monster using only those 2 monsters. You can only use this effect of "Gazer Shark" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50920465,3,0,0,33,1600,1400,4,512,2,0);
INSERT OR REPLACE INTO "texts" VALUES (50920465, 'Blizzard Thunderbird', 'You can discard 1 card; Special Summon 2 WATER Winged-Beast-Type monsters, 1 from your hand and 1 from your Graveyard, except "Blizzard Thunderbird", then return this card from the field to the hand. You can only use the effect of "Blizzard Thunderbird" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86325573,3,0,132,33,1100,1400,2,1,4,0);
INSERT OR REPLACE INTO "texts" VALUES (86325573, 'Battlin'' Boxer Big Bandage', 'Once per turn, this card cannot be destroyed by battle. Once per turn: You can target 1 "Battlin'' Boxer" monster in your Graveyard or 1 of your banished "Battlin'' Boxer" monsters that has a Level; the Levels of all "Battlin'' Boxer" monsters you currently control become the Level of that monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13313278,3,0,132,33,0,1800,4,1,4,0);
INSERT OR REPLACE INTO "texts" VALUES (13313278, 'Battlin'' Boxer Veil', 'When you take battle damage: You can Special Summon this card from your hand, and if you do, gain Life Points equal to the damage you took.', 'Special Summon this card from your hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59708927,3,0,135,33,200,200,2,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (59708927, 'Umbral Horror Ghost', 'During your Main Phase: You can Special Summon this card and 1 Level 4 or lower Fiend-Type monster from your hand. You cannot Normal Summon/Set during the turn you activate this effect. You can only use this effect of "Umbral Horror Ghost" once per turn.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85103922,3,0,151,33,2100,1400,5,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (85103922, 'Artifact Moralltach', 'You can Set this card from your hand to your Spell & Trap Card Zone as a Spell Card. During your opponent''s turn, when this Set card in the Spell & Trap Card Zone is destroyed and sent to your Graveyard: Special Summon it. If this card is Special Summoned during your opponent''s turn: You can destroy 1 face-up card your opponent controls.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12697630,3,0,151,33,1400,2100,5,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (12697630, 'Artifact Beagalltach', ' You can Set this card from your hand to your Spell & Trap Card Zone as a Spell Card. During your opponent''s turn, when this Set card in the Spell & Trap Card Zone is destroyed and sent to your Graveyard: Special Summon it. If this card is Special Summoned during your opponent''s turn: Destroy up to 2 Set cards you control (min. 1). You can only use this effect of "Artifact Beagalltach" once per turn.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48086335,3,0,151,33,2000,1600,5,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (48086335, 'Artifact Failnaught', 'You can Set this card from your hand to your Spell & Trap Card Zone as a Spell Card. During your opponent''s turn, when this Set card in the Spell & Trap Card Zone is destroyed and sent to your Graveyard: Special Summon it. If this card is Special Summoned during your opponent’s turn: You can target 1 "Artifact" monster in your Graveyard; Set that target to your Spell & Trap Card Zone as a Spell Card.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85080444,3,0,151,33,1200,2500,5,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (85080444, 'Artifact Aegis', 'You can Set this card from your hand to your Spell & Trap Card Zone as a Spell Card. During your opponent''s turn, when this Set card in the Spell & Trap Card Zone is destroyed and sent to your Graveyard: Special Summon it. If this card is Special Summoned during your opponent''s turn: "Artifact" monsters you control cannot be targeted or destroyed by your opponent''s card effects until the end of this turn.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11475049,3,0,151,33,1500,2200,5,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (11475049, 'Artifact Achilleshield', 'You can Set this card from your hand to your Spell & Trap Card Zone as a Spell Card. During your opponent''s turn, when this Set card in the Spell & Trap Card Zone is destroyed and sent to your Graveyard: Special Summon it. If this card is Special Summoned during your opponent''s turn: Your opponent cannot target "Artifact" monsters you control for attacks for the rest of this turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47863787,3,0,151,33,2300,1000,5,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (47863787, 'Artifact Labrys', 'You can Set this card from your hand to your Spell & Trap Card Zone as a Spell Card. When this Set card in your Spell & Trap Card Zone is destroyed and sent to the Graveyard during your opponent''s turn: Special Summon this card. When an "Artifact" card(s) is destroyed and sent to your Graveyard (except during the Damage Step): You can Special Summon this card from your hand.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84268896,3,0,151,33,1600,2400,5,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (84268896, 'Artifact Caduceus', 'You can Set this card from your hand to your Spell & Trap Card Zone as a Spell Card. During your opponent''s turn, when this Set card in the Spell & Trap Card Zone is destroyed and sent to your Graveyard: Special Summon it. During your opponent''s turn, each time an "Artifact" monster(s) is Special Summoned: Draw 1 card. You must control this face-up card to activate and to resolve this effect. You can only control 1 "Artifact Caduceus".', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10753491,3,0,10879120,33,100,100,1,1024,16,0);
INSERT OR REPLACE INTO "texts" VALUES (10753491, 'Sylvan Cherubsprout', 'When this card is Special Summoned: You can choose either 1 or 2, then excavate that many cards from the top of your Deck, send any excavated Plant-Type monsters to the Graveyard, also place the other cards on the bottom of your Deck in any order. If this card is excavated from the Deck and sent to the Graveyard by a card effect: You can Special Summon 1 Level 1 Plant-Type monster from your Deck. You can only use this effect of "Sylvan Cherubsprout" once per turn.', '1', '2', 'Special Summon 1 Level 1 Plant-Type monster from your Deck?', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47741109,3,0,144,33,900,400,1,1024,32,0);
INSERT OR REPLACE INTO "texts" VALUES (47741109, 'Sylvan Snapdrassinagon', 'If this card is sent from your hand or your side of the field to the Graveyard: You can excavate the top card of your Deck, and if it is a Plant-Type monster, send it to the Graveyard. Otherwise, place it on the bottom of your Deck. If this card is excavated from the Deck and sent to the Graveyard by a card effect: You can excavate the top card of your Deck, and if it is a Plant-Type monster, send it to the Graveyard. Otherwise, place it on the bottom of your Deck.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73136204,3,0,144,33,2300,1100,5,1024,2,0);
INSERT OR REPLACE INTO "texts" VALUES (73136204, 'Sylvan Lotuswain', 'Once per turn: You can excavate a number of cards from the top of your Deck, equal to the number of cards your opponent controls, send any excavated Plant-Type monsters to the Graveyard, also place the other cards on the bottom of your Deck in any order. If this card is excavated from the Deck and sent to the Graveyard by a card effect: You can target up to 5 "Sylvan" cards in your Graveyard, except "Sylvan Lotuswain"; place those targets on the bottom of your Deck in any order.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10530913,3,0,144,33,2600,2100,7,1024,8,0);
INSERT OR REPLACE INTO "texts" VALUES (10530913, 'Sylvan Sagequoia', 'When a "Sylvan" monster is sent to the Graveyard (except during the Damage Step): You can Special Summon this card from your hand. Once per turn: You can excavate the top card of your Deck, and if it is a Plant-Type monster, send it to the Graveyard. Otherwise, place it on the bottom of your Deck. If this card is excavated from the Deck and sent to the Graveyard by a card effect: You can target 1 "Sylvan" Spell/Trap Card in your Graveyard; add that target to your hand.', 'Activate effect?', 'Add 1 "Sylvan" Spell/Trap Card to hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46925518,3,0,141,33,300,1200,2,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (46925518, 'Ghostrick Doll', 'Cannot be Normal Summoned, unless you control a "Ghostrick" monster. Once per turn: You can change this card to face-down Defense Position. When this card is flipped face-up: During this turn''s End Phase, change all face-up monsters on the field to face-down Defense Position, then you can Special Summon 1 "Ghostrick" monster from your Deck in face-down Defense Position, whose Level is equal to or less than the total number of monsters changed to face-down Defense Position.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72913666,3,0,141,33,1400,1500,3,16,32,0);
INSERT OR REPLACE INTO "texts" VALUES (72913666, 'Ghostrick Werewolf', 'Cannot be Normal Summoned unless you control a "Ghostrick" monster. Once per turn: You can change this card to face-down Defense Position. When this card is flipped face-up: Inflict 100 damage to your opponent for each Set card on the field. You can only use this effect of "Ghostrick Werewolf" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9418365,3,0,136,33,2000,1000,4,32768,16,0);
INSERT OR REPLACE INTO "texts" VALUES (9418365, 'Bujin Hirume', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by banishing 1 "Bujin" monster from your Graveyard, except "Bujin Hirume". If this card, which was Summoned this way, is destroyed by your opponent''s card (by battle or by card effect), and sent from your side of the field to your Graveyard, and both players have a hand: You can discard 1 card, then your opponent discards 1 card. You can only control 1 "Bujin Hirume".', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45803070,3,0,4234,33,1700,1100,4,1024,1,0);
INSERT OR REPLACE INTO "texts" VALUES (45803070, 'Traptrix Dionaea', 'This card is unaffected by the effects of "Hole" Normal Trap Cards. When this card is Normal Summoned: You can target 1 "Traptrix" monster in your Graveyard; Special Summon that target in face-up Defense Position. When this card is Special Summoned: You can target 1 "Hole" Normal Trap Card in your Graveyard; Set that target. Banish it during the End Phase of your next turn. You can only use this effect of "Traptrix Dionaea" once per turn.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72291078,3,0,4123,4129,600,1000,2,32,8,0);
INSERT OR REPLACE INTO "texts" VALUES (72291078, 'Mecha Phantom Beast O-Lion', 'You can banish this card from your Graveyard; immediately after this effect resolves, Normal Summon 1 "Mecha Phantom Beast" monster from your hand. While you control a Token, this card cannot be destroyed by battle or card effects. If this card is sent to the Graveyard: You can Special Summon 1 "Mecha Phantom Beast Token" (Machine-Type/WIND/Level 3/ATK 0/DEF 0). You can only use this effect of "Mecha Phantom Beast O-Lion" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8696773,3,0,4221,33,2300,200,6,65536,4,0);
INSERT OR REPLACE INTO "texts" VALUES (8696773, 'Hazy Flame Hydra', 'Your opponent cannot target this card with card effects. You cannot Special Summon any monsters, except FIRE monsters. An Xyz Monster that was Summoned using this card as Xyz Material gains the following effect.
● When it is Xyz Summoned: You can target 1 "Hazy Flame" monster in your Graveyard; attach that target to this card as an Xyz Material.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34680482,3,0,113,33,1000,1000,4,4,1,0);
INSERT OR REPLACE INTO "texts" VALUES (34680482, 'Madolche Anjelly', 'When this card in your possession is destroyed by your opponent''s card (either by battle or by card effect) and sent to your Graveyard: Shuffle this card into the Deck. You can Tribute this card; Special Summon 1 "Madolche" monster from your Deck, but shuffle it into the Deck during the End Phase of your next turn. You can only use this effect of "Madolche Anjelly" once per turn. That Special Summoned monster cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71175527,3,0,16,33,1000,1500,3,1048576,8,0);
INSERT OR REPLACE INTO "texts" VALUES (71175527, 'Pilica, Descendant of Gusto', 'When this card is Normal or Special Summoned: You can target 1 WIND Tuner monster in your Graveyard; Special Summon that target in face-up Defense Position. Its effects are negated. If you activated this effect, you cannot Special Summon monsters for the rest of this turn, except WIND monsters. You can only use this effect of "Pilica, Descendant of Gusto" once per turn.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7573135,3,0,25,33,2600,1000,8,512,32,0);
INSERT OR REPLACE INTO "texts" VALUES (7573135, 'Gladiator Beast Augustus', 'When this card is Special Summoned by the effect of a "Gladiator Beast" monster: You can Special Summon 1 "Gladiator Beast" monster from your hand in face-up Defense Position. Shuffle it into the Deck during the End Phase. At the end of the Battle Phase, if this card attacked or was attacked: You can shuffle it into the Deck; Special Summon 1 "Gladiator Beast" monster from your Deck, except "Gladiator Beast Augustus".', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34968834,3,0,6,33,2400,0,6,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (34968834, 'Lucent, Netherlord of Dark World', 'If this card is discarded to the Graveyard by a card effect: Special Summon this card from the Graveyard, then, if it was discarded from your hand to your Graveyard by an opponent''s card effect, you can Special Summon 1 Fiend-Type monster from your Deck to either side of the field.', 'Activate Effect?', 'Special Summon?', 'Special Summon to your Side of the Field', 'Special Summon to your opponents side of the Field', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60953949,3,0,7,33,500,2000,4,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (60953949, 'Ancient Gear Box', 'If this card is added from the Deck or Graveyard to your hand, except by drawing it: You can add 1 EARTH Machine-Type monster with 500 ATK and/or DEF from your Deck to your hand, except "Ancient Gear Box". You can only use this effect of "Ancient Gear Box" once per turn.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6351548,3,0,0,33,1400,1200,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (6351548, 'Dawn Knight', 'If this card is sent from the field to the Graveyard: You can send 1 LIGHT monster from your Deck to the Graveyard. If this card is sent from your Deck to the Graveyard: Target 1 LIGHT monster in your Graveyard; place that target on the top of your Deck. You can only use 1 "Dawn Knight" effect per turn, and only once that turn.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33746252,3,0,0,33,2400,1000,6,8,16,0);
INSERT OR REPLACE INTO "texts" VALUES (33746252, 'Majesty''s Fiend', 'Cannot be Special Summoned. Monster effects cannot be activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69230391,3,0,190,33,2800,1000,8,128,4,0);
INSERT OR REPLACE INTO "texts" VALUES (69230391, 'Thestalos the Mega Monarch', 'You can Tribute Summon this card by Tributing 1 Tribute Summoned monster. When this card is Tribute Summoned: Look at your opponent''s hand and discard 1 card from their hand, then, if it was a Monster Card, inflict damage to your opponent equal to its original Level x 200. If this card was Tributed Summoned by Tributing a FIRE monster, add this additional effect.
● Also, inflict 1000 damage to your opponent after that.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6625096,3,0,0,33,0,0,1,131072,2,0);
INSERT OR REPLACE INTO "texts" VALUES (6625096, 'Beautunaful Princess', 'When this card is Normal or Special Summoned: You can banish this card; Special Summon 1 Level 4 or lower Fish-Type monster from your Deck, except "Beautunaful Princess". You can only use this effect of "Beautunaful Princess" once per turn.', 'banish this card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32623004,3,0,90,33,1600,100,3,64,2,0);
INSERT OR REPLACE INTO "texts" VALUES (32623004, 'Nopenguin', 'During either player''s turn, when an effect of a "Penguin" monster is activated: Special Summon this card from your Graveyard. You can only use the effect of "Nopenguin" once per turn. If a card would be returned from the field to the hand by the effect of a "Penguin" card, banish it instead.', 'Special Summon this card from your Graveyard?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68018709,3,0,0,33,100,2000,4,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (68018709, 'Condemned Maiden', 'During your opponent''s turn, you can activate 1 Quick-Play Spell Card from your hand. You can only use this effect of "Condemned Maiden" once per Duel.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95403418,3,0,128,33,-2,-2,1,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (95403418, 'Starduston', 'Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by sending any number of "Duston" monsters you control to the Graveyard (min. 1), and cannot be Special Summoned by other ways. This card’s ATK and DEF are equal to the number of "Duston" monsters sent for its Special Summon x 1000. Your opponent cannot activate Set Spell/Trap Cards, also they cannot Flip or Special Summon monsters. If you control more monsters than your opponent does, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31801517,3,0,18120472592456,8388641,4000,3000,8,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (31801517, 'Number 62: Galaxy-Eyes Prime Photon Dragon', '2 Level 8 monsters
If this card attacks or is attacked, during damage calculation (in either player''s turn): You can detach 1 Xyz Material from this card once per battle; this card gains ATK equal to the combined Ranks of all Xyz Monsters currently on the field x 200, during that damage calculation only. If this card in its owner''s control is destroyed by your opponent''s card effect while it has "Galaxy-Eyes Photon Dragon" as an Xyz Material: You can Special Summon this card during your 2nd Standby Phase after activation and double its ATK. Any battle damage this card inflicts to your opponent is halved unless it has "Galaxy-Eyes Photon Dragon" as an Xyz Material.', 'Activate Effect?', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68396121,3,0,18121280393288,8388641,4500,3000,9,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (68396121, 'Number C107: Neo Galaxy-Eyes Tachyon Dragon', '3 Level 9 monsters
Once per turn: You can detach 1 Xyz Material from this card; until the end of this turn, negate the effects of all other face-up cards currently on the field, also your opponent cannot activate cards or effects on the field. If this card has "Number 107: Galaxy-Eyes Tachyon Dragon" as an Xyz Material, it gains this effect.
● You can Tribute 2 monsters; this card can make up to 3 attacks on monsters during each Battle Phase this turn.', 'Negate effect', 'Attack three times', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94380860,3,0,72,8388641,2400,1200,4,4,2,0);
INSERT OR REPLACE INTO "texts" VALUES (94380860, 'Number 103: Ragnazero', '2 Level 4 monsters
Once per turn, during either player''s turn: You can detach 1 Xyz Material from this card, then target 1 face-up Attack Position monster your opponent controls, whose current ATK is different from its original ATK; destroy it, and if you do, draw 1 card.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20785975,3,0,4722760,8388641,2800,2400,5,4,2,0);
INSERT OR REPLACE INTO "texts" VALUES (20785975, 'Number C103: Ragnafinity', '3 Level 5 monsters
Once per turn, during either player''s turn: You can detach 1 Xyz Material from this card, then target 1 face-up monster your opponent controls; inflict damage to your opponent equal to the difference between that monster''s original ATK and current ATK, and if you do, banish it. When this card is destroyed and sent to the Graveyard while it has Xyz Material: You can Special Summon this card from your Graveyard. "Number 103: Ragnazero" must be in your Graveyard to activate and to resolve this effect.', 'Activate effect?', 'Special Summon this card from your Graveyard?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67173574,3,0,296357466184,8388641,2900,2400,5,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (67173574, 'Number C102: Archfiend Seraph', '4 Level 5 LIGHT monsters
If this face-up card would be destroyed, you can detach 2 Xyz Materials from this card instead. When the last Xyz Material(s) is detached from this card: Inflict 1500 damage to your opponent. If this card has "Number 102: Star Seraph Sentry" as an Xyz Material, it gains this effect.
● Once per turn: You can detach 1 Xyz Material from this card, then target 1 face-up monster your opponent controls; change that target''s ATK to 0, and if you do, negate its effects.', 'Avoid destruction?', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93568288,3,0,72,8388641,0,1200,4,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (93568288, 'Number 80: Rhapsody in Berserk', '2 Level 4 monsters
You can target 1 face-up Xyz Monster you control; equip this monster you control to that target. It gains 1200 ATK. You can detach 1 Xyz Material from this card, then target 1 card in your opponent''s Graveyard; banish that target. You can use this effect of "Number 80: Rhapsody in Berserk" up to twice per turn.', 'Attach to monster?', 'Banish a card from opponent''s graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20563387,3,0,4722760,8388641,0,2000,5,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (20563387, 'Number C80: Requiem in Berserk', '3 Level 5 monsters
You can target 1 face-up Xyz Monster you control; equip this monster you control to that target. It gains 2000 ATK. If a monster equipped with this card would be destroyed, destroy this card instead. If this card has "Number 80: Rhapsody in Berserk" as an Xyz Material, it gains this effect.
● You can detach 1 Xyz Material from this card, then target 1 card on the field; banish that target.', 'Equip this monster?', 'Banish a card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56051086,3,0,72,8388641,0,0,2,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (56051086, 'Number 43: Manipulator of Souls', '3 Level 2 DARK monsters
Once per turn: You can detach 1 Xyz Material from this card, then target 1 "Number" monster in your Graveyard; equip that target to this card. While equipped with a "Number" monster, this card cannot be destroyed by battle or by card effects. Once per turn, when you gain Life Points: You can have this card gain ATK equal to the amount of Life Points you gained, also inflict that much damage to your opponent.', 'Gain LP?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32446630,3,0,273154120,8388641,0,0,3,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (32446630, 'Number C43: High Manipulator of Chaos', '4 Level 3 DARK monsters
All Tokens you control can make a second attack during each Battle Phase. If this card has "Number 43: Manipulator of Souls" as an Xyz Material, it gains this effect.
● Once per turn: You can detach 1 Xyz Material from this card; Special Summon 1 "Manipulator Token" (Fiend-Type/DARK/Level 1/ATK ?/DEF ?). (When Summoned, its ATK and DEF each become equal to half your opponent''s current Life Points.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69840739,3,0,151,8388641,2400,2100,5,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (69840739, 'Artifact Durendal', '2 Level 5 monsters
Once per turn, during either player''s turn, you can activate 1 of these effects.
● When a monster effect is activated on the field, OR when a Normal Spell/Trap Card is activated: You can detach 1 Xyz Material from this card; the activated effect becomes "Destroy 1 Spell/Trap Card your opponent controls".
● You can detach 1 Xyz Material from this card; each player with a hand shuffles their entire hand into the Deck, then each player draws the same number of cards they shuffled into the Deck.', 'When a monster effect activates on the field, OR when a Normal Spell/Trap Card is activated: You can detach 1 Xyz Material from this card; that card''s effect becomes "Destroy 1 Spell/Trap Card your opponent controls."', 'You can detach 1 Xyz Material from this card; both players shuffle their entire hands into the Decks, then each player draws the same number of cards they shuffled.', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95239444,3,0,144,8388641,2800,2500,7,1024,32,0);
INSERT OR REPLACE INTO "texts" VALUES (95239444, 'Orea, the Sylvan High Arbiter', '2 Level 7 monsters
Once per turn: You can send 1 Plant-Type monster from your hand or face-up from your side of the field to the Graveyard; look at a number of cards from the top of your Deck, equal to the Level of the sent monster had in the hand or on the field, then place them on the top of the Deck in any order. Once per turn: You can detach 1 Xyz Material from this card; choose a number from 1 to 3, then excavate that many cards from the top of your Deck, send any excavated Plant-Type monsters to the Graveyard, and if you do, return up to that many cards from the field to the hand (min. 1), except this card. Also, place the other cards on the bottom of your Deck in any order.', 'Select Order', 'Select Order', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32224143,3,0,141,8388641,1400,1200,2,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (32224143, 'Ghostrick Socuteboss', '2 Level 2 monsters
While you control another "Ghostrick" monster, your opponent cannot target this card for attacks. Once per turn: You can detach 1 Xyz Material from this card, then target 1 face-up monster on the field, with ATK less than or equal to the combined ATK of all "Ghostrick" monsters on the field; destroy it, and if you do, that Monster Card Zone cannot be used as long as you control a "Ghostrick" monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68618157,3,0,136,8388641,2600,2500,4,32768,16,0);
INSERT OR REPLACE INTO "texts" VALUES (68618157, 'Bujinki Amaterasu', '3 Level 4 monsters
You can only control 1 "Bujinki Amaterasu". Once per turn, during either player''s turn: You can detach 1 Xyz Material from this card; apply this effects, depending on whose turn it is.
● Your turn: Target 1 of your banished Level 4 or lower monsters; Special Summon that target.
● Your opponent''s turn: Target 1 of your banished Level 4 or lower monsters; add that target to your hand.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95113856,3,0,0,8388641,2900,2500,9,32,8,0);
INSERT OR REPLACE INTO "texts" VALUES (95113856, 'Phantom Fortress Enterblathnir', '2 Level 9 monsters
Once per turn: You can detach 1 Xyz Material from this card, then activate 1 of these effects;
● Banish 1 card your opponent controls.
● Banish 1 random card from your opponent''s hand.
● Banish 1 card from your opponent''s Graveyard.
● Banish the top card of your opponent''s Deck, face-up.', 'Once per turn: You can detach 1 Xyz Material from this card, then activate 1 of these effects.', 'Banish 1 card your opponent controls.', 'Banish 1 random card from your opponent''s hand.', 'Banish 1 card from your opponent''s Graveyard.', 'Banish the top card of your opponent''s Deck, face-up.', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21501505,3,0,0,8388641,2450,1950,4,256,32,0);
INSERT OR REPLACE INTO "texts" VALUES (21501505, 'Cairngorgon, Antiluminescent Knight', '2 Level 4 monsters
During either player’s turn, when another card or effect is activated that targets exactly 1 card on the field (and no other cards): You can detach 1 Xyz Material from this card, then target another card on the field that would be an appropriate target for that card/effect; that card/effect now targets the new target.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67556500,3,0,0,12321,1900,800,4,8192,32,0);
INSERT OR REPLACE INTO "texts" VALUES (67556500, 'Phonon Pulse Dragon', '1 Tuner + 1 or more non-Tuner monsters
When this card is Synchro Summoned: You can declare a Level from 1 to 3; the Level of this card becomes that Level, but you cannot Special Summon for the rest of this turn, except for a Synchro Summon using this card as a Synchro Material Monster. You can only Special Summon "Phonon Pulse Dragon" once per turn.', 'Declare level?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94950218,3,0,0,262146,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (94950218, 'Reverse Breaker', 'Equip only to a "Utopia" monster. When the equipped monster declares an attack: Target 1 Spell/Trap Card your opponent controls; destroy that target. Your opponent cannot activate Spell/Trap Cards in response to this effect''s activation.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20349913,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (20349913, 'Galactic Charity', 'If you control a "Galaxy" Xyz Monster: Discard 1 card; draw 2 cards, also if you activate this card, any damage your opponent takes for the rest of this turn is halved. You can only activate 1 "Galactic Charity" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57734012,3,0,149,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (57734012, 'Rank-Up-Magic - The Seventh One', 'To activate this card, you must draw it for your normal draw in your Draw Phase, reveal it, and keep it revealed until the start of Main Phase 1. At the start of your Main Phase 1 that same turn, you can Special Summon, from your Extra Deck or Graveyard, 1 monster that has a number between "Number 101" and "Number 107" in its name, except "Number C" monsters. Then Xyz Summon, from your Extra Deck, 1 "Number C" monster with the same number in its name as the first monster, by using it as the Xyz Material. You can only apply the effect of "Rank-Up-Magic - The Seventh One" once per Duel.', 'Reveal "Rank-Up-Magic The Seventh One"?', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93238626,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (93238626, 'Don Thousand''s Throne', 'During each of your opponent''s End Phases: Gain Life Points equal to the number of times you took battle damage this turn x 500. When a "Number" monster you control is targeted for an attack, except "Number C" monsters: You can send this card to the Graveyard; negate the attack, then Special Summon from your Extra Deck, 1 "Number C" monster with the same number in its name as that "Number" monster you control, by using it as the Xyz Material. (This Special Summon is treated as an Xyz Summon. Xyz Materials attached to it also become Xyz Materials on the Summoned monster.) You can only control 1 "Don Thousand''s Throne".', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29223325,3,0,151,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (29223325, 'Artifact Ignition', 'Target 1 Spell/Trap Card on the field; destroy that target, and if you do, Set 1 "Artifact" monster directly from your Deck to your Spell & Trap Card Zone as a Spell Card. If this card in its owner''s possession is destroyed by an opponent''s card: Your opponent skips their next Battle Phase. (You must have an "Artifact" monster in your Main Deck to activate this card.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56611470,3,0,151,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (56611470, 'Artifacts Unleashed', 'Target 2 "Artifact" monsters you control; immediately after this effect resolves, Xyz Summon 1 Xyz Monster using those 2 monsters only, but if you activated this card, monsters you control cannot attack for the rest of this turn, except "Artifact" monsters. If this card in it''s owners possession is destroyed by an opponent''s card: You can reveal 1 Level 5 LIGHT monster in your hand; draw 1 card.', 'Reveal 1 Level 5 LIGHT monster in your hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82016179,3,0,144,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (82016179, 'Sylvan Charity', 'Draw 3 cards, then, if you have a "Sylvan" card in your hand, reveal 2 cards from your hand including at least 1 "Sylvan" card, then place them on the top of the Deck in any order. Otherwise, reveal your entire hand, then place it on the top of the Deck in any order. You can only activate 1 "Sylvan Charity" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29400787,3,0,141,524290,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (29400787, 'Ghostrick Parade', 'Monsters cannot attack face-down Defense Position monsters, but can attack directly if all monsters their opponent controls are face-down Defense Position. Your opponent takes no damage. When an opponent''s monster declares a direct attack: You can add 1 "Ghostrick" card from your Deck to your hand.', 'Add 1 "Ghostrick" card from your Deck to your hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55599882,3,0,136,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (55599882, 'Bujintervention', 'Target 1 "Bujin" monster on the field; apply this effect to it for the rest of this turn. Each time it destroys a monster by battle whose current ATK is greater than or equal to the targeted monster''s original ATK, and sends it to the Graveyard: Banish the destroyed monster, and if you do, banish all monsters from your opponent''s hand, Main Deck, Extra Deck, and Graveyard with the same name that the destroyed monster had in the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81994591,3,0,29,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (81994591, 'Diamond Core of Koa''ki Meiru', 'Add 1 "Koa''ki Meiru" card from your Deck to your hand, except "Diamond Core of Koa''ki Meiru". You can banish this card from your Graveyard; this turn, "Koa''ki Meiru" monsters you control cannot be destroyed.', '', 'Add Koaki Meiru', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28388296,3,0,36,524290,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (28388296, 'Scrap Factory', 'All "Scrap" monsters gain 200 ATK and DEF. When a face-up "Scrap" monster(s) on the field is destroyed by a card effect and sent to the Graveyard (except during the Damage Step): You can Special Summon 1 "Scrap" monster from your Deck. You can only use this effect of "Scrap Factory" once per turn.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54773234,3,0,0,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (54773234, 'Forbidden Scripture', 'If a monster battles an opponent''s monster, during damage calculation: Negate all other card effects on the field until the end of the Damage Step, also damage calculation for this battle uses each monster''s original ATK and DEF.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81171949,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (81171949, 'Jackpot 7', 'When this card is activated: Shuffle this card from the field into the Deck. When this card in your possession is sent to the Graveyard by an opponent''s card effect: Banish this card. If 3 of your "Jackpot 7" are currently banished, and were all banished by this effect, you win the Duel.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13166648,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (13166648, 'Double Dragon Descent', 'When an opponent''s Xyz Monster declares a direct attack: Special Summon 1 LIGHT Dragon-Type Xyz Monster from your Extra Deck in face-up Attack Position, then the attacking monster attacks it instead, and you proceed to damage calculation. Its ATK becomes equal to the attacking monster''s ATK, also its effects are negated. You can only activate 1 "Double Dragon Descent" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59650656,3,0,137,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (59650656, 'Tachyon Chaos Hole', 'When a face-up "Galaxy" Xyz Monster you control is destroyed by battle with your opponent''s attacking monster or by your opponent''s card effect and sent to your Graveyard: Destroy as many face-up cards your opponent controls as possible, and if you do, banish them. During your Draw Phase, if this card is in your Graveyard, instead of conducting your normal draw: You can banish this card, then target 1 "Galaxy" Xyz Monster in your Graveyard; Special Summon that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86049351,3,0,0,1048580,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (86049351, 'Last Counter', 'When an attack is declared involving a "Battlin'' Boxer" monster you control and an opponent''s monster, if you control another "Battlin'' Boxer" monster: Negate the attack, and if you do, send your battling monster to the Graveyard, then 1 "Battlin'' Boxer" monster you control gains ATK equal to your opponent''s battling monster''s original ATK, and if it does, proceed to damage calculation between that monster and your opponent''s battling monster. Then, take damage equal to the ATK gained by this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12444060,3,0,151,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (12444060, 'Artifact Sanctum', 'Special Summon 1 "Artifact" monster from your Deck. You can only activate 1 "Artifact Sanctum" per turn. You cannot conduct your Battle Phase the turn you activate this card. If this card in its owner''s possession is destroyed by an opponent''s card: You can target 1 card on the field; destroy that target.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49838105,3,0,144,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (49838105, 'Sylvan Waterslide', 'When an opponent''s monster declares a direct attack: You can excavate the top card of your Deck, and if it is a Plant-Type monster, send it to the Graveyard. Otherwise, place it on the bottom of your Deck. During your Draw Phase, instead of conducting your normal draw: Excavate the top card of your Deck, and if it is a Plant-Type monster, send it to the Graveyard. Otherwise, add it to your hand.', 'Excavate the top card of your Deck?', 'Conduct Normale Draw Phase?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85827713,3,0,141,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (85827713, 'Ghostrick Night', 'While a "Ghostrick" monster is face-up on the field, your opponent cannot Flip Summon monsters. When this card in your possession is destroyed by your opponent''s card and sent to the Graveyard: Your opponent cannot declare an attack this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11221418,3,0,136,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (11221418, 'Bujincident', 'Target 1 "Bujin" Xyz Monster you control; banish it, and if you do, return all monsters on the field to the hand. Until your 2nd End Phase after activation, neither player can Summon monsters, nor take damage (but can Normal Set). During your 2nd End Phase after activation: Target 1 "Bujin" monster in your Graveyard ; Special Summon the monster banished by this effect, and if you do, attach that target to it as an Xyz Material.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48716527,3,0,190,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (48716527, 'The Monarchs Erupt', 'Activate this card only if you have no cards in your Extra Deck and control a Tribute Summoned monster. Negate the effects of all face-up monsters on the field, except Tribute Summoned monsters. During your End Phase, if you control no Tribute Summoned monsters, send this card to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74100225,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (74100225, 'Evo-Singularity', 'Target 1 "Evoltile" monster and 1 "Evolsaur" monster in your Graveyard; Special Summon 1 "Evolzar" Xyz Monster from your Extra Deck, and if you do, attach those monsters to it as Xyz Materials.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11109820,3,0,115,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (11109820, 'Xyz Universe', 'Target 2 face-up Xyz Monsters on the field; send both monsters to the Graveyard, then Special Summon 1 Xyz Monster from your Extra Deck, except a "Number" monster, whose Rank is equal to, or 1 less than, the combined original Ranks of those 2 Xyz Monsters, and if you do, attach this card to it as an Xyz Material. If you activate this card, your opponent takes no further damage this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47594939,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (47594939, 'And the Band Played On', 'Neither player can Special Summon monsters with the same Level as those they control. Neither player can Special Summon monsters with the same Rank as those they control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73988674,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (73988674, 'Tri-and-Guess', 'If each player has an Extra Deck: Declare 1 Extra Deck monster card type (Fusion, Synchro, or Xyz); both players reveal their Extra Deck, and the player who has more monsters of the declared card type gains 3000 Life Points.', 'Fusion', 'Synchro', 'Xyz', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57690191,3,0,4218,33,1200,2400,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (57690191, 'Noble Knight Brothers', 'This card can only attack while you control exactly 3 "Noble Knight" monsters (and no other monsters). When this card is Normal Summoned: You can Special Summon up to 2 "Noble Knight" monsters from your hand, but cannot Special Summon monsters for the rest of this turn, except "Noble Knight" monsters. Once per turn: You can target 3 "Noble Knight" and/or "Noble Arms" cards in your Graveyard; shuffle all 3 into the Deck, then draw 1 card.', 'Special Summon up to 2 "Noble Knight" monsters?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93085839,3,0,4218,33,1600,2000,5,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (93085839, 'Noble Knight Eachtar', 'You can banish 2 "Noble Knight" monsters from your Graveyard; Special Summon this card from your hand or Graveyard. You can only use this effect of "Noble Knight Eachtar" once per turn. A Synchro or Xyz Summon of a "Noble Knight" monster using this card as a Material cannot be negated, also your opponent cannot activate cards or effects when that monster is Special Summoned.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20579538,3,0,10879120,33,100,100,1,1024,16,0);
INSERT OR REPLACE INTO "texts" VALUES (20579538, 'Sylvan Princessprout', 'You can only activate each effect of "Sylvan Princessprout" once per turn.
● You can Tribute this card; excavate the top card of your Deck, send it to the Graveyard, then you can place 1 "sprout" monster in your Graveyard on top of your Deck.
● If this card is excavated from the Deck and sent to the Graveyard by a card effect: You can declare a Level from 1 to 8; Special Summon this card from the Graveyard, and if you do, it becomes that Level.', 'You can Tribute this card; excavate the top card of your Deck, send it to the Graveyard, then you can place 1 "sprout" monster in your Graveyard on top of your Deck.', 'If this card is excavated from the Deck and sent to the Graveyard by a card effect: You can declare a Level from 1 to 8; Special Summon this card from the Graveyard, and if you do, it becomes that Level.', 'Place a card on top?', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56574543,3,0,136,33,1500,1000,4,16384,16,0);
INSERT OR REPLACE INTO "texts" VALUES (56574543, 'Bujingi Sinyou', 'During either player''s Damage Step, if a Beast-Warrior-Type "Bujin" monster you control battles an opponent''s monster: You can banish this card from your Graveyard; that monster you control gains ATK equal to the current ATK of the opponent''s monster it is battling until the end of the Damage Step, and if it does, all battle damage your opponent takes from that battle is halved. You can only use the effect of "Bujingi Sinyou" once per turn.', ' Banish this card from your Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82962242,3,0,142,33,2000,2000,7,16,32,0);
INSERT OR REPLACE INTO "texts" VALUES (82962242, 'Vampire Vamp', 'Once per turn, when this card or a "Vampire" monster is Normal Summoned to your side of the field: You can target 1 face-up monster your opponent controls, whose ATK is higher than this card''s; equip it to this card. This card gains ATK equal to the combined original ATK of the monsters equipped to it by this effect. When this card is sent to the Graveyard, while equipped with a card by this effect: Special Summon this card from the Graveyard.', 'Equip an opponent''s monster?', 'Equip an opponent''s monster? ', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29357956,3,0,25,97,2800,1900,8,512,32,0);
INSERT OR REPLACE INTO "texts" VALUES (29357956, 'Gladiator Beast Nerokius', '3 "Gladiator Beast" monsters
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization".) Cannot be destroyed by battle. If this card attacks or is attacked, your opponent cannot activate cards or effects until the end of the Damage Step. At the end of the Battle Phase, if this card attacked or was attacked: You can shuffle it into the Extra Deck; Special Summon 2 "Gladiator Beast" monsters from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55742055,3,0,4218,524290,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (55742055, 'Noble Knights of the Round Table', 'During your End Phase: You can activate each of these effects up to once per turn, depending on the total number of "Noble Knight" cards with different names in your Graveyard and/or you control.
● 3 or more: Send 1 "Noble Knight" card from your Deck to the Graveyard.
● 6 or more: Special Summon 1 "Noble Knight" monster from your hand, then you can equip 1 "Noble Arms" Equip Spell Card from your hand to that monster.
● 9 or more: Target 1 "Noble Knight" monster in your Graveyard; add that target to your hand.
● 12: Draw 1 card.', 'Send 1 "Noble Knight" card from your Deck to the Graveyard.', 'Special Summon 1 "Noble Knight" monster from your hand, then you can equip 1 "Noble Arms" Equip Spell Card from your hand to that monster.', 'Target 1 "Noble Knight" monster in your Graveyard; add that target to your hand.', 'Draw 1 card.', 'Equip 1 "Noble Arms" Equip Spell Card from your hand', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82140600,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (82140600, 'Avalon', 'Target 5 "Noble Knight" monsters in your Graveyard, including at least 1 "Artorigus" monster and 1 "Laundsallyn" monster; banish those targets, and if you do, destroy all cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18235309,3,0,190,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (18235309, 'Escalation of the Monarchs', 'Once per turn, during your opponent''s Main Phase or your opponent''s Battle Phase, you can: Immediately after this effect resolves, Tribute Summon 1 monster.', 'Tribute Summon 1 monster', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48531733,3,0,90,17,1100,800,3,4096,2,0);
INSERT OR REPLACE INTO "texts" VALUES (48531733, 'Bolt Penguin', 'With each arm forming an electric whip, this monster paralyzes its enemies with electric shocks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6901008,3,0,0,4129,1500,300,3,8,32,536870920);
INSERT OR REPLACE INTO "texts" VALUES (6901008, 'Phantom King Hydride', ' If you use this card you control for a Synchro Summon, you can treat it as a non-Tuner monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10389142,3,0,8061000,8388641,0,3000,7,32,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (10389142, 'Number 42: Galaxy Tomahawk', '2 Level 7 monsters
You can detach 2 Xyz Materials from this card; Special Summon as many "Battle Eagle Tokens" (Machine-Type/WIND/Level 6/ATK 2000/DEF 0) as possible, but destroy them during the End Phase of this turn, also your opponent takes no further battle damage this turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51852507,3,0,0,33,1000,100,3,1,1,-2130706432);
INSERT OR REPLACE INTO "texts" VALUES (51852507, 'Rose Archer', 'During either player''s turn, when your opponent''s activates a Trap Card while you control a Plant-Type monster: You can send this card from your hand to the Graveyard; negate the activation, and if you do, destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41493640,3,0,0,33,800,400,3,32768,1,262145);
INSERT OR REPLACE INTO "texts" VALUES (41493640, 'Shogi Knight', 'When this card is Normal Summoned: You can target 1 Set card in your opponent''s Spell & Trap Card Zone; reveal that target, then destroy it if it is a Trap Card. Otherwise return it to its original position. When you destroy a Trap Card by this effect: You can Special Summon 1 Level 3 EARTH monster from your hand in face-up Defense Position.', 'Special Summon?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76543119,3,0,131,33,1200,2000,4,32,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (76543119, 'Gimmick Puppet Des Troy', 'You can target 1 "Gimmick Puppet" monster on the field; destroy it. This effect can only be used once while this card is face-up on the field. When this card is sent from the field to the Graveyard: You can Special Summon 1 or 2 "Gimmick Puppet" monsters from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2648201,3,0,126,33,1000,1000,4,16384,16,0);
INSERT OR REPLACE INTO "texts" VALUES (2648201, 'ZW - Sleipnir Mail', 'You can target 1 "Utopia" monster you control; equip this monster from your hand or your side of the field to that target. It gains 1000 ATK. When this card you control is sent to your Graveyard because the equipped monster was destroyed by your opponent''s card (either by battle or card effect): You can target 1 "Utopia" monster in your Graveyard; Special Summon that target. You can only control 1 "ZW - Sleipnir Mail".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1426714,3,0,72,8388641,1800,0,3,16,32,0);
INSERT OR REPLACE INTO "texts" VALUES (1426714, 'Number 48: Shadow Lich', '2 Level 3 monsters
Once per turn, during your opponent''s turn: You can detach 1 Xyz Material from this card; Special Summon 1 "Phantom Token" (DARK/Fiend-Type/Level 1/ATK 500/DEF 500). (This is a Quick Effect.) While you control a "Phantom Token", your opponent cannot target this card for attacks. This card gains 500 ATK for each "Phantom Token" you control.', 'Special Summon 1 "Phantom Token"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9024367,3,0,123,33,2000,1200,4,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (9024367, 'Galaxy Dragon', 'This card can only attack Dragon-Type monsters. If this card battles a Dragon-Type monster, this card gains 1000 ATK during the Damage Step only, also negate that monster''s effects during each Battle Phase, as long as this card remains face-up on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36029076,3,0,0,33,2600,1300,7,2048,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (36029076, 'Hundred-Footed Horror', 'If your opponent controls a monster and you control no monsters, you can Normal Summon this card without Tributing, but its original ATK becomes 1300.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
