BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (98299011,3,0,0,4,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (98299011, 'Gift of the Mystical Elf', 'Increase your Life Points by 300 points for each monster on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98139712,3,0,0,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (98139712, 'Skull Invitation', 'Each time a card(s) is sent to the Graveyard, inflict 300 damage to its owner for each card sent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97687912,3,0,0,262146,0,0,0,0,0,16384);
INSERT OR REPLACE INTO "texts" VALUES (97687912, 'Fairy Meteor Crush', 'If the equipped monster attacks a Defense Position monster, inflict piercing battle damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97077563,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (97077563, 'Call of the Haunted', 'Activate this card by targeting 1 monster in your Graveyard; Special Summon that target in Attack Position. When this card leaves the field, destroy that target. When that target is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96965364,3,0,0,2,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (96965364, 'Insect Imitation', 'Tribute 1 monster. Special Summon 1 Insect-Type monster from your Deck whose Level is 1 higher than the Tributed monster''s.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96355986,3,0,0,4,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (96355986, 'Enchanted Javelin', 'Increase your Life Points by the ATK of 1 attacking monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93108433,3,0,0,65538,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (93108433, 'Monster Recovery', 'Unite 1 of your own monsters on your side of the field and your hand with your Deck and then shuffle it. Draw the same number of cards that were in your hand from the Deck. (You cannot activate this card if you have your opponent''s card in your hand.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90502999,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (90502999, 'Ground Collapse', 'Select 2 Monster Card Zones on the field. Neither player can use the selected zones. You cannot select a zone that is occupied by a Monster Card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88733579,3,0,0,33,1100,200,2,2048,1,512);
INSERT OR REPLACE INTO "texts" VALUES (88733579, 'Drill Bug', 'When this card inflicts Battle Damage to your opponent''s Life Points, you can select 1 "Parasite Paracide" card from your Deck, shuffle the Deck, and place "Parasite Paracide" on top of the Deck.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87511987,3,0,0,17,1800,1700,5,32,32,0);
INSERT OR REPLACE INTO "texts" VALUES (87511987, 'Spikebot', 'A mechanical soldier created by a wicked sorcerer, it attacks with the two steel balls attached to its arms.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86198326,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (86198326, '7 Completed', 'A Machine-Type monster equipped with this card gains either 700 ATK or DEF. You cannot change your choice while this card remains face-up on the field.', 'Gain 700 ATK', 'Gain 700 DEF', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84620194,3,0,0,17,1700,1000,4,2048,8,0);
INSERT OR REPLACE INTO "texts" VALUES (84620194, 'Girochin Kuwagata', 'Despite its small size, this monster has powerful jaws that can rip metal to shreds.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83994646,3,0,0,2097185,800,1200,3,2048,8,2);
INSERT OR REPLACE INTO "texts" VALUES (83994646, '4-Starred Ladybug of Doom', 'FLIP: Destroy all Level 4 monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81210420,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (81210420, 'Magical Hats', 'Activate only during your opponent''s Battle Phase. Select 2 non-Monster Cards from your Deck and 1 monster you control. Shuffle those 3 cards and Set them on the field in face-down Defense Position. The 2 cards selected from your Deck are treated as monsters (ATK 0/DEF 0) and are destroyed at the end of the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79870141,3,0,0,33,1400,1200,4,65536,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (79870141, 'Mad Sword Beast', ' If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78984772,3,0,0,17,2200,1700,6,128,4,0);
INSERT OR REPLACE INTO "texts" VALUES (78984772, 'Twin-Headed Fire Dragon', 'Two dragons fused as one from the effects of the Big Bang.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78658564,3,0,172,33,2300,0,4,1,1,2048);
INSERT OR REPLACE INTO "texts" VALUES (78658564, 'Goblin Attack Force', 'If this card attacks, it is changed to Defense Position at the end of the Battle Phase, and its battle position cannot be changed until the End Phase of your next turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78423643,3,0,0,17,1200,1400,4,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (78423643, 'Three-Headed Geedo', 'A three-headed nocturnal monster that is absolutely ruthless when fighting.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78193832,3,78193831,0,33,2600,2300,7,1,1,1056768);
INSERT OR REPLACE INTO "texts" VALUES (78193832, 'Buster Blader', 'This card gains 500 ATK for each Dragon-Type monster your opponent has on the field or in their Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78193831,3,0,0,33,2600,2300,7,1,1,1056768);
INSERT OR REPLACE INTO "texts" VALUES (78193831, 'Buster Blader', 'This card gains 500 ATK for each Dragon-Type monster your opponent controls or is in their Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77585514,3,77585513,188,33,2400,1500,6,32,32,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (77585514, 'Jinzo', 'Trap Cards cannot be activated. The effects of all face-up Trap Cards are negated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77585513,3,0,188,33,2400,1500,6,32,32,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (77585513, 'Jinzo', 'Trap Cards, and their effects on the field, cannot be activated. Negate all Trap Card effects on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75646520,3,0,0,4,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (75646520, 'Metal Detector', 'You can only activate this card when a Continuous Trap Card is activated. Negate all Continuous Trap Cards during the turn this card is activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74923978,3,0,0,131076,0,0,0,0,0,64);
INSERT OR REPLACE INTO "texts" VALUES (74923978, 'Forced Requisition', 'You can activate this card when you discard from your hand. After that, each time you discard from your hand, your opponent must also discard the same number of cards from his/her hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74701381,3,0,0,131076,0,0,0,0,0,1048576);
INSERT OR REPLACE INTO "texts" VALUES (74701381, 'DNA Surgery', 'When you activate this card, declare 1 Type of monster. As long as this card remains face-up on the field, all face-up monsters become the Type you declared.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73079365,3,0,0,4,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (73079365, 'Gust', 'You can activate this card when 1 or more of your Spell Cards are destroyed and sent from the field to the Graveyard by a card effect your opponent controls. Destroy 1 Spell or Trap Card on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71044499,3,0,0,2,0,0,0,0,0,6);
INSERT OR REPLACE INTO "texts" VALUES (71044499, 'Nobleman of Crossout', 'Target 1 face-down monster on the field; destroy that target, and if you do, banish it, then, if it was a Flip monster, each player reveals their Main Deck, then banishes all cards from it with that monster''s name.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70828912,3,0,0,262146,0,0,0,0,0,262146);
INSERT OR REPLACE INTO "texts" VALUES (70828912, 'Premature Burial', 'Activate this card by paying 800 LP, then target 1 monster in your Graveyard; Special Summon that target in face-up Attack Position and equip it with this card. When this card is destroyed, destroy the equipped monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67532912,3,0,0,17,800,800,3,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (67532912, 'Science Soldier', 'Soldiers equipped with state-of-the-art weaponry to face unknown creatures.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67049542,3,0,0,17,1000,1000,3,512,8,0);
INSERT OR REPLACE INTO "texts" VALUES (67049542, 'Dark Bat', 'Bats from the netherworld that use their hyper senses to detect their enemies.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66927994,3,0,0,17,1400,1700,4,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (66927994, 'Oni Tank T-34', 'An armored tank possessed by a fiend that will pursue enemies until they''re crushed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66719324,3,0,0,2,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (66719324, 'Rain of Mercy', 'Increases the Life Points of both players by 1000 points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66362965,3,0,147,33,2200,1200,6,1,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (66362965, 'The Fiend Megacyber', 'If your opponent controls at least 2 more monsters than you do, you can Special Summon this card (from your hand).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63689843,3,0,0,4,0,0,0,0,0,4194560);
INSERT OR REPLACE INTO "texts" VALUES (63689843, 'Attack and Receive', 'You can only activate this card when you take damage to your Life Points. Inflict 700 points of damage to your opponent''s Life Points. Also, inflict 300 points of damage to your opponent''s Life Points for each "Attack and Receive" card in your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62867251,3,0,0,131076,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (62867251, 'Light of Intervention', 'While this card is on the field, Monster Cards cannot be Set or flipped face-down. If a Monster Card would be Set, it must be Normal Summoned in face-up Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61740673,3,0,0,131076,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (61740673, 'Imperial Order', 'As long as this card remains face-up on the field, negate the effects of all Spell Cards on the field. Pay 700 Life Points during each of your Standby Phases. If you do not, this card is destroyed.', 'Pay 700LP?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61705417,3,0,0,4,0,0,0,0,0,1024);
INSERT OR REPLACE INTO "texts" VALUES (61705417, 'Graverobber', 'Select 1 Spell Card from your opponent''s Graveyard. You can use it as your hand until the end of the turn. If you use it, you take 2000 points of damage.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60866277,3,0,0,4,0,0,0,0,0,2097154);
INSERT OR REPLACE INTO "texts" VALUES (60866277, 'Earthshaker', 'Select 2 Monster Card Attributes. Your opponent then selects 1 of the 2 Attributes and destroys all face-up monsters with that Attribute on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60682203,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (60682203, 'Cold Wave', 'This card can only be activated at the start of your Main Phase 1. Until your next turn, you and your opponent cannot play or Set any Spell or Trap Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60082869,3,0,0,4,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (60082869, 'Dust Tornado', 'Target 1 Spell/Trap Card your opponent controls; destroy that target, then you can Set 1 Spell/Trap Card from your hand.', 'Set 1 Card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59560625,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (59560625, 'Shift', 'When your opponent targets exactly 1 monster you control (and no other cards) for an attack, or with a Spell/Trap effect: Target another monster you control that would be an appropriate target; that attack/Spell/Trap now targets the new target.', '改变对方的效果的对象', '改变对方的战斗对象', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59344077,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (59344077, 'Magic Drain', 'When your opponent activates a Spell Card: They can discard 1 Spell Card to negate this card''s effect, otherwise negate the activation of their Spell Card, and if you do, destroy it.', 'Discard 1 Spell Card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58621589,3,0,0,4,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (58621589, 'Shadow of Eyes', 'When a monster(s) is Set on your opponent''s side of the field: Target 1 of those Set monsters; change that Set monster to face-up Attack Position. (Flip Effects are not activated.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57409948,3,0,0,2097185,400,900,2,2048,8,2);
INSERT OR REPLACE INTO "texts" VALUES (57409948, 'Bombardment Beetle', 'FLIP: Pick up and see 1 face-down Defense Position Monster Card on your opponent''s side of the field. If it is an Effect Monster, destroy it (its Flip Effect is not activated), and if the card is not, return it to its original position.', '确认盖卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54109233,3,0,0,131076,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (54109233, 'Infinite Dismissal', 'Level 3 or lower monsters are destroyed during the End Phase of the turn that they are Normal Summoned or Flip Summoned.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52675689,3,0,0,33,1500,1800,5,2,32,65536);
INSERT OR REPLACE INTO "texts" VALUES (52675689, 'Invitation to a Dark Sleep', 'When this monster is Normal Summoned or Flip Summoned, select 1 of your opponent''s monsters. As long as this card remains face-up on the field, the selected monster cannot attack.', 'Cannot attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51345461,3,0,0,33,2450,1700,7,1,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (51345461, 'Sword Hunter', 'At the end of the Battle Phase, if this card destroyed a monster(s) by battle and sent it to the Graveyard this Battle Phase: Equip all those monsters from the Graveyard to this card as an Equip Spell Card(s) with this effect.
● The equipped monster gains 200 ATK.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50122883,3,0,0,2097185,500,300,2,8,32,2048);
INSERT OR REPLACE INTO "texts" VALUES (50122883, 'Bite Shoes', 'FLIP: Change the battle position of 1 face-up monster on the field.', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49587034,3,0,0,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (49587034, 'Lightforce Sword', 'Select 1 random card from your opponent''s hand and remove it from play face-down. During your opponent''s 4th Standby Phase after this card''s activation, return that card to their hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49251811,3,0,0,4,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (49251811, 'Mystic Probe', 'You can only activate this card when a Continuous Spell Card is activated. Negate all Continuous Spell Cards during the turn this card is activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48539234,3,0,0,131076,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (48539234, 'Appropriate', 'Activate only when your opponent draws a card(s), except during their Draw Phase. Draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43711255,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (43711255, 'Prohibition', 'Activate by declaring 1 card name. Cards with that name, and their effects, cannot be used. Cards already on the field are not affected (including face-down cards).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43434803,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (43434803, 'The Shallow Grave', 'Each player selects 1 monster in their Graveyard and Special Summons it in face-down Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42599677,3,0,0,17,1900,1300,5,128,4,0);
INSERT OR REPLACE INTO "texts" VALUES (42599677, 'Flame Champion', 'A warrior protected by a flaming shield that nullifies any attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37580756,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (37580756, 'Michizure', 'Activate only when a monster is sent from the field to your Graveyard. Select and destroy 1 monster on the field. (You can activate this card during the Damage Step.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37313786,3,0,0,4,0,0,0,0,0,134217984);
INSERT OR REPLACE INTO "texts" VALUES (37313786, 'Gamble', 'You can only activate this card when your opponent''s hand is 6 or more cards and your hand is 2 or less. Toss a coin and call heads or tails. If you call it right, draw until your hand has 5 cards. If you call it wrong, skip your next turn.', 'Please select Head or Tails', 'Head', 'Tails', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36868108,3,0,0,4,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (36868108, 'Armored Glass', 'You can only activate this card when a monster is equipped with an Equip Spell Card. Negate the effects of all Equip Spell Cards on the field during the turn this card is activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36468556,3,0,0,4,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (36468556, 'Ceasefire', 'Change all face-down Defense Position monsters on the field to face-up Defense Position (Flip Effects are not activated), also inflict 500 damage to your opponent for each Effect Monster on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36280194,3,0,0,4,0,0,0,0,0,1024);
INSERT OR REPLACE INTO "texts" VALUES (36280194, 'Backup Soldier', 'Activate only if there are 5 or more monsters in your Graveyard. Add up to 3 non-Effect Monsters with 1500 ATK or less from your Graveyard to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35346968,3,0,0,131076,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (35346968, 'Solemn Wishes', 'Increase your Life Points by 500 points each time you draw a card (or cards).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35316708,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (35316708, 'Time Seal', 'Skip the Draw Phase of your opponent''s next turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34694160,3,0,0,131076,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (34694160, 'The Eye of Truth', 'As long as this card remains face-up on the field, your opponent must show his/her hand. Your opponent increases his/her Life Points by 1000 points at each of his/her Standby Phases if he/she has a Spell Card in his/her hand.', 'Recover', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32269855,3,0,0,17,1300,500,3,16384,8,0);
INSERT OR REPLACE INTO "texts" VALUES (32269855, 'The All-Seeing White Tiger', 'A proud ruler of the jungle that some fear and others respect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31477025,3,0,0,17,2100,1300,5,128,4,0);
INSERT OR REPLACE INTO "texts" VALUES (31477025, 'Mr. Volcano', 'This seemingly mild-mannered creature has an extremely volatile temper.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31447217,3,0,0,17,2750,2400,7,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (31447217, 'Wingweaver', 'A six-winged fairy who prays for peace and hope.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30655537,3,0,147,17,1400,1200,4,32,8,0);
INSERT OR REPLACE INTO "texts" VALUES (30655537, 'Cyber Falcon', 'A jet-powered hawk that travels at the speed of sound.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30532390,3,0,0,17,1800,600,4,512,8,0);
INSERT OR REPLACE INTO "texts" VALUES (30532390, 'Sky Scout', 'With eyes like a hawk and a flying speed exceeding Mach 5, this monster is a master of the sky.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30325729,3,0,0,17,1000,400,3,8,4,0);
INSERT OR REPLACE INTO "texts" VALUES (30325729, 'Dokuroyaiba', 'A boomerang with brains that will pursue a target to the ends of the earth.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27911549,3,0,0,2097185,500,300,2,2048,1,5505056);
INSERT OR REPLACE INTO "texts" VALUES (27911549, 'Parasite Paracide', 'FLIP: Put this card face-up in your opponent''s Deck and shuffle it. When your opponent draws this card, it is Special Summoned to their side of the field in face-up Defense Position, and inflicts 1000 damage to them. Then, while this card is face-up on the field, all monsters your opponent controls become Insect-Type monsters.', 'Special Summon', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27125110,3,0,0,17,0,0,1,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (27125110, 'Thousand-Eyes Idol', 'A wicked entity that controls the hearts of men, its thousand eyes are able to see and expand the negative influences in an individual''s soul.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24294108,3,0,0,131074,0,0,0,0,0,4194305);
INSERT OR REPLACE INTO "texts" VALUES (24294108, 'Burning Land', 'Destroy all Field Spell Cards on the field. Inflict 500 points of damage to each player''s Life Points during his/her Standby Phases.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24128274,3,0,0,33,1600,1800,5,1,2,33554432);
INSERT OR REPLACE INTO "texts" VALUES (24128274, 'Deepsea Warrior', 'As long as "Umi" is face-up on the field, this card is unaffected by any Spell Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23615409,3,0,0,131074,0,0,0,0,0,1114112);
INSERT OR REPLACE INTO "texts" VALUES (23615409, 'Insect Barrier', 'Insect-Type monsters your opponent controls cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23471572,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (23471572, 'Solomon''s Lawbook', 'Skip your next Standby Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23171610,3,0,0,65538,0,0,0,0,0,8194);
INSERT OR REPLACE INTO "texts" VALUES (23171610, 'Limiter Removal', 'Double the ATK of all Machine-Type monsters you controlled at both the activation and resolution of this card, until the End Phase. During the End Phase, destroy those monsters.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22959079,3,0,8978494,2,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (22959079, 'Dimensionhole', 'Select 1 monster on your side of the field and remove it from play until your next Standby Phase. While the monster is removed from play, the Monster Card Zone of the selected monster cannot be used.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22359980,3,0,0,131076,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (22359980, 'Mirror Wall', 'Each of your opponent''s monsters that conducted an attack while this card was face-up on the field has its ATK halved as long as this card remains on the field. During each of your Standby Phases, pay 2000 LP or destroy this card.', 'Pay 2000LP for the effect of "Mirror Wall"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21237481,3,0,0,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (21237481, 'Type Zero Magic Crusher', 'Discard 1 Spell Card from your hand to inflict 500 points of damage to your opponent''s Life Points.', 'Inflict damage', 'Activate the effect of "Type Zero Magic Crusher"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17449108,3,0,0,2,0,0,0,0,0,5);
INSERT OR REPLACE INTO "texts" VALUES (17449108, 'Nobleman of Extermination', 'Select, destroy, and remove from play 1 face-down Spell or Trap Card. If it was a Trap Card, both players must remove from play all copies of that card from their Decks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16227556,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (16227556, 'Inspection', 'During your opponent''s Standby Phase, you can pay 500 Life Points to randomly select 1 card in your opponent''s hand and look at it.', '查看手牌', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12253117,3,0,0,4,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (12253117, 'World Suppression', 'You can only activate this card when a Field Spell Card is activated. Negate the Field Spell Card during the turn this card is activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11761845,3,0,0,17,2400,2150,6,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (11761845, 'Beast of Talwar', 'Only the master of the sword among the Fiend-Type monsters is permitted to hold the Talwar.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10992251,3,0,0,17,1200,800,4,32,16,0);
INSERT OR REPLACE INTO "texts" VALUES (10992251, 'Gradius', 'A high-performance jet fighter with power capsules for variable attack capabilities.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9074847,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (9074847, 'Major Riot', 'You can activate this card when 1 or more of your monsters are returned from the field to your hand by your opponent''s card effect. Return all Monster Cards on the field to your respective hands. Both you and your opponent can then Special Summon from your hand the same number of Monster Cards on the field in face-down Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8951260,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (8951260, 'Respect Play', 'During their respective turns, each player must show their opponent their hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6104968,3,0,0,2097185,900,600,3,16384,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (6104968, 'Bubonic Vermin', 'FLIP: You can Special Summon 1 "Bubonic Vermin" from your Deck in face-down Defense Position. Then shuffle your Deck.', 'Special Summon', 'Special Summon 1 "Bubonic Vermin" from your Deck?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5265750,3,0,0,17,1600,900,4,1,2,0);
INSERT OR REPLACE INTO "texts" VALUES (5265750, 'Skull Mariner', 'A pirate ship that appears out of the mist and sinks any seagoing vessels.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4920010,3,0,0,17,900,200,2,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (4920010, 'Souls of the Forgotten', 'A wicked spirit created by the hateful souls of those who fell in battle. It grows by assimilating the souls of its enemies.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4266839,3,0,0,33,300,800,2,8,32,8388608);
INSERT OR REPLACE INTO "texts" VALUES (4266839, 'Kiseitai', 'When your opponent''s monster attacks this card in face-down Defense Position, this card becomes an Equip Spell Card equipped to the attacking monster (No damage calculation is conducted). During each of your opponent''s Standby Phases, increase your Life Points by half of the ATK of the monster equipped with this card.', '变成装备卡', '回复LP', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4042268,3,0,0,17,1100,2000,4,64,2,0);
INSERT OR REPLACE INTO "texts" VALUES (4042268, 'Island Turtle', 'A huge turtle that is often mistaken for an island.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3643300,3,0,0,33,1850,1600,5,1,2,33554432);
INSERT OR REPLACE INTO "texts" VALUES (3643300, 'The Legendary Fisherman', 'While "Umi" is on the field, this card is unaffected by Spell effects and cannot be targeted for attacks, but does not prevent your opponent from attacking you directly.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2311603,3,0,0,17,1600,1500,4,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (2311603, 'Overdrive', 'An all-terrain armored vehicle armed with a heavy-duty machine gun.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2130625,3,0,0,4,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (2130625, 'Numinous Healer', 'You can only activate this card when you take damage to your Life Points. Increase your Life Points by 1000 points. Also, increase your Life Points by 500 points per card if there are additional "Numinous Healer" cards in your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1918087,3,0,172,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (1918087, 'Minor Goblin Official', 'You can only activate this card when your opponent''s Life Points are 3000 or less. Inflict 500 points of damage to your opponent''s Life Points during each of his/her Standby Phases.', 'Inflict 500 damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1248895,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (1248895, 'Chain Destruction', 'When a monster(s) with 2000 or less ATK is Summoned: Target 1 of them; destroy all cards with that name in its controller''s hand and Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (473469,3,0,0,4,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (473469, 'Driving Snow', 'You can only activate this card when 1 or more of your Trap Cards are destroyed and sent from the field to the Graveyard by a card effect your opponent controls. Destroy 1 Spell or Trap Card on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (296499,3,0,0,131076,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (296499, 'The Regulation of Tribe', 'Declare 1 Type of monster. Monsters of the declared Type cannot attack. Tribute 1 monster from your side of the field during each of your Standby Phases. If you do not, this card is destroyed.', 'Tribute 1 monster for the effect of "The Regulation of Tribe"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
