BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (35322812,3,0,0,17,500,2500,5,32,4,0);
INSERT OR REPLACE INTO "texts" VALUES (35322812, 'Woodborg Inpachi', 'The new form of the enigmatic Inpachi, remodeled by cutting-edge Dark World technology. Maneuverability has been sacrificed for strong armor, which is considered more important.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62327910,3,0,0,17,500,1200,4,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (62327910, 'Mighty Guard', 'A machine soldier that was developed as a guard. It is made of rust-proof metal.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8715625,3,0,0,17,500,500,2,32,32,0);
INSERT OR REPLACE INTO "texts" VALUES (8715625, 'Bokoichi the Freightening Car', 'A freight car that is exclusively for Dekoichi. It can transport anything, but most cargo arrives broken.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34100324,3,0,100,17,500,500,2,512,8,0);
INSERT OR REPLACE INTO "texts" VALUES (34100324, 'Harpie Girl', 'A Harpie chick who aspires to flit about beautifully and gorgeously, but attack sharply.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61505339,3,0,0,33,2300,3000,8,4096,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (61505339, 'The Creator', 'This card cannot be Special Summoned from the Graveyard. Once per turn, you can select 1 monster in your Graveyard, then send 1 card from your hand to the Graveyard and Special Summon that monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97093037,3,0,0,33,1600,1500,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (97093037, 'The Creator Incarnate', 'You can Tribute this card to Special Summon 1 "The Creator" from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34088136,3,0,65,33,1400,900,3,2048,8,270336);
INSERT OR REPLACE INTO "texts" VALUES (34088136, 'Ultimate Insect LV3', 'If this card was Special Summoned by the effect of "Ultimate Insect LV1", while it remains on the field all of your opponent''s monsters lose 300 ATK. During your Standby Phase, by sending this face-up card to the Graveyard, Special Summon 1 "Ultimate Insect LV5" from your hand or Deck. (You cannot activate this effect the turn this card is Normal Summoned, Special Summoned, or flipped face-up.)', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60482781,3,0,65,33,2300,1700,6,1,1,34);
INSERT OR REPLACE INTO "texts" VALUES (60482781, 'Mystic Swordsman LV6', 'If you Normal Summon this card, you must place it in face-down Defense Position. If this card attacks a face-down Defense Position monster, destroy the monster immediately with this card''s effect without flipping it face-up or applying damage calculation. You can return the monster destroyed with this effect to the top of its owner''s Deck, instead of sending it to the Graveyard.', 'Destroy', 'Return monster to top of its owner''s Deck?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1995985,3,0,65,33,1000,1000,3,1,16,262656);
INSERT OR REPLACE INTO "texts" VALUES (1995985, 'Silent Swordsman LV3', 'Negate your opponent''s Spell effects that target this card. During your Standby Phase: You can send this face-up card to the Graveyard; Special Summon 1 "Silent Swordsman LV5" from your hand or Deck. You cannot activate this effect the turn this card is Summoned or flipped face-up.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81306586,3,0,90,33,900,1800,4,64,2,2105360);
INSERT OR REPLACE INTO "texts" VALUES (81306586, 'Nightmare Penguin', 'All face-up WATER monsters you control gain 200 ATK. When this card is flipped face-up: Target 1 card your opponent controls; return that target to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23265594,3,0,0,1057,500,500,3,32,32,17833984);
INSERT OR REPLACE INTO "texts" VALUES (23265594, 'Heavy Mech Support Platform', 'Once per turn, you can either: Target 1 Machine-Type monster you control, equip this card to that target, OR: Unequip this card and Special Summon it in face-up Attack Position. While equipped by this effect, the equipped monster gains 500 ATK and DEF. (A monster can only be equipped with 1 Union monster at a time. If the equipped monster would be destroyed, destroy this card instead.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18891691,3,0,0,33,2700,1500,8,32,1,1056768);
INSERT OR REPLACE INTO "texts" VALUES (18891691, 'Perfect Machine King', 'This card gains 500 ATK for each other Machine-Type monster on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65260293,3,0,0,33,1500,1200,4,2,16,2129920);
INSERT OR REPLACE INTO "texts" VALUES (65260293, 'Element Magician', 'This monster gets the following effect(s) while there is a monster(s) with the following Attribute(s) on the field: ● WATER: Control of this card cannot switch. ● WIND: If this card destroyed your opponent''s monster by battle, it can attack once again in a row.', 'Attack again', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92755808,3,0,0,33,1500,1200,4,65536,32,-2145378304);
INSERT OR REPLACE INTO "texts" VALUES (92755808, 'Element Saurus', 'This monster gets the following effect(s) while there is a monster(s) with the following Attribute(s) on the field: ● FIRE: This card gains 500 ATK. ● EARTH: Negate the effect of an Effect Monster that this card destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28143906,3,0,0,33,2400,1400,6,512,8,1024);
INSERT OR REPLACE INTO "texts" VALUES (28143906, 'Roc from the Valley of Haze', 'When this card is sent directly from your hand to the Graveyard, add this card to the Deck and shuffle it.', 'Return to deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64538655,3,0,0,33,1200,1200,4,1,8,134217730);
INSERT OR REPLACE INTO "texts" VALUES (64538655, 'Sasuke Samurai 4', 'If this card battles a monster, toss a coin and call heads or tails before damage calculation. If you call it right, destroy the opponent''s monster with this effect.', '战斗怪兽破坏', '正面', '反面', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91932350,3,76812113,100,33,1300,1400,4,512,8,2105344);
INSERT OR REPLACE INTO "texts" VALUES (91932350, 'Harpie Lady 1', '(This card''s name is always treated as "Harpie Lady".)
All WIND monsters gain 300 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27927359,3,76812113,100,33,1300,1400,4,512,8,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (27927359, 'Harpie Lady 2', '(This card''s name is always treated as "Harpie Lady".)
Negate the effects of Flip Effect monsters this card destroys by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54415063,3,76812113,100,33,1300,1400,4,512,8,65536);
INSERT OR REPLACE INTO "texts" VALUES (54415063, 'Harpie Lady 3', '(This card''s name is always treated as "Harpie Lady").
An opponent''s monster that battles this card cannot declare an attack during your opponent''s next 2 turns.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90810762,3,0,0,33,100,200,3,128,4,139264);
INSERT OR REPLACE INTO "texts" VALUES (90810762, 'Raging Flame Sprite', 'This card can attack your opponent directly. If this card inflicts battle damage to your opponent by a direct attack: This card gains 1000 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26205777,3,0,190,33,2400,1000,6,128,4,4194368);
INSERT OR REPLACE INTO "texts" VALUES (26205777, 'Thestalos the Firestorm Monarch', 'When this card is Tribute Summoned, discard 1 random card from your opponent''s hand. If it was a Monster Card, inflict damage to your opponent equal to its Level x 100.', 'Opponent discards 1 random card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53693416,3,0,0,33,1300,1200,3,512,8,33554432);
INSERT OR REPLACE INTO "texts" VALUES (53693416, 'Eagle Eye', 'When this card is Normal Summoned successfully, no Trap Cards can be activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89698120,3,0,0,33,1300,1200,3,1,1,33554432);
INSERT OR REPLACE INTO "texts" VALUES (89698120, 'Tactical Espionage Expert', 'When this card is Normal Summoned successfully, no Trap Cards can be activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26082229,3,0,0,33,1300,1200,3,128,4,33554432);
INSERT OR REPLACE INTO "texts" VALUES (26082229, 'Invasion of Flames', 'When this card is Normal Summoned successfully, no Trap Cards can be activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52571838,3,0,0,33,1300,1200,3,131072,2,33554432);
INSERT OR REPLACE INTO "texts" VALUES (52571838, 'Creeping Doom Manta', 'When this card is Normal Summoned successfully, no Trap Cards can be activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88975532,3,0,0,33,1600,600,4,32768,32,0);
INSERT OR REPLACE INTO "texts" VALUES (88975532, 'Pitch-Black Warwolf', 'Your opponent cannot activate Trap Cards during the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15960641,3,0,0,33,1600,600,4,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (15960641, 'Mirage Dragon', 'Your opponent cannot activate Trap Cards during the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51355346,3,0,0,33,2000,0,4,128,4,1073154);
INSERT OR REPLACE INTO "texts" VALUES (51355346, 'Gaia Soul the Combustible Collective', 'You can tribute up to 2 Pyro-Type monsters. If you do this, this card gains ATK equal to the number of tributed monsters x 1000. During battle between this card and a Defense Position monster whose DEF is lower than the ATK of this card, inflict the difference as Battle Damage to your opponent. Destroy this card at the end of this turn.', 'Gain ATK', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88753985,3,0,0,33,300,200,2,128,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (88753985, 'Fox Fire', 'During the End Phase, if this card was destroyed by battle and sent to the Graveyard this turn and was face-up at the start of the Damage Step: Special Summon this card from the Graveyard. This face-up card cannot be Tributed for a Tribute Summon.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14148099,3,0,21,33,2300,1100,6,32,32,83886082);
INSERT OR REPLACE INTO "texts" VALUES (14148099, 'Big Core', 'Put 3 counters on this card when you Normal Summon it. This card cannot be destroyed as a result of battle. If this card battles a monster, remove 1 counter from this card at the end of the Damage Step. If this card battles without a counter, destroy this card at the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51632798,3,0,0,33,2800,2000,7,32,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (51632798, 'Fusilier Dragon, the Dual-Mode Beast', 'You can Normal Summon or Set this card without Tributing. If you do, its original ATK and DEF are halved.', 'Summon without tributes', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87621407,3,0,0,2097185,1400,1000,4,32,32,256);
INSERT OR REPLACE INTO "texts" VALUES (87621407, 'Dekoichi the Battlechanted Locomotive', 'FLIP: Draw 1 card, then draw 1 additional card for each face-up "Bokoichi the Freightening Car" you control.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13026402,3,0,0,33,300,400,2,32,4,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (13026402, 'A-Team: Trap Disposal Unit', 'This effect can be used during either player''s turn. When your opponent activates a Trap Card, Tribute this face-up card to negate the activation of the Trap Card and destroy it.', '発動を無効にし、それを破壊', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40410110,3,0,0,33,1800,1600,4,1024,16,2097152);
INSERT OR REPLACE INTO "texts" VALUES (40410110, 'Homunculus the Alchemic Being', 'Once per turn, you can change the Attribute of this monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86805855,3,0,0,97,2200,1500,6,1,32,4);
INSERT OR REPLACE INTO "texts" VALUES (86805855, 'Dark Blade the Dragon Knight', '"Dark Blade" + "Pitch-Dark Dragon"
Each time this card inflicts Battle Damage to your opponent, you can select up to 3 Monster Cards from your opponent''s Graveyard and remove them from play.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13803864,3,0,0,97,300,100,6,4,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (13803864, 'Mokey Mokey King', '"Mokey Mokey" + "Mokey Mokey" + "Mokey Mokey"
When this card is removed from the field, you can Special Summon as many "Mokey Mokey" as possible from your Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49398568,3,0,0,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (49398568, 'Serial Spell', 'Activate only when you activate one of your Normal Spell Cards. Discard all the cards in your hand to the Graveyard. The effect of this card becomes the same as the Normal Spell Card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75782277,3,0,100,524290,0,0,0,0,0,8193);
INSERT OR REPLACE INTO "texts" VALUES (75782277, 'Harpies'' Hunting Ground', 'All Winged Beast-Type monsters gain 200 ATK and DEF. When any "Harpie Lady" or "Harpie Lady Sisters" are Normal or Special Summoned: The player who conducted the Summon targets 1 Spell/Trap Card on the field; destroy that target.', 'S/T Destruction', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12181376,3,0,0,2,0,0,0,0,0,-2147475456);
INSERT OR REPLACE INTO "texts" VALUES (12181376, 'Triangle Ecstasy Spark', 'Until the End Phase, the ATK of all "Harpie Lady Sisters" currently on the field becomes 2700, your opponent cannot activate any Trap Cards, also negate all your opponent''s Trap Card effects on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48576971,3,0,0,262146,0,0,0,0,0,320);
INSERT OR REPLACE INTO "texts" VALUES (48576971, 'Necklace of Command', 'When a monster you control that''s equipped with this card is destroyed by battle, and this card is sent to the Graveyard, you can either:
● Draw 1 card. OR
● Discard 1 random card from your opponent''s hand.', 'Select effect', 'Draw 1 card', 'Discard 1 random card from your opponent''s hand', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63995093,3,0,0,2,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (63995093, 'Machine Duplication', 'Select 1 face-up Machine-Type monster you control with 500 or less ATK. You can Special Summon up to 2 cards with the same name from your Deck.', 'Select 1 face-up Machine-Type monster with 500 or less ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75560629,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (75560629, 'Flint', 'A monster equipped with this card loses 300 ATK and cannot change its Battle Position or attack. If the equipped monster is destroyed, select 1 monster on the field and equip this card to that monster.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1965724,3,0,0,131074,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (1965724, 'Mokey Mokey Smackdown', 'While a face-up "Mokey Mokey" is on your side of the field, if a Fairy-Type monster on your side of the field is destroyed, the ATK of all "Mokey Mokey" on your side of the field becomes 3000 until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47453433,3,0,0,2,0,0,0,0,0,40);
INSERT OR REPLACE INTO "texts" VALUES (47453433, 'Back to Square One', 'Discard 1 card, then target 1 monster on the field; place that target on the top of the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74848038,3,0,0,2,0,0,0,0,0,1048);
INSERT OR REPLACE INTO "texts" VALUES (74848038, 'Monster Reincarnation', 'Discard 1 card, then target 1 monster in your Graveyard; add it to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (242146,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (242146, 'Ballista of Rampart Smashing', 'If the equipped monster attacks a face-down Defense Position monster, it gains 1500 ATK during damage calculation only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37231841,3,0,0,131074,0,0,0,0,0,288);
INSERT OR REPLACE INTO "texts" VALUES (37231841, 'Lighten the Load', 'Once per turn, you can add 1 Level 7 or higher monster from your hand to your Deck and shuffle it, then draw 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13626450,3,0,0,65538,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (13626450, 'Malice Dispersion', 'Discard 1 card from your hand. Destroy all face-up Continuous Trap Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35686187,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (35686187, 'Tragedy', 'Activate only when a monster on your opponent''s side of the field in face-up Attack Position is changed to face-up Defense Position. Destroy all Defense Position monsters on your opponent''s side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49010598,3,0,0,1048580,0,0,0,0,0,-2147483638);
INSERT OR REPLACE INTO "texts" VALUES (49010598, 'Divine Wrath', 'When a monster effect is activated: Discard 1 card; negate the activation, and if you do, destroy that monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76515293,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (76515293, 'Xing Zhen Hu', 'Activate by selecting 2 Set Spell or Trap Cards on the field. The selected Spell or Trap Cards cannot be activated.', 'セットされた魔法・罠カードを２枚選んで下さい', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12503902,3,0,0,131076,0,0,0,0,0,33562624);
INSERT OR REPLACE INTO "texts" VALUES (12503902, 'Rare Metalmorph', 'Activate this card by targeting 1 Machine-Type monster on the field; it gains 500 ATK. Once, negate a Spell effect that targets that monster. When that monster leaves the field, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49998907,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (49998907, 'Fruits of Kozaky''s Studies', 'Look at the top 3 cards of your Deck and return those cards to the top of the Deck in any order.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75392615,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (75392615, 'Mind Haxorz', 'Pay 500 Life Points. Look at your opponent''s hand and all Set cards on their side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1781310,3,0,0,4,0,0,0,0,0,323);
INSERT OR REPLACE INTO "texts" VALUES (1781310, 'Fuh-Rin-Ka-Zan', 'You can only activate this card when there are at least 1 monster each of WIND, WATER, FIRE and EARTH Attributes face-up on the field. Select and apply 1 of these effects: ● Destroy all monsters on your opponent''s side of the field. ● Destroy all Spell and Trap Cards on your opponent''s side of the field. ● Randomly discard 2 cards from your opponent''s hand. ● Draw 2 cards.', 'Destroy all monsters on your opponent''s side of the field', 'Destroy all Spell and Trap Cards on your opponent''s side of the field', 'Randomly discard 2 cards from your opponent''s hand', 'Draw 2 cards', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48276469,3,0,0,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (48276469, 'Chain Burst', 'Each time a player activates a Trap Card, they take 1000 damage immediately after it resolves.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74270067,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (74270067, 'Pikeru''s Circle of Enchantment', 'Damage to you from card effects becomes 0 until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1669772,3,0,0,4,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (1669772, 'Spell Purification', 'Discard 1 card from your hand. Destroy all face-up Continuous Spell Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37053871,3,0,0,131076,0,0,0,0,0,131072);
INSERT OR REPLACE INTO "texts" VALUES (37053871, 'Astral Barrier', 'If your opponent''s monster attacks a monster on your side of the field, you can make the attack a direct attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74458486,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (74458486, 'Covering Fire', 'During the Damage Step, while an opponent''s monster is attacking a monster you control: Target 1 other face-up monster you control; your attacked monster gains ATK equal to that target''s ATK during the Damage Step only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
