BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (19680539,3,0,4218,33,1900,500,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (19680539, 'Noble Knight Gawayn', 'If you control a LIGHT Normal Monster, you can Special Summon this card (from your hand) in face-up Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14214060,3,0,0,17,2600,200,6,2,1,0);
INSERT OR REPLACE INTO "texts" VALUES (14214060, 'Trance the Magic Swordsman', 'A peculiar magician with considerable abilities. Supposedly, he''s just returned from a trip to outer space.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50613779,3,0,0,33,600,1200,3,2,32,8650752);
INSERT OR REPLACE INTO "texts" VALUES (50613779, 'Damage Mage', 'When you take damage from a card effect: You can Special Summon this card from your hand, and if you do, gain Life Points equal to the amount of damage you took.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87008374,3,0,126,33,1100,0,3,512,4,4202496);
INSERT OR REPLACE INTO "texts" VALUES (87008374, 'ZW - Phoenix Bow', 'You can target 1 face-up "Number C39: Utopia Ray" you control; equip this card from your hand to that target. It gains 1100 ATK. When the equipped monster destroys an opponent''s monster by battle: Inflict 1000 damage to your opponent. You can only control 1 face-up "ZW - Phoenix Bow".', 'Equip', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13492423,3,0,85,33,2000,2800,8,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (13492423, 'Photon Caesar', 'When this card is Normal or Flip Summoned: You can Special Summon 1 "Photon Caesar" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50491121,3,0,275710063,33,1600,1000,4,1,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (50491121, 'Heroic Challenger - Spartan', 'Once per turn, when an opponent''s monster declares an attack: You can target 1 face-up "Heroic" monster you control, except this card; this card gains ATK equal to that face-up monster''s original ATK, until the end of the Battle Phase.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26885836,3,0,275710063,33,2100,1300,6,1,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (26885836, 'Heroic Challenger - War Hammer', 'When this card destroys an opponent''s monster by battle and sends it to the Graveyard: You can equip the destroyed monster to this card. (You can only equip 1 monster at a time to this card with this effect.) This card gains ATK equal to that equipped monster''s ATK.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52370835,3,0,275710063,33,0,2000,4,1,1,16777216);
INSERT OR REPLACE INTO "texts" VALUES (52370835, 'Heroic Challenger - Swordshield', 'During either player''s turn, if you control a face-up "Heroic" monster: You can send this card from your hand to the Graveyard; for the rest of this turn, you take no Battle Damage and "Heroic" monsters you control cannot be destroyed by battle.', 'Activated', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89774530,3,0,275710063,33,1700,900,4,1,1,1074003968);
INSERT OR REPLACE INTO "texts" VALUES (89774530, 'Heroic Challenger - Double Lance', 'When this card is Normal Summoned: You can Special Summon 1 "Heroic Challenger - Double Lance" from your hand or Graveyard in face-up Defense Position. This card cannot be used as a Synchro Material Monster. This card cannot be used as an Xyz Material, except for the Xyz Summon of a Warrior-Type monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25163248,3,0,112,33,1500,700,3,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (25163248, 'Chronomaly Mayan Machine', 'This card can be treated as 2 Tributes for the Tribute Summon of a Machine-Type monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52158283,3,0,112,33,800,1600,4,256,1,2048);
INSERT OR REPLACE INTO "texts" VALUES (52158283, 'Chronomaly Colossal Head', 'You can banish this card from your Graveyard to target 1 Level 3 or higher Attack Position monster on the field; change it to face-up or face-down Defense Position. The effect of "Chronomaly Colossal Head" can only be used once per turn.', 'Change position', 'Change to face-up Defense Position', 'Change to face-down Defense Position', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88552992,3,0,112,33,1300,1400,4,32,16,0);
INSERT OR REPLACE INTO "texts" VALUES (88552992, 'Chronomaly Golden Jet', 'Once per turn: You can increase the Levels of all "Chronomaly" monsters you currently control by 1.', 'Increase level', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15941690,3,0,112,33,1300,400,3,256,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (15941690, 'Chronomaly Crystal Bones', 'If your opponent controls a monster and you control no monsters, you can Special Summon this card (from your hand). When you do: You can Special Summon 1 "Chronomaly" monster from your hand or Graveyard, except "Chronomaly Crystal Bones".', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51435705,3,0,112,33,900,600,3,256,16,512);
INSERT OR REPLACE INTO "texts" VALUES (51435705, 'Chronomaly Crystal Skull', 'If you control a face-up "Chronomaly" monster: You can discard this card to the Graveyard; add 1 "Chronomaly" monster from your Deck or Graveyard to your hand, except "Chronomaly Crystal Skull". The effect of "Chronomaly Crystal Skull" can only be used once per turn.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87430304,3,0,112,33,1800,1600,5,256,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (87430304, 'Chronomaly Moai', 'If you control a face-up "Chronomaly" monster, you can Special Summon this card (from your hand) in face-up Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14824019,3,0,4206,33,500,400,2,2,2,512);
INSERT OR REPLACE INTO "texts" VALUES (14824019, 'Spellbook Magician of Prophecy', 'When this card is Normal Summoned or flipped face-up: Add 1 "Spellbook" Spell Card from your Deck to your hand.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40213117,3,0,110,33,600,2000,3,2,1,1310720);
INSERT OR REPLACE INTO "texts" VALUES (40213117, 'Amores of Prophecy', 'Once per turn: You can reveal 1 "Spellbook" Spell Card in your hand; Special Summon 1 Level 4 or lower Spellcaster-Type monster from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87608852,3,0,110,33,1000,1000,3,2,1,1310720);
INSERT OR REPLACE INTO "texts" VALUES (87608852, 'Temperance of Prophecy', 'During your Main Phase, if you have activated a "Spellbook" Spell Card previously this turn: You can Tribute this card; Special Summon 1 Level 5 or higher LIGHT or DARK Spellcaster-Type monster from your Deck. You cannot Special Summon another Level 5 or higher monster during the turn you activate this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49191560,3,0,110,33,1800,1300,4,2,8,1049616);
INSERT OR REPLACE INTO "texts" VALUES (49191560, 'Charioteer of Prophecy', 'Once per turn: You can discard 1 "Spellbook" Spell Card to target 1 Spellcaster-Type monster in your Graveyard; add that target to your hand.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86585274,3,0,110,33,2500,2100,7,2,16,262147);
INSERT OR REPLACE INTO "texts" VALUES (86585274, 'High Priestess of Prophecy', 'You can reveal 3 "Spellbook" Spell Cards in your hand; Special Summon this card from your hand. Once per turn: You can banish 1 "Spellbook" Spell Card from your hand or Graveyard, then target 1 card on the field; destroy that target.', 'Special Summon', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12980373,3,0,113,33,500,300,3,16384,1,262176);
INSERT OR REPLACE INTO "texts" VALUES (12980373, 'Madolche Mewfeuille', 'When this card you control is destroyed by your opponent''s card (either by battle or by card effect) and sent to your Graveyard: Shuffle this card into your Deck. When this card is Normal Summoned: You can Special Summon 1 "Madolche" monster from your hand.', 'Return to deck', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49374988,3,0,113,33,0,1800,3,16384,1,2080);
INSERT OR REPLACE INTO "texts" VALUES (49374988, 'Madolche Baaple', 'When this card in your possession is destroyed by your opponent''s card (either by battle or by card effect) and sent to your Graveyard: Shuffle this card into your Deck. Once per turn: You can target 1 Attack Position "Madolche" monster you control and 1 face-up Attack Position monster your opponent controls; if both monsters are still on the field, change them to face-up Defense Position, and if you do, the ones changed by this effect cannot have their battle positions changed until the end of your opponent''s next turn.', 'Return to deck', '表側守備表示にする', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75363626,3,0,113,33,1700,1300,4,1,1,65568);
INSERT OR REPLACE INTO "texts" VALUES (75363626, 'Madolche Chouxvalier', 'When this card you control is destroyed by your opponent''s card (either by battle or by card effect) and sent to your Graveyard: Shuffle this card into your Deck. Your opponent cannot target face-up "Madolche" monsters you control for attacks, except "Madolche Chouxvalier".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11868731,3,0,113,33,1400,1200,4,2,1,544);
INSERT OR REPLACE INTO "texts" VALUES (11868731, 'Madolche Magileine', 'When this card you control is destroyed by your opponent''s card (either by battle or by effect) and sent to your Graveyard: Shuffle this card into your Deck. When this card is Normal or Flip Summoned: You can add 1 "Madolche" monster from your Deck to your hand.', 'Return to deck', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48252330,3,0,113,33,1500,800,4,2,1,544);
INSERT OR REPLACE INTO "texts" VALUES (48252330, 'Madolche Butlerusk', 'When this card you control is destroyed by your opponent''s card (either by battle or by card effect) and sent to your Graveyard: Shuffle this card into your Deck. When this card is Normal Summoned: You can add 1 Field Spell Card from your Deck to your hand. There must be another face-up "Madolche" monster on the field to activate and to resolve this effect.', 'Return to deck', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74641045,3,0,113,33,1000,1000,5,4,1,8227);
INSERT OR REPLACE INTO "texts" VALUES (74641045, 'Madolche Puddingcess', 'When this card you control is destroyed by your opponent''s card (either by battle or by card effect) and sent to your Graveyard: Shuffle this card into your Deck. While you have no monsters in your Graveyard, this card gains 800 ATK and DEF. After damage calculation, when this card battles an opponent''s monster: You can target 1 card your opponent controls; destroy that target.', 'Return to deck', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1045143,3,0,7475314,33,1000,500,3,32,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (1045143, 'Geargiano Mk-II', 'When this card is Normal or Flip Summoned: You can Special Summon 1 "Geargia" monster from your hand or Graveyard in face-up Defense Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47030842,3,0,114,33,1400,800,4,32,1,262160);
INSERT OR REPLACE INTO "texts" VALUES (47030842, 'Geargiaccelerator', 'If you control a "Geargia" monster, you can Special Summon this card (from your hand) in face-up Defense Position. When this card is sent from the field to the Graveyard: You can target 1 "Geargia" monster in your Graveyard, except "Geargiaccelerator"; add that target to your hand.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73428497,3,0,114,33,1500,500,4,32,1,270336);
INSERT OR REPLACE INTO "texts" VALUES (73428497, 'Geargiarsenal', 'This card gains 200 ATK for each "Geargia" monster you control. You can Tribute this card; Special Summon 1 "Geargia" monster from your Deck in Defense Position, except "Geargiarsenal".', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (923596,3,0,114,33,1100,1900,4,32,1,2560);
INSERT OR REPLACE INTO "texts" VALUES (923596, 'Geargiarmor', 'Once per turn: You can change this card to face-down Defense Position. When this card is flipped face-up: You can add 1 "Geargia" monster from your Deck to your hand, except "Geargiarmor".', 'Flip into face-down Defense Position', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36318200,3,0,0,33,700,500,1,16384,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (36318200, 'Uniflora, Mystical Beast of the Forest', 'If all the monsters in your Graveyard are Beast-Type: You can Tribute this card; Special Summon 1 Beast-Type monster from your hand or Graveyard, except "Uniflora, Mystical Beast of the Forest", but it cannot attack this turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73702909,3,0,0,33,900,500,1,1,1,1310720);
INSERT OR REPLACE INTO "texts" VALUES (73702909, 'Little Trooper', 'If this card is destroyed by battle: You can Special Summon 1 Level 2 or lower Warrior-Type monster from your Deck in face-down Defense Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9791914,3,0,0,33,1500,1300,4,1,1,262147);
INSERT OR REPLACE INTO "texts" VALUES (9791914, 'Silver Sentinel', 'You can Set this card from your hand to your Spell & Trap Card Zone as a Spell Card. During the End Phase of the turn this Set card in your Spell & Trap Card Zone was destroyed by an opponent''s card effect and sent to the Graveyard: Target 1 card your opponent controls (if possible); Special Summon this card from the Graveyard, and if you do, destroy that target (if any).', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35195612,3,0,0,2097185,1400,1200,4,1,1,2097160);
INSERT OR REPLACE INTO "texts" VALUES (35195612, 'Dust Knight', 'FLIP: Send 1 EARTH monster from your Deck to the Graveyard.', 'Send to Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72580321,3,0,0,33,1000,1500,3,256,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (72580321, 'Block Golem', 'If all the monsters in your Graveyard are EARTH: You can Tribute this card to target 2 Level 4 or lower Rock-Type monsters in your Graveyard, except "Block Golem"; Special Summon those targets, but their effects that activate on the field cannot be activated this turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8078366,3,0,119,33,1400,0,3,262144,2,1056768);
INSERT OR REPLACE INTO "texts" VALUES (8078366, 'Atlantean Attack Squad', 'This card gains 800 ATK while you control a face-up Fish, Sea Serpent, or Aqua-Type monster other than this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35073065,3,0,0,33,2400,1000,7,8,32,3407872);
INSERT OR REPLACE INTO "texts" VALUES (35073065, 'Illusory Snatcher', 'When you Tribute Summon a monster: You can Special Summon this card from your hand, and if you do, the Type, Attribute, and Level of this card become the same as that face-up Tribute Summoned monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61468779,3,0,0,33,2800,2200,8,32768,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (61468779, 'Grandsoil the Elemental Lord', 'Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by having exactly 5 EARTH monsters in your Graveyard, and cannot be Special Summoned by other ways. When this card is Special Summoned: You can target 1 monster in either player''s Graveyard; Special Summon that target to your side of the field. If this card leaves the field, skip the Battle Phase of your next turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7852878,3,0,0,33,3000,1800,8,16384,1,262146);
INSERT OR REPLACE INTO "texts" VALUES (7852878, 'Three Thousand Needles', 'At the end of the Damage Step, if this Defense Position card was attacked by a monster whose ATK is lower than this card''s DEF: Destroy the attacking monster.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34251483,3,0,172,33,1900,0,4,32768,1,0);
INSERT OR REPLACE INTO "texts" VALUES (34251483, 'Goblin Marauding Squad', 'When this card declares an attack, your opponent cannot activate cards or effects. If this card attacks, it is changed to Defense Position at the end of the Battle Phase, and its battle position cannot be changed until the End Phase of your next turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60645181,3,0,111,8388641,2000,2000,4,1,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (60645181, 'Heroic Champion - Excalibur', '2 Level 4 Warrior-Type monsters
Once per turn: You can detach 2 Xyz Materials from this card; this card''s ATK becomes double its original ATK until your opponent''s next End Phase.', '元々の攻撃力の倍になる', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93730230,3,0,786544,8388641,2100,1000,3,1048576,16,0);
INSERT OR REPLACE INTO "texts" VALUES (93730230, 'Chronomaly Crystal Chrononaut', '2 Level 3 monsters
Once per turn, when this card is targeted for an attack: You can detach 1 Xyz Material from this card; this turn, this card cannot be destroyed by battle or by card effects, also your opponent takes any Battle Damage you would take from battles involving this card.', 'Inflict Battle Damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39139935,3,0,4718704,8388641,2400,1500,5,32,16,4202496);
INSERT OR REPLACE INTO "texts" VALUES (39139935, 'Number 33: Chronomaly Machu Mech', '2 Level 5 monsters
Once per turn: You can detach 1 Xyz Material from this card to target 1 face-up monster your opponent controls; inflict damage to your opponent equal to the difference between its original ATK and current ATK, and if you do, this card gains ATK equal to the damage inflicted.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66523544,3,0,123,8388641,5000,2000,10,32,16,1);
INSERT OR REPLACE INTO "texts" VALUES (66523544, 'Superdimensional Robot Galaxy Destroyer', '3 Level 10 monsters
Once per turn: You can detach 1 Xyz Material from this card; destroy all Spell and Trap Cards your opponent controls. Your opponent cannot activate Spell/Trap Cards in response to this effect''s activation.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92918648,3,0,110,8388641,2800,2600,7,2,32,1);
INSERT OR REPLACE INTO "texts" VALUES (92918648, 'Hierophant of Prophecy', '2 Level 7 Spellcaster-Type monsters
 Once per turn: You can detach 1 Xyz Material from this card; destroy Spell/Trap Card(s) your opponent controls, up to the number of "Spellbook" Spell Cards in your Graveyard.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28912357,3,0,0,8388641,2300,1500,4,32,1,262160);
INSERT OR REPLACE INTO "texts" VALUES (28912357, 'Gear Gigant X', '2 Level 4 Machine-Type monsters
Once per turn: You can detach 1 Xyz Material from this card; add 1 Level 4 or lower Machine-Type monster from your Deck or Graveyard to your hand. When this card leaves the field: You can target 1 Level 3 or lower "Geargia" monster in your Graveyard; Special Summon that target.', 'Add to hand', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65301952,3,0,0,8388641,1500,1500,4,2,32,8704);
INSERT OR REPLACE INTO "texts" VALUES (65301952, 'Alchemic Magician', '3 Level 4 Spellcaster-Type monsters

This card gains 200 ATK for each Spell Card in your Graveyard. Once per turn, during your End Phase: You can detach 1 Xyz Material from this card and send 1 card from your hand to the Graveyard; choose 1 Spell Card from your Deck, then Set it in your Spell & Trap Card Zone.', 'Set', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91895091,3,0,0,8388641,1800,2200,3,256,1,2359296);
INSERT OR REPLACE INTO "texts" VALUES (91895091, 'Soul of Silvermountain', '2 Level 3 EARTH monsters
Once per turn: You can detach 1 Xyz Material from this card to target 1 Set card in your opponent''s Spell & Trap Card Zone; it cannot be activated while this card is face-up on the field. If this card destroys an opponent''s monster by battle while it has Xyz Material: You can target 1 EARTH monster in your Graveyard; Special Summon that target in face-up Defense Position.', 'Cannot be activated', 'Special Summon', 'Select 1 Set card in your opponent''s Spell & Trap Card Zone', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28290705,3,0,0,8388641,2300,1400,4,1024,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (28290705, 'Fairy King Albverdich', '2 Level 4 EARTH monsters
Once per turn: You can detach 1 Xyz Material from this card; all non-EARTH monsters currently on the field lose 500 ATK and DEF.', '攻撃力・守備力ダウン', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64689404,3,0,0,8388641,2700,1000,6,1,1,1048578);
INSERT OR REPLACE INTO "texts" VALUES (64689404, 'Sword Breaker', '2 Level 6 monsters
Once per turn: You can detach 1 Xyz Material from this card to declare 1 Monster Type; this card gains the following effect. At the start of the Damage Step, if this card battles a monster of a Type that has been declared: Destroy that monster.', 'Activated', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90673413,3,0,84,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (90673413, 'Gagagarevenge', 'Target 1 "Gagaga" monster in your Graveyard; Special Summon it and equip it with this card. When this card leaves the field, destroy the equipped monster. When this card is sent to the Graveyard because the equipped monster was used as an Xyz Material: All Xyz Monsters you currently control gain 300 ATK.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27068117,3,0,0,2,0,0,0,0,0,1073741824);
INSERT OR REPLACE INTO "texts" VALUES (27068117, 'Overlay Regen', 'Target 1 face-up Xyz Monster on the field; attach this card to it as an Xyz Material.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53466826,3,0,111,2,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (53466826, 'Heroic Chance', 'Target 1 face-up "Heroic" monster you control; this turn, double its ATK, but it cannot attack your opponent directly. You can only activate 1 "Heroic Chance" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90951921,3,0,112,2,0,0,0,0,0,516);
INSERT OR REPLACE INTO "texts" VALUES (90951921, 'Chronomaly Technology', 'Target 1 "Chronomaly" monster in your Graveyard; banish it, then look at the top 2 cards of your Deck, add 1 of them to your hand, and send the other to the Graveyard. You can only activate 1 "Chronomaly Technology" per turn. You cannot Special Summon any monsters the turn you activate this card, except "Chronomaly" monsters.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26345570,3,0,112,131074,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (26345570, 'Chronomaly Pyramid Eye Tablet', 'All "Chronomaly" monsters you control gain 800 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52340274,3,0,123,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (52340274, 'Galaxy Queen''s Light', 'Target 1 face-up Level 7 or higher monster you control; the Levels of all other face-up monsters you currently control become the current Level of that monster, until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89739383,3,0,4206,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (89739383, 'Spellbook of Secrets', 'Add 1 "Spellbook" card from your Deck to your hand, except "Spellbook of Secrets". You can only activate 1 "Spellbook of Secrets" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25123082,3,0,4206,2,0,0,0,0,0,1057280);
INSERT OR REPLACE INTO "texts" VALUES (25123082, 'Spellbook of Power', 'Target 1 face-up Spellcaster-Type monster you control; until the End Phase, it gains 1000 ATK. Also, until the End Phase, each time it destroys an opponent''s monster by battle: You can add 1 "Spellbook" Spell Card from your Deck to your hand. You can only activate 1 "Spellbook of Power" per turn.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52628687,3,0,4206,262146,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (52628687, 'Spellbook of Life', 'Banish 1 Spellcaster-Type monster from your Graveyard and reveal 1 other "Spellbook" Spell Card in your hand to target 1 Spellcaster-Type monster in your Graveyard; Special Summon that target in face-up Attack Position and equip it with this card. The equipped monster''s Level is increased by the Level of the monster that was banished for this card''s activation. You can only activate 1 "Spellbook of Life" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88616795,3,0,4206,65538,0,0,0,0,0,34603008);
INSERT OR REPLACE INTO "texts" VALUES (88616795, 'Spellbook of Wisdom', 'Target 1 Spellcaster-Type monster on the field and activate 1 of these effects;
● That face-up monster is unaffected by other Spell effects this turn.
● That face-up monster is unaffected by Trap effects this turn.', 'This turn, that target is unaffected by the effects of other Spell Cards.', 'This turn, that target is unaffected by the effects of Trap Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14001430,3,0,113,524290,0,0,0,0,0,8240);
INSERT OR REPLACE INTO "texts" VALUES (14001430, 'Madolche Chateau', 'When this card is activated: Shuffle all "Madolche" monsters in your Graveyard into the Deck. All "Madolche" monsters on the field gain 500 ATK and DEF. If a monster(s) in your Graveyard would be returned to the Deck by the effect of a "Madolche" monster, you can add it to your hand instead.', 'Return to the hand instead?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51405049,3,0,0,2,0,0,0,0,0,4194816);
INSERT OR REPLACE INTO "texts" VALUES (51405049, 'Where Arf Thou?', 'If you control a face-up Level 1 monster: Add 1 Level 1 monster from your Deck to your hand. During the End Phase of this turn, take 2000 damage if you did not Normal Summon the added monster, or a card with the same name, after activating this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87890143,3,0,0,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (87890143, 'Generation Force', 'If you control an Xyz Monster: Add 1 "Xyz" card from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14289852,3,0,0,524290,0,0,0,0,0,17825792);
INSERT OR REPLACE INTO "texts" VALUES (14289852, 'Catapult Zone', 'Once per turn, if a monster you control would be destroyed by battle, you can send 1 Rock-Type monster from your Deck to the Graveyard instead.', 'Send 1 Rock-Type monster from your Deck to the Graveyard instead?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40383551,3,0,0,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (40383551, 'Cold Feet', 'You cannot activate, Set, or use the effects of any Spell/Trap Cards this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86778566,3,0,0,4,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (86778566, 'Impenetrable Attack', 'During the Battle Phase, activate 1 of these effects.
● Target 1 monster on the field; it cannot be destroyed by battle or by card effects during this Battle Phase.
● You take no battle damage during this Battle Phase.
', 'Target 1 monster; it cannot be destroyed during this Battle Phase.', 'During this Battle Phase, you take no Battle Damage.', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13166204,3,0,84,4,0,0,0,0,0,4194306);
INSERT OR REPLACE INTO "texts" VALUES (13166204, 'Gagagarush', 'When a face-up "Gagaga" monster(s) you control is targeted by the effect of an opponent''s monster: Negate the effect of that opponent''s monster, and if you do, destroy it, then inflict damage to your opponent equal to the destroyed monster''s ATK or DEF in the Graveyard (whichever is higher).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49551909,3,0,111,4,0,0,0,0,0,4194306);
INSERT OR REPLACE INTO "texts" VALUES (49551909, 'Heroic Retribution Sword', 'Target 1 face-up "Heroic" monster you control; equip this card to that target. All Battle Damage you take from battles involving the equipped monster is also inflicted to your opponent. After damage calculation: Destroy any opponent''s monster that battles the equipped monster.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86555018,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (86555018, 'Stonehenge Methods', 'When a face-up "Chronomaly" monster(s) you control is destroyed by battle or by a card effect and sent to the Graveyard: Special Summon 1 Level 4 or lower "Chronomaly" monster from your Deck in face-up Defense Position. It cannot change its battle position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12940613,3,0,113,4,0,0,0,0,0,8224);
INSERT OR REPLACE INTO "texts" VALUES (12940613, 'Madolche Lesson', 'Target 1 "Madolche" monster in your Graveyard; Shuffle that target into your Deck, and if you do, all "Madolche" monsters you currently control gain 800 ATK and DEF, then you can shuffle 1 other monster from your Graveyard into the Deck.', 'Shuffle 1 monster from your Graveyard into the Deck?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48439321,3,0,113,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (48439321, 'Madolche Waltz', 'Each time a "Madolche" monster you control attacks or is attacked, after damage calculation: Inflict 300 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75833426,3,0,113,1048580,0,0,0,0,0,-2147483629);
INSERT OR REPLACE INTO "texts" VALUES (75833426, 'Madolche Tea Break', 'When a Spell/Trap card is activated, if you have no monsters in your Graveyard: Negate the activation, and if you do, return it to the hand, then, if you control a face-up "Madolche Puddingcess", you can destroy 1 card your opponent controls.', 'Destroy 1 card your opponent controls?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11228035,3,0,115,4,0,0,0,0,0,8224);
INSERT OR REPLACE INTO "texts" VALUES (11228035, 'Xyz Soul', 'Target 1 Xyz Monster in either player''s Graveyard; all monsters you currently control gain ATK equal to its Rank × 200, then you can shuffle it into the Extra Deck. The ATK increase lasts until the End Phase.', 'Return Monster to Extra Deck?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48216773,3,0,0,4,0,0,0,0,0,32);
INSERT OR REPLACE INTO "texts" VALUES (48216773, 'Compulsory Escape Device', 'Each player chooses 1 monster they control, then shuffles it into the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74611888,3,0,0,4,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (74611888, 'Turnabout', 'If there is a face-up monster on the field whose current Level is different from its original Level: Change all monsters on the field to face-down Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1005587,3,0,8978508,4,0,0,0,0,0,-2147483646);
INSERT OR REPLACE INTO "texts" VALUES (1005587, 'Void Trap Hole', 'When your opponent Special Summons a monster(s) with 2000 or more ATK: Negate the effects of one of those monsters with 2000 or more ATK, and if you do, destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47594192,3,0,0,4,0,0,0,0,0,3);
INSERT OR REPLACE INTO "texts" VALUES (47594192, 'Three of a Kind', 'If you control 3 or more monsters with the same name, except Tokens: Target 3 cards your opponent controls; destroy those targets.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73599290,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (73599290, 'Soul Drain', 'Activate by paying 1000 Life Points. Monsters that are banished, as well as monsters in the Graveyard, cannot activate their effects (that start a Chain).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (983995,3,0,0,1048580,0,0,0,0,0,-2147483384);
INSERT OR REPLACE INTO "texts" VALUES (983995, 'Rebound', 'When your opponent activates a Spell Card, Trap Card, or monster effect that returns a card(s) from the field to the hand: Negate that effect, and if you do, send 1 card from your opponent''s hand (at random) or from their side of the field to the Graveyard. When this Set card is destroyed by your opponent''s card effect and sent to the Graveyard: Draw 1 card.', 'Draw', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36378044,3,0,0,131076,0,0,0,0,0,134217984);
INSERT OR REPLACE INTO "texts" VALUES (36378044, 'Lucky Punch', 'Once per turn, when an opponent''s monster declares an attack: You can toss a coin 3 times. If the result is 3 heads, draw 3 cards, but if the result is 3 tails, destroy this card. If this face-up card on the field is destroyed: You lose 6000 Life Points.', 'Coin toss', 'Do you want to toss a coin?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56174248,3,0,110,33,2500,1200,6,2,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (56174248, 'Prophecy Destroyer', 'If this card is in your Graveyard: You can banish 3 "Spellbook" Spell Cards from your Graveyard; Special Summon this card from your Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82579942,3,0,108,33,1200,3000,6,2,16,17039360);
INSERT OR REPLACE INTO "texts" VALUES (82579942, 'Lightray Madoor', 'If 3 or more of your LIGHT monsters are banished, you can Special Summon this card (from your hand). Once per turn, this card cannot be destroyed by battle.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14568951,3,0,43,33,2100,1200,5,262144,2,-2147418112);
INSERT OR REPLACE INTO "texts" VALUES (14568951, 'Blue Dragon Ninja', 'Once per turn, during either player''s turn: You can discard 1 "Ninja" monster and 1 "Ninjitsu Art" card to target 1 face-up monster your opponent controls; this turn, that monster''s effects are negated, also that monster cannot attack.', 'Negate effect', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41952656,3,0,0,33,1000,1000,2,262144,2,264);
INSERT OR REPLACE INTO "texts" VALUES (41952656, 'Imairuka', 'When this card on the field is destroyed by your opponent''s card (either by battle or by card effect) and sent to the Graveyard: Send the top card of your Deck to the Graveyard, then, if it was a WATER monster, draw 1 card.', '卡组送墓', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87347365,3,0,0,33,100,2100,4,256,1,262160);
INSERT OR REPLACE INTO "texts" VALUES (87347365, 'Revival Golem', 'The effect of "Revival Golem" can only be used once per turn. When this card is sent from your Deck to the Graveyard: Activate 1 of these effects.
 ● Special Summon this card from the Graveyard.  ● Add this card from the Graveyard to your hand.', 'Select effect', 'Special Summon this card from the Graveyard.', 'Add this card from the Graveyard to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14745409,3,0,8314,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (14745409, 'Noble Arms - Gallatin', 'You can only control 1 face-up "Noble Arms - Gallatin". Equip only to a Warrior-Type monster. It gains 1000 ATK. During each of your Standby Phases, it loses 200 ATK. If this face-up card on the field is destroyed and sent to the Graveyard: You can target 1 face-up Warrior-Type "Noble Knight" monster you control; equip this card to that target. This effect of "Noble Arms - Gallatin" can only be used once per turn.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40230018,3,0,4206,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (40230018, 'Spellbook Library of the Crescent', 'If you have no "Spellbook" Spell Cards in your Graveyard: Reveal 3 "Spellbook" Spell Cards with different names from your Deck, your opponent randomly adds 1 of them to your hand, and shuffle the rest back into your Deck. You can only activate 1 "Spellbook Library of the Crescent" per turn. You cannot activate any Spell Cards the turn you activate this card, except "Spellbook" Spell Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76224717,3,0,0,131074,0,0,0,0,0,1299);
INSERT OR REPLACE INTO "texts" VALUES (76224717, 'Advance Zone', 'Once per turn, during the End Phase of any turn in which you Tribute Summoned a monster(s): You can apply these effects, depending on the number of monsters you Tributed for Tribute Summons this turn.
● 1 or more: Destroy 1 Set card your opponent controls.
● 2 or more: Draw 1 card.
● 3 or more: Add 1 monster from your Graveyard to your hand.', 'Destroy 1 Set card your opponent controls', 'Draw 1 card', 'Add 1 monster from your Graveyard to your hand', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13629812,3,0,97,131076,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (13629812, 'Ninjitsu Art of Shadow Sealing', 'Tribute 1 "Ninja" monster to target 1 monster your opponent controls; banish that target. While that card is banished, its Monster Card Zone cannot be used. When this face-up card leaves the field: Return the card banished by this effect to the same Monster Card Zone in the same battle position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7392745,3,0,0,2097185,300,300,3,16,1,786432);
INSERT OR REPLACE INTO "texts" VALUES (7392745, 'Chewbone', 'FLIP: Special Summon 3 "Chewbone Jr. Tokens" (Zombie-Type/EARTH/Level 1/ATK 100 / DEF 300) in Defense Position to your opponent''s side of the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4192696,3,0,0,33,1700,1000,4,1024,1,4456448);
INSERT OR REPLACE INTO "texts" VALUES (4192696, 'Eco, Mystical Spirit of the Forest', 'When you take damage from an opponent''s card effect: You can Special Summon this card from your hand, and if you do, inflict damage to your opponent equal to the damage you took, also both players take no further effect damage this turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9161357,3,0,4718704,8388641,2600,3000,6,32,16,0);
INSERT OR REPLACE INTO "texts" VALUES (9161357, 'Number 6: Chronomaly Atlandis', '2 Level 6 monsters
When this card is Xyz Summoned: You can target 1 "Number" monster in your Graveyard; equip that target to this card. This card gains ATK equal to half the ATK of that equipped monster. Once per turn: You can detach 1 Xyz Material from this card to send the monster equipped by this effect to the Graveyard; halve your opponent''s Life Points. You cannot conduct your Battle Phase the turn you activate this effect.', 'Equip', 'LP减半', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35255456,3,0,0,2,0,0,0,0,0,268697600);
INSERT OR REPLACE INTO "texts" VALUES (35255456, 'Miracle Contact', 'Shuffle into the Deck, from your hand, field, or Graveyard, the Fusion Material Monsters that are listed on an "Elemental HERO" Fusion Monster that lists "Elemental HERO Neos" as a Fusion Material, then Special Summon that Fusion Monster from your Extra Deck, ignoring its Summoning conditions.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12644061,3,0,0,524290,0,0,0,0,0,-2145386496);
INSERT OR REPLACE INTO "texts" VALUES (12644061, 'Advanced Dark', 'All "Crystal Beast" monsters on the field and in the Graveyard become DARK. If "Rainbow Dragon" or "Rainbow Dark Dragon" attacks, negate the effects of the attack target during that Battle Phase. During damage calculation, if a "Crystal Beast" monster you control battles and you would take damage: You can send 1 "Crystal Beast" monster from your Deck to the Graveyard; you take no Battle Damage from that battle.', 'Reduce damage to 0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84530620,3,0,0,33,1300,600,4,4096,16,3145728);
INSERT OR REPLACE INTO "texts" VALUES (84530620, 'Pahunder', 'Once per turn: You can Normal Summon 1 Level 4 LIGHT Thunder-Type monster from your hand, except "Pahunder", as an additional Normal Summon.', 'Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21524779,3,0,0,33,1400,700,4,4096,16,3145728);
INSERT OR REPLACE INTO "texts" VALUES (21524779, 'Mahunder', 'Once per turn: You can Normal Summon 1 Level 4 LIGHT Thunder-Type monster from your hand, except "Mahunder", as an additional Normal Summon.', 'Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57019473,3,0,0,33,900,400,4,4096,16,4);
INSERT OR REPLACE INTO "texts" VALUES (57019473, 'Sishunder', 'When this card is Normal Summoned: You can target 1 Level 4 LIGHT Thunder-Type monster with 1600 or less ATK in your Graveyard, except "Sishunder"; banish that target. During the End Phase of this turn, add that card to your hand.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84417082,3,0,72,8388641,2400,2000,4,8192,16,3);
INSERT OR REPLACE INTO "texts" VALUES (84417082, 'Number 91: Thunder Spark Dragon', '3 Level 4 monsters
Once per turn, you can activate 1 of these effects.
● Detach 3 Xyz Materials from this card; destroy all other face-up monsters on the field.
● Detach 5 Xyz Materials from this card; destroy all cards your opponent controls.', 'Destroy all face-up monsters on the field, except this card.', 'Destroy all cards your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20802187,3,0,0,131074,0,0,0,0,0,1040);
INSERT OR REPLACE INTO "texts" VALUES (20802187, 'Spirit Converter', 'Once per turn: You can target 1 Xyz Monster you control; attach 1 Level 4 LIGHT monster you control to that target as an Xyz Material. When this card is sent from the field to the Graveyard: Target 2 Level 4 LIGHT Thunder-Type monsters with the same name in your Graveyard; add those targets to your hand.', 'Attach Xyz Material', 'Add cards to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
