BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (44330098,3,0,0,33,2700,2500,7,8,32,4456448);
INSERT OR REPLACE INTO "texts" VALUES (44330098, 'Gorz the Emissary of Darkness', 'When you take damage from a card your opponent control: You can Special Summon this card from your hand. You must control no cards to activate and to resolve this effect. When Special Summoned this way, activate the appropriate effect, based on the type of damage:
● Battle Damage: Special Summon 1 "Emissary of Darkness Token" (Fairy-Type/LIGHT/Level 7/ATK ?/DEF ?). Its ATK and DEF are each equal to the amount of Battle Damage you took.
● Effect Damage: Inflict damage to your opponent equal to the amount of damage you took.', 'Special Summon', 'Special Summon token', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77585513,3,0,188,33,2400,1500,6,32,32,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (77585513, 'Jinzo', 'Trap Cards, and their effects on the field, cannot be activated. Negate all Trap Card effects on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27911549,3,0,0,2097185,500,300,2,2048,1,5505056);
INSERT OR REPLACE INTO "texts" VALUES (27911549, 'Parasite Paracide', 'FLIP: Put this card face-up in your opponent''s Deck and shuffle it. When your opponent draws this card, it is Special Summoned to their side of the field in face-up Defense Position, and inflicts 1000 damage to them. Then, while this card is face-up on the field, all monsters your opponent controls become Insect-Type monsters.', 'Special Summon', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49587034,3,0,0,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (49587034, 'Lightforce Sword', 'Select 1 random card from your opponent''s hand and remove it from play face-down. During your opponent''s 4th Standby Phase after this card''s activation, return that card to their hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1248895,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (1248895, 'Chain Destruction', 'When a monster(s) with 2000 or less ATK is Summoned: Target 1 of them; destroy all cards with that name in its controller''s hand and Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60082869,3,0,0,4,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (60082869, 'Dust Tornado', 'Target 1 Spell/Trap Card your opponent controls; destroy that target, then you can Set 1 Spell/Trap Card from your hand.', 'Set 1 Card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97077563,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (97077563, 'Call of the Haunted', 'Activate this card by targeting 1 monster in your Graveyard; Special Summon that target in Attack Position. When this card leaves the field, destroy that target. When that target is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22359980,3,0,0,131076,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (22359980, 'Mirror Wall', 'Each of your opponent''s monsters that conducted an attack while this card was face-up on the field has its ATK halved as long as this card remains on the field. During each of your Standby Phases, pay 2000 LP or destroy this card.', 'Pay 2000LP for the effect of "Mirror Wall"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48539234,3,0,0,131076,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (48539234, 'Appropriate', 'Activate only when your opponent draws a card(s), except during their Draw Phase. Draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36468556,3,0,0,4,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (36468556, 'Ceasefire', 'Change all face-down Defense Position monsters on the field to face-up Defense Position (Flip Effects are not activated), also inflict 500 damage to your opponent for each Effect Monster on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81210420,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (81210420, 'Magical Hats', 'Activate only during your opponent''s Battle Phase. Select 2 non-Monster Cards from your Deck and 1 monster you control. Shuffle those 3 cards and Set them on the field in face-down Defense Position. The 2 cards selected from your Deck are treated as monsters (ATK 0/DEF 0) and are destroyed at the end of the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71044499,3,0,0,2,0,0,0,0,0,6);
INSERT OR REPLACE INTO "texts" VALUES (71044499, 'Nobleman of Crossout', 'Target 1 face-down monster on the field; destroy that target, and if you do, banish it, then, if it was a Flip monster, each player reveals their Main Deck, then banishes all cards from it with that monster''s name.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70828912,3,0,0,262146,0,0,0,0,0,262146);
INSERT OR REPLACE INTO "texts" VALUES (70828912, 'Premature Burial', 'Activate this card by paying 800 LP, then target 1 monster in your Graveyard; Special Summon that target in face-up Attack Position and equip it with this card. When this card is destroyed, destroy the equipped monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78193831,3,0,0,33,2600,2300,7,1,1,1056768);
INSERT OR REPLACE INTO "texts" VALUES (78193831, 'Buster Blader', 'This card gains 500 ATK for each Dragon-Type monster your opponent controls or is in their Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98139712,3,0,0,131076,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (98139712, 'Skull Invitation', 'Each time a card(s) is sent to the Graveyard, inflict 300 damage to its owner for each card sent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23171610,3,0,0,65538,0,0,0,0,0,8194);
INSERT OR REPLACE INTO "texts" VALUES (23171610, 'Limiter Removal', 'Double the ATK of all Machine-Type monsters you controlled at both the activation and resolution of this card, until the End Phase. During the End Phase, destroy those monsters.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96965364,3,0,0,2,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (96965364, 'Insect Imitation', 'Tribute 1 monster. Special Summon 1 Insect-Type monster from your Deck whose Level is 1 higher than the Tributed monster''s.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59344077,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (59344077, 'Magic Drain', 'When your opponent activates a Spell Card: They can discard 1 Spell Card to negate this card''s effect, otherwise negate the activation of their Spell Card, and if you do, destroy it.', 'Discard 1 Spell Card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85742772,3,0,0,131076,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (85742772, 'Gravity Bind', 'Level 4 or higher monsters cannot attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3643300,3,0,0,33,1850,1600,5,1,2,33554432);
INSERT OR REPLACE INTO "texts" VALUES (3643300, 'The Legendary Fisherman', 'While "Umi" is on the field, this card is unaffected by Spell effects and cannot be targeted for attacks, but does not prevent your opponent from attacking you directly.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27125110,3,0,0,17,0,0,1,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (27125110, 'Thousand-Eyes Idol', 'A wicked entity that controls the hearts of men, its thousand eyes are able to see and expand the negative influences in an individual''s soul.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63519819,3,0,0,97,0,0,1,2,32,16857088);
INSERT OR REPLACE INTO "texts" VALUES (63519819, 'Thousand-Eyes Restrict', '"Relinquished" + "Thousand-Eyes Idol"

Other monsters cannot change their battle position or attack. Once per turn, you can equip 1 monster your opponent controls to this card (max 1). This card''s ATK and DEF become the same as the equipped monster''s. If this card would be destroyed by battle, the equipped monster is destroyed instead.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83994646,3,0,0,2097185,800,1200,3,2048,8,2);
INSERT OR REPLACE INTO "texts" VALUES (83994646, '4-Starred Ladybug of Doom', 'FLIP: Destroy all Level 4 monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79870141,3,0,0,33,1400,1200,4,65536,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (79870141, 'Mad Sword Beast', ' If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78658564,3,0,172,33,2300,0,4,1,1,2048);
INSERT OR REPLACE INTO "texts" VALUES (78658564, 'Goblin Attack Force', 'If this card attacks, it is changed to Defense Position at the end of the Battle Phase, and its battle position cannot be changed until the End Phase of your next turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (423705,3,0,0,33,1800,1600,4,1,1,1);
INSERT OR REPLACE INTO "texts" VALUES (423705, 'Gearfried the Iron Knight', 'When an Equip Card(s) is equipped to this card: Destroy the Equip Card(s).', 'Destroy equipped card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69140098,3,0,0,17,1900,900,4,2,1,0);
INSERT OR REPLACE INTO "texts" VALUES (69140098, 'Gemini Elf', 'Elf twins that alternate their attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49064413,3,0,0,129,3200,1800,8,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (49064413, 'The Masked Beast', 'This card can only be Ritual Summoned with the Ritual Spell Card, "Curse of the Masked Beast".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31709826,3,0,0,33,1500,500,4,64,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (31709826, 'Revival Jam', 'When this card is destroyed by battle and sent to the Graveyard: You can pay 1000 Life Points; Special Summon it in face-up Defense Position during your next turn''s Standby Phase.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86569121,3,0,0,17,1500,1200,4,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (86569121, 'Melchid the Four-Face Beast', 'This monster has four different masks for four different attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94377247,3,0,0,130,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (94377247, 'Curse of the Masked Beast', 'This card is used to Ritual Summon "The Masked Beast". You must also Tribute monsters whose total Levels equal 8 or more from the field or your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29549364,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (29549364, 'Mask of Restrict', 'Monsters cannot be Tributed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55226821,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (55226821, 'Lightning Blade', 'Equip only to a Warrior-Type monster. It gains 800 ATK. All WATER monsters lose 500 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18605135,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (18605135, 'Tornado Wall', 'Activate only while "Umi" is on the field. While "Umi" is face-up on the field, you take no Battle Damage from attacking monsters. Destroy this card when "Umi" leaves the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53582587,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (53582587, 'Torrential Tribute', 'When a monster(s) is Summoned: Destroy all monsters on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94163677,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (94163677, 'Infinite Cards', 'There is no limit to the number of cards in players'' hands.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21558682,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (21558682, 'Jam Defender', 'When an opponent''s monster declares an attack on a monster you control: You can target 1 "Revival Jam" you control; switch the attack target to that target.', '攻撃対象を移し替える', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57953380,3,0,0,131074,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (57953380, 'Card of Safe Return', 'When a monster is Special Summoned from your Graveyard, you can draw 1 card.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56747793,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (56747793, 'United We Stand', 'The equipped monster gains 800 ATK and DEF for each face-up monster you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83746708,3,0,110,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (83746708, 'Mage Power', 'The equipped monster gains 500 ATK and DEF for each Spell and Trap Card you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88240808,3,0,0,33,1800,700,4,2,32,4);
INSERT OR REPLACE INTO "texts" VALUES (88240808, 'Kycoo the Ghost Destroyer', 'When this card inflicts battle damage to your opponent: You can target up to 2 monsters in their Graveyard; banish those targets. Your opponent cannot banish cards from either player''s Graveyard.', 'Select up to 2 monsters to banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40133511,3,0,0,33,1600,900,4,16384,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (40133511, 'Bazoo the Soul-Eater', 'Once per turn: You can banish up to 3 monsters from your Graveyard; this card gains 300 ATK for each, until the end of your opponent''s turn.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31829185,3,0,0,33,2200,2800,8,8,32,266240);
INSERT OR REPLACE INTO "texts" VALUES (31829185, 'Dark Necrofear', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by banishing 3 Fiend-Type monsters from your Graveyard. During the End Phase, if this card was destroyed by an opponent''s card this turn (either by battle or by card effect) and sent to the Graveyard while it was a Monster Card in your possession: Target 1 face-up monster your opponent controls; equip this card from the Graveyard to that target. While this card is equipped to a monster by this effect, take control of that monster.', 'Take control', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45894482,3,0,0,33,1400,400,3,65536,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (45894482, 'Gilasaurus', 'You can Special Summon this card (from your hand). When you do: Your opponent can target 1 monster in their Graveyard; your opponent Special Summons that target to their side of the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93599951,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (93599951, 'Dark Spirit of the Silent', 'Activate only when an opponent''s monster declares an attack. Negate that attack, and select another face-up monster your opponent controls. That monster attacks instead. (If it is in face-up Defense Position, change it to Attack Position.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94212438,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (94212438, 'Destiny Board', 'At the end of each of your opponent''s turns, place 1 "Spirit Message" card from your hand or your Deck face-up on the field. If you control the "Spirit Message" cards "I", "N", "A", and "L" in the proper order, you win the Duel. If any "Spirit Message" cards or "Destiny Board" you control is removed from the field, all "Spirit Message" cards and "Destiny Board" you control are sent to the Graveyard.', 'カードを出す', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31893528,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (31893528, 'Spirit Message "I"', 'This card can only be placed on the field by the effect of "Destiny Board."', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67287533,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (67287533, 'Spirit Message "N"', 'This card can only be placed on the field by the effect of "Destiny Board."', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94772232,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (94772232, 'Spirit Message "A"', 'This card can only be placed on the field by the effect of "Destiny Board."', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30170981,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (30170981, 'Spirit Message "L"', 'This card can only be placed on the field by the effect of "Destiny Board."', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62279055,3,0,0,4,0,0,0,0,0,4259840);
INSERT OR REPLACE INTO "texts" VALUES (62279055, 'Magic Cylinder', 'When an opponent''s monster declares an attack: Target the attacking monster; negate the attack, and if you do, inflict damage to your opponent equal to its ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3078576,3,0,0,545,200,100,2,8,8,32);
INSERT OR REPLACE INTO "texts" VALUES (3078576, 'Yata-Garasu', 'This card cannot be Special Summoned. This card returns to its owner''s hand during the End Phase of the turn it is Normal Summoned or flipped face-up. When this card inflicts Battle Damage to your opponent, they skip their next Draw Phase.', 'Spirit', '跳过下次抽卡阶段', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53982768,3,0,0,33,2450,1600,6,8,32,-2146435072);
INSERT OR REPLACE INTO "texts" VALUES (53982768, 'Dark Ruler Ha Des', 'Cannot be Special Summoned from the Graveyard. Negate the effects of monsters destroyed by battle with Fiend-Type monsters you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14531242,3,0,0,17,1800,1700,4,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (14531242, 'Opticlops', 'A one-eyed giant that serves the "Dark Ruler Ha Des", it skewers its enemies with its sharp horn, shattering them to pieces.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49681811,3,0,0,33,2300,1700,5,1,1,-2146434560);
INSERT OR REPLACE INTO "texts" VALUES (49681811, 'Freed the Matchless General', 'Negate any Spell effects that target this card, and if you do, destroy that Spell Card. During your Draw Phase, instead of conducting your normal draw: You can add 1 Level 4 or lower Warrior-Type monster from your Deck to your hand. This card must be face-up on the field to activate and to resolve this effect.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53046408,3,0,0,65538,0,0,0,0,0,8388616);
INSERT OR REPLACE INTO "texts" VALUES (53046408, 'Emergency Provisions', 'Send any number of other Spell and Trap Cards you control to the Graveyard. Gain 1000 Life Points for each card sent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94568601,3,0,0,33,2900,2500,8,8192,4,32768);
INSERT OR REPLACE INTO "texts" VALUES (94568601, 'Tyrant Dragon', 'During your Battle Phase, if your opponent controls a monster after this card''s first attack, this card can make a second attack. Negate any Trap effects that target this card, and if you do, destroy that Trap Card. This card cannot be Special Summoned from the Graveyard, unless you Tribute 1 Dragon-Type monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31553716,3,0,0,33,1900,0,4,8192,8,18432);
INSERT OR REPLACE INTO "texts" VALUES (31553716, 'Spear Dragon', 'During battle between this attacking card and a Defense Position monster whose DEF is lower than the ATK of this card, inflict the difference as Battle Damage to your opponent. If this card attacks, it is changed to Defense Position at the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18036057,3,0,0,33,1900,1400,5,4,16,16640);
INSERT OR REPLACE INTO "texts" VALUES (18036057, 'Airknight Parshath', 'If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. When this card inflicts battle damage to your opponent: Draw 1 card.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76862289,3,0,0,545,2600,3100,7,8192,4,272);
INSERT OR REPLACE INTO "texts" VALUES (76862289, 'Yamata Dragon', 'This card cannot be Special Summoned. This card returns to its owner''s hand during the End Phase of the turn it is Normal Summoned or flipped face-up. When this card inflicts Battle Damage to your opponent, draw cards until you have 5 cards in your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75745607,3,0,0,545,2800,2900,8,128,4,80);
INSERT OR REPLACE INTO "texts" VALUES (75745607, 'Hino-Kagu-Tsuchi', 'This card cannot be Special Summoned. This card returns to its owner''s hand during the End Phase of the turn it is Normal Summoned or flipped face-up. If this card inflicts Battle Damage to your opponent, they discard all cards in their hand during the next Draw Phase, before they draw.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2134346,3,0,0,545,1700,1200,4,4,16,32800);
INSERT OR REPLACE INTO "texts" VALUES (2134346, 'Asura Priest', 'Cannot be Special Summoned. During the End Phase of the turn this card is Normal Summoned or flipped face-up: Return it to the hand. This card can attack all monsters your opponent controls once each.', 'Spirit', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (295517,3,22702055,0,524290,0,0,0,0,0,2105344);
INSERT OR REPLACE INTO "texts" VALUES (295517, 'A Legendary Ocean', 'This card''s name is treated as "Umi". Reduce the Level of all WATER monsters in both player''s hands and on the field by 1. All WATER monsters gain 200 ATK and DEF.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31036355,3,0,0,2,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (31036355, 'Creature Swap', 'Each player chooses 1 monster they control and switches control of those monsters with each other. Those monsters cannot change their battle positions for the rest of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29401950,3,0,8978508,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (29401950, 'Bottomless Trap Hole', 'When your opponent Summons a monster(s) with 1500 or more ATK: Destroy that monster(s) with 1500 or more ATK, and if you do, banish it instead of sending it to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79575620,3,0,0,33,400,1500,3,2,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (79575620, 'Injection Fairy Lily', 'If this card attacks or is attacked, during damage calculation (in either player''s turn): You can pay 2000 Life Points once per battle; this card gains 3000 ATK during that damage calculation only.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83555666,3,0,0,4,0,0,0,0,0,4194306);
INSERT OR REPLACE INTO "texts" VALUES (83555666, 'Ring of Destruction', 'You can only activate 1 “Ring of Destruction” per turn. During your opponent’s turn: Target 1 face-up monster your opponent controls whose ATK is lower than or equal to your opponent’s LP; destroy that face-up monster, and if you do, you take damage equal to that monster’s original ATK, then, inflict damage to your opponent equal to the damage you took.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40659562,3,0,5374044,33,1700,2400,5,256,1,2064);
INSERT OR REPLACE INTO "texts" VALUES (40659562, 'Guardian Sphinx', 'Once per turn: You can change this card to face-down Defense Position. When this card is Flip Summoned: Return all monsters your opponent controls to the hand.', '变成里侧守备表示', '对方场上的全部怪兽返回手牌', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76922029,3,0,0,33,1400,1500,4,1,32,200);
INSERT OR REPLACE INTO "texts" VALUES (76922029, 'Don Zaloog', 'When this card inflicts Battle Damage to your opponent, you can either:
● Discard 1 random card from your opponent''s hand. OR
● Send the top 2 cards of your opponent''s Deck to the Graveyard.', 'Select effect', 'Discard 1 random card from your opponent''s hand.', 'Send the top 2 cards of your opponent''s Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38699854,3,0,0,2,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (38699854, 'Book of Taiyou', 'Flip 1 face-down monster on the field into face-up Attack Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14087893,3,0,0,65538,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (14087893, 'Book of Moon', 'Target 1 face-up monster on the field; change that target to face-down Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37576645,3,0,0,4,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (37576645, 'Reckless Greed', 'Draw 2 cards and skip your next 2 Draw Phases.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90980792,3,0,22,33,1200,1500,4,8,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (90980792, 'Dark Jeroid', 'When this card is Summoned: Target 1 face-up monster on the field; it loses 800 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4335645,3,0,0,33,1200,800,4,8,32,2);
INSERT OR REPLACE INTO "texts" VALUES (4335645, 'Newdoria', 'When this card is destroyed by battle and sent to the Graveyard: Target 1 monster on the field; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76052811,3,0,0,33,2000,1400,5,8,32,64);
INSERT OR REPLACE INTO "texts" VALUES (76052811, 'Helpoemer', 'Cannot be Special Summoned from the Graveyard. If this card was destroyed by battle and sent to the Graveyard, this effect activates at the end of each of your opponent''s Battle Phases: Discard 1 random card from your opponent''s hand. This card must be in the Graveyard to activate and to resolve this effect', '戦闘によって破壊され墓地に送られた場合効果が発動', 'カードを捨てる', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24317029,3,0,46,2097185,1200,2000,4,2,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (24317029, 'Gravekeeper''s Spy', 'FLIP: Special Summon 1 "Gravekeeper''s" monster with 1500 or less ATK from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62473983,3,0,46,33,1900,1200,5,2,32,33816576);
INSERT OR REPLACE INTO "texts" VALUES (62473983, 'Gravekeeper''s Chief', 'You can only control 1 "Gravekeeper''s Chief". Cards in your Graveyard are unaffected by "Necrovalley". When this card is Tribute Summoned, you can select 1 "Gravekeeper''s" monster from your Graveyard and Special Summon it.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25262697,3,0,46,33,1500,1500,4,2,32,2048);
INSERT OR REPLACE INTO "texts" VALUES (25262697, 'Gravekeeper''s Assailant', 'If "Necrovalley" is on the field when this card declares an attack, you can select 1 face-up monster your opponent controls and change its battle position.', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85562745,3,0,0,131074,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (85562745, 'Dark Room of Nightmare', 'Each time your opponent takes damage from a card effect, except "Dark Room of Nightmare", inflict 300 damage to your opponent.', '给对方300伤害', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47355498,3,0,145,524290,0,0,0,0,0,-2147475456);
INSERT OR REPLACE INTO "texts" VALUES (47355498, 'Necrovalley', 'All "Gravekeeper''s" monsters gain 500 ATK and DEF. Cards in either player''s Graveyard cannot be banished. Negate any card effect that would move a card in the Graveyard, other than itself, to a different place.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78783370,3,0,0,1048580,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (78783370, 'Barrel Behind the Door', 'Activate only when a card''s effect that would inflict damage to you is activated. Your opponent takes the damage instead.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54704216,3,0,0,131076,0,0,0,0,0,4259840);
INSERT OR REPLACE INTO "texts" VALUES (54704216, 'Nightmare Wheel', 'Activate this card by targeting 1 monster your opponent controls; it cannot attack or change its battle position. When it leaves the field, destroy this card. During each of your Standby Phases: Inflict 500 damage to your opponent. That monster must be on the field to activate and to resolve this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (102380,3,0,0,33,3000,2500,8,8,4,4456448);
INSERT OR REPLACE INTO "texts" VALUES (102380, 'Lava Golem', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) to your opponent''s side of the field by Tributing 2 monsters they control. You cannot Normal Summon/Set the turn you Special Summon this card. During each of the controller''s Standby Phases: The controller takes 1000 damage.', 'Special Summon', '1000 damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33508719,3,0,0,2097185,700,600,2,256,1,264);
INSERT OR REPLACE INTO "texts" VALUES (33508719, 'Morphing Jar', 'FLIP: Both players discard all the cards in their hands, then draw 5 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51452091,3,0,0,131076,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (51452091, 'Royal Decree', 'Negate the effects of all other Trap Cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16589042,3,0,189,33,2300,2100,7,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (16589042, 'Swift Gaia the Fierce Knight', 'If this is the only card in your hand, you can Normal Summon it without Tributing.', 'リリースなしで召喚', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52077741,3,0,0,33,1400,1200,4,1,1,16777216);
INSERT OR REPLACE INTO "texts" VALUES (52077741, 'Obnoxious Celtic Guard', 'This card cannot be destroyed by battle with a monster that has 1900 or more ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17444133,3,0,0,33,1700,1650,4,262144,16,2097152);
INSERT OR REPLACE INTO "texts" VALUES (17444133, 'Kaiser Sea Horse', 'This card can be treated as 2 Tributes for the Tribute Summon of a LIGHT monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91512835,3,0,0,33,2200,2400,7,2048,1,794624);
INSERT OR REPLACE INTO "texts" VALUES (91512835, 'Insect Queen', 'This card cannot declare an attack unless you Tribute 1 monster. This card gains 200 ATK for each Insect-Type monster on the field. During the End Phase, if this card destroyed an opponent''s monster by battle this turn: Special Summon 1 "Insect Monster Token" (Insect-Type/EARTH/Level 1/ATK 100/DEF 100) in Attack Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99785935,3,0,0,17,1400,1700,4,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (99785935, 'Alpha the Magnet Warrior', 'Alpha, Beta, and Gamma meld as one to form a powerful monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39256679,3,0,0,17,1700,1600,4,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (39256679, 'Beta the Magnet Warrior', 'Alpha, Beta, and Gamma meld as one to form a powerful monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11549357,3,0,0,17,1500,1800,4,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (11549357, 'Gamma the Magnet Warrior', 'Alpha, Beta, and Gamma meld as one to form a powerful monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75347539,3,0,0,33,3500,3850,8,256,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (75347539, 'Valkyrion the Magna Warrior', 'This card cannot be Normal Summoned or Set. This card can only be Special Summoned by Tributing "Alpha The Magnet Warrior", "Beta The Magnet Warrior", and "Gamma The Magnet Warrior" from your hand or your side of the field. You can Tribute this card to Special Summon "Alpha The Magnet Warrior", "Beta The Magnet Warrior", and "Gamma The Magnet Warrior" from your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52040216,3,0,100,33,2000,2500,7,8192,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (52040216, 'Harpie''s Pet Dragon', 'This card gains 300 ATK and DEF for each "Harpie Lady" on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50287060,3,0,69,33,2200,2500,6,8,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (50287060, 'Archfiend of Gilfer', 'When this card is sent to the Graveyard: You can target 1 face-up monster on the field; equip that target with this card. That monster loses 500 ATK while equipped with this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47297616,3,0,0,33,2800,2400,8,8192,16,-2145116157);
INSERT OR REPLACE INTO "texts" VALUES (47297616, 'Light and Darkness Dragon', 'Cannot be Special Summoned. While face-up on the field, this card is also DARK-Attribute. Once per Chain, during either player''s turn, when a Spell Card, Trap Card, or monster effect is activated: This card loses exactly 500 ATK and DEF and that activation is negated. When this card is destroyed and sent to the Graveyard: Target 1 monster in your Graveyard (if possible); destroy all cards you control, also Special Summon that monster (if any).', 'Cannot be Special Summoned', 'Attribute is also treated as DARK', 'Negate effect', 'Los 500 ATK', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53347303,3,0,0,33,3000,2500,10,8192,16,-2147213304);
INSERT OR REPLACE INTO "texts" VALUES (53347303, 'Blue-Eyes Shining Dragon', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by Tributing 1 "Blue-Eyes Ultimate Dragon" you control. This card gains 300 ATK for each Dragon-Type monster in your Graveyard. You can negate the effects of Spells, Traps, and Effect Monsters that target this card.', 'Negate the effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62873545,3,0,0,97,5000,5000,12,8192,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (62873545, 'Dragon Master Knight', '"Black Luster Soldier" + "Blue-Eyes Ultimate Dragon"
This monster cannot be Special Summoned except by Fusion Summon. This card gains 500 ATK for each other Dragon-Type monster you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44910027,3,0,0,33,2400,3000,8,8192,32,0);
INSERT OR REPLACE INTO "texts" VALUES (44910027, 'Victory Dragon', 'This card cannot be Special Summoned. To Tribute Summon this card, you must Tribute 3 Dragon-Type monsters. If this card attacks your opponent directly and reduces their Life Points to 0, you win the Match.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46668237,3,0,0,33,2600,1800,7,16384,1,1310720);
INSERT OR REPLACE INTO "texts" VALUES (46668237, 'Green Baboon, Defender of the Forest', 'When a Beast-Type monster you control is destroyed and sent to the Graveyard, you can pay 1000 Life Points to Special Summon this card from your hand or the Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66973070,3,0,0,33,2300,1600,8,2048,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (66973070, 'Dreadscythe Harvester', 'You can Tribute 1 Insect-Type monster to have this card gain 500 ATK until the end of the turn.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
