BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (69933858,3,0,0,33,2600,2000,8,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (69933858, 'Gilford the Legend', 'Cannot be Special Summoned. When this card is Normal Summoned: You can equip as many Equip Spell Cards from your Graveyard as possible to a Warrior-Type monster(s) you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5438492,3,0,0,33,1100,1200,4,1,1,3408384);
INSERT OR REPLACE INTO "texts" VALUES (5438492, 'Warrior Lady of the Wasteland', 'When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 EARTH Warrior-Type monster with 1500 or less ATK from your Deck, in face-up Attack Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11321183,3,0,0,17,1800,1500,4,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (11321183, 'Dark Blade', 'They say he is a dragon-manipulating warrior from the dark world. His attack is tremendous, using his great swords with vicious power.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78658564,3,0,172,33,2300,0,4,1,1,2048);
INSERT OR REPLACE INTO "texts" VALUES (78658564, 'Goblin Attack Force', 'If this card attacks, it is changed to Defense Position at the end of the Battle Phase, and its battle position cannot be changed until the End Phase of your next turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (423705,3,0,0,33,1800,1600,4,1,1,1);
INSERT OR REPLACE INTO "texts" VALUES (423705, 'Gearfried the Iron Knight', 'When an Equip Card(s) is equipped to this card: Destroy the Equip Card(s).', 'Destroy equipped card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16589042,3,0,189,33,2300,2100,7,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (16589042, 'Swift Gaia the Fierce Knight', 'If this is the only card in your hand, you can Normal Summon it without Tributing.', 'リリースなしで召喚', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52077741,3,0,0,33,1400,1200,4,1,1,16777216);
INSERT OR REPLACE INTO "texts" VALUES (52077741, 'Obnoxious Celtic Guard', 'This card cannot be destroyed by battle with a monster that has 1900 or more ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10375182,3,0,0,33,1200,1900,4,1,4,73728);
INSERT OR REPLACE INTO "texts" VALUES (10375182, 'Command Knight', 'While at least 1 other monster exists on your side of the field, your opponent cannot select this card as an attack target. Also, while this card remains face-up on the field, increase the ATK of all your Warrior-Type monsters by 400 points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2460565,3,0,0,33,1200,400,3,1,1,1376256);
INSERT OR REPLACE INTO "texts" VALUES (2460565, 'Marauding Captain', 'Your opponent cannot target face-up Warrior-Type monsters for attacks, except this one. When this card is Normal Summoned: You can Special Summon 1 Level 4 or lower monster from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74131780,3,0,0,33,1000,1000,4,1,1,10);
INSERT OR REPLACE INTO "texts" VALUES (74131780, 'Exiled Force', 'You can Tribute this card to target 1 monster on the field; destroy that target.', '破坏场上的1只怪兽', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7572887,3,0,0,33,1500,1600,4,1,16,4);
INSERT OR REPLACE INTO "texts" VALUES (7572887, 'D.D. Warrior Lady', 'After damage calculation, when this card battles an opponent''s monster: You can banish that monster, also banish this card.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22609617,3,0,0,33,1300,800,3,1,32,36864);
INSERT OR REPLACE INTO "texts" VALUES (22609617, 'Mataza the Zapper', 'This card can make a second attack during each Battle Phase. Control of this face-up card on the field cannot switch.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47507260,3,0,65,33,900,0,2,1,1,262154);
INSERT OR REPLACE INTO "texts" VALUES (47507260, 'Mystic Swordsman LV2', 'If this card attacks a face-down Defense Position monster, destroy the monster immediately with this card''s effect without flipping it face-up or applying damage calculation. During the End Phase of a turn that this card destroyed a monster by battle, by sending this card to the Graveyard, Special Summon 1 "Mystic Swordsman LV4" from your hand or Deck.', 'Destroy', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74591968,3,0,65,33,1900,1600,4,1,1,262146);
INSERT OR REPLACE INTO "texts" VALUES (74591968, 'Mystic Swordsman LV4', 'If you Normal Summon this card, you must place it in face-down Defense Position. If this card attacks a face-down Defense Position monster, destroy the monster immediately with this card''s effect without flipping it face-up or applying damage calculation. During the End Phase of a turn that this card destroyed a monster by battle, by sending this card to the Graveyard, Special Summon 1 "Mystic Swordsman LV6" from your hand or Deck.', 'Destroy', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4041838,3,0,43,33,1800,1000,4,1,16,2);
INSERT OR REPLACE INTO "texts" VALUES (4041838, 'Ninja Grandmaster Sasuke', 'At the start of the Damage Step, if this card attacks a face-up Defense Position monster: Destroy that monster.', 'Destroy Defense Position monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57046845,3,0,0,33,2600,2200,7,1,16,2);
INSERT OR REPLACE INTO "texts" VALUES (57046845, 'Gearfried the Swordmaster', 'Cannot be Normal Summoned/Set. Must be Special Summoned with "Release Restraint" and cannot be Special Summoned by other ways. When an Equip Card(s) is equipped to this card: Target 1 monster your opponent controls; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84430950,3,0,0,33,500,800,4,1,32,32768);
INSERT OR REPLACE INTO "texts" VALUES (84430950, 'Armed Samurai - Ben Kei', 'In addition to a normal attack, this card can attack during the same Battle Phase as many times as the number of Equip Cards equipped to it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31423101,3,0,0,262146,0,0,0,0,0,9220);
INSERT OR REPLACE INTO "texts" VALUES (31423101, 'Divine Sword - Phoenix Blade', 'Equip only to a Warrior-Type monster. It gains 300 ATK. During your Main Phase, if this card is in your Graveyard you can remove from play 2 Warrior-Type monsters in your Graveyard to add this card to your hand.', '这张卡加入手牌', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45986603,3,0,0,262146,0,0,0,0,0,8392704);
INSERT OR REPLACE INTO "texts" VALUES (45986603, 'Snatch Steal', 'Take control of a monster on your opponent''s side of the field that is equipped with this card. Increase your opponent''s Life Points by 1000 points during each of their Standby Phases.', '对方回复1000LP', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5318639,3,0,0,65538,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (5318639, 'Mystical Space Typhoon', 'Target 1 Spell/Trap Card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42703248,3,0,0,2,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (42703248, 'Giant Trunade', 'Return all Spell and Trap Cards on the field to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55226821,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (55226821, 'Lightning Blade', 'Equip only to a Warrior-Type monster. It gains 800 ATK. All WATER monsters lose 500 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19613556,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (19613556, 'Heavy Storm', 'Destroy all Spell and Trap Cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32807846,3,0,0,2,0,0,0,0,0,1049088);
INSERT OR REPLACE INTO "texts" VALUES (32807846, 'Reinforcement of the Army', 'Add 1 Level 4 or lower Warrior-Type monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95281259,3,0,0,2,0,0,0,0,0,1049600);
INSERT OR REPLACE INTO "texts" VALUES (95281259, 'The Warrior Returning Alive', 'Target 1 Warrior-Type monster in your Graveyard; add that target to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37684215,3,0,70,262146,0,0,0,0,0,16785408);
INSERT OR REPLACE INTO "texts" VALUES (37684215, 'Fusion Sword Murasame Blade', 'Equip only to a Warrior-Type monster. It gains 800 ATK. While equipped to a monster, this card cannot be destroyed by card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68427465,3,0,0,262146,0,0,0,0,0,-2147475456);
INSERT OR REPLACE INTO "texts" VALUES (68427465, 'Wicked-Breaking Flamberge - Baou', 'Send 1 card from your hand to the Graveyard to equip this card. Increase the ATK of the equipped monster by 500 points. If a monster equipped with this card destroys a monster as a result of battle, the effect of that monster is negated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20188127,3,0,0,2,0,0,0,0,0,1040);
INSERT OR REPLACE INTO "texts" VALUES (20188127, 'Fairy of the Spring', 'Add 1 Equip Spell Card from your Graveyard to your hand. You cannot activate that Equip Spell Card this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22589918,3,0,0,65538,0,0,0,0,0,288);
INSERT OR REPLACE INTO "texts" VALUES (22589918, 'Reload', 'Add all the cards in your hand to your Deck and shuffle it. Then draw the same number of cards that you added to your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69162969,3,0,0,2,0,0,0,0,0,10);
INSERT OR REPLACE INTO "texts" VALUES (69162969, 'Lightning Vortex', 'Discard 1 card; destroy all face-up monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12923641,3,0,0,131074,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (12923641, 'Swords of Concealing Light', 'When this card resolves, all monsters your opponent controlled when this card was activated are changed to face-down Defense Position. Monsters your opponent controls cannot change their battle positions. Destroy this card during your 2nd Standby Phase after activation.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75417459,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (75417459, 'Release Restraint', 'Tribute 1 "Gearfried the Iron Knight"; Special Summon 1 "Gearfried the Swordmaster" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97077563,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (97077563, 'Call of the Haunted', 'Activate this card by targeting 1 monster in your Graveyard; Special Summon that target in Attack Position. When this card leaves the field, destroy that target. When that target is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77414722,3,0,0,1048580,0,0,0,0,0,-2147483639);
INSERT OR REPLACE INTO "texts" VALUES (77414722, 'Magic Jammer', 'When a Spell Card is activated: Discard 1 card; negate the activation, and if you do, destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51452091,3,0,0,131076,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (51452091, 'Royal Decree', 'Negate the effects of all other Trap Cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98239899,3,0,0,4,0,0,0,0,0,8195);
INSERT OR REPLACE INTO "texts" VALUES (98239899, 'Blast with Chain', 'Target 1 face-up monster you control; equip this card to that target. It gains 500 ATK. When this card is destroyed by a card effect while equipped: Target 1 card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
