BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (29436665,3,0,0,33,2500,2100,7,2,32,4456448);
INSERT OR REPLACE INTO "texts" VALUES (29436665, 'Dark Eradicator Warlock', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by Tributing 1 "Dark Magician". Each time a Normal Spell Card is activated, inflict 1000 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55424270,3,0,110,33,1400,1400,4,2,16,67117056);
INSERT OR REPLACE INTO "texts" VALUES (55424270, 'Mythical Beast Cerberus', 'Each time a Spell Card is activated, place 1 Spell Counter on this card when that Spell Card resolves. This card gains 500 ATK for each Spell Counter on it. If damage calculation is conducted involving this card, remove all Spell Counters from it at the end of the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46986414,3,0,162,17,2500,2100,7,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (46986414, 'Dark Magician', 'The ultimate wizard in terms of attack and defense.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69140098,3,0,0,17,1900,900,4,2,1,0);
INSERT OR REPLACE INTO "texts" VALUES (69140098, 'Gemini Elf', 'Elf twins that alternate their attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31560081,3,0,0,2097185,300,400,1,2,16,1024);
INSERT OR REPLACE INTO "texts" VALUES (31560081, 'Magician of Faith', 'FLIP: Target 1 Spell Card in your Graveyard; add that target to your hand.', 'Spell recovery', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73752131,3,0,0,33,1900,1700,4,2,32,67371016);
INSERT OR REPLACE INTO "texts" VALUES (73752131, 'Skilled Dark Magician', 'Each time a Spell Card is activated, place 1 Spell Counter on this card when that Spell Card resolves (max. 3). You can Tribute this card with 3 Spell Counters on it; Special Summon 1 "Dark Magician" from your hand, Deck, or Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9156135,3,0,0,33,400,800,2,2,32,68420096);
INSERT OR REPLACE INTO "texts" VALUES (9156135, 'Apprentice Magician', 'When this card is Summoned, place 1 Spell Counter on a face-up card that you can place a Spell Counter on. When this card is destroyed by battle, you can Special Summon 1 Level 2 or lower Spellcaster-Type monster from your Deck in face-down Defense Position.', 'Place spell counter', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72630549,3,0,0,33,2400,1900,6,2,16,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (72630549, 'Chaos Command Magician', 'Negate the effect of a Monster Card that targets this 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71413901,3,0,110,33,1600,1000,4,2,32,67117057);
INSERT OR REPLACE INTO "texts" VALUES (71413901, 'Breaker the Magical Warrior', 'If this card is Normal Summoned: Place 1 Spell Counter on it (max. 1). This card gains 300 ATK for each Spell Counter on it. You can remove 1 Spell Counter from this card, then target 1 Spell/Trap Card on the field; destroy that target.', 'Place spell counter', 'Gain attack', 'Destroy 1 Spell or Trap Card', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70791313,3,0,0,33,0,2000,4,2,16,67109120);
INSERT OR REPLACE INTO "texts" VALUES (70791313, 'Royal Magical Library', 'Each time a Spell Card is activated, place 1 Spell Counter on this card (max 3). You can remove 3 Spell Counters from this card to draw 1 card.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34853266,3,0,0,545,1100,1400,4,2,32,2064);
INSERT OR REPLACE INTO "texts" VALUES (34853266, 'Tsukuyomi', 'This card cannot be Special Summoned. This card returns to the owner''s hand during the End Phase of the turn it is Normal Summoned or flipped face-up. When this card is Normal Summoned or flipped face-up, flip 1 face-up monster on the field into face-down Defense Position.', 'Spirit', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9596126,3,0,0,33,2300,2000,6,2,32,1310724);
INSERT OR REPLACE INTO "texts" VALUES (9596126, 'Chaos Sorcerer', 'Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your Graveyard. Once per turn: You can target 1 face-up monster on the field; banish that target. This card cannot attack the turn you activate this effect.', 'Special Summon', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81383947,3,0,110,33,1200,0,2,2,16,8388608);
INSERT OR REPLACE INTO "texts" VALUES (81383947, 'White Magician Pikeru', 'During your Standby Phase, increase your Life Points by 400 points for each monster on your side of the field.', 'LP Recovery', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21051146,3,0,0,33,1400,1700,4,2,4,67108866);
INSERT OR REPLACE INTO "texts" VALUES (21051146, 'Blast Magician', 'Each time a Spell Card is activated, place 1 Spell Counter on this card. You can remove any number of Spell Counters from this card to destroy 1 face-up monster on the field with ATK equal to or less than 700 x the number of counters you removed.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46128076,3,0,110,33,1200,0,2,2,32,4194304);
INSERT OR REPLACE INTO "texts" VALUES (46128076, 'Ebon Magician Curran', 'During your Standby Phase, inflict 300 damage to your opponent for each monster they control.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6337436,3,0,0,33,1600,1200,4,2,32,4194304);
INSERT OR REPLACE INTO "texts" VALUES (6337436, 'Rapid-Fire Magician', 'Inflict 400 damage to your opponent each time you activate a Normal Spell Card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91819979,3,0,0,2,0,0,0,0,0,4194320);
INSERT OR REPLACE INTO "texts" VALUES (91819979, 'Magical Blast', 'Activate only while you control a Spellcaster-Type monster. Inflict 200 damage to your opponent for each Spellcaster-Type monster you control. If this card is in your Graveyard, you can add it to your hand instead of conducting your normal draw during your Draw Phase.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5318639,3,0,0,65538,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (5318639, 'Mystical Space Typhoon', 'Target 1 Spell/Trap Card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71044499,3,0,0,2,0,0,0,0,0,6);
INSERT OR REPLACE INTO "texts" VALUES (71044499, 'Nobleman of Crossout', 'Target 1 face-down monster on the field; destroy that target, and if you do, banish it, then, if it was a Flip monster, each player reveals their Main Deck, then banishes all cards from it with that monster''s name.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70828912,3,0,0,262146,0,0,0,0,0,262146);
INSERT OR REPLACE INTO "texts" VALUES (70828912, 'Premature Burial', 'Activate this card by paying 800 LP, then target 1 monster in your Graveyard; Special Summon that target in face-up Attack Position and equip it with this card. When this card is destroyed, destroy the equipped monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72302403,3,0,0,2,0,0,0,0,0,67584);
INSERT OR REPLACE INTO "texts" VALUES (72302403, 'Swords of Revealing Light', 'Flip all monsters your opponent controls face-up. This card remains on the field for 3 of your opponent''s turns. While this card is face-up on the field, monsters your opponent controls cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83746708,3,0,110,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (83746708, 'Mage Power', 'The equipped monster gains 500 ATK and DEF for each Spell and Trap Card you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19613556,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (19613556, 'Heavy Storm', 'Destroy all Spell and Trap Cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87880531,3,0,0,2,0,0,0,0,0,32768);
INSERT OR REPLACE INTO "texts" VALUES (87880531, 'Diffusion Wave-Motion', 'Pay 1000 Life Points. Select 1 Level 7 or higher Spellcaster-Type monster on your side of the field. During this turn, only the selected monster can attack and it attacks all monsters on your opponent''s side of the field once each. The effects of Effect Monsters destroyed by this attack(s) are not activated.', '相手モンスター全てに１回ずつ攻撃', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22589918,3,0,0,65538,0,0,0,0,0,288);
INSERT OR REPLACE INTO "texts" VALUES (22589918, 'Reload', 'Add all the cards in your hand to your Deck and shuffle it. Then draw the same number of cards that you added to your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2314238,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (2314238, 'Dark Magic Attack', 'If you control a "Dark Magician": Destroy all Spell and Trap Cards your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51481927,3,0,0,131074,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (51481927, 'Spell Absorption', 'Each time a Spell Card is activated, gain 500 Life Points immediately after it resolves.', '恢复LP', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69162969,3,0,0,2,0,0,0,0,0,10);
INSERT OR REPLACE INTO "texts" VALUES (69162969, 'Lightning Vortex', 'Discard 1 card; destroy all face-up monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28553439,3,0,0,65538,0,0,0,0,0,1310722);
INSERT OR REPLACE INTO "texts" VALUES (28553439, 'Magical Dimension', 'If you control a face-up Spellcaster-Type monster: Target 1 monster you control; Tribute it, then Special Summon 1 Spellcaster-Type monster from your hand, then you can destroy 1 monster on the field.', 'Destroy 1 monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25774450,3,0,0,2,0,0,0,0,0,4098);
INSERT OR REPLACE INTO "texts" VALUES (25774450, 'Mystic Box', 'Target 1 monster your opponent controls and 1 monster you control; destroy the first target, then give control of the second target to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58775978,3,0,0,2,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (58775978, 'Nightmare''s Steelcage', 'This card remains on the field for 2 of your opponent''s turns. While this card is face-up on the field, no monsters can attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97077563,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (97077563, 'Call of the Haunted', 'Activate this card by targeting 1 monster in your Graveyard; Special Summon that target in Attack Position. When this card leaves the field, destroy that target. When that target is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38275183,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (38275183, 'Spell Shield Type-8', 'Activate 1 of these effects.
● When a Spell Card is activated that targets exactly 1 monster on the field: Negate the activation, and if you do, destroy it.
● When a Spell Card is activated: Send 1 Spell Card from your hand to the Graveyard; negate the activation, and if you do, destroy it.
', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34029630,3,0,0,131076,0,0,0,0,0,67108864);
INSERT OR REPLACE INTO "texts" VALUES (34029630, 'Pitch-Black Power Stone', 'After activation, place 3 Spell Counters on this card. During each of your turns you can move 1 Spell Counter from this card to another face-up card that you can place a Spell Counter on. When there are no Spell Counters on this card, destroy it.', 'Remove Spell Counter?', 'Place counter', '魔力カウンターを置くカード', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49010598,3,0,0,1048580,0,0,0,0,0,-2147483638);
INSERT OR REPLACE INTO "texts" VALUES (49010598, 'Divine Wrath', 'When a monster effect is activated: Discard 1 card; negate the activation, and if you do, destroy that monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62279055,3,0,0,4,0,0,0,0,0,4259840);
INSERT OR REPLACE INTO "texts" VALUES (62279055, 'Magic Cylinder', 'When an opponent''s monster declares an attack: Target the attacking monster; negate the attack, and if you do, inflict damage to your opponent equal to its ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
