BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (85520851,3,0,0,33,3300,1400,8,65536,16,4194304);
INSERT OR REPLACE INTO "texts" VALUES (85520851, 'Super Conductor Tyranno', 'Once per turn: You can Tribute 1 monster; inflict 1000 damage to your opponent. This card cannot declare an attack the turn you activate this effect.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51934376,3,0,0,17,1700,1500,4,65536,2,0);
INSERT OR REPLACE INTO "texts" VALUES (51934376, 'Kabazauls', 'A huge monster in the shape of a hippopotamus. The sneezing from his gigantic body is so fierce that people mistake it for a hurricane.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37265642,3,0,13,17,1900,500,4,65536,1,0);
INSERT OR REPLACE INTO "texts" VALUES (37265642, 'Sabersaurus', 'This normally gentle dinosaur enjoys relaxing in its nest in the prairies. If it becomes angered, it turns terribly ferocious.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79870141,3,0,0,33,1400,1200,4,65536,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (79870141, 'Mad Sword Beast', ' If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45894482,3,0,0,33,1400,400,3,65536,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (45894482, 'Gilasaurus', 'You can Special Summon this card (from your hand). When you do: Your opponent can target 1 monster in their Graveyard; your opponent Special Summons that target to their side of the field.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65287621,3,0,0,33,2400,1500,6,65536,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (65287621, 'Dark Driceratops', 'If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2671330,3,0,0,33,1500,1200,4,65536,1,16);
INSERT OR REPLACE INTO "texts" VALUES (2671330, 'Hyper Hammerhead', 'At the end of the Damage Step, if an opponent''s monster that battled this card is not destroyed: Return that opponent''s monster to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38670435,3,0,0,33,2600,1800,7,65536,1,131072);
INSERT OR REPLACE INTO "texts" VALUES (38670435, 'Black Tyranno', 'If the only cards your opponent controls are Defense Position monsters, this card can attack your opponent directly.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83235263,3,0,0,33,-2,0,4,65536,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (83235263, 'Tyranno Infinity', 'The original ATK of this card is the number of your banished Dinosaur-Type monsters x 1000.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22587018,3,0,0,33,1600,1000,4,65536,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (22587018, 'Hydrogeddon', 'When this card destroys a monster your opponent controls by battle and sends it to the Graveyard: You can Special Summon 1 "Hydrogeddon" from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58071123,3,0,0,33,1800,800,4,65536,8,4194304);
INSERT OR REPLACE INTO "texts" VALUES (58071123, 'Oxygeddon', 'When this card is destroyed by battle with a Pyro-Type monster and sent to the Graveyard, inflict 800 damage to both players.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90654356,3,0,0,33,1000,500,3,65536,8,16);
INSERT OR REPLACE INTO "texts" VALUES (90654356, 'Black Ptera', 'When this card is sent from the field to the Graveyard, except by being destroyed by battle: Return it to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79409334,3,0,0,33,1200,2000,4,65536,1,2048);
INSERT OR REPLACE INTO "texts" VALUES (79409334, 'Black Stego', 'If this face-up Attack Position card is targeted for an attack: Change this card to Defense Position.', 'Change to defense position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15894048,3,0,0,33,3000,2200,8,65536,1,0);
INSERT OR REPLACE INTO "texts" VALUES (15894048, 'Ultimate Tyranno', 'If this card is in face-up Attack Position at the beginning of your Battle Phase, it must attack first, and attack all monsters your opponent controls once each.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63259351,3,0,0,33,0,2000,4,65536,1,68419584);
INSERT OR REPLACE INTO "texts" VALUES (63259351, 'Miracle Jurassic Egg', 'While face-up on the field, this card cannot be banished. Each time a Dinosaur-Type monster(s) is sent to your Graveyard, place 2 counters on this card. You can Tribute this card; Special Summon 1 Dinosaur-Type monster from your Deck whose Level is less than or equal to the number of counters that were on this card.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36042004,3,0,0,33,500,500,2,65536,1,1310720);
INSERT OR REPLACE INTO "texts" VALUES (36042004, 'Babycerasaurus', 'When this card is destroyed by a card effect and sent to the Graveyard: Special Summon 1 Level 4 or lower Dinosaur-Type monster from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84808313,3,0,0,2,0,0,0,0,0,1048576);
INSERT OR REPLACE INTO "texts" VALUES (84808313, 'Big Evolution Pill', 'Tribute 1 Dinosaur-Type monster; while this card is face-up on the field, you can Normal Summon Dinosaur-Type monsters without Tributing. This card remains on the field for 3 of your opponent''s turns.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83682725,3,0,0,2,0,0,0,0,0,1048592);
INSERT OR REPLACE INTO "texts" VALUES (83682725, 'Tail Swipe', 'Target 1 Level 5 or higher Dinosaur-Type monster you control; if that Dinosaur-Type monster is still face-up on the field, choose up to 2 monsters your opponent controls that have a lower Level than it, or are face-down, and return them to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10080320,3,0,0,524290,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (10080320, 'Jurassic World', 'All Dinosaur-Type monsters gain 300 ATK and DEF.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22537443,3,0,0,65538,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (22537443, 'Sebek''s Blessing', 'Activate only when a monster you control has attacked your opponent directly. Gain Life Points equal to the Battle Damage that the monster inflicted to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34016756,3,0,0,2,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (34016756, 'Riryoku', 'Target 2 face-up monsters on the field; halve the ATK of 1 monster, and if you do, add that lost ATK to the other monster. These effects last until the End Phase.', 'Select monster to halve the ATK', 'Select the monster to gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48642904,3,0,0,2,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (48642904, 'Mesmeric Control', 'During your opponent''s next turn after you activate this card, your opponent cannot change the battle positions of monsters, except with a card effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5318639,3,0,0,65538,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (5318639, 'Mystical Space Typhoon', 'Target 1 Spell/Trap Card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22046459,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (22046459, 'Megamorph', 'While your Life Points are lower than your opponent''s, the equipped monster''s ATK becomes double its original ATK. While your Life Points are higher, the equipped monster''s ATK becomes half its original ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19613556,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (19613556, 'Heavy Storm', 'Destroy all Spell and Trap Cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69162969,3,0,0,2,0,0,0,0,0,10);
INSERT OR REPLACE INTO "texts" VALUES (69162969, 'Lightning Vortex', 'Discard 1 card; destroy all face-up monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85852291,3,0,0,2,0,0,0,0,0,288);
INSERT OR REPLACE INTO "texts" VALUES (85852291, 'Magical Mallet', 'Shuffle any number of cards from your hand into the Deck, then draw that same number of cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11925569,3,0,0,4,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (11925569, 'Hunting Instinct', 'When a monster(s) is Special Summoned to your opponent''s side of the field: Special Summon 1 Dinosaur-Type monster from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58419204,3,0,0,4,0,0,0,0,0,9437184);
INSERT OR REPLACE INTO "texts" VALUES (58419204, 'Survival Instinct', 'Banish any number of Dinosaur-Type monsters from your Graveyard; gain 400 Life Points for each Dinosaur-Type monster banished to activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42175079,3,0,0,4,0,0,0,0,0,3);
INSERT OR REPLACE INTO "texts" VALUES (42175079, 'Volcanic Eruption', 'During your End Phase, if you control "Jurassic World": Destroy all cards on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79569173,3,0,0,131076,0,0,0,0,0,1049616);
INSERT OR REPLACE INTO "texts" VALUES (79569173, 'Seismic Shockwave', 'Activate this card when a face-up Dinosaur-Type monster you control is destroyed and sent to the Graveyard (except during the Damage Step): Choose 3 of your opponent''s unused Spell & Trap Card Zones. Those Card Zones cannot be used. Destroy this card during your 3rd Standby Phase after activation. If you do: You can target 1 Dinosaur-Type monster in your Graveyard; add that target to your hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96008713,3,0,0,4,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (96008713, 'Magical Arm Shield', 'When your opponent declares an attack while you control a monster: Target 1 face-up monster your opponent controls, except the attacking monster; take control of that target until the end of the Battle Phase, and if you do, it is attacked instead, and you proceed to damage calculation.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14315573,3,0,0,1048580,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (14315573, 'Negate Attack', 'Activate only when a target opponent''s monster declares an attack. Negate the attack and end the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69632396,3,0,172,1048580,0,0,0,0,0,-2147483632);
INSERT OR REPLACE INTO "texts" VALUES (69632396, 'Goblin Out of the Frying Pan', 'Pay 500 Life Points. Negate the activation of a Spell Card and return it to the owner''s hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6137095,3,0,0,1048580,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (6137095, 'Malfunction', 'Pay 500 Life Points. Negate the activation of a Trap Card and return it to its original position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23869735,3,0,0,131076,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (23869735, 'Fossil Excavation', 'Activate this card by discarding 1 card, then target 1 Dinosaur-Type monster in your Graveyard; Special Summon that target. Its effects are negated. When this card leaves the field, destroy that monster. When that monster is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
