BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (89631139,3,0,0,17,3000,2500,8,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (89631139, 'Blue-Eyes White Dragon', 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95788410,3,0,0,17,2950,2900,8,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (95788410, 'Rabidragon', 'It''s a snowfield-dwelling, giant-ear-sporting, super-acoustic, snowball-shaped mutant dragon! There''s no way anybody can escape.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43096270,3,0,0,17,2000,100,4,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (43096270, 'Alexandrite Dragon', 'Many of the czars'' lost jewels can be found in the scales of this priceless dragon. Its creator remains a mystery, along with how they acquired the imperial treasures. But whosoever finds this dragon has hit the jackpot... whether they know it or not.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (11091375,3,0,0,17,1900,1600,4,8192,8,0);
INSERT OR REPLACE INTO "texts" VALUES (11091375, 'Luster Dragon', 'A very beautiful dragon covered with sapphire. It does not like fights, but has incredibly high attack power.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21615956,3,0,44,4113,100,2000,1,8192,4,0);
INSERT OR REPLACE INTO "texts" VALUES (21615956, 'Flamvell Guard', 'A Flamvell guardian who commands fire with his will. His magma-hot barrier protects his troops from intruders.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88241506,3,0,0,4129,0,0,1,2,16,327680);
INSERT OR REPLACE INTO "texts" VALUES (88241506, 'Maiden with Eyes of Blue', 'When this card is targeted for an attack: You can negate the attack, and if you do, change the battle position of this card, then you can Special Summon 1 "Blue-Eyes White Dragon" from your hand, Deck, or Graveyard. During either player''s turn, when a card or effect is activated that targets this face-up card (except during the Damage Step): You can Special Summon 1 "Blue-Eyes White Dragon" from your hand, Deck, or Graveyard. You can only use 1 "Maiden with Eyes of Blue" effect per turn, and only once that turn.', 'Negate Attack?', 'Special Summon 1 "Blue-Eyes White Dragon"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14235211,3,0,0,4129,500,200,1,8192,16,16384);
INSERT OR REPLACE INTO "texts" VALUES (14235211, 'Rider of the Storm Winds', 'You can target 1 Dragon-Type Normal Monster you control; equip this monster from your hand or your side of the field to that target. If the monster equipped with this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. If the equipped monster would be destroyed, destroy this card instead.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57662975,3,0,0,2081,2700,2500,8,8192,32,1);
INSERT OR REPLACE INTO "texts" VALUES (57662975, 'Darkstorm Dragon', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect,
● Once per turn: You can send 1 face-up Spell/Trap Card you control to the Graveyard; destroy all Spell/Trap Cards on the field.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52824910,3,0,0,33,2400,2200,6,8192,16,16777232);
INSERT OR REPLACE INTO "texts" VALUES (52824910, 'Kaiser Glider', 'This card cannot be destroyed by battle with a monster that has the same ATK. When this card is destroyed and sent to the Graveyard, return 1 monster on the field to its owner''s hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77901552,3,0,105,33,2100,1400,6,8192,16,1376256);
INSERT OR REPLACE INTO "texts" VALUES (77901552, 'Hieratic Dragon of Tefnuit', 'If your opponent controls a monster and you control no monsters, you can Special Summon this card (from your hand). This card cannot attack during the turn it is Special Summoned this way. When this card is Tributed: Special Summon 1 Dragon-Type Normal Monster from your hand, Deck, or Graveyard, and make its ATK and DEF 0.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15960641,3,0,0,33,1600,600,4,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (15960641, 'Mirage Dragon', 'Your opponent cannot activate Trap Cards during the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20277376,3,0,0,33,1000,1500,4,8192,32,1049616);
INSERT OR REPLACE INTO "texts" VALUES (20277376, 'Divine Dragon Apocralyph', 'Once per turn: You can discard 1 card, then target 1 Dragon-Type monster in your Graveyard; add that target to your hand.', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79814787,3,0,0,4129,300,250,1,8192,16,512);
INSERT OR REPLACE INTO "texts" VALUES (79814787, 'The White Stone of Legend', 'When this card is sent to the Graveyard: Add 1 "Blue-Eyes White Dragon" from your Deck to your hand.', 'Add card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34627841,3,0,0,33,200,700,3,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (34627841, 'Kaibaman', 'You can Tribute this card to Special Summon 1 "Blue-Eyes White Dragon" from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66337215,3,0,0,33,1800,600,4,2,16,1048);
INSERT OR REPLACE INTO "texts" VALUES (66337215, 'Herald of Creation', 'Once per turn: You can discard 1 card, then target 1 Level 7 or higher monster in your Graveyard; add that target to your hand.', '7星以上的怪兽加入手牌', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17444133,3,0,0,33,1700,1650,4,262144,16,2097152);
INSERT OR REPLACE INTO "texts" VALUES (17444133, 'Kaiser Sea Horse', 'This card can be treated as 2 Tributes for the Tribute Summon of a LIGHT monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37742478,3,0,0,33,1100,1900,4,4,16,2105368);
INSERT OR REPLACE INTO "texts" VALUES (37742478, 'Honest', 'During your Main Phase: You can return this face-up card from the field to the hand. During either player''s Damage Step, when a LIGHT monster you control battles: You can send this card from your hand to the Graveyard; that monster gains ATK equal to the ATK of the opponent''s monster it is battling, until the end of this turn.', 'Return to hand', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95956346,3,0,0,33,1400,800,4,4,16,2359296);
INSERT OR REPLACE INTO "texts" VALUES (95956346, 'Shining Angel', 'When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 LIGHT monster with 1500 or less ATK from your Deck, in face-up Attack Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41620959,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (41620959, 'Dragon Shrine', 'Send 1 Dragon-Type monster from your Deck to the Graveyard, then if the monster you sent to the Graveyard was a Dragon-Type Normal Monster, you can send 1 more Dragon-Type monster from your Deck to the Graveyard. You can only activate 1 "Dragon Shrine" per turn.', ' Send another Dragon-Type Monster to the Graveyard?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87025064,3,0,0,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (87025064, 'Silver''s Cry', 'Target 1 Dragon-Type Normal Monster in your Graveyard; Special Summon that target. You can only activate 1 "Silver''s Cry" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17655904,3,0,0,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (17655904, 'Burst Stream of Destruction', 'Activate only while you control a face-up "Blue-Eyes White Dragon". Destroy all monsters your opponent controls. "Blue-Eyes White Dragon" cannot attack the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81385346,3,0,0,2,0,0,0,0,0,5242881);
INSERT OR REPLACE INTO "texts" VALUES (81385346, 'Stamping Destruction', 'If you control a Dragon-Type monster: Target 1 Spell/Trap Card on the field; destroy that target, and if you do, inflict 500 damage to its controller.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28596933,3,0,0,2,0,0,0,0,0,17);
INSERT OR REPLACE INTO "texts" VALUES (28596933, 'A Wingbeat of Giant Dragon', 'Return 1 face-up Level 5 or higher Dragon-Type monster you control to the owner''s hand and destroy all Spell and Trap Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38120068,3,0,0,2,0,0,0,0,0,264);
INSERT OR REPLACE INTO "texts" VALUES (38120068, 'Trade-In', 'Discard 1 Level 8 monster; draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39701395,3,0,0,2,0,0,0,0,0,264);
INSERT OR REPLACE INTO "texts" VALUES (39701395, 'Cards of Consonance', 'Discard 1 Dragon-Type Tuner monster with 1000 or less ATK to draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18756904,3,0,0,2,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (18756904, 'White Elephant''s Gift', 'Send 1 face-up non-Effect Monster you control to the Graveyard to draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2295440,3,0,0,2,0,0,0,0,0,262656);
INSERT OR REPLACE INTO "texts" VALUES (2295440, 'One for One', 'Send 1 monster from your hand to the Graveyard; Special Summon 1 Level 1 monster from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83764718,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (83764718, 'Monster Reborn', 'Target 1 monster in either player''s Graveyard; Special Summon it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72549351,3,0,0,2,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (72549351, 'Dragonic Tactics', 'Tribute 2 Dragon-Type monsters; Special Summon 1 Level 8 Dragon-Type monster from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68005187,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (68005187, 'Soul Exchange', 'Target 1 monster your opponent controls; this turn, if you Tribute a monster, you must Tribute that monster, as if you controlled it. You cannot conduct your Battle Phase the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72302403,3,0,0,2,0,0,0,0,0,67584);
INSERT OR REPLACE INTO "texts" VALUES (72302403, 'Swords of Revealing Light', 'Flip all monsters your opponent controls face-up. This card remains on the field for 3 of your opponent''s turns. While this card is face-up on the field, monsters your opponent controls cannot declare an attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98045062,3,0,0,65538,0,0,0,0,0,6144);
INSERT OR REPLACE INTO "texts" VALUES (98045062, 'Enemy Controller', 'Activate 1 of these effects.
● Target 1 face-up monster your opponent controls; change that target''s battle position.
● Tribute 1 monster, then target 1 face-up monster your opponent controls; take control of that target until the End Phase.', 'Change the Battle Position of 1 face-up monster your opponent controls', 'Tribute 1 monster. Select 1 face-up monster your opponent controls. Take control of it until the End Phase', 'Select effect', 'Select effect', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13513663,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (13513663, 'Castle of Dragon Souls', 'Once per turn: You can banish 1 Dragon-Type monster from your Graveyard, then target 1 face-up monster you control; it gains 700 ATK, until the End Phase. When this face-up card is sent to the Graveyard: You can target 1 of your banished Dragon-Type monsters; Special Summon that target. You can only control 1 face-up "Castle of Dragon Souls".', 'Banish a Dragon', 'Special Summon a Dragon', 'Activate Effect', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50078509,3,0,0,131076,0,0,0,0,0,-2147418112);
INSERT OR REPLACE INTO "texts" VALUES (50078509, 'Fiendish Chain', 'Activate this card by targeting 1 Effect Monster on the field; its effects are negated, also it cannot attack. When it is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37390589,3,0,0,4,0,0,0,0,0,10240);
INSERT OR REPLACE INTO "texts" VALUES (37390589, 'Kunai with Chain', 'Activate 1 or both of these effects (simultaneously).
● When an opponent''s monster declares an attack: Target the attacking monster; change that target to Defense Position.
● Target 1 face-up monster you control; equip this card to that target. It gains 500 ATK.', 'When an opponent''s monster attacks: Target the attacking monster; change that target to Defense Position', 'Target 1 face-up monster you control; equip this card to that target. It gains 500 ATK', 'Activate both effects', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28378427,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (28378427, 'Damage Condenser', 'Activate only by discarding 1 card when you take Battle Damage. Special Summon, in Attack Position, 1 monster from your Deck with ATK equal to or less than the Battle Damage you took.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97077563,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (97077563, 'Call of the Haunted', 'Activate this card by targeting 1 monster in your Graveyard; Special Summon that target in Attack Position. When this card leaves the field, destroy that target. When that target is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94192409,3,0,0,4,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (94192409, 'Compulsory Evacuation Device', 'Target 1 monster on the field; return that target to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82382815,3,0,0,1048580,0,0,0,0,0,-2147483645);
INSERT OR REPLACE INTO "texts" VALUES (82382815, 'Champion''s Vigilance', 'If you control a face-up Level 7 or higher Normal Monster, when a monster would be Summoned OR a Spell/Trap Card is activated: Negate the Summon or activation, and destroy that card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40908371,3,0,0,8225,2500,3000,9,8192,16,2359296);
INSERT OR REPLACE INTO "texts" VALUES (40908371, 'Azure-Eyes Silver Dragon', '1 Tuner + 1 or more non-Tuner Normal Monsters
When this card is Special Summoned: Dragon-Type monsters you currently control cannot be targeted or destroyed by card effects until the end of the next turn. Once per turn, during your Standby Phase: You can target 1 Normal Monster in your Graveyard; Special Summon that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
