BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (9748752,3,0,190,33,2400,1000,6,8,32,6291460);
INSERT OR REPLACE INTO "texts" VALUES (9748752, 'Caius the Shadow Monarch', 'When this card is Tribute Summoned: Target 1 card on the field; banish that target, and if you do, inflict 1000 damage to your opponent if it was a DARK monster.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36733451,3,0,0,33,1300,200,4,4,16,9220);
INSERT OR REPLACE INTO "texts" VALUES (36733451, 'Dimensional Alchemist', 'Once per turn, you can activate this effect to remove from play the top card of your Deck and give this card 500 ATK until the End Phase. When this card is destroyed and sent from your side of the field to your Graveyard, you can select 1 of your removed from play monsters and return it to your hand.', 'Gain attack', 'Select 1 of your banished monsters to return to your hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72237166,3,0,0,33,200,100,2,1,1,16);
INSERT OR REPLACE INTO "texts" VALUES (72237166, 'Samsara Kaiser', 'When you Tribute Summon a monster by Tributing this card, return this card to your hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27408609,3,0,0,33,1500,1500,6,1,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (27408609, 'Golden Homunculus', 'This card gains 300 ATK and DEF for each of your removed from play cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54493213,3,0,0,33,-2,-2,4,128,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (54493213, 'Helios - The Primordial Sun', 'This card''s ATK and DEF are each equal to the number of removed from play monsters x 100.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37043180,3,0,0,33,1200,1000,4,1,1,4);
INSERT OR REPLACE INTO "texts" VALUES (37043180, 'D.D. Warrior', 'When this card battles a monster, after damage calculation remove from play that monster and this card.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88240808,3,0,0,33,1800,700,4,2,32,4);
INSERT OR REPLACE INTO "texts" VALUES (88240808, 'Kycoo the Ghost Destroyer', 'When this card inflicts battle damage to your opponent: You can target up to 2 monsters in their Graveyard; banish those targets. Your opponent cannot banish cards from either player''s Graveyard.', 'Select up to 2 monsters to banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40133511,3,0,0,33,1600,900,4,16384,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (40133511, 'Bazoo the Soul-Eater', 'Once per turn: You can banish up to 3 monsters from your Graveyard; this card gains 300 ATK for each, until the end of your opponent''s turn.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74131780,3,0,0,33,1000,1000,4,1,1,10);
INSERT OR REPLACE INTO "texts" VALUES (74131780, 'Exiled Force', 'You can Tribute this card to target 1 monster on the field; destroy that target.', '破坏场上的1只怪兽', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7572887,3,0,0,33,1500,1600,4,1,16,4);
INSERT OR REPLACE INTO "texts" VALUES (7572887, 'D.D. Warrior Lady', 'After damage calculation, when this card battles an opponent''s monster: You can banish that monster, also banish this card.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3773196,3,0,0,33,800,1200,2,32,32,263168);
INSERT OR REPLACE INTO "texts" VALUES (3773196, 'D.D. Scout Plane', 'If this card is removed from play, Special Summon it in face-up Attack Position during the End Phase of this turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (47829960,3,0,0,33,1400,1500,4,1,8,8196);
INSERT OR REPLACE INTO "texts" VALUES (47829960, 'Chaosrider Gustaph', 'Once per turn, you can remove from play up to 2 Spell Cards in your Graveyard. This card gains 300 ATK for each card removed, until the end of your opponent''s next turn.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36584821,3,0,0,33,-2,-2,3,8,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (36584821, 'Gren Maju Da Eiza', 'This card''s ATK and DEF are each equal to the number of your removed from play cards x 400.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48092532,3,0,0,33,1800,200,4,1,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (48092532, 'D.D. Survivor', 'During the End Phase, if this card was banished while face-up, on your side of the field, this turn: Special Summon this banished card. This effect can only activate once per turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82112775,3,0,0,33,1700,1500,5,2,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (82112775, 'D.D.M. - Different Dimension Master', 'Once per turn, you can discard 1 Spell Card to Special Summon 1 of your removed from play monsters.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94853057,3,0,0,33,1600,0,3,4,16,4);
INSERT OR REPLACE INTO "texts" VALUES (94853057, 'Banisher of the Radiance', 'Any card sent to the Graveyard is banished instead.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70074904,3,0,0,33,1700,1600,4,1,1,4);
INSERT OR REPLACE INTO "texts" VALUES (70074904, 'D.D. Assailant', 'After damage calculation, when this card is destroyed by battle with an opponent''s monster: Banish that monster, also banish this card.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9622164,3,0,0,262146,0,0,0,0,0,263168);
INSERT OR REPLACE INTO "texts" VALUES (9622164, 'D.D.R. - Different Dimension Reincarnation', 'Discard 1 card, then target 1 of your banished monsters; Special Summon it in face-up Attack Position, and equip it with this card. When this card leaves the field, destroy the equipped monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5318639,3,0,0,65538,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (5318639, 'Mystical Space Typhoon', 'Target 1 Spell/Trap Card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71044499,3,0,0,2,0,0,0,0,0,6);
INSERT OR REPLACE INTO "texts" VALUES (71044499, 'Nobleman of Crossout', 'Target 1 face-down monster on the field; destroy that target, and if you do, banish it, then, if it was a Flip monster, each player reveals their Main Deck, then banishes all cards from it with that monster''s name.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5758500,3,0,0,2,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (5758500, 'Soul Release', 'Select up to 5 cards from the Graveyard(s) and remove them from play.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32807846,3,0,0,2,0,0,0,0,0,1049088);
INSERT OR REPLACE INTO "texts" VALUES (32807846, 'Reinforcement of the Army', 'Add 1 Level 4 or lower Warrior-Type monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70231910,3,0,0,2,0,0,0,0,0,12);
INSERT OR REPLACE INTO "texts" VALUES (70231910, 'Dark Core', 'Discard 1 card, then target 1 face-up monster on the field; banish that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61127349,3,0,0,262146,0,0,0,0,0,24580);
INSERT OR REPLACE INTO "texts" VALUES (61127349, 'Big Bang Shot', 'The equipped monster gains 400 ATK. If the equipped monster attacks a Defense Position monster, inflict piercing battle damage to your opponent. When this card leaves the field, banish the equipped monster.', 'Banish', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98045062,3,0,0,65538,0,0,0,0,0,6144);
INSERT OR REPLACE INTO "texts" VALUES (98045062, 'Enemy Controller', 'Activate 1 of these effects.
● Target 1 face-up monster your opponent controls; change that target''s battle position.
● Tribute 1 monster, then target 1 face-up monster your opponent controls; take control of that target until the End Phase.', 'Change the Battle Position of 1 face-up monster your opponent controls', 'Tribute 1 monster. Select 1 face-up monster your opponent controls. Take control of it until the End Phase', 'Select effect', 'Select effect', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69162969,3,0,0,2,0,0,0,0,0,10);
INSERT OR REPLACE INTO "texts" VALUES (69162969, 'Lightning Vortex', 'Discard 1 card; destroy all face-up monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87910978,3,0,0,2,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (87910978, 'Brain Control', 'Pay 800 Life Points. Select 1 face-up monster your opponent controls. Take control of it until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81674782,3,0,0,131074,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (81674782, 'Dimensional Fissure', 'Any monster sent to the Graveyard is banished instead.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35011819,3,0,0,131076,0,0,0,0,0,-2147483392);
INSERT OR REPLACE INTO "texts" VALUES (35011819, 'By Order of the Emperor', 'You can choose to negate the activation of an Effect Monster''s effect that activates when a monster is Normal Summoned (including itself). If you do, that Effect Monster''s controller draws 1 card.', 'Negate monster effect', 'Negate the activation of a monster effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27174286,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (27174286, 'Return from the Different Dimension', 'Pay half your Life Points; Special Summon as many of your banished monsters as possible. During the End Phase, banish all monsters that were Special Summoned by this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53582587,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (53582587, 'Torrential Tribute', 'When a monster(s) is Summoned: Destroy all monsters on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29401950,3,0,8978508,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (29401950, 'Bottomless Trap Hole', 'When your opponent Summons a monster(s) with 1500 or more ATK: Destroy that monster(s) with 1500 or more ATK, and if you do, banish it instead of sending it to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56120475,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (56120475, 'Sakuretsu Armor', 'When an opponent''s monster declares an attack: Target the attacking monster; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71587526,3,0,0,4,0,0,0,0,0,12);
INSERT OR REPLACE INTO "texts" VALUES (71587526, 'Karma Cut', 'Discard 1 card to select 1 face-up monster your opponent controls, and remove it from play. Then, remove from play any cards in your opponent''s Graveyard with the same name as that monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8628798,3,0,0,4,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (8628798, 'D.D. Dynamite', 'Inflict 300 damage to your opponent for each of their removed from play cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30241314,3,0,0,131076,0,0,0,0,0,262148);
INSERT OR REPLACE INTO "texts" VALUES (30241314, 'Macro Cosmos', 'When this card resolves: You can Special Summon 1 "Helios - The Primordial Sun" from your hand or Deck. While this card is face-up on the field, any card sent to the Graveyard is banished instead.', 'Do you want to Special Summon?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
