BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (63487632,3,0,41,33,2600,1200,8,8192,8,262148);
INSERT OR REPLACE INTO "texts" VALUES (63487632, 'Dragunity Arma Leyvaten', 'You can Special Summon this card from your hand or your Graveyard by removing from play 1 face-up monster you control equipped with a "Dragunity" card(s). When this card is Normal or Special Summoned, you can select 1 Dragon-Type monster in your Graveyard, except "Dragunity Arma Leyvaten", and equip it to this card. When this card is sent to the Graveyard by your opponent''s card effect, you can select 1 of the monsters that were equipped to this card when it was sent to the Graveyard, and Special Summon that monster from the Graveyard.', 'Equip', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (876330,3,0,41,33,2100,1500,6,8192,8,1311744);
INSERT OR REPLACE INTO "texts" VALUES (876330, 'Dragunity Arma Mystletainn', 'You can Special Summon this card from your hand by sending 1 face-up "Dragunity" monster you control to the Graveyard. When this card is Normal or Special Summoned from the hand, you can select 1 Dragon-Type "Dragunity" monster in your Graveyard, and equip it to this card.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36870345,3,0,41,4129,1000,800,2,8192,8,262147);
INSERT OR REPLACE INTO "texts" VALUES (36870345, 'Dragunity Aklys', 'When this card is Normal Summoned, you can Special Summon 1 "Dragunity" monster from your hand, then equip it with this card. When this card is sent to the Graveyard while equipped to a monster, select 1 card on the field, and destroy it.', '特殊召唤并装备', '场上的1张卡破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28183605,3,0,41,33,1500,1000,4,512,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (28183605, 'Dragunity Dux', 'This card gains 200 ATK for each face-up "Dragunity" card you control. When this card is Normal Summoned, you can select 1 Level 3 or lower Dragon-Type "Dragunity" monster in your Graveyard and equip it as an Equip Card to this card.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54578613,3,0,41,33,1200,800,3,512,8,262154);
INSERT OR REPLACE INTO "texts" VALUES (54578613, 'Dragunity Legionnaire', 'When this card is Normal Summoned, you can select 1 Level 3 or lower "Dragunity" Dragon-Type monster in your Graveyard, and equip it to this card as an Equip Card. You can send 1 "Dragunity" card from your Spell & Trap Card Zone to the Graveyard to select 1 face-up monster your opponent controls, and destroy it.', 'Equip', '对方场上表侧表示存在的1只怪兽破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81962318,3,0,41,33,500,300,1,512,8,1048584);
INSERT OR REPLACE INTO "texts" VALUES (81962318, 'Dragunity Tribus', 'When this card is Normal or Special Summoned, you can send 1 Level 3 or lower Dragon-Type monster from your Deck to the Graveyard.', '检索送墓', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13361027,3,0,41,4129,1000,1000,3,8192,8,1311744);
INSERT OR REPLACE INTO "texts" VALUES (13361027, 'Dragunity Darkspear', 'Once per turn, you can Tribute 1 Dragon-Type "Dragunity" monster to select and Special Summon 1 Level 4 or lower Winged Beast-Type monster from your Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81661951,3,0,41,33,1700,1200,4,512,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (81661951, 'Dragunity Militum', 'Once per turn, you can select 1 "Dragunity" card in your Spell & Trap Card Zone, and Special Summon it.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18060565,3,0,41,33,2200,1600,5,512,8,1048576);
INSERT OR REPLACE INTO "texts" VALUES (18060565, 'Dragunity Primus Pilus', 'When this card is Normal or Special Summoned, you can select 1 face-up Winged Beast-Type "Dragunity" monster you control. Equip it with 1 Level 3 or lower Dragon-Type "Dragunity" monster from your Deck.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54455664,3,0,41,4129,600,400,1,8192,8,32768);
INSERT OR REPLACE INTO "texts" VALUES (54455664, 'Dragunity Brandistock', 'While this card is equipped to a monster, that monster can attack twice during each Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80549379,3,0,41,4129,1200,800,2,8192,8,1048576);
INSERT OR REPLACE INTO "texts" VALUES (80549379, 'Dragunity Javelin', 'If this face-up card is destroyed while in the Monster Card Zone, you can equip it to 1 face-up Winged Beast-Type "Dragunity" monster you control, instead of sending it to the Graveyard.', 'Activate effect of "Dragunity Javelin"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82199284,3,0,55,33,2000,1200,4,512,8,65552);
INSERT OR REPLACE INTO "texts" VALUES (82199284, 'Mist Valley Falcon', 'This card cannot declare an attack unless you return 1 card you control to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51962254,3,0,0,33,1000,900,4,512,8,1056768);
INSERT OR REPLACE INTO "texts" VALUES (51962254, 'Hunter Owl', 'This card gains 500 ATK for each face-up WIND monster you control. While you control another face-up WIND monster, your opponent cannot select this card as an attack target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12800777,3,0,0,33,1600,1200,4,512,8,2361348);
INSERT OR REPLACE INTO "texts" VALUES (12800777, 'Garuda the Wind Spirit', 'This card cannot be Normal Summoned or Set. This card can only be Special Summoned by removing from play 1 WIND monster in your Graveyard. During your opponent''s End Phase, you can select 1 face-up monster your opponent controls, and change its battle position.', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84834865,3,0,0,33,1400,900,4,2048,8,2359296);
INSERT OR REPLACE INTO "texts" VALUES (84834865, 'Flying Kamakiri 1', 'When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 WIND monster with 1500 or less ATK from your Deck in face-up Attack Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31553716,3,0,0,33,1900,0,4,8192,8,18432);
INSERT OR REPLACE INTO "texts" VALUES (31553716, 'Spear Dragon', 'During battle between this attacking card and a Defense Position monster whose DEF is lower than the ATK of this card, inflict the difference as Battle Damage to your opponent. If this card attacks, it is changed to Defense Position at the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43586926,3,0,0,33,1500,1200,3,8192,8,270336);
INSERT OR REPLACE INTO "texts" VALUES (43586926, 'Twin-Headed Behemoth', 'During the End Phase, if this card was destroyed on the field and sent to the Graveyard this turn: Special Summon it from the Graveyard, and make its ATK and DEF 1000. You can only use the effect of "Twin-Headed Behemoth" once per Duel.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (980973,3,0,65,33,1200,900,3,8192,8,262656);
INSERT OR REPLACE INTO "texts" VALUES (980973, 'Armed Dragon LV3', 'During your Standby Phase, you can send this face-up card from the field to the Graveyard to Special Summon 1 "Armed Dragon LV5" from your hand or Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46384672,3,0,65,33,2400,1700,5,8192,8,262154);
INSERT OR REPLACE INTO "texts" VALUES (46384672, 'Armed Dragon LV5', 'Send 1 Monster Card from your hand to the Graveyard to destroy I face-up monster on your opponent''s side of the field with an ATK equal to or less than the ATK of the sent monster. During the End Phase of a turn that this card destroyed a monster as a result of battle, send this card to the Graveyard to Special Summon 1 "Armed Dragon LV7" from your hand or Deck.', 'Destroy', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39191307,3,0,0,33,1400,1100,3,8192,4,1310720);
INSERT OR REPLACE INTO "texts" VALUES (39191307, 'Masked Dragon', 'When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 Dragon-Type monster with 1500 or less ATK from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62265044,3,0,0,524290,0,0,0,0,0,1049096);
INSERT OR REPLACE INTO "texts" VALUES (62265044, 'Dragon Ravine', 'Once per turn, during your Main Phase, you can discard 1 card to activate 1 of these effects:
● Add 1 Level 4 or lower "Dragunity" monster from your Deck to your hand.
● Send 1 Dragon-Type monster from your Deck to the Graveyard.', 'Select effect', 'Add 1 Level 4 or lower "Dragunity" monster from your Deck to your hand.', 'Send 1 Dragon-Type monster from your Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99659159,3,0,0,131074,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (99659159, 'Dragon Mastery', 'Each monster you control that is equipped with 1 or more "Dragunity" monster(s) gain 500 ATK. Once per turn, you can select 1 face-up monster you control, and equip it with 1 Dragon-Type "Dragunity" monster from your hand.', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56747793,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (56747793, 'United We Stand', 'The equipped monster gains 800 ATK and DEF for each face-up monster you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83746708,3,0,110,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (83746708, 'Mage Power', 'The equipped monster gains 500 ATK and DEF for each Spell and Trap Card you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55991637,3,0,0,2,0,0,0,0,0,4194306);
INSERT OR REPLACE INTO "texts" VALUES (55991637, 'Dragon''s Gunfire', 'Activate only if you control a face-up Dragon-Type monster. Activate 1 of these effects:
● Inflict 800 damage to your opponent.
● Select 1 face-up monster with 800 or less DEF, and destroy it.', 'Inflict 800 damage to your opponent.', 'Select 1 face-up monster with 800 or less DEF, and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81385346,3,0,0,2,0,0,0,0,0,5242881);
INSERT OR REPLACE INTO "texts" VALUES (81385346, 'Stamping Destruction', 'If you control a Dragon-Type monster: Target 1 Spell/Trap Card on the field; destroy that target, and if you do, inflict 500 damage to its controller.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (31036355,3,0,0,2,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (31036355, 'Creature Swap', 'Each player chooses 1 monster they control and switches control of those monsters with each other. Those monsters cannot change their battle positions for the rest of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74848038,3,0,0,2,0,0,0,0,0,1048);
INSERT OR REPLACE INTO "texts" VALUES (74848038, 'Monster Reincarnation', 'Discard 1 card, then target 1 monster in your Graveyard; add it to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81439173,3,0,0,2,0,0,0,0,0,8);
INSERT OR REPLACE INTO "texts" VALUES (81439173, 'Foolish Burial', 'Send 1 monster from your Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72892473,3,0,0,2,0,0,0,0,0,328);
INSERT OR REPLACE INTO "texts" VALUES (72892473, 'Card Destruction', 'Each player discards their entire hand, then draws the same number of cards they discarded.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59744639,3,0,0,4,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (59744639, 'Windstorm of Etaqua', 'Change the battle positions of all face-up monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37507488,3,0,0,4,0,0,0,0,0,262160);
INSERT OR REPLACE INTO "texts" VALUES (37507488, 'Relieve Monster', 'When an opponent''s monster declares an attack: Target 1 monster you control; return that target to the hand, then Special Summon 1 Level 4 monster from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30461781,3,0,0,4,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (30461781, 'Legacy of Yata-Garasu', 'Activate 1 of these effects:
● Draw 1 card.
● Activate only if your opponent controls a face-up Spirit monster. Draw 2 cards.', 'Draw 1 card.', 'Draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (52503575,3,0,0,131076,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (52503575, 'Final Attack Orders', 'All face-up monsters on the field are changed to Attack Position and their battle positions cannot be changed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44095762,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (44095762, 'Mirror Force', 'When an opponent''s monster declares an attack: Destroy all Attack Position monsters your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54178050,3,0,0,131076,0,0,0,0,0,1064960);
INSERT OR REPLACE INTO "texts" VALUES (54178050, 'Dragon''s Rage', 'During battle between an attacking Dragon-Type monster you control and a Defense Position monster whose DEF is lower than the ATK of the attacking monster, inflict the difference as Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29401950,3,0,8978508,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (29401950, 'Bottomless Trap Hole', 'When your opponent Summons a monster(s) with 1500 or more ATK: Destroy that monster(s) with 1500 or more ATK, and if you do, banish it instead of sending it to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79333300,3,0,0,4,0,0,0,0,0,2097184);
INSERT OR REPLACE INTO "texts" VALUES (79333300, 'Spiritual Wind Art - Miyabi', 'Tribute 1 WIND monster to select 1 card your opponent controls. Place that card on the bottom of the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53567095,3,0,0,4,0,0,0,0,0,1048587);
INSERT OR REPLACE INTO "texts" VALUES (53567095, 'Icarus Attack', 'Tribute 1 Winged Beast-Type monster to select 2 cards on the field. Destroy them.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
