BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (50720316,3,0,12296,33,1000,1500,4,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (50720316, 'Elemental HERO Shadow Mist', 'If this card is Special Summoned: You can add 1 "Change" Quick-Play Spell Card from your Deck to your hand. If this card is sent to the Graveyard: You can add 1 "HERO" monster from your Deck to your hand, except "Elemental HERO Shadow Mist". You can only use 1 "Elemental HERO Shadow Mist" effect per turn, and only once that turn.', 'Add 1 "Change" Quick-Play Spell Card from your Deck to your hand?', 'Add 1 "HERO" monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37195861,3,0,12296,33,1500,1200,4,1,2,1040);
INSERT OR REPLACE INTO "texts" VALUES (37195861, 'Elemental HERO Ocean', 'Once per turn, during your Standby Phase: You can target 1 "HERO" monster you control or in your Graveyard; return that target to the hand.', 'Return "HERO" monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75434695,3,0,12296,33,1000,2000,4,1,1,1552);
INSERT OR REPLACE INTO "texts" VALUES (75434695, 'Elemental HERO Woodsman', 'Once per turn, during your Standby Phase: You can add 1 "Polymerization" from your Deck or Graveyard to your hand.', 'Add 1 "Polymerization" to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9327502,3,0,12296,33,1000,1500,4,4096,16,263168);
INSERT OR REPLACE INTO "texts" VALUES (9327502, 'Elemental HERO Voltic', 'When this card inflicts Battle Damage to your opponent: You can target 1 of your banished "Elemental HERO" monsters; Special Summon that target.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98266377,3,0,12296,33,1600,1200,4,128,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (98266377, 'Elemental HERO Heat', 'This card gains 200 ATK for each face-up "Elemental HERO" monster you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21844576,3,0,12296,17,1000,1000,3,1,8,0);
INSERT OR REPLACE INTO "texts" VALUES (21844576, 'Elemental HERO Avian', 'A winged Elemental HERO who wheels through the sky and manipulates the wind. His signature move, Featherbreak, gives villainy a blow from sky-high.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89943723,3,0,602120,17,2500,2000,7,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (89943723, 'Elemental HERO Neos', 'A new Elemental HERO has arrived from Neo-Space! When he initiates a Contact Fusion with a Neo-Spacian, his unknown powers are unleashed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69884162,3,0,602120,2081,1900,1300,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (69884162, 'Elemental HERO Neos Alius', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it become an Effect Monster with this effect.
● This face-up card''s name becomes "Elemental HERO Neos".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59793705,3,0,12296,33,2600,1800,7,1,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (59793705, 'Elemental HERO Bladedge', 'If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89252153,3,0,12296,33,1600,1800,5,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (89252153, 'Elemental HERO Necroshade', ' Once, while this card is in the Graveyard, you can Normal Summon 1 Level 5 or higher "Elemental HERO" monster from your hand without Tributes.', 'Effect of "Elemental HERO Necroshade"', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86188410,3,0,12296,33,1500,1600,4,1,1,33554432);
INSERT OR REPLACE INTO "texts" VALUES (86188410, 'Elemental HERO Wildheart', 'This card is unaffected by the effects of Trap Cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79979666,3,0,12296,33,800,1200,4,1,2,262400);
INSERT OR REPLACE INTO "texts" VALUES (79979666, 'Elemental HERO Bubbleman', 'If this is the only card in your hand, you can Special Summon it (from your hand). When this card is Summoned: You can draw 2 cards. You must control no other cards and have no cards in your hand to activate and to resolve this effect.', 'Special Summon', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80344569,3,0,31,33,900,300,3,256,1,1040);
INSERT OR REPLACE INTO "texts" VALUES (80344569, 'Neo-Spacian Grand Mole', 'At the start of the Damage Step, if this card battles an opponent''s monster: You can return both monsters to the hand (without damage calculation).', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37742478,3,0,0,33,1100,1900,4,4,16,2105368);
INSERT OR REPLACE INTO "texts" VALUES (37742478, 'Honest', 'During your Main Phase: You can return this face-up card from the field to the hand. During either player''s Damage Step, when a LIGHT monster you control battles: You can send this card from your hand to the Graveyard; that monster gains ATK equal to the ATK of the opponent''s monster it is battling, until the end of this turn.', 'Return to hand', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85087012,3,0,0,33,400,400,3,32,1,8456);
INSERT OR REPLACE INTO "texts" VALUES (85087012, 'Card Trooper', 'Once per turn: You can choose a number from 1 to 3, then send that many cards from the top of your Deck to the Graveyard; this card gains 500 ATK for each card sent to the Graveyard this way, until the end of this turn. If this card you control is destroyed and sent to your Graveyard: Draw 1 card.', 'Gain attack', 'Draw card', 'Send how many cards to Graveyard?', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57116033,3,0,164,33,300,200,1,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (57116033, 'Winged Kuriboh', 'If this card on the field is destroyed and sent to the Graveyard: Any further Battle Damage you take this turn becomes 0.', 'Reduce damage to 0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (423585,3,0,0,33,800,1600,4,2,32,264704);
INSERT OR REPLACE INTO "texts" VALUES (423585, 'Summoner Monk', 'Cannot be Tributed. When this card is Normal or Flip Summoned: Change this card to Defense Position. Once per turn: You can discard 1 Spell Card; Special Summon 1 Level 4 monster from your Deck, but that monster cannot attack this turn.', 'Change to defense position', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40410110,3,0,0,33,1800,1600,4,1024,16,2097152);
INSERT OR REPLACE INTO "texts" VALUES (40410110, 'Homunculus the Alchemic Being', 'Once per turn, you can change the Attribute of this monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93600443,3,0,165,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (93600443, 'Mask Change Second', 'Discard 1 card, then target 1 face-up monster you control that has a Level; send it to the Graveyard, then Special Summon 1 "Masked HERO" monster from your Extra Deck with the same Attribute as that monster, but with a higher Level. (This Special Summon is treated as a Special Summon with "Mask Change".) You can only activate 1 "Mask Change Second" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84536654,3,0,165,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (84536654, 'Form Change', 'Target 1 "HERO" Fusion Monster you control; return that monster to the Extra Deck, then Special Summon from your Extra Deck, 1 "Masked HERO" monster with the same Level as the original Level of the returned monster but with a different name. (This Special Summon is treated as a Special Summon with "Mask Change".)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87819421,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (87819421, 'Mask Charge', 'Target 1 "HERO" monster and 1 "Change" Quick-Play Spell Card in your Graveyard; add those targets to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21143940,3,0,165,65538,0,0,0,0,0,268697600);
INSERT OR REPLACE INTO "texts" VALUES (21143940, 'Mask Change', 'Target 1 face-up "HERO" monster you control; send it to the Graveyard, then Special Summon 1 "Masked HERO" monster from the Extra Deck with the same Attribute that the "HERO" monster had when it was on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24094653,3,0,70,2,0,0,0,0,0,268697608);
INSERT OR REPLACE INTO "texts" VALUES (24094653, 'Polymerization', 'Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters from your hand or your side of the field as Fusion Materials.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45906428,3,0,70,2,0,0,0,0,0,268697604);
INSERT OR REPLACE INTO "texts" VALUES (45906428, 'Miracle Fusion', 'Banish, from your side of the field or your Graveyard, the Fusion Material Monsters that are listed on an "Elemental HERO" Fusion Monster Card, then Special Summon that Fusion Monster from your Extra Deck. (This Special Summon is treated as a Fusion Summon.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54283059,3,0,70,2,0,0,0,0,0,268698656);
INSERT OR REPLACE INTO "texts" VALUES (54283059, 'Parallel World Fusion', 'Choose an "Elemental HERO" Fusion Monster in your Extra Deck whose listed Fusion Material Monsters are banished, shuffle the banished Fusion Material Monsters into the Deck, then Special Summon that Fusion Monster from your Extra Deck. (This Special Summon is treated as a Fusion Summon.) You cannot Special Summon another monster(s) during the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8949584,3,0,0,2,0,0,0,0,0,262656);
INSERT OR REPLACE INTO "texts" VALUES (8949584, 'A Hero Lives', 'When you control no face-up monsters: Pay half your Life Points; Special Summon 1 Level 4 or lower "Elemental HERO" monster from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75141056,3,0,0,2,0,0,0,0,0,8);
INSERT OR REPLACE INTO "texts" VALUES (75141056, 'Hero Mask', 'Target 1 face-up monster you control; send 1 "Elemental HERO" monster from your Deck to the Graveyard, then that target''s name becomes the sent monster''s name, until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74825788,3,0,0,2,0,0,0,0,0,24576);
INSERT OR REPLACE INTO "texts" VALUES (74825788, 'H - Heated Heart', 'Target 1 face-up monster you control; until the End Phase, it gains 500 ATK, and if it attacks a Defense Position monster, inflict piercing Battle Damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (213326,3,0,0,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (213326, 'E - Emergency Call', 'Add 1 "Elemental HERO" monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37318031,3,0,0,2,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (37318031, 'R - Righteous Justice', 'Destroy Spell/Trap Cards equal to the number of face-up "Elemental HERO" cards you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63703130,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (63703130, 'O - Oversoul', 'Target 1 "Elemental HERO" Normal Monster in your Graveyard; Special Summon that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32807846,3,0,0,2,0,0,0,0,0,1049088);
INSERT OR REPLACE INTO "texts" VALUES (32807846, 'Reinforcement of the Army', 'Add 1 Level 4 or lower Warrior-Type monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95281259,3,0,0,2,0,0,0,0,0,1049600);
INSERT OR REPLACE INTO "texts" VALUES (95281259, 'The Warrior Returning Alive', 'Target 1 Warrior-Type monster in your Graveyard; add that target to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98645731,3,0,0,2,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (98645731, 'Pot of Duality', 'Reveal the top 3 cards of your Deck, add 1 of them to your hand, then shuffle the rest back into your Deck. You can only activate 1 "Pot of Duality" per turn. You cannot Special Summon during the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22020907,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (22020907, 'Hero Signal', 'When a monster you control is destroyed by battle and sent to the Graveyard: Special Summon 1 Level 4 or lower "Elemental HERO" monster from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37412656,3,0,0,4,0,0,0,0,0,1026);
INSERT OR REPLACE INTO "texts" VALUES (37412656, 'Hero Blast', 'Target 1 "Elemental HERO" Normal Monster in your Graveyard; add that target to your hand, then destroy 1 face-up monster your opponent controls with ATK less than or equal to the target''s ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97077563,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (97077563, 'Call of the Haunted', 'Activate this card by targeting 1 monster in your Graveyard; Special Summon that target in Attack Position. When this card leaves the field, destroy that target. When that target is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29401950,3,0,8978508,4,0,0,0,0,0,4);
INSERT OR REPLACE INTO "texts" VALUES (29401950, 'Bottomless Trap Hole', 'When your opponent Summons a monster(s) with 1500 or more ATK: Destroy that monster(s) with 1500 or more ATK, and if you do, banish it instead of sending it to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94192409,3,0,0,4,0,0,0,0,0,16);
INSERT OR REPLACE INTO "texts" VALUES (94192409, 'Compulsory Evacuation Device', 'Target 1 monster on the field; return that target to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78621186,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (78621186, 'Battleguard Howling', 'When a Warrior-Type monster you control is targeted for an attack, or by an opponent''s monster effect: Target 1 face-up monster your opponent controls; inflict damage to your opponent equal to the original ATK of the face-up monster you targeted with this card, and if you do, return it to the hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23204029,3,0,12296,97,3000,2600,9,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (23204029, 'Contrast HERO Chaos', '2 "Masked HERO" monsters
(This card is always treated as an "Elemental HERO" monster.)
Must be Fusion Summoned and cannot be Special Summoned by other ways. While face-up on the field, this card is also LIGHT-Attribute. Once per turn, during either player''s turn: You can target 1 face-up card on the field; negate that target''s effects until the end of this turn.', 'Negate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50608164,3,0,40968,97,2500,1800,8,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (50608164, 'Masked HERO Koga', 'Must be Special Summoned by "Mask Change", and cannot be Special Summoned by other ways. This card gains 500 ATK for each monster your opponent controls. Once per turn, during either player''s turn: You can banish 1 "HERO" monster from your Graveyard, then target 1 face-up monster on the field; it loses ATK equal to the banished monster''s ATK, until the end of this turn.', 'Banish a HERO Monster? ', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22093873,3,0,40968,97,2700,1900,8,1,8,0);
INSERT OR REPLACE INTO "texts" VALUES (22093873, 'Masked HERO Kamikaze', 'Must be Special Summoned by "Mask Change", and cannot be Special Summoned by other ways. Cannot be destroyed by battle. Only 1 monster can attack during your opponent''s Battle Phase. When this card destroys an opponent''s monster by battle and sends it to the Graveyard: You can draw 1 card.', 'Draw 1 card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58481572,3,0,40968,97,2400,1800,6,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (58481572, 'Masked HERO Dark Law', 'Must be Special Summoned by "Mask Change", and cannot be Special Summoned by other ways. Any card sent to your opponent''s Graveyard is banished instead. Once per turn, if your opponent adds a card(s) from their Main Deck to their hand, except during the Draw Phase or Damage Step: You can banish 1 random card from your opponent''s hand.', 'Banish 1 random card from your opponent''s hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3642509,3,0,12296,97,2800,2200,8,1,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (3642509, 'Elemental HERO Great Tornado', '1 "Elemental HERO" monster + 1 WIND monster
Must be Fusion Summoned and cannot be Special Summoned by other ways. When this card is Fusion Summoned: Halve the ATK and DEF of all face-up monsters your opponent controls.', 'Halve ATK and DEF', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
