BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (47826112,3,0,119,33,2800,1600,7,262144,2,270352);
INSERT OR REPLACE INTO "texts" VALUES (47826112, 'Poseidra, the Atlantean Dragon', 'You can Tribute 3 Level 3 or lower WATER monsters; Special Summon this card from your hand or Graveyard. When you do: Return all Spell and Trap Cards on the field to the hand, and if you do, if 3 or more cards are returned to the hand by this effect, all monsters your opponent currently controls lose 300 ATK for each.', 'Special Summon', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74311226,3,0,119,33,1800,0,4,262144,2,1180160);
INSERT OR REPLACE INTO "texts" VALUES (74311226, 'Atlantean Dragoons', 'All face-up Level 3 or lower Sea Serpent-Type monsters you control can attack your opponent directly. When this card is sent to the Graveyard to activate a WATER monster''s effect: Add 1 Sea Serpent-Type monster from your Deck to your hand, except "Atlantean Dragoons".', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (706925,3,0,119,33,1400,0,3,262144,2,1310723);
INSERT OR REPLACE INTO "texts" VALUES (706925, 'Atlantean Marksman', 'When this card inflicts Battle Damage to your opponent: You can Special Summon 1 Level 4 or lower Sea Serpent-Type "Atlantean" monster, except "Atlantean Marksman", from your Deck. When this card is sent to the Graveyard to activate a WATER monster''s effect: Target 1 Set card your opponent controls; destroy that target.', 'Special Summon', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37104630,3,0,119,33,0,1600,2,262144,2,1048579);
INSERT OR REPLACE INTO "texts" VALUES (37104630, 'Atlantean Heavy Infantry', 'During your Main Phase, you can Normal Summon a Level 4 or lower Sea Serpent-Type monster in addition to your Normal Summon/Set. (You can only gain this effect once per turn.) When this card is sent to the Graveyard to activate a WATER monster''s effect: Target 1 face-up card your opponent controls; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26976414,3,0,119,17,1400,0,2,262144,2,0);
INSERT OR REPLACE INTO "texts" VALUES (26976414, 'Atlantean Pikeman', 'The Great Ocean Lord, who reigns over the depths, is served by these lancers. Deep-sea creatures exist in fear of facing the stream of attacks their lances are capable of.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8078366,3,0,119,33,1400,0,3,262144,2,1056768);
INSERT OR REPLACE INTO "texts" VALUES (8078366, 'Atlantean Attack Squad', 'This card gains 800 ATK while you control a face-up Fish, Sea Serpent, or Aqua-Type monster other than this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95231062,3,0,0,33,1400,0,3,262144,2,1);
INSERT OR REPLACE INTO "texts" VALUES (95231062, 'Lost Blue Breaker', 'If there is another face-up Fish, Sea Serpent, or Aqua-Type monster on the field: You can Tribute this card to target 1 Spell/Trap Card on the field; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20470500,3,0,0,33,1800,400,4,262144,2,-2128609278);
INSERT OR REPLACE INTO "texts" VALUES (20470500, 'Armed Sea Hunter', 'After damage calculation, if this card battles an Effect Monster: Negate the effects of that monster (including in the Graveyard). You must control another face-up WATER monster to activate and resolve this effect. If this card would be destroyed, you can destroy 1 face-up Level 3 or lower WATER monster you control instead.', 'Negate effects', 'Destroy 1 face-up Level 3 or lower WATER monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42463414,3,0,0,33,1300,0,3,262144,2,8192);
INSERT OR REPLACE INTO "texts" VALUES (42463414, 'Spined Gillman', 'All Fish, Sea Serpent, and Aqua-Type monsters you control gain 400 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78868119,3,0,0,4129,200,400,2,262144,2,1310720);
INSERT OR REPLACE INTO "texts" VALUES (78868119, 'Deep Sea Diva', 'When this card is Normal Summoned: You can Special Summon 1 Level 3 or lower Sea Serpent-Type monster from your Deck.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4252828,3,0,0,33,1200,200,3,262144,2,16785408);
INSERT OR REPLACE INTO "texts" VALUES (4252828, 'Mermaid Archer', 'Once per turn: You can target 1 face-up Level 3 or lower monster you control; equip that target to this card. (You can only equip 1 monster at a time to this card with this effect.) While equipped with a monster by this effect, this card gains 800 ATK. If this card would be destroyed, you can destroy the monster equipped to it with this effect instead.', 'Equip', 'Activate the effect of "Mermaid Archer" to avoid destruction?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65496056,3,0,0,33,1400,1200,4,262144,2,11);
INSERT OR REPLACE INTO "texts" VALUES (65496056, 'Codarus', 'You can send 1 face-up "Umi" you control to the Graveyard to target up to 2 cards your opponent controls; send those targets to the Graveyard.', 'Send to Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43797906,3,0,0,33,1900,1200,4,64,2,520);
INSERT OR REPLACE INTO "texts" VALUES (43797906, 'Warrior of Atlantis', 'You can discard this card to the Graveyard; add 1 "A Legendary Ocean" from your Deck to your hand.', 'Search', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18318842,3,0,117,33,1800,1300,4,64,2,16);
INSERT OR REPLACE INTO "texts" VALUES (18318842, 'Abyss Soldier', 'Once per turn: You can discard 1 WATER monster to the Graveyard to target 1 card on the field; return it to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27655513,3,0,0,33,1500,400,4,524288,2,2097160);
INSERT OR REPLACE INTO "texts" VALUES (27655513, 'Skreech', 'If this card is destroyed by battle: Send 2 WATER monsters from your Deck to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91133740,3,0,0,33,0,1900,3,64,2,2);
INSERT OR REPLACE INTO "texts" VALUES (91133740, 'Snowman Eater', 'When this card is flipped face-up: Target 1 face-up monster on the field; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81306586,3,0,90,33,900,1800,4,64,2,2105360);
INSERT OR REPLACE INTO "texts" VALUES (81306586, 'Nightmare Penguin', 'All face-up WATER monsters you control gain 200 ATK. When this card is flipped face-up: Target 1 card your opponent controls; return that target to the hand.', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93920745,3,0,90,2097185,750,500,2,64,2,16);
INSERT OR REPLACE INTO "texts" VALUES (93920745, 'Penguin Soldier', 'FLIP: You can target up to 2 monsters on the field; return those targets to the hand.', 'Return to hand', 'Return Monster Cards to hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17559367,3,0,0,33,1000,1100,3,64,2,512);
INSERT OR REPLACE INTO "texts" VALUES (17559367, 'Deep Diver', 'At the end of the Battle Phase, if this card was destroyed by battle and sent to the Graveyard: Choose 1 monster from your Deck and place it on top of your Deck.', 'Search', 'Select 1 monster to place on top of your Deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30276969,3,0,0,4129,800,800,2,262144,2,16777216);
INSERT OR REPLACE INTO "texts" VALUES (30276969, 'Reese the Ice Mistress', 'This card cannot be destroyed by battle with a Level 4 or higher monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57839750,3,0,0,33,1400,1000,4,32768,2,2359296);
INSERT OR REPLACE INTO "texts" VALUES (57839750, 'Mother Grizzly', 'When this card is destroyed by battle and sent to the Graveyard: You can Special Summon 1 WATER monster with 1500 or less ATK from your Deck, in face-up Attack Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93830681,3,0,0,33,700,1500,3,131072,2,1056768);
INSERT OR REPLACE INTO "texts" VALUES (93830681, 'Friller Rabca', 'When a face-up Fish, Sea Serpent, or Aqua-Type monster you control is targeted for an attack: You can banish this card from your Graveyard to target the attacking monster; negate the attack, and if you do, that target loses 500 ATK until your next End Phase. You can only use the effect of "Friller Rabca" once per turn.', 'Negate attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73199638,3,0,119,65538,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (73199638, 'Call of the Atlanteans', 'Target 3 Level 3 or lower Sea Serpent-Type monsters in your Graveyard; Special Summon all 3 of them. You cannot Special Summon any other monsters during the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (295517,3,22702055,0,524290,0,0,0,0,0,2105344);
INSERT OR REPLACE INTO "texts" VALUES (295517, 'A Legendary Ocean', 'This card''s name is treated as "Umi". Reduce the Level of all WATER monsters in both player''s hands and on the field by 1. All WATER monsters gain 200 ATK and DEF.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73628505,3,0,0,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (73628505, 'Terraforming', 'Add 1 Field Spell Card from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49669730,3,0,0,131074,0,0,0,0,0,2359296);
INSERT OR REPLACE INTO "texts" VALUES (49669730, 'Water Hazard', 'Once per turn: You can Special Summon 1 Level 4 or lower WATER monster from your hand. You must control no monsters to activate and to resolve this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7653207,3,0,0,2,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (7653207, 'Aqua Jet', 'Target 1 face-up Fish, Sea Serpent, or Aqua-Type monster you control; it gains 1000 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33057951,3,0,0,2,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (33057951, 'Surface', 'Target 1 Level 3 or lower Fish, Sea Serpent, or Aqua-Type monster in your Graveyard; Special Summon it in face-up Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22123627,3,0,0,2,0,0,0,0,0,288);
INSERT OR REPLACE INTO "texts" VALUES (22123627, 'Moray of Greed', 'Shuffle 2 WATER monsters from your hand into the Deck, then draw 3 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96947648,3,0,0,2,0,0,0,0,0,2098176);
INSERT OR REPLACE INTO "texts" VALUES (96947648, 'Salvage', 'Target 2 WATER monsters with 1500 or less ATK in your Graveyard; add those targets to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53129443,3,0,137,2,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (53129443, 'Dark Hole', 'Destroy all monsters on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (51562916,3,0,0,2,0,0,0,0,0,2359296);
INSERT OR REPLACE INTO "texts" VALUES (51562916, 'Big Wave Small Wave', 'Destroy all face-up WATER monsters on your side of the field. Then you can Special Summon WATER monsters from your hand, up to the same number of monsters destroyed by this effect.', 'Special summon WATER monsters from hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7935043,3,0,0,4,0,0,0,0,0,18874368);
INSERT OR REPLACE INTO "texts" VALUES (7935043, 'Aegis of the Ocean Dragon Lord', 'Until the End Phase, face-up Level 3 or lower WATER monsters you control cannot be destroyed by battle or by card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43889633,3,0,0,131076,0,0,0,0,0,1310724);
INSERT OR REPLACE INTO "texts" VALUES (43889633, 'Forgotten Temple of the Deep', 'While this card is on the field, this card''s name becomes "Umi". Once per turn: You can target 1 Level 4 or lower Fish, Sea Serpent or Aqua-Type monster you control; banish that target. During your End Phase: Special Summon the monster(s) banished by this effect.', 'Activate effect of "Forgotten Temple of the Deep"?', 'Banish', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18605135,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (18605135, 'Tornado Wall', 'Activate only while "Umi" is on the field. While "Umi" is face-up on the field, you take no Battle Damage from attacking monsters. Destroy this card when "Umi" leaves the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53582587,3,0,0,4,0,0,0,0,0,2);
INSERT OR REPLACE INTO "texts" VALUES (53582587, 'Torrential Tribute', 'When a monster(s) is Summoned: Destroy all monsters on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (6540606,3,0,0,4,0,0,0,0,0,2097216);
INSERT OR REPLACE INTO "texts" VALUES (6540606, 'Spiritual Water Art - Aoi', 'Tribute 1 WATER monster; look at your opponent''s hand, then send 1 card from their hand to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85742772,3,0,0,131076,0,0,0,0,0,65536);
INSERT OR REPLACE INTO "texts" VALUES (85742772, 'Gravity Bind', 'Level 4 or higher monsters cannot attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25642998,3,0,0,4,0,0,0,0,0,5308416);
INSERT OR REPLACE INTO "texts" VALUES (25642998, 'Poseidon Wave', 'When an opponent''s monster declares an attack: Target the attacking monster; negate the attack, and if you do, inflict 800 damage to your opponent for each face-up Fish, Sea Serpent, or Aqua-Type monster you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
