BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (62514770,3,0,0,4113,0,2400,6,8192,32,0);
INSERT OR REPLACE INTO "texts" VALUES (62514770, 'Labradorite Dragon', 'The ancients compared this prized creature to moonlight rippling across water. A bringer of harmony, reminder of past glories, able to soothe the hearts of even the most ambitious men.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99902789,3,0,0,33,800,800,2,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (99902789, 'Chow Chow Chan', 'When your opponent activates a Normal Trap Card in response to your monster’s attack declaration targeting an opponent’s monster: You can discard this card; negate the activation, and if you do, destroy that card (this is a Quick Effect).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35307484,3,0,139,33,100,500,2,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (35307484, 'Malicevorous Spoon', 'When a "Malicevorous" monster with a different name is Normal or Special Summoned to your side of the field (except during the Damage Step): You can target 1 Level 2 Fiend-Type monster in your Graveyard; Special Summon that target. Its effects are negated. You can only use the effect of "Malicevorous Spoon" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61791132,3,0,139,33,400,400,2,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (61791132, 'Malicevorous Fork', 'You can send 1 other Fiend-Type monster from your hand to the Graveyard; Special Summon this card from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98780137,3,0,139,33,600,100,2,8,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (98780137, 'Malicevorous Knife', 'When this card is Normal Summoned: You can target 1 "Malicevorous" monster in your Graveyard except "Malicevorous Knife"; Special Summon that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24184846,3,0,132,33,100,1400,3,1,4,4);
INSERT OR REPLACE INTO "texts" VALUES (24184846, 'Battlin'' Boxer Rib Gardna', 'During either player''s turn: You can banish this card from your hand or Graveyard, then target 1 "Battlin'' Boxer" monster you control; banish it until your next Standby Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61679541,3,0,132,33,800,1000,3,1,4,2);
INSERT OR REPLACE INTO "texts" VALUES (61679541, 'Battlin'' Boxer Rabbit Puncher', 'At the start of the Damage Step, if this card attacks a Defense Position monster: Destroy that monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24062258,3,0,0,33,1800,0,4,2,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (24062258, 'Secret Sect Druid Dru', 'When this card is Normal Summoned: You can target 1 Level 4 DARK monster in your Graveyard with 0 ATK and/or DEF, except "Secret Sect Druid Dru"; Special Summon that target in face-up Defense Position. Its effects are negated. You can only use the effect of "Secret Sect Druid Dru" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50457953,3,0,0,33,100,1400,4,8192,1,2097152);
INSERT OR REPLACE INTO "texts" VALUES (50457953, 'Mythic Tree Dragon', 'Once per turn: You can target 1 WATER Dragon-Type monster you control; this card''s Level becomes the current Level of that monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92841002,3,0,0,33,1000,2000,8,8192,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (92841002, 'Mythic Water Dragon', 'If you control an EARTH monster, you can Special Summon this card (from your hand). You can only Special Summon "Mythic Water Dragon" once per turn this way.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29330706,3,0,0,33,2000,2800,8,8192,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (29330706, 'Armed Protector Dragon', 'Face-up Equip Cards you control cannot be destroyed by card effects. This card gains 500 ATK for each Equip Card equipped to this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55735315,3,0,0,33,4000,0,8,8192,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (55735315, 'Soul Drain Dragon', 'Cannot be Normal Summoned/Set. Must be Special Summoned by your Dragon-Type Xyz Monster''s effect, and cannot be Special Summoned by other ways. When this card is Special Summoned while your Life Points are lower than your opponent''s: This card gains ATK equal to the difference, but your opponent takes no battle damage this turn. This card cannot attack your opponent directly.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (92729410,3,0,0,33,800,0,2,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (92729410, 'Baby Raccoon Ponpoko', 'When this card is Normal Summoned: You can Special Summon 1 Level 2 Beast-Type monster from your Deck in face-down Defense Position, except "Baby Raccoon Ponpoko". You cannot Special Summon any monsters during the turn you activate this effect, except Beast-Type monsters.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28118128,3,0,0,2097185,0,800,2,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (28118128, 'Baby Raccoon Tantan', 'FLIP: Special Summon 1 Level 2 Beast-Type monster from your Deck, except "Baby Raccoon Tantan".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54512827,3,0,141,33,800,0,1,8,32,-2147219456);
INSERT OR REPLACE INTO "texts" VALUES (54512827, 'Ghostrick Lantern', 'Cannot be Normal Summoned, unless you control a "Ghostrick" monster. Once per turn: You can change this card to face-down Defense Position. When an opponent''s monster declares a direct attack, or when a "Ghostrick" monster you control is targeted for an attack: You can negate the attack, and if you do, Special Summon this card from your hand in face-down Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81907872,3,0,141,33,600,0,1,8,32,262400);
INSERT OR REPLACE INTO "texts" VALUES (81907872, 'Ghostrick Specter', 'Cannot be Normal Summoned, unless you control a "Ghostrick" monster. Once per turn: You can change this card to face-down Defense Position. When a "Ghostrick" monster is destroyed by an opponent''s card effect, or by battle with their attacking monster, and sent to your Graveyard: You can Special Summon this card from your hand in face-down Defense Position, and if you do, draw 1 card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27491571,3,0,141,33,1200,200,2,2,32,2048);
INSERT OR REPLACE INTO "texts" VALUES (27491571, 'Ghostrick Witch', 'Cannot be Normal Summoned, unless you control a "Ghostrick" monster. Once per turn: You can change this card to face-down Defense Position. Once per turn: You can target 1 face-up monster your opponent controls; change it to face-down Defense Position.', 'Set', 'Flip 1 monster face-down', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54490275,3,0,141,33,1000,800,2,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (54490275, 'Ghostrick Yuki-onna', 'Cannot be Normal Summoned, unless you control a "Ghostrick" monster. Once per turn: You can change this card to face-down Defense Position. When this card is destroyed by battle and sent to the Graveyard: You can change the monster that destroyed it to face-down Defense Position, and if you do, it cannot change its battle position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80885284,3,0,141,33,400,1800,3,16,32,512);
INSERT OR REPLACE INTO "texts" VALUES (80885284, 'Ghostrick Jiangshi', 'Cannot be Normal Summoned, unless you control a "Ghostrick" monster. Once per turn: You can change this card to face-down Defense Position. When this card is flipped face-up: You can add from your Deck to your hand, 1 "Ghostrick" monster whose Level is less than or equal to the number of "Ghostrick" monsters you control. You can only use this effect of "Ghostrick Jiangshi" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16279989,3,0,141,33,1600,0,3,16,32,512);
INSERT OR REPLACE INTO "texts" VALUES (16279989, 'Ghostrick Stein', 'Cannot be Normal Summoned, unless you control a "Ghostrick" monster. Once per turn: You can change this card to face-down Defense Position. When this card inflicts battle damage to your opponent: You can add 1 "Ghostrick" Spell/Trap Card from your Deck to your hand. You can only use this effect of "Ghostrick Stein" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53678698,3,0,136,33,1900,1500,4,32768,16,262656);
INSERT OR REPLACE INTO "texts" VALUES (53678698, 'Bujin Mikazuchi', 'When a Beast-Warrior-Type "Bujin" monster(s) you control is destroyed by battle or by card effect and sent to the Graveyard: You can Special Summon this card from your hand. Once per turn, during the End Phase, if a "Bujin" monster(s) was sent from your hand to your Graveyard this turn while you controlled this face-up card: You can add 1 "Bujin" Spell/Trap Card from your Deck to your hand. You can only control 1 "Bujin Mikazuchi".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89662736,3,0,136,33,1700,800,4,512,16,-2143289344);
INSERT OR REPLACE INTO "texts" VALUES (89662736, 'Bujingi Crow', 'When a Beast-Warrior-Type "Bujin" monster you control is targeted for an attack by an opponent''s monster: You can send this card from your hand to the Graveyard; negate the attack, and if you do, inflict damage to your opponent equal to half the attacker''s ATK. You can only use the effect of "Bujingi Crow" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16157341,3,0,136,33,1600,300,4,512,16,16384);
INSERT OR REPLACE INTO "texts" VALUES (16157341, 'Bujingi Ibis', 'During your Main Phase 1: You can send this card from your hand to the Graveyard, then target 1 "Bujin" monster you control; this turn, if it attacks a Defense Position monster, inflict piercing battle damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42551040,3,0,136,33,1100,1900,4,16384,16,10240);
INSERT OR REPLACE INTO "texts" VALUES (42551040, 'Bujingi Boar', 'If you control a "Bujin" monster: You can banish this card from your Graveyard, then target 1 face-up Attack Position monster your opponent controls; change it to face-up Defense Position, and if you do, its DEF becomes 0 until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88940154,3,0,136,33,1700,500,4,16384,16,1);
INSERT OR REPLACE INTO "texts" VALUES (88940154, 'Bujingi Centipede', 'If you control a Beast-Warrior-Type "Bujin" monster: You can banish this card from your Graveyard, then target 1 Spell/Trap Card your opponent controls; destroy that target. You can only use the effect of "Bujingi Centipede" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15335853,3,0,4123,33,2100,100,4,32,8,0);
INSERT OR REPLACE INTO "texts" VALUES (15335853, 'Mecha Phantom Beast Sabre Hawk', 'This card cannot attack your opponent directly. If you have a monster in your Graveyard that is not a "Mecha Phantom Beast" monster, this card cannot attack. This card''s Level is increased by the total Levels of all "Mecha Phantom Beast Tokens" you control. While you control a Token, this card cannot be destroyed by battle or card effects. Once per turn: You can Tribute 1 Token, then target 1 card in either player''s Graveyard; banish that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41329458,3,0,4123,33,1000,2500,7,32,8,786432);
INSERT OR REPLACE INTO "texts" VALUES (41329458, 'Mecha Phantom Beast Kalgriffin', 'You can Tribute 2 "Mecha Phantom Beast" monsters; Special Summon this card from your hand. You can only use this effect of "Mecha Phantom Beast Kalgriffin" once per turn. While you control a Token, this card cannot be destroyed by battle or card effects. Once per turn: You can discard 1 "Mecha Phantom Beast" monster; Special Summon 1 "Mecha Phantom Beast Token" (Machine-Type/WIND/Level 3/ATK 0/DEF 0).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (88728507,3,0,142,33,1500,1500,4,16,32,262656);
INSERT OR REPLACE INTO "texts" VALUES (88728507, 'Vampire Sorcerer', 'If this card in your possession is sent to your Graveyard by your opponent''s card (either by battle or by card effect): You can add 1 DARK "Vampire" monster or 1 "Vampire" Spell/Trap Card from your Deck to your hand. You can banish this card from your Graveyard; 1 DARK "Vampire" monster you Normal Summon this turn can be Summoned without Tributing.', 'Add 1 DARK "Vampire" monster or 1 "Vampire" Spell/Trap Card from your Deck to your hand?', '    ', 'Normal Summon without Tribute', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14212201,3,0,142,33,2000,0,5,16,32,1074003968);
INSERT OR REPLACE INTO "texts" VALUES (14212201, 'Shadow Vampire', 'When this card is Normal Summoned: You can Special Summon 1 DARK "Vampire" monster from your hand or Deck, except "Shadow Vampire", but if you do, only that monster can attack for the rest of this turn. This card cannot be used as an Xyz Material for an Xyz Summon, except for the Xyz Summon of a DARK monster.', 'Special Summon 1 DARK "Vampire" monster from your hand or Deck?', 'Description Effect 2', 'Normal Summon without Tribute', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40607210,3,0,142,33,2000,1200,6,16,32,262272);
INSERT OR REPLACE INTO "texts" VALUES (40607210, 'Vampire Grace', 'When a Level 5 or higher Zombie-Type monster(s) is Special Summoned to your side of the field by the effect of a Zombie-Type monster while this card is in your Graveyard: You can pay 2000 LP; Special Summon this card from your Graveyard. You can only use this effect of "Vampire Grace" once per turn. Once per turn: You can declare 1 card type (Monster, Spell, or Trap); your opponent sends 1 card of that type from their Deck to the Graveyard.', 'Monster', 'Spell', 'Trap', 'Select Card Type', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17601919,3,0,0,33,900,1000,3,16,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (17601919, 'Pumprincess the Princess of Ghosts', 'If this face-up card is destroyed while in a Monster Card Zone, you can place it face-up in your Spell & Trap Card Zone as a Continuous Spell Card, instead of sending it to the Graveyard. While this card is treated as a Continuous Spell Card by this effect, during each player''s Standby Phase: Place 1 Pumpkin Counter on this card. All monsters your opponent controls lose 100 ATK and DEF for each Pumpkin Counter on this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53090623,3,0,0,33,1000,1000,4,16,32,0);
INSERT OR REPLACE INTO "texts" VALUES (53090623, 'Yellow-Blooded Oni', 'When you Xyz Summon a monster: You can Special Summon this card from your hand. Once per turn: You can detach 1 Xyz Material from a monster you control, then target 1 face-up Xyz Monster on the field; reduce its Rank by 1, and if you do, it loses 300 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80485722,3,0,142,33,1600,1600,4,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (80485722, 'Vampire Hunter', 'At the start of the Damage Step, if this card battles a DARK monster: Destroy that monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16889337,3,0,0,545,800,1800,4,8,32,512);
INSERT OR REPLACE INTO "texts" VALUES (16889337, 'Aratama', 'Cannot be Special Summoned. During the End Phase of the turn this card is Normal Summoned or flipped face-up: Return it to the hand. When this card is Normal Summoned or flipped face-up: You can add 1 Spirit monster from your Deck to your hand, except “Aratama”.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43378076,3,0,0,545,1500,1900,4,4,4,16);
INSERT OR REPLACE INTO "texts" VALUES (43378076, 'Rasetsu', 'Cannot be Special Summoned. During the End Phase of the turn this card is Normal Summoned or flipped face-up: Return it to the hand. When this card is Normal Summoned or flipped face-up: You can reveal 1 Spirit monster in your hand, except "Rasetsu", then target 1 face-up Attack Position monster your opponent controls; return that target to the hand. You cannot Special Summon during the turn you activate this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (89362180,3,0,0,2081,1700,1400,4,16,32,2359296);
INSERT OR REPLACE INTO "texts" VALUES (89362180, 'Skelesaurus', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it become an Effect Monster with these effects.
● This card becomes EARTH Dinosaur-Type. When this card destroys an opponent''s monster by battle and sends it to the Graveyard: You can Special Summon that monster to your side of the field in face-up Defense Position, and if you do, it becomes Zombie-Type.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15767889,3,0,0,2081,1700,1600,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (15767889, 'Knight Day Grepher', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it become an Effect Monster with this effect.
● During your End Phase: You can target 1 Equip Spell Card in your Graveyard; add that target to your hand. You can only use this effect of "Knight Day Grepher" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42155488,3,0,0,4129,2200,1100,6,1048576,8,0);
INSERT OR REPLACE INTO "texts" VALUES (42155488, 'Genomix Fighter', 'You can Normal Summon this card without Tributing, but its original ATK is halved and its Level becomes 3. Once per turn: You can declare 1 Monster Type; if this card is used as a Synchro Material Monster this turn, treat this card and the other Synchro Material Monsters as that Monster Type for that Synchro Summon. If you activate this effect, you cannot Normal or Special Summon monsters for the rest of this turn, except monsters with the declared Monster Type.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78540593,3,0,0,33,2800,1600,8,1024,4,0);
INSERT OR REPLACE INTO "texts" VALUES (78540593, 'Mariña, Princess of Sunflowers', 'If exactly 1 other Plant-Type monster you control (and no other cards) is destroyed by battle or by card effect and sent to the Graveyard: You can target 1 card your opponent controls; destroy that target. This card must be face-up on the field to activate and to resolve this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15545291,3,0,190,33,2800,1000,8,256,1,16777219);
INSERT OR REPLACE INTO "texts" VALUES (15545291, 'Granmarg the Mega Monarch', 'You can Tribute Summon this card by Tributing 1 Tribute Summoned monster. When this card is Tribute Summoned: Target up to 2 Set cards on the field; destroy those targets. If this card was Tributed Summoned by Tributing an EARTH monster, add this additional effect.
● Also, draw 1 card after that.', 'Tribute summon with 1 monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41039846,3,0,0,33,1200,1800,5,512,32,0);
INSERT OR REPLACE INTO "texts" VALUES (41039846, 'Swarm of Crows', 'Cannot be Special Summoned from the Deck. Once per turn: You can change this card to face-down Defense Position. When this card is Flip Summoned: Discard 1 random card from your opponent''s hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77428945,3,0,0,33,1600,500,3,524288,1,0);
INSERT OR REPLACE INTO "texts" VALUES (77428945, 'Terrene Toothed Tsuchinoko', 'When this card is Special Summoned: Change all other Special Summoned monsters on the field to face-down Defense Position. You can only use the effect of "Terrene Toothed Tsuchinoko" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40217358,3,0,128,33,0,1000,1,8,2,0);
INSERT OR REPLACE INTO "texts" VALUES (40217358, 'Blue Duston', 'Cannot be used as a Fusion, Synchro, or Xyz Material for a Summon. While this card is face-up on the field, it cannot be Tributed. When this card on the field is destroyed: Banish 1 random card from the controller''s hand, face-down, until the next turn''s Standby Phase. You can only control 1 face-up "Blue Duston".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77205367,3,0,4722760,8388641,1000,1000,3,8,32,8192);
INSERT OR REPLACE INTO "texts" VALUES (77205367, 'Number C96: Dark Storm', '4 Level 3 DARK monsters
This card cannot be destroyed by battle, also all battle damage you take from battles involving this card is also inflicted to your opponent. If this card has "Number 96: Dark Mist" as an Xyz Material, it gains this effect.
● Once per battle, during either player''s turn, when an attack is declared involving this card and an opponent''s monster: You can detach 1 Xyz Material from this card; the ATK of that opponent''s monster becomes 0, and if it does, this card gains ATK equal to the original ATK of the opponent''s monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3790062,3,0,7143496,8388641,1300,0,2,8,32,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (3790062, 'Number 65: Djinn Buster', '2 Level 2 DARK monsters
During either player''s turn, when an effect of an opponent''s monster is activated: You can detach 2 Xyz Materials from this card; negate the activation, and if you do, inflict 500 damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49195710,3,0,4722760,8388641,1600,0,3,8,32,-2147475456);
INSERT OR REPLACE INTO "texts" VALUES (49195710, 'Number C65: King Overfiend', '3 Level 3 DARK monsters
Once per turn: You can detach 1 Xyz Material from this card, then target 1 face-up monster your opponent controls; it loses 1000 ATK and DEF. While this card has "Number 65: Djinn Buster" as an Xyz Material, it gains this effect.
●Effect Monsters your opponent controls cannot activate their effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76589815,3,0,132,8388641,0,1300,3,1,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (76589815, 'Battlin'' Boxer Cheat Commissioner', '2 Level 3 monsters
All monsters your opponent controls must attack, if able. While you control another "Battlin'' Boxer" monster, your opponent cannot target this card for attacks. When an attack is declared involving another "Battlin'' Boxer" monster you control: You can detach 2 Xyz Materials from this card; look at your opponent''s hand, then Set 1 Spell Card from their hand to your side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2978414,3,0,72,8388641,3000,3000,8,8192,16,-2147217408);
INSERT OR REPLACE INTO "texts" VALUES (2978414, 'Number 46: Dragluon', '2 Level 8 Dragon-Type monsters
Once per turn, if you control no other monsters: You can detach 1 Xyz Material from this card, then activate 1 of these effects.
● Special Summon 1 Dragon-Type monster from your hand.
● Target 1 Dragon-Type monster your opponent controls; take control of that target.
● Dragon-Type monsters your opponent controls cannot activate their effects until the end of your opponent''s turn.', 'Special Summon', 'Take Control of 1 Dragon-Type Monster', 'Negate effects of Dragon-Type Monsters', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39972129,3,0,72,8388641,1000,1000,2,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (39972129, 'Number 64: Ronin Raccoon Sandayu', '2 Level 2 Beast-Type monsters
Once per turn: You can detach 1 Xyz Material from this card; Special Summon 1 "Kagemusha Raccoon Token" (Beast-Type/EARTH/Level 1/ATK ?/DEF 0). (When Summoned, its ATK becomes equal to the current ATK of the monster on the field that has the highest ATK. Your choice, if tied.) While you control another Beast-Type monster, this card cannot be destroyed by battle or card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75367227,3,0,141,8388641,1800,1600,3,16,32,65554);
INSERT OR REPLACE INTO "texts" VALUES (75367227, 'Ghostrick Alucard', '2 Level 3 monsters
Your opponent cannot target other "Ghostrick" monsters, or any face-down Defense Position monsters, for attacks. You can detach 1 Xyz Material from this card, then target 1 Set card your opponent controls; destroy that target. You can only use this effect of "Ghostrick Alucard" once per turn. If this card is sent to the Graveyard: You can target 1 other "Ghostrick" card in your Graveyard; add that target to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1855932,3,0,136,8388641,2500,2000,4,32768,16,8320);
INSERT OR REPLACE INTO "texts" VALUES (1855932, 'Bujintei Kagutsuchi', '2 Level 4 Beast-Warrior-Type monsters
When this card is Xyz Summoned: Send the top 5 cards of your Deck to the Graveyard (or your entire Deck, if less than 5), also this card gains 100 ATK for each "Bujin" card sent to the Graveyard by this effect. If a "Bujin" Beast-Warrior-Type monster(s) you control would be destroyed by battle or by card effect, you can detach 1 Xyz Material from this card instead of destroying 1 of those monsters. You can only control 1 "Bujintei Kagutsuchi".', 'Detach Material?', 'Detach Material?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38250531,3,0,142,8388641,2500,0,5,16,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (38250531, 'Crimson Knight Vampire Bram', '2 Level 5 Zombie-Type monsters
You can detach 1 Xyz Material from this card, then target 1 monster in your opponent''s Graveyard; Special Summon that target to your side of the field, but if you do, only that monster can attack for the rest of this turn. You can only use this effect of "Crimson Knight Vampire Bram" once per turn. During the Standby Phase of the next turn after this card you controlled was destroyed by your opponent''s card (either by battle or by card effect) and sent to your Graveyard: Special Summon it from the Graveyard in face-up Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64245689,3,0,0,8388641,1700,900,3,1024,1,262272);
INSERT OR REPLACE INTO "texts" VALUES (64245689, 'Meliae of the Trees', '2 Level 3 EARTH monsters
Once per turn: You can detach 1 Xyz Material from this card, then activate 1 of these effects.
● Send 1 Plant-Type monster from your Deck to the Graveyard.
● Target 1 Plant-Type monster in your Graveyard; Special Summon that target in face-up Defense Position.', 'Send to grave', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1639384,3,0,0,8388641,2800,1800,8,1,16,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (1639384, 'Divine Dragon Knight Felgrand', '2 Level 8 monsters
Once per turn, during either player''s turn: You can detach 1 Xyz Material from this card, then target 1 face-up monster on the field; this turn, its effects are negated, but it is unaffected by other card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37038993,3,0,0,12321,800,1400,2,524288,4,8192);
INSERT OR REPLACE INTO "texts" VALUES (37038993, 'Puralis, the Purple Pyrotile', '1 Tuner + 1 non-Tuner monster
When this card is sent from the field to the Graveyard: All monsters your opponent currently controls lose 500 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63422098,3,0,0,8225,2900,2800,9,256,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (63422098, 'Giganticastle', '1 Tuner + 1 or more non-Tuner monsters
This card gains 200 ATK and DEF for each non-Tuner Synchro Material Monster used to Synchro Summon this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (917796,3,0,0,2,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (917796, 'Gagagatag', 'All "Gagaga" monsters you currently control gains 500 ATK for each "Gagaga" monster you currently control, until your next Standby Phase. You can only activate 1 "Gagagatag" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36916401,3,0,132,2,0,0,0,0,0,262272);
INSERT OR REPLACE INTO "texts" VALUES (36916401, 'Battlin'' Boxing Spirits', 'Send the top card of your Deck to the Graveyard, then target 1 "Battlin'' Boxer" monster in your Graveyard; Special Summon that target in face-up Defense Position. You can only activate 1 "Battlin'' Boxing Spirits" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63300440,3,0,0,262146,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (63300440, 'Dragon Shield', 'Equip only to a Dragon-Type monster. It cannot be destroyed by battle or card effects. Neither player takes battle damage from battles involving the equipped monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99795159,3,0,141,524290,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (99795159, 'Ghostrick Mansion', 'Monsters cannot attack face-down Defense Position monsters, but can attack directly if all monsters their opponent controls are face-down Defense Position. All effect damage, and battle damage inflicted by monsters other than "Ghostrick" monsters, is halved.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35183853,3,0,136,2,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (35183853, 'Bujin Regalia - The Mirror', 'At the start of your Main Phase 1, if your opponent controls more monsters than you do and you control a Beast-Warrior-Type "Bujin" monster: Until the end of your opponent''s next turn, Spell/Trap Cards, and their effects, cannot be activated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62188962,3,0,142,524290,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (62188962, 'Vampire Kingdom', 'Zombie-Type monsters gain 500 ATK during damage calculation only. Once per turn, when a card(s) is sent from your opponent''s Deck to the Graveyard: Target 1 card on the field; send 1 DARK "Vampire" monster from your hand or Deck to the Graveyard, and if you do, destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98672567,3,0,0,2,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (98672567, 'Pot of Dichotomy', 'At the start of your Main Phase 1: Target 3 monsters with different Types in your Graveyard; Shuffle all 3 into the Deck, then draw 2 cards. You cannot conduct your Battle Phase the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25067275,3,0,0,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (25067275, 'Swords at Dawn', 'Target 1 Equip Spell Card in your Graveyard and 1 appropriate monster on the field; equip the Equip Spell Card to that monster. Destroy that Equip Spell Card during the End Phase. If you activate this card, you cannot Special Summon for the rest of this turn. You can only activate 1 "Swords at Dawn" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61466310,3,0,190,131074,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (61466310, 'Return of the Monarchs', 'You cannot Special Summon monsters from the Extra Deck. When you Tribute Summon a monster: You can activate 1 of these effects;
● Add, from your Deck to your hand, 1 monster with 2400 ATK and 1000 DEF with a different name from that Tribute Summoned monster.
● Add, from your Deck to your hand, 1 monster with 2800 ATK and 1000 DEF with a different name from that Tribute Summoned monster.
The Tribute Summoned monster must be face-up on the field to activate and to resolve this effect. You can only activate this effect of "Return of the Monarchs" once per turn.', 'Add 1 monster.', 'Add 1 monster with 2400 ATK and 1000 DEF', 'Add 1 monster with 2800 ATK and 1000 DEF', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98850929,3,0,0,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (98850929, 'Sacred Serpent''s Wake', 'You can only activate 1 "Sacred Serpent''s Wake" per turn. If you control 2 or more different kinds of monsters (Ritual, Fusion, Synchro, or Xyz): Activate 1 or more effects, depending on the number of different kinds you control, and resolve in sequence.
● 2 or more: Target 1 monster in your Graveyard or 1 of your banished monsters; add that target to your hand.
● 3 or more: Target 1 Trap Card in your Graveyard; add that target to your hand.
● 4: Target 1 Spell Card in your Graveyard, except "Sacred Serpent''s Wake"; add that target to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24845628,3,0,0,262146,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (24845628, 'Magicalized Duston Mop', 'The equipped monster cannot be used as a Fusion, Synchro, or Xyz Material for a Summon, and it cannot be Tributed. When this card on the field is destroyed by your opponent''s card effect and sent to the Graveyard: You can add 1 "Duston" monster from your Deck to your hand. You can only control 1 "Duston Mop".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50243722,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (50243722, 'Burst Rebirth', 'Pay 2000 Life Points, then target 1 monster in your Graveyard; Special Summon that target in face-down Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97738431,3,0,72,4,0,0,0,0,0,1073741824);
INSERT OR REPLACE INTO "texts" VALUES (97738431, 'Numbers Overlay Boost', 'Target 1 "Number" Xyz Monster you control that has no Xyz Materials; attach 2 monsters from your hand to that face-up Xyz Monster, as Xyz Materials.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23122036,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (23122036, 'Intrigue Shield', 'Target 1 face-up monster you control; equip this card to that target. Once per turn, while the equipped monster is in face-up Attack Position, it cannot be destroyed by battle. You take no battle damage from attacks involving it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50527144,3,0,141,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (50527144, 'Ghostrick Vanish', 'Reveal 1 "Ghostrick" monster in your hand; this turn, "Ghostrick" cards you control, and face-down Defense Position monsters you control, cannot be targeted by, or be destroyed by, card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86516889,3,0,141,4,0,0,0,0,0,2048);
INSERT OR REPLACE INTO "texts" VALUES (86516889, 'Ghostrick Scare', 'Target any number of face-down Defense Position monsters you control; change them to face-up Defense Position, count the number of "Ghostrick" monsters among them, and if you do, change up to that many face-up monsters your opponent controls to face-down Defense Position (min. 1).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22900598,3,0,142,4,0,0,0,0,0,262656);
INSERT OR REPLACE INTO "texts" VALUES (22900598, 'Vampire Takeover', 'If you have no card in your Field Card Zone and all face-up monsters you control (min. 1) are Zombie-Type: Activate 1 "Vampire Kingdom" directly from your Deck, then, you can Special Summon 1 DARK "Vampire" monster from your Graveyard in face-up Defense Position. You can only activate 1 "Vampire Takeover" per turn.', 'Special Summon 1 DARK "Vampire" monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59305593,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (59305593, 'Mistake', 'Neither player can add cards from their Deck to their hand except by drawing them.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85893201,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (85893201, 'Chain Ignition', 'Once per turn, if a monster(s) your opponent controls is destroyed by your opponent''s card effect (except during the Damage Step): You can target 1 card on the field; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22888900,3,0,0,4,0,0,0,0,0,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (22888900, 'Grisaille Prison', 'If you control a face-up monster that was Tribute, Ritual or Fusion Summoned: Until the end of your opponent''s next turn, neither player can Synchro or Xyz Summon, Synchro and Xyz Monsters cannot attack, also their effects are negated.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58272005,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (58272005, 'Survival of the Fittest', 'Target 1 Dinosaur-Type monster you control; equip this card to that target. It gains 1000 ATK. When it destroys an opponent''s monster by battle and sends it to the Graveyard: The equipped monster can make a second attack on an opponent''s monster in a row.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84677654,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (84677654, 'BIG Win!?', 'Declare a Level between 1 and 12; each player tosses a coin, and if both are Heads, the Levels of all face-up monsters you currently control become the declared Level. If both are tails, you lose Life Points equal to the declared Level x 500.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
