BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (19041767,3,0,0,33,1500,0,4,2,2,16777216);
INSERT OR REPLACE INTO "texts" VALUES (19041767, 'Gemini Summoner', 'Once per turn, during your opponent''s End Phase, you can pay 500 Life Points to Normal Summon or Set 1 Gemini monster from your hand, or Normal Summon 1 face-up Gemini monster you control. Once per turn, if this card would be destroyed by battle, it is not destroyed.', 'Normal Summon', '召喚', 'セット', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97127906,3,0,12,17,1900,800,4,524288,1,0);
INSERT OR REPLACE INTO "texts" VALUES (97127906, 'Alien Shocktrooper', 'The Aliens have used a mysterious biological substance to create a supreme race of soldiers. They do not have the natural powers of the other Aliens, but can make stunning physical attacks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (33112041,3,0,50,17,500,500,1,128,4,0);
INSERT OR REPLACE INTO "texts" VALUES (33112041, 'Volcanic Rat', 'This mutated mouse dwells in the core of active volcanoes. No amount of heat is too much for it to bear.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60606759,3,0,6,17,100,2100,4,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (60606759, 'Renge, Gatekeeper of Dark World', 'His renowned athletic physique has made him famous with the populace of Dark World. They call him "Iron Wall Renge" because no one can break through his incredible defenses.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96005454,3,0,0,17,1700,100,3,8192,32,0);
INSERT OR REPLACE INTO "texts" VALUES (96005454, 'Hunter Dragon', 'This dragon has taken down countless prey with its sharp fangs. It strikes very quickly, because if it does not strike first, it is vulnerable to a counter-attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22499463,3,0,80,17,100,2000,4,524288,1,0);
INSERT OR REPLACE INTO "texts" VALUES (22499463, 'Venom Cobra', 'Hard scales cover all parts of this gigantic cobra. It hunts by shooting large amounts of venom, but because of its large size, its attack pattern is easily predicted.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79856792,3,0,0,33,4000,0,10,8192,16,271404);
INSERT OR REPLACE INTO "texts" VALUES (79856792, 'Rainbow Dragon', 'Cannot be Normal Summoned or Set. Must be Special Summoned (from your hand) by having 7 "Crystal Beast" cards with different names on your field or in your Graveyard, and cannot be Special Summoned by other ways. This card cannot activate its effects the turn it is Special Summoned. ● During either player''s turn: You can send all "Crystal Beast" monsters you control to the Graveyard; this card gains 1000 ATK for each card sent. ● You can banish all "Crystal Beast" monsters in your Graveyard; shuffle all cards on the field into the Decks.', 'Send all "Crystal Beast" monsters you control to the Graveyard', 'Banish all "Crystal Beast" monsters in your Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43751755,3,0,30,33,800,300,2,16384,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (43751755, 'Chrysalis Pantail', 'You can Tribute this card while "Neo Space" is on the field to Special Summon 1 "Neo-Spacian Dark Panther" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17363041,3,0,30,33,600,400,2,512,8,262144);
INSERT OR REPLACE INTO "texts" VALUES (17363041, 'Chrysalis Chicky', 'You can Tribute this card while "Neo Space" is on the field to Special Summon 1 "Neo-Spacian Air Hummingbird" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29246354,3,0,30,33,100,700,2,1024,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (29246354, 'Chrysalis Pinny', 'You can Tribute this card while "Neo Space" is face-up on the field to Special Summon 1 "Neo-Spacian Glow Moss" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16241441,3,0,30,33,300,300,2,2048,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (16241441, 'Chrysalis Larva', 'You can Tribute this card while "Neo Space" is on the field to Special Summon 1 "Neo-Spacian Flare Scarab" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42239546,3,0,30,33,700,100,2,256,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (42239546, 'Chrysalis Mole', 'You can Tribute this card while "Neo Space" is face-up on the field to Special Summon 1 "Neo-Spacian Grand Mole" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4906301,3,0,0,33,600,1300,3,1,32,65536);
INSERT OR REPLACE INTO "texts" VALUES (4906301, 'Necro Gardna', 'During your opponent''s turn: You can banish this card from your Graveyard; negate the next attack this turn from a monster your opponent controls (this is a Quick Effect).', '1次攻击无效', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8062132,3,0,0,33,0,0,10,524288,32,100934656);
INSERT OR REPLACE INTO "texts" VALUES (8062132, 'Vennominaga the Deity of Poisonous Snakes', 'Cannot be Normal Summoned or Set. Must first be Special Summoned with "Rise of the Snake Deity" and cannot be Special Summoned by other ways except by its own effect. This card gains 500 ATK for each Reptile-Type monster in your Graveyard. This card cannot be targeted by, and is unaffected by, Spell/Trap effects and other Effect Monsters'' effects. When this card is destroyed by battle and sent to the Graveyard: You can banish 1 other Reptile-Type monster from your Graveyard; Special Summon this card. When this card inflicts Battle Damage to your opponent: Place 1 Hyper-Venom Counter on it. When 3 Hyper-Venom Counters are on this card, you win the Duel.', 'Special Summon', 'Place counter', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72677437,3,0,0,33,0,0,8,524288,32,34873348);
INSERT OR REPLACE INTO "texts" VALUES (72677437, 'Vennominon the King of Poisonous Snakes', 'Cannot be Special Summoned by another Effect Monster''s effect. This card is unaffected by "Venom Swamp". This card gains 500 ATK for each Reptile-Type monster in your Graveyard. When this card is destroyed by battle and sent to the Graveyard: You can banish 1 other Reptile-Type monster from your Graveyard; Special Summon this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73899015,3,0,80,33,1200,600,3,524288,1,67174400);
INSERT OR REPLACE INTO "texts" VALUES (73899015, 'Venom Snake', 'Once per turn, you can place 1 Venom Counter on 1 monster your opponent controls. If you activate this effect, this card cannot attack during this turn.', 'Place counter', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9284723,3,0,80,33,1600,1200,5,524288,1,67108864);
INSERT OR REPLACE INTO "texts" VALUES (9284723, 'Venom Boa', 'Once per turn, you can place 2 Venom Counters on 1 monster your opponent controls. If you activate this effect, this card cannot attack during this turn.', 'Place counter', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36278828,3,0,80,33,1000,800,4,524288,32,67108864);
INSERT OR REPLACE INTO "texts" VALUES (36278828, 'Venom Serpent', 'Once per turn, you can place 1 Venom Counter on 1 monster your opponent controls.', 'Place counter', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (69884162,3,0,602120,2081,1900,1300,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (69884162, 'Elemental HERO Neos Alius', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it become an Effect Monster with this effect.
● This face-up card''s name becomes "Elemental HERO Neos".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95888876,3,0,0,2081,2400,1500,6,8192,4,32768);
INSERT OR REPLACE INTO "texts" VALUES (95888876, 'Chthonian Emperor Dragon', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect:
● This card can attack twice during the same Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22377815,3,0,0,2081,1500,500,4,64,2,64);
INSERT OR REPLACE INTO "texts" VALUES (22377815, 'Aquarian Alessa', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect:
● When this card destroys an opponent''s monster by battle and sends it to the Graveyard, they discard 1 random card.', 'Discard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68762510,3,0,0,2081,1500,500,4,4,8,256);
INSERT OR REPLACE INTO "texts" VALUES (68762510, 'Lucky Pied Piper', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect:
● When this card destroys an opponent''s monster by battle and sends it to the Graveyard, draw 1 card.', 'Draw', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95166228,3,0,0,2081,2350,1000,5,2048,1,32768);
INSERT OR REPLACE INTO "texts" VALUES (95166228, 'Grasschopper', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect:
● This card can attack all monsters your opponent controls once each.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21155323,3,0,0,2081,1500,500,4,256,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (21155323, 'Goggle Golem', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect:
● The original ATK of this card becomes 2100.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57549932,3,0,0,2081,1500,500,3,1,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (57549932, 'Dawnbreak Gardna', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect:
● The original DEF of this card becomes 2300.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94944637,3,0,0,2081,2400,2000,6,2,32,1310720);
INSERT OR REPLACE INTO "texts" VALUES (94944637, 'Doom Shaman', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect:
● Once per turn, you can Special Summon 1 Fiend-Type monster from your hand or from either player''s Graveyard. When this card is removed from the field, destroy all Fiend-Type monsters Special Summoned by this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20438745,3,0,0,2081,1500,500,5,128,4,4194304);
INSERT OR REPLACE INTO "texts" VALUES (20438745, 'King Pyron', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect:
● Once per turn, you can inflict 1000 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57827484,3,0,0,2081,1500,500,4,8,32,131072);
INSERT OR REPLACE INTO "texts" VALUES (57827484, 'Shadow Delver', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect:
● Once per turn, you can select 1 face-up level 4 or lower DARK monster you control. It can attack your opponent directly this turn.', 'Activated', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83812099,3,0,0,33,1500,800,4,32,16,16777216);
INSERT OR REPLACE INTO "texts" VALUES (83812099, 'Flint Lock', 'Once per turn, you can equip a "Flint" on the field to this card. You can take any "Flint" equipped to this card and equip it to another face-up monster. This card can only be equipped with one "Flint" at a time. While equipped with "Flint", this card is unaffected by "Flint''s" effect and cannot be destroyed by battle.', 'Equip', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29216198,3,0,0,2097185,1100,700,3,8,32,2048);
INSERT OR REPLACE INTO "texts" VALUES (29216198, 'Gravitic Orb', 'FLIP: Change the battle positions of all face-up monsters your opponent controls.', 'Change battle position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56605802,3,0,0,2097185,300,1000,2,2048,1,32);
INSERT OR REPLACE INTO "texts" VALUES (56605802, 'Phantom Cricket', 'FLIP: Return 1 face-down monster from the field to the top of its owner''s Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82099401,3,0,0,2097185,100,100,1,2,2,512);
INSERT OR REPLACE INTO "texts" VALUES (82099401, 'Crystal Seer', 'FLIP: Pick up 2 cards from the top of your Deck. Select 1 of those cards and add it to your hand, and place the other card on the bottom of your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19594506,3,0,9,33,1800,800,4,1,16,512);
INSERT OR REPLACE INTO "texts" VALUES (19594506, 'Neo Space Pathfinder', 'You can discard this card to the Graveyard to add 1 "Neo Space" from your Deck or Graveyard to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55589254,3,0,0,33,2300,2000,6,8192,2,262146);
INSERT OR REPLACE INTO "texts" VALUES (55589254, 'Frost and Flame Dragon', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by removing from play 1 FIRE and 2 WATER monsters from your Graveyard. Once per turn, you can discard 1 card to destroy 1 monster on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81977953,3,0,0,33,2300,2000,6,8,8,262145);
INSERT OR REPLACE INTO "texts" VALUES (81977953, 'Desert Twister', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by removing from play 1 EARTH and 2 WIND monsters from your Graveyard. Once per turn, you can discard 1 card to destroy 1 Spell or Trap Card on the field.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34334692,3,0,0,33,300,300,1,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (34334692, 'Ritual Raven', 'If you Ritual Summon a DARK Ritual Monster, this 1 card can be used as the entire Tribute.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18372968,3,0,0,33,1500,300,3,524288,1,2);
INSERT OR REPLACE INTO "texts" VALUES (18372968, 'Razor Lizard', 'When this card attacks a face-down Defense Position monster while there is another Reptile-Type monster on your side of the field besides this card, destroy the monster immediately with this card''s effect without flipping it face-up, or applying damage calculation.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54766667,3,0,0,33,1500,0,4,4,16,2097152);
INSERT OR REPLACE INTO "texts" VALUES (54766667, 'Light Effigy', 'If you Tribute Summon a LIGHT Normal Monster, you can treat this 1 monster as 2 Tributes.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81755371,3,0,0,33,1500,0,4,8,32,2097152);
INSERT OR REPLACE INTO "texts" VALUES (81755371, 'Dark Effigy', 'If you Tribute Summon a DARK Normal Monster, you can treat this 1 monster as 2 Tributes.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17259470,3,0,0,33,1800,0,4,16,32,1311744);
INSERT OR REPLACE INTO "texts" VALUES (17259470, 'Zombie Master', 'Once per turn: You can send 1 monster from your hand to the Graveyard, then target 1 Level 4 or lower Zombie-Type monster in either player''s Graveyard; Special Summon that target. This card must be face-up on the field to activate and to resolve this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78734254,3,17955766,31,97,900,1100,4,1,2,4194306);
INSERT OR REPLACE INTO "texts" VALUES (78734254, 'Neo-Spacian Marine Dolphin', 'This card''s name is also treated as "Neo-Spacian Aqua Dolphin". This card cannot be Special Summoned except with "NEX". Once per turn, you can discard 1 card to look at your opponent''s hand and select 1 Monster Card in it. If you control a monster with an ATK greater than or equal to the selected monster''s, destroy the selected card and inflict 500 damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5128859,3,0,602120,97,2800,2300,8,1,2,64);
INSERT OR REPLACE INTO "texts" VALUES (5128859, 'Elemental HERO Marine Neos', '"Elemental HERO Neos" + "Neo-Spacian Marine Dolphin"
Must first be Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization"). Once per turn: You can destroy 1 random card in your opponent''s hand.', '手札破壊', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41517968,3,0,12296,97,2000,1000,6,1,32,16386);
INSERT OR REPLACE INTO "texts" VALUES (41517968, 'Elemental HERO Darkbright', '"Elemental HERO Sparkman" + "Elemental HERO Necroshade"
Must be Fusion Summoned and cannot be Special Summoned by other ways. If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent. If this card attacks, change it to Defense Position at the end of the Damage Step. If this card is destroyed: Target 1 monster your opponent controls; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78512663,3,0,602120,97,3000,2500,9,1,4,8240);
INSERT OR REPLACE INTO "texts" VALUES (78512663, 'Elemental HERO Magma Neos', '"Elemental HERO Neos" + "Neo-Spacian Flare Scarab" + "Neo-Spacian Grand Mole"
Must be first Special Summoned (from your Extra Deck) by shuffling the above cards you control into the Deck. (You do not use "Polymerization"). This card gains 400 ATK for each card on the field. During the End Phase: Shuffle this card into the Extra Deck. When this card is shuffled into the Extra Deck this way: Return all cards on the field to the hand.', 'Back to Extra Deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40391316,3,0,15,97,0,2500,5,16384,16,0);
INSERT OR REPLACE INTO "texts" VALUES (40391316, 'Ojama Knight', '2 "Ojama" monsters
Select up to 2 of your opponent''s Monster Card Zones. The selected zones cannot be used.', 'Select Monster Card Zone?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55428811,3,0,0,2,0,0,0,0,0,288);
INSERT OR REPLACE INTO "texts" VALUES (55428811, 'Fifth Hope', 'Target 5 "Elemental HERO" cards in your Graveyard; shuffle them into the Deck, then draw 2 cards (draw 3 cards instead, if you had no other cards on your side of the field and in your hand when you activated this card).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18302224,3,0,9,65538,0,0,0,0,0,270336);
INSERT OR REPLACE INTO "texts" VALUES (18302224, 'Reverse of Neos', 'Activate only when a face-up "Neos" Fusion Monster you control is destroyed. Special Summon 1 "Elemental HERO Neos" from your Deck in Attack Position. It gains 1000 ATK and is destroyed during the End Phase of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82639107,3,0,0,2,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (82639107, 'Convert Contact', 'Activate only while you control no monsters. Send 1 "Neo-Spacian" monster from your hand and 1 from your Deck to the Graveyard. Then draw 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80368942,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (80368942, 'Cocoon Party', 'Special Summon 1 "Chrysalis" monster from your Deck for each "Neo-Spacian" monster with a different name in your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81913510,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (81913510, 'NEX', 'Send 1 face-up "Neo-Spacian" monster you control to the Graveyard. Special Summon 1 Level 4 monster with the same name from your Extra Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43644025,3,0,0,131074,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (43644025, 'Cocoon Rebirth', 'You can Tribute 1 face-up "Chrysalis" monster you control to Special Summon 1 "Neo-Spacian" monster written in the card text of that card from either player''s Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54306223,3,0,80,524290,0,0,0,0,0,67117058);
INSERT OR REPLACE INTO "texts" VALUES (54306223, 'Venom Swamp', 'During each player''s End Phase: Place 1 Venom Counter on each face-up monster, except "Venom" monsters. Monsters lose 500 ATK for each Venom Counter on them. Destroy a monster if its ATK becomes 0 by this effect.', 'Place counter', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17189677,3,0,0,2,0,0,0,0,0,1048584);
INSERT OR REPLACE INTO "texts" VALUES (17189677, 'Snake Rain', 'Discard 1 card. Select 4 Reptile-Type monsters from your Deck and send them to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60728397,3,0,80,2,0,0,0,0,0,67108872);
INSERT OR REPLACE INTO "texts" VALUES (60728397, 'Venom Shot', 'Activate only while you control a face-up "Venom" monster, "Vennominaga the Deity of Poisonous Snakes", or "Vennominon the King of Poisonous Snakes". Send 1 Reptile-Type monster from your Deck to the Graveyard and place 2 Venom Counters on 1 face-up monster your opponent controls.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80033124,3,0,147,2,0,0,0,0,0,268697600);
INSERT OR REPLACE INTO "texts" VALUES (80033124, 'Cyberdark Impact!', 'Return 1 "Cyberdark Edge", "Cyberdark Keel" and "Cyberdark Horn" from your side of the field, hand, or Graveyard to your Deck. Special Summon 1 "Cyberdark Dragon" from your Extra Deck. (This Special Summon is treated as a Fusion Summon.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16437822,3,0,0,65538,0,0,0,0,0,34);
INSERT OR REPLACE INTO "texts" VALUES (16437822, 'Flint Missile', 'Destroy 1 monster equipped with "Flint". You can return this card to your Deck instead of sending it to the Graveyard after it resolves.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43422537,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (43422537, 'Double Summon', 'You can conduct 2 Normal Summons/Sets this turn, not just 1.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (79816536,3,0,0,2,0,0,0,0,0,512);
INSERT OR REPLACE INTO "texts" VALUES (79816536, 'Summoner''s Art', 'Add 1 Level 5 or higher Normal Monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15305240,3,0,0,2,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (15305240, 'Creature Seizure', 'Each player gives their opponent control of 1 of their monsters (controller''s choice). You must choose a face-up Normal Monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42709949,3,0,0,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (42709949, 'Phalanx Pike', 'The equipped monster gains 900 ATK for each card in either Graveyard that has the same name it does.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (78794994,3,0,0,262146,0,0,0,0,0,262146);
INSERT OR REPLACE INTO "texts" VALUES (78794994, 'Symbols of Duty', 'Send 1 Normal Monster you control to the Graveyard. Select and Special Summon 1 monster from either Graveyard and equip it with this card. When this card is removed from the field, destroy the equipped monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5183693,3,0,0,262146,0,0,0,0,0,8224);
INSERT OR REPLACE INTO "texts" VALUES (5183693, 'Amulet of Ambition', 'Equip only to a Normal Monster. If it battles a monster with a higher Level, the equipped monster gains 500 ATK x the difference in Levels (during that battle only). When this card is sent to the Graveyard, you can return it to the top of your Deck.', '回到卡组最上面', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (41587307,3,0,96,262146,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (41587307, 'Broken Bamboo Sword', 'The equipped monster gains 0 ATK.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43452193,3,0,0,4,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (43452193, 'Mirror Gate', 'When an opponent''s monster declares an attack targeting a face-up "Elemental HERO" monster you control: Switch control of the opponent''s attacking monster with the targeted monster you control, then calculate damage. Control of both monsters switches back during the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19024706,3,0,0,4,0,0,0,0,0,262146);
INSERT OR REPLACE INTO "texts" VALUES (19024706, 'Hero Counterattack', 'When an "Elemental HERO" monster you control is destroyed by battle: Your opponent chooses and reveals 1 random card from your hand, then, if it is an "Elemental HERO" monster, you destroy 1 monster your opponent controls and Special Summon the chosen monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56641453,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (56641453, 'Cocoon Veil', 'Activate by Tributing 1 face-up "Chrysalis" monster. This turn, any damage to a player caused by an effect becomes 0. Special Summon 1 "Neo-Spacian" monster written on the "Chrysalis" monster you Tributed, from your hand, Deck or from either player''s Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81791932,3,0,0,4,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (81791932, 'Snake Whistle', 'Activate only when a Reptile-Type monster you control is destroyed. Special Summon 1 Level 4 or lower Reptile-Type monster from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44584775,3,0,0,131076,0,0,0,0,0,1310720);
INSERT OR REPLACE INTO "texts" VALUES (44584775, 'Damage - Reptile', 'Once per turn, when you take Battle Damage from a battle involving a Reptile-Type monster, you can Special Summon 1 Reptile-Type monster from your Deck with ATK less than or equal to the Battle Damage you took.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80678380,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (80678380, 'Snake Deity''s Command', 'Activate by showing your opponent 1 "Venom" monster in your hand. Negate the activation and effect of an opponent''s Spell Card, and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16067089,3,0,0,4,0,0,0,0,0,262656);
INSERT OR REPLACE INTO "texts" VALUES (16067089, 'Rise of the Snake Deity', 'When a face-up "Vennominon the King of Poisonous Snakes" you control is destroyed, except by battle: Special Summon 1 "Vennominaga the Deity of Poisonous Snakes" from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77972406,3,0,0,4,0,0,0,0,0,67108864);
INSERT OR REPLACE INTO "texts" VALUES (77972406, 'Ambush Fangs', 'Activate only when a face-up "Venom" monster you control is declared as an attack target. Negate the attack and end the Battle Phase. Then place 1 Venom Counter on the monster that attacked.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (4466015,3,0,80,4,0,0,0,0,0,71303168);
INSERT OR REPLACE INTO "texts" VALUES (4466015, 'Venom Burn', 'Select 1 monster with a Venom Counter(s). Remove all Venom Counters from that card, and inflict 700 damage to your opponent for each Venom Counter removed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40465719,3,0,0,4,0,0,0,0,0,268);
INSERT OR REPLACE INTO "texts" VALUES (40465719, 'Common Charity', 'Draw 2 cards, then remove from play 1 Normal Monster Card from your hand. If you don''t have any Normal Monster Cards in your hand to remove, send all cards in your hand to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77859858,3,0,0,131076,0,0,0,0,0,4194560);
INSERT OR REPLACE INTO "texts" VALUES (77859858, 'Destructive Draw', 'If either player has no cards in their hand at the start of their Draw Phase, they can draw 1 more card in addition to their normal draw. This card''s controller loses 700 Life Points during their End Phase. (If less than 700, they become 0 instead). When this face-up card is removed from the field, inflict 3000 damage to the player who controlled it.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3244563,3,0,0,4,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (3244563, 'Shield Spear', 'Target 1 face-up monster on the field; it gains 400 ATK and DEF until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30643162,3,0,0,4,0,0,0,0,0,24576);
INSERT OR REPLACE INTO "texts" VALUES (30643162, 'Strike Slash', 'When a monster you control declares an attack: Until the End Phase, that monster gains 700 ATK, also, if it attacks a Defense Position monster, inflict piercing battle damage to your opponent.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76137276,3,0,0,4,0,0,0,0,0,1024);
INSERT OR REPLACE INTO "texts" VALUES (76137276, 'Spell Reclamation', 'Discard 1 card and chain this card to a Spell Card you activated. Whenever that Spell Card is sent to the Graveyard, return it to its owner''s hand.', '手札を１枚捨ててチェーン発動', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2122975,3,0,0,4,0,0,0,0,0,1024);
INSERT OR REPLACE INTO "texts" VALUES (2122975, 'Trap Reclamation', 'Discard 1 card and chain this card to a Trap Card you activated. Whenever that Trap Card is sent to the Graveyard, return it to its owner''s hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39526584,3,0,0,4,0,0,0,0,0,8388608);
INSERT OR REPLACE INTO "texts" VALUES (39526584, 'Gift Card', 'Your opponent gains 3000 Life Points.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (5915629,3,0,0,4,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (5915629, 'The Gift of Greed', 'Your opponent draws 2 cards.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42309337,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (42309337, 'Counter Counter', 'Negate the activation of a Counter Trap Card, and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81434470,3,0,0,33,300,2100,5,131072,2,262144);
INSERT OR REPLACE INTO "texts" VALUES (81434470, 'Thousand-Eyes Jellyfish', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by Tributing 1 "Ocean''s Keeper". Your opponent must play with their hand revealed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18828179,3,0,0,33,2400,1000,6,131072,2,262147);
INSERT OR REPLACE INTO "texts" VALUES (18828179, 'Cranium Fish', 'You can Special Summon this card by Tributing 1 "Ocean''s Keeper". You can discard 1 WATER monster to the Graveyard to destroy 1 face-down card.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44223284,3,0,0,33,1700,600,4,131072,2,17039360);
INSERT OR REPLACE INTO "texts" VALUES (44223284, 'Abyssal Kingshark', 'Once per turn, if this card would be destroyed by an effect that does not target it, it is not destroyed.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (17706537,3,0,0,33,1800,0,4,256,1,4194304);
INSERT OR REPLACE INTO "texts" VALUES (17706537, 'Fossil Tusker', 'When this card destroys an opponent''s monster by battle and sends it to the Graveyard, inflict 400 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (43191636,3,0,0,2081,1500,1000,4,131072,2,10240);
INSERT OR REPLACE INTO "texts" VALUES (43191636, 'Phantom Dragonray Bronto', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect:
● The original ATK of this card becomes 2300. If this card attacks, it is changed to Defense Position at the end of the Battle Phase. This card''s battle position cannot be changed until the end of your next turn, except with a card effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70595331,3,0,0,2081,2100,800,6,16,32,1310720);
INSERT OR REPLACE INTO "texts" VALUES (70595331, 'Il Blud', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it become an Effect Monster with this effect.
● Once per turn: You can Special Summon 1 Zombie-Type monster from your hand or from either player''s Graveyard. When this card leaves the field, destroy all Zombie-Type monsters Special Summoned by this card''s effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (16984449,3,0,0,2081,1500,1500,4,2048,4,263168);
INSERT OR REPLACE INTO "texts" VALUES (16984449, 'Blazewing Butterfly', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is face-up on the field, you can Normal Summon it to have it be treated as an Effect Monster with this effect:
● You can Tribute this card to Special Summon 1 Gemini monster from your Graveyard, except "Blazewing Butterfly". A Gemini monster Special Summoned by this effect is treated as an Effect Monster, and gains its effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
