BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (21844576,3,0,12296,17,1000,1000,3,1,8,0);
INSERT OR REPLACE INTO "texts" VALUES (21844576, 'Elemental HERO Avian', 'A winged Elemental HERO who wheels through the sky and manipulates the wind. His signature move, Featherbreak, gives villainy a blow from sky-high.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58932615,3,0,12296,17,1200,800,3,1,4,0);
INSERT OR REPLACE INTO "texts" VALUES (58932615, 'Elemental HERO Burstinatrix', 'A flame manipulator who was the first Elemental HERO woman. Her Burstfire burns away villainy.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84327329,3,0,12296,17,800,2000,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (84327329, 'Elemental HERO Clayman', 'An Elemental HERO with a clay body built-to-last. He''ll preserve his Elemental HERO colleagues at any cost.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20721928,3,0,12296,17,1600,1400,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (20721928, 'Elemental HERO Sparkman', 'An Elemental HERO and a warrior of light who proficiently wields many kinds of armaments. His Static Shockwave cuts off the path of villainy.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57116033,3,0,164,33,300,200,1,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (57116033, 'Winged Kuriboh', 'If this card on the field is destroyed and sent to the Graveyard: Any further Battle Damage you take this turn becomes 0.', 'Reduce damage to 0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83104731,3,0,7,33,3000,3000,8,32,1,16384);
INSERT OR REPLACE INTO "texts" VALUES (83104731, 'Ancient Gear Golem', 'Cannot be Special Summoned. If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. If this card attacks, your opponent cannot activate any Spell/Trap Cards until the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10509340,3,0,7,33,2000,2000,6,32,1,-2147483648);
INSERT OR REPLACE INTO "texts" VALUES (10509340, 'Ancient Gear Beast', 'This card cannot be Special Summoned. The effects of your opponent''s monsters that this card destroys by battle are negated. If this card attacks, your opponent cannot activate any Spell or Trap Cards until the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56094445,3,0,7,33,1300,1300,4,32,1,0);
INSERT OR REPLACE INTO "texts" VALUES (56094445, 'Ancient Gear Soldier', 'If this card attacks, your opponent cannot activate any Spell or Trap Cards until the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82482194,3,0,0,33,2000,1800,5,2048,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (82482194, 'Millennium Scorpion', 'Each time this card destroys 1 monster on your opponent''s side of the field by battle and sends it to the Graveyard, this card gains 500 ATK.', 'Gain attack', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (19877898,3,0,65,33,2600,1200,7,2048,8,8192);
INSERT OR REPLACE INTO "texts" VALUES (19877898, 'Ultimate Insect LV7', 'If this card was Special Summoned by the effect of "Ultimate Insect LV5", while it remains on the field all your opponent''s monsters lose 700 ATK and DEF.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45871897,3,0,82,33,100,-2,4,256,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (45871897, 'Lost Guardian', 'The original DEF of this card becomes the number of your Rock-Type monsters that are removed from play × 700.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82260502,3,0,92,33,2400,1200,6,256,1,65536);
INSERT OR REPLACE INTO "texts" VALUES (82260502, 'Hieracosphinx', 'Your opponent cannot select a face-down Defense Position monster as an attack target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18654201,3,0,92,33,1200,2400,6,256,1,8);
INSERT OR REPLACE INTO "texts" VALUES (18654201, 'Criosphinx', 'When a monster is returned from the field to the owner''s hand, the owner of the returned monster selects and sends 1 card in their hand to the Graveyard.', 'Send to Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45159319,3,0,0,33,1100,2000,4,256,1,2048);
INSERT OR REPLACE INTO "texts" VALUES (45159319, 'Moai Interceptor Cannons', 'Once per turn, you can flip this card into face-down Defense Position.', 'Flip into face-down Defense Position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71544954,3,0,0,33,-2,-2,7,256,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (71544954, 'Megarock Dragon', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by removing from play a Rock-Type monster(s) in your Graveyard. The original ATK and DEF of this card become the number of Rock-Type monsters you removed from play when you Special Summoned this card x 700.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13532663,3,0,0,2097185,800,800,2,256,1,4096);
INSERT OR REPLACE INTO "texts" VALUES (13532663, 'Dummy Golem', 'FLIP: Your opponent selects 1 monster that they control. Switch control of the selected monster and this card.', 'コントロールを入れ替える', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (40937767,3,0,0,33,1600,1500,4,256,1,4194304);
INSERT OR REPLACE INTO "texts" VALUES (40937767, 'Grave Ohja', 'While there is a face-down Defense Position monster(s) on your side of the field, no player can select this card as an attack target. Each time a monster on your side of the field is Flip Summoned, inflict 300 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76321376,3,0,0,33,1000,1900,3,256,1,4194304);
INSERT OR REPLACE INTO "texts" VALUES (76321376, 'Mine Golem', 'When this card is destroyed by battle and sent to the Graveyard, inflict 500 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3810071,3,0,0,33,1300,1000,3,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (3810071, 'Monk Fighter', 'Battle Damage to this card''s controller from a battle involving this card becomes 0.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (49814180,3,0,0,33,1900,1000,5,256,1,294912);
INSERT OR REPLACE INTO "texts" VALUES (49814180, 'Master Monk', 'This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by Tributing 1 "Monk Fighter". This card can attack twice during the same turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75209824,3,0,82,33,800,1400,4,256,1,2064);
INSERT OR REPLACE INTO "texts" VALUES (75209824, 'Guardian Statue', 'Once per turn, you can flip this card into face-down Defense Position. When this card is Flip Summoned, return 1 monster on your opponent''s side of the field to its owner''s hand.', 'Flip into face-down Defense Position', 'Return to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2694423,3,0,62,33,500,600,2,256,1,2050);
INSERT OR REPLACE INTO "texts" VALUES (2694423, 'Medusa Worm', 'Once per turn, you can flip this card into face-down Defense Position. When this card is Flip Summoned, destroy 1 monster on your opponent''s side of the field.', 'Flip into face-down Defense Position', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (48092532,3,0,0,33,1800,200,4,1,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (48092532, 'D.D. Survivor', 'During the End Phase, if this card was banished while face-up, on your side of the field, this turn: Special Summon this banished card. This effect can only activate once per turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75487237,3,0,0,33,100,1800,4,1,1,-2147481600);
INSERT OR REPLACE INTO "texts" VALUES (75487237, 'Mid Shield Gardna', 'Once per turn, you can flip this card into face-down Defense Position. Negate the activation of a Spell Card that targets this 1 face-down monster. At that time, flip this card into face-up Defense Position.', 'Flip into face-down Defense Position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1571945,3,0,43,2097185,1500,800,4,1,16,2);
INSERT OR REPLACE INTO "texts" VALUES (1571945, 'White Ninja', 'FLIP: Destroy 1 Defense Position monster.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37970940,3,0,191,2097185,500,1500,3,2,1,2101248);
INSERT OR REPLACE INTO "texts" VALUES (37970940, 'Aussa the Earth Charmer', 'FLIP: While this card is face-up on the field, take control of 1 EARTH monster your opponent controls.', 'Take control of 1 opponent EARTH monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (74364659,3,0,191,2097185,500,1500,3,2,2,2101248);
INSERT OR REPLACE INTO "texts" VALUES (74364659, 'Eria the Water Charmer', 'FLIP: Take control of 1 WATER monster on your opponent''s side of the field for as long as this card remains face-up on the field.', 'Take control of 1 opponent WATER monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (759393,3,0,191,2097185,500,1500,3,2,4,4096);
INSERT OR REPLACE INTO "texts" VALUES (759393, 'Hiita the Fire Charmer', 'FLIP: Take control of 1 FIRE monster on your opponent''s side of the field for as long as this card remains face-up on the field.', 'Take control of 1 FIRE monster on your opponent''s side of the field', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37744402,3,0,191,2097185,500,1500,3,2,8,2101248);
INSERT OR REPLACE INTO "texts" VALUES (37744402, 'Wynn the Wind Charmer', 'FLIP: While this card is face-up on the field, take control of 1 WIND monster your opponent controls.', 'Take control of 1 opponent WIND monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63142001,3,0,40,33,0,0,3,4096,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (63142001, 'Batteryman AA', 'If all "Batteryman AA"(s) you control are in Attack Position, this card gains 1000 ATK for each. If all "Batteryman AA"(s) you control are in Defense Position, this card gains 1000 DEF for each.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9637706,3,0,0,33,1600,300,3,16384,1,0);
INSERT OR REPLACE INTO "texts" VALUES (9637706, 'Des Wombat', 'Any damage to you from a card effect becomes 0.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36021814,3,0,0,33,-2,0,1,16,32,270340);
INSERT OR REPLACE INTO "texts" VALUES (36021814, 'King of the Skull Servants', 'The original ATK of this card is the combined number of "King of the Skull Servants" and "Skull Servant" in your Graveyard x 1000. When this card is destroyed by battle and sent to the Graveyard: You can banish 1 other "King of the Skull Servants" or "Skull Servant" from your Graveyard; Special Summon this card.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62420419,3,0,0,161,2500,1500,8,8,16,4096);
INSERT OR REPLACE INTO "texts" VALUES (62420419, 'Reshef the Dark Being', 'This card can only be Ritual Summoned with the Ritual Spell Card, "Final Ritual of the Ancients". Once per turn, by discarding 1 Spell Card from your hand, take control of 1 monster on your opponent''s side of the field until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (99414168,3,0,0,161,1200,1400,3,2,16,2097152);
INSERT OR REPLACE INTO "texts" VALUES (99414168, 'Elemental Mistress Doriado', 'This card can only be Ritual Summoned with the Ritual Spell Card, "Doriado''s Blessing". The Attribute of this card is also treated as WIND, WATER, FIRE, and EARTH while it is face-up on the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35809262,3,0,12296,97,2100,1200,6,1,8,4194304);
INSERT OR REPLACE INTO "texts" VALUES (35809262, 'Elemental HERO Flame Wingman', '"Elemental HERO Avian" + "Elemental HERO Burstinatrix"
Must be Fusion Summoned and cannot be Special Summoned by other ways. When this card destroys a monster by battle and sends it to the Graveyard: Inflict damage to your opponent equal to the ATK of the destroyed monster.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61204971,3,0,12296,97,2400,1500,6,1,16,2);
INSERT OR REPLACE INTO "texts" VALUES (61204971, 'Elemental HERO Thunder Giant', '"Elemental HERO Sparkman" + "Elemental HERO Clayman"
Must be Fusion Summoned and cannot be Special Summoned by other ways. Once per turn: You can discard 1 card to target 1 face-up monster on the field with original ATK less than the ATK of this card; destroy that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (42664989,3,0,0,2,0,0,0,0,0,256);
INSERT OR REPLACE INTO "texts" VALUES (42664989, 'Card of Sanctity', 'Banish all other cards you control and in your hand (min.1 from each); draw until you have 2 cards in your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87910978,3,0,0,2,0,0,0,0,0,4096);
INSERT OR REPLACE INTO "texts" VALUES (87910978, 'Brain Control', 'Pay 800 Life Points. Select 1 face-up monster your opponent controls. Take control of it until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98792570,3,0,0,2,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (98792570, 'Gift of the Martyr', 'Send 1 monster on your side of the field to the Graveyard. Select 1 monster on your side of the field. The selected monster gains ATK equal to the ATK of the sent monster until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34187685,3,0,0,2,0,0,0,0,0,32768);
INSERT OR REPLACE INTO "texts" VALUES (34187685, 'Double Attack', 'Discard 1 Monster Card from your hand to the Graveyard. Select 1 monster on your side of the field with a lower Level than the discarded monster. The selected monster can attack twice this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61181383,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (61181383, 'Battery Charger', 'Pay 500 Life Points. Special Summon 1 "Batteryman" monster from your Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97570038,3,0,0,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (97570038, 'Kaminote Blow', 'Activate only if there is at least 1 face-up "Chu-Ske the Mouse Fighter", "Monk Fighter", or "Master Monk" on your side of the field. Destroy the monster(s) that battle with these monsters on your side of the field this turn, at the end of each Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23965037,3,0,0,130,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (23965037, 'Doriado''s Blessing', 'This card is used to Ritual Summon "Elemental Mistress Doriado". You must also Tribute monsters whose total Levels equal 3 or more from the field or your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60369732,3,0,0,130,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (60369732, 'Final Ritual of the Ancients', 'This card is used to Ritual Summon "Reshef the Dark Being". You must also Tribute monsters whose total Levels equal 8 or more from the field or your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96458440,3,0,0,262146,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (96458440, 'Legendary Black Belt', 'Equip only to "Chu-Ske the Mouse Fighter", "Monk Fighter", or "Master Monk". When the equipped monster destroys your opponent''s monster by battle and sends it to the Graveyard, inflict damage to your opponent equal to the DEF of the destroyed monster.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23842445,3,0,0,262146,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (23842445, 'Nitro Unit', 'Equip only to a monster on your opponent''s side of the field. When the equipped monster is destroyed by battle and sent to the Graveyard, inflict damage to your opponent equal to the ATK of the equipped monster.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59237154,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (59237154, 'Shifting Shadows', 'Once per turn, by paying 300 Life Points, rearrange the face-down Defense Position monsters on your side of the field, then return them in face-down Defense Position.', 'シャッフルして、再び裏側守備表示で並べ替える', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (96631852,3,0,0,131074,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (96631852, 'Impenetrable Formation', 'Select 1 monster on your side of the field to activate this card. While you have 2 or more monsters on your side of the field, and all monsters on your side of the field are in Defense Position, the selected monster gains 700 DEF. When the selected monster is removed from the field, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22020907,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (22020907, 'Hero Signal', 'When a monster you control is destroyed by battle and sent to the Graveyard: Special Summon 1 Level 4 or lower "Elemental HERO" monster from your hand or Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58015506,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (58015506, 'Pikeru''s Second Sight', 'Until your opponent''s second End Phase, your opponent shows you all the cards that they draw before adding them to their hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (85519211,3,0,0,4,0,0,0,0,0,4194306);
INSERT OR REPLACE INTO "texts" VALUES (85519211, 'Minefield Eruption', 'Inflict 1000 damage to your opponent for each face-up "Mine Golem" on your side of the field. After that, destroy all face-up "Mine Golem"(s) on your side of the field.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21908319,3,0,0,4,0,0,0,0,0,4194304);
INSERT OR REPLACE INTO "texts" VALUES (21908319, 'Kozaky''s Self-Destruct Button', 'Inflict 1000 damage to the player who destroyed this Set card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58392024,3,0,70,4,0,0,0,0,0,32);
INSERT OR REPLACE INTO "texts" VALUES (58392024, 'Mispolymerization', 'Activate only when a Fusion Monster is Special Summoned. Return all face-up Fusion Monsters to their respective Fusion Decks.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84397023,3,0,0,4,0,0,0,0,0,134217728);
INSERT OR REPLACE INTO "texts" VALUES (84397023, 'Level Conversion Lab', 'Select 1 monster in your hand and show it to your opponent, then roll a six-sided die. If the result is 1, send the selected monster to the Graveyard. If the result is 2-6, the Level of the selected monster becomes equal to the result until the end of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (20781762,3,0,0,4,0,0,0,0,0,4194312);
INSERT OR REPLACE INTO "texts" VALUES (20781762, 'Rock Bombardment', 'Select 1 Rock-Type monster in your Deck and send it to the Graveyard. Inflict 500 damage to your opponent. Then shuffle the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57270476,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (57270476, 'Grave Lure', 'Turn the top card of your opponent''s Deck face-up, then your opponent shuffles their Deck. When your opponent draws the face-up card, immediately send it to the Graveyard.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83675475,3,0,0,4,0,0,0,0,0,4718594);
INSERT OR REPLACE INTO "texts" VALUES (83675475, 'Token Feastevil', 'Activate only when a Token(s) is Special Summoned. Destroy all Tokens on the field, and inflict 300 damage to your opponent for each destroyed Token.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10069180,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (10069180, 'Spell-Stopping Statute', 'Activate only when your opponent activates a Continuous Spell Card. Negate the activation and the effect of the card and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56058888,3,0,0,1048580,0,0,0,0,0,-2147483647);
INSERT OR REPLACE INTO "texts" VALUES (56058888, 'Royal Surrender', 'Activate only when your opponent activates a Continuous Trap Card. Negate the activation and the effect of the card and destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82452993,3,0,0,131076,0,0,0,0,0,33554432);
INSERT OR REPLACE INTO "texts" VALUES (82452993, 'Lone Wolf', 'Activate only if the 1 and only monster on your side of the field is "Chu-Ske the Mouse Fighter", "Monk Fighter", or "Master Monk". That monster cannot be destroyed as a result of battle, and is unaffected by any of your opponent''s monster effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
