BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (8124921,3,0,64,17,200,300,1,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (8124921, 'Right Leg of the Forbidden One', 'A forbidden right leg sealed by magic. Whosoever breaks this seal will know infinite power.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44519536,3,0,64,17,200,300,1,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (44519536, 'Left Leg of the Forbidden One', 'A forbidden left leg sealed by magic. Whosoever breaks this seal will know infinite power.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7902349,3,0,64,17,200,300,1,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (7902349, 'Left Arm of the Forbidden One', 'A forbidden left arm sealed by magic. Whosoever breaks this seal will know infinite power.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70903634,3,0,64,17,200,300,1,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (70903634, 'Right Arm of the Forbidden One', 'A forbidden right arm sealed by magic. Whosoever breaks this seal will know infinite power.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
