BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (30741334,3,0,0,8388641,2800,2000,8,1,4,4194560);
INSERT OR REPLACE INTO "texts" VALUES (30741334, 'Coach King Giantrainer', '3 Level 8 monsters
You can detach 1 Xyz Material from this card; draw 1 card and reveal it, then if it was a monster, inflict 800 damage to your opponent. You cannot conduct your Battle Phase the turn you activate this effect. You can use the effect of "Coach King Giantrainer" up to thrice per turn.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67136033,3,0,0,33,2600,2700,8,32768,4,1073741824);
INSERT OR REPLACE INTO "texts" VALUES (67136033, 'Coach Captain Bearman', 'You can Normal Summon this card without Tributing, but its original ATK becomes 1300. Once per turn: You can make all Level 4 Beast-Warrior-Type monsters you currently control become Level 8 until the End Phase. This card cannot be used as an Xyz Material for an Xyz Summon, except for the Xyz Summon of a FIRE Warrior-Type monster.', '不用解放作召唤', '等级变化', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3534077,3,0,0,33,1600,1200,4,32768,4,262144);
INSERT OR REPLACE INTO "texts" VALUES (3534077, 'Coach Soldier Wolfbark', 'You can target 1 Level 4 FIRE Beast-Warrior-Type monster in your Graveyard; Special Summon it in face-up Defense Position. Its effects are negated. You can only use the effect of "Coach Soldier Wolfbark" once per turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30929786,3,0,121,33,1500,100,3,32768,4,512);
INSERT OR REPLACE INTO "texts" VALUES (30929786, 'Brotherhood of the Fire Fist - Rooster', 'When this card is Special Summoned by the effect of a "Fire Fist" monster: You can add 1 "Fire Fist" monster from your Deck to your hand. You can only use this effect of "Brotherhood of the Fire Fist - Rooster" once per turn. Once per turn: You can send 1 face-up "Fire Formation" Spell/Trap Card you control to the Graveyard; Set 1 "Fire Formation" Spell/Trap Card directly from your Deck.', 'Search card group', 'Set', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (66413481,3,0,8458369,33,1800,200,4,32768,4,262147);
INSERT OR REPLACE INTO "texts" VALUES (66413481, 'Fire King Avatar Yaksha', 'If a face-up "Fire King" monster you control is destroyed by a card effect (except during the Damage Step): You can Special Summon this card from your hand. If this card is destroyed and sent to the Graveyard: You can destroy 1 card in your hand or that you control. You can only use this effect of "Fire King Avatar Yaksha" once per turn.', 'Special Summon', '破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
