BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (37195861,3,0,12296,33,1500,1200,4,1,2,1040);
INSERT OR REPLACE INTO "texts" VALUES (37195861, 'Elemental HERO Ocean', 'Once per turn, during your Standby Phase: You can target 1 "HERO" monster you control or in your Graveyard; return that target to the hand.', 'Return "HERO" monster', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8483333,3,0,0,33,2800,2500,8,16384,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (8483333, 'Mosaic Manticore', 'During the Standby Phase of your next turn after you Tribute Summoned this face-up card on the field: Special Summon, from the Graveyard, as many monster(s) as possible that were used for its Tribute Summon. They cannot declare an attack, and their effects are negated.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13893596,3,0,0,33,-2,0,10,2,32,270344);
INSERT OR REPLACE INTO "texts" VALUES (13893596, 'Exodius the Ultimate Forbidden Lord', 'Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by shuffling all monsters in your Graveyard into the Deck, and cannot be Special Summoned by other ways. When this card declares an attack: Send 1 monster from your hand or Deck to the Graveyard. This card gains 1000 ATK for each Normal Monster in your Graveyard. If this face-up card would leave the field, banish it instead. If there are 5 different "Forbidden One" cards in your Graveyard that were sent there by this card''s effect, you win the Duel.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21672573,3,0,0,33,1300,2200,4,8,16,32);
INSERT OR REPLACE INTO "texts" VALUES (21672573, 'Emperor Sem', 'Each time you Tribute Summon a monster, each player can select 1 card from their Graveyard and return it to the top of their Deck.', 'Return to deck', 'Do you want to select 1 card from your Graveyard and return it to the top of your Deck?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (70902743,3,0,69,8225,3000,2000,8,8192,32,2);
INSERT OR REPLACE INTO "texts" VALUES (70902743, 'Red Dragon Archfiend', '1 Tuner + 1 or more non-Tuner monsters
After damage calculation, when this card attacks a Defense Position monster your opponent controls: Destroy all Defense Position monsters your opponent controls. During your End Phase: Destroy all other monsters you control that did not declare an attack this turn. This card must remain face-up on the field to activate and to resolve this effect.', '守备怪物全部破坏', '未攻击的怪物全部破坏', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (75162696,3,0,0,33,1800,1500,4,4,16,1376256);
INSERT OR REPLACE INTO "texts" VALUES (75162696, 'Victoria', 'Once per turn, you can select 1 Dragon-Type monster from your opponent''s Graveyard, and Special Summon to your side of the field. Your opponent cannot select another face-up Fairy-Type monster as an attack target.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46986414,3,0,162,17,2500,2100,7,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (46986414, 'Dark Magician', 'The ultimate wizard in terms of attack and defense.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95453143,3,0,0,8225,3000,2500,8,8192,32,2097668);
INSERT OR REPLACE INTO "texts" VALUES (95453143, 'Hundred Eyes Dragon', '1 DARK Tuner + 1 or more non-Tuner Fiend-Type monsters
Once per turn, you can activate this card''s effect by removing from play 1 Level 6 or lower DARK Effect Monster from your Graveyard. Until the End Phase, treat this card''s name as that monster''s name and this card gains the same effects as that monster while face-up on the field. When this card is destroyed and sent to the Graveyard, add 1 "Earthbound Immortal" monster from your Deck to your hand.', '获得怪物效果', '从自己卡组把1只名字带有「地缚神」的怪兽加入手卡', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9433350,3,0,35,33,3000,2500,8,8192,32,327680);
INSERT OR REPLACE INTO "texts" VALUES (9433350, 'Malefic Blue-Eyes White Dragon', 'This card cannot be Normal Summoned or Set. This card can only be Special Summoned by removing from play 1 "Blue-Eyes White Dragon" from your Deck. There can only be 1 face-up "Malefic" monster on the field. Other monsters you control cannot declare an attack. If there is no face-up Field Spell Card on the field, destroy this card.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (68140974,3,0,12307,33,2500,2500,1,32,32,-1610272767);
INSERT OR REPLACE INTO "texts" VALUES (68140974, 'Meklord Emperor Wisel', 'Cannot be Normal Summoned/Set. Must be Special Summoned by its own effect, and cannot be Special Summoned by other ways. When a face-up monster you control is destroyed by a card effect and sent to the Graveyard: You can Special Summon this card from your hand. Other monsters you control cannot declare an attack. Once per turn: You can target 1 face-up Synchro Monster your opponent controls; equip that target to this card. This card gains ATK equal to those equipped monsters'' combined ATK. Once per turn, during either player''s turn, when an opponent''s Spell Card is activated: You can negate the activation, and if you do, destroy it.', 'Special Summon', 'Equip Synchro monster', 'Negate and destroy Spell Card', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90953320,3,0,39,8225,2400,1800,5,2,32,256);
INSERT OR REPLACE INTO "texts" VALUES (90953320, 'T.G. Hyper Librarian', '1 Tuner + 1 or more non-Tuner monsters
While this card is face-up on the field, each time a Synchro Monster(s) is Synchro Summoned, draw 1 card for each.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55935416,3,0,72,8388641,500,600,1,16384,16,288);
INSERT OR REPLACE INTO "texts" VALUES (55935416, 'Number 56: Gold Rat', '3 Level 1 monsters
Once per turn: You can detach 1 Xyz Material from this card; draw 1 card, then shuffle 1 card from your hand into the Deck.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1662004,3,0,121,4129,500,200,3,32768,4,537198592);
INSERT OR REPLACE INTO "texts" VALUES (1662004, 'Brotherhood of the Fire Fist - Spirit', 'Cannot be used as a Synchro Material Monster, except for the Synchro Summon of a Beast-Warrior-Type monster. When this card is Normal Summoned: You can target 1 Level 3 FIRE monster with 200 or less DEF in your Graveyard; Special Summon that target in face-up Defense Position. If you do, you can only attack with Beast-Warrior-Type monsters for the rest of this turn. You can only use the effect of "Brotherhood of the Fire Fist - Spirit" once per turn.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57996334,3,0,130,33,1900,800,6,1,1,262144);
INSERT OR REPLACE INTO "texts" VALUES (57996334, 'Dododo Buster', 'If your opponent controls a monster and you control no monsters, you can Special Summon this card (from your hand). If Summoned this way, its Level becomes 4. When this card is Tribute Summoned: You can target 1 "Dododo" monster in your Graveyard; Special Summon that target in face-up Defense Position.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2648201,3,0,126,33,1000,1000,4,16384,16,0);
INSERT OR REPLACE INTO "texts" VALUES (2648201, 'ZW - Sleipnir Mail', 'You can target 1 "Utopia" monster you control; equip this monster from your hand or your side of the field to that target. It gains 1000 ATK. When this card you control is sent to your Graveyard because the equipped monster was destroyed by your opponent''s card (either by battle or card effect): You can target 1 "Utopia" monster in your Graveyard; Special Summon that target. You can only control 1 "ZW - Sleipnir Mail".', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93108839,3,0,72,8388641,1000,1000,4,128,4,0);
INSERT OR REPLACE INTO "texts" VALUES (93108839, 'Number 58: Burner Visor', '2 Level 4 monsters
Once per turn, you can either: Target 1 face-up Xyz Monster you control; equip this card to that target, OR: Unequip this card and Special Summon it in face-up Attack Position. The equipped monster can attack your opponent directly. When the equipped monster inflicts battle damage to your opponent: You can discard 1 card; inflict 500 damage to your opponent.', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (39153655,1,0,175,16777249,1800,600,101056516,8,32,0);
INSERT OR REPLACE INTO "texts" VALUES (39153655, 'D/D Cerberus', 'Pendulum Effect
Once per turn: You can target 1 "DD" monster you control; its Level becomes 4, and if it does, it gains 400 ATK and DEF. 

Monster Effect
When this card is Pendulum Summoned from your hand while you control a "DD" monster, except "DD Cerberus": You can target 1 Continuous Spell Card in your Graveyard; add it to your hand.', 'Add 1 Continuous Spell Card to hand from Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97007933,1,0,8214,8225,2200,1600,6,32,8,0);
INSERT OR REPLACE INTO "texts" VALUES (97007933, 'Hyperspeedroid Dharma', '1 Tuner + 1 or more non-Tuner monsters
If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. You can only use each of these effects of "High Speed Roid Magical Sword Dharma" once per turn.
● You can banish 1 Machine-Type monster from your Graveyard; inflict 500 damage to your opponent.
● If this card is in the Graveyard and you control no cards: You can Special Summon this card. You cannot Normal Summon/Set during the turn you activate this effect.', 'You can banish 1 Machine-Type monster from your Graveyard; inflict 500 damage to your opponent.', 'Special Summon this card', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
