BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (24861088,3,0,112,33,1800,1500,4,32,16,0);
INSERT OR REPLACE INTO "texts" VALUES (24861088, 'Chronomaly Nebra Disk', ' When this card is Normal Summoned: You can add 1 "Chronomaly" card from your Deck to your hand, except "Chronomaly Nebra Disk". If this card is in your Graveyard and all face-up monsters you control are "Chronomaly" monsters (min. 1): You can Special Summon this card from your Graveyard in face-up Defense Position. You cannot use card effects the turn you activate this effect, except "Chronomaly" card effects. You can only use 1 "Chronomaly Nebra Disk" effect per turn, and only once that turn.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50260683,3,0,4718704,8388641,2000,2500,4,32,16,0);
INSERT OR REPLACE INTO "texts" VALUES (50260683, 'Number 36: Chronomaly Chateau Huyuk', '2 Level 4 "Chronomaly" monsters
Once per turn, during either player''s turn: You can detach 1 Xyz Material from this card, then target 1 face-up monster your opponent controls; that monster''s ATK becomes 0 until the end of this turn. You can Tribute 1 "Chronomaly" monster, then target 1 monster your opponent controls whose current ATK is different from its original ATK; destroy that target.', 'Attack to 0?', 'Destroy a monster?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (87255382,3,0,118,33,1700,1100,4,8192,8,0);
INSERT OR REPLACE INTO "texts" VALUES (87255382, 'Heraldic Beast Amphisbaena', ' You can discard 1 other "Heraldic Beast" monster; Special Summon this card from your hand. Once per turn: You can discard 1 "Heraldic Beast" monster; this card gains 800 ATK until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (23649496,3,0,4718592,8388641,2200,2200,4,1048576,16,0);
INSERT OR REPLACE INTO "texts" VALUES (23649496, 'Number 18: Heraldry Patriarch', '2 Level 4 monsters
During either player''s turn, if there are 2 or more monsters on the field with the same name: You can detach 1 Xyz Material from this card, then target 1 of those monsters; destroy all other monsters on the field with the same name as that target. While this card is face-up on the field, your opponent cannot Summon another monster with the same name as that target. If this card is sent to the Graveyard: You can send 2 "Heraldic Beast" monsters from your Deck to the Graveyard', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59048135,3,0,146,524290,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (59048135, 'Augmented Heraldry', 'Psychic-Type Xyz Monsters on the field cannot be targeted by Spell/Trap effects. Once per turn: You can discard 1 "Heraldic Beast" monster; add 1 "Heraldry" Spell/Trap Card from your Deck to your hand, except "Heraldry Augmentation". You cannot Normal or Special Summon any monsters during the turn you activate this effect, except Psychic-Type Xyz Monsters and "Heraldic Beast" monsters.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (387282,3,0,84,33,200,800,2,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (387282, 'Gagaga Sister', 'When this card is Normal Summoned: You can add 1 "Gagaga" Spell/Trap Card from your Deck to your hand. You can target 1 other "Gagaga" monster you control; the Levels of both that monster and this card become the combined current Levels of those 2 monsters, until the End Phase. You can only use this effect of "Gagaga Sister" once per turn.', 'Add 1 "Gagaga" Spell/Trap Card from your Deck to your hand?', 'Activate Effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46871387,3,0,4718681,8388641,2400,1200,4,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (46871387, 'Number 55: Gogogo Goliath', '2 Level 4 monsters
You can detach 1 Xyz Material from this card, then target 1 Level 4 EARTH Rock-Type monster in your Graveyard; add that target to your hand. You can only use the effect of "Number 55: Gogogo Goliath" once per turn. All monsters you control gain 800 DEF.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73866096,3,0,130,2,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (73866096, 'Dodododraw', 'Send 1 "Dododo" monster from your hand or face-up from your Monster Card Zone to the Graveyard; draw 2 cards. You can only activate 1 "Dodododraw" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9260791,3,0,4219,33,300,250,1,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (9260791, 'Galaxy-Eyes Cloudragon', 'You can Tribute this card; Special Summon 1 "Galaxy-Eyes" monster from your hand or Graveyard, except "Galaxy-Eyes Cloud Dragon". You can only use this effect of "Galaxy-Eyes Cloud Dragon" once per turn. If this card is in your Graveyard: You can target 1 "Galaxy-Eyes" Xyz Monster you control; attach this card from your Graveyard to that monster as an Xyz Material. You can only use this effect of "Galaxy-Eyes Cloud Dragon" once per Duel.', 'Target 1 "Galaxy-Eyes" Xyz Monster you control', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (46659709,3,0,123,33,2000,0,5,32,16,0);
INSERT OR REPLACE INTO "texts" VALUES (46659709, 'Galaxy Soldier', 'You can send 1 other LIGHT monster from your hand to the Graveyard; Special Summon this card from your hand in face-up Defense Position. When this card is Special Summoned: You can add 1 "Galaxy" monster from your Deck to your hand. You can only use this effect of "Galaxy Soldier" once per turn.', 'Add 1 "Galaxy" monster from your Deck to your hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (72044448,3,0,85,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (72044448, 'Photon Stream of Destruction', 'If you control a "Galaxy-Eyes" monster: Target 1 card on the field; banish that target. If you do not control "Galaxy-Eyes Photon Dragon", you can only activate this card during your turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8038143,3,0,0,1048580,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (8038143, 'Tachyon Transmigration', 'If you control a "Galaxy-Eyes" monster: Negate the activations of your opponent''s Spell Cards, Trap Cards, and monster effects that are in the same Chain as this card, and if you do, shuffle all of those negated cards on the field into the Deck. If you control a "Galaxy-Eyes Tachyon Dragon" monster, you can activate this card from your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35537251,3,0,132,33,1800,1400,4,1,4,0);
INSERT OR REPLACE INTO "texts" VALUES (35537251, 'Battlin'' Boxer Shadow', 'You can detach 1 Xyz Material from a "Battlin'' Boxer" Xyz Monster you control; Special Summon this card from your hand. You can only use the effect of "Battlin'' Boxer Shadow" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71921856,3,0,8650824,8388641,2300,1600,4,1,4,0);
INSERT OR REPLACE INTO "texts" VALUES (71921856, 'Number 79: Battlin'' Boxer Nova Kaiser', '2 Level 4 monsters
Once per turn: You can attach 1 "Battlin'' Boxer" monster from your hand or Graveyard to this card as an Xyz Material. This card gains 100 ATK for each Xyz Material attached to it. When this card is destroyed by your opponent''s card (either by battle or by card effect) and sent to your Graveyard: You can target Level 4 or lower "Battlin'' Boxer" monsters in your Graveyard, up to the number of Xyz Materials this card had on the field; Special Summon those targets.', 'Activate effect?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (8316565,3,0,0,1048580,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (8316565, 'Jolt Counter', 'During the Battle Phase, when a Spell Card, Trap Card, or monster effect is activated, while you control a "Battlin'' Boxer" monster: Negate the activation, and if you do, destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65848811,3,0,275710063,33,1800,200,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (65848811, 'Heroic Challenger - Assault Halberd', 'If your opponent controls a monster and you control no monsters, you can Special Summon this card (from your hand). If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. When this card inflicts battle damage to your opponent: You can add 1 "Heroic" card from your Deck to your hand.', 'Add 1 "Heroic" card from your Deck to your hand?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (1833916,3,0,275710063,33,1300,1100,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (1833916, 'Heroic Challenger - Thousand Blades', 'Once per turn: You can discard 1 "Heroic" card; Special Summon 1 "Heroic" monster from your Deck, and if you do, change this card to Defense Position. If you activate this effect, you cannot Special Summon any monsters for the rest of this turn, except "Heroic" monsters. When you take damage from an attack or a card effect while this card is in your Graveyard: You can Special Summon this card from the Graveyard in face-up Attack Position. You can only use this effect of "Heroic Challenger - Thousand Blades" once per turn.', 'Special Summon this card from the Graveyard?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (38331564,3,0,134,33,1800,400,4,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (38331564, 'Star Seraph Scepter', 'When this card is Normal or Special Summoned: You can add 1 "Star Seraph" monster from your Deck to your hand, except "Star Seraph Scepter". An Xyz Monster that was Xyz Summoned using 3 or more monsters you control as Xyz Materials (including this card on the field) gains this effect.
● When this card is Xyz Summoned: Target 1 other card on the field; destroy that card, and if you do, draw 1 card.', 'Add 1 "Star Seraph" monster from your Deck to your hand?', 'Destroy a card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64726269,3,0,134,33,1500,900,4,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (64726269, 'Star Seraph Scale', 'When this card is Special Summoned: You can Special Summon 1 "Star Seraph" monster from your hand, then you can place 1 LIGHT monster from your Graveyard on the top of your Deck. An Xyz Monster that was Xyz Summoned using 3 or more monsters you control (including this card on the field) gains this effect.
● While this card has Xyz Material, each turn, the first time a monster(s) is Special Summoned from the hand, immediately draw 1 card.', 'Special Summon 1 "Star Seraph" monster from your hand?', 'Place 1 LIGHT monster from your Graveyard on the top of your Deck?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91110378,3,0,134,33,800,2000,4,4,16,0);
INSERT OR REPLACE INTO "texts" VALUES (91110378, 'Star Seraph Sovereign', 'This card cannot be used as an Xyz Material, except for the Xyz Summon of a monster that uses 3 or more monsters as Xyz Material for its Xyz Summon. If you Normal or Special Summon a "Star Seraph" monster(s): You can Special Summon this card from your hand, and if you do, draw 1 card, then, if it is a “Star Seraph” monster, you can Special Summon that monster from your hand.', 'Special Summon this card?', 'Special Summon this card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (37115973,3,0,0,33,1600,1400,4,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (37115973, 'Numeral Hunter', 'If this card is Summoned: Shuffle all "Number" Xyz Monsters on the field into the Extra Deck. Neither player can Special Summon "Number" Xyz Monsters, also this card cannot be destroyed by battle with, and is unaffected by the effects of, Xyz Monsters.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63504681,3,0,4718703,8388641,1500,1500,4,1,32,0);
INSERT OR REPLACE INTO "texts" VALUES (63504681, 'Number 86: Heroic Champion - Rhongomyniad', '2 or more (max. 5) Level 4 Warrior-Type monsters
During each of your opponent''s End Phases: Detach 1 Xyz Material from this card. This card gains effects based on the number of Xyz Materials attached to it.
● 1 or more: This card cannot be destroyed by battle.
● 2 or more: This card gains 1500 ATK and DEF.
● 3 or more: This card is unaffected by other card effects.
● 4 or more: Your opponent cannot Normal/Special Summon.
● 5 or more: Once per turn: You can destroy all cards your opponent controls.', 'This card cannot be destroyed by battle.', 'This card gains 1500 ATK and DEF.', 'This card is unaffected by other card effects.', 'Your opponent cannot Normal/Special Summon.', 'Once per turn: You can destroy all cards your opponent controls.', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90098780,3,0,109,8388641,1100,1800,3,8,2,0);
INSERT OR REPLACE INTO "texts" VALUES (90098780, 'Humhumming the Key Djinn', '2 Level 3 monsters
When this card is Special Summoned: You can target 1 "Djinn" Xyz Monster in your Graveyard; Special Summon that monster, then you can attach up to 2 cards from your hand to it as Xyz Materials. Once per turn, during your Main Phase 1: You can detach 1 Xyz Material from this card, then target 1 "Djinn" Xyz Monster you control; that monster can attack your opponent directly this turn.', 'Special Summon 1  "Djinn" Xyz Monster from the Graveyard?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26493435,3,0,0,524290,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (26493435, 'Onomatopia', 'Each time you Special Summon a "Utopia" monster, place 1 Feel the Flow Counter on this card. Monsters you control gain 200 ATK and DEF for each Feel the Flow Counter on this card. Once per turn: You can remove 2 Feel the Flow Counters from this card; Special Summon 1 "Zubaba", "Gagaga", "Gogogo", or "Dododo" monster from your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63881033,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (63881033, 'Marshalling Field', ' You cannot Special Summon monsters, except Machine-Type monsters. Once per turn: You can declare a Level from 5 to 9; all Level 5 or higher Machine-Type monsters you currently control become the declared Level. If a Machine-Type Xyz Monster you control would be destroyed, you can send this face-up card to the Graveyard instead. If this card is sent from the field to the Graveyard: You can add 1 "Rank-Up-Magic Argent Chaos Force" from your Deck or Graveyard to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (65305468,3,0,72,8388641,0,0,0,1,16,0);
INSERT OR REPLACE INTO "texts" VALUES (65305468, 'Number F0: Utopic Future', '2 non-"Number" Xyz Monsters with the same Rank
(This card is always treated as a Rank 1 monster.)
Cannot be destroyed by battle, also any battle damage either player takes from a battle involving this card becomes 0. At the end of the Damage Step, when this card battles an opponent''s monster: You can take control of that opponent''s monster until the end of the Battle Phase. If this face-up card would be destroyed by a card effect, you can detach 1 Xyz Material from this card instead.', 'Take control of opponent''s monster?', 'Avoid Destruction? ', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91499077,3,0,84,8388641,1900,1600,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (91499077, 'Gagaga Samurai', '2 Level 4 monsters
Once per turn: You can detach 1 Xyz Material from this card, then target 1 "Gagaga" monster you control; this turn, that target can make a second attack during each Battle Phase. When another monster is targeted for an attack: You can change this card to Defense Position, then change the attack target to this card, and you proceed to damage calculation.', 'Activate Effect? ', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (28884172,3,0,84,33,100,100,4,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (28884172, 'Gagaga Mancer', 'Once per turn: You can target 1 "Gagaga" monster in your Graveyard, except "Gagaga Mancer"; Special Summon it. If you activated this effect, you cannot Special Summon monsters for the rest of this turn, except "Gagaga" monsters. If this card as an Xyz Material is detached and sent to the Graveyard to activate an Xyz Monster''s effect: You can target 1 Xyz Monster you control; it gains 500 ATK until the end of this turn.', 'Choose a Xyz Monster to gain 500 ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (64283880,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (64283880, 'Guard Go!', 'If a face-up "Gagaga", "Gogogo", or "Dododo" monster(s) you control is destroyed by battle or by card effect and sent to your Graveyard: Target 1 of those monsters; Special Summon it, then you can Special Summon up to 2 "Gagaga", "Dododo", and/or "Gogogo" monsters from your hand in Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (91677585,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (91677585, 'Hi-Five the Sky', 'During your Battle Phase: Target 1 face-up Xyz Monster that has already attacked; it can make a second attack during this Battle Phase, and if it does, your opponent cannot activate cards or effects until the end of the Damage Step.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (27062594,3,0,0,131076,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (27062594, 'The Door of Destiny', 'When an opponent''s monster declares a direct attack: Negate the attack, and if you do, Special Summon this card as an Effect Monster (Fiend-Type/LIGHT/Level 1/ATK 0/DEF 0). (This card is also still a Trap Card.) During each of your Standby Phases, if Summoned this way: You can banish any number of "Utopia" monsters with different names from your Graveyard, and if you do, inflict 500 damage to your opponent for each monster banished by this effect, and if you do that, this card gains ATK equal to the damage inflicted.', 'Banish "Utopia" monsters ', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63060238,3,0,12296,33,1200,1800,4,1,4,0);
INSERT OR REPLACE INTO "texts" VALUES (63060238, 'Elemental HERO Blazeman', 'If this card is Normal or Special Summoned: You can add 1 "Polymerization" from your Deck to your hand. You can send 1 "Elemental HERO" monster from your Deck to the Graveyard, except "Elemental HERO Blazeman"; this card''s Attribute, ATK, and DEF becomes the Attribute, ATK, and DEF of the monster sent to the Graveyard by this effect, until the end of this turn. If you activated this effect, you cannot Special Summon monsters for the rest of this turn, except Fusion Monsters. You can only use 1 "Elemental HERO Blazeman" effect per turn, and only once that turn.', 'Add 1 "Polymerization" from your Deck', 'Send 1 "Elemental HERO" monster from your Deck to the Graveyard', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90555947,3,0,16842794,97,3200,2100,10,256,1,0);
INSERT OR REPLACE INTO "texts" VALUES (90555947, 'Naturia Gaiastrio', '2 EARTH Synchro Monsters
During either player''s turn, when a card or effect that targets exactly 1 card on the field (and no other cards) is activated: You can send 1 card from the hand to the Graveyard; negate the activation, and if you do, destroy it.', 'Negate effect? ', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26949946,3,0,4123,8225,2700,2000,9,32,8,0);
INSERT OR REPLACE INTO "texts" VALUES (26949946, 'Mecha Phantom Beast Jaculuslan', '1 "Mecha Phantom Beast" Tuner + 1 or more non-Tuner "Mecha Phantom Beast" monsters
When this card is Synchro Summoned: You can Tribute any number of "Mecha Phantom Beast Tokens"; discard an equal number of random cards from your opponent''s hand. Other "Mecha Phantom Beast" monsters you control cannot be destroyed by battle or by card effects. If this card in your possession is destroyed by your opponent''s card (either by battle or by card effect): You can Set 1 Quick-Play Spell Card directly from your Deck.', 'Tribute "Mecha Phantom Beast Tokens"?', 'Set 1 Quick-Play Spell Card from Deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (53334641,3,0,141,8388641,2000,2500,4,4,32,0);
INSERT OR REPLACE INTO "texts" VALUES (53334641, 'Ghostrick Angel of Mischief', '2 Level 4 monsters
You can also Xyz Summon this card by using a "Ghostrick" Xyz Monster you control as the Xyz Material, except "Ghostrick Spoiled Angel". (Xyz Materials attached to that monster also become Xyz Materials on this card.) When this card has 10 Xyz Materials attached to it, you win the Duel. Once per turn: You can detach 1 Xyz Material from this card; add 1 "Ghostrick" Spell/Trap Card from your Deck to your hand. Once per turn: You can attach 1 "Ghostrick" card from your hand to this card as an Xyz Material.', '           ', 'Add 1 "Ghostrick" Spell/Trap Card from Deck to your hand.', 'Attach 1 "Ghostrick" card from hand.', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45010690,3,0,0,33,1500,800,3,1024,1,0);
INSERT OR REPLACE INTO "texts" VALUES (45010690, 'Flowerbot', 'When this card is sent to the Graveyard: Draw 1 card, then place 1 card from your hand on the top of your Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (71415349,3,0,0,33,1400,0,3,16,32,0);
INSERT OR REPLACE INTO "texts" VALUES (71415349, 'Humpty Grumpty', 'Once per turn: You can change this card to face-down Defense Position. When this card is Flip Summoned: This card gains 800 ATK until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34898052,3,0,0,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (34898052, 'Dragoroar', 'Banish 1 EARTH, 1 WATER, 1 FIRE, and 1 WIND monster from your Graveyard; shuffle 1 card on the field into the Deck.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (10282757,3,0,0,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (10282757, 'Planckton', 'During this turn, apply these effects.
● Rank 3 or lower Xyz Monsters gain 500 ATK and DEF.
● Rank 4 or higher Xyz Monsters cannot attack.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54629413,3,0,0,4129,1600,200,4,8,4,0);
INSERT OR REPLACE INTO "texts" VALUES (54629413, 'Guerrilla Kite', 'When this card is sent from the field to the Graveyard: Inflict 500 damage to your opponent. You can only use this effect of "Guerillakite" once per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (81028112,3,0,0,33,1500,300,3,1048576,16,0);
INSERT OR REPLACE INTO "texts" VALUES (81028112, 'Wattsychic Fighter', 'When this card is Normal or Special Summoned: You can target 1 card in your opponent''s Graveyard; place that target to either the top or bottom of the Deck. You can only use this effect of "Wattchic Fighter" once per turn.', 'Activate Effect?', 'Top', 'Bottom', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (54407825,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (54407825, 'Earthshattering Event', 'When a card(s) is sent from your Deck or your opponent''s Deck to the Graveyard: Target 1 card in either Graveyard; shuffle that target into the Deck, also neither player can send cards from their Deck to the Graveyard for the rest of this turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (80802524,3,0,141,4,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (80802524, 'Ghostrick Break', 'When exactly 1 "Ghostrick" monster you control is destroyed by your opponent''s card (either by battle or by card effect) and sent to the Graveyard: Target 2 "Ghostrick" monsters in your Graveyard with a different name than the destroyed monster; Special Summon them in face-down Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13760677,3,0,0,16777249,1800,0,84213764,16,32,0);
INSERT OR REPLACE INTO "texts" VALUES (13760677, 'P.M. Captor', 'Pendulum Effect
When you Pendulum Summon a Zombie-Type monster(s): You can activate this effect; this turn, they cannot be destroyed by battle or by card effects. 

Monster Effect
When this card destroys an opponent''s monster by battle: You can target 1 Pendulum Monster in your Graveyard; add it to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50155385,3,0,0,33,200,2000,4,512,8,0);
INSERT OR REPLACE INTO "texts" VALUES (50155385, 'Spiritual Whisper', 'Once per turn, this card cannot be destroyed by battle. When this card is Pendulum Summoned: You can add 1 Ritual Monster or 1 Ritual Spell Card from your Deck to your hand.', 'Add 1 Ritual Monster or 1 Ritual Spell Card to hand from deck', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86559484,3,0,115,33,1700,200,4,8192,4,0);
INSERT OR REPLACE INTO "texts" VALUES (86559484, 'Xyz-Raypierce', 'You can banish 1 Dragon-Type monster and 1 Wyrm-Type monster from your Graveyard; Special Summon 1 "Xyz-Ray Pierce" from your hand or Deck. When this card is sent from the field to the Graveyard: You can inflict 500 damage to your opponent. You can only use each effect of "Xyz-Ray Pierce" once per turn.', 'Inflict 500 damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34761062,3,0,0,2081,1800,200,4,16,4,0);
INSERT OR REPLACE INTO "texts" VALUES (34761062, 'Heavy Knight of the Flame', 'This card is treated as a Normal Monster while face-up on the field or in the Graveyard. While this card is a Normal Monster on the field, you can Normal Summon it to have it become an Effect Monster with this effect.
● At the start of the Damage Step, if this card attacks a Special Summoned monster: You can banish that monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61156777,3,0,0,33,1800,1000,4,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (61156777, 'BOXer', 'When this card destroys an opponent''s monster by battle and sends it to the Graveyard: You can place 1 counter on this card. You can send this card with 2 or more counters to the Graveyard; Special Summon 1 EARTH monster from your Deck. If this card would be destroyed by battle or card effect, you can remove 1 counter from this card instead.', 'Remove a counter? ', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (7541475,3,0,0,33,2300,2100,6,8192,16,0);
INSERT OR REPLACE INTO "texts" VALUES (7541475, 'Kabuki Dragon', 'Once per turn, if a monster you control attacks an opponent''s monster, before damage calculation: You can change the battle position of the attacked monster. Once per turn, if an opponent''s monster attacks a monster you control, before damage calculation: You can change the battle position of the attacked monster.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60434189,3,0,0,65538,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (60434189, 'Pendulum Impenetrable', 'This turn, cards in the Pendulum Zones cannot be destroyed by your opponent''s card effects, also when any opponent''s card effect resolves that targeted a card(s) in the Pendulum Zones at activation, negate that effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (0,0,0,0,0,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
