BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (38999506,3,0,0,17,2900,2450,8,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (38999506, 'Cosmo Queen', 'Queen of the galaxies and mistress of the stars.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (14214060,3,0,0,17,2600,200,6,2,1,0);
INSERT OR REPLACE INTO "texts" VALUES (14214060, 'Trance the Magic Swordsman', 'A peculiar magician with considerable abilities. Supposedly, he''s just returned from a trip to outer space.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (50930991,3,0,0,17,1700,1000,4,2,16,0);
INSERT OR REPLACE INTO "texts" VALUES (50930991, 'Neo the Magic Swordsman', 'A dimensional drifter who not only practices sorcery, but is also a sword and martial arts master.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (15025844,3,0,0,17,800,2000,4,2,16,0);
INSERT OR REPLACE INTO "texts" VALUES (15025844, 'Mystical Elf', 'A delicate elf that lacks offense, but has a terrific defense backed by mystical power.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (44430454,3,0,61,17,200,2000,3,1,1,0);
INSERT OR REPLACE INTO "texts" VALUES (44430454, 'Chamberlain of the Six Samurai', 'The Six Samurai are supported from the shadows by this silent and mysterious warrior. His past is unknown to them, but his countless scars are proof of his experience.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94203886,3,0,84,33,800,1200,2,2,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (94203886, 'Gagaga Child', 'If you control a face-up "Gagaga" monster, except "Gagaga Kid", you can Special Summon this card (from your hand). When you do: You can target 1 face-up "Gagaga" monster you control; this card''s Level becomes the Level of that monster. You cannot conduct your Battle Phase the turn you activate this effect.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30608985,3,0,0,2097185,400,400,2,2,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (30608985, 'Magical Undertaker', 'FLIP: You can target 1 Level 4 or lower Spellcaster-Type monster in your Graveyard; Special Summon that target.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67692580,3,0,0,33,900,600,2,512,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (67692580, 'Caligo Claw Crow', 'If you control a DARK monster, you can Special Summon this card (from your hand). You can only Special Summon "Caligo Claw Crow" once per turn this way', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (26082117,3,0,84,33,1500,1000,4,2,32,0);
INSERT OR REPLACE INTO "texts" VALUES (26082117, 'Gagaga Magician', 'Once per turn: You can declare a Level from 1 to 8; this card becomes that Level until the End Phase. You can only control 1 "Gagaga Magician". This card cannot be used as a Synchro Material Monster.', 'Change level', 'Please select a Level from 1 to 8', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (3606728,3,0,84,33,1000,800,3,2,32,1073750016);
INSERT OR REPLACE INTO "texts" VALUES (3606728, 'Gagaga Girl', 'You can target 1 face-up "Gagaga Magician" you control; this card''s Level becomes the Level of that monster. An Xyz Monster that was Summoned using only this card and other "Gagaga" monsters as Xyz Material gains this effect,
 ● When it is Xyz Summoned: You can target 1 Special Summoned monster your opponent controls; its ATK becomes 0.', 'Change level', 'ATK becomes 0', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (12423762,3,0,84,33,1500,2000,4,1,1,17039360);
INSERT OR REPLACE INTO "texts" VALUES (12423762, 'Gagaga Gardna', 'When an opponent''s monster declares a direct attack: You can Special Summon this card from your hand. When this face-up card is targeted for an attack: You can discard 1 card; this card cannot be destroyed by that battle.', 'Special Summon', '不被战破', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97896503,3,0,143,33,1600,900,3,1,1,2);
INSERT OR REPLACE INTO "texts" VALUES (97896503, 'Zubaba Knight', 'At the start of the Damage Step, if this card attacks a face-up Defense Position monster: Destroy that monster.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (24291651,3,0,0,33,0,1800,4,1,16,2048);
INSERT OR REPLACE INTO "texts" VALUES (24291651, 'Ganbara Knight', 'When this face-up Attack Position card is targeted for an attack: You can change it to Defense Position.', 'Change to defense position', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98865920,3,0,0,33,1200,600,3,1,4,4194304);
INSERT OR REPLACE INTO "texts" VALUES (98865920, 'Achacha Archer', 'When this card is Normal or Flip Summoned: Inflict 500 damage to your opponent.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (25259669,3,0,172,33,1400,0,4,1,1,264192);
INSERT OR REPLACE INTO "texts" VALUES (25259669, 'Goblindbergh', 'When this card is Normal Summoned: You can Special Summon 1 Level 4 or lower monster from your hand, then change this card to Defense Position if you activated this effect.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94656263,3,0,0,33,1100,1500,4,524288,32,262144);
INSERT OR REPLACE INTO "texts" VALUES (94656263, 'Kagetokage', 'Cannot be Normal Summoned/Set. When you Normal Summon a Level 4 monster: You can Special Summon this card from your hand. This card cannot be used as a Synchro Material Monster.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86039057,3,0,0,33,1700,100,4,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (86039057, 'Tasuke Knight', 'When an opponent''s monster declares an attack, while you have no cards in your hand and this card is in your Graveyard: You can Special Summon this card from your Graveyard, then end the Battle Phase. You can only use the effect of "Tasuke Knight" once per Duel.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (76080032,3,0,126,33,1900,0,4,16384,16,-2147475456);
INSERT OR REPLACE INTO "texts" VALUES (76080032, 'ZW - Unicorn Spear', 'You can target 1 face-up "Number C39: Utopia Ray" you control; equip this card from your hand to that target. It gains 1900 ATK. If the equipped monster battles an opponent''s monster, the opponent''s monster''s effect is negated during the Battle Phase only. You can only control 1 face-up "ZW - Unicorn Spear".', 'Equip', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (2460565,3,0,0,33,1200,400,3,1,1,1376256);
INSERT OR REPLACE INTO "texts" VALUES (2460565, 'Marauding Captain', 'Your opponent cannot target face-up Warrior-Type monsters for attacks, except this one. When this card is Normal Summoned: You can Special Summon 1 Level 4 or lower monster from your hand.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (45141844,3,0,0,2097185,450,600,2,2,32,2);
INSERT OR REPLACE INTO "texts" VALUES (45141844, 'Old Vindictive Magician', 'FLIP: Target 1 monster your opponent controls; destroy that target.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (93087299,3,0,0,131074,0,0,0,0,0,0);
INSERT OR REPLACE INTO "texts" VALUES (93087299, 'Swords of Burning Light', 'If you control no monsters, monsters your opponent controls cannot declare an attack. If you control a monster or your opponent has 5 or more cards in their hand, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (22346472,3,0,0,2,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (22346472, 'Blustering Winds', 'Target 1 face-up monster you control; it gains 1000 ATK and DEF until your next Standby Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (67775894,3,0,0,262146,0,0,0,0,0,1057032);
INSERT OR REPLACE INTO "texts" VALUES (67775894, 'Wonder Wand', 'Equip only to a Spellcaster-Type monster. It gains 500 ATK. If you control the equipped monster and this card: You can send both to the Graveyard; draw 2 cards.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (94770493,3,0,0,65538,0,0,0,0,0,40960);
INSERT OR REPLACE INTO "texts" VALUES (94770493, 'Double or Nothing!', 'When a monster''s attack is negated: Target that monster; during this Battle Phase, it can attack again, and if it does, its ATK is doubled during the Damage Step only.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (73178098,3,0,0,65538,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (73178098, 'Ego Boost', 'When a monster declares an attack: Target 1 face-up monster on the field; it gains 1000 ATK until the end of the Battle Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (90673413,3,0,84,262146,0,0,0,0,0,8192);
INSERT OR REPLACE INTO "texts" VALUES (90673413, 'Gagagarevenge', 'Target 1 "Gagaga" monster in your Graveyard; Special Summon it and equip it with this card. When this card leaves the field, destroy the equipped monster. When this card is sent to the Graveyard because the equipped monster was used as an Xyz Material: All Xyz Monsters you currently control gain 300 ATK.', 'Gain ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (13032689,3,0,115,262146,0,0,0,0,0,1073750016);
INSERT OR REPLACE INTO "texts" VALUES (13032689, 'Xyz Unit', 'Equip only to an Xyz Monster. It gains ATK equal to its Rank × 200. If the equipped monster you control would detach its Xyz Material to activate its effect: You can detach this card as 1 of the Xyz Materials.', 'Activate effect of "Xyz Unit"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (403847,3,0,0,131074,0,0,0,0,0,1056768);
INSERT OR REPLACE INTO "texts" VALUES (403847, 'The A. Forces', 'All Warrior-Type monsters you control gain 200 ATK for each Warrior or Spellcaster-Type monster you control.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (32807846,3,0,0,2,0,0,0,0,0,1049088);
INSERT OR REPLACE INTO "texts" VALUES (32807846, 'Reinforcement of the Army', 'Add 1 Level 4 or lower Warrior-Type monster from your Deck to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (95281259,3,0,0,2,0,0,0,0,0,1049600);
INSERT OR REPLACE INTO "texts" VALUES (95281259, 'The Warrior Returning Alive', 'Target 1 Warrior-Type monster in your Graveyard; add that target to your hand.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (30585393,3,0,0,4,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (30585393, 'Puzzle Reborn', 'If exactly 1 monster you control is destroyed by a card effect: Target that monster; Special Summon it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18446701,3,0,84,4,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (18446701, 'Gagagashield', 'Target 1 face-up Spellcaster-Type monster you control; equip this card to that target. Twice per turn, it cannot be destroyed by battle or card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (21843307,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (21843307, 'Copy Knight', 'When a Level 4 or lower Warrior-Type monster is Normal Summoned to your side of the field: Special Summon this card as a Normal Monster Card with the same name and Level as the Normal Summoned monster (Warrior-Type/LIGHT/ATK 0/DEF 0). (This card is still treated as a Trap Card.)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (86778566,3,0,0,4,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (86778566, 'Impenetrable Attack', 'During the Battle Phase, activate 1 of these effects.
● Target 1 monster on the field; it cannot be destroyed by battle or by card effects during this Battle Phase.
● You take no battle damage during this Battle Phase.
', 'Target 1 monster; it cannot be destroyed during this Battle Phase.', 'During this Battle Phase, you take no Battle Damage.', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (59070329,3,0,0,4,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (59070329, 'Utopian Aura', 'Detach 1 Xyz Material you control; the face-up Xyz Monsters you control cannot be destroyed by card effects until the End Phase.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (58628539,3,0,115,4,0,0,0,0,0,3);
INSERT OR REPLACE INTO "texts" VALUES (58628539, 'Xyz Effect', 'When you Xyz Summon a monster: You can target 1 card on the field; destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29267084,3,0,0,131076,0,0,0,0,0,73728);
INSERT OR REPLACE INTO "texts" VALUES (29267084, 'Shadow Spell', 'Activate this card by targeting 1 face-up monster your opponent controls; it loses 700 ATK, also it cannot attack or change its battle position. When it leaves the field, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60082869,3,0,0,4,0,0,0,0,0,1);
INSERT OR REPLACE INTO "texts" VALUES (60082869, 'Dust Tornado', 'Target 1 Spell/Trap Card your opponent controls; destroy that target, then you can Set 1 Spell/Trap Card from your hand.', 'Set 1 Card?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97077563,3,0,0,131076,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (97077563, 'Call of the Haunted', 'Activate this card by targeting 1 monster in your Graveyard; Special Summon that target in Attack Position. When this card leaves the field, destroy that target. When that target is destroyed, destroy this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (77538567,3,0,0,1048580,0,0,0,0,0,-2147483391);
INSERT OR REPLACE INTO "texts" VALUES (77538567, 'Dark Bribe', 'When an opponent''s Spell/Trap Card is activated: Your opponent draws 1 card, also negate the Spell/Trap activation, and if you do, destroy it.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (84013237,3,0,8323144,8388641,2500,2000,4,1,16,65536);
INSERT OR REPLACE INTO "texts" VALUES (84013237, 'Number 39: Utopia', '2 Level 4 monsters
When any player''s monster declares an attack: You can detach 1 Xyz Material from this card; negate the attack. When this card is targeted for an attack, while it has no Xyz Materials: Destroy this card.', 'Negate attack', 'Self Destruct', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (56840427,3,0,8327240,8388641,2500,2000,4,1,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (56840427, 'Number C39: Utopia Ray', '3 Level 4 LIGHT monsters
You can also Xyz Summon this card by using a "Number 39: Utopia" you control as the Xyz Material. (Xyz Materials attached to that monster also become Xyz Materials on this card.) You can detach 1 Xyz Material from this card; it gains 500 ATK and 1 monster your opponent controls loses 1000 ATK, until the End Phase. You must have 1000 Life Points or less to activate and to resolve this effect.', 'Change ATK', 'Xyz summon by stacking on top of "Number 39: Utopia"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
