BEGIN TRANSACTION;
INSERT OR REPLACE INTO "datas" VALUES (83274244,3,0,130,33,2300,900,6,1,1,8192);
INSERT OR REPLACE INTO "texts" VALUES (83274244, 'Dododo Warrior', 'You can Normal Summon this card without Tributing, but its original ATK becomes 1800. If this card attacks, negate all card effects that activate in the opponent''s Graveyard, until the end of the Damage Step.', 'Normal Summon without Tributes', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (29669359,3,0,72,8388641,2500,1000,5,65536,4,4194306);
INSERT OR REPLACE INTO "texts" VALUES (29669359, 'Number 61: Volcasaurus', '2 Level 5 monsters
Once per turn: You can detach 1 Xyz Material from this card to target 1 face-up monster your opponent controls; destroy that opponent''s monster, and if you do, inflict damage to your opponent equal to the destroyed monster''s original ATK. This card cannot attack your opponent directly during the turn you activate this effect.', '破坏和伤害', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55067058,3,0,72,8388641,2000,2500,5,65536,2,1073741824);
INSERT OR REPLACE INTO "texts" VALUES (55067058, 'Number 19: Freezerdon', '2 Level 5 monsters
Once per turn, if an Xyz Monster you control would activate an effect by detaching an Xyz Material(s), you can detach 1 Xyz Material from this card instead of 1 of those Xyz Materials.', 'Activate efefct of "Number 19: Freezerdon"?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (82052602,3,0,84,65538,0,0,0,0,0,4456448);
INSERT OR REPLACE INTO "texts" VALUES (82052602, 'Gagagaback', 'During the turn a "Gagaga" monster you control was destroyed by battle and sent to the Graveyard: Special Summon as many monsters from your Graveyard as possible that were destroyed by battle this turn, in face-up Defense Position, then take 600 damage for each monster Special Summoned by this effect. You can only activate 1 "Gagagaback" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (18446701,3,0,84,4,0,0,0,0,0,16777216);
INSERT OR REPLACE INTO "texts" VALUES (18446701, 'Gagagashield', 'Target 1 face-up Spellcaster-Type monster you control; equip this card to that target. Twice per turn, it cannot be destroyed by battle or card effects.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (36834155,3,0,85,33,1000,1000,3,32,16,8192);
INSERT OR REPLACE INTO "texts" VALUES (36834155, 'Photon Pirate', 'You can banish 1 "Photon" monster from your Graveyard; this card gains 1000 ATK until the End Phase. You can use the effect of "Photon Pirate" up to twice per turn.', 'Increase ATK', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (63223260,3,0,85,33,0,0,1,32,16,0);
INSERT OR REPLACE INTO "texts" VALUES (63223260, 'Photon Satellite', 'Once per turn: You can target 1 other "Photon" monster you control; the Levels of both that monster and this card become the combined current Levels of those 2 monsters.', 'Level becomes equal to combined Levels', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (9718968,3,0,85,33,2100,1000,5,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (9718968, 'Photon Slasher', 'If a face-up Xyz Monster is on the field, you can Special Summon this card (from your hand) in face-up Defense Position.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35112613,3,0,85,33,300,200,1,8,16,16);
INSERT OR REPLACE INTO "texts" VALUES (35112613, 'Kuriphoton', 'During either player''s turn: You can send this card from your hand to the Graveyard and pay 2000 Life Points; you take no damage this turn. If this card is in your Graveyard: You can send 1 "Photon" monster from your hand to the Graveyard, except "Kuriphoton"; add this card from your Graveyard to your hand. You can only use this effect of "Kuriphoton" once per turn.', 'Take 0 damage', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (62107612,3,0,0,33,0,0,1,2,16,4194304);
INSERT OR REPLACE INTO "texts" VALUES (62107612, 'Dimension Wanderer', 'When a monster is banished by the effect of "Galaxy-Eyes Photon Dragon": You can send this card from your hand to the Graveyard; inflict 3000 damage to your opponent. You can only use the effect of "Dimension Wanderer" once per turn.', 'Inflict damage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (98555327,3,0,123,33,0,1800,4,2,16,512);
INSERT OR REPLACE INTO "texts" VALUES (98555327, 'Galaxy Wizard', 'Once per turn: You can increase this card''s Level by 4 until the End Phase. You can Tribute this card; add 1 "Galaxy" card from your Deck to your hand, except "Galaxy Wizard".', 'Increase level', 'Add to hand', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (35950025,3,0,123,33,2800,2600,8,1,16,270336);
INSERT OR REPLACE INTO "texts" VALUES (35950025, 'Galaxy Knight', 'If you control a "Photon" or "Galaxy" monster, you can Normal Summon this card without Tributing. When you do: Target 1 "Galaxy-Eyes Photon Dragon" in your Graveyard (if possible); regardless, this card loses 1000 ATK, and if it does, Special Summon that target (if any) in face-up Defense Position. This ATK decrease lasts until the End Phase.', 'Normal Summon without tribute', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (55935416,3,0,72,8388641,500,600,1,16384,16,288);
INSERT OR REPLACE INTO "texts" VALUES (55935416, 'Number 56: Gold Rat', '3 Level 1 monsters
Once per turn: You can detach 1 Xyz Material from this card; draw 1 card, then shuffle 1 card from your hand into the Deck.', 'Draw card', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (61344030,3,0,0,8388641,2000,1000,4,1,16,-2147475200);
INSERT OR REPLACE INTO "texts" VALUES (61344030, 'Starliege Paladynamo', '2 Level 4 LIGHT monsters
Once per turn: You can detach 2 Xyz Materials from this card to target 1 face-up monster your opponent controls; its ATK becomes 0, and if it does, its effects are negated. When this card you control is destroyed by your opponent''s card (either by battle or by card effect) and sent to your Graveyard: Draw 1 card.', 'ATK becomes 0 and negate effect', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97433739,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (97433739, 'Message in a Bottle', 'Target 3 monsters with different Levels in your Graveyard; Special Summon all 3 of them. Their ATK''s become 0, also their effects are negated. If you do not Xyz Summon this turn after Summoning those 3 monsters, you lose 4000 Life Points during the End Phase. You cannot Special Summon any other monsters, except by Xyz Summon, during the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34838437,3,0,0,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (34838437, 'Accellight', 'If you control no monsters: Special Summon 1 Level 4 or lower "Photon" or "Galaxy" monster from your Deck. You can only activate 1 "Accellight" per turn. You cannot Normal Summon/Set during the turn you activate this card.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (60222582,3,0,123,2,0,0,0,0,0,262144);
INSERT OR REPLACE INTO "texts" VALUES (60222582, 'Galaxy Expedition', 'If you control a Level 5 or higher "Photon" or "Galaxy" monster: Special Summon 1 Level 5 or higher "Photon" or "Galaxy" monster from your Deck in face-up Defense Position. You can only activate 1 "Galaxy Expedition" per turn.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (97617181,3,0,123,262146,0,0,0,0,0,270336);
INSERT OR REPLACE INTO "texts" VALUES (97617181, 'Galaxy Zero', 'Target 1 "Photon" or "Galaxy" monster in your Graveyard; Special Summon it in face-up Attack Position and equip it with this card. It cannot attack or activate its effects. If it would be destroyed during the Battle Phase, you can destroy this card instead. When this card leaves the field: The equipped monster''s ATK becomes 0. You can only activate 1 "Galaxy Zero" per turn.', 'Use the effect of "Galaxy Zero" to avoid destruction?', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (34796454,3,0,0,33,100,100,1,1,16,262144);
INSERT OR REPLACE INTO "texts" VALUES (34796454, 'Triple Star Trion', 'During the End Phase, if this card is in the Graveyard because it was sent there this turn as a Tribute for a successful Tribute Summon: You can Special Summon this card from the Graveyard.', 'Special Summon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (57036718,3,0,143,33,1800,600,3,1,1,8194);
INSERT OR REPLACE INTO "texts" VALUES (57036718, 'Zubaba Buster', 'At the end of the Damage Step, if this card inflicts Battle Damage to your opponent: Destroy the face-up monster with the lowest ATK (if it''s a tie, you get to choose), and if you do, this card loses 800 ATK.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT OR REPLACE INTO "datas" VALUES (83021423,3,0,0,33,1200,1800,6,1,8,1);
INSERT OR REPLACE INTO "texts" VALUES (83021423, 'Chachaka Archer', 'Once per turn: You can target 1 Spell/Trap Card on the field; destroy it.', 'Destroy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
COMMIT;
